### ISSUE TITLE
build script does not seem to honour environment variables.

### ISSUE THREAD

**Issue by chris-stones** [pocoproject/poco#1000]
One would expect...
export CXX="distcc armv7l-unknown-linux-gnueabi-g++"
export CXXFLAGS="-marm -Os -mtune=cortext-a7 -mcpu=cortex-a7"
../configure
make -j4

to build using the given CXXFLAGS, using distcc.
the build/config scripts however overwrite theese environment variables.

workaround...

use the --cflags="" option in the configure script to add CXXFLAGS.
set the CROSS_COMPILE environment variable to "distcc   your-compiler-tripplet-"
Even when not cross-compiling.

IF not actually cross compiling, You also need to adjust the STRIP variable in build/config/Linux to "STRIP = strip"

Chris.

**Comment by zosrothko** [comment]
Hi

This is the current behavior. Environment variable like CXX, CXXFLAGS.. are never taken into account. Below a snippet from build/config/ Linux, all variable assignments are using the single assignement "=", not the additional assignement "+=". @obiltschnig should state if one could use or not the "+=" to meet your expectation.

#
# Define Tools
#
CC      = ${CROSS_COMPILE}gcc
CXX     = ${CROSS_COMPILE}g++
LINK    = $(CXX)
LIB     = ${CROSS_COMPILE}ar -cr
RANLIB  = ${CROSS_COMPILE}ranlib
SHLIB   = $(CXX) -shared -Wl,-soname,$(notdir $@) -o $@
SHLIBLN = $(POCO_BASE)/build/script/shlibln
STRIP   = ${CROSS_COMPILE}strip
DEP     = $(POCO_BASE)/build/script/makedepend.gcc 
SHELL   = sh
RM      = rm -rf
CP      = cp
MKDIR   = mkdir -p

#
# Extension for Shared Libraries
#
SHAREDLIBEXT     = .so.$(target_version)
SHAREDLIBLINKEXT = .so

#
# Compiler and Linker Flags
#
CFLAGS          = 
CFLAGS32        =
CFLAGS64        =
CXXFLAGS        = -Wall -Wno-sign-compare
CXXFLAGS32      =
CXXFLAGS64      =
LINKFLAGS       =
LINKFLAGS32     =
LINKFLAGS64     =
STATICOPT_CC    =
STATICOPT_CXX   =
STATICOPT_LINK  = -static
SHAREDOPT_CC    = -fPIC
SHAREDOPT_CXX   = -fPIC
SHAREDOPT_LINK  = -Wl,-rpath,$(LIBPATH)
DEBUGOPT_CC     = -g -D_DEBUG
DEBUGOPT_CXX    = -g -D_DEBUG
DEBUGOPT_LINK   = -g
RELEASEOPT_CC   = -O2 -DNDEBUG
RELEASEOPT_CXX  = -O2 -DNDEBUG
RELEASEOPT_LINK = -O2
