### ISSUE TITLE
ActiveDispatcher saves reference to event context after event was performed until it gets new event

### ISSUE THREAD

**Issue by voron86** [pocoproject/poco#1002]
ActiveDispatcher saves reference to event context after event was performed until it gets new event. So if I pass smart pointer as argument of ActiveMethod with ActiveDispatcher. I can't remove object until I call any ActiveMethod for the same ActiveDispatcher.

I fixed it in my local build:

void ActiveDispatcher::run()
{
	AutoPtr<Notification> pNf = _queue.waitDequeueNotification();
	while (pNf && !dynamic_cast<StopNotification*>(pNf.get()))
	{
                {
                    MethodNotification* pMethodNf = dynamic_cast<MethodNotification*>(pNf.get());
                    poco_check_ptr (pMethodNf);
                    ActiveRunnableBase::Ptr pRunnable = pMethodNf->runnable();
                    pRunnable->duplicate(); // run will release
                    pRunnable->run();
                    pNf = nullptr;
                }

		pNf = _queue.waitDequeueNotification();
	}
}

**Comment by macrule** [comment]
The patch by voron86 works. The committed fix however, leaves out the extra scope around the pRunnable AutoPtr. This causes the ActiveResult to not be released until the next ActiveMethod call.
