### ISSUE TITLE
--no-ipv6 is broken at-least on Armv7a ...

### ISSUE THREAD

**Issue by chris-stones** [pocoproject/poco#1003]
Under ARM Linux, when configureing with --prefix=/usr --no-ipv6 --no-samples 
The code succesfully compiles.
However, when issueing the 'sudo make install' command, everything is RE-COMPILED for some reason.

the re-compile fails.

*\* Compiling src/DNS.cpp (debug, shared)
distcc armv7l-unknown-linux-gnueabihf-g++  -Iinclude -I/home/alarm/work/poco-1.6.1/CppUnit/include -I/home/alarm/work/poco-1.6.1/CppUnit/WinTestRunner/include -I/home/alarm/work/poco-1.6.1/Foundation/include -I/home/alarm/work/poco-1.6.1/XML/include -I/home/alarm/work/poco-1.6.1/JSON/include -I/home/alarm/work/poco-1.6.1/Util/include -I/home/alarm/work/poco-1.6.1/Net/include -Wall -Wno-sign-compare -DPOCO_BUILD_HOST=alarm -DPOCO_NET_NO_IPv6 -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -DNet_EXPORTS -c src/DNS.cpp -o /home/alarm/work/poco-1.6.1/BADBUILD/Net/obj/Linux/armv7l/debug_shared/DNS.o
In file included from src/DNS.cpp:19:0:
include/Poco/Net/SocketAddress.h:166:26: error: 'IPv6SocketAddressImpl' is not a member of 'Poco::Net::Impl'
   AlignedCharArrayUnion Poco::Net::Impl::IPv6SocketAddressImpl
                          ^
include/Poco/Net/SocketAddress.h:166:26: error: 'IPv6SocketAddressImpl' is not a member of 'Poco::Net::Impl'
include/Poco/Net/SocketAddress.h:166:64: error: template argument 1 is invalid
   AlignedCharArrayUnion Poco::Net::Impl::IPv6SocketAddressImpl
                                                                ^
include/Poco/Net/SocketAddress.h: In member function 'Poco::Net::SocketAddress::Impl\* Poco::Net::SocketAddress::pImpl() const':
include/Poco/Net/SocketAddress.h:191:58: error: request for member 'buffer' in '((const Poco::Net::SocketAddress_)this)->Poco::Net::SocketAddress::_memory', which is of non-class type 'const int'
  return reinterpret_cast<Ptr>(const_cast<char *>(_memory.buffer));
                                                          ^
include/Poco/Net/SocketAddress.h: In member function 'void Poco::Net::SocketAddress::newIPv6(const sockaddr_in6_)':
include/Poco/Net/SocketAddress.h:233:18: error: expected type-specifier
  new (storage()) Poco::Net::Impl::IPv6SocketAddressImpl(sockAddr);
                  ^
include/Poco/Net/SocketAddress.h: In member function 'void Poco::Net::SocketAddress::newIPv6(const Poco::Net::IPAddress&, Poco::UInt16)':
include/Poco/Net/SocketAddress.h:243:18: error: expected type-specifier
  new (storage()) Poco::Net::Impl::IPv6SocketAddressImpl(hostAddress.addr(), htons(portNumber), hostAddress.scope()
                  ^
include/Poco/Net/SocketAddress.h: In member function 'char\* Poco::Net::SocketAddress::storage()':
include/Poco/Net/SocketAddress.h:259:17: error: request for member 'buffer' in '((Poco::Net::SocketAddress_)this)->Poco::Net::SocketAddress::_memory', which is of non-class type 'int'
  return _memory.buffer;
                 ^
distcc[7589] ERROR: compile src/DNS.cpp on localhost failed
/home/alarm/work/poco-1.6.1/build/rules/compile:53: recipe for target '/home/alarm/work/poco-1.6.1/BADBUILD/Net/obj/Linux/armv7l/debug_shared/DNS.o' failed
make[1]: *_\* [/home/alarm/work/poco-1.6.1/BADBUILD/Net/obj/Linux/armv7l/debug_shared/DNS.o] Error 1
make[1]: Leaving directory '/home/alarm/work/poco-1.6.1/Net'
Makefile:125: recipe for target 'Net-libexec' failed
make: **\* [Net-libexec] Error 2

Thanks.

**Comment by aleks-f** [comment]
see #1950
