### ISSUE TITLE
Data/SQLite:testIncrementVacuum blocked on Windows and fails on Linux/Cygwin

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#1004]
Hello

After an merge with the develop branch head, it seems that the unit test Data/SQLite/SQLiteTest::testIncrementVacuum fails both on Linux/Cgwin and also on Windows/VS2013.

****************************************
*** Cygwin i686 Data/SQLite
****************************************
testIncrementVacuum: FAILURE
!!!FAILURES!!!
Runs: 1   Failures: 1   Errors: 0
There was 1 failure:
 1: N7CppUnit10TestCallerI10SQLiteTestEE.testIncrementVacuum
    "pragma_mode==2"
    in "src/SQLiteTest.cpp", line 3461

On Windows7/VS2013, testIncrementVacuum is blocked with a sporadic CPU usage of 0,1%

Does this test is really portable on Linux/Cygwin and Windows??

**Comment by aleks-f** [comment]
It got broken by [this merge](https://github.com/pocoproject/poco/commit/044a23b1e81fb9917566396bb8f5a88897d84ba8#diff-450c565ec95fec3224f7c0ff65ea9512). Allegedly, the dummy.db is locked and that's why tests fail. I did not have time to look at it.

**Comment by zosrothko** [comment]
So meantime, can be the test ignored by commenting out this line in order to avoid Travis CI failling ?

	CppUnit_addTest(pSuite, SQLiteTest, testIncrementVacuum);

**Comment by zosrothko** [comment]
Fixed by PR#1024 at least on VS2013: bump to sqlite 3.9.2

**Comment by zosrothko** [comment]
Data/SQLit IncrementVacuum test commented out until be fixed on other platforms than Windows.
