### ISSUE TITLE
Logger API should take AutoPtr instead of plain pointer

### ISSUE THREAD

**Issue by DEvil0000** [pocoproject/poco#1009]
In all the examples for Logging you use AutoPtr to store the channels. This makes perfect sense. But the Logger API only takes plain pointers and those are not counted with AutoPtr.
So the examples only work if you store the Channels on the stack where you do not remove them (like main function for example), if you store them differently or randomly.
I was getting a segfault because of this in log(Message&).
Consider the following code:

> void configurePocoLogger()
> {
>   AutoPtr<NullChannel> pNULL(new NullChannel);
>   AutoPtr<SimpleFileChannel> pFile(new SimpleFileChannel);
>   pFile->setProperty("path", "/tmp/beforeValid.log"); //"/tmp/beforeValid.log"
>   pFile->setProperty("rotation", "never");
>   Poco::Logger::root().setChannel(pFile);
>   Poco::Logger::root().setLevel(Poco::Message::PRIO_TRACE);
> }
> int main(int argc, char*\* argv)
> {
>     configurePocoLogger();
>     Logger& logger = Logger::root();
>     logger.warning("Testing string function");
>     return 0;
> }

After configurePocoLogger() is finished AutoPtr will remove the object because a plain ptr is not counted.
Actually the code above somehow works with gcc - the code actually failing was like the following what is obviously wrong but should be the same in my eyes:

> void configurePocoLogger()
> {
>   AutoPtr<NullChannel> pNULL(new NullChannel);
>   Channel\* pCh = pNULL;
>   if (true)
>   {
>       AutoPtr<SimpleFileChannel> pFile(new SimpleFileChannel);
>       pFile->setProperty("path", "/tmp/beforeValid.log"); //"/tmp/beforeValid.log"
>       pFile->setProperty("rotation", "never");
>       pCh = pFile;
>   }
>   Poco::Logger::root().setChannel(pCh);
>   Poco::Logger::root().setLevel(Poco::Message::PRIO_TRACE);
> }
> int main(int argc, char*\* argv)
> {
>     configurePocoLogger();
>     Logger& logger = Logger::root();
>     logger.warning("Testing string function");
>     return 0;
> }

I think for the first code the compiler somehow detects that the stack variable is still used so I am not 100% sure but I think it at least could go wrong.

**Comment by DEvil0000** [comment]
may be related to #292

**Comment by aleks-f** [comment]
Indeed, Logger does take naked pointers. However, it [does the right thing](https://github.com/pocoproject/poco/blob/f3995e336f9a9b8a07f503027ff769b5affa1276/Foundation/src/Logger.cpp#L46) in regards to reference counting.

**Comment by DEvil0000** [comment]
hmm - this explains why the first code was still working. was not expecting something like this in the setter.
It is up to you if you want AutoPtr API or plain pointer.

**Comment by obiltschnig** [comment]
I'll definitely want to replace plain pointers to RefCountedObjects with AutoPtr in all interfaces, so this is welcome. Should be backwards compatible as well, so I'll probably be fine with that pending a quick review.

**Comment by DEvil0000** [comment]
it may not be backwards compatible (for same code) because of #1008 for all other cases it is as far as I can say.
