### ISSUE TITLE
Logger: PatternFormatter option %T = thread name

### ISSUE THREAD

**Issue by DEvil0000** [pocoproject/poco#1012]
%T is the thread name.
But somehow it seams only working for poco threads, not for other pthreads for example created by ace.

When I set the name for a ace thread with prctl I can see the names in htop.
(I can also not see the names of poco threads there)

see: pthread_setname_np & prctl(PR_SET_NAME,..)

Am I doing something wrong?

**Comment by obiltschnig** [comment]
%T uses the Poco::Thread internal thread name, which obviously is not available for threads created outside of POCO.

**Comment by DEvil0000** [comment]
How about using the pthreads name? Would be an improvement - right?Or is this not portable?


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Günter Obiltschnig <notifications@github.com> 
Datum: 27.02.2016  17:33  (GMT+01:00) 
An: pocoproject/poco <poco@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de> 
Betreff: Re: [poco] Logger: PatternFormatter option %T = thread name (#1012) 

%T uses the Poco::Thread internal thread name, which obviously is not available for threads created outside of POCO.

**Comment by obiltschnig** [comment]
That's not portable, unfortunately, not even between POSIX systems (function names ending in _np are non-POSIX extensions)
