### ISSUE TITLE
  Logger: PatternFormatter improvement suggestions

### ISSUE THREAD

**Issue by DEvil0000** [pocoproject/poco#1013]
1) In general a fixed length for the 'head' part of a log line is pretty important for me just because it makes log files much more readable. I can set a length for %v (and datetime padding zero) but for nothing else. I would like to have this [length] syntax optional for every possible argument.
Especially for %I, %T, %U, %u, %x..
2) %q = prioritiy name (first char only)
This is nice because it is very short but in my opinion a three letter abbreviation is more readable.
Example:
TRC, DEB, INF, WRN, ERR, FTL
3) %I = thread ID
Again I like the short ID but sometimes I would be more interested in the LWP ID or the thread pointer/start address.
4) %T = thread name
not working for most threads in my tasks - see #1012 
5) %U = source file
This is actually the file with full path what might get pretty long. I would like something for just the file name. [I fixed it with a own macro using basename(__FILE__) ]
6) %x is not documented - is it working?
7) sometimes a property might be empty like %T (task name) so if you would normally print it in parenthesis like "(%T)" it looks strange. It would be nice if I could allow some optional left and right surrounding. But still keeping fixed length by filling with spaces.

**Comment by mfslog** [comment]
hi,@DEvil0000  for point 5. %U = source file. i have some request. i also want to just show the file name without path info. i check this issue , find you already fix it, can you share you code with me . i want to know how to write the code.  :D i don't want to modify the Poco code so i need you help.

**Comment by DEvil0000** [comment]
I do not have the exact code anymore. Beside that my code was written against 1.6.1 so it could have changed over time. In the mean time I have written a FormattingChannel calling basename on the file path before printing like this: 
```
format(const Message& msg, std::string& text){
text.append(basename(msg.getSourceFile()));
}
```
Other than that I had a macro doing the job. You can have a look at the poco macros and how they work in `Foundation/include/Poco/Logger.h`. Basically they look like this:
```
#define poco_fatal(logger, msg) \
	if ((logger).fatal()) (logger).fatal(msg, __FILE__, __LINE__); else (void) 0
```
you can use the same or a bit more fancy approach and write `__FILE__` as `basename(__FILE__)`.
If you do not use the macros but the Message object you can give it e.g. as parameter:
`Message floodMsg(msgSource, msgText, level, basename(__FILE__), __LINE__);`

Happy coding ;)
