### ISSUE TITLE
Error compiling android project

### ISSUE THREAD

**Issue by cj8640** [pocoproject/poco#1019]
error information：

cj@cj-ThinkPad-X250:~/android-ndk-r10/samples/sdk_project/jni$ ndk-build
[armeabi] SharedLibrary  : libmyLib.so
/home/cj/android-ndk-r10/samples/sdk_project/jni/include/Poco/SharedPtr.h:385: error: undefined reference to 'Poco::NullPointerException::NullPointerException(int)'
/home/cj/android-ndk-r10/samples/sdk_project/jni/include/Poco/SharedPtr.h:388: error: undefined reference to 'typeinfo for Poco::NullPointerException'
/home/cj/android-ndk-r10/samples/sdk_project/jni/include/Poco/SharedPtr.h:388: error: undefined reference to 'Poco::NullPointerException::~NullPointerException()'
/home/cj/android-ndk-r10/samples/sdk_project/jni/include/Poco/Dynamic/Var.h:223: error: undefined reference to 'Poco::format(std::string const&, Poco::Any const&, Poco::Any const&)'
/home/cj/android-ndk-r10/samples/sdk_project/jni/include/Poco/Dynamic/Var.h:223: error: undefined reference to 'Poco::BadCastException::BadCastE

compile passed： Poco::JSON::Parser parser();
compile failed：    Poco::JSON::Parser parser;

**Comment by aleks-f** [comment]
Looks like you have linking errors. Are you linking with all the libraries your application depends on?

**Comment by cj8640** [comment]
I compiled libPocoFoundation.a,libPocoJSON.a in order to Android's platform,but linked error when ndk-build.    

Android.mk:

LOCAL_PATH := $(call my-dir)
###include myStaticLibrary lib as a prebuilt lib###
include $(CLEAR_VARS)


LOCAL_MODULE        :=  myLib
LOCAL_SRC_FILES := com_damn_hellojni_DamnHelloJNIClass.cpp

LOCAL_LDLIBS := -llog
LOCAL_STATIC_LIBRARIES := libPocoNet libPocoFoundation 

LOCAL_C_INCLUDES    :=  $(LOCAL_PATH)/include 
include $(BUILD_SHARED_LIBRARY)


Could you give me some suggestions.think you
