### ISSUE TITLE
Abbreviation in setThreadName can happen even if thread name is not too long

### ISSUE THREAD

**Issue by kimgr** [pocoproject/poco#1022]
https://github.com/pocoproject/poco/blob/develop/Foundation/src/Thread_POSIX.cpp#L79

`pthread_setname_np` is documented to return `ERANGE` if the name is too long, so we should only go into abbreviation mode if it actually returns `ERANGE`. There are other error returns documented for `pthread_setname_np`, and the current code will blow the stack if the thread name is actually shorter.

Also, on line 83 you use `std::memcpy` and then on line 85 you use naked `memcpy`. Might be nice to be consistent here.

It would be great if we could get these fixes into Poco 1.6.2, then we can retire our local patch for the next internal roll.

Thanks!

**Comment by kimgr** [comment]
I'm a bit concerned with your adaptation of the changes I suggested:

- `pthread_setname_np` is not documented to use `errno`. Rather it returns its error code
- It should only return `ERANGE` if thread name is > 15, so the length check seems redundant. Did you have a good reason to add that?
- We consciously stayed away from std::string, because we don't want to mess with the heap (we have enough trouble with heap fragmentation and allocation performance)
- This line:

        truncName.append(threadName, threadName.size() - 7, 7);

is just wrong unless I'm missing something. If threadName is 16 chars long, it will copy from index 9 to index 16, which misses a character, and reads past the end (hitting the NUL terminator for most implementations of std::string.)

Any chance you could stay with the changes we made? It looks a little messier, but it appears objectively better.

**Comment by obiltschnig** [comment]
You are correct regarding errno. 

My rationale for using std::string was that C++11 compilers (including now also GCC) support small object optimization for std::string, so that strings below a certain size should not touch the heap. 16 chars should definitely fit into that (at least in MSVC, haven't checked GCC yet). Apart from that - are you really creating so many threads that this becomes relevant to heap fragmentation? 

Regarding the append: for a 16 char threadName, this will append from index 9 to index 15, not 16, so this should be fine.

**Comment by kimgr** [comment]
You're absolutely right about the final append, sorry about that! I worked it out on paper while watching TV, I must've focused on the wrong thing :-/

As for std::string use in general, we've just been burned by temporaries hitting the heap for no good reason, that we tend to stay away from potential dynamic allocation if the buffer size is fixed anyway. Death by a thousand cuts, and all that.

Thanks for updating this anyway!
