### ISSUE TITLE
Cross compiling using CMake

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#1024]
From [forum](http://pocoproject.org/forum/viewtopic.php?f=12&t=6654&p=12359):

"I'm using poco in a CMake project, and I can't find a way to configure poco to use my toolchhain.
In fact I just want to do what we already can do with ./configure --config but from CMake."

**Comment by bachp** [comment]
Cross compiling with CMake is described [here](https://cmake.org/cmake/help/git-master/manual/cmake-toolchains.7.html#cross-compiling). There is nothing special about Poco.

However if you are looking for pre definde CMake toolchain files we don't provide these.

**Comment by aaboyd** [comment]
CMake will use ```CC=/path/to/gcc``` and ```CXX=/path/to/g++```.  So, if you just want to use a different version of gcc than you should have no problems.  I have compiled on a linux ( x86_64 ) machine to a raspberry pi without having to create a toolchain file at all.  Just set those variables.

Creating a complicated toolchain can sometimes be complicated.  [Polly](https://github.com/ruslo/polly) might be able to help with that.

**Comment by lmussier** [comment]
Hi, this do the trick, I've also to pass some options for my target (mostly options in ARMLinux config)
Thanks.
