### ISSUE TITLE
POCO wrapper over common hash functions

### ISSUE THREAD

**Issue by alexandruirimiea** [pocoproject/poco#1025]
Is there by any chance any wrapper over the most common hash functions (e.g.: MD5, SHA256, etc)? I have searched but I couldn't find any.

If there isn't, will it ever be considered in the future?

**Comment by aleks-f** [comment]
[MD4](https://github.com/pocoproject/poco/blob/f3995e336f9a9b8a07f503027ff769b5affa1276/Foundation/include/Poco/MD4Engine.h#L53), [MD5](https://github.com/pocoproject/poco/blob/f3995e336f9a9b8a07f503027ff769b5affa1276/Foundation/include/Poco/MD5Engine.h#L53), [SHA1](https://github.com/pocoproject/poco/blob/f3995e336f9a9b8a07f503027ff769b5affa1276/Foundation/include/Poco/SHA1Engine.h#L36),[RSA](https://github.com/pocoproject/poco/blob/f3995e336f9a9b8a07f503027ff769b5affa1276/Crypto/include/Poco/Crypto/RSADigestEngine.h#L35)

**Comment by alexandruirimiea** [comment]
Perfect.

This collection of libraries is awesome. I wonder why many people didn't hear about it yet. It should be like a practical standard library, like boost.
