### ISSUE TITLE
GetModuleFileName symbol in Poco?

### ISSUE THREAD

**Issue by ddsherstennikov** [pocoproject/poco#1035]
When POCO is linked with windows executable which uses GetModuleFileName method, it can not be found. My guess is that POCO have used this method name and the complaint of linker is really about ambiguity: POCO overrides AinApi symbol.

When WinApi's GetModuleFileName is changed to GetModuleFileNameW, linkage goes fine.

**Comment by bachp** [comment]
There is a [UnWindows.h](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/UnWindows.h) which is doing exactly what you experience.

To disable the this you need to define `POCO_NO_UNWINDOWS` when using the Poco headers in your application.
