### ISSUE TITLE
Can I use binding to enable command line options from configuration files?

### ISSUE THREAD

**Issue by oblitum** [pocoproject/poco#1036]
I have an standard ApplicationServer application that currently adds a bunch of command line options. I was thinking of being able to pass these options in the configuration file while the application should get those values from the configuration file options throught the same command line options I was already using, instead of querying for configurations and having to deal with command-line/configuration-file options priority myself.

Is something like this easily set up?

**Comment by obiltschnig** [comment]
See http://pocoproject.org/docs/Poco.Util.Option.html#26587
