### ISSUE TITLE
LIBFLAGS in build/config/Linux breaks build in Ubuntu 14.04

### ISSUE THREAD

**Issue by RangelReale** [pocoproject/poco#1053]
Compiling in Linux using the Makefile, I got this error when linking PocoFoundation.a:

ar: two different operation options specified

comenting all the "LIBFLAGS" values in the build file solves this problems, why was this added (commit in 2015-11-17).

**Comment by zosrothko** [comment]
Look at this issue: #894

**Comment by RangelReale** [comment]
I posted in #1018, because it seems that it broke static compilation.
I just did ./configure and make.

**Comment by zosrothko** [comment]
Can you add the line anyway, I do not have a Ubuntu system under hands..

**Comment by RangelReale** [comment]
# ./configure --static --omit=Crypto,NetSSL_OpenSSL,Data/ODBC,Data/MySQL,PageCompiler,PageCompiler/File2Page,ApacheConnector,PDF,CppParser,PocoDoc,ProGen,MongoDB,Redis --no-samples

# make -j 4

**Comment by zosrothko** [comment]
IMO,the -m32.-m64 options should be removed only from the LIBFLAGS and stay the others flags.

**Comment by aleks-f** [comment]
ok, let's see if that takes care of it

**Comment by zosrothko** [comment]
By the way, I just build Poco@develop on Fedora 22 in static mode (first time I did it) and there are a lot of problems, specially at link time as for example
sqlite3.c:(.text+0x5b99): AVERTISSEMENT: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by aleks-f** [comment]
there was an old discussion about that on sourceforge forum but I can't find it anymore; we were not able to find a way to cleanly build it statically and, at the time, it had to do with some kerberos functions. If you can fix it, send pull. static linking on linux is a PITA full of perils of all kinds

**Comment by zosrothko** [comment]
I will see later on... I have already 3 PRs on fire... The AppVeyor stuff, the MkdocMkrelease and the Distro stuff and I would like to close them before... In any case, just removing the -m32/m64 from LIBFLAGS in conf/Linux of the develop branch would unblock @ RangelReale.. Can you do it?

**Comment by aleks-f** [comment]
it's been [done](https://github.com/pocoproject/poco/commit/be8663c3956860f84a260b10d9d29c7875a0d554) already, see the notification above

**Comment by obiltschnig** [comment]
From my experience, trying to link libc and other system libraries on Linux is a PITA. What works is building static POCO libs, and then linking the executable with the static POCO libs, but the shared system libraries. This currently requires two separate build steps, though.

**Comment by aleks-f** [comment]
There's also the pthread static linking [problem](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52590). It grieved me a while ago - all compiled and linked but every call to std::thread::joinable() dereferenced null pointer and crashed. I think it would be best to always link std lib and pthread dynamically on Linux, even for static poco builds.
