### ISSUE TITLE
MongoDB Document toString with element is date object

### ISSUE THREAD

**Issue by manthanrtilva** [pocoproject/poco#1062]
Hi,

When i run below code.

	Poco::MongoDB::Connection connection("localhost",27017);
	Poco::MongoDB::Database db("a");
	Poco::MongoDB::ResponseMessage response;
	Poco::SharedPtr<Poco::MongoDB::InsertRequest> insertPlayerRequest = db.createInsertRequest("b");
	Poco::Timestamp t;
	insertPlayerRequest->addNewDocument()
		.add("lastname", "Valdes")
		.add("firstname", "Victor")
		.add("time", t);
	connection.sendRequest(*insertPlayerRequest);
	
    Poco::SharedPtr<Poco::MongoDB::QueryRequest> queryPtr = db.createQueryRequest("b");
    queryPtr->setNumberToReturn(1);
    connection.sendRequest(*queryPtr, response);
    Poco::Dynamic::Var result;
    if ( response.hasDocuments() )
    {
    	std::cout<<response.documents()[0]->toString()<<std::endl;
    }

its printing output like below.

{"_id":56619736ce47c3e150903db6,"firstname":"Victor","lastname":"Valdes","time":2015-12-04T13:37:58.161000Z}

I think, as we using toString method time element should be surrounded by double quote.

Let me know if my understanding is wrong or there is any issue in library.

**Comment by manthanrtilva** [comment]
You just need to update in Element.h file toString() method of  struct ElementTraits<Timestamp>.

Correct me if I am wrong? So I can continue with my development.

**Comment by fbraem** [comment]
Correct. Just need some time to see if this change doesn't break anything.

**Comment by aleks-f** [comment]
@fbraem you can use [Var::isDateTime()](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Dynamic/Var.h#L505-L511),  those were introduced for [JSONRowFormatter](https://github.com/pocoproject/poco/blob/develop/Data/src/JSONRowFormatter.cpp#L144)
