### ISSUE TITLE
Process hangs on waitpid

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#1063]
Process test hangs on [waitpid](https://github.com/pocoproject/poco/blob/develop/Foundation/src/Process_UNIX.cpp#L67); This problem started manifesting in Travis after https://github.com/pocoproject/poco/commit/b9cfd346a12b4b7c0fb84bb844e99c1d9ed326da , but I can't see how that pull could have caused it. /cc recent committers: @obiltschnig @mikedld @vmiklos @zosrothko

**Comment by aleks-f** [comment]
Hanging is fixed but the tests still fail. I don't have time now to investigate further but it would be nice if one of the recent committers could figure out what's going on

**Comment by vmiklos** [comment]
How can I run the failing test? I tried `travis/runtests.sh`, it seems to hang here after printing testSendToReceiveFrom (I tried with an 1 hour timeout), even before b9cfd34. Thanks.

**Comment by zosrothko** [comment]
On Fedora22, all tests run by .travis/runtests.sh on teh develop branch are passing except one

There was 1 error:
 1: N7CppUnit10TestCallerI14HTTPServerTestEE.testChunkedRequestKeepAlive
    "N4Poco3Net12NetExceptionE: Net Exception"
    in "<unknown>", line -1

12 runs, 1 failed.

Failed: Net

**Comment by vmiklos** [comment]
Hmm, where is what I get:

```
$ build/script/runtests.sh Net N7CppUnit10TestCallerI14HTTPServerTestEE.testChunkedRequestKeepAlive


****************************************
*** Linux x86_64 Net
****************************************


testChunkedRequestKeepAlive: 

OK (1 tests)



1 runs, 0 failed.


$ git log -1
commit 95f1a7c30db80be83636ddb2dfc4ddf566ffda23
Author: Alex Fabijanic <alex@pocoproject.org>
Date:   Sun Dec 6 23:18:29 2015 -0600

    Process hangs on waitpid #1063

```

I.e. it doesn't seem to fail here as of the latest master.

**Comment by zosrothko** [comment]
[fandre@obelix poco]$ git log -1
commit 95f1a7c30db80be83636ddb2dfc4ddf566ffda23
Author: Alex Fabijanic <alex@pocoproject.org>
Date:   Sun Dec 6 23:18:29 2015 -0600

    Process hangs on waitpid #1063

**Comment by vmiklos** [comment]
Hmm, and if you revert 95f1a7c30db80be83636ddb2dfc4ddf566ffda23 and b9cfd346a12b4b7c0fb84bb844e99c1d9ed326da locally, then the problem goes away?

**Comment by zosrothko** [comment]
All Travis jobs are failing with only one failure in Foundation

!!!FAILURES!!!
Runs: 697   Failures: 1   Errors: 0

There was 1 failure: 
 1: N7CppUnit10TestCallerI11ProcessTestEE.testSignalExitCode
    "rc == -SIGINT"
    in "src/ProcessTest.cpp", line 210

This test is passing fine on Fedora 22

**Comment by vmiklos** [comment]
Yes, it passes fine on openSUSE 13.2 as well. I'll try to find out what environment the Travis jobs are using, hopefully something I can mimic locally.

**Comment by vmiklos** [comment]
Hrm, I have no idea how to reproduce the failure. Travis seems to use Ubuntu 12.04, here is one full log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/95533798/log.txt

That's the "gcc (make) unbundled" scenario. Now I installed the same distro in a VM, tried to follow the instructions in .travis.yml as-is, and still the test mentioned in the log passes just fine:

```
build/script/runtests.sh Foundation N7CppUnit10TestCallerI11ProcessTestEE.testSignalExitCode
```

I'm a bit stuck on how to trigger the failure locally, then.

**Comment by mikedld** [comment]
Tried reproducing on OS X, no luck. Getting another error in about 1 of 3-4 runs

```
There was 1 failure:
 1: N7CppUnit10TestCallerI26TimedNotificationQueueTestEE.testDequeue
    "ts2.elapsed() >= 0"
    in "src/TimedNotificationQueueTest.cpp", line 109
```

but never the ProcessTest one.

**Comment by zosrothko** [comment]
you can run a single testsuite/test from a component as

build/script/runtests.sh Foundation Process
or 
build/script/runtests.sh Foundation SignalExitCode

**Comment by mikedld** [comment]
> build/script/runtests.sh Foundation Process
> or
> build/script/runtests.sh Foundation SignalExitCode

Doesn't fail either way (running in a `while` loop) on OS X.

Could this be related to http://pocoproject.org/forum/viewtopic.php?t=5456 ?

**Comment by mikedld** [comment]
Quick test with
```
sh -c 'trap "" SIGINT; build/script/runtests.sh Foundation SignalExitCode'
```
shows that it could indeed be related. This also means that Travis catches `SIGINT`. So we need to either pick another signal or explicitly clear the signal mask in TestApp.

**Comment by zosrothko** [comment]
6 days ago, the test was ok... look for passed build at travis...

`testLaunchEnv: `
`testIsRunning: `
`testSignalExitCode: `
`testLock: `
`testTryLock: `

**Comment by zosrothko** [comment]
@mikedld You are pretty rigth with the trap of SIGINT by Travis.
Below the latest log where trapped signal are displayed within travis/runtests.sh. So the solution is to ask travis to remove this SIGINT trap when using travis_wait.

travis_wait 30 ./travis/runtests.sh
trap -- '' SIGINT
trap -- '' SIGQUIT
export POCO_BASE=`pwd`
pwd
export CPPUNIT_IGNORE="\
  N7CppUnit10TestCallerI8PathTestEE.testExpand \
  N7CppUnit10TestCallerI13RawSocketTestEE.testEchoIPv4 \
  N7CppUnit10TestCallerI13RawSocketTestEE.testSendToReceiveFromIPv4 \
  N7CppUnit10TestCallerI14ICMPClientTestEE.testPing \
  N7CppUnit10TestCallerI22HTTPSClientSessionTestEE.testProxy \
  N7CppUnit10TestCallerI22HTTPSStreamFactoryTestEE.testProxy \
  N7CppUnit10TestCallerI19MulticastSocketTestEE.testMulticast \
  N7CppUnit10TestCallerI13NTPClientTestEE.testTimeSync"
export EXCLUDE_TESTS="Data/MySQL Data/ODBC MongoDB PDF"
export PATH=$PATH:.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
build/script/runtests.sh

**Comment by mikedld** [comment]
Making the following change works for me (on OS X):

```patch
--- a/Foundation/testsuite/src/TestApp.cpp
+++ b/Foundation/testsuite/src/TestApp.cpp
@@ -49,6 +49,7 @@ int main(int argc, char** argv)
                }
                else if (arg == "-raise-int")
                {
+                       std::signal(SIGINT, SIG_DFL);
                        std::raise(SIGINT);
                }
        }
```

Could you confirm?

**Comment by zosrothko** [comment]
Confirmed
