### ISSUE TITLE
New feature In MongoDB API.

### ISSUE THREAD

**Issue by manthanrtilva** [pocoproject/poco#1064]
Hi,
It will be great if MongoDB API has some method like add(std::string,Poco::Dynamic::Var)/add(std::string,Poco::JSON::Object::Ptr) and get(std::string,Poco::Dynamic::Var)/get(std::string,Poco::JSON::Object::Ptr).

Currently I have write one wrapper function addObjectToDoc(Poco::MongoDB::Document& doc,Poco::JSON::Object::Ptr object) to achieve this functionality. Even thought is not complete but it's okay for my purpose.

**Comment by fbraem** [comment]
Adding this functionality to the MongoDB module makes it depend on the JSON module. The question is: do we want this?

**Comment by aleks-f** [comment]
That's up to you @fbraem, maybe alleviate such dependency by just having `add/get(std::string, Dynamic::Var)` and ifdef implementation to disable JSON dependency by default (but allow introducing dependency via macro definition). In the implementation, assume that Var contains either `std::string` or `JSON::Object::Ptr` and deal with it accordingly. But, if the full JSON dependency makes sense and will be needed also in the interface eventually, then just introduce it. That's my $.02, I don't have enough knowledge or experience with this library to have strong opinion one way or the other.

**Comment by manthanrtilva** [comment]
If keeping module independent is really issue then we can provide such methods in sample examples and just provide documentation about it in module to user. This will also keep module independent and user will get right code to reuse. 
Does it make sense?

**Comment by fbraem** [comment]
Can you make your code public? Create a gist? I will have a look and see if I can find some time to look into this ...

**Comment by manthanrtilva** [comment]
@fbraem 
Sure. Code is at 
https://gist.github.com/manthanrtilva/904d5b6010795bebf70a

This may be not production ready, but you can guide me if you want some changes from my side.
