### ISSUE TITLE
Poco logger in multithread cause "dead lock" issue 

### ISSUE THREAD

**Issue by lion117** [pocoproject/poco#1065]
# background 
i wanna use poco logger in my console program for two purpose 
- print important information in the console 
- record some necessary software running statue information into logger files 
So I  fellow the example in the poco library like following image  which could work well in **single thread** software 
but There is one issue in the multiple thread software . 

```C++
	AutoPtr<SplitterChannel> splitterChannel(new SplitterChannel());
	AutoPtr<Channel> consoleChannel(new ConsoleChannel());
	AutoPtr<FileChannel> rotatedFileChannel(new FileChannel("rotated.log"));

	rotatedFileChannel->setProperty("rotation", file_size);
	rotatedFileChannel->setProperty("path", i_filename);
	rotatedFileChannel->setProperty("archive", "timestamp");

	splitterChannel->addChannel(consoleChannel);
	splitterChannel->addChannel(rotatedFileChannel);

	AutoPtr<Formatter> formatter(new PatternFormatter("Datetime: %Y/%n/%d-%L%H:%M:%S  thread: %T%I Code line : %u \r\nPosition: %U\r\n%p: %t "));
	AutoPtr<Channel> formattingChannel(new FormattingChannel(formatter, splitterChannel));
	Logger::root().setChannel(formattingChannel);
```

# Trigger  condition 
- New a console software 
- Setup several threads , which all of them could record info
- kill make console lose focuse , keeping console recording information(print something on console screen ) all the time 
- make console get focus 
> result :  All the threads would die one by one . nothing output from console screen anymore until user type something into console 

## assumption 
the phenomenon is like  multiple threads crash into **dead lock ** , until  key lock had been released (type keyboard)

**Comment by aleks-f** [comment]
Logger is thread-safe, it is very likely that you are doing it to yourself somehow. Make a [SSCCE](http://sscce.org/) and post it here.

**Comment by lion117** [comment]
```

### main 

```C++
#include "stdafx.h"
#include <string>
#include <iostream>
#include <windows.h>
#include <iostream>
using namespace std;
////////////////////////////////////////////////////////////
#include "Poco/Thread.h"
#include "Poco/ThreadPool.h"
#include "Poco/Runnable.h"
/////////////////////////////////////////////////////////////
#include "Poco/PatternFormatter.h"
#include "Poco/FormattingChannel.h"
#include "Poco/FileChannel.h"
#include "Poco/AutoPtr.h"
#include "Poco/Format.h"
#include "Poco/ConsoleChannel.h"
#include "Poco/SplitterChannel.h"
#include "Poco/Path.h"
#include "Poco/Logger.h"

using namespace Poco;

#define logger_handle   (Logger::get("logger"))      // shortcut to use poco logger 


string getCurrentFileName()
{
	char buffer[MAX_PATH];
	GetModuleFileNameA(NULL, buffer, MAX_PATH);
	return std::string(buffer);
}

void Logger_init_v2(unsigned int t_max_size)
{
	string	i_filename = getCurrentFileName();
	i_filename += ".log";
	string file_size = format("%uM", t_max_size);
	AutoPtr<SplitterChannel> splitterChannel(new SplitterChannel());
	AutoPtr<Channel> consoleChannel(new ConsoleChannel());
	AutoPtr<FileChannel> rotatedFileChannel(new FileChannel("rotated.log"));
	rotatedFileChannel->setProperty("rotation", file_size);
	rotatedFileChannel->setProperty("path", i_filename);
	rotatedFileChannel->setProperty("archive", "timestamp");
	splitterChannel->addChannel(consoleChannel);
	splitterChannel->addChannel(rotatedFileChannel);
	AutoPtr<Formatter> formatter(new PatternFormatter("Datetime: %Y/%n/%d-%L%H:%M:%S  thread: %T%I Code line : %u \r\nPosition: %U\r\n%p: %t "));
	AutoPtr<Channel> formattingChannel(new FormattingChannel(formatter, splitterChannel));
	Logger::root().setChannel(formattingChannel);
}

class Logger_task : public Runnable
{
public:
	Logger_task(string t_name)
	{
		_name = t_name;
	}

	virtual void run()
	{
		int i = 0;
		while (i < 10000)
		{
			string i_logger_info = format("%s logger task %d", _name, i);
			poco_information(logger_handle, i_logger_info);
			i++;
		}
	}
private:
	string _name;
};

int _tmain(int argc, _TCHAR* argv[])
{
	Logger_init_v2(2);

	/// multiple- thread test 
	ThreadPool i_pool;
	Logger_task i_task1("task1");
	Logger_task i_task2("task2");
	Logger_task i_task3("task3");
	Logger_task i_task4("task4");
	Logger_task i_task5("task5");
	Logger_task i_task6("task6");
	i_pool.start(i_task1);
	i_pool.start(i_task2);
	i_pool.start(i_task3);
	i_pool.start(i_task4);
	i_pool.start(i_task5);
	i_pool.start(i_task6);
	i_pool.joinAll();

	system("pause");
	return 0;
}
```


##Trigger condition

- New a console software
- Setup several threads , which all of them could record info
- kill make console lose focuse , keeping console recording information(print something on console screen ) all the time
- make console get focus 

> ***result*** : All the threads would die one by one . nothing output from console screen anymore until user type something into console



![q -20151208090153](https://cloud.githubusercontent.com/assets/3996029/11644887/bfabfd0a-9d8a-11e5-81cc-a1dd7e8654b1.png)

**Comment by aleks-f** [comment]
The code does exactly what you told it to do - pause at this line until something is entered:
`system("pause");`

**Comment by lion117** [comment]
accurately  , without  this code line 
```
system("pause");
```
the issue still there . anyway , from logic code , the main thread would wait at 
```
i_pool.joinAll();              // until all  threads done jobs 
```
![q -20151208092623](https://cloud.githubusercontent.com/assets/3996029/11645233/c36465b0-9d8d-11e5-873a-3710363a3882.png)

**Comment by aleks-f** [comment]
It works as expected:
![threadlogcapture](https://cloud.githubusercontent.com/assets/2429093/11646030/3f333e4c-9d1f-11e5-8729-dcc654a13234.PNG)

**Comment by aleks-f** [comment]
BTW, you are not logging where you think you are. You initialize "root", but log to "logger".

**Comment by lion117** [comment]
Thanks  a lot . Issue had been located which was the my IDE problems, poco logger is ok .
