### ISSUE TITLE
POP3ClientSession retrieveMessage failure after retrieveHeader

### ISSUE THREAD

**Issue by yiivon** [pocoproject/poco#107]
While retrieveHeader, the response before \r\n\r\n be read from DialogSocket's buffer only, but some mail-server(like QQ mail) append a other lines. 
After retrieveHeader operation, the same POP3ClientSession object executing retrieveMessage failure, because the DialogSocket's current buffer storing the old data from the previous operation.

**Comment by aleks-f** [comment]
this is quite old, @yiivon can you provide an example of the message that causes problems?
