### ISSUE TITLE
Add -DPOCO_HAVE_LIBRESOLV to Linux build configuration

### ISSUE THREAD

**Issue by oblitum** [pocoproject/poco#1076]
If I start my application with my wifi disabled I get "host not found" for anything like `StreamSocket(SocketAddress("google.com:80"))`. If I let the application running in a loop trying to connect it keeps getting "host not found",  that's OK, but when I enable my wifi back the application keeps returning "host not found".

This doesn't happen if my application starts when my wifi is ON, then turned OFF and ON again. If the application starts with wifi OFF, it doesn't matter whether I turn wifi ON, it simply won't connect.

**Comment by aleks-f** [comment]
We know how WiFi works but we have no clue how your application works. A [SSCCE](http://sscce.org/) may help in the process :).

**Comment by oblitum** [comment]
@aleks-f Hi, the situation I mention already provides a SSCCE. Something along this line:

```
for (;;) {
    try {
        StreamSocket(SocketAddress("google.com:80"));
        cout << "connected" << endl;
        break;
    } catch(...) {
        cout << "not connected" << endl;
        std::this_thread::sleep_for(10s);
    }
}
```

I'll come back later to put it in a compilable state, but the description is just that.

**Comment by oblitum** [comment]
In the previous sample, if I start it when my network is ON, if I disable the network and enable it back, it starts to output `"connected"` again. If I launch it with the network OFF and turn it ON afterwards, the sample never displays anything but `"not connected"`.

**Comment by aleks-f** [comment]
The only way I could compile the description was if I commented it, but then it didn't do anything ;)

Now that we have code, we can diagnose the problem:  you are assigning a temporary object to `connection`, here:
```c++
auto connection = StreamSocket(SocketAddress("google.com:80"));
```
which makes the whole thing undefined behavior - literally anything that happens makes sense, including the behavior you observed. 

Try
```c++
StreamSocket connection(SocketAddress("google.com:80"));
```
and you'll see it will work. Take care and enjoy POCO :)

**Comment by aleks-f** [comment]
It occurred to me that the temporary should be copied in the auto variable as value, not reference; so, your original code is valid. I tried it on Linux/gcc, and the problem does not manifest there. I assume it must be something related to windows or VC compiler that is causing it on windows but I had not time to research further.

**Comment by obiltschnig** [comment]
It would be helpful to know what platform you're using. Don't think its a compiler issue.

**Comment by oblitum** [comment]
@aleks-f  As you have commented, I've changed the original code to just pop a temporary without storing it, which should provide the same behavior. To tell the truth, in my original code I was not using `auto` in original code but just the temporary like now, I've them changed to a version like yours, which didn't make a difference.

@obiltschnig I'm on Archlinux on a [MacBook Pro](https://support.apple.com/kb/SP619?locale=en_US)

**Comment by oblitum** [comment]
For sake of reference, I've tried the old-style declaration to no effect.

**Comment by aleks-f** [comment]
I ran both versions of code on Ubuntu 15.04 with g++ 4.9.2 and could not reproduce problem in any shape. Also ran it through valgrind, no problems reported.

**Comment by obiltschnig** [comment]
Try calling Poco::DNS::reload() before creating the socket (or more specifically, the SocketAddress). You may need to #include "Poco/Net/DNS.h"

You may also need to rebuild the Net library with -DPOCO_HAVE_LIBRESOLV

**Comment by oblitum** [comment]
By the way, I'm running Poco 1.6.1-1 on Arch.

**Comment by oblitum** [comment]
@obiltschnig I have changed my code to this:

```
#include <thread>
#include <chrono>
#include <iostream>
#include <Poco/Net/DNS.h>
#include <Poco/Net/StreamSocket.h>

using namespace std;
using namespace Poco::Net;
using namespace std::chrono_literals;

int main () {
    for (;;) {
        try {
            Poco::Net::DNS::reload();
            StreamSocket connection(SocketAddress("google.com:80"));
            cout << "connected" << endl;
        } catch(...) {
            cout << "not connected" << endl;
        }
        this_thread::sleep_for(1s);
    }
}```

It compiles, so I ask whether `-DPOCO_HAVE_LIBRESOLV` is implied or I still need to rebuild the library.

I got the same behavior with the previous sample.

**Comment by obiltschnig** [comment]
No, -DPOCO_HAVE_LIBRESOLV is unfortunately not the default. Add it to build/config/Linux:

    SYSFLAGS += -DPOCO_HAVE_LIBRESOLV

**Comment by oblitum** [comment]
Full specs:

- GCC 5.2.0
- Up to date ArchLinux x86-64
- [MacBook Pro](https://support.apple.com/kb/SP619?locale=en_US)
- Poco 1.6.1-1

**Comment by oblitum** [comment]
@obiltschnig OK, I guess I'll try this later, compiling the library ourselves is not a good option at the moment.

**Comment by aleks-f** [comment]
you can try with IP address to eliminate the DNS doubt

**Comment by obiltschnig** [comment]
You can also try calling

  res_init();

which is what DNS::reload() does. Need to #include <resolv.h>

**Comment by oblitum** [comment]
@aleks-f yes, using a google ip address does solve the problem.

**Comment by obiltschnig** [comment]
I have seen this issue on some embedded Linux platforms, when changing network configurations.

**Comment by aleks-f** [comment]
ok, so it is DNS. FWIW, catching Poco::Net::NetException and logging displayText() would give you more precise info on what fails

**Comment by oblitum** [comment]
Thank you guys, the following fix the issue for me:

```c++
#include <thread>
#include <chrono>
#include <iostream>
#include <resolv.h>
#include <Poco/Net/StreamSocket.h>

using namespace std;
using namespace Poco::Net;
using namespace std::chrono_literals;

int main () {
    for (;;) {
        try {
            res_init();
            StreamSocket connection(SocketAddress("google.com:80"));
            cout << "connected" << endl;
        } catch(...) {
            cout << "not connected" << endl;
        }
        this_thread::sleep_for(1s);
    }
}
```

Also thanks for the `displayText` tip.

**Comment by oblitum** [comment]
I'm not sure whether I should keep it open b/c poco doesn't do the expected by default yet, it's seems there's a solution already if it compiled with `-DPOCO_HAVE_LIBRESOLV`.

**Comment by obiltschnig** [comment]
One note regarding res_init(): it's not thread safe so if your application calls it from multiple threads wrap it in a critical section (mutex).

We should add -DPOCO_HAVE_LIBRESOLV to the Linux build configuration.

**Comment by oblitum** [comment]
@obiltschnig ok, thanks for the tip, issue title is fine as @aleks-f made it. Regards.

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/b71d54d65cb759d92fbc5166890936107080608a#diff-5d1f6d0485aa3d806bb91768f8f149c6
