### ISSUE TITLE
Host verify fails in X509Certificate ( >1.5.1)

### ISSUE THREAD

**Issue by Kaeslin** [pocoproject/poco#1079]
With the POCO releases > 1.5.1 it is possible to create a SecureHTTPSession to Hosts with invalid certificates (invalid Host name) and an active RejectCertificateHandler.
The InvalidCertificateHandler is not called and I guess the verify method in X509Certificate fails.

**Comment by aleks-f** [comment]
Can you post code to reproduce this?

**Comment by Kaeslin** [comment]
I connect to a WebSocket Server with an RejectCertificateHandler. My expectation is that the connection creation fails, because of the invalid hostname in the certificate.
But the connection is created.

Here is the code:

**Properties File**
```
openSSL.client.caConfig=/etc/ssl/certs/
openSSL.client.verificationMode = strict
openSSL.client.verificationDepth = 5
openSSL.client.invalidCertificateHandler.name = RejectCertificateHandler
```

**Code**
```cpp
try
{
  shared_ptr<HTTPSClientSession> _pHttpsClientSession;
  shared_ptr<WebSocket> _pWsConnection;
  std::string host = "developerconnectivity-ccl.cloudapp.net";
  int port = 443;

  _pHttpsClientSession = shared_ptr<HTTPSClientSession>(new HTTPSClientSession( host, port ));

  HTTPRequest UpdateReq( HTTPRequest::HTTP_GET, "wss://developerconnectivity-ccl.cloudapp.net");
  HTTPResponse UpdateRes;

  _pWsConnection = shared_ptr<WebSocket>(new WebSocket( *_pHttpsClientSession, UpdateReq, UpdateRes ));
}
catch ( const Poco::Exception& e )
{
}
```

**Comment by obiltschnig** [comment]
In order to enable certificate host name verification, add the following setting to the properties file:

    openSSL.client.extendedVerification = true

Otherwise, OpenSSL will only validate the certificate chain, but not whether the server certificate's CN matches the actual host name.

**Comment by Kaeslin** [comment]
Thanks for the advice, now it works.
