### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1081]
I have created a pocoproject project on Slack (https://pocoproject.slack.com) a couple of months ago. Feels a bit lonely there, only getting messages from the GitHub bot ;-).  Would be greate if those of you currently working on POCO (especially @RangelReale and @zosrothko) could join. Send me your email address for an invite (guenter at appinf.com).

**Comment by zosrothko** [comment]
zosrothko@orange.fr

**Comment by Mazyod** [comment]
I only contributed a little, and not sure if I can dedicate more time yet, but would love to. If it's ok, I'd love to be part of this mazyod@gmail.com
