### ISSUE TITLE
Enhancement: Unify dynamic structures in Poco

### ISSUE THREAD

**Issue by matejk** [pocoproject/poco#1083]
Poco uses a few concepts for representation of dynamic structures:
- Dynamic (Var, Struct, Array...)
- MongoDB dynamic structs
- JSON (wrapped around Dynamic Var)
- Redis Type/Array

When manipulating data from different sources one has to write conversion functions from one type of dynamic structure to another.

My proposal is that Poco::Dynamic is used as the main dynamic data structure. JSON, Redis, MongoDB structures shall be internal structures for marshaling/unmarshaling for the purpose of communication with the server.

JSON, MongoDB, Redis shall use Poco::Dynamic in their interfaces and convert the data to internal representations.

Supported types for each of the libs shall be documented. The lib shall throw exceptions when improper type is passed to it and/or have validators.

**Comment by aleks-f** [comment]
Yes, it should be unified. If possible, don't break existing interfaces, just add the ones with "standard" structures.

**Comment by fbraem** [comment]
I agree that we need to support Poco::Dynamic in the interfaces without changing the internal representations ...
