### ISSUE TITLE
No <string> on ArchiveStrategy when compiling poco-1.6.1 for Android

### ISSUE THREAD

**Issue by Grabber** [pocoproject/poco#1084]
## ENVIRONMENT

lvmc@ubuntu:~/Desktop/poco-1.6.1$ lsb_release -d
Description:    Ubuntu 15.04

lvmc@ubuntu:~/Desktop/poco-1.6.1$ uname -a
Linux ubuntu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

export PATH=$PATH:$HOME/Android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin
## COMPILING

cd poco-1.6.1

./configure --config=Android --no-samples --no-tests --static --omit=CppUnit,CppParser,CodeGeneration,PageCompiler,Remoting,Data/MySQL,Data/ODBC,Zip,XML

make -s -j4 ANDROID_ABI=armeabi-v7a
## ERROR

*\* Compiling src/ArchiveStrategy.cpp (debug, static)
*\* Compiling src/Ascii.cpp (debug, static)
*\* Compiling src/ASCIIEncoding.cpp (debug, static)
*\* Compiling src/AsyncChannel.cpp (debug, static)
In file included from include/Poco/Foundation.h:148:0,
                 from include/Poco/ArchiveStrategy.h:23,
                 from src/ArchiveStrategy.cpp:17:
include/Poco/Bugcheck.h:24:18: fatal error: string: No such file or directory
compilation terminated.
/home/lvmc/Desktop/poco-1.6.1/build/rules/compile:37: recipe for target '/home/lvmc/Desktop/poco-1.6.1/Foundation/obj/Android/armeabi-v7a/debug_static/ArchiveStrategy.o' failed
make[1]: **\* [/home/lvmc/Desktop/poco-1.6.1/Foundation/obj/Android/armeabi-v7a/debug_static/ArchiveStrategy.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
In file included from include/Poco/Foundation.h:148:0,
                 from include/Poco/ASCIIEncoding.h:23,
                 from src/ASCIIEncoding.cpp:17:
include/Poco/Bugcheck.h:24:18: fatal error: string: No such file or directory
compilation terminated.
In file included from include/Poco/Foundation.h:148:0,
                 from include/Poco/AsyncChannel.h:23,
                 from src/AsyncChannel.cpp:17:
include/Poco/Bugcheck.h:24:18: fatal error: string: No such file or directory
compilation terminated.
/home/lvmc/Desktop/poco-1.6.1/build/rules/compile:37: recipe for target '/home/lvmc/Desktop/poco-1.6.1/Foundation/obj/Android/armeabi-v7a/debug_static/ASCIIEncoding.o' failed
make[1]: **\* [/home/lvmc/Desktop/poco-1.6.1/Foundation/obj/Android/armeabi-v7a/debug_static/ASCIIEncoding.o] Error 1
In file included from include/Poco/Foundation.h:148:0,
                 from include/Poco/Ascii.h:23,
                 from src/Ascii.cpp:17:
include/Poco/Bugcheck.h:24:18: fatal error: string: No such file or directory
compilation terminated.
/home/lvmc/Desktop/poco-1.6.1/build/rules/compile:37: recipe for target '/home/lvmc/Desktop/poco-1.6.1/Foundation/obj/Android/armeabi-v7a/debug_static/AsyncChannel.o' failed
make[1]: **\* [/home/lvmc/Desktop/poco-1.6.1/Foundation/obj/Android/armeabi-v7a/debug_static/AsyncChannel.o] Error 1
/home/lvmc/Desktop/poco-1.6.1/build/rules/compile:37: recipe for target '/home/lvmc/Desktop/poco-1.6.1/Foundation/obj/Android/armeabi-v7a/debug_static/Ascii.o' failed
make[1]: **\* [/home/lvmc/Desktop/poco-1.6.1/Foundation/obj/Android/armeabi-v7a/debug_static/Ascii.o] Error 1
Makefile:69: recipe for target 'Foundation-libexec' failed
make: **\* [Foundation-libexec] Error 2

**Comment by Grabber** [comment]
Same behaviour from latest version from git repository.

**Comment by Brandantl** [comment]
Was able to reproduce this issue on Linux Mint 17.1.


** Compiling src/ArchiveStrategy.cpp (debug, static)
arm-linux-androideabi-g++  -Iinclude -I/home/brandan/poco-1.6.1/CppUnit/include -I/home/brandan/poco-1.6.1/CppUnit/WinTestRunner/include -I/home/brandan/poco-1.6.1/Foundation/include -I/home/brandan/poco-1.6.1/XML/include -I/home/brandan/poco-1.6.1/JSON/include -I/home/brandan/poco-1.6.1/Util/include -I/home/brandan/poco-1.6.1/Net/include -mthumb -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -frtti -fexceptions -DPOCO_BUILD_HOST=brandan-P5K-E  -DPOCO_ANDROID -DPOCO_NO_FPENVIRONMENT -DPOCO_NO_WSTRING -DPOCO_NO_SHAREDMEMORY  -g -D_DEBUG  -c src/ArchiveStrategy.cpp -o /home/brandan/poco-1.6.1/Foundation/obj/Android/armeabi/debug_static/ArchiveStrategy.o
In file included from include/Poco/Foundation.h:148:0,
                 from include/Poco/ArchiveStrategy.h:23,
                 from src/ArchiveStrategy.cpp:17:
include/Poco/Bugcheck.h:24:18: fatal error: string: No such file or directory
compilation terminated.
make[1]: *** [/home/brandan/poco-1.6.1/Foundation/obj/Android/armeabi/debug_static/ArchiveStrategy.o] Error 1
make[1]: Leaving directory `/home/brandan/poco-1.6.1/Foundation'
