### ISSUE TITLE
Poco File  and Path decode/encode issue 

### ISSUE THREAD

**Issue by lion117** [pocoproject/poco#1098]
Hi , There are some decode/encode issues in Class Poco::File  & Poco::Path which could not compatibility with chinese path 
eg: 
```C++
/// software located path 
"C://安装路径/测试软件.exe"

Poco::Path.current() ;   // could not work well , return messy code 

/// target file
string i_target = "C://测试路径/例子.txt";

Poco::File i_finder(i_target);
i_finder.exist();      // could not find file even file do exist 
```

BTW , Hoping Poco::Path could add a function to retrieve current software directory 
something like :
```C++
 std::string getCurrentDir()
{
	char buffer[MAX_PATH];
	GetModuleFileNameA(NULL, buffer, MAX_PATH);
	Poco::Path i_path(buffer);
	return std::string(i_path.parent().toString());
}
```

although Path::current could work, but it could not work very well in IDE debug state
eg:

- Bin
  - demo.exe            // wish to retrieve this path in IDE debug state 
- source
  -demo.vcxproj        // in debug state  , Path::current would get source directory , instead Bin directory 

It seems  Util Application contain such a function , but it looks not so directly and easy to use

**Comment by aleks-f** [comment]
You are asking for the executable binary path base name (which is [available in Application](https://github.com/pocoproject/poco/blob/d69878cdd5e0b13915884d5cf0159b20bf440a6c/Util/include/Poco/Util/Application.h#L78)), not current directory. Doing it in a multi-platform way is possible but not so simple without access to `argv`, see [here](http://stackoverflow.com/a/1024937/205386).

**Comment by lion117** [comment]
thanks for your reply. I think I did not describe my questions clearly . accurately , i had two questions
1. decode/encode issues
2. retrieve working directory  with  a **simple POCO::API**
Thanks to your help and Poco authorized demo , I found it in Util  Folder. 


# first issue 
It seems poco 1.60 release  version  had serious issues  on decode/encode aspect 
like:
json parser could not parse strings which contain chinese letters 
Poco::File::exists()  could not tell the exactly result if the filename contain chinese letters 
Poco::Path.current() ;   // could not work well , return messy code   "C://安装路径/测试软件.exe"

**Comment by aleks-f** [comment]
where exactly is the encoding/decoding here:
```
string i_target = "C://测试路径/例子.txt";
Poco::File i_finder(i_target);
```

**Comment by lion117** [comment]
sorry , my bad. Here is my debug result : 
![q -20151230171429](https://cloud.githubusercontent.com/assets/3996029/12048668/e807f584-af18-11e5-9591-5a439d4e3525.png)
![q -20151230171444](https://cloud.githubusercontent.com/assets/3996029/12048669/ebeb971e-af18-11e5-88df-7694ec81eb57.png)

![q -20151230171429](https://cloud.githubusercontent.com/assets/3996029/12048664/e158db7c-af18-11e5-8197-d64601960023.png)

**Comment by aleks-f** [comment]
I am not familiar with boost, but I would guess that a combination of your OS locale, character set used for your application and boost using [codecvt](http://www.boost.org/doc/libs/1_60_0/libs/filesystem/doc/reference.html#path-Encoding-conversions) takes care of things. For string unification and portability problems, see [Portable String Literals in C++](http://accu.org/index.php/journals/1842), "How Boost filesystem doesn’t help" chapter in particular.

All Poco interfaces expect UTF8 strings; use multi-byte character set for your application and convert the filename string before using it to create File object.

**Comment by lion117** [comment]
My system default character set is GB2312 . I had try to switch my IDE character set from **Unicode character set**  to **multi-byte character set** ,  But the result is the same . Boost worked , but Poco could not be compatibility with Chinese words very well.

**Comment by aleks-f** [comment]
UTF8 will work but you will have to write encoding for it or use another library. How did you convert the name to UTF8?

**Comment by lion117** [comment]
You are right  . after converter string from GBK character set to **UTF-8** , Poco could work well (but awful to display) .
My computer default character set is **GBK** (default simple chinese language ), So , string container would take it as character Set . 

Here is code which could work with Poco 
```C++
	string i_target = "C://测试路径/例子.txt";
	string i_uft8 = boost::locale::conv::between(i_target, "UTF-8", "GBK" );
	File i_finder(i_uft8);
	if (!i_finder.exists())
	{
		cout<< "file not exist"<<endl;
	}
```
