### ISSUE TITLE
c++11/VS2013:  testMutexRecursion: f:\dd\vctools\crt\crtw32\stdcpp\thr\mutex.c(40): mutex destroyed while busy

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#1100]
Hi

With the latest c++11 branch on Win7 with VS2013 in static_mt mode, one gets the exception below

testMutexRecursion: f:\dd\vctools\crt\crtw32\stdcpp\thr\mutex.c(40): mutex destroyed while busy
f:\dd\vctools\crt\crtw32\stdcpp\thr\mutex.c(40): mutex destroyed while busy

**Comment by zosrothko** [comment]
Not reproduceable...

**Comment by BWJHJ** [comment]
Hi .Have you desolved this problem?
