### ISSUE TITLE
Contributing Dockerfiles

### ISSUE THREAD

**Issue by Mazyod** [pocoproject/poco#1110]
Hello,

I've used Poco to build a realtime game server, and now working on using it for an HTTP web server. I really appreciate the recent Redis contribution, it saved me some time.

The point I wanted to reach is, I will be writing some dockerfiles to bootstrap the server with the necessary dependencies. I thought it would be useful for the Poco community if there was a way developers can share and discuss dockerfiles for various use cases, like HTTP server, websocket server, ... etc.

I could just contribute those to DockerHub, but was interested in hearing your thoughts about this. Is this something you'd like to manage along side the library, or is it out of scope?

Thanks,

**Comment by aleks-f** [comment]
It would be useful for development and testing, especially for running testsuites that depend on external servers, e.g. mysql, mongodb, redis etc. as well as testing various gcc/clang compiler versions. Whether this should all be in one container or multiple, I'm not sure yet - I guess it would depend on resources.

I have created [poco repository](https://hub.docker.com/u/poco/), send me your username and I'll add you there so you can create containers.

**Comment by Mazyod** [comment]
Thanks Alex, glad to hear you guys are embracing docker. My username is "Mazyod", same as here.

This is the initial working docker file I created to give me a container with built Poco libraries and configured Postgres configuration, but I'll need to improve it before pushing it to the repo. I'll post it here to encourage contributions:
https://gist.github.com/Mazyod/9159d327643c615354bd
