### ISSUE TITLE
How to build poco with redis component on windows7?

### ISSUE THREAD

**Issue by WillDebbie** [pocoproject/poco#1112]
I have built poco(branch:poco-develop) on windows7 using the command below:
buildwin 120 build shared both x64 nosamples notests msbuild

I have installed Microsoft Visual Studio 2013 and
the content of the components file like this:
CppUnit
CppUnit/WinTestRunner
Foundation
XML
JSON
Util
Net
Crypto
NetSSL_OpenSSL
NetSSL_Win
Data
Data/SQLite
Data/ODBC
Data/MySQL
Zip
PageCompiler
PageCompiler/File2Page
PDF
CppParser
MongoDB
Redis
PocoDoc
ProGen

But there was nothing about redis generated,but others(eg:MongoDB) did;

**Comment by fbraem** [comment]
@obiltschnig can you generate all the Visual Studio solution files for Redis?

**Comment by obiltschnig** [comment]
Yes, can do that.
