### ISSUE TITLE
World-write permissions on files created by daemon

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#1114]
When ServerApplication starts, it [clears the inherited umask](https://github.com/pocoproject/poco/blob/develop/Util/src/ServerApplication.cpp#L693).

While this is something that needs to be done in order to avoid unintended interference with permissions of the files created by the daemon itself, it has an undesirable consequence that files created by daemon (e.g.  log files, pidfile etc) end up being created world-writable. This should be set to something more reasonable and secure (e.g. at least 664) for the files created by Poco.

**Comment by obiltschnig** [comment]
Fix: set default umask to 027 and added --umask command-line parameter to override default.
