### ISSUE TITLE
Error in VarHolder::checkUpperLimit

### ISSUE THREAD

**Issue by zack-snyder** [pocoproject/poco#1122]
From browsing your source code I think I found an issue in:
https://github.com/pocoproject/poco/blob/poco-1.7.2/Foundation/include/Poco/Dynamic/VarHolder.h#L400

Doing a conversion from Uint8(200) to Int8 should result in undefined behavior.

I think it should be

```
else if (from > static_cast<F>(std::numeric_limits<T>::max()))
```

But then the first if statement seems to be not needed anymore...

I have no test suite here, so verify this behavior first.

**Comment by aleks-f** [comment]
see [explanation](https://github.com/pocoproject/poco/pull/1904#issuecomment-332403553)
