### ISSUE TITLE
Question: workaround for pocomsg.mc?

### ISSUE THREAD

**Issue by VikingExplorer** [pocoproject/poco#1125]
Question: what's the work around for getting this weird error:

Performing Custom Build Tools
1>mc : error : 0x2 trying to open file <C:\Dev\Couloir\3pLibs\poco-1.6.1\Foundation\src\pocomsg.mc>.

**Comment by zosrothko** [comment]
pocomsg.mc should be here: ..../poco/Foundation/src/pocomsg.mc

**Comment by VikingExplorer** [comment]
It is there.

**Comment by zosrothko** [comment]
use git instead of downloading the zipfile...
