### ISSUE TITLE
Build For Android using Visual Studio?

### ISSUE THREAD

**Issue by VikingExplorer** [pocoproject/poco#1126]
How do I build POCO for Android using VS2015?

**Comment by aleks-f** [comment]
no support for that, afaik

**Comment by VikingExplorer** [comment]
Can I build on a Windows machine?

**Comment by aleks-f** [comment]
you can build poco on windows for windows. there is no currently support to build for android on windows. you have to use Linux or maybe you can use windows with cygwin, but I'm not expert in this matter. @RangelReale will know more

**Comment by VikingExplorer** [comment]
With the makefile provided in the "POCO C++ Libraries Android Platform Notes", I should be able to create a VS project file for Android.  Which compiler is preferred, GCC or CLANG?

**Comment by VikingExplorer** [comment]
Where is the list of source files, or is every file in the src directory included in Android builds?

**Comment by RangelReale** [comment]
I only built Poco on Linux, using the instructions at http://pocoproject.org/docs/99300-AndroidPlatformNotes.html, which uses the standalone toolchain. Once I tried compiling in Windows, but it was too much hassle, and in Linux it compiles very easily.

**Comment by VikingExplorer** [comment]
Can I assume that all source files included in Windows builds should be included in Android builds?

**Comment by RangelReale** [comment]
The Android build uses the default Linux build, using Makefiles. If you compile in Windows using the Makefiles, yes, all files are included on the android build.
