### ISSUE TITLE
Poco::NumberFormatter::format(float, precision) rounding changed

### ISSUE THREAD

**Issue by tavi-cacina** [pocoproject/poco#1128]
```
float f = 12.45f; // represented as 12.4499998
string s = Poco::NumberFormatter::format(f, 2); 
```

In older Poco s == "12.45"
In newer Poco s == "12.44"

That is probably because of this change:

commit 91d5be438b3c03d68096aee5b04bb3566e7e95a7

> replaced stream-based number formatting 
> embedded a portion of double-conversion library (http://code.google.com/p/double-conversion/) and replaced stream-based number formatting

I see in NumericString.cpp function pad():
    else if ((frac > precision) && (decSepPos != std::string::npos))
      str = str.substr(0, decSepPos + 1 + precision);

At input str is "12.449999809265137"
On output becomes "12.44"

**Comment by aleks-f** [comment]
yes, this should have been done by rounding before truncating.

**Comment by obiltschnig** [comment]
Received a similar bug report from a customer. This should be fixed for 1.7.0.

**Comment by obiltschnig** [comment]
@aleks-f could you look into this?

**Comment by obiltschnig** [comment]
fixed this, at least for NumberFormatter, by adding floatToFixedStr(), etc. There's still the issue with floatToStr()/doubleToStr() with precision and width - the result could still be truncated and not properly rounded, due to pad(). NumberFormatter::format() with precision always uses fixed format now.

**Comment by aleks-f** [comment]
@obiltschnig : fixed, not sure if you will include this in 1.7 or not, so I did not commit there

**Comment by obiltschnig** [comment]
TODO: merge 9fef033 and ad492bd into poco-1.8.0 branch

**Comment by aleks-f** [comment]
all done
