### ISSUE TITLE
Poco::JSON::Stringifier::stringify with vector, list, deque, struct prepends and appends double quotes

### ISSUE THREAD

**Issue by Burgch** [pocoproject/poco#1130]
The change introduced in a787b4f898b906ddf421aa07247579ab5e024c38 means that `vector`, `list`, `deque` and `struct` are prepended and appended with double quotes by the call to `formatString`. This produces incorrect JSON for e.g. a vector of integers, which one would expect to produce an array of integers, and not a string (although the string does contain the JSON representation of an array of integers).

**Comment by aleks-f** [comment]
should be extended with [inspection for containers](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Dynamic/Var.h#L439)
