### ISSUE TITLE
Poco::Data::MySQL TRIGGER

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1133]
I found a strange problem when I create trigger in MYSQL.
In SQlite it' works without problem.
In MySQL if I use the Poco Data Session to push the trigger query it seams to work (it's do not throw any error) but the trigger is not created.
If I use the same query to create the trigger using for example the function mysql_real_query directly the trigger is created.
Have you ever experienced this kind of behavior?

**Comment by aleks-f** [comment]
@micheleselea can you provide code reproducing this?

**Comment by micheleselea** [comment]
Ok let me dig a little bit in my code because it was a very old issue

**Comment by micheleselea** [comment]
Ok I take a simple TRIGGER from MySQL
 This is what I did to make TRIGGER work
```
try {
	std::string sConnectionString;
	Poco::format(sConnectionString, "host=%s;db=%s;user=%s;password=%s;compress=false;auto-reconnect=true", sServer, sDBName, sMySqlUsername, sMySqlPassword);

	Poco::Data::Session cSession(Poco::Data::SessionFactory::instance().create(Poco::Data::MySQL::Connector::KEY, sConnectionString));
	
	cSession << "CREATE TABLE account (acct_num INT, amount DECIMAL(10,2));", Keywords::now;
	
	Poco::Any h = cSession.getProperty("handle");
	MYSQL* pDB = Poco::AnyCast<MYSQL*>(h);
	if (pDB == nullptr)
		throw Poco::BadCastException("pDB nullptr");

	std::string sql;
	int rc = 0;

	sql = "CREATE TRIGGER ins_sum BEFORE INSERT ON account FOR EACH ROW SET @sum = @sum + NEW.amount;";
	rc = mysql_query(pDB, sql.c_str());
	if (rc != 0) {
		if (mysql_error(pDB) != nullptr) {
			sql = "CREATE TRIGGER1 (already exists?) error ";
			sql.append(mysql_error(pDB));
		}
	}
}
catch (Poco::Exception& exc) {

}
```

If I simply do somethink like
`cSession << "CREATE TRIGGER ins_sum BEFORE INSERT ON account FOR EACH ROW SET @sum = @sum + NEW.amount;", Keywords::now;`

Instruction fail

**Comment by aleks-f** [comment]
well, I'm getting this:
```
mysql_stmt_prepare error
[mysql_stmt_error]: This command is not supported in the prepared statement protocol yet
[mysql_stmt_errno]: 1295
[mysql_stmt_sqlstate]: HY000
[statemnt]: CREATE TRIGGER Strings AFTER INSERT ON Strings FOR EACH ROW SET @sum = @sum + NEW.str;
```
See "[SQL Syntax Allowed in Prepared Statements](https://dev.mysql.com/doc/refman/5.7/en/sql-syntax-prepared-statements.html)'
I'l leave this open as question, if you care to look further into this, there's a [branch](https://github.com/pocoproject/poco/tree/mysql-trigger) with failing test
