### ISSUE TITLE
Different package on github and official web site

### ISSUE THREAD

**Issue by lgm42** [pocoproject/poco#1135]
I'm using the poco 1.6.1 full official package on your website at the UrI:
http://pocoproject.org/releases/poco-1.6.1/poco-1.6.1-all.zip

And the build_vs140.cmd is missing.

But I download the package onto your github at the uri:
https://github.com/pocoproject/poco/releases/tag/poco-1.6.1-release

And the file is present.
Are there other differences ? What is the most recommended package ?

**Comment by jano42** [comment]
+1

**Comment by zosrothko** [comment]
This was a bug in the release process script release/script/mkdrelease. It is fixed in the develop branch

**Comment by obiltschnig** [comment]
fixed in 1.6.2
