### ISSUE TITLE
How to set MongoDB writeconcern trough POCO?

### ISSUE THREAD

**Issue by nolate** [pocoproject/poco#1136]
Hey!
I'm making an application which works on collections trough 20 threads and each thread makes an insert, 4 updates, 1 query, copy the query response to an other collection than delete the row from the first collection. To find the correct row I use a unique atomic integer. Both 20 threads repeat this at least 2000 times. 
My code: Just tried to add that writeConcern document but its just worse.
```cpp
void MongoDatabaseTest::ConnectionsUpdateRow(
  Poco::MongoDB::UpdateRequest &updateRequest,
  std::string element,
  std::string newElement
)
{
  Poco::MongoDB::Document &selector = updateRequest.selector();
  Poco::MongoDB::Document &update   = updateRequest.update();

  selector.add(element, "0");
  update.addNewDocument("$set").add(element, newElement);

  /*
  update.addNewDocument("writeConcern")
        .add("w", "4")
        .add("j", "true")
        .add("wtimeout", "5000");
  */
  try {
    Connection.sendRequest(updateRequest);
    
  } catch (...) {
    printf("Update catch \n");   
  }

  selector.clear();
  update.clear();
}
```
My problem is some of the queries are not updated. 
The replica set works with MMAPv1 engine due to the high volume of data moving.
Thanks!

**Comment by fbraem** [comment]
If I read the documentation correctly you should use getLastError to handle writeConcern. Send a getLastError command after an insert or update.

**Comment by nolate** [comment]
You did read it correctly and thanks for your answer. I found that solution also but on pocoproject.org the documentation for MongoDB offers me a getLastError function which is (http://pocoproject.org/docs-1.5.2/Poco.MongoDB.Database.html#19081):
`cpp
std::string getLastError(Connection & connection) const;
`
In this I cant set write concern based on Mongo docs (getLastError: 1, w: "majority", wtimeout:5000)

Cheers!

**Comment by fbraem** [comment]
As a workaround you can create your own getLastError command like it is done in the Database class. I will add writeConcern to my todo-list.

**Comment by nolate** [comment]
According to MongoDB docs:
>Changed in version 2.6: A new protocol for write operations integrates write concerns with the write operations and eliminates the need to call the getLastError command. Previous versions required a getLastError command immediately after a write operation to specify the write concern.

In my opinion it would be better to let update and insert requests to have a response message and maybe to add write concern / read preference parameter to the requests.

```
db.collection.insert(
   <document or array of documents>,
   {
     writeConcern: <document>,
     ordered: <boolean>
   }
)
```

Thanks for you fast answer!
I really enjoyed working with POCO but seem like sadly have to change to C driver. 
Cheers!

**Comment by fbraem** [comment]
The POCO implementation uses the wire protocol and I don't find any information about writeConcern in the documentation: https://docs.mongodb.org/manual/reference/mongodb-wire-protocol
Insert, update and delete don't return a response, so I suppose that your example is also calling getLastError when doing the insert ... Such a call can be added to POCO.

**Comment by nolate** [comment]
You are right. Thanks a lot for helping me. I'll try to solve it with POCO. At last could you help me with db.getMongo().setReadPref()? I cant see how to set it trough POCO.
