### ISSUE TITLE
Poco generated PDF doesn't respect transparency of images

### ISSUE THREAD

**Issue by AttitudeMonger** [pocoproject/poco#1140]
I am trying the basic PDF example as given in the PDF samples. This is my code:

``` C++
        File pdfFile(Path::expand("/Users/attitude/Desktop/sample.pdf"));
        if (pdfFile.exists()) pdfFile.remove();
        File pngFile(Path::expand("/Users/attitude/Desktop/RnSghvV.png"));

        Document document(pdfFile.path());

        Page page = document[0];
        Font helv = document.font("Helvetica");
        page.setFont(helv, 24);

        std::string hello = "Hello PDF World from ";
        float textWidth = page.textWidth(hello);
        float textBegin = (page.getWidth() - textWidth) / 2;
        page.writeOnce(textBegin, page.getHeight() - 50, hello);

        Image image = document.loadPNGImage(pngFile.path());
        page.drawImage(image, 100,
                80,
                image.width(),
                image.height());

        document.save();
```

The image is attached. As you can see, the image has no background when opened in an image viewer. However, in the PDF generated by Poco, the image has an ugly black background at the borders of the image. PDF also attached.

Is there a way around it?
![rnsghvv](https://cloud.githubusercontent.com/assets/7725182/12687194/60bbe59c-c6f4-11e5-9bd4-d60564c8340d.png)

Image is coming as:

<img width="567" alt="output" src="https://cloud.githubusercontent.com/assets/7725182/12687228/8e82acea-c6f4-11e5-8449-d91d94a76c20.png">

[sample.pdf](https://github.com/pocoproject/poco/files/110366/sample.pdf)

**Comment by aleks-f** [comment]
PDF is not actively maintained nor is it part of the releases, so - use at your own risk. If you wish to contribute, that is welcome, too. It is based on [libHaru](http://libharu.org/) - a good library, but it also appears not to be actively maintained.

**Comment by AttitudeMonger** [comment]
Can you tell me where the code for drawPage lies, so that I can find out how you are using libHaru to draw the image?

**Comment by aleks-f** [comment]
This habit of asking for information that is easily accessible is not making me happy - there's a repository search box right up there ^^^. 

You are probably looking for drawImage(); surprisingly, it is in [Page.h](https://github.com/pocoproject/poco/blob/f3995e336f9a9b8a07f503027ff769b5affa1276/PDF/include/Poco/PDF/Page.h#L1114)

**Comment by AttitudeMonger** [comment]
Sorry, but I looked into Page.cpp and couldn't find it, that's why asked. Yes I was talking about drawImage().

**Comment by AttitudeMonger** [comment]
Did not know about the repository search feature, that's pretty neat. Thanks.

**Comment by muratkarakus7** [comment]
Regarding the "finding drawImage() function", I would like to make a better
suggestion.

For reading large code bases, I suggest to use the Eclipse tool.  Though, I
am a huge fan of the VIM, I still value the Eclipse and its pretty robust
code navigation features.

Find the code navigation shortcuts here and master them :)
http://rayfd.me/2007/05/20/10-eclipse-navigation-shortcuts-every-java-programmer-should-know/


*--*

*Regards,KARAKUS Murat*

**Comment by AttitudeMonger** [comment]
Thanks.. :)

Meanwhile, Aleks, I tried adding one more page to the document after the code I have given above. I just tried `document.addPage()`, and it fails with the error message

```bash
libc++abi.dylib: terminating with uncaught exception of type Poco::IllegalStateException: Illegal state
Abort trap: 6
```

Strangely, I wrapped this code in a try-catch block, still the code is not coming to catch. Is the addPage() API not fully functional?

**Comment by AttitudeMonger** [comment]
The source code reveals that it internally uses `HPDF_AddPage`, which is pretty standard as I see from Haru documentation. So I am probably not using it correctly. Any pointer will be helpful.. :)
