### ISSUE TITLE
POCO 1.6.1   Poco::XML::DOMParser  undefined entity "&nbsp;"

### ISSUE THREAD

**Issue by zhutuo** [pocoproject/poco#1144]
Hi:
     when I use Poco::XML::DOMParser to parser html,it throw exception undefined entity when there is `"&nbsp;"` characters.What should I do to fix  it?
     For example:
 ```
  const std::string THTML =
"<p class=\"feature-text\">\n"
"\t\t<span id=\"localeBlockingLabel\" class=\"feature-title\">Manage Blocking:</span>\n"
"\t\t<span class=\"feature-title\">&nbsp;</span>\n"
"\t\t<span id=\"localeBlockingDescription\" class=\"feature-title\">You can disable adblocking for some websites. Manage your list of websites for which you want to see ads.</span>\n"
"</p>";

 try
{
       DOMParser parser;
	//parser.setFeature(XMLReader::FEATURE_NAMESPACES, true);
	//parser.setFeature(XMLReader::FEATURE_NAMESPACE_PREFIXES, true);

	AutoPtr<Document> pDoc = parser.parseString(THTML);
	NodeIterator it(pDoc, NodeFilter::SHOW_ALL);
	Node* pNode = it.nextNode();
	while (pNode)
	{
		std::cout << pNode->nodeName() << ":" << pNode->nodeValue() << std::endl;
		pNode = it.nextNode();
	}
}
catch (Exception& exc)
{
	std::cerr << exc.displayText() << std::endl;
}
```

**Comment by obiltschnig** [comment]
&nbsp; is not a standard XML entity, it's a HTML entity defined in the XHTML DTD. You'll have to parse the XHTML DTD by referencing it in the document's XML declaration in order for the parser to recognize this and other XHTML entities.

Another option is to provide a LexicalHandler to the parser and implement the skippedEntity() method. &nbsp; and other entities will be reported though this.
See the SAXParser sample for how to do this.
