### ISSUE TITLE
Move to standard integer types

### ISSUE THREAD

**Issue by Burgch** [pocoproject/poco#1147]
On Mac, compiling with Clang (from Xcode 6.2), `Poco::Int64` resolves to `long`, whereas `boost::int64_t` and the <cstdint> `int64_t` resolve to `long long`, which then causes issues when setting an int64_t in a DynamicVar and converting it back to int64_t, unless everything is explicitly cast to Poco::Int64 and back.

**Comment by obiltschnig** [comment]
Changing the definition of Poco::Int64 and Poco::UInt64 will require a lot of changes (in Dynamic::Var and other classes), so not sure I will do this, as it could potentially break existing code.

**Comment by obiltschnig** [comment]
Will handle that in 2.0.

**Comment by mltucker** [comment]
Ran into this on iOS for the arm64 architecture.  And it's a big problem for us since Apple is dropping armv7 support in iOS 11!

**Comment by Burgch** [comment]
I believe I have a workaround where, if `POCO_LONG_IS_64_BIT ` is defined, template specialisations for `long long` and `unsigned long long` (which `int64_t` and `uint64_t` map to on macOS) are added to `Poco::Dynamic::VarHolderImpl`, along with all of the necessary conversion functions. This seems to be passing the tests I've added and prevents the `BadCastException`s that you would see if you optimistically used `(u)int64_t` with e.g. `Poco::JSON::Object`. Would this be an acceptable addition for Poco 1.8.0?

**Comment by aleks-f** [comment]
@Burgch for 1.x line of releases, yes - coordinate contribution with @obiltschnig. 
2.0 (ie. current develop branch) will be based on &lt;cstdint&gt;

**Comment by aleks-f** [comment]
@obiltschnig this turned out to be more complicated than expected. basically, the stumbing block is 64 bit long on clang - as things are now, when long is 64-bit, there is no way to pass long and unsigned long to NumberFormatter and BinaryReader/Writer - only Poco::(U)Int64.
