### ISSUE TITLE
getting ERRFMT from format

### ISSUE THREAD

**Issue by VikingExplorer** [pocoproject/poco#1159]
I'm having trouble understanding the format function. It's like magic. I've got a String class that encapsulates a wstring.

void Log::debug_msg( const String& fmt, const Any& value )
{
	auto msg = format( fmt, value );

It seems to figure out the string by calling the basic_string operator? I've also got lots of code with %ls. Desperately searching for what this could have meant. Should I globally replace this with %s? Is %S supported?  Any help would be appreciated.

![errfmt](https://cloud.githubusercontent.com/assets/15109208/13219222/94ed383e-d93c-11e5-84f7-e435859a5113.PNG)

**Comment by VikingExplorer** [comment]
Do I need to check out CppFormat?  I was hoping that Poco would be a one stop shop.

**Comment by obiltschnig** [comment]
Reading the documentation of [Poco::format()](http://pocoproject.org/docs/Poco.html#12498) would also help ;-) However, Poco::format() currently does not support std::wstring.

**Comment by VikingExplorer** [comment]
Gunter, I have read the docs. It wasn't clear that this is the problem. The fmt variable is my Couloir::String object, encapsulating a wstring.  However, as the image shows, the string operator is called to populate the msg. The ERRFMT indicates that %s is an incorrect specifier, but it's in the documentation.  Any ideas on what the problem is or how to fix this?

**Comment by aleks-f** [comment]
Yes, it is in the documentation and it says clearly that `%s` is for `std::string`. Since you are not passing the correct type, you get `ERRFMT`, which is also documented:
```Starting with release 1.4.3, an argument that does not match the format specifier no longer results in a BadCastException. The string [ERRFMT] is written to the result string instead.```

**Comment by VikingExplorer** [comment]
I guess I'm not getting the point of the Any class. My class has a std::string operator. How did it decide what to do with the object I passed in? I certainly didn't pass it a wstring.

**Comment by aleks-f** [comment]
Your code does not show what was put in the `Poco::Any`. But, whatever type you put in there, you can only get exactly the same type out - there's [no conversion](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Any.h#L493) whatsoever in `Any`, not even implicit.

**Comment by VikingExplorer** [comment]
So, it's back to the format function. It correctly interpreted the Couloir::String object passed into the first argument, but does not do the same for the 2nd argument.  Is that a correct analysis?

**Comment by aleks-f** [comment]
Probably. Your `std::string` cast did the job for `fmt`, but there is really no such thing as type casting for `Any`, so extracting `string` from `Any` holding `wstring` fails. It is always a good idea to provide a [http://www.sscce.org/](http://www.sscce.org/) - screenshots don't do nearly good job.

**Comment by VikingExplorer** [comment]
Ok, thank you. This has helped me see the way forward. I'll add another function for String and leave Any version for floats & ints:

static void debug_msg( const String& fmt, const Any& value1, const Any& value2 );
static void debug_msg( const String& fmt, const String& value1, const String& value2 );

I find it odd that if it doesn't support wstring, it still compiles. I took a look at Any.h, but couldn't immediately see why this is ambiguous. I think I can fix this by being careful not to pass a wstring.

2>Model\RecordList.cpp(276): error C2668: 'Couloir::Log::debug_msg': ambiguous call to overloaded function
2>  C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Include\Log.hpp(26): note: could be 'void Couloir::Log::debug_msg(const Couloir::String &,const Couloir::String &,const Couloir::String &)'
2>  C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Include\Log.hpp(21): note: or       'void Couloir::Log::debug_msg(const Couloir::String &,const Poco::Any &,const Poco::Any &)'
2>  Model\RecordList.cpp(276): note: while trying to match the argument list '(const char [89], const std::wstring, const std::wstring)'

**Comment by aleks-f** [comment]
It compiles because type check happens [at runtime](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Any.h#L493), not at compile time. `std::wstring` is pretty much useless from portability standpoint and Poco does not support it in that sense - it is only used "behind the scene", in some Windows specific cases.

**Comment by VikingExplorer** [comment]
wstring not portable?  really, that would be disturbing if true. I've got 8 modules (~50k LOC C++) that were originally created for WinDesktop. I've gotten the first of my 8 modules building on Android & iOS. No problem with wstring. 

Looks like I'll have to come up with a different approach, because Any isn't working for me.  LOC like this:

	Log::debug_msg( "\t Dumping Error %d of %d", i + 1, nCount );

are matching up with both, because I have ctors for String that accept a float and int. With just a one-hop conversion either way, it's ambiguous.

**Comment by aleks-f** [comment]
It's not that wstring is not portable - it is, it's just a `std::basic_string`, after all. The problem is that wide char "width" is not standardized.

**Comment by obiltschnig** [comment]
And not just character width - also encoding. 

--
Günter Obiltschnig
Applied Informatics Software Engineering GmbH

**Comment by VikingExplorer** [comment]
While I have you two, do I really have to create a Linux VM in order to build Poco for Android?

**Comment by aleks-f** [comment]
I have no clue and I don't know anyone on Poco team with more Android expertise than @RangelReale, who already [answered](https://github.com/pocoproject/poco/issues/1126) that question. It's a Makefile-based build, probably best to ask on an Android or VS forum how to deal with that.

**Comment by RangelReale** [comment]
It's very easy to compile Poco on Android, so I never tried any other way.

**Comment by VikingExplorer** [comment]
You mean, "compile on Linux", right? What do you mean, compile on Android?

**Comment by RangelReale** [comment]
Ops sorry, compile on Linux of course!

**Comment by VikingExplorer** [comment]
Based on the above, I gather that you may not want constructive feedback, but just in case, here is some:

I've been interested in Poco for some time now. At some point, my company plans to replace our ASP.NET Web API REST web services with a C++ implementation.  There are several possibilities, include MS Casablanca and POCO Remoting. The price seems reasonable. We're using our experiences with POCO as way to help us evaluate.  We're very concerned about open source projects, because they tend to be unsupported dead ends.  POCO seemed better than your average open source project, since it seems to have active leaders updating and supporting it.

The feeling I got from this exchange:  responses seem defensive and somewhat arrogant. Referencing the format documentation, but not the very skimpy Any documentation? Most of the documentation is simply auto-generated from comments. Any neutral observer can see that I asked nicely about what I was confused about.

I've got over 30 years of software development experience. I'm quite familiar with make files, thank you for assuming. I know quite well that make files are NOT OS specific. In fact, it's quite easy to create a Makefile project using Visual Studio (https://msdn.microsoft.com/en-us/library/txcwa2xx.aspx).

This brings up a glaring question: Why haven't they been willing to take the few minutes (an hour?) to get this building for Android on Windows?  Compared to the time to create and test all of this software, it's quite a mystery. However, the above comments seem to indicate a bias? Is there a disdain for Windows?

Maybe I'm wrong, since you're carrying around legacy VS solutions (2013, 2012, 2010 and 2008), someone has spent a lot of time on Windows. Maybe you're not aware that Visual Studio 2015 supports Android builds using either Clang or GCC. It seems like common sense to drop support for VS 2008 (8 years old), 2010 and 2012 and add full support for VS 2015. This would include projects for both Android and iOS.

Our intention is to perhaps target Linux eventually, but with only ~1% of the market, it's hardly a priority.  I'm reminded of this http://www.techrepublic.com/article/can-we-please-stop-talking-about-the-linux-desktop/

I can't help but question the common sense of anyone who seems obsessed with some half-forgotten OS like Linux. I hope my impression is wrong about that. If Windows is looked down upon by the creators of POCO, even though it has 90% market share on the desktop, while Linux is considered something great with its measly 1.7% market share, I may have to reevaluate.

**Comment by fleahy** [comment]
First time commenting but I think this warrants a comment...

I can see arrogance in both sides, but I think you seem to want top level support from an open source and free library. I don't think you get this type of quick response from paid-for and closed source companies costing thousands. Usually you first hit support which then tries to fob you off and if you're lucky and can convince them to pass it on you might eventually make it to a developer. Here you're getting direct help from the main developers themselves, and the response times are amazing. 

I think a lot of the Poco libraries are meant for server-type programs. For server-type programs, specially Web API REST interfaces like you mention I think you'll find the proportions are reversed and there are a lot more Linux machines being used than Windows. Windows does have a much stronger market share of the desktop, but that reverses for servers for a number of reasons. 


I am using Poco extensively and it does have it flaws as do a lot of libraries. But it's open, if you see a way to fix it then by all means do it and contribute back! Send a pull request with good quality code and I'm sure they'd be glad to take it.

**Comment by VikingExplorer** [comment]
Fleahy,

Several points. There is a gap of 24 hours between my question and the first answer. There is no apparent arrogance in my entries until 35 minutes ago. Almost every one of the responses is snarky and/or flippant. I certainly do get good response from companies in the business of selling software. I've had extensive email discussions with the main developers of Casablanca at Microsoft.

You're whole discussion of Linux has one answer:  Do developers create software on Servers?

The whole OS server thing is skewed because Linux is the most common choice for low cost hosting companies. These servers are not targets for application development.

For applications targeting Azure and SQL Server, Windows Server is the logical choice.

As for being "Open", I don't see that as a clear advantage. In large part, Open Source is where software goes to die.  When it can't be monetized, it's put into Open Source. We have an endless roadmap ahead of us, and we have no interest in "contributing back".

Ok, so I'm getting the message that POCO is intended for people working in hosting facilities developing software directly on servers, and not for people using wstring (because it's really a std::string after all?).  Very strange.

I'll have to take all this into consideration, because we're developers using VS on Windows 10 desktops and laptops, targeting Android, iOS and Windows.  Not feeling welcome.

**Comment by aleks-f** [comment]
Well, I think several points here need response:

First of all, the intent of my answers was to help and explain, not to be arrogant.

Documentation is very clear - it states that `%s` is for `std::string` and there is no mention of `std:wstring` (which is entirely different type) support anywhere, plus there is the explanation what the outcome of using unsupported data type is. Please don't pass judgment on us for something that is a logical consequence of not reading documentation carefully enough. When you asked, I explained thoroughly the entire mechanism behind it.

The `std::wstring` is a `std::basic_string<wchar_t>` typedef, so any `std::wstring`-based code will compile just fine on any standard-compliant compiler and any supported platform. How it will behave is an entire different story - as Günter and I explained, the difference is not only in the width of wide char but also in the encoding (which is really implicit in `wchar_t` width being > 1 and not guaranteed by standard). So, your `wstring` syntax will be portable but your semantics may not, depending on how you interpret and what you do with contents (of which we know nothing) of the `std::wstring`. Poco uses `std::string` and `UTF-8` in all interfaces - it was a deliberate design choice and it will remain so for the foreseeable future, because it is the only sanely portable solution for the problem.

OS arguments of the type "my OS is better than yours" are silly and I doubt anyone here was meaning to state anything of sorts. Yes, Windows rules the major part of traditional desktop market. Which is not what it was once and now represents a very small fraction of the overall computing market - Android is Linux, iOS is BSD Unix and Windows phones practically do not exist. There's a lot of non-windows servers out there and many, many of them run Linux. Even Microsoft CEO exclaims they love Linux, and they run it on Azure, so what's there to argue about - let thousand flowers bloom and let people use whatever works for them - Windows, Linux and OSX have always been first-class Poco citizens. I will say here, though, that complaining about having to spin a VM in order to build for Android does not phase me much because (1) it is not difficult at all and (2) this is open source and free product, if you have an itch - scratch it, (3) if you can afford it, wait until one of project members has an itch and, last but not least, (4) you can offer an incentive and we'll gladly do it for you :).

See also [Contributing Mini-FAQ](https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md):

> Q: Why does compilation or test run fail on MinGW, Cygwin, [your platform of choice here]?
> 
> A: Because we have limited manpower/resources available and can't keep up with every minute detail of every platform. Core team makes sure reasonably recent versions of Visual Studio, clang and gcc build/tests pass on Windows, OSX and Linux; the rest is left to the contributors and other parties with interest in particular platforms. As its name says, POCO is very portable and typically it is a minor code fix or ifdef that is needed to iron a wrinkle out; please consider changing it yourself and send us pull request - that will make everyone happy. If you are inclined to do so, please consider "owning" a platform or build system. It is not much of a commitment - you will be expected to (a) keep things tidy (i.e building cleanly with tests passing) in regards to your area and (b) respond to user's inquiries thereof.

**Comment by VikingExplorer** [comment]
For the record:

1) It was Any class that was the problem, and it's documentation is simply auto-generated comments. You took about 3 days to say that Any won't work in this case. 

2) I have no emotional attachment to operating systems, and I have had lots of good experiences in the distant past developing for various unix OSs. But really, only an idiot would say that Android = Linux, especially from a application development POV.

So, the bottom line is that you refuse to provide make files or Projects that Visual Studio can use to build POCO for Android & iOS.  Looks to me like some emotional pro Linux bias.

**Comment by obiltschnig** [comment]
We (as core maintainers) have no emotional bias in one direction or another. It's just that our resources are limited, and we have to decide where to spend our time (which of there is way not enough). I have to split my time between work on POCO and macchina.io and doing support/consulting work, which pays my bills. So we tend to focus on things that either a) we have a personal need for, or b) get paid for. For me, Android support via Visual Studio is neither a personal need (I don't do Android, although I did the original port of POCO to Android), nor has anyone offered to pay me to do it. Also, it's way more work than just 1 hour to get the POCO build for Android in Visual Studio. I used to do most of my development work in Visual Studio for many years, and IMO it's still one of the best C++ IDEs available. However, most of my work today is done on OS X, or in a Linux VM, simply because that's where my interest is, and where I feel most comfortable. And I prefer to spend my (unpaid) time in an environment I enjoy.
So if you want support for Android via Visual Studio, your options are: a) do it yourself and contribute it back, or b) pay someone to do it for you. The option you chose, complaining, does not work in an open source communities.

**Comment by aleks-f** [comment]
In the interest of fairness and accuracy, here are the missing pieces: which were deleted by @VikingExplorer 

> [poco] getting ERRFMT from format (#1159)
> 18 messages
> VikingExplorer <notifications@github.com>	Mon, Feb 22, 2016 at 7:20 AM
> Reply-To: pocoproject/poco <reply+002510a5da74dbe35e3d50de48f602ecfc8371804e24afde92cf0000000112e2cd1192a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> I'm having trouble understanding the format function. It's like magic. I've got a String class that encapsulates a wstring.
> 
> void Log::debug_msg( const String& fmt, const Any& value )
> {
> auto msg = format( fmt, value );
> 
> It seems to figure out the string by calling the basic_string operator? Any help would be appreciated.
> 
> errfmt
> 
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 9:54 AM
> Reply-To: pocoproject/poco <reply+002510a582a544993b00c5f6db677eddbca2257f5a61c12d92cf0000000112e4429a92a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> Do I need to check out CppFormat? I was hoping that Poco would be a one stop shop.
> 
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 10:46 AM
> Reply-To: pocoproject/poco <reply+002510a53da4d6e9aa0a0fe229c58ec7cbdcff195def15ab92cf0000000112e44ee592a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> Gunter, I have read the docs. It wasn't clear that this is the problem. The fmt variable is my Couloir::String object, encapsulating a wstring. However, as the image shows, the string operator is called to populate the msg. The ERRFMT indicates that %s is an incorrect specifier, but it's in the documentation. Any ideas on what the problem is or how to fix this?
> 
> [Quoted text hidden]
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 10:56 AM
> Reply-To: pocoproject/poco <reply+002510a5e57ac6de4d4981f1648814bba32ddf4b5139fe1b92cf0000000112e4514892a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> I guess I'm not getting the point of the Any class. My class has a std::string operator. How did it decide what to do with the object I passed in? I certainly didn't pass it a wstring.
> 
> [Quoted text hidden]
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 11:09 AM
> Reply-To: pocoproject/poco <reply+002510a5b196921c41da521511758312c325ed5e76500c0292cf0000000112e4543692a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> So, it's back to the format function. It correctly interpreted the Couloir::String object passed into the first argument, but does not do the same for the 2nd argument. Is that a correct analysis?
> 
> [Quoted text hidden]
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 11:36 AM
> Reply-To: pocoproject/poco <reply+002510a5e5a55b8737b3e763240d1e3418825b855db9502292cf0000000112e45aa292a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> Ok, thank you. This has helped me see the way forward. I'll add another function for String and leave Any version for floats & ints:
> 
> static void debug_msg( const String& fmt, const Any& value1, const Any& value2 );
> static void debug_msg( const String& fmt, const String& value1, const String& value2 );
> 
> I find it odd that if it doesn't support wstring, it still compiles. I took a look at Any.h, but couldn't immediately see why this is ambiguous. I think I can fix this by being careful not to pass a wstring.
> 
> 2>Model\RecordList.cpp(276): error C2668: 'Couloir::Log::debug_msg': ambiguous call to overloaded function
> 2> C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Include\Log.hpp(26): note: could be 'void Couloir::Log::debug_msg(const Couloir::String &,const Couloir::String &,const Couloir::String &)'
> 2> C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\Include\Log.hpp(21): note: or 'void Couloir::Log::debug_msg(const Couloir::String &,const Poco::Any &,const Poco::Any &)'
> 2> Model\RecordList.cpp(276): note: while trying to match the argument list '(const char [89], const std::wstring, const std::wstring)'
> 
> [Quoted text hidden]
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 11:59 AM
> Reply-To: pocoproject/poco <reply+002510a5344b5a78b289ed902500d7335d6b67bcf95c896a92cf0000000112e45ffe92a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> wstring not portable? really, that would be disturbing if true. I've got 8 modules (~50k LOC C++) that were originally created for WinDesktop. I've gotten the first of my 8 modules building on Android & iOS. No problem with wstring.
> 
> Looks like I'll have to come up with a different approach, because Any isn't working for me. LOC like this:
> 
> Log::debug_msg( "\t Dumping Error %d of %d", i + 1, nCount );
> are matching up with both, because I have ctors for String that accept a float and int. With just a one-hop conversion either way, it's ambiguous.
> 
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 12:18 PM
> Reply-To: pocoproject/poco <reply+002510a5fba82c7fd511831cd87f4dfa672c88764c916c8392cf0000000112e4649392a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> While I have you two, do I really have to create a Linux VM in order to build Poco for Android?
> 
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 5:30 PM
> Reply-To: pocoproject/poco <reply+002510a5087bde64979981bdb126ee76a2cb7a0b1af75de392cf0000000112e4ad9292a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> Based on the above, I gather that you may not want constructive feedback, but just in case, here is some:
> 
> I've been interested in Poco for some time now. At some point, my company plans to replace our ASP.NET Web API REST web services with a C++ implementation. There are several possibilities, include MS Casablanca and POCO Remoting. The price seems reasonable. We're using our experiences with POCO as way to help us evaluate. We're very concerned about open source projects, because they tend to be unsupported dead ends. POCO seemed better than your average open source project, since it seems to have active leaders updating and supporting it.
> 
> The feeling I got from this exchange: responses seem defensive and somewhat arrogant. Referencing the format documentation, but not the very skimpy Any documentation? Most of the documentation is simply auto-generated from comments. Any neutral observer can see that I asked nicely about what I was confused about.
> 
> I've got over 30 years of software development experience. I'm quite familiar with make files, thank you for assuming. I know quite well that make files are NOT OS specific. In fact, it's quite easy to create a Makefile project using Visual Studio (https://msdn.microsoft.com/en-us/library/txcwa2xx.aspx).
> 
> This brings up a glaring question: Why haven't they been willing to take the few minutes (an hour?) to get this building for Android on Windows? Compared to the time to create and test all of this software, it's quite a mystery. However, the above comments seem to indicate a bias? Is there a disdain for Windows?
> 
> Maybe I'm wrong, since you're carrying around legacy VS solutions (2013, 2012, 2010 and 2008), someone has spent a lot of time on Windows. Maybe you're not aware that Visual Studio 2015 supports Android builds using either Clang or GCC. It seems like common sense to drop support for VS 2008 (8 years old), 2010 and 2012 and add full support for VS 2015. This would include projects for both Android and iOS.
> 
> Our intention is to perhaps target Linux eventually, but with only ~1% of the market, it's hardly a priority. I'm reminded of this http://www.techrepublic.com/article/can-we-please-stop-talking-about-the-linux-desktop/
> 
> I can't help but question the common sense of anyone who seems obsessed with some half-forgotten OS like Linux. I hope my impression is wrong about that. If Windows is looked down upon by the creators of POCO, even though it has 90% market share on the desktop, while Linux is considered something great with its measly 1.7% market share, I may have to reevaluate.
> 
> VikingExplorer <notifications@github.com>	Tue, Feb 23, 2016 at 6:38 PM
> Reply-To: pocoproject/poco <reply+002510a5453329bb8f703440776ce4baa6c58b6de9fe90f192cf0000000112e4bd8392a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> Fleahy,
> 
> Several points. There is a gap of 24 hours between my question and the first answer. There is no apparent arrogance in my entries until 35 minutes ago. Almost every one of the responses is snarky and/or flippant. I certainly do get good response from companies in the business of selling software. I've had extensive email discussions with the main developers of Casablanca at Microsoft.
> 
> You're whole discussion of Linux has one answer: Do developers create software on Servers?
> 
> The whole OS server thing is skewed because Linux is the most common choice for low cost hosting companies. These servers are not targets for application development.
> 
> For applications targeting Azure and SQL Server, Windows Server is the logical choice.
> 
> As for being "Open", I don't see that as a clear advantage. In large part, Open Source is where software goes to die. When it can't be monetized, it's put into Open Source. We have an endless roadmap ahead of us, and we have no interest in "contributing back".
> 
> Ok, so I'm getting the message that POCO is intended for people working in hosting facilities developing software directly on servers, and not for people using wstring (because it's really a std::string after all?). Very strange.
> 
> I'll have to take all this into consideration, because we're developers using VS on Windows 10 desktops and laptops, targeting Android, iOS and Windows. Not feeling welcome.
> 
> [Quoted text hidden]
> VikingExplorer <notifications@github.com>	Wed, Feb 24, 2016 at 6:38 AM
> Reply-To: pocoproject/poco <reply+002510a56022838d344050c1e47a20060d73592b5843d4cc92cf0000000112e5664a92a169ce0812447e@reply.github.com>
> To: pocoproject/poco <poco@noreply.github.com>
> For the record:
> 
> 1) It was Any class that was the problem, and it's documentation is simply auto-generated comments. You took about 3 days to say that Any won't work in this case.
> 
> 2) I have no emotional attachment to operating systems, and I have had lots of good experiences in the distant past developing for various unix OSs. But really, only an idiot would say that Android = Linux, especially from a application development POV.
> 
> So, the bottom line is that you refuse to provide make files or Projects that Visual Studio can use to build POCO for Android & iOS. Looks to me like some emotional pro Linux bias.

**Comment by aleks-f** [comment]
and for the future discussions, two rules:

1) no diverting one issue to another - it is bad manners
2) forum is the place for discussions like this

**Comment by obiltschnig** [comment]
Well, since @VikingExplorer has left/fled(?) without leaving a trace and all the discussion now does is put people into a bad light (deserved or not), I'm going to delete it.
