### ISSUE TITLE
Data testing

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#1161]
We need some help with testing for Data library before 1.7.0 - anyone who can help a bit this week let us know here or on slack. There's been a massive merge form [ODBCSybase](https://github.com/pocoproject/poco/tree/ODBCSybase) and [PostgreSQL](https://github.com/pocoproject/poco/tree/PostgreSQL) branches, so it will be helpful to run tests for:

ODBC (win/linux/mac)
MySQL
PostgreSQL

@obiltschnig @intensifi @kostya-lnk-ms

**Comment by aleks-f** [comment]
@zosrothko : how much of this is tested in travis/appveyor?

**Comment by obiltschnig** [comment]
Will postpone releasing this changes to 1.8.0 in early April to have some more time for testing.
Also, need 1.7.0 to be a low-risk upgrade for 1.6.1 users.

**Comment by zosrothko** [comment]
On AppVeyor, the following tests are proceeded  (and only with  release/shared configuration)
MongoDB
Data/SQLite

On Travis, the following tests are proceeded (both in release:shared & debug/shared)
Redis
MongoDB
Data
Data/SQLite

**Comment by zosrothko** [comment]
I can help for testing Postgres/ODBC on Win/Cygwin/Fedora this week.

**Comment by zosrothko** [comment]
On AppVeyor, MySQL is configured with

    Path: C:\Program Files\MySql\MySQL Server 5.6
    Server name: 127.0.0.1 or localhost
    Server port: 3306
    root password: Password12!

so Data/MySQL tests should be changed to comply with this root password for beeing tested on AppVeyor. The database name can have whatever name.

Same for PostgreSQL on AppVeyor

    Path:
        C:\Program Files\PostgreSQL\9.3
        C:\Program Files\PostgreSQL\9.4
    Server name: 127.0.0.1 or localhost
    Server port: 5432
    postgres account password: Password12!

**Comment by zosrothko** [comment]
On AppVeyor, same also for SQLServer as
Instance name: SQL2014
sa password: Password12!

**Comment by kostya-lnk-ms** [comment]
Hello,

Unfortunately I left the company, which sponsored Odbc improvements and I don't have that infrastructure at home.

I let them know, so they might help.

Best regards,
Kostya
________________________________

**Comment by intensifi** [comment]
I have tested PostgreSQL with my app in addition to the included test suite. 

Are you looking for more app level tests or my test cases to be written?

I have been thinking of making some common Data test cases for some time as I see how many of the common tests have changed in per DB branches.

**Comment by obiltschnig** [comment]
More application-level testing is definitely welcome. Today I switched one of my applications from 1.4.7 to 1.7.0 and ran into that MySQL deadlock on startup issue. This was an OSP-based application.

**Comment by zosrothko** [comment]
Some comments on the Data/PostgresSQL
1/ There is on the x64 version for VS2013 while one shoudl have also the x86 one
2/ The paths to PostgreSQL include and lib are harcoded in the vcxproj while there should be setup outside thru the global variable LIB and INCLDUE as for OpenSSL
3/ the root usr/pwd is postgres/postgres as usualy defined by default for testing configuration but this won't work on AppVeyor because the root usr/pwd are postgres/Password12!. Thus to push Data/PostgreSQL testing on AppVeyor, the root password shoudl be changed until AppVeyor comes back to postgres/postgres

**Comment by zosrothko** [comment]
See PR #1170 for progress on this subject....It would be a definitive help to merge the develop branch into the PostgreSQL branch so that AppVeyor & Travis CI pass. I tried to merge locally but there are too many conflicts in Data/ODBC & Data/PostgreSQL that I do not know how to solve securely....

**Comment by kostya-lnk-ms** [comment]
Ok, I'd attempt merging dev to Sybase branch.

Best regards,
Kostya
________________________________

**Comment by aleks-f** [comment]
@zosrothko @kostya-lnk-ms : PostgreSQL and ODBCSybase branches are dead-end do not use those. If you want to test  **any** Data library, fork off develop branch and send any pulls you may have there.

**Comment by zosrothko** [comment]
Ok so could you delete those dead end branches or rename them to an unsable name?

**Comment by aleks-f** [comment]
done - deleted
