### ISSUE TITLE
Poco::Util::Application loadConfiguration ()

### ISSUE THREAD

**Issue by skinnyMan** [pocoproject/poco#1165]
As it stands, configuration files name must match exactly to the name of the executable. Being able to load a specific configuration file at runtime would be great.

**Scenario**: A rack of 80+ linux boxes boot up and copy our executable and config file from a file server. (this allows easy deployment when new releases are pushed.)

**Problem**: Some of those 80+ linux boxes may be a mix of different hardware, mix of architectures (x64 vs. x86), so our one configuration file no longer works for all machines. So we are finding that we need to have multiple config files which means we need to rename our executables individually so that it finds the correct configuration file.

**Solution**: Having access to a function that would allow us to define which configuration file to use at runtime, allow our code to figure out the environment and then tell POCO which configuration it should use.

**Comment by obiltschnig** [comment]
There is an overload of [loadConfiguration()](http://pocoproject.org/docs/Poco.Util.Application.html#26136) that allows passing in a path.

**Comment by skinnyMan** [comment]
Hi @obiltschnig ,

So loadConfiguration() function will not care what the configuration file name is?

Thanks.

**Comment by skinnyMan** [comment]
The overloaded function works. Thanks again.
