### ISSUE TITLE
SessionPool Login Timeout issue

### ISSUE THREAD

**Issue by giuspo77** [pocoproject/poco#117]
"SessionPool" constructor is not possible set Login Timeout in order to quickly exit from "get()" method. Usually I use ODBC Driver to connect towards MS SQL Server, so at begining of my application I create a SessionPool with a right connection string. If my connection string does not correct, in particular IP Server, and after I use "get()" method, the application gets stuck for 60s.
How is it possible bypass and decrease Login Timeout on SessionPool?

Thanks a lot.
Giulio.

**Comment by aleks-f** [comment]
there is [idleTime](https://github.com/pocoproject/poco/blob/poco-1.7.9/Data/include/Poco/Data/SessionPool.h#L76) for that
