### ISSUE TITLE
Poco::Data::RecordSet: rowCount not reset after execute

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1171]
Hi all, I think there's something wrong with RecordSet called multiple time on SELECT.
Take this code as example:
`
Poco::Data::Statement select(cDBsession);
select << "SELECT * FROM car_plates ORDER BY DateTime DESC", Keywords::range(0, 50000);
while (!select.done()) {
  select.execute();
  Poco::Data::RecordSet rs(select);
bool more = rs.moveFirst();
if (!more)
	break;

std::size_t cols = rs.columnCount();
std::size_t rows = rs.rowCount();
.....other stuff
}
`

You expect the fist run rows=50000 and it's correct. second run should be the same, instead rows will be 100000...and if you cicle until rs.moveNext() return true, you will get an exception on row 50000 obviously. I'm trying with iterator to see if it's the same

**Comment by micheleselea** [comment]
using row iterator have the same problem

**Comment by micheleselea** [comment]
ah ok...I think I found, these can be the problem

void StatementImpl::assignSubTotal(bool reset)
{
	if (_extractors.size() == _subTotalRowCount.size())
	{
		CountVec::iterator it  = _subTotalRowCount.begin();
		CountVec::iterator end = _subTotalRowCount.end();
		for (int counter = 0; it != end; ++it, ++counter)
		{
			if (_extractors[counter].size())
			{
				if (reset)
					*it += CountVec::value_type(_extractors[counter][0]->numOfRowsHandled());
				else
					*it = CountVec::value_type(_extractors[counter][0]->numOfRowsHandled());
			}
		}
	}
}

I think reset is missused

**Comment by obiltschnig** [comment]
The behavior is different from 1.4.7, and it seems to me it's a bug. Every execute() on the statement should reset the RecordSet, not append to it.

**Comment by obiltschnig** [comment]
Yes, assignSubTotal() seems is the culprit. 

@aleks-f please confirm.
