### ISSUE TITLE
Merge Unix domain sockets

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1174]
Merge Unix domain sockets support from develop to 1.8.0 branch.

**Comment by mandeepsandhu** [comment]
Whats the target date for **`1.8.0`** release? Will this feature support Linux's abstract socket namespace?

**Comment by Bjoe** [comment]
I create a pull request. For details see #1529 'Merge Unix domain sockets to Poco 1.8.0'

**Comment by obiltschnig** [comment]
Fixed in a460bafa702f4298c910d96704e682eb67c5c381
