### ISSUE TITLE
Merge PostgreSQL

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1175]
Merge PostgreSQL support and other Data improvements from develop branch to 1.8.0 branch.

**Comment by obiltschnig** [comment]
Not ready for 1.8.0

**Comment by fbraem** [comment]
What needs to be done to get it ready? In the future my MQWeb project will need to connect to a PostgreSQL database, so maybe I can find some time to help ...

**Comment by aleks-f** [comment]
@fbraem In theory, it is ready, but it's been basically orphaned - nobody paying attention or doing any work on it for a long time. I can run the tests for 2.0, but have no time for any serious development or bug fixing. If you want it in 2.0, I would not mind, just go over it and make sure it's in good shape.

**Comment by obiltschnig** [comment]
Also, the coding style does not really make me happy. But first and foremost, we need a maintainer for it.
