### ISSUE TITLE
poco asserts on streams

### ISSUE THREAD

**Issue by ddsherstennikov** [pocoproject/poco#1185]
response.send() fires poco assertion on stream being null. This hurts debugging process and looks like internal poco error.

Also, send() method in sockets raises noncritical exceptions now and then, which may be related.

One hypothesis is that it's related to persistent http mode, enabled in poco by default.

Hope for comments.

**Comment by obiltschnig** [comment]
The assertion is very likely due to a misuse. As for the "noncritical exceptions", you'll have to be a bit more specific.

**Comment by ddsherstennikov** [comment]
@obiltschnig, pardon me - codebase had multiple response.send() calls due to clumsy merge. This, of course, created legitimate assertions on behalf of framework.

I consider the topic closed.

**Comment by ddsherstennikov** [comment]
@obiltschnig, pardon me - codebase had multiple response.send() calls due to clumsy merge. This, of course, created legitimate assertions on behalf of framework.

I consider the topic closed.
