### ISSUE TITLE
Having a framework like Java's Filter classes to find files

### ISSUE THREAD

**Issue by majidazimi** [pocoproject/poco#1192]
Is there any interest to create a framework like this?
The only modification to current code base is to add a `list()` method to `File` class that accepts a `Filter` and returns a `std::vector<File>` that passes the specified `Filter`. This would allow user to list files inside a directory with more complex logic.

I would like to implement such thing. More generically I would like to add the whole Apache [commons IO](https://commons.apache.org/proper/commons-io/) package.

**Comment by aleks-f** [comment]
Sure, read [Contributing](https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md) and send a pull when ready.

**Comment by obiltschnig** [comment]
Complete Apache commons may not be necessary. A lot of these features are already in POCO.

**Comment by majidazimi** [comment]
@obiltschnig I agree with. Thus I will send step by step and small patches so you can decide which part to include.
