### ISSUE TITLE
Incorrect include in header

### ISSUE THREAD

**Issue by LukeCz** [pocoproject/poco#1196]
Hi,
Include directive seem wrong in Poco/Net/Context.h:
#include "Poco/Crypto/X509Certificate.h"

while the file is Poco/Net/X509Certificate.h
This is causing compilation error:

In file included from /opt/poco-1.7.1-all/include/Poco/Net/HTTPSClientSession.h:24:
In file included from /opt/poco-1.7.1-all/include/Poco/Net/Utility.h:24:
/opt/poco-1.7.1-all/include/Poco/Net/Context.h:25:10: fatal error: 'Poco/Crypto/X509Certificate.h' file not found
#include "Poco/Crypto/X509Certificate.h"

**Comment by aleks-f** [comment]
actually, there is [Poco/Crypto/X509Certificate.h](https://github.com/pocoproject/poco/blob/poco-1.7.1/Crypto/include/Poco/Crypto/X509Certificate.h)

**Comment by obiltschnig** [comment]
Need to set you header search paths correctly. Including Poco/Net/X509Certificate.h will not fix your issue, as that includes Poco/Crypto/X509Certificate.h as well.

**Comment by LukeCz** [comment]
I found what the issue was. When installing POCO I was skipping Crypto because it was not needed in 1.6.1. Starting 1.7 the same code requires header from Crypto so I had to do full install of POCO.
