### ISSUE TITLE
POCO_OS_FAMILY_UNIX Process launch defunct process

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1199]
Hi every one, I found on a POCO_OS_FAMILY_UNIX platform (it was a RaspBerry platform) that if you use Poco::Process::launch without wait the process on exit you can generate defunct process.
So you should wait the process, otherwise send a signal and close pid. Probably could be nice to have a function to do that or on the destruction of ProcessHandle

std::vectorstd::string args;
Poco::ProcessHandle ph = Poco::Process::launch(sProgramPath, args);     
# ifdef POCO_OS_FAMILY_UNIX

```
signal(SIGCHLD, SIG_IGN);
close(ph.id());
OR
ph.wait();
```
# endif

**Comment by mikedld** [comment]
Closing the PID is an invalid operation, as PID is not a file descriptor, and `signal()` doesn't send the signal, but changes current signal handler.

Other than that, I agree that there is a possibility of zombie processes if `waitpid()` wasn't called to get child status after its termination. I'll try to implement what I talked about in issue #1097. If anyone disagrees, speak  up now.

**Comment by micheleselea** [comment]
you are right, it's enough signal(SIGCHLD, SIG_IGN); to make defunct disappear

**Comment by aleks-f** [comment]
@mikedld : your intended solution involves a thread? best to see with @obiltschnig is he has some objections to it. I see the two potentially troubling aspects of it - thread and the fact it hijacks a signal. but I haven't done much work directly with Process class, either, so I don't know how much of a pain this problem is in practice

**Comment by mikedld** [comment]
@aleks-f, yes, but thread will be created (and signal handler changed) on demand, when user attempts to create a child process for the first time. I could understand if it goes against some of POCO principles, but otherwise I think it would be a very nice solution. @obiltschnig, any comment?

**Comment by obiltschnig** [comment]
Not sure I want a thread for every single process I launch. Many times, Poco::Process is just used to launch a command and read its output via a Pipe. At least this use case should be preserved without an additional overhead. Maybe what could be done is that ProcessHandle could launch a thread "on demand". The thread would simply block in waitpid(), then signal a Poco::Event when done. This way one could properly implement isRunning() and wait with timeout. The thread should only be created if someone calls isRunning() or wait() with timeout. If the ProcessHandle is destroyed while the process is still running, the process should be killed. This should prevent zombies and other leaks in all cases, with minimum overhead. Also, the API would stay the same (except for the additional wait with timeout).
As for WNOHANG, I remember some portability issues with it. This should be kept in mind.

**Comment by mikedld** [comment]
Oh, I suppose I wasn't clear enough. The plan was to have a single thread for all the child processes. The way it works is:
  1. create a non-blocking self-pipe
  2. register a SIGCHLD handler whose only responsibility is to write a single byte into one end of self-pipe
  3. start a thread which waits for data on another end of self-pipe, and when recieved calls `waitpid()` (with `WNOHANG`) until it errors out, notifying interested parties (e.g. process handles) on each successful call with PID and status information.

I'll try to find information on portability issues, but if you have it handy that'd be great.
