### ISSUE TITLE
Building without the bundled libraries

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#120]
[SF442](https://sourceforge.net/p/poco/bugs/442/):

On linux where I have installed pcre 8.30, when using POCO_UNBUNDLED, build fails, because Unicode.cpp uses bundled internal pcre files.

when linking cpspc

```
/home/abuild/rpmbuild/BUILD/poco-1.4.6p1-all/lib/Linux/x86_64/libPocoFoundation.so: undefined reference to `_pcre_ucd_stage1'
/home/abuild/rpmbuild/BUILD/poco-1.4.6p1-all/lib/Linux/x86_64/libPocoFoundation.so: undefined reference to `_pcre_ucd_records'
/home/abuild/rpmbuild/BUILD/poco-1.4.6p1-all/lib/Linux/x86_64/libPocoFoundation.so: undefined reference to `_pcre_ucp_gentype'
/home/abuild/rpmbuild/BUILD/poco-1.4.6p1-all/lib/Linux/x86_64/libPocoFoundation.so: undefined reference to `_pcre_ucd_stage2'
```

**Comment by tpetazzoni** [comment]
This issue is also affecting the Buildroot project. I quickly adapted the Gentoo patch, and it seems to work, but it's indeed not a very clean solution.

Could this problem be solved upstream ?

**Comment by zosrothko** [comment]
The GenToo patch is no more visible... 

@aleks-f 
I had the same problem which is solved by

objects += $(pcre_utf8_objects)

ifdef POCO_UNBUNDLED
	SYSLIBS += -lpcre -lz
else
	objects += $(zlib_objects) $(pcre_objects)
endif

**Comment by aleks-f** [comment]
@zosrothko that's what's currently in the [development branch](https://github.com/pocoproject/poco/blob/develop/Foundation/Makefile#L47-L51), since [2012](https://github.com/pocoproject/poco/commit/1d8e75687e4ce644a27205f4b01a2e3be2e8e1fc#diff-cef3ab153a5417905a615b634c62f6a3). what am I missing?

**Comment by tpetazzoni** [comment]
@aleks-f Right, indeed, I missed that. However, isn't this still building some parts of PCRE even when PCRE_UNBUNDLED is defined ? If that's the case, then it's still not super clean. I wonder what happens when the external pcre changes, and the internal pcre parts that are still being built are not being updated accordingly, for example.

**Comment by aleks-f** [comment]
It shouldn't. I assume you meant POCO_UNBUNDLED, not PCRE_UNBUNDLED - there's no such define in poco. If you find a place where embedded pcre is compiled when POCO_UNBUNDLED is defined, let us know.

**Comment by tpetazzoni** [comment]
@aleks-f Yes, sorry I meant POCO_UNBUNDLED. The $(pcre_utf8_objects) variable, which is still being used when POCO_UNBUNDLED is defined, contains pcre_ucd pcre_tables. And those are files that are duplicated in Poco from the pcre sources. I.e even with POCO_UNBUNDLED you are still building parts of pcre inside Poco, and I'm worried what happens if those pcre parts become in some way incompatible with the external pcre being used in a POCO_UNBUNDLED situation.

**Comment by aleks-f** [comment]
I could be missing something, but I can find only one place where $(pcre_utf8_objects) is [used](https://github.com/pocoproject/poco/blob/develop/Foundation/Makefile#L50).

**Comment by zosrothko** [comment]
@aleks-f : it is not the same in poco-1.6.1 and poco-1.6.2 as in my develop branch & pull request

Here the poco-1.6.1 & poco-1.6.2 version:
pcre_utf8_objects = pcre_ucd pcre_tables

ifdef POCO_UNBUNDLED
	SYSLIBS += -lpcre -lz
else
	objects += $(zlib_objects) $(pcre_objects) $(pcre_utf8_objects)
endif

**Comment by glensc** [comment]
i managed to find updated patch for 1.6
https://github.com/buildroot/buildroot/blob/master/package/poco/0004-fix-unbundled-pcre-usage.patch

from @tpetazzoni by buildroot project, however my build still fails with:

```
    In file included from src/RegularExpression.cpp:21:0:
    /usr/include/pcre.h:325:26: error: conflicting declaration 'typedef struct real_pcre pcre'
     typedef struct real_pcre pcre;
                              ^
    In file included from src/RegularExpression.cpp:17:0:
    include/Poco/RegularExpression.h:37:34: note: previous declaration as 'typedef struct real_pcre8_or_16 pcre'
      typedef struct real_pcre8_or_16 pcre;

```

**Comment by aleks-f** [comment]
@zosrothko @bachp is this still relevant?

**Comment by zosrothko** [comment]
@aleks-f Building UNBUNDLED is still relevant because major distro like Debian & Fedora will always build Poco package using POCO_UNBUNDLED. By the way, currently AppVeyor & Travis CI are failing in testing unbundled Poco... this is a hard check because embedded pcre is different from the unbundled one

**Comment by bachp** [comment]
@aleks-f Yes also Yocto/OpenEmbedded is using the unbundled version.

**Comment by aleks-f** [comment]
ok, this [commit](https://github.com/pocoproject/poco/commit/35a7b47138cba28fb30db88b9719b5f1f2b405d9#diff-f621d161144028c431dba5a0c0b6d257) should have removed the problem (although it was not ported to 1.x branches, thus not released). I am not 100% content with it, because it may still cause problems if unbundled version has changed the copied parts of code), but then again, that part is probably not likely to change often

Anyway, if the above commit is agreed as the way to go, then Foundation Makefile and CMakeLists can be updated and we can port the fix back to 1.8 branch
/cc @obiltschnig @bachp @zosrothko

**Comment by glensc** [comment]
this repo has patch for pcre.patch: https://github.com/pld-linux/poco

however not sure how up to date it is. may be useful here. did not look closer.

**Comment by aleks-f** [comment]
@glensc that patch is porting changes from develop branch to 1.x release, as described [above](https://github.com/pocoproject/poco/issues/120#issuecomment-336195282)
