### ISSUE TITLE
How to create installer package (*.deb or smth)?

### ISSUE THREAD

**Issue by Zhomart** [pocoproject/poco#1201]
I have many devices with debian on them. My application is written using Poco. I have 1 development device where I compile and test my application. Now I want to install the application to all other devices.
Compiling Poco on each devices takes several hours without tests/samples.

I've tried compiling static independent binary using `g++ -static` but I couldn't make it work.
Now I've tried shipping compiled "libPoco*.so.41" together with app and run app with `LD_LIBRARY_PATH` set, couldn't make it run, complains about different versions of `libstdc++.so.6`.

Now I want to generate `*.deb` package for Poco and install it on other devices. I don't know is it a good/easy way.

How do you ship your application written using Poco?

**Comment by aleks-f** [comment]
see [distro](https://github.com/pocoproject/distro)

**Comment by avalchev** [comment]
I also added a Dockerfile, which is building the package: [Dockerfile](https://github.com/pocoproject/poco/wiki/Dockerfile-for-creating-deb-packages-(Ubuntu-15.10)) (Hope this is the correct place).

**Comment by zosrothko** [comment]
You can use the distro/Linux/Ubuntu/poco/1.6.1/debian/ directory to setup your own debian package or use this ppa if the poco-1.6.1 version is fine for your need.
- sudo add-apt-repository -y ppa:zosrothko/poco
- sudo apt-get update -qq
- sudo apt-get install -qq -y libpoco-dev

**Comment by Zhomart** [comment]
This is just great, thank you! I'll test it out today.

**Comment by Zhomart** [comment]
I'm working on arm, unfortunately repository of @zosrothko didn't help. Tried building using `distro` stuck on some stupid issue https://github.com/pocoproject/distro/issues/8.

I used commands from Dockerfile provided by @avalchev . It works, thank you!
