### ISSUE TITLE
Poco::Path Poco::File trim path

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1202]
I think should be nice if Poco::Path and Poco::File trim the string used for create object by deleting not only leading and trailing spaces but even \r and \n chars, otherwise if you push inside a string with a trailing \n the Poco::File give you obviously errors. It's just an idea

**Comment by obiltschnig** [comment]
IMO it should be the responsibility of the caller to make sure what is passed to Poco::Path and Poco::File is a valid path.

**Comment by micheleselea** [comment]
Ok was just a point of view, only because you cannot have a path with \r or \n
anyway it's doesn't matter
