### ISSUE TITLE
getdtablesize has been removed on Android 21

### ISSUE THREAD

**Issue by edkimmel** [pocoproject/poco#1204]
See this link https://code.google.com/p/android/issues/detail?id=74387
If that function has been deprecated for 12 years, I think it's a good time to replace it.

PocoFoundation's Process_UNIX.cpp uses getdtablesize still.

**Comment by obiltschnig** [comment]
replace with sysconf(_SC_OPEN_MAX)

**Comment by obiltschnig** [comment]
fixed in poco-1.7.2; already fixed in develop
