### ISSUE TITLE
Unused typedef poco_static_assert_typedef_XXX

### ISSUE THREAD

**Issue by pqvst** [pocoproject/poco#1205]
After upgrading to the latest version of Poco, I've started receiving many many warnings.
    
    Unused typedef 'poco_static_assert_typedef_XXX

See example and trace in below screenshot.

![screen shot 2016-03-17 at 13 38 35](https://cloud.githubusercontent.com/assets/4990657/13846207/bccdb1e6-ec45-11e5-9102-b1c6b3a676cb.png)

How do I prevent these warnings or is this a bug?

OS: Mac OS/X
Version: poco 1.6.1

**Comment by obiltschnig** [comment]
The latest version is 1.7.1, which has fixed this issue.

**Comment by pqvst** [comment]
@obiltschnig Ah, nice. Didn't notice that 1.7.1 was released :)
