### ISSUE TITLE
It is not successful to start a timer in a concurrent environment

### ISSUE THREAD

**Issue by asdliuquan** [pocoproject/poco#1207]
I use the thread pool, where each thread set a timer. When I use more than 16 threads concurrent, the timer (Timer:: start) can not start successful.

**Comment by obiltschnig** [comment]
The default ThreadPool has a limit of 16 threads. You'll need to increase the limit to a suitable value by calling Poco::ThreadPool::defaultPool().addCapacity(n);

**Comment by asdliuquan** [comment]
thanks, I have fixed this problem like this:

void Timer::start(const AbstractTimerCallback& method, Thread::Priority priority, ThreadPool& threadPool)
{
	Clock nextInvocation;
	nextInvocation += static_cast<Clock::ClockVal>(_startInterval)*1000;
	
	FastMutex::ScopedLock lock(_mutex);	

	if (_pCallback)
	{
		throw Poco::IllegalStateException("Timer already running");
	}

	_nextInvocation = nextInvocation;
	_pCallback = method.clone();
	_wakeUp.reset();
    do
    {
    	try
    	{
    		threadPool.startWithPriority(priority, *this);
    	}
        catch(NoThreadAvailableException&)
        {
            threadPool.addCapacity(16);
            continue;
        }
    	catch (...)
    	{
    		delete _pCallback;
    		_pCallback = 0;
    		throw;
    	}
        break;
    }while(1);
}

**Comment by obiltschnig** [comment]
Thanks for the pull request, but the Timer class is not supposed to change the capacity of the ThreadPool. Your application should make sure that the ThreadPool has a capacity suitable for all threads your application needs. Individual classes using the ThreadPool should not change its capacity.
