### ISSUE TITLE
Inconsistency between "1.7.2" releases: GitHub vs. pocoproject.org

### ISSUE THREAD

**Issue by UnitedMarsupials** [pocoproject/poco#1208]
Hello!

The content of the dynamically-generated tarball of the [poco-1.7.2-release branch available on GitHub](https://codeload.github.com/pocoproject/poco/tar.gz/poco-1.7.2-release?dummy=/pocoproject-poco-poco-1.7.2-release_GH0.tar.gz) is different from that of the [1.7.2-all](http://pocoproject.org/releases/poco-1.7.2/poco-1.7.2-all.tar.gz) served by pocoproject.org.

Notably, the GitHub version offers components like CppParser and PDF, which aren't present in the official tarball.

The discrepancy requires an explanation -- are the GitHub-only bits not quite as tested, perhaps? What should we, the downstream packagers and end-users, use -- GitHub or pocoproject.org? Thank you

**Comment by aleks-f** [comment]
You should use pocoproject.org. Github "release" is really just a tag.
