### ISSUE TITLE
Upgrade SQLite to 3.12.0 or newer

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1221]
https://www.sqlite.org/releaselog/3_12_0.html

**Comment by mkrivos** [comment]
Hello,
can I provide patch ?

**Comment by obiltschnig** [comment]
Sure!

**Comment by obiltschnig** [comment]
See pull request #1224

**Comment by obiltschnig** [comment]
3.12.1 is available: https://www.sqlite.org/releaselog/3_12_1.html

**Comment by obiltschnig** [comment]
upgraded poco-1.7.3 and develop to 3.12.1 with 8268ebe1793df7e62b6f32246ffe191479c48661

**Comment by obiltschnig** [comment]
...aaand we have 3.12.2
