### ISSUE TITLE
Add to HTTPServerRequest methods for host and port

### ISSUE THREAD

**Issue by avalchev** [pocoproject/poco#1227]
Hi *,

it's going to be useful to add `getServerName()` and `getServerPort()` to `HTTPServerRequest` class, especially when handling virtual hosts.

Regards.

**Comment by aleks-f** [comment]
there is already [getURI()](https://github.com/pocoproject/poco/blob/develop/Net/include/Poco/Net/HTTPRequest.h#L66) and [getHost()](https://github.com/pocoproject/poco/blob/develop/Net/include/Poco/Net/HTTPRequest.h#L79), but if you want `getPort()` as well, send a pull

**Comment by obiltschnig** [comment]
There's also serverParams() and serverAddress(), so I don't think we'll need any additional methods. For virtual hosts, the server name can be obtained via getHost().
