### ISSUE TITLE
WebSocket sendBytes & sendFrame return value

### ISSUE THREAD

**Issue by adrian-007** [pocoproject/poco#1230]
Hi, while working on a WebSocket implementation in our project I've encountered a problem with send functions in WebSocket component:
WebSocketImpl.cpp:
`_pStreamSocketImpl->sendBytes(frame.begin(), length + static_cast<int>(ostr.charsWritten()));
    return length;`

return value does not indicate how much data was actually sent but instead it just returns the buffer's size that was passed to it.
Yet the documentation states that

> ```
>   /// Returns the number of bytes sent, which may be
>   /// less than the number of bytes specified.
>   ///
>   /// Certain socket implementations may also return a negative
>   /// value denoting a certain condition.
> ```

It seems to me that there is a bug in the code and the documentation is right - those two methods should return actual sent bytes count.

**Comment by bsuvorov** [comment]
I have the same problem. I see issues of not sending entire frames to server from iOS LTE connections.
