### ISSUE TITLE
Windows 10 badly detected

### ISSUE THREAD

**Issue by jano42** [pocoproject/poco#1238]
I'm using Poco 1.7.2 under Windows 10 professional

I'm using the displayName function to get my application platform.

``` c++
Poco::Environment::osDisplayName()
```

But it returns "**Windows 8**" and the version is "**6.2 (Build 9200)**"

**Comment by flachesis** [comment]
https://msdn.microsoft.com/zh-tw/library/windows/desktop/ms724833(v=vs.85).aspx

**Comment by flachesis** [comment]
https://bugs.php.net/patch-display.php?bug_id=69642&patch=detect-windows-10-not-working-yet&revision=latest

I think this is the problem...

**Comment by bachp** [comment]
I think the relevant information from https://msdn.microsoft.com/zh-tw/library/windows/desktop/ms724833(v=vs.85).aspx is:

> For applications that have been manifested for Windows 8.1 or Windows 10. Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). To manifest your applications for Windows 8.1 or Windows 10, refer to Targeting your application for Windows.

**Comment by flachesis** [comment]
https://msdn.microsoft.com/zh-tw/library/windows/desktop/dn481241(v=vs.85).aspx

poco use deprecated function GetVersionEx on win10.

**Comment by obiltschnig** [comment]
so what should be used instead of GetVersionEx?

**Comment by flachesis** [comment]
https://msdn.microsoft.com/en-us/library/windows/hardware/ff561910(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/hardware/ff563620(v=vs.85).aspx
https://autohotkey.com/boards/viewtopic.php?t=6057

I think we can use RtlGetVersion function.

**Comment by obiltschnig** [comment]
Well, if the OS decides to lie to you we should just accept it as it is. Any workaround will likely result in a huge maintenance nightmare. Send your complaints directly to Microsoft.

**Comment by obiltschnig** [comment]
If someone cares enough for this issue, send an acceptable pull request. Otherwise we'll leave it as it is.

**Comment by bachp** [comment]
Maybe I misunderstand the issue and I don't know enough about manifesting on windows.

But as far as I understand if the application using Poco is correctly manifested it should get the correct results. So this means the wrong result has nothing to do with Poco but with the application that is using it.

I don't have a Windows  10 machine at hand so I can't check my assumption.

**Comment by obiltschnig** [comment]
The problem is that you have to create a new manifest for your application whenever a new Windows version comes out, otherwise GetVersionEx will always report the highest Windows version the application has a manifest for. Nevertheless, nothing we can fix in POCO.

**Comment by sdaly2107** [comment]
There are version helpers, but they are only available from the Win 8.1 SDK onwards. 

GetVersionEx is deprecated and returns incorrect info, instead RtlGetVersion which is called by GetVersionEx but without a load of app compatibility stuff can be used.  You need to dynamically load it, but it works and we have been using this fine for over a year now.  We have just started using Poco for another project, but I may add a pull request for this soon.

**Comment by zeroxer** [comment]
[GetProductInfo](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getproductinfo) may help.
