### ISSUE TITLE
Poco::Zip::Compress with non-seekable stream fails for CM_STORE

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1239]
Hi all, I found a strange behavior of the Compress utility for zip.
If you use something like

std::ostream& ostr = response.send();
bool bSeekable=false;
Poco::Zip::Compress c(ostr, bSeekable);

to stream for example over network (here you have a slice of code from Poco::HttpServer
std::string sFileName("c:\\somefile.txt");
Poco::Path pFile(sFileName);
c.addFile(pFile, pFile, Poco::Zip::ZipCommon::CM_STORE, Poco::Zip::ZipCommon::CL_SUPERFAST);
c.close();

the addFile with Poco::Zip::ZipCommon::CM_DEFLATE is ok, with Poco::Zip::ZipCommon::CM_STORE it throw exception on outputstream. ostr is a ofstream on your disk it's all ok.
The error occur even with CM_AUTO if you try compress jpeg because internally is used CM_STORE.

Do you think it's not possible to use CM_STORE over network?

**Comment by micheleselea** [comment]
forgot to tell you I'm using Windows 10

**Comment by micheleselea** [comment]
tried even on linux arm (Poco libs 1.7.2) same results

**Comment by micheleselea** [comment]
I think the problem is that when in the Compress::addEntry is called zipOut.close(); we reach this if
if (_pHeader->searchCRCAndSizesAfterData())

I think in this step if the out stream is not seekable we shoud enter in this condition, instead we miss it and we enter in the code above where we do _pOstr->seekp( that screw up the out stream

I'm going deeper to discover why that point the seekable is miss checked...l'll let you know

**Comment by micheleselea** [comment]
ok found...the bad code is

bool ZipLocalFileHeader::searchCRCAndSizesAfterData() const
{
	if (getCompressionMethod() == ZipCommon::CM_DEFLATE)
	{
		// check bit 3
		return ((ZipUtil::get16BitValue(_rawHeader, GENERAL_PURPOSE_POS) & 0x0008) != 0);
	}
	return false;
}

when I use CM_STORE you always got false so you always consider it seekable that way.
Do you think you can just remove 
if (getCompressionMethod() == ZipCommon::CM_DEFLATE)
?

**Comment by obiltschnig** [comment]
Safer would be to check for CM_DEFLATE or CM_STORE: 

    if (getCompressionMethod() == ZipCommon::CM_STORE || getCompressionMethod() == ZipCommon::CM_DEFLATE)

these are the only two methods supported by POCO Zip. Not sure regarding the other methods. If in doubt, check the Zip file specification.

**Comment by micheleselea** [comment]
ok, tried now and that fix the problem
