### ISSUE TITLE
How to create my own rootcert.pem/any.pem?

### ISSUE THREAD

**Issue by zhutuo** [pocoproject/poco#1240]
In the sample HTTPSTimeServer,I found it the digital certificate is outdated.but How can I update it?I try to create a new CA with openssl tools;but the new *.pem files will cause crash. the file any.pem is combined with a private key and a Certificate;but what key is the private key and what Certificate is the Certificate?so what is the file rootcert.pem?it is different with any.pem's. combined with server.key and server.crt? Is rootcert.pem the client Certificate or the root Certificate ?  Please explain in detail,I need your help.

**Comment by avalchev** [comment]
Certificate generation is not poco specific. You can take a look [here](http://www.akadia.com/services/ssh_test_certificate.html).

**Comment by zhutuo** [comment]
@avalchev the file any.pem is combined with a private key and a Certificate;but what key is the private key and what Certificate is the Certificate?so what is the file rootcert.pem?it is different with any.pem's. Please explain in detail,I need your help.

**Comment by zhutuo** [comment]
combined with server.key and server.crt? Is rootcert.pem the client Certificate  or the root Certificate ?

**Comment by guarense** [comment]
Openssl> req -x509 -days 365 -newkey rsa:2048 -keyout any.pem -out any.pem
(pass phrase = secret)
Openssl> req -new -key -any.pem -out server.csr
Openssl> x509 -req -in server.csr -signkey any.pem -out rootcert.pem

**Comment by gelldur** [comment]
```
openssl req -x509 -days 365 -newkey rsa:2048 -keyout any.pem -out any.pem
openssl req -new -key any.pem -out server.csr #no more -any.pem
openssl x509 -req -in server.csr -signkey any.pem -out rootcert.pem
```
