### ISSUE TITLE
Rename CMAKE Variables to allow grouping

### ISSUE THREAD

**Issue by emma3826** [pocoproject/poco#1241]
Some context information:

I am currently building Poco Version  1.6.1 as a cmake project.

As I find it easier to work with a GUI tool when configuring cmake, I am using cmake-gui (https://cmake.org/cmake/help/v3.0/manual/cmake-gui.1.html)

Using cmake-gui it is possible to group the cmake variables. 

Problem:

When grouping, some of the variables belong to a group called POCO but many others are located under a group called ENABLE.

Proposed Solution:
Would it be possible to rename those variables (e.g. add POCO_ prefix)
As I am currently building on a linux machine I am doing a sed to rename, as an workaround:
grep -rl 'ENABLE_' ./ | xargs sed -i 's/ENABLE_/POCO_ENABLE/g'

**Comment by bachp** [comment]
I never checked with the GUI but if we can make things easier I'm open.

One problem I see is how to deal with backwards compatibility? Is it important that the option variables don't change so we don't break builds?

Maybe Poco 2.0 I think we can clean up some of the CMake stuff even if it is not backwards compatible.

**Comment by emma3826** [comment]
From my perspective, renaming the CMAKE input variables would break the backwards compatibility.
Nonetheless: shall I provide a patch with the changes so they can be integrated when the right moment comes?

**Comment by bachp** [comment]
Yes please open a PR
