### ISSUE TITLE
error C2872: 'BLOB' : ambiguous symbol

### ISSUE THREAD

**Issue by leyon1210** [pocoproject/poco#1249]
the problem as below:
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1576): error C2872: 'BLOB' : ambiguous symbol
1>          could be 'C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1150) : _BLOB BLOB'
1>          or       'D:\library\poco-1.6.1-all\library\Poco\include\Poco/Data/LOB.h(185) : Poco::Data::BLOB'
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1587): error C2872: 'BLOB' : ambiguous symbol
1>          could be 'C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1150) : _BLOB BLOB'
1>          or       'D:\library\poco-1.6.1-all\library\Poco\include\Poco/Data/LOB.h(185) : Poco::Data::BLOB'

How to fix it?

**Comment by patricklaf** [comment]
I have just installed Visual Studio 2019 and compiled Poco-1.10.1-all, with Data (SQLite and MariaDB), without problem.
I am trying to compile a program using Poco::Net and Poco::Data libraries and I encounter the same problem. This is the output (sorry in French):
```
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winsock2.h(1561,25): error C2872: 'BLOB' : symbole ambigu (compilation du fichier source src\Bancald.cpp)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winsock2.h(1143,3): message : est peut-être '_BLOB BLOB' (compilation du fichier source src\Bancald.cpp)
1>D:\Librairies\poco-1.10.1-all\Data\include\Poco\Data\LOB.h(193,7): message : ou       'Poco::Data::BLOB' (compilation du fichier source src\Bancald.cpp)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winsock2.h(1570,25): error C2872: 'BLOB' : symbole ambigu (compilation du fichier source src\Bancald.cpp)
1>D:\Windows Kits\10\Include\10.0.18362.0\um\winsock2.h(1143,3): message : est peut-être '_BLOB BLOB' (compilation du fichier source src\Bancald.cpp)
1>D:\Librairies\poco-1.10.1-all\Data\include\Poco\Data\LOB.h(193,7): message : ou       'Poco::Data::BLOB' (compilation du fichier source src\Bancald.cpp)
========== Génération : 0 a réussi, 1 a échoué, 0 à jour, 0 a été ignoré ==========
```
This issue was closed without explanation. Is there a simple fix? I didn't find any other issue about this problem.

**Comment by patricklaf** [comment]
I found the solution: just include `Winsock2.h` before anything else.
[VS2008 Compile error with <winsock2.h>](https://stackoverflow.com/questions/4061562/vs2008-compile-error-with-winsock2-h) was helpful.
