### ISSUE TITLE
Support for HTTP cache in POCO::Net

### ISSUE THREAD

**Issue by shekharhimanshu** [pocoproject/poco#1250]
I have just started developing a mobile network library in C++ using POCO framework and would like to confirm if there is any future plans for adding http cache support in the networking library. (something like OkHttp in Android).
I need to cache the http responses for performance reasons and was thinking to implement it using the already present [Cache Framework](http://pocoproject.org/slides/140-Cache.pdf) in POCO if no such plans exist for adding http caching support.

**Comment by obiltschnig** [comment]
No concrete plans for HTTP cache support, but it's not too hard to build it with the POCO cache framework the way you need it.

**Comment by shekharhimanshu** [comment]
Thank you @obiltschnig for the confirmation!
