### ISSUE TITLE
Poco::Data::Statement formatting interferes with SQL wildcard

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1255]
Poco::Data::Statement supports formatting via Poco::format(). This means that for every statement string, Poco::format() will be called, even if no arguments are provided. This will mean that '%' SQL wildcard characters will be removed unless escaped ("%%"), which may lead to unexpected behavior.

Should Poco::Data::Statement be changed to only call format if at least one parameter is specified?

@aleks-f

**Comment by aleks-f** [comment]
yes, that would probably be the right thing to do

**Comment by intensifi** [comment]
@aleks-f 
@obiltschnig 

This may not be completely related to this topic but different DBs use different substitution parameters characters ("%", "$1", "$2", etc.) come to mind.  I would desire that what ever is chosen be consistent across DBs.

**Comment by obiltschnig** [comment]
Poco::Data::Statement already calls Poco::format() only if parameters are specified.
