### ISSUE TITLE
Fix FindMySQL.cmake for MySQL 5.7 and up

### ISSUE THREAD

**Issue by guruofquality** [pocoproject/poco#1256]
There is now only one library which is thread-safe (mysqlclient), and no longer a separate mysqlclient_r. More information here about the change in version 5.7: http://mysqlserverteam.com/deprecating-the-mysql_config-libs_r-option/

The line `find_library(MYSQL_LIB NAMES mysqlclient_r` in FindMySQL.cmake should be changed to `find_library(MYSQL_LIB NAMES mysqlclient`. According to the link above, this change should also be ok for 5.6 and 5.5 versions as well as mysqlclient_r was supposed to be a backwards compatibility symlink.

We may need a version specific check to pick the correct name, or just assume mysql is recent and use the mysqlclient version of the name.
- tested with 1.7.2 release on ubuntu xenial

**Comment by xcl706** [comment]
this is helpful! i met the same problem, on poco 1.9.0

**Comment by Bjoe** [comment]
This is fixed in `poco-1.9.1`
