### ISSUE TITLE
URI encoding

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#1260]
URI encoding seems to be somewhat ad-hoc. I propose to always encode [reserved characters](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters), plus (maybe with an option) encode what is now called [ILLEGAL_CHARS](https://github.com/pocoproject/poco/blob/develop/Foundation/src/URI.cpp#L31) and align that with [this list](https://en.wikipedia.org/wiki/Percent-encoding#Character_data).
/cc @obiltschnig

**Comment by obiltschnig** [comment]
Current implementation tries to do as little escaping as possible to prevent an unnecessary explosion of percent-encoded characters. There may be room for improvement, so make a proposal. You just have to keep in mind that this is quite a hairy area and it's easy to get things wrong. Also, different parts of an URI have different reserved characters.

**Comment by obiltschnig** [comment]
OTOH the URI code is quite old and there may be clearer rules now compared to when I wrote the code.

**Comment by hyphenlee** [comment]
#1531 
I have add extra illegal_chars according to the https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters .
Hope it helps

**Comment by tastytea** [comment]
`Poco::URI::encode("1+2", "", out);` does not escape `+` in 1.9.0.

### Snippet:

``` c++
std::string out;
Poco::URI::encode("!-#-$-%-&-'-(-)-*-+-,-/-:-;-=-?-@-[-]", "", out);
std::cout << out << '\n';
```

### Result:

```
%21-#-%24-%25-&-%27-%28-%29-%2A-+-%2C-/-:-;-=-?-@-%5B-%5D
```
