### ISSUE TITLE
Issue for std::string-typed path / file name containing the 0x00 char

### ISSUE THREAD

**Issue by alex-87** [pocoproject/poco#1265]
Hello,

  There is an issue concerning the wrong account of the null (not allowed) character in a path, which results in an undefined behavior. The bug is reproducible like following:

```
#include <Poco/Path.h>
#include <Poco/File.h>
#include <iostream>

int main(int argc, char** argv)
{
    std::string fileName = "Text.txt";
    fileName.append(2, 0x0);
    fileName.append(2, 'x');

    Poco::File file( Poco::Path::expand(fileName) );

    if ( file.exists() ) {
        std::cout << "The file "
              << Poco::Path::expand(fileName)
              << " exists"
              << std::endl;
    }

    return 0;
}
```

The result of this sample, **admitting the file** `Text.txt` **really exists**, is:
`The file Text.txtxx exists` (of course, **there is no** `Text.txtxx` **file**).

The issue is caused by the fact that POCO considers the null-terminated string only, but std::string doesn't, by taking into account all of the symbols, and not only the null-terminated char sequence. Consequently, the result of the `file.exists()` isn't correct because of the mal-formed-but-correct string corresponding to the file name.

Hoping it helps,
Have a great day.

**Comment by micheleselea** [comment]
I don't know but usually the concept of "string" is a null terminated sequence of characters. I think is not wrong that the string considered in your case it's Text.txt because if you, for example, for some reason in tour code put the '\0' char to make the string exactly what you need (Text.txt) without resising string the behavior is correct...but it's just my point of view.

**Comment by alex-87** [comment]
I agree with the fact that POCO considers, in this case, `Text.txt` only. My concern is more about processing the file name, for example here:

```
FileImpl::FileImpl(const std::string& path): _path(path)
{
	std::string::size_type n = _path.size();
	if (n > 1 && _path[n - 1] == '/')
		_path.resize(n - 1);
}
```

In [File_UNIX.cpp](https://github.com/pocoproject/poco/blob/develop/Foundation/src/File_UNIX.cpp), for example, either we consider an entier string by using `_path.size()`, or we consider a null-terminated string by using `std::char_traits<char>::length(_path.data())`, otherwise the behaviour could be random.

This is why I opened a pull request which only ensures there is no possible gap between the null-terminated string and a string which contains a null char.
