### ISSUE TITLE
extract<Poco::JSON::Object::Ptr>() fails on iPhone 6 

### ISSUE THREAD

**Issue by advantiss** [pocoproject/poco#1275]
The code below works fine on iPhone 4s and iPhoneSimulator and Windows as well: 

```
Poco::JSON::Parser jsonParser;
auto parsedJSON = jsonParser.parse("{\"Method\":\"multiply\",\"ArgsJson\":\"[1.1,1.1]\"}");
auto parsedResult = parsedJSON.extract<Poco::JSON::Object::Ptr>();
```

but fails on iPhone 5/6 with exception message

```
 Can not convert N4Poco9SharedPtrINS_4JSON6ObjectENS_16ReferenceCounterENS_13ReleasePolicyIS2_EEEE to 4Poco9SharedPtrINS_4JSON6ObjectENS_16ReferenceCounterENS_13ReleasePolicyIS2_EEEE
```

All Poco libraries for iPhone 6 was built for arm64 architecture using actual make files

```
./configure --config=iPhone-clang-libc++ --static --no-tests --no-samples --minimal
make POCO_TARGET_OSARCH=arm64 -s -j4
```

And compiler settings in XCode
![image](https://cloud.githubusercontent.com/assets/1725970/15338356/36e5b0ec-1c88-11e6-843b-576e0aeb3cf1.png)

Please advice how to avoid that fail or fix the sources.

UPD: debugging shows that POCO_LONG_IS_64_BIT is defned

**Comment by advantiss** [comment]
Exception is being thrown from the code below in Var.h
Looks like `pHolder->type() == typeid(T)` comparison somehow returns false for the same type

```
	template <typename T>
	const T& extract() const
		/// Returns a const reference to the actual value.
		///
		/// Must be instantiated with the exact type of
		/// the stored value, otherwise a BadCastException
		/// is thrown.
		/// Throws InvalidAccessException if Var is empty.
	{
		VarHolder* pHolder = content();

		if (pHolder && pHolder->type() == typeid(T))
		{
			VarHolderImpl<T>* pHolderImpl = static_cast<VarHolderImpl<T>*>(pHolder);
			return pHolderImpl->value();
		}
		else if (!pHolder)
			throw InvalidAccessException("Can not extract empty value.");
		else
			throw BadCastException(format("Can not convert %s to %s.",
				std::string(pHolder->type().name()),
				std::string(typeid(T).name())));
	}
```

**Comment by AbhinavBansal** [comment]
Hi, Is there a solution to this?

I am also getting Bad cast exception. 

Can not convert N4Poco9SharedPtrINS_4JSON6ObjectENS_16ReferenceCounterENS_13ReleasePolicyIS2_EEEE to N4Poco9SharedPtrINS_4JSON6ObjectENS_16ReferenceCounterENS_13ReleasePolicyIS2_EEEE. 

My JSON is in the format:
       {\"AAA\":{\"BBB\":\"onemoresuffix.com\",\"deleted\":1}}

Code:
        Poco::JSON::Parser parser;
        Poco::Dynamic::Var result = parser.parse(json);
        std::string value = result.convert<std::string>();

Interestingly, If I run app in DEBUG mode, it works, but fails in RELEASE mode.
Is there any compiler setting that I should do?
Any help would be appreciated.

**Comment by AbhinavBansal** [comment]
Is there anything I can do about it.
I have changed the condition to workaround
`strcmp(pHolder->type().name(),typeid(T).name()) == 0` instead of  `pHolder->type() == typeid(T)`

**Comment by killerbobjr** [comment]
For arm64 builds, add the compiler flag:  -fvisibility=hidden
There seems to be some sort of an issue in ParserHandler that causes Object::get to return a null when compiled without this flag.
