### ISSUE TITLE
Strange PCRE 8.31 problem in Poco 1.3.6 under Ubuntu 14.04 86_64

### ISSUE THREAD

**Issue by eppie20** [pocoproject/poco#1284]
Hi everyone, 

I'm using Poco 1.3.6 with great joy but since we are planning to migrate from Ubuntu 12.04 32b to 14.04 64b I come across a problem which I explained in detail at Ubuntu's Launchpad: https://bugs.launchpad.net/ubuntu/+source/pcre3/+bug/1361610 

I encountered this problem first in Ubuntu 13.xx but this didn't matter because we decided to use 14.04 LTS so is is an issue again :)

**Comment by obiltschnig** [comment]
1.3.6 is now almost 5 years old (and no longer maintained) so you really should consider upgrading to a newer release.

**Comment by eppie20** [comment]
Maybe that is the best solution. Still it is shame that Ubuntu 14.04 uses a very old Poco :(

**Comment by zosrothko** [comment]
@eppie20 You can use my own ppa poco-1.7.3 for Trusty, Precise, Xenial and Xaketty at
https://launchpad.net/~zosrothko/+archive/ubuntu/poco

**Comment by zosrothko** [comment]
As an temporary solution or a workaround, you can use my own ppa [poco-1.7.8](https://launchpad.net/~zosrothko/+archive/ubuntu/pocoproject/+packages). I run regex.cc and got this output
```
fandre@Ubuntu-x64:~/pcre$ g++ regex.cpp -lPocoFoundation -o regex && ./regex
Poco POCO_VERSION on Linux 4.4.0-72-generic @ x86_64
Poco  match 1234567890 to pattern ^[0-9]{10} matches? yes
Poco  match 123456789 to pattern ^[0-9]{10} matches? no
```
I am currently trying to fix the pcre mess, balancing between the poco requirements and the debian packaging requirments. It would be very interesting if you can confirm this ppa solve all your issues.
