### ISSUE TITLE
asynchronous network library

### ISSUE THREAD

**Issue by idekel** [pocoproject/poco#1285]
Poco provides a very good network library but it lacks asynchronous functionalities, so I wonder if there is any plans to add them in the future or if you are already working on some solution, because I am almost finishing an async library, nothing too fancy, but It's based on Poco Net library.
Currently, I have implemented async reads, writes and a very simple, but already working async DNS resolution, on top of that I am thinking to add later other higher label Libraries, so I would like to contribute but I have never contribute before to any opensource project before and I do not know how to proceed. So if any one could point me in the right direction I would appreciated.

**Comment by aleks-f** [comment]
Read [contributing](https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md) document and go. We can create a separate branch for the feature and you send pulls against that branch (instead of directly develop). We'll keep the branch synced with develop and merge when release-ready. This is a feature we've been sorely lacking and it would be nice to have it. Do you have/plan all major platforms (Linux/epoll, Mac,BSD/kqueue and windows IOCP)?

**Comment by idekel** [comment]
Thanks, I will read it. I do have plans for all major platforms, that's why I've only used Poco and ansi C++11, but I've only tested on Linux as I finished the basics today, of course I plan to write a lot of test cases, and run them at least on (Linux, FreeBSD and Windows)

**Comment by obiltschnig** [comment]
+1

--
Günter Obiltschnig
Applied Informatics Software Engineering GmbH

**Comment by idekel** [comment]
According to documentation in the link given by aleks-f, I should start by forking Poco and them creating a new branch for the feature I want to implement, so far so good, but I would like some advise:
1. should I use develop or c++11 branch? My code uses C++11's features.
2. The code is in a namespace called "Async" should I put it under Poco or Poco::Net?
3. The Poco code based is very easy to read but if I need to make a question about some class or library, is this the appropriate way to ask, or is there a better place?

**Comment by aleks-f** [comment]
1. branch develop (use [these](https://github.com/pocoproject/poco/blob/c%2B%2B11/Foundation/include/Poco/Config.h#L30-L42) defines)

2. I'd say Poco::Net. I wouldn't even put it in its own namespace as we will likely use some of it [here](https://github.com/pocoproject/poco/blob/develop/Net/src/Socket.cpp#L74). In fact, it may be a good idea to start from there and have all loops in Net::Socket only @obiltschnig ?

3. here is fine. I will also send you slack invitation but I need your email. email me    
    `at(alex, dot(pocoproject, org))`

**Comment by DevAlone** [comment]
So how is the process going?

**Comment by checkmobi** [comment]
Any plan for integrating kqueue on osx ? currently is using select which doesn't support more than 1024 sockets. 

Silviu

**Comment by silviucpp** [comment]
Or even better is to implement the polling mechanism using libev or libevent which are available on most of the platforms

**Comment by zhou881117** [comment]
why not integrate the branch  of  reactor-http ?
