### ISSUE TITLE
Generated PocoConfig.cmake packages are not relocatable

### ISSUE THREAD

**Issue by bachp** [pocoproject/poco#1291]
Currently the CMake configurations files generated by Poco are not relocatable if system libraries (unbundled) are used.

This is because they refer to third party libraries like OpenSSL and do this with their full path.

The solution would be to completly move to [IMPORTED targets](https://cmake.org/cmake/help/git-master/manual/cmake-buildsystem.7.html#imported-targets), but this is not supported by all packages.

The issue is described in the [CMake Documentation](https://cmake.org/cmake/help/git-master/manual/cmake-packages.7.html#creating-relocatable-packages).

I don't see a quick solution to fix this issue and I think to solve it properly the following is needed:
1.  Fix the CMake find or config modules for all required third party tools to provide imported targets. This requires some work on CMake itself and I already started working on this.
2. Use these imported targets in Poco. This is easy once they are available, but I has the disadvantage that Poco might become only buildable with the latest CMake version containing these changes.

**Comment by Bjoe** [comment]
For the sake of completeness in `poco-1.9.1` and `develop` branch, the cmake build is using only the `IMPORTED targets`.
I think this issue is fixed.

**Comment by bachp** [comment]
@Bjoe I think to have this completly fixed https://github.com/pocoproject/poco/pull/2599 is also needed.

**Comment by Bjoe** [comment]
@bachp Yep right.

**Comment by Bjoe** [comment]
#2599 and #2679 is merged now. So all targets/third party are `IMPORTED`

**Comment by bachp** [comment]
@Bjoe Thanks for fixing this. I don't find anything missing. I will close this. I will do some extended verification when I update the recipe in OpenEmbedded.
