### ISSUE TITLE
1.7.3 x64 build fails on machine type difference

### ISSUE THREAD

**Issue by jshanab** [pocoproject/poco#1292]
Command in 64bit VC2010 console
        buildwin.cmd 100 build all both x64
error 
       obj64\debug_shared\CppUnitException.obj : fatal error LNK1112: module machine type 'X86' 

I saw a post on the forum for this and hit it myself. The issue seems to be a CppUnitException.obj is already in the repo either from the 32bit build prior or in the tarfile and the "buildwin.cmd 100 clean" does not remove it. (Perhaps it needed more arguments)

Opening the cppunit sln and cleaning the project then building allowed the buildwin.cmd to complete.

**Comment by DvoryankinEvgeny** [comment]
I have the same problem with VS2015. I'm download source code of library from http://pocoproject.org/ and my build_vs140.cmd is different from file in this repo. My file contains this:
```
@echo off
if defined VS140COMNTOOLS (
call "%VS140COMNTOOLS%\vsvars32.bat")
buildwin 140 ...
```
File in 1.7.3 branch in this repo don't have this line

**Comment by FlemishLion1302** [comment]
Do not use the "Developer Command Prompt for VS2015". Instead use the ""VS2015 x64 Native Tools Command Prompt" to launch "buildwin.cmd 140 build all both x64".
