### ISSUE TITLE
MySQL into  is not effect

### ISSUE THREAD

**Issue by xsw123** [pocoproject/poco#1295]
Code like this:
      std::vectorstd::string names;
    *_pSession << "show databases", into(names), now;
    //print the results
    for (std::vectorstd::string::const_iterator it = names.begin(); it != names.end(); ++it)
    {
        std::cout << *it << std::endl;
    }

the excute result is that ,  names.size() is correct, but  all element in names is “”, has anyone konw why? I'm confused this for a long time . Thanks ![MySQL version: 5.6.2 ; POCO Version: 1.7 ]

**Comment by micheleselea** [comment]
I think you shoud change definition of names in
std::vector<Poco::Tuple<std::string>> names;
