### ISSUE TITLE
FTPClientSession -> FTPSClientSession (FTP over TLS)

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1297]
Hi all, two point about FTP client session:
1) in function beginUpload the first code on datastream is "delete _pDataStream;" that is not "safe" because _pDataStream is null...probably "delete null" do nothing but I think it's better to check
2)I've implemented in my FTP server (created with Poco lib) AUTH TLS command to make FTPS explicit SSL connection: I'm going to implement this feature in the FTPClientSession, I think I can override FTPClientSession so add this function. If you are interested, after I double check it, I can give you the override class FTPSClientSession. Let me know

**Comment by obiltschnig** [comment]
reg. 1: deleting a null pointer is perfectly safe in C++ - it will simply do nothing, so there's no need to check for a null pointer before calling delete.
reg. 2: contribution welcome

**Comment by micheleselea** [comment]
good, as soon I have I can attach you the derived FTPSClientSession class

**Comment by micheleselea** [comment]
I think I'll have to make a new class because FTPClientSession has private sockets member. Anyway, one day if it's work good, we can substitute the class or you can do whatever you think it's better

**Comment by micheleselea** [comment]
Ok here you are a ZIP file with FTPSClientSession class that do the FTPS protocol (TLS on FTP). It's basically made on FTPClientSession with some more function. Have a look, I tested with FileZillaServer and with my own FTP server (made with Poco) and I think it works.
Probably the style of some code can be better, but you can see that the class has few modifications from original.
Let e know if you have a look to it, I insert a couple of comments to better understand, but it's quite simple 
[FTPS.zip](https://github.com/pocoproject/poco/files/346564/FTPS.zip)

**Comment by micheleselea** [comment]
Just a small fix to avoid multiple request to TLS connection if the server does not support it
[FTPS.zip](https://github.com/pocoproject/poco/files/346586/FTPS.zip)

**Comment by obiltschnig** [comment]
Thanks, but I would prefer if we could reuse as much of Poco::Net::FTPClientSession as possible, instead of duplicating code which usually becomes a maintenance nightmare. Even if this means making changes to the base class, making some data members protected (or adding protected methods). Like with HTTPSClientSession or SecureSMTPClientSession.

**Comment by micheleselea** [comment]
Is exactly what I was talking about in my last message, and I agree with you. The point is:

- We should make at least _pControlSocket and _pDataStream protected

- But keep in mind that the new class support FTP or FTPS as well, so you can use one class to handle both kind of connection, so basically you can even replace the old FTPClientSession with the new one and you have just one class.

I think both way is fine, I just let you choose what do you think is the best

**Comment by micheleselea** [comment]
If you look at FileZillaClient is exactly what it does, it try in TLS mode and than fallback in FTP plain mode. The FTPSClientSession does the same

**Comment by micheleselea** [comment]
Ah forgot another point: in the old FTPClientSession I think we could have a problem if the connection is not authenticated so if you do not call login. Because only in login we read the welcome message (I put it in `receiveServerReadyReply()` function) otherwise the reply is not read, and I think we can screw up the reply to the first command: not sure about this but looking the code it seams

**Comment by obiltschnig** [comment]
I'm fine with making _pControlSocket and _pDataStream protected. I'd like to keep both FTPClientSession and FTPSClientSession, but the fallback in FTPSClientSession is fine. Adding a method secure() to indicate whether the connection is using TLS would be a good idea.
Also, please format the code according to our styleguide to save me some work.

**Comment by micheleselea** [comment]
Ok, I'm going to make the changes, and than I'll post new file. Give me just a couple of days because I don't know if today I can put hands on

**Comment by micheleselea** [comment]
Ok I think I did it. I have changed FTPClientSession to make protected member I need in FTPSClientSession. I tried to write with code in Poco style, just have a look to files.
In zip file I have re-created the Poco/Net and Poco/NetSSL_OpenSSL directory tree
[FTPS.zip](https://github.com/pocoproject/poco/files/378277/FTPS.zip)

**Comment by micheleselea** [comment]
I think it's better to set setNoDelay(true) for control and data socket

**Comment by AnotherCodeSegment** [comment]
Any plans to create a branch for this?

**Comment by obiltschnig** [comment]
No, it will go into the poco-1.8.0 and develop branches.

**Comment by micheleselea** [comment]
I tested the FTPSClientSession for a while and I think it works good.
The only thing I think we should change is when we pass an external socket to the class, the constructor is like:
`FTPClientSession::FTPClientSession(const` StreamSocket& socket):`
	`_host(socket.address().host().toString()),`
	`_port(socket.address().port()),`
	`_pControlSocket(new` DialogSocket(socket)),`
	`_pDataStream(0),`
	`_passiveMode(true),`
	`_fileType(TYPE_BINARY),`
	`_supports1738(true),`
	`_serverReady(false),`
	`_isLoggedIn(false),`
	`_timeout(DEFAULT_TIMEOUT)``
`{``
	`_pControlSocket->setReceiveTimeout(_timeout);`
`}`

I think we should add
'receiveServerReadyReply();`
after set timeout, so you are ready to do all stuff need, otherwise if you send some command before do open() or login() or other stuff it results in a request/reply desync.

explain better:
Client->Server OPEN socket
Server->Client SendWelcome message
Client->Server sendCommand() whatever (that read as reply the Welcome message)
Client->login desync....

**Comment by Tyrben** [comment]
Hi guys,
This feature looks excellent and very achieved.
Do you plan to integrate it into a release soon?

**Comment by micheleselea** [comment]
I'm using since 3/4 years in my production environment so I think it's
stable. Probably what is missing is some kind of "well written" code 

2019-12-27 10:35 Tyrben ha scritto:

> Hi guys,
> This feature looks excellent and very achieved.
> Do you plan to integrate it into a release soon? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/pocoproject/poco/issues/1297?email_source=notifications&amp;email_token=ABNHXD2WPQURE7S5TH6ILQTQ2XD6DA5CNFSM4CHSKSHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHW4VVA#issuecomment-569232084
[2]

**Comment by obiltschnig** [comment]
merged into poco-1.10.0
