### ISSUE TITLE
ZipFileInfo: Assertion violation when reading ods files

### ISSUE THREAD

**Issue by few** [pocoproject/poco#1298]
Reading an ods file (which is a zip file) (created by LibreOffice Calc 4.2) leads to the following error message:

Assertion violation: std::memcmp(_rawInfo, HEADER, ZipCommon::HEADER_SIZE) == 0 [in file "src/ZipFileInfo.cpp", line 93]

This breaks the "Decompress Single Files" example in the documentation when reading from the stream.
Note that Decompress is able to decompress the entire archive without a problem.

poco-1.7.3 build from source on Ubuntu 14.04 x86_64.

**Comment by obiltschnig** [comment]
Could you provide the ods file and steps to reproduce the issue?

**Comment by obiltschnig** [comment]
See also #1416
