### ISSUE TITLE
Application logger() exception

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1301]
Hi all, I found that if you use Application logger like
`Poco::Util::Application::instance().logger().information("Application is running...")`
if for some reason you are running out of space from the function throw exception, and if not catched you can have crash in your app.
Because there're some define like poco_information that already incapsulate logger, we can have another define that is exception free, for example I tested on windows and linux something like
`#define poco_log_notice_safe(format, ...)\
    try {Poco::Util::Application::instance().logger().notice(format, ##__VA_ARGS__);}catch(...){}`

**Comment by obiltschnig** [comment]
Contribution welcome. Please rename macros to poco_log_*_nothrow().

**Comment by micheleselea** [comment]
`#if defined(_DEBUG) || defined(POCO_LOG_DEBUG)
#ifndef poco_log_debug_nothrow
#define poco_log_debug_nothrow(format, ...)\
	try {Poco::Util::Application::instance().logger().debug(format, ##__VA_ARGS__);}catch(...){}
#endif
#ifndef poco_log_trace_nothrow
#define poco_log_trace_nothrow(format, ...)\
	try {Poco::Util::Application::instance().logger().trace(format, ##__VA_ARGS__);}catch(...){}
#endif
#else
#define poco_log_debug_nothrow(format, ...)
#define poco_log_trace_nothrow(format, ...)
#endif

#ifndef poco_log_notice_nothrow
#define poco_log_notice_nothrow(format, ...)\
	try {Poco::Util::Application::instance().logger().notice(format, ##__VA_ARGS__);}catch(...){}
#endif

#ifndef poco_log_information_nothrow
#define poco_log_info_nothrow(format, ...)\
	try {Poco::Util::Application::instance().logger().information(format, ##__VA_ARGS__);}catch(...){}
#endif

#ifndef poco_log_warning_nothrow
#define poco_log_warning_nothrow(format, ...)\
	try {Poco::Util::Application::instance().logger().warning(format, ##__VA_ARGS__);}catch(...){}
#endif

#ifndef poco_log_error_nothrow
#define poco_log_error_nothrow(format, ...)\
	try {Poco::Util::Application::instance().logger().error(format, ##__VA_ARGS__);}catch(...){}
#endif

#ifndef poco_log_critical_nothrow
#define poco_log_critical_nothrow(format, ...)\
	try {Poco::Util::Application::instance().logger().critical(format, ##__VA_ARGS__);}catch(...){}
#endif

#ifndef poco_log_fatal_nothrow
#define poco_log_fatal_nothrow(format, ...)\
	try {Poco::Util::Application::instance().logger().fatal(format, ##__VA_ARGS__);}catch(...){}
#endif
`

**Comment by micheleselea** [comment]
Here you are a .h file with define coded as the "convenience macros" in Logger.h
[poco_log_nothrow.txt](https://github.com/pocoproject/poco/files/345687/poco_log_nothrow.txt)
