### ISSUE TITLE
Inconsistent behavior between OS of HTTP headers containing newlines

### ISSUE THREAD

**Issue by ahh** [pocoproject/poco#1302]
I am not clear if there are standardization issues that make this WAI, but there is a puzzling inconsistency with POCO's HTTP client between OSX and Linux.  

Specifically, on Linux, sending a HTTP request with a custom header containing a newline succeeds; on OSX, we get a "400 Bad Request" from every server I've tried.  Repro is quite simple; Github won't let me attach a C++ source file (seriously?) so here it is inline:

```
#include <cassert>
#include <string>
#include <iostream>

#include "Poco/URI.h"
#include "Poco/Net/HTTPClientSession.h"
#include "Poco/Net/HTTPRequest.h"
#include "Poco/Net/HTTPResponse.h"

using Poco::URI;
using Poco::Net::HTTPClientSession;
using Poco::Net::HTTPRequest;
using Poco::Net::HTTPResponse;

int main() {
  URI uri("http://httpbin.org/post");
  HTTPClientSession session(uri.getHost(), uri.getPort());
  HTTPRequest req(HTTPRequest::HTTP_POST, uri.getPathAndQuery(),
                  Poco::Net::HTTPMessage::HTTP_1_1);

  req.set("X-Dummy-Header", "bar\n");
  req.setContentType("application/json");
  std::string body = "{ \"foo\" : 1 }";
  req.setContentLength(body.length());
  session.sendRequest(req) << body;
  HTTPResponse resp;
  auto &rs = session.receiveResponse(resp);
  std::string got(std::istreambuf_iterator<char>(rs), {});
  std::cout << got << std::endl << resp.getReason() << std::endl;
  return 0;
}
```

On Linux output is:

```
{
  "args": {},
  "data": "\r\n{ \"foo\" : 1",
  "files": {},
  "form": {},
  "headers": {
    "Content-Length": "13",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "X-Dummy-Header": "bar"
  },
  "json": null,
  "origin": "74.125.59.6",
  "url": "http://httpbin.org/post"
}
```

On OSX output is:

```
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

Bad Request
```

This reproduces with the latest release.

**Comment by micheleselea** [comment]
probably `req.set("X-Dummy-Header", "bar\n");` the \n screw up the HTTP header. I think it's just the CRLF SO difference. But if you use `req.set("X-Dummy-Header", "bar");` it works?

**Comment by ahh** [comment]
Correct - it's the ```\n``` that causes the problem.  I assume as you do that it's something to do with newline encoding, but I feel like this isn't what should happen.

**Comment by micheleselea** [comment]
Probably the set function should check \r or \n is not present in value, but if you put that kind of header you can early stop the HTTP header and the server does not finish parsing header

**Comment by obiltschnig** [comment]
HTTP header fields must not contain LF or CR LF except for header field continuations, which allows the value to be split across multiple lines. However, in this case, a TAB or SPACE must immediately follow the CR LF. This is currently supported when reading header fields (in this case, the CF LF SPACE/TAB sequence is reduced to a single SPACE), but not when writing them. Therefore, including a CR or LF in a header value will lead to a malformed request or response, unless the setter takes care of proper continuation formatting.

**Comment by ahh** [comment]
Why does the request not end up malformed on Linux? They and OSX use the
same CR encoding...(I think.)
