### ISSUE TITLE
BoringSSL support for Android 6

### ISSUE THREAD

**Issue by syedhali** [pocoproject/poco#1314]
According to Google, starting with Android 6 they are moving away from OpenSSL and towards [BoringSSL](https://boringssl.googlesource.com/boringssl/). To support Android versions 6+ it'd be fantastic if Poco could support BoringSSL (which is a fork of OpenSSL). 

I can confirm the NetSSL lib doesn't work with Android 6 (`SSL Exception` is raised, but works fine with any Android version below 6). 

Android 6.0 BoringSSL change discussed here: [here](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html)

**Inline google message:**
![screen shot 2016-07-14 at 3 00 27 pm](https://cloud.githubusercontent.com/assets/1275640/16855409/d654f97e-49da-11e6-85e3-ed83a943d321.png)

**Comment by dsoprea** [comment]
Any updates to this? Is there any evidence that BoringSSL isn't already supported? It's just a Google-controlled OpenSSL. The APIs and even output library files are typically the same (maybe some macros made into actual functions, but this is minor).
