### ISSUE TITLE
Empty SocketReactor never sleeps

### ISSUE THREAD

**Issue by mkarasik** [pocoproject/poco#1316]
If you look at SocketReactor code

`

 void SocketReactor::run()
 {
 ...
    if (nSockets == 0)
    {
	onIdle();
        Thread::trySleep(_timeout.milliseconds());
    }
`
It is trying to sleep just 'milliseconds' part of the span, not the whole configured time.

Shouldn't it be as below?

` Thread::trySleep(_timeout.totalMilliseconds());`

**Comment by micheleselea** [comment]
I think you are right, It's ok if you leave the 250ms default wait time, but if you set it to 1sec you obtain a trySleep(0).
Anyway usually is not so critical to change that sleep value, but I think should be fixed

**Comment by obiltschnig** [comment]
I can confirm it's a bug.
