### ISSUE TITLE
Multiprocessor compilation

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1323]
In next release of Poco libs should be nice to have the "Multiprocessor compilation" in Visualstudio solutions enabled by default

**Comment by aleks-f** [comment]
Since we have no progen anymore, quite  bit of work here to go through all 2015/17 projects. cmake-only maybe?
/cc @micheleselea @obiltschnig

**Comment by micheleselea** [comment]
I think is not a key features: if someone need it (like me) can change a compilation flag in project solution used. So nevermind the change for all project files

**Comment by zosrothko** [comment]
@micheleselea That's already the case, Multiprocessor is enabled

**Comment by zosrothko** [comment]
@aleks-f @micheleselea Changing/adding/removing an XML element from all vxcproj files is easy to do with XSLT. So even if ProGen is not updated anymore, one can change globally all vcxproj files if needed.
