### ISSUE TITLE
Possibility of memory leaks during usage of Poco::JSON::Object 

### ISSUE THREAD

**Issue by rynkowsg** [pocoproject/poco#1335]
```
Object::Ptr object = result.extract<Object::Ptr>();
```
```
Object::Ptr object = Object::Ptr(new Object());
```
```
Object::Ptr object = new Object();
```
All above samples are correct, but what if some less experienced C++ programmer with some Java experience would try this:
```
Object object = new Object();
```
**It works, compiler doesn't complain but it is not correct.**
The latest example is not assigning, it is an initialization of `Object`, it is an equivalent of:
```
Object object(new Object());
```

`Poco::JSON::Object` allows to use two constructors:
```
Object(bool preserveInsertionOrder = false);
Object(const Object& copy);
```
The wrong example uses the first one - `new Object()` creates a pointer that compiler implicitly cast into `bool`.
There were constructed two objects:
- on the right, there will be created an object on the heap, without a possibility of releasing,
- the second object, created on the stack, will have by default `preserveInsertionOrder` assign to true.

I saw that usage in my organisation, and I thought that that `Poco::JSON::Object`' interface should not allow for that usage. 

**Make interfaces easy to use correctly and hard to use incorrectly.**

I'll create a pull request with modification of the first constructor to add an explicit expectation of `bool` value.

**Comment by obiltschnig** [comment]
Correct, Object(bool) ctor should definitely be explicit.

**Comment by rynkowsg** [comment]
Thanks!
