### ISSUE TITLE
Poco::Crypto RSA

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1340]
Hello.
Does library have variants to decrypt message by public RSA key. 
I have found that openSSL library has function for decrypt message by public KEY which called RSA_public_decrypt(...), but Poco library uses only RSA_private_decrypt(...).

Is there any chance that this type of decryption will be added in future?

**Comment by cristiantm** [comment]
While it could be done, may I ask you why you need it? Usually RSA public decyption is used for signature validation, and it is available by using RSADigestEngine (that uses RSA_verify)

**Comment by skident** [comment]
Maybe it is a way to resolve my issue, but I need more comments or example for understand how it works
