### ISSUE TITLE
Error	C2061	syntax error: identifier 'storage'

### ISSUE THREAD

**Issue by ML1** [pocoproject/poco#1343]
Hello,

I got storage error when I complied with debug configuration of project. I looked the Alignment.h file and saw that when we commented #define POCO_HAVE_ALIGNMENT line everything is fine. What will be the exact problem? Platform: VC++ 2015,x64 I have some thoughts maybe it is related with #ifdef POCO_ENABLE_CPP11 preprocessor definition but it is compiled in release configuration.

Thanks in Advance

**Comment by zosrothko** [comment]
Can you drop the exact compile error message?

**Comment by ML1** [comment]
These are errors:

1>C:\poco-1.7.4-all\Net\include\Poco/Net/IPAddress.h(438): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/IPAddress.h(448): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/IPAddress.h(458): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/IPAddress.h(468): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/IPAddress.h(478): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/IPAddress.h(488): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/IPAddress.h(498): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/SocketAddress.h(202): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/SocketAddress.h(212): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/SocketAddress.h(222): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/SocketAddress.h(233): error C2061: syntax error: identifier 'storage'
1>C:\poco-1.7.4-all\Net\include\Poco/Net/SocketAddress.h(243): error C2061: syntax error: identifier 'storage'

Thanks

**Comment by ML1** [comment]
https://github.com/pocoproject/poco/issues/234

Similar to this issue:
we commented #define POCO_HAVE_ALIGNMENT line everything is fine.

**Comment by ML1** [comment]
1>c:\users\m1\documents\wxrememberme_src\wxmemdbg.h(28): warning C4005: 'new': macro redefinition

#ifdef _DEBUG
#define new DEBUG_NEW
#endif 

Could be related with previous warning? wxwidget's new macro redefinition is changing new storage line?
#ifdef POCO_HAVE_ALIGNMENT
	new (storage()) Poco::Net::Impl::IPv4SocketAddressImpl;
#else
	_pImpl = new Poco::Net::Impl::IPv4SocketAddressImpl;
#endif

**Comment by obiltschnig** [comment]
That's probably the issue. The small object optimization in IPAddress and elsewhere needs placement new, which is probably not supported by wxwidgets DEBUG_NEW. Also, there will very likely be runtime issues if you mix DEBUG_NEW with C++'s new. I'd suggest disabling wxwidget's DEBUG_NEW, if possible.
