### ISSUE TITLE
[PocoXML] [VxWorks] constants not correctly initialised

### ISSUE THREAD

**Issue by skarux** [pocoproject/poco#1354]
The constants declared in Poco/SAX/XMLReader.h do not get correctly initialised when compiling with g++ 4.3.3 on VxWorks 6.9, probably because of VxWorks issues dealing with static objects initialised by functions.
In particular I am talking about:

```
// SAX Features
static const XMLString FEATURE_VALIDATION;
static const XMLString FEATURE_NAMESPACES;
static const XMLString FEATURE_NAMESPACE_PREFIXES;
static const XMLString FEATURE_EXTERNAL_GENERAL_ENTITIES;
static const XMLString FEATURE_EXTERNAL_PARAMETER_ENTITIES;
static const XMLString FEATURE_STRING_INTERNING;

// SAX Properties
static const XMLString PROPERTY_DECLARATION_HANDLER;
static const XMLString PROPERTY_LEXICAL_HANDLER;
```

initialised in XMLReader.cpp

```
const XMLString XMLReader::FEATURE_VALIDATION                  = toXMLString("http://xml.org/sax/features/validation");
const XMLString XMLReader::FEATURE_NAMESPACES                  = toXMLString("http://xml.org/sax/features/namespaces");
const XMLString XMLReader::FEATURE_NAMESPACE_PREFIXES          = toXMLString("http://xml.org/sax/features/namespace-prefixes");
const XMLString XMLReader::FEATURE_EXTERNAL_GENERAL_ENTITIES   = toXMLString("http://xml.org/sax/features/external-general-entities");
const XMLString XMLReader::FEATURE_EXTERNAL_PARAMETER_ENTITIES = toXMLString("http://xml.org/sax/features/external-parameter-entities");
const XMLString XMLReader::FEATURE_STRING_INTERNING            = toXMLString("http://xml.org/sax/features/string-interning");
const XMLString XMLReader::PROPERTY_DECLARATION_HANDLER        = toXMLString("http://xml.org/sax/properties/declaration-handler");
const XMLString XMLReader::PROPERTY_LEXICAL_HANDLER            = toXMLString("http://xml.org/sax/properties/lexical-handler");
```

Trying to print  these constants they are always null, and it happens with any object initialised using a function.

Note: I am using Poco 1.7.4 and to compile the sources I have used my own makefile since the attached VxWorks project is generated for VxWorks 5.x PPC and Tornado, that does not work with VxWorks 6.x+

**Comment by obiltschnig** [comment]
Not much we can do about it. At one point you just have to assume a correctly working C++ compiler and runtime. But then, this is VxWorks...

**Comment by skarux** [comment]
I know, I often get this kind of weird issues working with VxWorks. In my project I'll probably switch them to integers since looking at the code it looks like that their content it is never actually retrieved but only used as "indicator".

**Comment by obiltschnig** [comment]
Have you talked to WindRiver support about that issue? Given what they charge for VxWorks, they should at least be able to provide a solution.

**Comment by skarux** [comment]
Not yet since at the moment using Poco libraries is just a kind of "experiment", we are still checking out other alternatives. 
Since we switched from C to C++ we are getting many issues with the WindRiver mutilated version of g++ and VxWorks, in particular with munching and other stuff related to static objects that never work as they should.

**Comment by obiltschnig** [comment]
So, things have not really improved since I did the port to 5.5.1 some years ago.
