### ISSUE TITLE
[JSON::Object] After copy-ctor, JSON::Object::_keys still points to keys in map of copied object

### ISSUE THREAD

**Issue by mazhen2009** [pocoproject/poco#1355]
JSON::Array jsnArry;
	for (size_t k = 0; k < 10; k++)
	{
		JSON::Object subObjValue(true);
		subObjValue.set("Value", "value1");
		subObjValue.set("Frequency", "Frequency1");
		jsnArry.add(subObjValue);
	}

jsnArry.add(subObjValue) will copy subObjValue, and the _keys was copied. but the _keys is **&ret.first->first**.  It was not updated to the new pointer.

**Comment by obiltschnig** [comment]
@fbraem please have a look.
