### ISSUE TITLE
Bug with Poco::JSON::OBject Stringify method

### ISSUE THREAD

**Issue by aarruunn-23** [pocoproject/poco#1357]
Earlier I used poco 1.5.2 JSON object stringify method. It returned the result:

{
"apiName" : "Help",
"payload" : "[\n {\n  \"api\" : \"/v2/module/module/?starttime=#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"/v2/module/module/?starttime =#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"/v2/module/exception/?starttime =#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"/v2/module/module/?starttime =#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"/v2/module/module/?starttime =#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"/v2/lamps\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"/v2/module/help\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"/v2/module/version\",\n  \"method\" : \"GET\"\n }\n]"
}

Recently I have upgraded to poco 1.7.4. The same poco json object stringify method returns:

{
 "apiName" : "Help",
 "payload" : "[\n {\n  \"api\" : \"\\\/v2\\\/module\\\/module\\\/?starttime=#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"\\\/v2\\\/module\\\/module\\\/?starttime =#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"\\\/v2\\\/module\\\/exception\\\/?starttime =#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"\\\/v2\\\/module\\\/module\\\/?starttime =#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"\\\/v2\\\/module\\\/module\\\/?starttime =#&endtime=#&state=#\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"\\\/v2\\\/lamps\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"\\\/v2\\\/module\\\/help\",\n  \"method\" : \"GET\"\n },\n {\n  \"api\" : \"\\\/v2\\\/module\\\/version\",\n  \"method\" : \"GET\"\n }\n]"
}

The problem is the extra two slashes \\\ everywhere in 1.7.4. So what is that I am dong wrong?? Has anything changed in stringify method after 1.5.2. If you compare two results you can find the problem.

The code is as follows:

	Poco::JSON::Object main;	
        main.set("apiName", oResponse.GetResourceName());
        main.set("payload", oResponse.GetPayload());		
        main.stringify(responseStr, 0);

The responseStr output is what I have shown above for both 1.5.2 and 1.7.4. What is the issue since I run this same 4 lines in different versions of poco but get different results?? I have searched in google as well but found nothing concrete.

**Comment by aarruunn-23** [comment]
@aleks-f

**Comment by obiltschnig** [comment]
There have been various fixes in the JSON library since 1.5.2.

Escaping the solidus ('/') is valid in JSON (although, in most cases it's not really necessary; see http://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped for an explanation). Maybe the Stringifier method should be changed to allow passing an option to not escape the solidus.
