### ISSUE TITLE
Error detected running test suite.

### ISSUE THREAD

**Issue by cwaldron** [pocoproject/poco#1360]
After downloading poco and build the library and test suite, the errors below were reported.  Any direction or suggestions to fix these error are helpful.  Thanks.

!!!FAILURES!!!
Runs: 700   Failures: 1   Errors: 8

There were 8 errors:
 1: class CppUnit::TestCaller<class ProcessTest>.testLaunch
    "class Poco::SystemException: System exception"
    in "<unknown>", line -1
 2: class CppUnit::TestCaller<class ProcessTest>.testLaunchRedirectIn
    "class Poco::SystemException: System exception"
    in "<unknown>", line -1
 3: class CppUnit::TestCaller<class ProcessTest>.testLaunchRedirectOut
    "class Poco::SystemException: System exception"
    in "<unknown>", line -1
 4: class CppUnit::TestCaller<class ProcessTest>.testLaunchEnv
    "class Poco::SystemException: System exception"
    in "<unknown>", line -1
 5: class CppUnit::TestCaller<class ProcessTest>.testLaunchArgs
    "class Poco::SystemException: System exception"
    in "<unknown>", line -1
 6: class CppUnit::TestCaller<class ProcessTest>.testIsRunning
    "class Poco::SystemException: System exception"
    in "<unknown>", line -1
 7: class CppUnit::TestCaller<class ProcessTest>.testIsRunningAllowsForTermination
    "class Poco::SystemException: System exception"
    in "<unknown>", line -1
 8: class CppUnit::TestCaller<class SharedMemoryTest>.testCreateFromFile
    "class Poco::NotFoundException: Not found"
    in "<unknown>", line -1

There was 1 failure:
 1: class CppUnit::TestCaller<class PatternFormatterTest>.testPatternFormatter
    "result.find("2005-01-01 ") == 0"
    in "src\PatternFormatterTest.cpp", line 69

**Comment by nikitarulz** [comment]
Hey @cwaldron , did you find the reason or solution for the error you raised?
I'm also getting these failures with a different log.

Any hints?

**Comment by zosrothko** [comment]
Which Poco version are you building?

**Comment by nikitarulz** [comment]
Poco version 1.7.5-all

**Comment by zosrothko** [comment]
Could you try the latest Poco version: poco-1.9.0 ?

**Comment by nikitarulz** [comment]
I tried with poco-1.9.0 version as well. 
And m still getting the same errors.

```
There were 4 failures: 
 1: N7CppUnit10TestCallerI11ProcessTestEE.testLaunch
    "rc == 3"
    in "src/ProcessTest.cpp", line 61
 2: N7CppUnit10TestCallerI11ProcessTestEE.testLaunchRedirectIn
    "rc == 100"
    in "src/ProcessTest.cpp", line 89
 3: N7CppUnit10TestCallerI11ProcessTestEE.testLaunchRedirectOut
    "s == "Hello, world!""
    in "src/ProcessTest.cpp", line 118
 4: N7CppUnit10TestCallerI11ProcessTestEE.testLaunchEnv
    "s == "test""
    in "src/ProcessTest.cpp", line 151
```

**Comment by zosrothko** [comment]
How do you launch the testsuites?

**Comment by nikitarulz** [comment]
The procedure I followed:
1. Downloaded poco-1.7.5-all and poco-1.9.0-all from internet.
2. Extracted the source code. (`tar -xvf poco-xxx.tar.bz2`)
3. `cd poco-xxx`
4. `./configure`
Configured for Linux
5. `make`
(takes too much of time)
6. `cd Foundation`
7. `./testsuite/bin/Linux/armv7l/testrunner -all`

And then I got the result as `Runs: 688   Failures: 4   Errors: 0`

**Comment by nikitarulz** [comment]
But there is no runtests.sh script file present anywhere in Poco-1.7.5.

**Comment by zosrothko** [comment]
Yes you are right.. The script is only delivered starting from poco-1.9.1. Thus, you can pick up from GitHub branch poco-1.9.1

**Comment by nikitarulz** [comment]
Thanks @zosrothko , the runtests.sh scrcipt worked.

After analysing the runtests.sh script, found out that these failure test cases are dependent on **TestApp and TestAppd** library files. Either copy these files in /usr/lib or set $LD_LIBRARY_PATH to directory where these libraries are present.

Then executing `./testsuite/bin/Linux/armv7l/testrunner -all` in any version will also work.
