### ISSUE TITLE
Net::WebSocketImpl::sendBytes discarding rval of StreamSocketImpl::sendBytes

### ISSUE THREAD

**Issue by designfu** [pocoproject/poco#1362]
The length rval of `WebSocketImpl::sendBytes`'s call to `_pStreamSocketImpl->sendBytes` isn't checked - full `length` is always returned. This will get Poco undetectably out of sync if system buffers are exceeded.

**Comment by obiltschnig** [comment]
For a blocking socket, StreamSocketImpl::sendBytes() guarantees that the full buffer is always sent or an exception is thrown. The WebSocket class does not work with an underlying non-blocking socket.

**Comment by designfu** [comment]
Thanks, bad assumption on my part that Poco's non-blocking.
