### ISSUE TITLE
Possible deadlock in SessionPool

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1372]
Hi all, I think I found a possible deadlock in SessionPool shutdown function. I would know what do you think about.
The functions involved are
`void SessionPool::onJanitorTimer(Poco::Timer&)`
and
`void SessionPool::shutdown()`
the problem is in shutdown you have
`Poco::Mutex::ScopedLock lock(_mutex);`
and than
`_janitorTimer.stop();`
if timer thread is entering onJanitorTimer function you will obtain a deadlock because first line of function is ScopedLock
probably we should

```
{
Poco::Mutex::ScopedLock lock(_mutex);
  if (_shutdown) return;
  _shutdown = true;
}
  _janitorTimer.stop();
```

...

or

```
_shutdown = true;
_janitorTimer.stop();
Poco::Mutex::ScopedLock lock(_mutex);

```

let me know what you think

**Comment by obiltschnig** [comment]
I think the critical thing is doing the _janitorTimer.stop() with the mutex unlocked. 

    void SessionPool::shutdown()
    {
        {
            Poco::Mutex::ScopedLock lock(_mutex);
            if (_shutdown) return;
            _shutdown = true;
        }
        _janitorTimer.stop();

        Poco::Mutex::ScopedLock lock(_mutex);
        closeAll(_idleSessions);
        closeAll(_activeSessions);
}

**Comment by JhonAir** [comment]
Hi，Is new Release Version has the same problem?

**Comment by micheleselea** [comment]
that is a good question @obiltschnig 
I fixed my lib version with the fix you proposed but I think the original source code has the same issue
