### ISSUE TITLE
Poco::Data - NotFoundException on SELECT * FROM TABLE 

### ISSUE THREAD

**Issue by dhossein** [pocoproject/poco#1375]
Poco::Data::Select throw Poco::Data::NotFoundException for this statement: SELECT * FROM TABLE

It seems that the Poco::Data::SQLite::Utility class does not provide a mapping for sqltype UNIQUEIDENTIFIER, which corresponds to BLOB in my database. I recognize this may be a non-standard type, but I would like the option to add a mapping to the Utility class if possible. Can this be done? Please advise.

**Comment by dhossein** [comment]
Note, it's Poco::Data::Statement that throws the exception not Poco::Data::Select

**Comment by obiltschnig** [comment]
The type mapping code is in Data/SQLite/src/Utility.cpp. Adding the line

    	_types.insert(TypeMap::value_type("UNIQUEIDENTIFIER", MetaColumn::FDT_BLOB));

to the constructor should be sufficient.

**Comment by dhossein** [comment]
Thank you for the reply. Your solution will work in my particular case but it requires that I fork and patch Poco locally. There are obvious disadvantages to this approach. A more robust solution may be introduce API for adding new type mappings at runtime. Do you feel this is a reasonable feature for the next release?

**Comment by dhossein** [comment]
Also, I would comment that the NotFoundException thrown from Data::SQLite::Utility::getColumnType() could provide more information so that the issue can easily be traced back to the cause.

**Comment by obiltschnig** [comment]
It would help if you could send a pull request.

**Comment by dhossein** [comment]
Ok. I will have a look what can be done here. Just hit another sqltype that which has a same problem.

Our of curiosity, do you know of a workaround for this issue?

**Comment by dhossein** [comment]
I have created a pull request for two commits that resolve the issues above. The second commit allows sqltypes to be added at runtime with code like this:

```
#include "Poco/Data/SQLite/Utility.h"

SQLite::Utility::addColumnType("UNIQUEIDENTIFIER", MetaColumn::FDT_BLOB);
SQLite::Utility::addColumnType("XML", MetaColumn::FDT_STRING);
```
The first commit modifies behavior of the SQLite implementation so that unknown types are mapped to BLOB. This may not be totally necessary since we can add custom sqltype mappings (I just happened to make this patch first..

Please advise.

**Comment by dhossein** [comment]
Thank you for accepting my patches.

Cheers,
