### ISSUE TITLE
Poco::Crypto and/or Poco::NetSSL fail to build with OpenSSL 1.1.0 

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1376]
According to https://twitter.com/CodeSegment/status/770936033802321920:

> @pocoproject just noticed that OpenSSL 1.1.0 hides stuff required by POCO, have to stay with 1.0.2h... 😶

Have to investigate.

**Comment by mbuckaway** [comment]
Quick hack to make it compile. Crypto and Net_SSL test suites pass (with the exception of the Net_SSL proxy test - lack of available proxy)

Diff was with Openssl 1.1.0b and poco 1.7.6

[poco-openssl-1.1.0b.diff.zip](https://github.com/pocoproject/poco/files/545103/poco-openssl-1.1.0b.diff.zip)
