### ISSUE TITLE
Error of compilation while include Poco::Data::BLOB

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1382]
So, I just included the Poco::Data::BLOB.h in my source.cpp and had the compilation problem.
![image](https://cloud.githubusercontent.com/assets/4731371/18172868/f0630408-706f-11e6-97f3-855e60bd423c.png)

**Comment by zosrothko** [comment]
Which version/branch of Poco are you cloning?

**Comment by skident** [comment]
I'll check it in Monday and add this information

**Comment by skident** [comment]
The version of POCO os 1.6.0-all (2014-12-22)

**Comment by scorp12** [comment]
has there been any fix for the issue, as im having the same error with blob.h , I have tried 5 different versions of poco. all with the same error

**Comment by zosrothko** [comment]
I would suggest you to use the latest poco released version poco-1.7.8-release found here [https://github.com/pocoproject/poco/releases](https://github.com/pocoproject/poco/releases) or clone the  branch 1.7.8 from the git repo [ https://github.com/pocoproject/poco]( https://github.com/pocoproject/poco)
BTW, no Blob.h file exists in the Poco/Data includes

**Comment by scorp12** [comment]
I have tried the new release and get the same error with LOB.h

**Comment by scorp12** [comment]
Im using vs2013 with toolsets 110 and 120. Ive tried the following... 1.46p1. 1.47. 1.47p1. Poco-develop.. poco-c11.. 1.78. 1.51. 1.60.  I have about 15 dufferent versions on my computer and have built most of them several time using different build options with the results being one if two errors.

**Comment by scorp12** [comment]
Either blob.h errors or external symbol errors.

**Comment by zosrothko** [comment]
You can also install poco-1.7.3 as a msi see [VS2013.Poco.1.7.3.x64.msi](https://github.com/pocoproject/distro/releases)
BTW are you using the source tarball or a git clone?

**Comment by scorp12** [comment]
I have done from poco site. And github as a zip downliad.   Not clone

**Comment by zosrothko** [comment]
OK, it seems there is some issue with the tarball source. Could you use git as below
`git clone -b poco-1.7.8 https://github.com/pocoproject/poco poco-1.7.8`

**Comment by scorp12** [comment]
Cool thanks ill give it a try when i get home

**Comment by scorp12** [comment]
Can i ask what the issue may appear to be with tarball

**Comment by scorp12** [comment]
i was able to clone the repo as you suggested.  most seem to compile. but looking into the lib folder. all of the data folder did not auto compile. so have to manually build the folder and subfolders

**Comment by zosrothko** [comment]
That's abnormal... All modules should be produced. What command did you use to build Poco?

**Comment by scorp12** [comment]
Sorry about late reply.. didnt get an email saying anything... the cmd i used was both the vs120.bat file.  Vs110 bat file.. and buildwin file..

**Comment by scorp12** [comment]
All end up with an external error with blob.h 
Ive tried multiple version of poco with the same result

**Comment by zosrothko** [comment]
Can you give back the result of the command
```
git show
git status
git branch
type components
```
