### ISSUE TITLE
SevenZip code is outdated.

### ISSUE THREAD

**Issue by DevO2012** [pocoproject/poco#1384]
Poco appears to use outdated version of  "9.22 beta"  from "2011-04-18".

But current version is "16.02" from "2016-05-21" !

**Comment by obiltschnig** [comment]
Any volunteers to take over SevenZip maintenance?

**Comment by DevO2012** [comment]
Well I was able to usdate to 16.02 now.

https://github.com/DevO2012/poco/tree/develop/SevenZip
