### ISSUE TITLE
Fix issues reported by static source code analysis

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1397]
Here's a list of issues from a customer's analysis of the macchina.io source code with Klocwork:

    #5676: 'this->_messageType' is not initialized in this constructor.
    /macchina/platform/RemotingNG/src/BinaryDeserializer.cpp:28 | BinaryDeserializer()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #10241: Possible memory leak. Dynamic memory stored in 'li.pManifest' allocated through function 'new' at line 162 can be lost at line 181
    /macchina/platform/Foundation/include/Poco/ClassLoader.h:181 | loadLibrary()
    Code: MLK.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #10280: Possible memory leak. Dynamic memory stored in 'li.pLibrary' allocated through function 'new' at line 161 can be lost at line 181
    /macchina/platform/Foundation/include/Poco/ClassLoader.h:181 | loadLibrary()
    Code: MLK.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #23687: 'this->_null' is not initialized in this constructor.
    /macchina/platform/Data/include/Poco/Data/Extraction.h:60 | Extraction()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #36127: Possible memory leak. Dynamic memory stored in 'pSession' allocated through function 'new' at line 89 can be lost at line 162. Also there is one similar error on line 162.
    /macchina/platform/NetSSL_OpenSSL/src/HTTPSStreamFactory.cpp:162 | open()
    Code: MLK.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #36445: Possible memory leak. Dynamic memory stored in 'pSession' allocated through function 'new' at line 87 can be lost at line 131. Also there is one similar error on line 156.
    /macchina/platform/Net/src/HTTPStreamFactory.cpp:131 | open()
    Code: MLK.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #37383: 'this->_ttl' might not be initialized in this constructor.
    /macchina/platform/Net/src/ICMPSocket.cpp:43 | ICMPSocket()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #37384: 'this->_ttl' might not be initialized in this constructor.
    /macchina/platform/Net/src/ICMPSocket.cpp:51 | ICMPSocket()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #37387: 'this->_timeout' might not be initialized in this constructor.
    /macchina/platform/Net/src/ICMPSocket.cpp:43 | ICMPSocket()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #37388: 'this->_timeout' might not be initialized in this constructor.
    /macchina/platform/Net/src/ICMPSocket.cpp:51 | ICMPSocket()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #37398: 'this->_dataSize' might not be initialized in this constructor.
    /macchina/platform/Net/src/ICMPSocket.cpp:43 | ICMPSocket()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #37399: 'this->_dataSize' might not be initialized in this constructor.
    /macchina/platform/Net/src/ICMPSocket.cpp:51 | ICMPSocket()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #37463: Possible memory leak. Dynamic memory stored in 'buffer' allocated through function 'new[]' at line 58 can be lost at line 69
    /macchina/platform/Net/src/ICMPSocketImpl.cpp:69 | receiveFrom()
    Code: MLK.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #39470: 'this->_zstr.data_type' is not initialized in this constructor.
    /macchina/platform/Foundation/src/InflatingStream.cpp:47 | InflatingStreamBuf()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #39471: 'this->_zstr.data_type' is not initialized in this constructor.
    /macchina/platform/Foundation/src/InflatingStream.cpp:73 | InflatingStreamBuf()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #39472: 'this->_zstr.data_type' is not initialized in this constructor.
    /macchina/platform/Foundation/src/InflatingStream.cpp:99 | InflatingStreamBuf()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #39473: 'this->_zstr.data_type' is not initialized in this constructor.
    /macchina/platform/Foundation/src/InflatingStream.cpp:125 | InflatingStreamBuf()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #39496: 'this->_zstr.reserved' is not initialized in this constructor.
    /macchina/platform/Foundation/src/InflatingStream.cpp:47 | InflatingStreamBuf()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #39497: 'this->_zstr.reserved' is not initialized in this constructor.
    /macchina/platform/Foundation/src/InflatingStream.cpp:73 | InflatingStreamBuf()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #39498: 'this->_zstr.reserved' is not initialized in this constructor.
    /macchina/platform/Foundation/src/InflatingStream.cpp:99 | InflatingStreamBuf()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #39499: 'this->_zstr.reserved' is not initialized in this constructor.
    /macchina/platform/Foundation/src/InflatingStream.cpp:125 | InflatingStreamBuf()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #45538: 'this->_encoding' is not initialized in this constructor.
    /macchina/platform/Net/src/MailMessage.cpp:199 | MailMessage()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #45557: Possible memory leak. Dynamic memory stored in 'pPS' allocated through function 'createPartStore' at line 104 can be lost at line 120
    /macchina/platform/Net/src/MailMessage.cpp:120 | handlePart()
    Code: MLK.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #46635: Memory leak. Dynamic memory stored in 'new[]((_blockSize * sizeof(unsigned char)))' allocated through function 'new[]' at line 40 is lost at line 40
    /macchina/platform/Foundation/src/MemoryPool.cpp:40 | MemoryPool()
    Code: MLK.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #47313: 'this->_nullable' is not initialized in this constructor.
    /macchina/platform/Data/src/MetaColumn.cpp:26 | MetaColumn()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #47314: 'this->_length' is not initialized in this constructor.
    /macchina/platform/Data/src/MetaColumn.cpp:26 | MetaColumn()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #47315: 'this->_type' is not initialized in this constructor.
    /macchina/platform/Data/src/MetaColumn.cpp:26 | MetaColumn()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #47316: 'this->_position' is not initialized in this constructor.
    /macchina/platform/Data/src/MetaColumn.cpp:26 | MetaColumn()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #47317: 'this->_precision' is not initialized in this constructor.
    /macchina/platform/Data/src/MetaColumn.cpp:26 | MetaColumn()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #51307: 'this->_lockfd' is not initialized in this constructor.
    /macchina/platform/Foundation/src/NamedEvent_UNIX.cpp:84 | NamedEventImpl()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #51309: 'this->_semfd' is not initialized in this constructor.
    /macchina/platform/Foundation/src/NamedEvent_UNIX.cpp:84 | NamedEventImpl()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #51379: 'this->_lockfd' is not initialized in this constructor.
    /macchina/platform/Foundation/src/NamedMutex_UNIX.cpp:84 | NamedMutexImpl()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #51380: 'this->_semfd' is not initialized in this constructor.
    /macchina/platform/Foundation/src/NamedMutex_UNIX.cpp:84 | NamedMutexImpl()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #54199: 'this->_type' is not initialized in this constructor.
    /macchina/platform/Net/src/NetworkInterface.cpp:234 | NetworkInterfaceImpl()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #55446: 'this->_enabledEvents' might not be initialized in this constructor.
    /macchina/platform/Data/SQLite/src/Notifier.cpp:33 | Notifier()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #55447: 'this->_enabledEvents' might not be initialized in this constructor.
    /macchina/platform/Data/SQLite/src/Notifier.cpp:43 | Notifier()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #55461: 'this->_row' might not be initialized in this constructor.
    /macchina/platform/Data/SQLite/src/Notifier.cpp:33 | Notifier()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #55462: 'this->_row' might not be initialized in this constructor.
    /macchina/platform/Data/SQLite/src/Notifier.cpp:43 | Notifier()
    Code: UNINIT.CTOR.MIGHT | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #55610: 'this->_null' is not initialized in this constructor.
    /macchina/platform/Foundation/include/Poco/Nullable.h:68 | Nullable()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #55612: 'this->_null' is not initialized in this constructor.
    /macchina/platform/Foundation/include/Poco/Nullable.h:82 | Nullable()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #55613: 'this->_null' is not initialized in this constructor.
    /macchina/platform/Foundation/include/Poco/Nullable.h:89 | Nullable()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #59540: Pointer 'extParser' returned from call to function 'XML_ExternalEntityParserCreate' at line 722 may be NULL, will be passed to function and may be dereferenced there by passing argument 1 to function 'parseExternal' at line 725.
    /macchina/platform/XML/src/ParserEngine.cpp:725 | handleExternalEntityRef()
    Code: NPD.FUNC.CALL.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #59551: Pointer 'this->_parser' returned from call to function 'init' at line 242 may be NULL and will be dereferenced at line 252. Also there is one similar error on line 256.
    /macchina/platform/XML/src/ParserEngine.cpp:252 | parse()
    Code: NPD.FUNC.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #59598: Pointer '_parser' returned from call to function 'XML_ParserCreateNS' at line 452 may be NULL and will be dereferenced at line 453. Also there are 2 similar errors on line(s) 458, 466.
    /macchina/platform/XML/src/ParserEngine.cpp:453 | init()
    Code: NPD.FUNC.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #86658: 'this->_pid' is not initialized in this constructor.
    /macchina/platform/Data/src/SQLChannel.cpp:52 | SQLChannel()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #86668: 'this->_priority' is not initialized in this constructor.
    /macchina/platform/Data/src/SQLChannel.cpp:52 | SQLChannel()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #86726: 'this->_tid' is not initialized in this constructor.
    /macchina/platform/Data/src/SQLChannel.cpp:52 | SQLChannel()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #133415: 'this->_currentPart' is not initialized in this constructor.
    /macchina/platform/JSON/src/Template.cpp:356 | Template()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #133416: 'this->_currentPart' is not initialized in this constructor.
    /macchina/platform/JSON/src/Template.cpp:362 | Template()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #135021: 'this->osPrio' is not initialized in this constructor.
    /macchina/platform/Foundation/include/Poco/Thread_POSIX.h:133 | ThreadData()
    Code: UNINIT.CTOR.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #159747: Pointer 'xtra._ptr' returned from call to function 'Buffer<unsigned char>' at line 107 may be NULL and will be dereferenced at line 109.
    /macchina/platform/Zip/src/ZipFileInfo.cpp:109 | parse()
    Code: NPD.FUNC.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #159754: Pointer 'buf._ptr' returned from call to function 'Buffer<unsigned char>' at line 101 may be NULL and will be dereferenced at line 103.
    /macchina/platform/Zip/src/ZipFileInfo.cpp:103 | parse()
    Code: NPD.FUNC.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #159913: Pointer 'buf._ptr' returned from call to function 'Buffer<unsigned char>' at line 131 may be NULL and will be dereferenced at line 133.
    /macchina/platform/Zip/src/ZipLocalFileHeader.cpp:133 | parse()
    Code: NPD.FUNC.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

    #159972: Pointer 'xtra._ptr' returned from call to function 'Buffer<unsigned char>' at line 137 may be NULL and will be dereferenced at line 139.
    /macchina/platform/Zip/src/ZipLocalFileHeader.cpp:139 | parse()
    Code: NPD.FUNC.MUST | Severity: Error (3) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Owner: unowned

**Comment by micheleselea** [comment]
very interesting, which static analyzer did you use? I usually run cpp check

**Comment by micheleselea** [comment]
anyway probably some of that are just "warning" because if you look at
37463: Possible memory leak. Dynamic memory stored in 'buffer' allocated through function 'new[]' at line 58 can be lost at line 69

I check the ICMPSocketImpl::receiveFrom and buffer is correctly deleted even if throw, so that line is not an error

**Comment by obiltschnig** [comment]
Analysis was done with Klocwork, a commercial tool. The list of issues has already been filtered down to those I'd like to fix. The code in ICMPSocket will work correctly, but I don't like buffers allocated with new. Using Poco::Buffer instead will free us from having to take care of delete. Generally, there's nothing really serious, but worth looking at anyway.

**Comment by obiltschnig** [comment]
For reference:
d59ff2ac1ee9ca49f5c6239b43b9263cdd1df3ad
8a9b7abe2ff0a5ab0cb22b978655ff0469693049
0a1a4f70dd6d653e7f3861ff4d16b45f0685e90e
9bc12df4a213886ec2ce71c5275b3d408d5d936b
e6034908c1106a8b03c77e8d411842217b75463f
1fb56d8c8e21f8836375751c53fb601543e4b516
cb2537b343d2488147e2ce22980d61ddc1c2b853
6441479f4dc815e9163d4bba910ada97f393b21e
5ad31f223673c7908828973806a8c6b3a8bd4713
e07dbdc718c85efeb027ac28607287ca7cdb600d
c716239c222b4320941287b6d42c1b45166e52cb
26ccbe2504351bbd85ad11381dcc3f33f74b4649
9cefa0d8889b344a0f28bcf345e69ed1c5990991
22a5def3936a26e3b3ef78c2852a63ffc22ab0f8
075cfeb4cb4d3114c9ec10a2b1b8681c6f04f8c7
7c43cc8ec2c98a8dc284eb69659b1cd2c657add9
8d053e259cfb707b31377c39ca44548f60fda442
caed8507f45e637658104bdb3790f3c74035bd1d
