### ISSUE TITLE
Review/Add EntityModel to Data

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1405]
Just a reminder to review and possibly add the contribution by @throstur62

**Comment by aleks-f** [comment]
@obiltschnig where is this contribution?

**Comment by obiltschnig** [comment]
https://gist.github.com/obiltschnig/083281497f28b10c510119089887d7f2
https://gist.github.com/obiltschnig/f65dd18845baf27fbc15b012f6dd0d8a

**Comment by aleks-f** [comment]
Not all implementation is there, are there .cpp files?

Regarding [this](https://gist.github.com/obiltschnig/f65dd18845baf27fbc15b012f6dd0d8a#file-entityserver-h-L77) issue, the workaround is simple, I answered on [SO](https://stackoverflow.com/a/47044158/205386)
