### ISSUE TITLE
Poco::JSON::Object::getNames()

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1406]
Hello, guys!
I need to get names from JSON Object in the same order as in request (not sorted)

So, when I send the JSON object like this {"B":11, "A":12}, I want to get ["B", "A"] names (as in original object)

Also, could you please add description to method Poco::JSON::Object::getNames() in which order the names will be given. I see that names are in the Lexicographical order, but I'm not sure that this property has guaranteed by library

**Comment by fbraem** [comment]
It's true getNames doesn't take account of the preserve order switch. When preserve order is true, we should return it in the original order. I don't think this fix will break anything.
