### ISSUE TITLE
Insert NULL value into Database

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1407]
How to insert NULL value through ODBC using Poco?

I have a list of Poco::Any which contains values for binding to query. For example I have the optional field in table with type int. 
What kind of value I should insert into listPoco::Any for insert NULL in this field?

**Comment by makarychev** [comment]
Hello, 
I think It should be Poco::Any() with empty constructor. It works for me.
If the Any is empty typeid(void) is returned.
And if deep dive the right case is here for NULL
`void AbstractBinder::bind(....) 
{`
`...`
	`else if(type == typeid(void))`
	`	bind(pos, Keywords::null, dir);`
`...}`

**Comment by ostropik** [comment]
This doesn't work for type IMAGE (
