### ISSUE TITLE
is this a bug? SocketReactor can't handle reset by peer excption.

### ISSUE THREAD

**Issue by whidbey** [pocoproject/poco#1413]
Poco::Net::SocketReactor 's code.

void SocketReactor::run()

When the socket actor as client,
once the connection complete, and the server hangs.

the client will raise exception in the SocketReactor::run()'s loop

it' cant' handle these error at all and just continue to raise the error forever.

**Comment by whidbey** [comment]
http://stackoverflow.com/questions/2742708/socket-select-handling-abrupt-disconnections
this guy same problem like me.
but I can't find any fix in version 1.7.5 and 1.7.2

**Comment by whidbey** [comment]
the problem maybe raise by dispatch function，

**Comment by obiltschnig** [comment]
Cannot reproduce this issue. Note that in your onReadable handler, you'll need to check whether receiveBytes() returns 0, and in this case delete your handler. The same if you catch a socket-related exception - you'll have to place a try...catch block around your onReadable handler code. Unfortunately, this code was missing from the EchoServer sample, which suffers from the same issue.

**Comment by whidbey** [comment]
the try catch may not help ,but remove handler may help for me.thanks.
