### ISSUE TITLE
Onwriteable and sendbytes in socket.

### ISSUE THREAD

**Issue by whidbey** [pocoproject/poco#1417]
I noticed that,if I implement onwriteable method for reactor.

this method will loop execute when a readable finished.
if I block (or sleep for example in readable event for 100seconds),and then

onwriteable will wait for 100seconds after readable.

however, within the 100seconds,I can sendbytes to client just nothing about with onwriteable.
is am right?

**Comment by whidbey** [comment]
and a notice is ,when I implement onwritable,the cpu would exceed to 25%..
and I comment it, it will run 

so I think the problem is the SocketActor.cpp 's "run" code has someproblem.

**"that is"**  it never used a timeout when socket.select(...)  it just a deadloop in it.

**Comment by micheleselea** [comment]
I think you have to "schedule" onwritable only when you have to write something otherwise remove it, because usually a socket is always writebale

**Comment by obiltschnig** [comment]
Yes, a socket is virtually always writable, unless you manage to fill up the send buffer by sending just too much data. Therefore, onWritable should only be used when you actually have something to write, otherwise you'll end up with mentioned issue.

**Comment by whidbey** [comment]
that's ok，I will remove the wriable event and I will use notificationqueue to store the many datas.
and then send one by one.

**Comment by whidbey** [comment]
thanks
