### ISSUE TITLE
Poco::Delegate assignment operator fails to compile for some specializations

### ISSUE THREAD

**Issue by tmarschen** [pocoproject/poco#1418]
Hello Dear,

I am using POCO for my project. But I got some compiler error on poco-1.7.4-release.

This is the error info:
"...\Foundation\include\Poco/Delegate.h", line 344: Error: #135: class template "Poco::Delegate" has no member "_pTarget"
this->_pTarget = delegate._pTarget;
^
"...\Foundation\include\Poco/Delegate.h", line 344: Error: #135: class template "Poco::Delegate" has no member "_pTarget"
this->_pTarget = delegate._pTarget;
^
...\Net\src\HTTPServerConnection.cpp: 484 warnings, 2 errors

If I remove this line in Delegate.h, it will compile success.But I am not sure if it's OK.

It's highly appreciated if anyone can help me.

thanks

B.R.

**Comment by obiltschnig** [comment]
That assignment to _pTarget definitely does not make sense and can be safely removed.

**Comment by tmarschen** [comment]
Hello, obiltschnig 

Thanks very much for your feedback. 

B.R.
