### ISSUE TITLE
serversocket can listen on same port 

### ISSUE THREAD

**Issue by whidbey** [pocoproject/poco#1419]
ServerSocket create event( listen) can apply multi times in multi applications..
is this normal?

[btw: I mean  a serversocket can run in serveral application with the same port  default..

ServerSocket a(12345);
ServerSocket b(12345);
ServerSocket c(12345);

and netstat -an ,there is 3 "12345"

**Comment by obiltschnig** [comment]
That's because the ServerSocket constructor taking a SocketAddress or port number will set the SO_REUSEADDR and SO_REUSEPORT options. To disable that, use the default constructor of ServerSocket and manually call bind() and listen().

**Comment by whidbey** [comment]
thank you. i see.
