### ISSUE TITLE
Repository Reorganization

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1420]
I plan to reorganize the GitHub repository in the near future, with the goal to:
- Have a poco "core" repository containing the libraries that are part of the release packages
- Have separate repositories for other libraries.

Note: this is a work in progress, subject to further discussion.

Ultimately, the poco repository will only contain the following libraries and tools:
- CppUnit
- Foundation
- XML
- JSON
- Util
- Net
- Crypto
- NetSSL_OpenSSL
- Data
- Data/SQLite
- Data/ODBC
- Data/MySQL
- PageCompiler

All other libraries will be moved into their own repositories:
- CppParser
- MongoDB
- Redis
- PDF
- ApacheConnector
- NetSSL_Win and Crypto_Win
- SevenZip
- ProGen
- PocoDoc

This will allow us to nominate maintainers for the various libraries and give them full GitHub access to these repositories, without having to give everyone full access to the poco repository. Also, it will get libraries that are currently not maintained (PDF, SevenZip) out of the main codebase.

**Comment by zosrothko** [comment]
I would suggest to put also NetSSL_Win & Crypt_Win in the core codebase for consistency.

**Comment by RangelReale** [comment]
What about the "NetEx" library we were talking about in the past?

**Comment by obiltschnig** [comment]
NetEx should go into its own repository.

Regarding NetSSL_Win and Crypto_Win - these would need a bit more work and testing (especially Crypto_Win), as well as a regular maintainer.

**Comment by aleks-f** [comment]
I have a NetEx stale sandbox somewhere, with async HTTP client and everything moved (ICMP etc). I can take ownership of that portion transition.
