### ISSUE TITLE
Problem with STLPort 

### ISSUE THREAD

**Issue by smesgary** [pocoproject/poco#1421]
Hi everybody,
I am building poco library for arm-linux. When i tried to compile using cross compiler(gcc 4.7), i get the error of STLPort, so i installed stlport(5.2.1) and then i get some errors about std::isnan and std::isinf , ... .
After that i consider that the ARM-Linux config file suggest gcc 2.95.3 and STLport 4.6.2. Both of them are very old. So i delete the options for STLport in ARM-Linux file like this:

#
## System Specific Flags
#
SYSFLAGS =  -I$(OPENSSL_INCLUDE) -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_REENTRANT -D_THREAD_SAFE -DPOCO_NO_FPENVIRONMENT

#
## System Specific Libraries
#
SYSLIBS  =  -L$(OPENSSL_LIB) -lpthread -ldl -lrt

and the i compiled the poco for ARM-Linux and everything seems OK.
does it make any problem?
Can't we use STL instead of STLPort with newer version of GCC?
Can i commit this code?

**Comment by obiltschnig** [comment]
There's no need to use STLPort anymore. That specific configuration was for an Embedded Linux platform with an old GCC. You should use one of the other configurations as template, like Angstrom or BeagleBoard.

**Comment by obiltschnig** [comment]
Note to maintainers: remove or update obsolete build configurations

**Comment by smesgary** [comment]
Thanks a lot.
