### ISSUE TITLE
Windows 10 Anniversary Update NetSSL_Win

### ISSUE THREAD

**Issue by jalmoreno** [pocoproject/poco#1423]
I'm update Windows 10 to Anniversary Update and compile the download example, when try download i've got this exception:
"Failed to acquire Schannel credentials: The Local Security Authority cannot be contacted". 

After this exception Windows crashs and restart. 

This problem just happens on this last Windows 10 Update. 
Someone got this problem also?

Regards.

**Comment by bracketttc** [comment]
Reproduced. Windows 10 Anniversary Update, develop branch, CMake build with generator Visual Studio 14 2015 Win64 and Visual Studio 14 2015.

Exception seems to occur anytime you attempt to make an SSL connection. Insecure connections work normally.

**Comment by jalmoreno** [comment]
The problem happens here:
`schannelCred.hRootStore = _hCollectionCertStore;`

For now i don't know the reason but I will be investigating and will report more details soon.

**Comment by jalmoreno** [comment]
I'm still unknown the reason about this issue inside Windows 10 Anniversary Update but, reading SCHANNEL_CRED structure, i found that:

> hRootStore
> Optional. Valid for server applications only. Handle to a certificate store that contains self-signed root certificates for certification authorities (CAs) trusted by the application. This member is used only by server-side applications that require client authentication.

So my current patch is:
`schannelCred.hRootStore = isForServerUse() ? _hCollectionCertStore : NULL;`

For now that's all.

**Comment by OlafvdSpek** [comment]
If Windows crashes there's certainly a bug there, have you reported it?

**Comment by emou** [comment]
Reproduced this using Poco 1.9.7p2 on Windows Server 2016 Standard, Build 14393. Applying all Windows updates fixed the issue.

![image](https://user-images.githubusercontent.com/48381/50970557-5efc3300-14ea-11e9-87e1-d065c84adb84.png)

The error that required the reboot was due to Isass service crashing:

![image](https://user-images.githubusercontent.com/48381/50970619-8c48e100-14ea-11e9-87bb-5849f41f00ee.png)

**Comment by OgreTransporter** [comment]
New error to same example: SSL Exception: Error during handshake: The function requested is not supported

**Comment by maxim-voronko** [comment]
We reproduced the issue with Windows Server 2016. When we attempted to make an SSL connection we had error "Failed to acquire Schannel credentials: The Local Security Authority cannot be contacted".

We replaced the line of code:
schannelCred.hRootStore = _hCollectionCertStore;
with
schannelCred.hRootStore = isForServerUse() ? _hCollectionCertStore : NULL;

Now everything is working fine.
