### ISSUE TITLE
About C++11, one module head file and project template

### ISSUE THREAD

**Issue by JiekeZhu** [pocoproject/poco#1424]
Hi there,
I'm new to server side programming. 
I have searched a lot to find the best solution for my projects. 
What I care the most is it should be convenient to use and it should have got everything I need such as http(s) module, socket, and database module and so on.
Now I see Poco got all what I need. Really excellent work.

However there are a few tiny things blocking me from using it smoothly.
1. C++11 features.
The rvalue, std::move and std::thread are not in use.  I think the C++ STL is doing a great job in making normal programming and cross-platform programming easier and with better performance. The widely used Cocos2d-x game engine is also using C++11, and the modern C++ model and style is nice. If Poco with C++11 can come to be used sooner, I think Poco would be much easier to be learned and accepted.
<p>
2. About one module head file and project template.
I highly recommend you to see the project structure of Cocos2d-x(The C++ part). It's very much easy to be used. I mean as a beginner I can start to create a project(with command line tools) and work on my stuff immediately. When I need some feature, I only need to include one module head file. Starting up with Poco, I need to know everything I need to use and then include them in. To create my own project, I need to copy the sample project and do a lot configuration as I want. .....

Poco is very good server app developing solution. It's could be easily used by any one who want to build something on the server side.

After learned Node.js, Go and hesitated with C#, I come back to C++ for server programming :)

By the way, 
For Windows platform, I suggest you to use the PropertySheets(.props) to set the configurations. It will be much easier to maintain and reusable. 
When I introduce Poco to my colleagues, they asked me if there are any performance test reports. I can't answer that. I have no idea what it would be when the core parts are compared to libEvent and Theron.

All these are my personal opinions, could be very misunderstandings. Just speak them out :)

**Comment by obiltschnig** [comment]
C++11 will hopefully come later this year, for the rest, we're open to contributions ;-)

**Comment by JiekeZhu** [comment]
Thanks for the quick response.
I will try to get familiar with Poco and do something with it. And then find my way to contributions.
Such a good library, a complete server app solution. Good luck on the journey.
