### ISSUE TITLE
memory leaks SocketReactor and ClientHandler.

### ISSUE THREAD

**Issue by whidbey** [pocoproject/poco#1430]
client sends socket message to client handler.
and
 void onReadable( Poco::Net::ReadableNotification *pNf){
        pNf->release();
        try{

```
        readMessage();
    }catch(...){
        disconnect();
    }
};
```

void ClientSession::readMessage() {
    char s[1024]={0};
    int n = _socket.receiveBytes(s,1024);
    return;
};

this will loss 4 bytes everyone or several client package come.

I guess is there something leaks here.

I am using codeblocks and can't see what's the reason;

**Comment by whidbey** [comment]
run app will ok receving message,but memory leaks.
debug app will hang up when received one or two message from client.

**Comment by whidbey** [comment]
catch exception in:

void SocketReactor::run()

   catch(Poco::Net::ConnectionResetException &ex){
            stop();
        }
		catch (Exception& exc)
		{
			ErrorHandler::handle(exc); //hang up here
		}

**Comment by whidbey** [comment]
then I find socket.sendBytes function will change my buffer.
thus, the client sendBytes to Server will undefined.
Poco::Buffer<char>  buffer;
buffer.asign something.
guess what happen if sendBytes(buffer.begin(),buffer.size()) ?
the first time will ok
and second time will cause the server OnReadable() can't reach.....

**Comment by whidbey** [comment]
sorry I can't figure it out . everything is ok in Release model.
no leaks,no hangs up..
so I guess it must be a bug...

**Comment by whidbey** [comment]
sure it's a bug of reactor..help nice fix in 1.7.6. and 
I am turn into Poco::tcpserver ,everythings is ok .but it's not good than reactor.

**Comment by whidbey** [comment]
increse the speed of client,and send package by 10ms.
the server using Poco::Net::Tcpserver is all so leaks..

however ,when compile to release,everything is smooth...

**Comment by micheleselea** [comment]
I do not understand the problem: I always use both TCPServer and Reactor without leaks...try explain better

**Comment by whidbey** [comment]
@micheleselea  how to use TCPserver and Reactor at the sametime？

I found the leaks comes from Poco::Buffer, I replace all to char is ok. everything is ok
in Release model. leaks in "Debug" model. perhaps the data is so fast so that program
could not free the memory on time.

now I use TCPserver.. as reactor model I can't figure out a way to detect the client loss connection.

do you have an example how to use tcpserver and rector both in the same service?
thanks.

**Comment by micheleselea** [comment]
I used TCPServer and Reactor in the same service but for different purpose.
I never see a Poco::Buffer leak in debug, because class allocate and deallocate buffer correctly so I do not understand why have to leak memory....there's no "time reason" about deallocation

**Comment by whidbey** [comment]
is possible the ide 's bug?
I am using code::blocks.
