### ISSUE TITLE
HTTPServerParams timeouts

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1442]
Hello, guys.
I have a question about timeouts for HTTP Server. 
I see the method setTimeout, but I'm not sure that it sets the connection timeout. It seems like receive timeout.

void setTimeout(const Poco::Timespan & timeout);
Sets the connection timeout for HTTP connections.

**Comment by micheleselea** [comment]
It's read timeout of accepted connection.
Is set in HTTPServerSession constructor

**Comment by matisszilard** [comment]
In the [HTTPClientSession](https://pocoproject.org/docs/Poco.Net.HTTPClientSession.html#21079) the `setKeepAliveTimeout` set the connection timeout for the HTTP connections. The `setTimeout` is for the request timeouts:

```c++
void setKeepAliveTimeout(
    const Poco::Timespan & timeout
);
// Sets the connection timeout for HTTP connections.

void setTimeout(
    const Poco::Timespan & timeout
);
// Sets the timeout for the HTTP session.
```

In the [HTTPServerParams](https://pocoproject.org/docs/Poco.Net.HTTPServerParams.html#21736) documentation the functions has the same description:

```c++
void setKeepAliveTimeout(
    const Poco::Timespan & timeout
);
Sets the connection timeout for HTTP connections.

void setTimeout(
    const Poco::Timespan & timeout
);
Sets the connection timeout for HTTP connections.
```
