### ISSUE TITLE
Compilation using MinGW

### ISSUE THREAD

**Issue by gitgkk** [pocoproject/poco#1444]
I'm trying to build the poco-1.7.5-all library on windows with MinGW for use with a Qt project using Msys 1.0. g++.exe (GCC) 5.3.0. I used help found on the website and some external links to help compiling with MinGW. The build fails. 

What are the external library dependency versions for each library?

src/NetworkInterface.cpp: In static member function 'static Poco::Net::NetworkInterface::Map Poco::Net::NetworkInterface
::map(bool, bool)':
src/NetworkInterface.cpp:1182:46: error: 'struct _IP_ADAPTER_ADDRESSES' has no member named 'ReceiveLinkSpeed'
     ifIt->second.impl().setRunning(pAddress->ReceiveLinkSpeed > 0 || pAddress->TransmitLinkSpeed > 0);
                                              ^
src/NetworkInterface.cpp:1182:80: error: 'struct _IP_ADAPTER_ADDRESSES' has no member named 'TransmitLinkSpeed'
     ifIt->second.impl().setRunning(pAddress->ReceiveLinkSpeed > 0 || pAddress->TransmitLinkSpeed > 0);
                                                                                ^
src/NetworkInterface.cpp:1228:33: error: 'struct _IP_ADAPTER_UNICAST_ADDRESS' has no member named 'OnLinkPrefixLength'
        prefixLength = pUniAddr->OnLinkPrefixLength;
                                 ^
make[1]: **\* [/c/POCO/poco-1.7.5-all/Net/obj/MinGW/i686/debug_static/NetworkInterface.o] Error 1
make[1]: Leaving directory `/c/POCO/poco-1.7.5-all/Net'
make: **\* [Net-libexec] Error 2

Any ideas anyone?

**Comment by bracketttc** [comment]
Those structs are part of Microsofts's IP Helper API and you should be getting them from `<iphlpapi.h>`.
Qt has smaller structs of the same name in their `qnetworkinterface_win_p.h` header. Depending on order of inclusion, Qt might be redefining the struct before you use it.

I haven't worked with Qt, so I don't know how hard it would be to not include their networking headers if you're not going to use their networking code; but that's where I'd try to start.
