### ISSUE TITLE
Conflict with check macro in Mac OS 10.12 SDK causes compiler errors

### ISSUE THREAD

**Issue by bitjeep** [pocoproject/poco#1451]
One of the function names used in NumericString.h (check) conflicts with a macro defined in AssertMacros.h in the Mac OS 10.12 SDK and causes compiler errors.  Attached is a zipped patch which fixes this.

[check_symbol_conflict.patch.zip](https://github.com/pocoproject/poco/files/528207/check_symbol_conflict.patch.zip)

**Comment by jacobsologub** [comment]
Still an issue as of `poco-1.8.1`

**Comment by aleks-f** [comment]
@obiltschnig [fixed](https://github.com/pocoproject/poco/commit/7726d024ab98a35267dae17defca29d29e477039) only in develop

**Comment by aleks-f** [comment]
[fixed](https://github.com/pocoproject/poco/commit/6fa4fda1e455bc0ddc38507041acbec28fbf89c3) in 1.8.2
