### ISSUE TITLE
HTTPAuthenticationParams Digest parsing

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1452]
Recently I found that HTTPAuthenticationParams  fail to parse "WWW-Authenticate: Digest" if we have a string like this
WWW-Authenticate: Digest nonce = "61222aff71732d14ab6319f3b69cda99", realm = "TEST"
the problem is the SPACE between nonce and =
It's not clear from RFC if the space must not be there or it does not matter, Do you think we can support here the space or can produce negative effect?

**Comment by obiltschnig** [comment]
From my understanding of RFC 2617 spaces are not allowed before and after '='. What server is giving this (malformed?) header?

**Comment by micheleselea** [comment]
I think it's not a "standard server" it's server from our customer. I was just wandering about spaces, from my understanding, I agree with you, spaces should not be there. I asked customer check his reply.
Just think if this "space resilience" can be useful to be more adaptive

**Comment by obiltschnig** [comment]
While I generally agree that being generous in what to accept is a good thing (see Postel's Law), I'd prefer to keep things as they are for the moment, as allowing spaces here could possibly break other things.
