### ISSUE TITLE
SQLite: very slow insert

### ISSUE THREAD

**Issue by alexukr** [pocoproject/poco#1455]
Hello.
The simple code inserting 9000 records consisting of 4-character strings only into newly created db takes too long to execute:

```
std::vector<std::string> test_gen_data(size_t rec_count)
{
    char record[8];
    std::vector<std::string> vec;
    vec.reserve(rec_count);

    for (int i = 0; i < rec_count; ++i)
    {
        snprintf(record, sizeof(record)/sizeof(record[0]), "%04d", i);
        vec.push_back(record);
    }
    return vec;
}

void test_create_db(char const* filepath)
{
    std::vector<std::string> vec = test_gen_data(9000);

    Poco::Data::SQLite::Connector::registerConnector();
    Poco::Data::Session session("SQLite", filepath);
    session << "CREATE TABLE MyTable (my_field TEXT)", Poco::Data::Keywords::now;
    session << "INSERT INTO MyTable (my_field) VALUES (?)",
        Poco::Data::Keywords::use(vec),
        Poco::Data::Keywords::now; // THIS COMMAND TAKES TOO LONG
}

int main()
{
    test_create_db("test.sqlite");
}
```

I run it on Windows 8.1, compiled with Visual C++ 2015 (ver. 14.0.25425.01 Update 3) with static linkage (including runtime), x64, both Debug and Release versions took too long to create this simple DB.

It took more than 10 minutes to produce ~100 KB file with 9000 records.
The process didn't consume CPU (0%) and RAM (1.5 MB commited memory). And it issued a lot of Write I/O (90 000) and Other I/O (115 000) operations, and Write I/O bytes was about 130 MB.

The Poco framework was built with the following options:

cmake . -G "Visual Studio 14 2015 Win64" -DPOCO_STATIC=ON -DPOCO_MT=ON -DENABLE_NETSSL=OFF -DENABLE_DATA=ON -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_SQLITE=ON -DENABLE_MONGODB=OFF -DENABLE_PAGECOMPILER=OFF -DENABLE_PAGECOMPILER_FILE2PAGE=OFF

The python script doing the same work on the same machine in the same directory took less than a second to create the same DB.

**Comment by obiltschnig** [comment]
At least on my 2011 MacBook Pro I cannot reproduce that (took ~7 seconds). Will try on Windows later.

**Comment by alexukr** [comment]
"took ~7 seconds"

I think you DID reproduce it on Mac as well ;)

This operation should not take so long (7 seconds is too long as well for this).

**Comment by obiltschnig** [comment]
Obviously there's a big difference between 7 seconds and 10 minutes ;-) Even if 7 seconds are still too long. But there may be a cost of abstraction imposed by the Data library. Will try to compare against direct SQLite API use also.

**Comment by obiltschnig** [comment]
On my Windows 7 virtual machine, the sample took about 30 seconds to run (with rather low CPU usage). Which is not great, but still far from 10 minutes. So I don't think that's a POCO Data issue. There's still some room for performance improvements, though.

**Comment by alexukr** [comment]
I tried what is advised here: http://stackoverflow.com/questions/1711631/improve-insert-per-second-performance-of-sqlite?rq=1

I.e. I used sqlite3 API directly to create the same test db. The very first and simple advise - using BEGIN/END TRANSACTION - solved my problem, my code starded working as fast as python code even without using bindings.

I also tried NOT to use BEGIN/END TRANSACTION and use bindings (probably, what you do in Poco implementation) - and it still worked very slow.

However if I add the following to my Poco example from my initial post:

	session << "BEGIN TRANSACTION" << Poco::Data::Keywords::now;
	session << "INSERT INTO MyTable (my_field) VALUES (?)",
		Poco::Data::Keywords::use(vec),
		Poco::Data::Keywords::now;
	session << "END TRANSACTION" << Poco::Data::Keywords::now;

it won't work faster.

Can you tell me what is wrong in this code (maybe I shouldn't use 'now' keyword somewhere) and is it possible to use BEGIN/END TRANSACTION trick with the current version of Poco?

And, of course, another question: will you embed this solution in POCO implementation so all statements using containers would result in this faster code: begin transaction; old implementation; end transaction?

Thanks.

**Comment by obiltschnig** [comment]
For me, adding 

```
session.begin();
```

before the INSERT and

```
session.end();
```

after it make a big difference - time goes down to a couple of milliseconds.
Same for "BEGIN" and "COMMIT".

**Comment by alexukr** [comment]
Yes, session.begin(); session.commit() works for me as well, thanks.

**Comment by crosscode-nl** [comment]
SQLite traditionally uses a very simple journaling mechanism. It will copy the database, and once the transaction is completed it will copy the journal back over the database. 

If you use WAL journal mode you will see it will also improve your performance. Or if you don't need crash integrity you could maybe use MEMORY. 

See the following link: https://www.sqlite.org/pragma.html#pragma_journal_mode
