### ISSUE TITLE
Leap second support

### ISSUE THREAD

**Issue by kimgr** [pocoproject/poco#1456]
A question was raised internally how well we support leap seconds (https://ics-cert.us-cert.gov/sites/default/files/documents/Best_Practices_for_Leap_Second_Event_Occurring_on_31_December_2016_S508C.pdf)

We're looking at our respective platforms to see if they use smoothing to sneak the leap second in, or if 23:59:60 will be visible to applications. We use Poco for most of our time arithmetic -- have you considered leap seconds? Is there strict validation for seconds-per-minute ranges?

Thanks!

**Comment by obiltschnig** [comment]
POCO has no special handling for leap seconds. Constructing a Poco::DateTime or Poco::LocalDateTime with seconds argument == 60 will lead to an assertion exception, as seconds are range-checked in Poco::DateTime and Poco::LocalDateTime. Leap seconds are also not considered in time interval calculations, but I guess that's the same everywhere.

**Comment by obiltschnig** [comment]
Will probably change the assertion for seconds to allow 60 as well; should have no negative consequences.

**Comment by kimgr** [comment]
Thanks, I appreciate it! I can pull that commit in as a patch for the version we use.

Yeah, considering leap seconds in calculations is probably not worth it (especially since there seems to be no way to know when they happen, arithmetically. It's all politics, as far as I can see.)
