### ISSUE TITLE
Probably invalid epoll_create() usage inside Poco/Socket.cpp

### ISSUE THREAD

**Issue by okvorb** [pocoproject/poco#1458]
Hi

I've faced to the problem with Poco::Socket::select() method that throws Poco::IOException with error code 22 (EINVAL). After debugging session I've found exact line of code where this exception happens:

File "Net/src/Socket.cpp" Line 155 (1.7.5 version):

```
		epollSize = eventLast - eventsIn;
		epollfd = epoll_create(epollSize); // Problem is here when epollSize == 0
		if (epollfd < 0)
		{
			char buf[1024];
			strerror_r(errno, buf, sizeof(buf));
			SocketImpl::error(std::string("Can't create epoll queue: ") + buf);
		}

```
According to the manual (http://man7.org/linux/man-pages/man2/epoll_create.2.html) :+1: 

       In the initial epoll_create() implementation, the size argument
       informed the kernel of the number of file descriptors that the caller
       expected to add to the epoll instance.  The kernel used this
       information as a hint for the amount of space to initially allocate
       in internal data structures describing events.  (If necessary, the
       kernel would allocate more space if the caller's usage exceeded the
       hint given in size.)  **Nowadays, this hint is no longer required** (the
       kernel dynamically sizes the required data structures without needing
       the hint), **but size must still be greater than zero**, in order to
       ensure backward compatibility when new epoll applications are run on
       older kernels.

Maybe it will be better to check size argument and always pass something greater than zero to epoll_create() ? Thanks.

P.S. There is another minor bug with  **strerror_r** function. It has different behaviour and not always changes **buf** variable but returns char* to the static string. In this case _std::string("Can't create epoll queue: ") + buf_ results in text with random garbage at the end.

**Comment by okvorb** [comment]
Unfortunately it is not enough. **epoll_create(1)** had solved epoll queue creation, but there is such a situation (i'm observe it in GDB right now) when **epoll_create** returns valid handle and **epollSize** variable still equals to zero. Look at line 182:

` rc = epoll_wait(epollfd, eventsOut, epollSize, remainingTime.totalMilliseconds());`

epoll_wait will be called with zero value in third argument, which cause EINVAL error according to manual page. After that, code on line 196 will be executed and Poco::InvalidArgument exception with code 22 generated:

`if (rc < 0) SocketImpl::error();`

I haven't  tried to pass 1 to epoll_wait() yet. I guess there is some error in logic that calculates epollSize variable.

**Comment by okvorb** [comment]
Okay. I've tried to replace epoll_wait(epollfd, eventsOut, epollSize, remainingTime.totalMilliseconds()) with 
epoll_wait(epollfd, eventsOut, 1, remainingTime.totalMilliseconds()). It worked in way that exception is eliminated, but infinite loop has stayed. Resuming aforementioned info, it's needed to handle closed socket somehow.

**Comment by obiltschnig** [comment]
epollSize can only be 0 if all sockets in readList, writeList and exceptList are invalid (the fd is POCO_INVALID_SOCKET). It may make sense to just return 0 in this case before calling epoll_create(), because there's nothing for epoll to work on.

Furthermore, I find it a bit problematic to allocate eventsIn on the stack. But then, the whole implementation is a bit lacking (especially having to create the poll again and again in every call to select()) and will be replaced with a new API in 1.8.
