### ISSUE TITLE
Poco::Data::SQLite::SQLiteStatementImpl::next() error

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1461]
I probably found a problem using SQLite Poco class and the "PRAGMA incremental_vacuum" command. On a debian jessy armv7l (kernel Linux 4.4.13-v7+) ditribution I always get a SEGMENTATION FAULT when I run the PRAGMA comment. With other PRAGMA (for example auto_vacuum or cache_size) I have no problem.
I tried on a Windows system and I can't get the error

Using directly sqlite3_exec(handle,"PRAGMA incremental_vacuum"...) works with handle taken from PocoSQLite session

the function that seems to SEGMENT is SQLiteStatementImpl::next()

I'll try on a debian not arm too, just to double check this behavior

**Comment by micheleselea** [comment]
With a standard debian PC there's no problem...I'll investigate more, anyway to test the error the very first query to do on the db created, before all other command or table created is:
PRAGMA auto_vacuum=2

**Comment by micheleselea** [comment]
The system I found problem is a Raspberry pi 3. I'll try with another Raspberry with a different system and let you know

**Comment by micheleselea** [comment]
Indeed I found the reason of "PRAGMA incremental_vacuum" segmentation fault under Linux.
The problem is the line 276
`_affectedRowCount += (*extracts.begin())->numOfRowsHandled();`
when you do incremental_vacuum statement the extracts vecotr is empty so the line above (*extracts.begin()) crash. In windows does not crash probably just for a coincidence.
we have to check !=itEnd

**Comment by obiltschnig** [comment]
Cannot reproduce this, unfortunately. When executing above PRAGMA, SQLiteStatementImpl::next() isn't even called.

**Comment by micheleselea** [comment]
On Windows you are right, but on linux After the fix of *begin() i solvedIl 05 dic 2016 8:18 PM, Günter Obiltschnig <notifications@github.com> ha scritto:Cannot reproduce this, unfortunately. When executing above PRAGMA, SQLiteStatementImpl::next() isn't even called.

**Comment by obiltschnig** [comment]
Do you have a small code snippet to reproduce this? I'd like to better understand what's happening. And, btw., which POCO version are you using?

**Comment by micheleselea** [comment]
I'm using the latest version 1.7.6 + some change to FTPSClient but nevermind for this.
I'm using SQLite 3.15.2 but was the same at least from 3.15.0 (ps. 3.15.0 had some problem with vacuum)
I found that the problem was not there with an in memory db but only with a file db.
I can reproduce the problem on a RaspBerryPi 3 with a dietpi or even with a raspbian (minibian version)

Unfortunatly I do not have the original lib, I should recompile but today I do not have enough time
anyway the theory you should reproduce it with this code
create a file DB like this

Session tmp (Poco::Data::SQLite::Connector::KEY, "dummy.db");
tmp << "PRAGMA auto_vacuum=2", now;
tmp << "PRAGMA journal_mode=WAL", now;
tmp << "CREATE TABLE test (Id INTEGER PRIMARY KEY AUTOINCREMENT,datetime BIGINT,Info TEXT)", now;
tmp << "PRAGMA incremental_vacuum", now;

and you should get in the problem if you do not check extract.begin()!=end()

**Comment by obiltschnig** [comment]
Still haven't been able to reproduce, but added check, which is good practice anyway.
