### ISSUE TITLE
MongoDB URI

### ISSUE THREAD

**Issue by jacobsologub** [pocoproject/poco#1467]
Is it possible to connect to MongoDB using the standard connection string format?

example:
`mongodb://<user>:<password>@hostname.com:<port>/database-name?ssl=true`

https://docs.mongodb.com/manual/reference/connection-string/

**Comment by fbraem** [comment]
This functionality is not available in the MongoDB module at the moment.

**Comment by jacobsologub** [comment]
@fbraem Thanks for the info. Will use mongocxx driver for now.
