### ISSUE TITLE
Poco::URIStreamOpener fails with certain URIs but libcurl succeeds.

### ISSUE THREAD

**Issue by jacobsologub** [pocoproject/poco#1471]
Poco::URIStreamOpener fails with the following uris: 

https://m.soundcloud.com/grizzlybearband/will-calls-diplo-remix
https://soundcloud.com/grizzlybearband/will-calls-diplo-remix

but succeeds using libcurl

```
std::string content = {};
auto& opener = Poco::URIStreamOpener::defaultOpener();
        
try {
    const auto is = std::shared_ptr<std::istream> { opener.open ("https://m.soundcloud.com/grizzlybearband/will-calls-diplo-remix") };
    Poco::StreamCopier::copyToString (*(is.get()), content);
}
catch (Poco::Exception& e) {
    std::cout << e.message() << std::endl;
}
```

The above results in a `HTTP Exception/Bad Request` exception but libcurl succeeds.

**Comment by jacobsologub** [comment]
This uri http://www.nytimes.com/2016/10/26/us/politics/donald-trump-interviews.html?_r=0 also fails but succeeds using libcurl.

`Too many URI redirects`

Is there a way to up the maximum number of redirects?

**Comment by obiltschnig** [comment]
Interesting. The first URI (m.soundcloud.com) works ocassionally. The second one (soundcloud.com) does not work. However, if I modify HTTPSStreamFactory.cpp to add a "User-Agent" header to the HTTP request, it works.

The NYT URI seems to fail because of too many redirects. The reason being that URIStreamOpener does not handle cookies sent by the server.

**Comment by obiltschnig** [comment]
You may want to use HTTPClientSession/HTTPSClientSession, which gives you more control over the HTTP request.

**Comment by jacobsologub** [comment]
@obiltschnig thanks for the reply.

I suspected the User-Agent header because I think some of these websites perform more stringent checking on the incoming traffic.

I had a go with HTTPClientSession/HTTPSClientSession a couple days ago but ran into some issues setting the complete URI. It seemed to break or not like urls with query parameters. I'll try again using HTTPClientSession/HTTPSClientSession and report back if I run into any issues on a separate gh issue.
