### ISSUE TITLE
Problem with linking Poco::Crypto to project

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1474]
Hello, everyone.
My application uses the poco library. I built poco library with flag POCO_STATIC by CMake and have a bunch of libraries *.lib (PocoCrypto.lib also). I've write the path to poco libraries in my project, but when I try to start my application, it crashes and gives me error about PocoCrypto.dll not found.
I do not understand why my application whants to use the *.dll file. 
Could you help me, please ?

**Comment by skident** [comment]
should I add the labriry name into Additional Dependencies of Linker (VS2012) ?
I've removed the recode PocoCrypt.lib and problem with *.dll file resolved, but I have the same problem with the openSSL library, my application wants LIBEAY32.dll

**Comment by skident** [comment]
As a note, I should say that problem appeared after adding the Poco::Crypto library into project (another Poco sublibraries work well)

**Comment by aleks-f** [comment]
a bit stale, but most likely the lib linked to is not static library but a dll stub. as for libeay, openssl libraries must also be resolved, make sure you have them in the path
