### ISSUE TITLE
Allow client sockets to be bound to a local IP address

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1475]
See https://pocoproject.org/forum/viewtopic.php?f=12&t=6774

Also related: #892, #411

**Comment by roccocorsi** [comment]
I have the same requirement for this feature.  I found this issue through a post I made on stackoverflow -

[https://stackoverflow.com/questions/47229554/how-to-bind-specific-source-ip-address-using-poconethttpsclientsession](https://stackoverflow.com/questions/47229554/how-to-bind-specific-source-ip-address-using-poconethttpsclientsession)

Is there any progress with the implementation?  Is there anything I can do to help it along?

Thank you!

**Comment by aleks-f** [comment]
> Is there any progress with the implementation?

not that I know of, @obiltschnig  ?

> Is there anything I can do to help it along?

yes, implement it and send a pull request to [develop](https://github.com/pocoproject/poco/tree/develop) branch. we'll make sure it ends up in all the right places (ie. to be released in 2.0 and be backported to 1.8.x series of releases).

**Comment by roccocorsi** [comment]
Hi Alex.  Guess you are the same Alex as on stackoverflow.  :-)

In [https://pocoproject.org/forum/viewtopic.php?f=12&t=6774](https://pocoproject.org/forum/viewtopic.php?f=12&t=6774) there is discussion that a fix was core dumping.  Is this what is holding this up or is it just lack of anyone implementing?

Thanks

**Comment by roccocorsi** [comment]
I meant Aleks, sorry about that.

**Comment by aleks-f** [comment]
> I meant Aleks, sorry about that.

not a problem, I go by both and i've been called worse names :)

> Is this what is holding this up or is it just lack of anyone implementing?

I'm not aware of any work done yet, some promises but no delivery so far ...
The core dump may refer to an old poco version or some workaround the forum poster tried and was crashing.
I know of no reason this would not work and I think it is not a large amount of work. If you are serious about doing it, please do read [CONTRIBUTING.md](https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md) and send a pull.

**Comment by roccocorsi** [comment]
Hi Aleks

I got this to work for HTTP and HTTPS.

Should I post here to get comments or should I immediately do pull request?

Thanks,

**Comment by aleks-f** [comment]
Please do pull request to develop branch - it's the easiest way to discuss a contribution. I will have limited time during the next couple of weeks, but @obiltschnig may be able to give some feedback.

**Comment by roccocorsi** [comment]
Code wise I think I am done with this feature. Your comments are very welcome.

Regression jobs work mostly, and I think the only failure reported has nothing to do with my change.  Failure is in Foundation, but I only touched network parts, so not sure what to do.  Is it normal to see some random failures in the unit test?  What is done normally, are the failed tests repeated, or are the regression tests really reliable?

Should I include an example program (also doubling as my test tool) showing how to use HTTPClientSession and HTTPSClientSession with the source IP address set or not set.  I could also include how to setup a system to have multiple interfaces and how to do the routing to allow testing this feature and use tcpdump to see that traffic is going to right interface.

**Comment by aleks-f** [comment]
> Failure is in Foundation, but I only touched network parts, so not sure what to do.

Sometimes, some timing-sensitive Foundation tests may fail. Also, sometimes travis (if that's where you are looking) is in a zombie state of mind and fails to fetch packages or execute some setup scripts.

> Should I include an example program

Yes, that would be nice.

**Comment by roccocorsi** [comment]
Made a new pull request. [2078](https://github.com/pocoproject/poco/pull/2078/files)  Please tell me if it is improved enough to be merged?  Has finally passed all the tests for the first time. It is a solid IPv4 implementation, and works well for my purposes.

For IPv6, needs more thought and work as far as I can tell. I currently need the IPv4 implementation and would have to look into IPv6 soon.  But I don't feel I know enough yet to implement correctly. Would really appreciate your thoughts on where to take it with IPv6.   Do we allow setting both IPv4 and IPv6 source address at same time and depending on the target IP (if it is IPv4 or IPv6) use the correct source IP.  Or allow settings only one of the two address family and if target IP doesn't have same address family source IP address set throw exception, etc...

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/d0312c6f6007aba47908fae250a098f6faf65053

**Comment by roccocorsi** [comment]
I am working on modifications to support IPv6 and also have the Source Address set when using the 
Proxy.  Should I do this through this issue or do I need to open another one?

**Comment by aleks-f** [comment]
open a new one

**Comment by roccocorsi** [comment]
Hmm, don't know if you should have changed the title of this issue.  Was probably a good one.  :-)  Let me explain.

Current implementation actually supports IPv6 in the basic case where source address is specified as IPv6 and target host is also on IPv6, but if you set source address as IPv4 and target is IPv6 then exception will be thrown, and same if the opposite situation with source address is set to IPv6, but target is IPv4.

So change would be to support setting an IPv4 source address and an IPv6 source address, then depending on the target host address family, using the appropriate address family (IPv4 or IPv6) when setting the source address.

This is useful when passing DNS name for host, and no address family verification is done on host address ahead of time by the application.  Adapt to whatever host we might be dealing with without application having to make decisions or DNS lookups to figure out address family ahead of time.

I guess new issue could be titled "Support dual IPv4/IPv6 address family when setting source address".  And you could set the title of this issue back to the original without the IPv4 part.

Additionally for HTTP proxy support, I now realize that I didn't make the original source address change apply to that feature, so would like to fix that, and also support this dual address family item for the HTTP proxy.

Should the HTTP proxy support be another issue?

Sorry for the long discussion.

**Comment by aleks-f** [comment]
> Should the HTTP proxy support be another issue?

yes, make it a separate issue and also separate pull request, if possible.

**Comment by roccocorsi** [comment]
I've created pull requests for the two new issues reported in #2270 and #2271.
Would appreciate code review and comments.
Thank you.

**Comment by zosrothko** [comment]
Use this button on the top right corner of your job `    Re-build PR`

**Comment by roccocorsi** [comment]
I have never seen that button.   Do I have to be logged into AppVeyor?  Is it same user/password as github?
I see that it was re-triggered.  Thank you!

**Comment by zosrothko** [comment]
@roccocorsi Yeap, you need to be logged in.. Usually, one is using the GitHub identification

**Comment by roccocorsi** [comment]
I logged into AppVeyor and Travis, but I can't see the retrigger button.  Do I need to be 'Member' or 'Owner' to be able to do that?

**Comment by roccocorsi** [comment]
@zosrothko I'm just 'Contributor' so might not have access to retrigger.  I did login to AppVeyor.

**Comment by roccocorsi** [comment]
I've finally seen the retrigger buttons after Aleks made me a 'Developer/Member'.
