### ISSUE TITLE
Poco::URI parse userinfo

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1478]
Hi, Poco::URI parse a uri like
http://user:pass@host/path/cgi?query
in the correct way. I found that if password or username contains @ like
http://user:p@ss@host/path/cgi?query
the class fail to parse userinfo because the second @ screw up the userinfo stored. I do not know if RFC says that you can't have @ in userinfo, what do you think about?

**Comment by obiltschnig** [comment]
You'll have to percent-encode the @ in the email address .

**Comment by micheleselea** [comment]
ok is not an email address, anyway I got it I need to escape the @ char, thanks
