### ISSUE TITLE
Poco::Net::TCPServer Black list IP

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1485]
Should be nice to have some feature to put a BAD IP in a black list so we can for example ignore connection from that IP for some time. I was think to the HTTPServer that is a TCP server, because you do the "black list logic" in the createRequestHandler of HTTPRequest is too late because you are already in the thread that serve connection, so a BAD (probably intentional) client can easly block your server

**Comment by micheleselea** [comment]
For example a fast way to do that is to let me extend the TCPServerDispatcher and give it to the TCPServer

**Comment by obiltschnig** [comment]
I'm thinking about having a TCPConnectionFilter interface like:

```
class TCPConnectionFilter: public Poco::RefCountedObject
{
public:
    typedef Poco::AutoPtr<TCPConnectionFilter> Ptr;

    virtual bool accept(Poco::Net::StreamSocket& socket) = 0;

protected:
    virtual ~TCPConnectionFilter();
};
```

And then have a 

```
setConnectionFilter(const TCPConnectionFilter::Ptr& pFilter);
```
method in TCPServer. HTTPServer is a subclass of TCPServer, so it would be applicable for both.
TCPServer would call the filter's accept() method immediately after `acceptConnection()`.

**Comment by micheleselea** [comment]
nice

**Comment by obiltschnig** [comment]
Parameter to accept() should probably be a `Poco::Net::SocketAddress`.

**Comment by micheleselea** [comment]
I think should be more interesting to have a Poco::Net::StreamSocket& socket parameter, so you can for example just discard connection, or make some more "complicated" stuff like reply slowly to the request or whatever you need

**Comment by obiltschnig** [comment]
Filter is called from the accept loop, so it should not do anything lengthy to not block other connections from being accepted. I don't think there's much useful for the filter to do with the socket, except for obtaining the peer address.

**Comment by micheleselea** [comment]
Yes understand about accept connection loop, I was think about more stuff you can do with a socket in a separated thread: it's just an idea, I was only think to slow down an attacker that want to exaust your connections or cpu

**Comment by obiltschnig** [comment]
Okay, see 0b0c80840862ce2db1e3c16585663573bb3fa09c

**Comment by micheleselea** [comment]
ok I'l try

**Comment by micheleselea** [comment]
ok nice it works, I'll keep in test but I think it's a good feature

**Comment by micheleselea** [comment]
If you want to know how I use it it's basically like this:

1. I have a Poco::ExpireCache that I fill with a pair (IP,counter) where count is the number of times I found something strange on connection; for example authentication error, bad request or request of unknown method
2. When the accept() method of TCPConnectionFilter is called I check the counter value of that IP and if it's grater than a threshold I put it in a "ban state": I put it in a socket vector to not close the socket immediately but to  leave the socket pending....
3.every accept call I check if it's time to close some "old" socket, so nothing blocking

those 3 steps was for bad active socket, so sockets that make bad request
We have another use case that is the "silent socket" so for example some one that call 1000 telnet application leaving a lot of pending silent socket: in this case the receive timeout give some way to escape, but you already have a thread reading for something that will never arrive. So you can use quite the same approach to increment and decrement the counter to intercept a bad number of silent connected sockets

Do you think can be other use case of "bad socket"?

**Comment by micheleselea** [comment]
On linux system the code line
#if defined(POCO_OS_FAMILY_UNIX)
						if (ss.address().family() != AddressFamily::UNIX_LOCAL)
#endif
compile with error because he does not know what is AddressFamily, probably include or using is missing

**Comment by micheleselea** [comment]
ss.address().family() return a IPAddress::Family
so I do not understand what is UNIX_LOCAL?
perhaps the if should be if isLocal() ?

**Comment by whidbey** [comment]
good feature as I have requested before.. a function to ban illgeal ips.
