### ISSUE TITLE
OSAtomicDecrement32 & OSAtomicIncrement32 deprecated in macOS 10.12

### ISSUE THREAD

**Issue by skyline75489** [pocoproject/poco#1487]
The compiler complains about this:

>'OSAtomicDecrement32' is deprecated: first deprecated in macOS 10.12 - Use
> std::atomic_fetch_sub_explicit(std::memory_order_relaxed) from \<atomic\>
> instead [-Wdeprecated-declarations]

**Comment by madeinquant** [comment]
/usr/local/include/Poco/AtomicCounter.h:255:9: error: use of undeclared identifier 'OSAtomicIncrement32' return OSAtomicIncrement32(&_counter);

encountered similar error on os x (10.12.3) , please advise how to fix the error.

**Comment by garikyes** [comment]
I had the same issue as madeinquant.  Passing -std=c++11 to g++/clang solves the problem for me.

**Comment by uniatom5rg** [comment]
if you use Cmake, Please "add set(CMAKE_CXX_STANDARD 11)" fixed issues

**Comment by ClausKlein** [comment]
To compile the poco code On branch poco-1.8.0 with clang++ under mac OS X with -std=c++98

 name -a:
`Darwin Claus-MBP.fritz.box 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64 i386 MacBookPro5,1 Darwin`

g++ --version:
`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

I need this patch: 
[AtomicCounter.patch.txt](https://github.com/pocoproject/poco/files/1327142/AtomicCounter.patch.txt)
