### ISSUE TITLE
Add data to a ZIP archive

### ISSUE THREAD

**Issue by Kvaz1r** [pocoproject/poco#1490]
If use class Compress as write in [POCO Zip User Guide](https://pocoproject.org/docs/ZipUserGuide.html) then new file rewrite old data. In documentation I found the class Add, but function [execute](https://github.com/pocoproject/poco/blob/develop/Zip/src/Add.cpp#L34) just call of method AddFile for Compress object and have an extra unused parameter.
So is it possible add data to an exist ZIP archive?

**Comment by Kvaz1r** [comment]
Any comments?

**Comment by obiltschnig** [comment]
In order to add a file to an existing Zip archive, you'll have to extract the existing Zip archive to a directory, then add the file to that directory and then re-create the Zip archive from the directory.

**Comment by Kvaz1r** [comment]
I understand, I mean currently no function "wrapper" for this. It would be convenient  as like in [this](https://nih.at/libzip/zip_file_add.html) library.
