### ISSUE TITLE
How to handle a path when using http server

### ISSUE THREAD

**Issue by lvhuat** [pocoproject/poco#1492]
Samples are all handle the root path `http://localhost:9980/ `
What should i do if i want to handle `/data` or /cities/NewYork or any else?

**Comment by micheleselea** [comment]
Take a look to HttpTimeServer.cpp sample
in TimeRequestHandlerFactory

	HTTPRequestHandler* createRequestHandler(const HTTPServerRequest& request)
	{
		if (request.getURI() == "/")
			return new TimeRequestHandler(_format);
		else
			return 0;
	}
you can have
if (request.getURI() == "/path/you/need")
