### ISSUE TITLE
Application crashes on construction RSAKey in multiple threads

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1498]
I have N threads and every of them creates the Poco::RSAKey. It worked pretty well, but I found out that in some cases my application crashes. I made a sample and I see the same behaviour as before - test application crashes (code below)
`void method()
{
	int maxLoops = 100;
	for (int i = 0; i < maxLoops; i++)
		RSAKey publicKey("public.key");
}

int main()
{
	int maxThreads = 100;
	vector<future<void>> threads;
	for (int i = 0; i < maxThreads; i++)
		threads.emplace_back(async(method));

	for (auto& tr : threads)
		tr.get();
        return 0;
}`

As you can see, I just create 100 threads and each of them 100 times creates the same RSAKey (without cycle it crashes too, but not always). 
I tried to create RSAKey from std::istream, but result is the same. 
The problem appears in method void OpenSSLInitializer::initialize() file OpenSSLInitializer.cpp

**Comment by micheleselea** [comment]
try this:

int main()
{
Poco::Net::initializeSSL();
//your stuff
Poco::Net::uninitializeSSL();
}

**Comment by skident** [comment]
Thanks a lot! It works.
