### ISSUE TITLE
Alpine 3.4 trouble with Foundation/src/Error.cpp

### ISSUE THREAD

**Issue by Dekken** [pocoproject/poco#1501]
Copying a working setup from centos 7, the following line causes a compilation failure:
poco-1.7.6/Foundation/src/Error.cpp:71:56: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(int)'
   return std::string(strerror_r(errorCode, errmsg, 256));

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/5.3.0/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-5.3.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 5.3.0' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-esp --enable-cloog-backend --enable-languages=c,c++,objc,java,fortran,ada --disable-libssp --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib
Thread model: posix
gcc version 5.3.0 (Alpine 5.3.0)

g++ -std=c++14 -DNDEBUG -O2 -fPIC -fstack-protector -Wformat -Wformat-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wall -Ipoco-1.7.6/Foundation/include -DPOCO_BUILD_HOST=localhost.localdomain -DPOCO_TARGET_OSNAME=Linux -DPOCO_TARGET_OSARCH=x86_64 -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL -DNDEBUG -o Error.o -c poco-1.7.6/Foundation/src/Error.cpp

poco-1.7.6/Foundation/src/Error.cpp: In static member function 'static std::__cxx11::string Poco::Error::getMessage(int)':
poco-1.7.6/Foundation/src/Error.cpp:71:56: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(int)'
   return std::string(strerror_r(errorCode, errmsg, 256));

Replacing the line with the "#else" line of "return std::string(strerror(errorCode));" works

**Comment by rnalrd** [comment]
Issue still exists with Alpine 3.6 (edge)

** Compiling src/Error.cpp (debug, shared)
g++  -Iinclude -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/CppUnit/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/CppUnit/WinTestRunner/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Foundation/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/XML/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/JSON/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Util/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Net/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Crypto/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/NetSSL_OpenSSL/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Data/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Data/SQLite/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Data/ODBC/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Data/MySQL/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/MongoDB/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Zip/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/PageCompiler/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/PageCompiler/File2Page/include -Wall -Wno-sign-compare -DPOCO_BUILD_HOST=df1844j -DPOCO_TARGET_OSNAME=Linux -DPOCO_TARGET_OSARCH=x86_64  -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -c src/Error.cpp -o /home/larena/aports/testing/poco/src/poco-1.7.7-all/Foundation/obj/Linux/x86_64/debug_shared/Error.o
src/Error.cpp: In static member function 'static std::__cxx11::string Poco::Error::getMessage(int)':
src/Error.cpp:71:56: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(int)'
   return std::string(strerror_r(errorCode, errmsg, 256));


(edge-x86_64) ~/aports/testing/poco$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.3.0/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-6.3.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 6.3.0' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-cloog-backend --enable-languages=c,c++,objc,java,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
gcc version 6.3.0 (Alpine 6.3.0)

**Comment by rnalrd** [comment]
The problem is that is using the GNU version of strerror_r. To make it uses the POSIX version, as the comment in source say, you have to do:

make CXXFLAGS="$CXXFLAGS -U_GNU_SOURCE -D_XOPEN_SOURCE=600" || return 1

However I have another compiler error in Environment_UNIX.cpp which I'm looking at.

**Comment by obiltschnig** [comment]
Do you have a fix for the Environment_UNIX.cpp issue?
