### ISSUE TITLE
Redis: Select db.

### ISSUE THREAD

**Issue by JiekeZhu** [pocoproject/poco#1504]
static Command select(const std::string& dbid);
		/// Select the DB with having the specified zero - based numeric index.

Command Command::select(const std::string& dbid)
{
	Command cmd("SELECT");

	cmd << dbid;

	return cmd;
}

Br.

**Comment by brandery** [comment]
so this redis db selection enhancement hasn't been accepted? why?

**Comment by anklean** [comment]
try this code:  
 Poco::Redis::Array cmd;
  Poco::Redis::BulkString sdb=db;
  cmd.add("SELECT").add(sdb).end(); 
_redis.execute<std::string>(cmd);
