### ISSUE TITLE
Building static release mt x64 fails with VC2010 (Win7)

### ISSUE THREAD

**Issue by AndreasMartin72** [pocoproject/poco#1506]
First I tried to build poco using build_vs100.cmd, but that failed very quickly (even that cppunitd.lib exists):
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++ Building [WinTestRunner_vs100.vcxproj]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Microsoft (R) Visual Studio Version 10.0.40219.1.
Copyright (C) Microsoft Corp. All rights reserved.
1>------ Build started: Project: WinTestRunner, Configuration: debug_shared Win3
2 ------
1>Build started 30.11.2016 21:13:25.
1>InitializeBuildStatus:
1>  Touching "obj\debug_shared\WinTestRunner.unsuccessfulbuild".
1>ClCompile:
1>  All outputs are up-to-date.
1>ResourceCompile:
1>  All outputs are up-to-date.
1>ManifestResourceCompile:
1>  All outputs are up-to-date.
1>LINK : fatal error LNK1104: cannot open file 'cppunitd.lib'
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.05
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX  BUILD FAILED. EXITING. XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

So I switched to buildwin.cmd with arguments:
`buildwin 100 build static_mt release x64 nosamples notests msbuild`
Stopped again at module "Foundation", since TARGET_MACHINE is not properly set. Fixed that, got the next errors for MySQL and PostgreSQL. I don't have these modules, I just need SQLite3, so I deleted the paths Data\MySQL and Data\PostgreSQL and proceeded.
Next error on Redis_x64_vs100:
`fatal error C1083: Cannot open source file: 'include\Poco\Redis\RedisEventArgs.cpp': No such file or directory`
Here the extension is wrong: I replaced the file with "RedisEventArgs.h". 
With these changes the build finally succeeded.
What about making MySQL and PostgreSQL optional?

Regards, Andreas

**Comment by FlemishLion1302** [comment]
Andreas, check https://github.com/pocoproject/poco/issues/1292 - even though it is for VS2015.

**Comment by AndreasMartin72** [comment]
This doesn't work with my MSVC installation (I've tried v110 and v120 also). It lacks the particular toolsets:
```C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(514,5): error MSB8008: Das angegebene Plattformtoolset (v140) ist nicht installiert oder ungültig. Stellen Sie sicher, dass ein unterstützter PlatformToolset-Wert ausgewählt wurde. [d:\git\poco\CppUnitCppUnit_x64_vs140.vcxproj]```

Regards, Andreas
