### ISSUE TITLE
ODBC and Unicode

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1512]
Hello, everyone!

I use Poco::Data::ODBC for working with MS SQL database (collation sql_latin1_general_cp1_ci_as).

I want to fetch data from field nvarchar(64) which contains unicode symbols and trying put the data into variable std::wstring.

I have been debuging so deep but can't find out where the problem is. In some moment the data in the Preparator appear and contain only 31 symbols, but I wait for the 40 symbols. 

Can somebody explain me this behaviour? Does problem really exist or it is something with my code?

**Comment by skident** [comment]
Update: found out that data received from SQL already with wrong length and content.
`void ODBCStatementImpl::makeStep()
{
	_extractors[currentDataSet()]->reset();
	_nextResponse = SQLFetch(_stmt);  // Not all data received!!!
....
`

SQLFetch is the function from C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include\sql.h

**Comment by obiltschnig** [comment]
Could it be this is related to #1436? Fix is in 1.7.7 and develop branch.

**Comment by skident** [comment]
It helped, thank you!
