### ISSUE TITLE
MongoDB: add support for authentication.

### ISSUE THREAD

**Issue by alexey-milovidov** [pocoproject/poco#1513]
I could not find the way to specify user and password for `MongoDB::Connection`.

**Comment by fbraem** [comment]
For the moment there are no methods provided in the POCO MongoDB classes, but authentication can be done using some commands. You can find a sample here: https://pocoproject.org/forum/viewtopic.php?f=10&t=6326&p=11426&hilit=mongodb+auth#p11485

**Comment by alexey-milovidov** [comment]
Nice, thanks! I will use it.

**Comment by obiltschnig** [comment]
Have a need for this in upcoming project, so I implemented both MONGODB-CR (default pre 3.0) and SCRAM-SHA-1 (default from 3.0). 

Kudos to whoever wrote this useful explanation of the SCRAM-SHA-1 authentication flow: http://www.alienfactory.co.uk/articles/mongodb-scramsha1-over-sasl
