### ISSUE TITLE
HTTPRequestHandler - It is not working for second request with custom body

### ISSUE THREAD

**Issue by baszczewski** [pocoproject/poco#1517]
Hello. I just discovered the strange behavior of a simple http server built with _Poco::Util::ServerApplication_ + _Poco::Net::HTTPRequestHandlerFactory_ + _Poco::Net::HTTPRequestHandler_.

I saw this issue on extreamlly simple _HTTPRequestHandler_ instance which resturns only text (and do not process any request data).

```c++
void ErrorRequestHandler::handleRequest(Poco::Net::HTTPServerRequest& request, Poco::Net::HTTPServerResponse& response)
{
    // my answer
    response.sendBuffer(m_message.c_str(), m_message.length());
}

```

So I made to my server few requests with RESTer plugin (Firefox).

**Request 1**
___Method___:
POST 
___Headers___:
Connection: Keep-Alive
Content-Length: 12
Date: Sat, 10 Dec 2016 09:54:22 GMT
___My body___:
cars%5B%5D=1&user%5Bname%5D=marcin
___Output___:
Content of my m_message. Everyting is ok. 

**Request 2**
___Method___:
POST 
___My body___:
cars%5B%5D=1&user%5Bname%5D=marcin
___Output___:
Just "Connection: Close" which is not content of my message. 

The worst thing here is that if I want to close app after first request (not second), Poco will crash app. The problem is inside body parsing somewhere inside Poco implementation. For example with body:
```
user%5Bname%5D=marcin
```
or 
```
cars%5B%5D=1
```
problem does not occur!

PS
Strange thing here is that everything works correctly (even with my body from request 1), if I parse request stream with _HTMLForm_ before return response:
```c++
Poco::Net::HTMLForm form(request, request.stream());
```

**Comment by obiltschnig** [comment]
You are responsible for consuming all request data in your request handler before returning. Otherwise, request data will remain in socket buffer and prevent the next request from being processed correctly. In any case, the HTTPServer framework should not crash, but it may throw an exception when it receives bad request data.

**Comment by baszczewski** [comment]
@obiltschnig 
Thank you for your advice. But how consume this request if I do not need to parse the body for this request?

What about our samples (for example _HTTPTimeServer_), which don't consumes this request?
```c++
void handleRequest(HTTPServerRequest& request, HTTPServerResponse& response)
{
	Application& app = Application::instance();
	app.logger().information("Request from " + request.clientAddress().toString());

	Timestamp now;
	std::string dt(DateTimeFormatter::format(now, _format));

	response.setChunkedTransferEncoding(true);
	response.setContentType("text/html");

	std::ostream& ostr = response.send();
	ostr << "<html><head><title>HTTPTimeServer powered by POCO C++ Libraries</title>";
	ostr << "<meta http-equiv=\"refresh\" content=\"1\"></head>";
	ostr << "<body><p style=\"text-align: center; font-size: 48px;\">";
	ostr << dt;
	ostr << "</p></body></html>";
}
```
They can result invalid request and undefined app behaviour bacuse of "special" request body. Isn't it? Maybe we need some additional information inside documentation?

**Comment by baszczewski** [comment]
PS
Unfortunately server (Poco :: Net :: HTTPServer) will crash here if I will stop him before the app close with __false__ attribute (server->stopAll (false);).

**Comment by Dian8** [comment]
I also have this problem. 

We create handlers in HTTPRequestHandlerFactory::createRequestHandler()  - but how are they freed?

**Comment by aleks-f** [comment]
> We create handlers in HTTPRequestHandlerFactory::createRequestHandler() - but how are they freed?

they go into a [smart pointer](https://github.com/pocoproject/poco/blob/poco-1.9.0/Net/src/HTTPServerConnection.cpp#L79-L83)

**Comment by Dian8** [comment]
> > We create handlers in HTTPRequestHandlerFactory::createRequestHandler() - but how are they freed?
> 
> they go into a [smart pointer](https://github.com/pocoproject/poco/blob/poco-1.9.0/Net/src/HTTPServerConnection.cpp#L79-L83)

Thank you! Which is a proper way to reuse handles?
