### ISSUE TITLE
bug in JSON ParseHandler.cpp (empty keys should be valid)

### ISSUE THREAD

**Issue by vin-d** [pocoproject/poco#1521]
Hi,
I'm using Poco 1.7.5 JSON module but from reading the code 1.7.6 has the same problem.
I have to parse a JSON string and have the following error with JSON files that have an empty key [even if it is still valid to have an empty string in JSON ](http://json.org/) (**string is a sequence of zero or more Unicode characters**) : 

example : 
```
{"example":
  {"":""}
}
```
and this code with the string describe above.
```
Poco::JSON::Parse p;
p.parse(myJsonString);
```
throws
because of 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Assertion violation: !_key.empty() [in file ["src/ParseHandler.cpp", line 136](https://github.com/pocoproject/poco/blob/develop/JSON/src/ParseHandler.cpp#L136)]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

This assert in line 136 shouldn't be there.
what do you think about this ?

Thank you.

**Comment by obiltschnig** [comment]
Looks like, in `ParseHandler.cpp`, the two `poco_assert_dbg()` statements in `startObject()` and `startArray()` must be removed, as they make no sense since a key can in fact be an empty string. 
#3470 only removed the `poco_assert_dbg()` in `setValue()`.
