### ISSUE TITLE
Cross-compiling for 32 bit on 64 bit Linux fails during linking (with workaround)

### ISSUE THREAD

**Issue by leomeyer** [pocoproject/poco#1525]
I want to cross-compile POCO for i386 (32 bit) on Linux Ubuntu Server 14.04 (same as the Travis CI environment). I could not find better instructions to setup a 32 bit cross-compiling environment, so what I did is copy the build/config/Linux file to build/config/Linux_i386 and make the following changes:
CFLAGS = -m32
CXXFLAGS = -m32 -Wall -Wno-sign-compare
LINKFLAGS = -m32

Environment variables: POCO_TARGET_OSARCH="i386", ARCHFLAGS="-arch i386"
Additionally installed packages: gcc-multilib, g++-multilib, libc6-dev-i386 (implicitly installed)

Compiling the object files with g++ 4.8 (OS default) worked, however linking failed with error "file class ELFCLASS32 incompatible with ELFCLASS64". Closer inspection revealed that the -m32 flag did not get passed to g++ at the linking stage.

I tried to add -m32 to the other linking options STATICOPT_LINK, SHAREDOPT_LINK etc. but this had no effect.

In the end I added the -m32 flag to the SYSLIBS variable and this got finally passed to g++ and all libraries were linked correctly.

IMO the LINKFLAGS should be passed to g++ during linking (using SYSLIBS doesn't seem quite correct for passing additional linker flags).

If I'm doing this wrong please let me know!

Thanks and regards, Leo

**Comment by zosrothko** [comment]
the file build/rules/global computes all flags used by other scripts and specially
```
#
# Compose compiler flags
#
COMMONFLAGS = -DPOCO_BUILD_HOST=$(HOSTNAME) -DPOCO_TARGET_OSNAME=$(OSNAME) -DPOCO_TARGET_OSARCH=$(OSARCH) $(POCO_FLAGS)
CFLAGS     += $(COMMONFLAGS) $(SYSFLAGS)
CXXFLAGS   += $(COMMONFLAGS) $(SYSFLAGS)
LINKFLAGS  += $(COMMONFLAGS) $(SYSFLAGS)

ifeq ($(OSARCH_64BITS),1)
CFLAGS     += $(CFLAGS64)
CXXFLAGS   += $(CXXFLAGS64)
LIBFLAGS   += $(LIBFLAGS64)
SHLIBFLAGS += $(SHLIBFLAGS64)
DYLIBFLAGS += $(DYLIBFLAGS64)
LINKFLAGS  += $(LINKFLAGS64)
else
CFLAGS     += $(CFLAGS32)
CXXFLAGS   += $(CXXFLAGS32)
LIBFLAGS   += $(LIBFLAGS32)
SHLIBFLAGS += $(SHLIBFLAGS32)
DYLIBFLAGS += $(DYLIBFLAGS32)
LINKFLAGS  += $(LINKFLAGS32)
endif
```

**Comment by leomeyer** [comment]
Sorry, but I'm not getting it. How should I use this file to make a proper 32 bit build then?

Also, if I set LINKFLAGS in the config and the global file only adds to it, then how come the linker still doesn't see the flag?

**Comment by imalyavskiy** [comment]
Nice talk!
