### ISSUE TITLE
Would Poco support mbed TLS?

### ISSUE THREAD

**Issue by davidshen84** [pocoproject/poco#1528]
[mbed TLS](https://tls.mbed.org/) is designed for embedded device. It would be better for mobile device. Could Poco support it?

**Comment by obiltschnig** [comment]
Theoretically, yes. Practically, one would have to implement a library similar to NetSSL_OpenSSL or NetSSL_Win, but using the mbed TLS APIs.

**Comment by lmussier** [comment]
Hi,

Sorry to unbury very old issue but is there any one going this path nowadays (I don't see anything about mbedtls in poco)?
Our project is looking for this kind of feature, a good multipurpose library (POCO) with mbedtls support (!POCO).

Thanks

**Comment by CryptoManiac** [comment]
Up?

**Comment by obiltschnig** [comment]
No plans at the moment (core team is busy with other projects), but contributions would be accepted.
