### ISSUE TITLE
How to get 3des cbc cipher key

### ISSUE THREAD

**Issue by skident** [pocoproject/poco#1530]
Hi, guys.
I want to generate a cipher key 3des cbc from class Poco::Crypto::CipherKey. Which name should I transmit into constructor for getting key?

I know that names are provided by openssl library but I can't find the whole list of available names. For example I use next names for get aes keys:
"aes-128-cbc"
"aes-128-cfb"
"aes-128-ofb"
"aes-256-cbc"
"aes-256-cfb"
"aes-256-ofb"

And another question about Crypto Provider. Which kind of Crypto Provider is used in Poco::Crypto for Windows OS ?

**Comment by obiltschnig** [comment]
Try the output of the `openssl ciphers` command.
On Windows, NetSSL_Win uses SChannel with the default provider.
