### ISSUE TITLE
Upgrade bundled zlib to 1.2.11

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1534]
Released January 15, 2017

Version 1.2.11 has these key improvements over 1.2.10:
- Fix deflate stored bug when pulling last block from window
- Permit immediate deflateParams changes before any deflate input
- Due to the bug fixes, any installations of 1.2.9 or 1.2.10 should be immediately replaced with 1.2.11.

Version 1.2.10 has these key improvements over 1.2.9:
- Fix bug in deflate_stored() for zero-length input
- Fix bug in gzwrite.c that produced corrupt gzip files

Version 1.2.9 has these key improvements over 1.2.8:
- Improve compress() and uncompress() to support large lengths
- Allow building zlib outside of the source directory
- Fix bug when level 0 used with Z_HUFFMAN or Z_RLE
- Fix bugs in creating a very large gzip header
- Add uncompress2() function, which returns the input size used
- Dramatically speed up deflation for level 0 (storing)
- Add gzfread() and gzfwrite(), duplicating the interfaces of fread() and fwrite()
- Add crc32_z() and adler32_z() functions with size_t lengths
- Many portability improvements

**Comment by mkrivos** [comment]
Version 1.2.10 has these key improvements over 1.2.9:

    Fix bug in deflate_stored() for zero-length input
    Fix bug in gzwrite.c that produced corrupt gzip files

**Comment by mkrivos** [comment]
I will send a patch

**Comment by obiltschnig** [comment]
Maybe we should wait a couple of days for 1.2.11 now ;-)

**Comment by obiltschnig** [comment]
... and we now have 1.2.11

**Comment by mkrivos** [comment]
Yes, I will ...

**Comment by obiltschnig** [comment]
already done

**Comment by mkrivos** [comment]
Hmm, I was too slow ;-)
