### ISSUE TITLE
Implement MailMessage::decode

### ISSUE THREAD

**Issue by rillig** [pocoproject/poco#1543]
There is already `MailMessage::encodeWord`, but the corresponding `decode` is missing. This makes it difficult to use this library efficiently and leads to many wrong implementations, since this subject is not trivial to implement.

See http://stackoverflow.com/questions/41422934/c-decode-e-mails-subject

**Comment by aleks-f** [comment]
Done, mostly - RFC2047 is not a trivial spec to implement.
