### ISSUE TITLE
Compile error in Environment_UNIX.cpp under Alpine Linux (busybox/musl)

### ISSUE THREAD

**Issue by rnalrd** [pocoproject/poco#1544]
./configure --config=Linux --prefix=/usr --minimal --shared

make CXXFLAGS="$CXXFLAGS -U_GNU_SOURCE -D_XOPEN_SOURCE=600" || return 1

** Compiling src/EventChannel.cpp (debug, shared)
g++  -Iinclude -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/CppUnit/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/CppUnit/WinTestRunner/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Foundation/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/XML/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/JSON/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Util/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Net/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Crypto/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/NetSSL_OpenSSL/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Data/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Data/SQLite/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Data/ODBC/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Data/MySQL/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/MongoDB/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/Zip/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/PageCompiler/include -I/home/larena/aports/testing/poco/src/poco-1.7.7-all/PageCompiler/File2Page/include -Os -fomit-frame-pointer -U_GNU_SOURCE -D_XOPEN_SOURCE=600 -g -D_DEBUG -fPIC -c src/EventChannel.cpp -o /home/larena/aports/testing/poco/src/poco-1.7.7-all/Foundation/obj/Linux/x86_64/debug_shared/EventChannel.o
In file included from src/Environment.cpp:28:0:
src/Environment_UNIX.cpp: In static member function 'static void Poco::EnvironmentImpl::nodeIdImpl(Poco::UInt8 (&)[6])':
src/Environment_UNIX.cpp:235:35: error: invalid application of 'sizeof' to incomplete type 'Poco::EnvironmentImpl::nodeIdImpl(Poco::UInt8 (&)[6])::ifreq'
  int len = 100*sizeof(struct ifreq);

src/Environment_UNIX.cpp:236:16: error: aggregate 'Poco::EnvironmentImpl::nodeIdImpl(Poco::UInt8 (&)[6])::ifconf ifc' has incomplete type and cannot be defined
  struct ifconf ifc;

src/Environment_UNIX.cpp:258:32: error: invalid application of 'sizeof' to incomplete type 'Poco::EnvironmentImpl::nodeIdImpl(Poco::UInt8 (&)[6])::ifreq'
   len += 10*sizeof(struct ifreq);

src/Environment_UNIX.cpp:267:77: error: invalid use of incomplete type 'const struct Poco::EnvironmentImpl::nodeIdImpl(Poco::UInt8 (&)[6])::ifreq'
    const struct sockaddr* sa = reinterpret_cast<const struct sockaddr*>(&ifr->ifr_hwaddr);

src/Environment_UNIX.cpp:235:30: note: forward declaration of 'struct Poco::EnvironmentImpl::nodeIdImpl(Poco::UInt8 (&)[6])::ifreq'
  int len = 100*sizeof(struct ifreq);

src/Environment_UNIX.cpp:274:29: error: invalid application of 'sizeof' to incomplete type 'Poco::EnvironmentImpl::nodeIdImpl(Poco::UInt8 (&)[6])::ifreq'
   ptr += sizeof(struct ifreq);

make[1]: *** [/home/larena/aports/testing/poco/src/poco-1.7.7-all/build/rules/compile:54: /home/larena/aports/testing/poco/src/poco-1.7.7-all/Foundation/obj/Linux/x86_64/debug_shared/Environment.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/larena/aports/testing/poco/src/poco-1.7.7-all/Foundation'
make: *** [Makefile:131: Foundation-libexec] Error 2

(edge-x86_64) ~/aports/testing/poco$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.3.0/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-6.3.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 6.3.0' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-cloog-backend --enable-languages=c,c++,objc,java,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
gcc version 6.3.0 (Alpine 6.3.0)

**Comment by obiltschnig** [comment]
Seems there's no easy fix for this; it's a musl specific issue with kernel/userspace headers.

Similar issues: 
  - https://github.com/sam-github/libnet/issues/52
  - https://github.com/OLSR/olsrd/issues/6

Also: http://wiki.musl-libc.org/wiki/FAQ#Q:_why_am_i_getting_.22error:_redefinition_of_struct_ethhdr.2Ftcphdr.2Fetc.22_.3F

**Comment by rnalrd** [comment]
My C knowledge is very limited, however it doesn't appear to me a musl issue, rather a code issue in your library. Musl tends to be very correct (sometimes annoyingly :) and generally when code is patched to compile against musl, it improves.

**Comment by obiltschnig** [comment]
I had no issues with musl-based recent OpenWRT.

Tested now with Alpine 3.5.1 and at least Foundation built fine. There's an issue in Poco::Net::NetworkInterface, which I have fixed for now with a workaround due to the missing <linux/if_packet.h> header (there's a new Alpine build config).

I suggest someone who cares about this enough should submit a pull request with a proper fix.

I already have way too many platforms to take care of and I'm not too keen about yet another platform breaking stuff in order to force me to do things "right" (and thereby possibly breaking other platforms...).

**Comment by obiltschnig** [comment]
Oh, noticed that there's a linux-headers package that brings the missing <linux/*.h> headers. Could have saved me some work :/

**Comment by rnalrd** [comment]
Removing "-U_GNU_SOURCE" and "-D_XOPEN_SOURCE=600" and using the patch from [OpenWRT](https://github.com/openwrt/packages/blob/master/libs/poco/patches/200-strerror.patch) this is error disappear and it does compile.

I noticed that it builds with -O2 while Alpine uses -Os. So it doesn't inherit build environment $CXXFLAGS. Currently working on that.

Thanks!
