### ISSUE TITLE
Merge partition space information methods from develop

### ISSUE THREAD

**Issue by TcT2k** [pocoproject/poco#1545]
Please merge the partition space information functions `File::totalSpace()`, `File::usableSpace()` and `File::freeSpace()` from develop to 1.8

**Comment by obiltschnig** [comment]
I will very probably drop the current 1.8 branch and use develop as base for next release.

**Comment by TcT2k** [comment]
Sound like a good idea. Thank you

**Comment by TcT2k** [comment]
As this has not been included 1.8 it would be great if it could be included in an upcoming release.
