### ISSUE TITLE
Enable bitcode for iPhone build config

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1546]
Change `OSFLAGS` to include `-fembed-bitcode`:
`OSFLAGS                ?= -arch $(POCO_TARGET_OSARCH) -isysroot $(IPHONE_SDK_BASE) $(THUMB) -miphoneos-version-min=$(IPHONE_SDK_VERSION_MIN) -fembed-bitcode
`

**Comment by mahboud** [comment]
How do you get around this error:  
`ld: -bind_at_load and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
