### ISSUE TITLE
Base64Decoder invalid result

### ISSUE THREAD

**Issue by baszczewski** [pocoproject/poco#1547]
My encoded text:
```c++
std::string payloadPart = "eyJpZCI6NDUsInJvbGVzIjpbImxvZ2luIiwiYWRtaW4iXX0";
```
you can check it here: https://www.base64decode.org/

and here is sample with Poco:
```c++
std::string payloadData;
std::istringstream payloadIstr(payloadPart);
Poco::Base64Decoder payloadDecoder(payloadIstr);
payloadDecoder >> payloadData;
```
and my result (content of payloadData) is INVALID:
```json
{"id":45,"roles":["login","admin"
```
Here should be correct JSON! But last chars is missing...

**Comment by obiltschnig** [comment]
This is not an issue with Base64Decoder. When you read a std::string with the stream extraction operator `>>`, the string will only be read up to the first whitespace. Use some other means to read the string from the stream, e.g. `Poco::StreamCopier::copyToString()`.

**Comment by baszczewski** [comment]
@obiltschnig 
Thank you for your advice. But this not help at all.
```c++
Poco::StreamCopier::copyToString(payloadDecoder, payloadData);
```
result empty string. Other usage:
```c++
Poco::StreamCopier::copyToString(payloadDecoder, payloadData, 1);
```
same string with missing characters. 

Before I write about this issue, I also check other usage variant found inside Poco sources:
```c++
static const int eof = std::char_traits<char>::eof();
int ch = payloadDecoder.get();
while (ch != eof)
{
  payloadData += (char) ch;
  ch = payloadDecoder.get();
}
```
but this also return invalid text:
```json
{"id":45,"roles":["login","admin"
```

**Comment by obiltschnig** [comment]
Your Base64 data is invalid. It's missing a `=` padding character at the end. Correct:

    std::string payloadPart = "eyJpZCI6NDUsInJvbGVzIjpbImxvZ2luIiwiYWRtaW4iXX0=";

**Comment by baszczewski** [comment]
@obiltschnig 
Yes. Thats right. Thank you for your help. Maybe we need support for multiple base64 variants in future Poco versions?
https://en.m.wikipedia.org/wiki/Base64#Variants_summary_table

**Comment by jimmibond** [comment]
you can check the result here [Base64 Decode](https://codebeautify.org/base64-decode)
