### ISSUE TITLE
Poco::Dynamic::Var isArray() returns false for arrays.

### ISSUE THREAD

**Issue by gmax79** [pocoproject/poco#1548]
json: 
{
    "listen": [
      "127.0.0.1:55000",
      "127.0.0.1:56000"
    ]
}

code:
 
JSON::Parser p;
Dynamic::Var root = p.parse(input);

JSON::Query q(root);
Dynamic::Var listen = q.find("listen");

listen.isEmpty() // false - ok
listen.isArray()  // false - ?

I found this code in Array.h
template <>
class VarHolderImpl<JSON::Array::Ptr>: public VarHolder
{
...
  bool isArray() const
  {
    return false;   // maybe true ?
  }
};

in VarHolder.cpp
inline bool VarHolder::isArray() const
{
	return true;  // maybe false ?
}

**Comment by obiltschnig** [comment]
The result is correct, even though it may be a bit misleading. The result of q.find("listen") contains a JSON::Array object, not a Poco::Dynamic::Array (which would support operator []), therefore isArray() correctly returns false.

**Comment by gmax79** [comment]
Thanks for the answer.
In documentation q.find (JSON::Query)  returns Dynamic::Var. How it convert to JSON::Array ?
Please write a sample of how to read the parameter listen.
possible variants: listen: "value"  or listen: [  "value1", "value2" ]

**Comment by obiltschnig** [comment]
Warning: not tested

    JSON::Parser p;
    Dynamic::Var root = p.parse(input);

    JSON::Query q(root);
    Dynamic::Var listen = q.find("listen");

    if (!listen.isEmpty())
    {
        Poco::JSON::Array::Ptr pArr = listen.extract<Poco::JSON::Array::Ptr>();
        for (std::size_t i = 0; i < pArr->size(); i++)
        {
            var value = pArr->get(i);
            // ...
        }
    }

**Comment by gmax79** [comment]
Vielen Dank!
