### ISSUE TITLE
Poco Json Serialization Capability 

### ISSUE THREAD

**Issue by sisyphus79** [pocoproject/poco#1550]
Hi all, I currently use  library  avro to serialize my data from json to binary before sending to Kinesis streamer. Does Poco provides its own serialization library to do the same work and remove the dependency with additional libraries?
To be more specific actually I have both a json file and a data struct. The json file is needed to validate schema and then we fill the structure with data and serialize them.

Sending over part of the code to have look on what  I do and comment if you wish:

`//validate schema
ifstream in("myFile.json");
avro::ValidSchema mySchema;
avro::compileJsonSchema(in, mySchema);

//create input file stream
ifstream ifs("myFile.json");
string json((istreambuf_iterator(ifs)), (istreambuf_iterator()));

//create writer
avro::DataFileWriter writer("dataFile", mySchema, syncInterval, Codec::DEFLATE_CODEC);
writer.write(*_data);
writer.flush();

vector buffer;
ifstream dataFile("dataFile", ios_base::in | ios_base::binary);
unsigned char ch = dataFile.get();
while (dataFile.good()) {
buffer.push_back(ch);
}`

and then send to Kinesis streamer. 
Wherever I searched I didn't find any relevant example.

Thanks in advance.

**Comment by fbraem** [comment]
POCO JSON has a PrintHandler class to serialize JSON, but there is no schema validator ...

**Comment by abdessattar** [comment]
Hello, 
PrintHandler is avalible only for the serialiZation Json.
We cannot use it to deserialization JSON  ?
Thanks in advance,

**Comment by fbraem** [comment]
Use Poco::JSON::Parser to deserialize JSON

**Comment by abdessattar** [comment]
would you please show me an example of serialization and deserialization JSON.
Thank you in avance,

**Comment by fbraem** [comment]
Have you looked at the [sample code](https://github.com/fbraem/poco/blob/develop/JSON/samples/Benchmark/src/Benchmark.cpp)  ? and the [testing code](https://github.com/fbraem/poco/blob/develop/JSON/testsuite/src/JSONTest.cpp) ?

**Comment by abdessattar** [comment]
no I will do it.

**Comment by abdessattar** [comment]
Hello,
Itried to build the sample code but I didn't get a good result , would do you please explain me hwo can I add a Poco_base environment variable?

Thank you in advance,

**Comment by abdessattar** [comment]
Hello sir,
I try to compile your example but it was crushed?
I don't know the reason.
Really, I need a help
Thank you in  advance,

**Comment by fbraem** [comment]
Did you read [Getting Started With The POCO C++ Libraries](https://pocoproject.org/docs/00200-GettingStarted.html)? And maybe it's better to ask your questions on the [POCO forum](https://pocoproject.org/forum).

**Comment by abdessattar** [comment]
Thank you very much

**Comment by abdessattar** [comment]
Hello again,
It is possible to integrate this repository to a project done with 2005?
Thank you in advance,
Best regards,

**Comment by aleks-f** [comment]
2005 was 12 years ago, so we do not support it. the oldest VS version officially supported (although not for long) is 2010
