### ISSUE TITLE
Poco::URI, it will be more convenient if getQueryParameters(or another) can return a std::map<std::string, std::string>.

### ISSUE THREAD

**Issue by JiekeZhu** [pocoproject/poco#1556]
Hi there,
When I use Poco::URI to parse the url from a request and take the query parameters, I find it's a vector of pair. I think it will be more convenient if getQueryParameters(or another) can return a **std::map<std::string, std::string>**.
I will add a  method to my local copy. 👍 
BR,
Jieke

**Comment by obiltschnig** [comment]
There is no guarantee that query parameter names are unique, e.g. `field1=value1&field1=value2` would be valid. Furthermore, we'd like to preserve the order of query parameters. Therefore the vector.

**Comment by JiekeZhu** [comment]
Got it. Thanks.

**Comment by ngjermundshaug** [comment]
Totally agree with @JiekeZhu - having a map would be **way** more convenient - and this is more or less the de-facto standard in other programming languages like C# and Java (either a map or a GetParameterValue() method).

I suggest keeping todays method which will cover those edge cases (field1=value1&field1=value2) - while also providing a new method that returns a std::map<std::string, std::string>
