### ISSUE TITLE
SQLite 3.16.2

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1558]
I'm using 3.16.2 in Pocolib 1.7.6 and 1.7.7 without problem, I think it's a stable version and has some optimizations

**Comment by mkrivos** [comment]
sqlite & zlib updates are here: https://github.com/pocoproject/poco/pull/1535

**Comment by micheleselea** [comment]
ok SQLite are good, I think l'll take even zlib update

**Comment by micheleselea** [comment]
I checked Zlib but there's not a lot of changes from current zlib version present in pocolibs. I read changelog and most of the changes are in gz-files that are not present in pocoproject....Am I wrong?
