### ISSUE TITLE
Compilation issues with Net module in Solaris 10

### ISSUE THREAD

**Issue by ashok012** [pocoproject/poco#1564]
Facing issues with compilation of POCO libraries in Solaris 10 environment. Getting following error:

src/NetworkInterface.cpp:1346:21: error: ifaddrs.h: No such file or directory

Found some references mentioning that, this module added in Solaris 11. But it is not clear how to handle this in Solaris 10 for POCO libraries.

**Comment by Anaga** [comment]
I also can't compile on SonOS 9, and on SunOS10.

**Comment by aleks-f** [comment]
yeah, sorry guys, solaris is not exactly at the top of our list. we may get to it, but no timeframe at this time
