### ISSUE TITLE
compile error in src/Event_POSIX.cpp under RedHat 4 (Nahant Update 7)

### ISSUE THREAD

**Issue by skydeepsky** [pocoproject/poco#1568]
I download poco-1.7.7-all from [here](https://pocoproject.org/releases/poco-1.7.7/poco-1.7.7-all.tar.gz),and then upload to my fresh install RedHat 4(U7) x86_64 ,when I compile ,it aborted with the follow error info:
> In file included from src/Event.cpp:25:0:
src/Event_POSIX.cpp: In constructor 'Poco::EventImpl::EventImpl(bool)':
src/Event_POSIX.cpp:72:54: error: 'pthread_condattr_setclock' was not declared in this scope
  if (pthread_condattr_setclock(&attr, CLOCK_MONOTONIC))
                                                      ^
gmake[1]: *** [/poco-1.7.7-all/Foundation/obj/Linux/x86_64/debug_shared/Event.o] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Foundation-libexec] Error 2

My OS is Red Hat Enterprise Linux AS release 4 (Nahant Update 7),it is Linux 2.6.9.
Following is my compile step :

> tar -zxvf poco-1.7.7-all.tar.gz
cd poco-1.7.7-all
chmod 755 *
vi Foundation\include\Poco\Config.h
**enable define  POCO_NO_INOTIFY**
./configure --everything	
gmake -s -j4 

How to correct this error? 
THANKS for any help that can be given!

**Comment by skydeepsky** [comment]
I download poco-1.7.7-all from [here](https://pocoproject.org/releases/poco-1.7.7/poco-1.7.7-all.tar.gz),and then upload to my fresh install RedHat 4(U7) x86_64 ,when I compile ,it aborted with the above error info.
My step is follow:

> tar -zxvf poco-1.7.7-all.tar.gz
cd poco-1.7.7-all
chmod 755 *
vi Foundation\include\Poco\Config.h
**enable define  POCO_NO_INOTIFY**
./configure --everything	
gmake -s -j4

**Comment by obiltschnig** [comment]
I'm sorry but we'll no longer support such an old distribution. Use an older POCO release, or get a newer RedHat release.

**Comment by bachp** [comment]
I agree with @obiltschnig. RHEL4 Extended Life Cycle Support will end in [March, 31 2017](https://access.redhat.com/solutions/690063) anyway.
