### ISSUE TITLE
Question regarding class URIStreamOpener

### ISSUE THREAD

**Issue by sisyphus79** [pocoproject/poco#1569]
Hi all,
I followed the download.cpp example in order to fix code for downloading binary file. The code is 
```
		std::string url_test ="http://my_webpage/file.bin";
		URI uri_test (url_test);
		std::auto_ptr<std::istream> pStr(URIStreamOpener::defaultOpener().open(uri_test));
		std::string data;
		Poco::StreamCopier::copyToString(*pStr.get(), data);
		std::string::size_type size = data.size();

```
I have two questions regarding the above 

1) what if I'm behind a proxy server, how can I pass the proxy server arguments?
2) Since I want to calculate current download speed of large files how can I get dynamically the size of the file  instead of waiting for the whole download to end ?

**Comment by obiltschnig** [comment]
1) use Poco::Net::HTTPClientSession::setGlobalProxyConfig()
2) not possible with URIStreamOpener. Use HTTPClientSession and look for the Content-Length header. However, if the server does not provide a Content-Length header (e.g., because it's using chunked transfer encoding), you're out of luck.

**Comment by sisyphus79** [comment]
Thanks a lot for the support and sorry for the delay of closing the issue
