### ISSUE TITLE
How to cancel Blocking I/O download stream function before it is completed

### ISSUE THREAD

**Issue by dkarantonis** [pocoproject/poco#1576]
Hi,

We have 2 tasks running in parallel. One task copies download stream and the other one counts the download progress. The task that copies the stream uses the Blocking I/O StreamCopier::copyStream(istream, ostringstream);. 

What we need to do is to find a way to cancel the task that copies the stream after a period of time, even though the download has not been completed. The nature of Blocking I/O function does not allow us to cancel the task until the download finishes. Is there any way we could implement this? 

Thanks,
Dimitris

**Comment by obiltschnig** [comment]
Use HTTP(S)ClientSession directly instead of URIStreamOpener. This will give you more control over timeouts. Furthermore, don't use StreamCopier to copy the stream's contents. Use your own read/write loop. You can also call abort() on the session from another thread to cancel the download.

**Comment by dkarantonis** [comment]
Hi Günter,

Aborting https session from another thread did the trick. 

thanks a lot,
Dimitris
