### ISSUE TITLE
Unable to unzip zip file created using non-seeking stream

### ISSUE THREAD

**Issue by MrHacky** [pocoproject/poco#1580]
Running the following code (in a directory containing the attached input.txt file) results in a CRC error and then throws Poco::IllegalStateException.

```
#include <Poco/Zip/Decompress.h>
#include <Poco/Zip/Compress.h>
#include <Poco/Delegate.h>

#include <sstream>
#include <iostream>

struct Test {
	void test() {
		std::stringstream output;
		Poco::Zip::Compress zip(output, false);
		zip.addFile("input.txt", "output.txt");
		zip.close();

		std::stringstream input(output.str());
		Poco::Zip::Decompress unzip(input, ".");
		unzip.EError += Poco::Delegate<Test, std::pair<const Poco::Zip::ZipLocalFileHeader, const std::string> >(this, &Test::onDecompressError);
		unzip.decompressAllFiles();
	}

	void onDecompressError(const void* pSender, std::pair<const Poco::Zip::ZipLocalFileHeader, const std::string>& info)
	{
		std::cout << info.second << "\n";
	}
};

int main(int argc, char* argv[])
{
	Test().test();
}
```

**Comment by MrHacky** [comment]
[input.txt](https://github.com/pocoproject/poco/files/754843/input.txt)

**Comment by micheleselea** [comment]
I'm using non-seeking stream without problem but I'm using it in a HTTP transaction, and it works. I don't know if it's different with stringstream

**Comment by MrHacky** [comment]
but does it work with the file i attached? With most files it works for me too, but in some rare cases it fails. The attached file is one with which i've been able to reproduce the problem

**Comment by micheleselea** [comment]
I use non-seeking compress stream to compress HTTP reply/request so I have no file attached usually

**Comment by obiltschnig** [comment]
Could be related to #1567 and #1566

**Comment by obiltschnig** [comment]
Well, that was one fun little edge case.
