### ISSUE TITLE
Poco::MySQL insert performance

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1584]
Hi all, I was making some test on MySQL insert and I found interesting results about performance.
Here you are a description of the test (MySQL on linux OS, test client on windows OS, software compiled in release mode):
1)Connecting to an existing MySQL DB
2)Creating an empty table with just one INTEGER filed and one TEXT filed
3)Insert a lot of elements in TRANSACTION of 1000 elements
4)calculating how many inserts per seconds I can get

Here you are the piece of code:
```
#define MYSQL_USER "root"
#define MYSQL_PWD  "pwd"
#define MYSQL_HOST "localhost"
#define MYSQL_DB   "testdb"

std::string dbConnString = "host=" MYSQL_HOST
	";user=" MYSQL_USER
	";password=" MYSQL_PWD
	";db=" MYSQL_DB
	";compress=false;auto-reconnect=true";

Session session(MySQL::Connector::KEY, dbConnString);
std::cout << "Connected to [MySQL]" << std::endl;

Poco::Any h = session.getProperty("handle");
MYSQL* pDB =  = Poco::AnyCast<MYSQL*>(h);

session << "DROP TABLE IF EXISTS test", Keywords::now;
session << "CREATE TABLE test (Id BIGINT PRIMARY KEY AUTO_INCREMENT,Cont BIGINT,Description TEXT)", Keywords::now;
Poco::Timestamp tsNow;
int iCountT = 0;
session.begin();
for (int i = 1; i < 10000000; ++i) {
	if (isCancelled())
		break;
	std::string sQuery;
	Poco::format(sQuery, "INSERT INTO test (Cont,Description)VALUES(%d,'text')", i);
	session << sQuery, Keywords::now;
	
	++iCountT;
	if (iCountT>=1000) {
		iCountT = 0;
		session.commit();
		double fRowPerSec = i;
		Poco::Timespan tspanOp(tsNow.elapsed());
		if (tspanOp.totalMilliseconds() > 0) {
			fRowPerSec *= 1000;
			fRowPerSec /= tspanOp.totalMilliseconds();
		}
		std::cout << Poco::NumberFormatter::format(fRowPerSec, 2) << "rows/s" << std::endl;

		session.begin();
	}
}
session.commit();

std::cout << "Disconnecting ..." << std::endl;
session.close();
std::cout << "Disconnected." << std::endl;
```

Now the interest thing is that this way I can get about 1600 rows/sec...that seams to be quite good.

Now if you try to exchange the line of code
`session << sQuery, Keywords::now;`
with
`mysql_query(pDB, sQuery.c_str());`

I can insert about 3600 rows/sec that is much more faster than before. I know the second line is more direct and has less overhead, but I think we should investigate about what is slowing down the process when we use `session << sQuery, Keywords::now;`
Let me know what do you think

**Comment by obiltschnig** [comment]
Yes, we should investigate that. There is definitely some potential for optimization, not just in the MySQL connector, but in the core Data library and the other connectors as well. Could you do this?

**Comment by micheleselea** [comment]
If I found some time I'll try to find the bottleneck. I let you know when I can, I'm quite busy this month but I'll try

**Comment by obiltschnig** [comment]
Same for me, I have been aware of performance issues for some time now, but there's always been too many other things of higher priority.

**Comment by cngzhnp** [comment]
Maybe unnecessary check in execute function in Statement.cpp file. Because, executeAsync is already implemented for async calls, why do you check that whether this call is async or not? Removing this check. maybe helps to make it faster.
