### ISSUE TITLE
waitForTerminationRequest crashes when closing

### ISSUE THREAD

**Issue by daB0bby** [pocoproject/poco#1592]
I have an application running as `Poco::Util::ServerApplication`.

This is what my dummy main function looks like

    int main(const std::vector<std::string>& args) override
    {
        if (_helpRequested)
            displayHelp();
        else
        {
            std::cout << "Running server..." << std::endl;

            // Wait for CTRL-C or kill
            Poco::Util::ServerApplication::waitForTerminationRequest();

            // Shutdown
        }

        return Poco::Util::Application::EXIT_OK;
    }

So if I hit `Ctrl-C` the program returns 0 (as expected)
If i click on the windows close button (`X`) the program does not return 0.

**Comment by micheleselea** [comment]
pressing X button is the same to KILL appplication. So it's correct what you have as return code. The clean way is tu use the ctrl+C method that is quite the same to call Poco::Util::ServerApplication::terminate()

**Comment by aborisovich** [comment]
Please consider reopening.
There are people in this world that may not afford to support simple "application kill".
Sometimes there are resources that should be handled no matter what.
And if you don't I will write a life support app using POCO framework next time and wait till you got to hospital...
But seriously, Windows OS gives you ~6 seconds to clean resources when X is closed on the console (using SetConsoleCtrlHandler). You should allow framework users some solution to this problem. Yes I know ctrl+c works perfectly fine.
It is not enough.

**Comment by micheleselea** [comment]
You can use the Poco::Util::ServerApplication::terminate() function. I use in my application to exit from waitForTerminationRequest()

**Comment by aleks-f** [comment]
> And if you don't I will write a life support app using POCO framework next time and wait till you got to hospital...

If your life support application is running on windows as a console application, you have bigger problems than this.

But seriously - send a pull request with your desired feature, and we will review it.
