### ISSUE TITLE
Control reaches end of non-void function in SocketImpl::poll on systems for which POCO_HAVE_FD_POLL is set

### ISSUE THREAD

**Issue by mtol1701** [pocoproject/poco#1596]
I'm getting a Net/src/SocketImpl.cpp:546: warning: control reaches end of non-void function
While compiling the PocoNet library, version **1.7.7** on a system for which **POCO_HAVE_FD_POLL** gets set.

In the conditionally compiled section at line 460, #elif defined(POCO_HAVE_FD_POLL), there is no return statement after the while loop on line 486. The actual bool return error code value would be incorrect/unreliable.

This can be verified by inspection.
It seems something like this was omitted after line 486
            if (rc < 0)
            {
                error();
            }
            return rc > 0;

Thanks,
Mark Tol

**Comment by HenryHu** [comment]
This patch does not compile. errorCode is not defined.

**Comment by obiltschnig** [comment]
Send a pull request, please.
