### ISSUE TITLE
Cross platform way to to detect  32bit over 64bit platform

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1598]
Hi 
I'm wondering if there is a smart way to achieve cross platform detection of 32bit vs 64bit architecture using poco macros that just checking for every possible architecture with POCO_OS_LINUX , POCO_OS_MAC_OS_X, POCO_OS_SOLARIS etc.

Thanks in advance.

**Comment by obiltschnig** [comment]
On 64-bit platforms (where pointers are 64-bit), the macro POCO_PTR_IS_64_BIT will be defined to 1.

**Comment by dk1301** [comment]
Thanks for the solution.
