### ISSUE TITLE
fix MinGW 4.8.2 Compilation

### ISSUE THREAD

**Issue by ljx0305** [pocoproject/poco#1603]
The error information is as follows
$ g++  -Iinclude -I/d/open_source/src/poco-1.7.7/CppUnit/include -I/d/open_source/src/poco-1.7.7/CppUnit/WinTestRunner/
include -I/d/open_source/src/poco-1.7.7/Foundation/include -I/d/open_source/src/poco-1.7.7/XML/include -I/d/open_source
/src/poco-1.7.7/JSON/include -I/d/open_source/src/poco-1.7.7/Util/include -I/d/open_source/src/poco-1.7.7/Net/include
-DPOCO_BUILD_HOST=DESKTOP-MDEE2NJ -DPOCO_TARGET_OSNAME=MinGW -DPOCO_TARGET_OSARCH=i686  -D_WIN32 -DMINGW32 -DWINVER=0x5
01 -DPOCO_NO_FPENVIRONMENT -DPCRE_STATIC -DPOCO_THREAD_STACK_SIZE -I/usr/local/include -I/usr/include  -g -D_DEBUG  -c
src/Environment.cpp -o /d/open_source/src/poco-1.7.7/Foundation/obj/MinGW/i686/debug_static/Environment.o
In file included from c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/iphlpapi.h:16:0,
                 from src/Environment_WIN32U.cpp:26,
                 from src/Environment.cpp:33:
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:44:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET Address;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:56:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET Prefix;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:64:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET     NextHop;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:79:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET     Address;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:152:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET    Address;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:250:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET Source;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:251:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET Destination;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:254:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET CurrentNextHop;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:273:3: error: 'SOCKADDR_INET' does not name a type
   SOCKADDR_INET Address;
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:382:9: error: 'PSOCKADDR_IN6' does not name a type
   const PSOCKADDR_IN6 SourceAddressList,
         ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:384:9: error: 'PSOCKADDR_IN6' does not name a type
   const PSOCKADDR_IN6 DestinationAddressList,
         ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:387:3: error: 'PSOCKADDR_IN6_PAIR' has not been declared
   PSOCKADDR_IN6_PAIR *SortedAddressPairList,
   ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:454:9: error: 'SOCKADDR_INET' does not name a type
   const SOCKADDR_INET *SourceAddress,
         ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:455:9: error: 'SOCKADDR_INET' does not name a type
   const SOCKADDR_INET *DestinationAddress,
         ^
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:458:3: error: 'SOCKADDR_INET' has not been declared
   SOCKADDR_INET *BestSourceAddress
   ^
In file included from c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/iphlpapi.h:16:0,
                 from src/Environment_WIN32U.cpp:26,
                 from src/Environment.cpp:33:
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/netioapi.h:585:9: error: 'SOCKADDR_INET' does not name a type
   const SOCKADDR_INET *SourceAddress
         ^
In file included from src/Environment_WIN32U.cpp:26:0,
                 from src/Environment.cpp:33:
c:/Qt/4.8.7/mingw482_32/i686-w64-mingw32/include/iphlpapi.h:147:5: error: 'SOCKADDR_IN6' does not name a type
     SOCKADDR_IN6 Ipv6Address;
     ^

Repair methods:  on "Foundation\src\Environment_WIN32U.cpp" file

#include <winsock2.h>
+#include <ws2ipdef.h>    add this head file
#include <wincrypt.h>
#include <iphlpapi.h>

**Comment by motein** [comment]
This is really helpful and cool. I am now compiling ZMQ ~~ Thanks, man.
