### ISSUE TITLE
pcre_internal.h HAVE_STDINT_H usage changed from 1.7.7 to 1.7.8 breaking the build on older MSVC

### ISSUE THREAD

**Issue by lbakman** [pocoproject/poco#1604]
Hi

The usage of HAVE_STDINT_H and HAVE_INTTYPES_H changed from Poco version 1.7.7 to 1.7.8:

In version 1.7.7:
#if HAVE_STDINT_H
#include <stdint.h>
#elif HAVE_INTTYPES_H
#include <inttypes.h>
#endif

In version 1.7.8:
#if defined HAVE_STDINT_H
#include <stdint.h>
#elif defined HAVE_INTTYPES_H
#include <inttypes.h>
#endif

The new usage does not work well with the pcre_config.h which by default defines HAVE_STDINT_H and HAVE_INTTYPES_H to 0 - causing the pcre_internal.h to always expect stdint.h to be available.

Regards
Lau Bakman

**Comment by obiltschnig** [comment]
Which VS version are you referring to? At least VS2008 works fine according to my tests.

**Comment by lbakman** [comment]
I am building Poco using cmake and the "Visual Studio 9 2008" generator:

mkdir _build
cd _build
cmake .. -G "Visual Studio 9 2008" -DPOCO_STATIC=ON -DPOCO_MT=ON
cmake --build . --config Release

The compiler fails to build Unicode.cpp with the error that stdint.h cannot be found. 
Visual Studio 2008 does not provide stdint.h - at least it is not in my Visual Studio 2008 installation and googling suggests that it is not provided by Visual Studio until 2010.

Also my point is that HAVE_STDINT_H will always be defined in Poco 1.7.8 due to pcre_config.h, making the "#if defined HAVE_STDINT_H" a bit obsolete.

Looking back at the Poco source, I can see that the following lines have been removed from Unicode.cpp  file in the develop branch:

extern "C"
{
#include "pcre_config.h"
#include "pcre_internal.h"
}

but those lines are still in the Unicode.cpp file in the release 1.7.8 branch.

I am downloading Poco via the url https://github.com/pocoproject/poco/archive/poco-1.7.8-release.tar.gz.

**Comment by obiltschnig** [comment]
Looks like that issue is in `pcre_internal.h` with:
```
#if defined HAVE_STDINT_H
#include <stdint.h>
#elif defined HAVE_INTTYPES_H
#include <inttypes.h>
#endif
```

The `defined` should be removed, like in previous releases. Currently running some tests, will provide a patch release.

**Comment by lbakman** [comment]
Thank you

**Comment by lbakman** [comment]
This fixes the build issue with Unicode.cpp and pcre_internal.h.

Thank you!
