### ISSUE TITLE
SecureSocketImpl shutdown()

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1605]
Hi all, I'm having a strange TCP RESET packet when a secure socket close connection with a server.
The point is this:

1)have an HTTPS server made with Poco libs
2)I have an HTTPSClientSession that make request
3)Connection start, data are transferred ok
4)when it's time to close both server (a little bit earlier) and client close connection
5)Closing a SecureSocketImpl make SecureSocketImpl::shutdown() and than a close() socket
6)I think that both server and client do the same
7)the "strange think" happen because when the client do shutdown the FIN connection is already sent from server and received from client so when client do shutdown() it sends some packet that will receive a TCP RST packet

I don't know if the explanation is clear or not, but I found it because some firewall interprets that RST packet like an attempt to port scan. The comment in shutdown method make me think that we already have some "experience" in shutting down ssl connection

**Comment by micheleselea** [comment]
the function that receive a RESET packet is
int rc = SSL_shutdown(_pSSL);

**Comment by micheleselea** [comment]
I found that:
1)if I read 1 byte before doing close the SSL_get_shutdown tells me SSL_RECEIVED_SHUTDOWN
accordling to SSL documentation:
If a "close notify" was received, SSL_RECEIVED_SHUTDOWN will be set, for setting SSL_SENT_SHUTDOWN the application must however still call SSL_shutdown or SSL_set_shutdown() itself.

So Probably before calling SSL_shutdown we should check if SSL_RECEIVED_SHUTDOWN and than use SSL_set_shutdown to set the state without send data that will be rejected.
It's just a guess...but I'm not an SSL expert, so what do you think about?

**Comment by micheleselea** [comment]
Ok I think the problem here is the way we use
int rc = SSL_shutdown(_pSSL);
because both SecureSocketImpl (client and server side) check if shutdown sent, call SSL_shutdown to send shutdown packet and immediately close socket. This behavior (that was made to handle some browser problem) can bring us to the RESET packet problem...
I don't know do you think we should better check that condition?

**Comment by obiltschnig** [comment]
For reference: http://stackoverflow.com/questions/28056056/handling-ssl-shutdown-correctly

I experimented with the correct way to shutdown, by calling SSL_shutdown() twice:

```
diff --git a/NetSSL_OpenSSL/src/SecureSocketImpl.cpp b/NetSSL_OpenSSL/src/SecureSocketImpl.cpp
index 9a81898..54eb73e 100644
--- a/NetSSL_OpenSSL/src/SecureSocketImpl.cpp
+++ b/NetSSL_OpenSSL/src/SecureSocketImpl.cpp
@@ -227,6 +227,10 @@ void SecureSocketImpl::shutdown()
                        // flag by calling SSL_shutdown() once and be
                        // done with it.
                        int rc = SSL_shutdown(_pSSL);
+                       if (rc == 0 && _pSocket->getBlocking())
+                       {
+                               rc = SSL_shutdown(_pSSL);
+                       }
                        if (rc < 0) handleError(rc);
                        if (_pSocket->getBlocking())
                        {
```

Tried with Safari (Mac), Chrome and Firefox (Mac, Win) and IE11 and none of the browsers reported an error now. Interestingly, a clean shutdown only worked with Safari (first result 0, second 1, as it should be). With all other browsers, had 0 first, then -1.

**Comment by micheleselea** [comment]
Ok thanks, I'm going to try the code: I forgot to tell you I'm using OpenSSL 1.0.2k now, but I think was the same with 1.0.2j. I do not have feedback with previews version

**Comment by micheleselea** [comment]
I think I have to change the shut down on both server and client side correct?

**Comment by micheleselea** [comment]
Ok tested change in client side (HTTPSClientSession) with google for example, and it's seams ok. Tested the server side (HTTPsServer) with Chrome and seams ok. Now I'm going to try Server and Client modification and let you know

**Comment by micheleselea** [comment]
try both HTTPSClientSession on a HTTPServer (https) and the shutdown it's ok...I think it's a good solution, and should not have problem because the shutdown is in a try catch code

**Comment by obiltschnig** [comment]
Good, so I'll leave the changes in. The previous behavior was with pre 1.0 OpenSSL, so things probably have improved there.

**Comment by micheleselea** [comment]
Tested for some days and it works. The only "issue" is that if the other end do not send a SSL_shutdown properly when you close socket you get locked on the second SSL_shutdown for some seconds...in my case about 20 seconds. I'm looking in SSL documentation to see if there's a set timeout function but probably there's not

**Comment by micheleselea** [comment]
Ok found...you can simply use setReceiveTimeout() and you can set the ammount of time to wait for SSL_shutdown notification

**Comment by micheleselea** [comment]
I'm using the ssl shutdown patch in production environment and I have no connection error, but I do not try with a MacOS 10.12. I try with IE Edge chrome firefox and it's seams to works

**Comment by micheleselea** [comment]
About this SSL_shutdown "problem". I do not figure out yet the correct solution.
The solution of the double SSL_shutdown fix the RST packet received but can lead in a longer socket close if you do not receive the second close notification: but you can fix this changing the receive timeout.
The problem with the current implementation (after reverting the fix because MacOS problem) is that some Firewall consider the RST packet as a port scan attack.
Have you ever had this kind of behavior to walk around?

**Comment by micheleselea** [comment]
Anyway I don't get the reason why Safari should say "connection lost" if you add an instruction to better handle SSL shutdown...I expect exactly the opposite.
The problem is closing the connection too early cause the first SSL_shutdown notification useless because will be always discarded...I think we should check
`bool shutdownReceived = (shutdownState & SSL_RECEIVED_SHUTDOWN) == SSL_RECEIVED_SHUTDOWN;`
before do SSL_shutdown
