### ISSUE TITLE
Poco cannot run sql server stored procedures with temporary tables inside

### ISSUE THREAD

**Issue by wxShayan** [pocoproject/poco#1606]
Hello, I have an sql server stored procedure which uses temporary tables. Suppose the following simplified stored procedure (I removed many lines too show the problem):

CREATE PROCEDURE [dbo].[ReadUserAuthenticationData] 
    @userID AS INT
AS
BEGIN
    SELECT * INTO #userTempTable FROM TUser WHERE userID = @userID
    SELECT UserName	FROM TUser Where userID = @UserID
END

Executing this stored procedure using the following code:

Statement select(session);
std::string username;
select << "EXEC ReadUserAuthenticationData ?", use(userID), into(username), now;

The select statement will execute without returning any data but if you remove the first select from stored procedure it will work perfectly. Please note that any other works with temporary tables like inserting to them, also causes the same problem or even causes the program to raise exception in case of working with record sets.

**Comment by pedrodias74** [comment]
Try putting
          SET NOCOUNT ON;
on the beginning of your stored procedure.
