### ISSUE TITLE
Problematic license for JSON component

### ISSUE THREAD

**Issue by stweil** [pocoproject/poco#1614]
It's currently impossible to fully support POCO on Debian because the JSON component [includes code](https://github.com/pocoproject/poco/blob/develop/JSON/include/Poco/JSON/Parser.h#L32) using the [JSON License](http://www.json.org/license.html). It would be very helpful if that code could be replaced.

See also https://wiki.debian.org/qa.debian.org/jsonevil.

**Comment by ibroheem** [comment]
Thats a very big one!
That had been in existience for some few years!

**Comment by obiltschnig** [comment]
@fbraem: how hard would it be to get rid of the JSON License'd code fragments?

**Comment by aleks-f** [comment]
What needs to be done is preserve the [Parser](https://github.com/pocoproject/poco/blob/develop/JSON/include/Poco/JSON/Parser.h) public interface and use another parser behind it.

I looked at options out there and based on [Native JSON benchmark](https://github.com/miloyip/nativejson-benchmark), [ujson](https://bitbucket.org/awangk/ujson/src) looks like a good candidate (fast and reasonably conformant, but memory usage sucks). Also [cJSON](https://github.com/DaveGamble/cJSON) may be a good option.

Then there's also [UltraJSON](https://github.com/esnme/ultrajson), but there's no benchmark for it and there are some license links there on which I can not comment - if `Good` is not good enough, it's hard to tell what is good anymore ...

**Comment by obiltschnig** [comment]
There's also the JSON parser I have written and used in various projects, but currently it does not handle comments and does not check for valid UTF-8. This would probably be the best way to go as we don't have to deal with yet another third party code base and its licensing...

**Comment by stweil** [comment]
Would it be possible to revert commit 38131d452d which introduced that license for `JSON/Parser.h`?

@obiltschnig, using your parser also sounds promising. Many projects would not miss the current deficits which you mentioned or be willing to fix them. Maybe you can add an alternative Parser.h (in addition to the existing one) based on your code, so projects could start testing it.

**Comment by obiltschnig** [comment]
@fbraem could you comment on which parts of the Parser code fall under the JSON license?

**Comment by fbraem** [comment]
I started the POCO JSON with its own token based parser, but because it was slower then the POCO::Web::JSON parser, Alex recommended to [replace](https://github.com/pocoproject/poco/commit/87d955ecde8e2bc2843047b54ce33018dab1329b) my parser by that parser. But I don't see that license mentioned there. So I wonder why it is added to the code in this [change](https://github.com/pocoproject/poco/commit/38131d452d5e11270dacf731a2381057806227b7).

**Comment by obiltschnig** [comment]
Okay, then I'll forward this question to @aleks-f 

The question is, what of the existing code (e.g., the parseChar() method???) can we keep, and what has to be replaced by a clean reimplementation.

**Comment by aleks-f** [comment]
@obiltschnig [parseChar](https://github.com/pocoproject/poco/blob/develop/JSON/src/Parser.cpp#L156) is the entry point from the outside world. Basically, all private functions should be replaced with new parser functionality. I don't think this is an enormous task, just pick a parser you want (I suggested few above) and we'll replace it. If yours is fine, then you can use that too, but significantly affecting performance, compliance or memory usage may become an issue for users depending on those things.

**Comment by stweil** [comment]
Here are some related bug reports:

[Debian bug report for LibreOffice Online](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787080) and 
[LibreOffice Online bug report](https://bugs.documentfoundation.org/show_bug.cgi?id=103678).

The 2nd one suggests using [Orcus](http://kohei.us/files/orcus/doc/json.html) instead of the Poco JSON component.

**Comment by stweil** [comment]
Is there anything new for this issue?

**Comment by aleks-f** [comment]
no, we have no resources available for it right now. that said, if anyone wants to step in and replace it with a parser of comparable performance/memory usage, they are welcome to it. I proposed few alternatives [above](https://github.com/pocoproject/poco/issues/1614#issuecomment-282610288)

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/b595b55c245b5ee1013399408456fc48171a107e
