### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by abdessattar** [pocoproject/poco#1616]
Hello,
I saw your contribuation in POCO library, but I need to knw how can I use it to get the obejcet serialization in format JSON?
thank you in advance,
Best regards,

**Comment by matisszilard** [comment]
You can use the `Poco::JSON Object` class `stringify` method: https://pocoproject.org/docs-1.5.0/Poco.JSON.Object.html

Example: 

```
Poco::JSON::Object json;
std::ostringstream os;
json.stringify (os); // writes the JSON object into an ostream. In this example into a stringstream
```

**Comment by abdessattar** [comment]
Thank you,
I ant to know if the serializaion and the deserialization to and from JSON  is done with c++; the serialization/deserialization is done between 
json format <->objects built with c++. 
Thanl you in advance,
Best regards,
