### ISSUE TITLE
MySQL: prepared statement by default?

### ISSUE THREAD

**Issue by paulosuzart** [pocoproject/poco#1617]
Hi, I started using POCO MySQL for MemSQL access. 

```

[MySQL]: [Comment]: mysql_stmt_prepare error	[mysql_stmt_error]: MemSQL does not support prepared statements by default. This feature is currently built as a prototype and is not supported in production. You can enable it by setting enable_binary_protocol=true	[mysql_stmt_errno]: 1295	[mysql_stmt_sqlstate]: HY000	[statemnt]: select person_1.name as person_1_name from person as person_1

```

It's clear in the MemSQL documentation they don't support prepared statements, but according to POCO doc, a prepared statement is created by omitting the `now` keyword. But the statement uses `now`:

   ```
Statement select(session);
select << "select person_1.name as person_1_name from person person_1", now;
```

Is there a way to force **no prepared** statement execution by default?

**Comment by paulosuzart** [comment]
This seems to be the default behavior after some investigation and looking at `void StatementExecutor::prepare(const std::string& query)`.

Has anybody worked around it to disable POCO invoking `mysql_stmt_prepare`?

**Comment by regevran** [comment]
I'm not able to create a Poco::Data::Session object, an exception is thrown.
Can you share the technique to make it work?
