### ISSUE TITLE
AtomicCounter.h fails in macOS 10.12

### ISSUE THREAD

**Issue by lovecoffeeandmilk** [pocoproject/poco#1626]
OSAtomicDecrement32 and all its siblings in macOS 10.12 have been deprecated. I change the code to 
inline AtomicCounter::ValueType AtomicCounter::operator ++ () // prefix
{
	return __sync_add_and_fetch(&_counter, 1);
}

and it works.

If new Poco enforces c++11, use the C++ atomic might be more safer than using the system's one

**Comment by obiltschnig** [comment]
This has been fixed in release 1.7.8

**Comment by lovecoffeeandmilk** [comment]
The issue I reported, is based on 1.7.8. So I guess the issue is mostly still there. 
Could you check AtomicCounter.h in 1.7.8 and search for the keyword OSAtomicDecrement32 which has been deprecated ?

**Comment by obiltschnig** [comment]
Since the replacement for the OSAtomic functions is C++11 atomics, you need to build with `-std=c++11 -stdlib=libc++`.

**Comment by lovecoffeeandmilk** [comment]
Thanks. I have tried and it is ok now.
