### ISSUE TITLE
Im sure its been covered

### ISSUE THREAD

**Issue by ghost** [pocoproject/poco#1633]
Im working on a project that uses an older poco version (which required common.h and Blob.h)

As i want to update the files to a newer and better version. Can someone point to info how to replace those files in the code.  I've searched for information but nothing that is clear.

the reason im looking at it this way is anytime i try to use BLoB.h i get errors. research is showing all info is correct within the BLoB.h file

![Uploading 2017-03-13 22_20_57-spitfire.png…]()

**Comment by scorp12** [comment]
As i want to update the files to a newee better version.    Sorry typed on phone.
