### ISSUE TITLE
How can one get the file size of a FTP file ?

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1634]
Hi
I'm using FTPClientSession to download/upload files and measure the relevant speed rates. However it will be much easier for my implementation if I know the file size upfront. So I'd like to know if it possible to find the file size the same way that  response.getContentLength works after the creation of an HTTPResponse object?

**Comment by micheleselea** [comment]
response.getContentLength works withe the header of the HTTP request. There's nothing like that in FTP protocol.
If you are the FTP client you can do something like:
Poco::File f(sFileName)
f.getSize();
if you need to upload file to server, or you have to ask to FTP server the size of the file you are going to download, for example with a LIST (FTP command) or STAT or something that FTP server support

**Comment by dk1301** [comment]
Hi again and thanks for your quick response. The STAT command did the job. However I encountered another problem. The  setTimeout function did not work in my case. I used the following code 

```
session.login(_USER_NAME, _PASSWORD);                    
session.setFileType(FTPClientSession::TYPE_BINARY);
Timespan::TimeDiff KWaitUSec(_dwnlTimeout*Timespan::SECONDS);
session.setTimeout(Timespan(KWaitUSec));
std::istream& is = session.beginDownload(filePath);
ostringstream os;
StreamCopier::copyStream(is, os);
session.endDownload();
session.logout();
session.close();
```
Even though the connection was achieved the file was downloaded successfully the timeout did not
work whatever timespan I inserted (e.x 5 ,10 15 ,40 seconds).
Any idea what I have done wrong?

**Comment by micheleselea** [comment]
I think in your case you can use the timespan like this
`Timespan ts(long seconds,long microseconds);`
It's probably simpler. Anyway you should set timeout before login because the timeout value is setted during connection.
AnyWay I do not get the problem, if the connection is ok you will never have timeout

**Comment by dk1301** [comment]
Ok I got it. My intention was to stop an ongoing file transfer and thought that this timeout could do the job. However I also tried the abort function of FTPClientSession on a different thread since the code freezes on StreamCopier::copyStream(is, os); , perhaps due to blocking-io. Since I need to measure the ongoing download/upload speed is there a way to stop the current transfer on a different thread?

**Comment by micheleselea** [comment]
you should avoid using StreamCopier::copyStream(is, os); but do your own
while(!bStop){
//copy some bytes
}

**Comment by dk1301** [comment]
Is there any specific example or reference regarding your proposal with 
```
while(!bStop){
//copy some bytes
}
```
because I haven't understand what I exactly need to do ?

**Comment by micheleselea** [comment]
mmm....was just an example to explain that if you look in the StreamCopier::copyStream source code, you will find a do while cicle that copy from input to output stream. So why don't you make your boll bStop variable set to false from an external thread? I think it's quite a simple task you do not need an example

**Comment by dk1301** [comment]
Thanks a lot for your help
