### ISSUE TITLE
socket error in macos 10.12

### ISSUE THREAD

**Issue by lovecoffeeandmilk** [pocoproject/poco#1635]
Create a HTTPClientSession with the URL http://poco.roundsquare.net/downloads/test.txt

When sendRequest is called, an exception is thrown with exception message Net Excetpion.

I use the XCode to debug Poco by setting the breaking point, and find the ::socket function is called in the 

void SocketImpl::initSocket(int af, int type, int proto)

with the following parameter: ::socket(166, 1, 0). The return value of this socket is, certainly -1, because 166 is not recognized by Mac OS socket API.  The correct value, should be 2 because it is TCP protocol.

After some debugging I find 166 comes from 
inline int IPv4SocketAddressImpl::af() const
{
	return _addr.sin_family;
}

This sin_family is '\xa6' which is 166 after being converted to integer.

P.S. the code is below 

        Poco::URI uri("http://poco.roundsquare.net/downloads/test.txt");
        std::string path(uri.getPath());
        std::cout<<path<<std::endl;
        if (path.empty()) path = "/";
        std::cout<< uri.getHost() << " " <<uri.getPort()<<std::endl;
        const std::string myPath = ('/' == path.c_str()[0]) ? path:("/"+path);
        SocketAddress sa (uri.getHost(),   uri.getPort());
        HTTPClientSession session(uri.getHost(),   uri.getPort());
        HTTPRequest req(HTTPRequest::HTTP_GET, myPath, Poco::Net::HTTPMessage::HTTP_1_1);
        try{
            session.sendRequest(req);
        }
        catch (NetException & e)
        {
            std::cout<< e.what() << std::endl;
        }
    	Poco::Net::HTTPResponse res;
        std::istream& rs = session.receiveResponse(res);
        Poco::StreamCopier::copyStream(rs, std::cout);

**Comment by lovecoffeeandmilk** [comment]
I can be of further help in debugging if needed.

**Comment by obiltschnig** [comment]
A few things to consider:
1) Have you checked whether the samples (e.g. `Net/samples/httpget`) and testsuites that come with POCO work if you use the standard build procedure (`./configure && make`)?
2) How do you build POCO (e.g., GNU Make or CMake)? How do you build your application in Xcode? Check that the compiler settings match (e.g., `-std=c++11 -stdlib=libc++`).
3) Use `e.displayText()` to show the complete exception message instead just e.what().

**Comment by lovecoffeeandmilk** [comment]
I have not check the test suites, but let me try. I use cmake (that is why I could generate Xcode project), but before that I added the flag -std=c++11.

**Comment by obiltschnig** [comment]
I'd recommend building the libraries with the GNU Make build system and linking them to your Xcode project. That's what I do and what I know will work.

**Comment by lovecoffeeandmilk** [comment]
Thanks for suggestion. I use CMAKE mainly for generating a XCode project such that I could debug my project and Poco in the same XCode session.  If I use ./configure way to build, I am not familiar on how to generate an Xcode project for poco.
