### ISSUE TITLE
POCO Application / Server framework issues

### ISSUE THREAD

**Issue by htartisan** [pocoproject/poco#1639]
0
down vote
favorite
I have used the POCO C++ libraries fairly extensivly in the past, and I have been pretty happy with them. I find the code to be well designed/written, and (IMO) the compiled code size (libraries and application) end up being smaller than using something else like Boost.

That being said... I am having some trouble using the POCO Application / Server classes. I am trying to create a server application, and configure it with parameters that are specified either in the application "properties" file, or on the command line.

I want to first load all parameters from the "properties" file, and then load parameters from the command line (command line params should over-ride params in the "properties" file).

I was having trouble getting the server to load ANY params from the command line, even though I defined them in the "defineOptions" method (of my main application class). (Example: I defined "h"/"help" in the "defineOptions" method, and specified "-h" on the command, but the "handleHelp" method was never entered.) I tried changing my main application class initialization code to more closely match the "SampleServer" initialization code, but now I have a bug that when the "config().getString(sKey)" method is called, it NEVER returns.

The exact code that I am using is:

```
bool getConfigStr(const std::string sKey, std::string &sVal)    
{   
    if (config().hasOption(sKey) == true)
    {
        if (config().hasProperty(sKey) == true)
        {
            sVal = (config().getString(sKey)); 
            return true;
        }
    } 

    return false;
}

```
The "hasOption" and "hasProperty" calls both return true, but the "getString" call NEVER returns with a value.

I tried posting this question on the POCO forum, but got no response.

Any suggestions???

**Comment by zosrothko** [comment]
Are you on Linux or Windows?

**Comment by htartisan** [comment]
My current development work has been on Windows.

But one of the reasons that I'm using POCO is that I would like to port the software in the future to also work on Linux.

**Comment by zosrothko** [comment]
I would suggest you to have a look to this document [Applications.pdf](https://pocoproject.org/slides/190-Applications.pdf), slide 12, that states
```
Command line arguments are usually specified in the format typical for the platform:
> /option or /option=value on Windows
> -o, -ovalue, --option or --option:value on Unix
```

**Comment by htartisan** [comment]
Yes.  I have looked at that document.

I am having trouble with the code "hanging" while checking for (potential) options, even when NO options have been specified on the command line.  The problem isn't in the option text that I have typed on the command line when I run the application (server process).  The problem is in the code that scans for the existence of a (potential) option.

ALSO NOTE:  If the typing of ANY text on the command line (whether it is validly formatted or not) can cause the POCO code to hang (never return from the call), I would think that's a pretty major bug!  It's one thing to return with an error, but never returning from the call is not reasonable behavior.

**Comment by obiltschnig** [comment]
I'd suggest you fire up the debugger and check where it actually hangs. I'm not aware of any bug in the command-line parsing code and haven't seen any issue in there for the last couple of years. So I'd say it has something to do with your code or your environment. Have you tried reproducing the issue with the SampleApp or SampleServer applications? Furthermore, hasOption() and hasProperty() are the same, so calling one of these is sufficient.

**Comment by htartisan** [comment]
I have tried running the code in the debugger.  The hang is someplace deep inside the processing for "config().getString()".  I don't understand the Poco code well enough to understand what's going on inside those classes.

I also built the example "SampleServer" (on Windows), and it hung on execution when I just specified "/help" on the command line.

**Comment by obiltschnig** [comment]
What version of Windows, what version of Visual Studio (or other toolchain?), what version of POCO?

**Comment by aleks-f** [comment]
> I have tried running the code in the debugger. The hang is someplace deep

"someplace deep" is a vague description. if you are running in debugger, you can step in, right to the place where it hangs - no need to understand anything about the code, debugger will walk you right to the point where it hangs.

**Comment by htartisan** [comment]
In my debug test runs on my server code, the first call to "config().getString()" that fails, the value of the string that is being searched for is "system.nodeName".  The call to "config().hasOption()" with this value returns true, but the call to "config().getString()" never returns.

Suggestions???

**Comment by aleks-f** [comment]
give us the exact reliable way to reproduce the behavior and we will be able to help. 

in other words: provide the runtime and build environments specs as @obiltschnig suggested and how to reproduce the behavior with eg. a poco example code
