### ISSUE TITLE
SHA for 1.7.8-all has changed

### ISSUE THREAD

**Issue by dunn** [pocoproject/poco#1640]
At some point between when 1.7.8 was added to Homebrew and now, the checksum of the source tarball changed from `0b620887bb24721c72487a17523fb09d81b459eef73ae815bd6e7d308d466dd0` to `4e426b4870a79fb42511f6aeadbb688b4047bdc3c9a21ac31deb364ce49ec69f`:
```
$ brew fetch -s poco
==> Downloading https://pocoproject.org/releases/poco-1.7.8/poco-1.7.8-all.tar.gz
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.11-98-gbfb5bf1d (Macintosh; Intel macOS 10.12.3) curl/7.51.0 --fail https://pocoproject.org/releases/poco-1.7.8/poco-1.7.8-all.tar.gz -C 0 -o /Users/alex/Library/Caches/Homebrew/poco-1.7.8.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6030k  100 6030k    0     0   241k      0  0:00:24  0:00:24 --:--:--  348k
Downloaded to: /Users/alex/Library/Caches/Homebrew/poco-1.7.8.tar.gz
SHA256: 4e426b4870a79fb42511f6aeadbb688b4047bdc3c9a21ac31deb364ce49ec69f
==> Verifying poco-1.7.8.tar.gz checksum
Warning: Formula reports different SHA256: 0b620887bb24721c72487a17523fb09d81b459eef73ae815bd6e7d308d466dd0
```

Was it repackaged, or is this change unexpected?

**Comment by obiltschnig** [comment]
The release tar balls/zips have been updated a couple of hours after the release announcement. Did not expect anyone to be that quick with updating the packages ;-)

**Comment by fxcoudert** [comment]
Thanks for confirming, we will ship the new version. Please consider releasing a .1 release or increase version number in this case, to avoid this confusion to users and distributors.
