### ISSUE TITLE
If using Poco from a pre-built library then cannot use Logger level trace or debug

### ISSUE THREAD

**Issue by davidcallen** [pocoproject/poco#1651]
I am using Poco libraries v1.7.3 in Linux Fedora 23. I installed these from the Fedora repository.

I find that use of the macros poco_trace and poco_debug (and their variants) will not output any log messages even if my logger has log level set to "trace".

This is because the Poco library was not built with the compiler definition POCO_LOG_DEBUG.  In Foundation/include/Poco/Logger.h 

Can the line below be removed: 

#if defined(_DEBUG) || defined(POCO_LOG_DEBUG)

A workaround is to build Poco from source.

**Comment by zosrothko** [comment]
Correct... should be fixed sonner or later...

**Comment by zosrothko** [comment]
In fact, it works fine right now, you just have to define POCO_LOG_DEBUG in the CXXFLAGS flags you pass when compiling your application.
