### ISSUE TITLE
[VS2013][Foundation] Compile error 

### ISSUE THREAD

**Issue by kevintruong** [pocoproject/poco#1654]
With the latest VS2013 install directly through web install 
Install the version here [VS2013 community](https://go.microsoft.com/fwlink/?LinkId=517284) 

Compile error with error message 
```
Error	2	error C2280: 'std::pair<const _Kty,_Ty>::pair(const std::pair<const _Kty,_Ty> &)': attempting to reference a deleted function	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xmemory0	600	1	Foundation
```
With build with VS build 140 is work

**Comment by zosrothko** [comment]
You can insttal poco with an msi found here: [VS2013.Poco.1.7.8.x64.msi](https://github.com/pocoproject/distro/releases)

**Comment by kevintruong** [comment]
@zosrothko Really thanks for you suggestion. 
But We also made some change in Poco project. That's reason why I have to compile poco :)

**Comment by zosrothko** [comment]
So that means the error you get is coming from your changes...

**Comment by kevintruong** [comment]
oh, Not actually, I checkout the latest code from github. The origin version, no more no less. 
And trying to compile the source by VS version which i listed above. 
And It' through the error message.

**Comment by kevintruong** [comment]
But when I tried to uninstall all VS version which currently install in my Pc. And reinstall the version VS2013 which worked before without any error compile. This time, it compile success. I means no error. 
I guess some think wrong with VS Community 2013 latest version

**Comment by kevintruong** [comment]
oki. Done , Thank
