### ISSUE TITLE
Number of bytes uploaded issue when aborting ftp client session 

### ISSUE THREAD

**Issue by dkarantonis** [pocoproject/poco#1656]
Hi,

i am using the following code to upload some data to my ftp server:
```
ostringstream osstrm;
int bufferSize = 2097152; //in bytes
FillWithData(osstrm, bufferSize);
CountingOutputStream costrm(session.beginUpload(file.path()));
costrm << osstrm.str();
```

Then, i call the FTPClientSession abort function from another thread before the upload completes. I call the counting stream pos method to get bytes uploaded, but I get the total size of bufferSize, even if the real uploaded bytes are less.
`cout << costrm.pos();`

Any idea on why this happens?

thanks

**Comment by micheleselea** [comment]
I think the abort function come after you have already write all data to the internal socket buffer system, so is not an application level problem. Anyway I think that if not all bytes are sent you should receive a network or ftp exeption
