### ISSUE TITLE
Does poco support the call of a python script from a C++ program ?

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1660]
I'd like to know whether poco provides a c++ wrapper or something relevant for running python scripts ?

**Comment by OgreTransporter** [comment]
As far as I know poco doesn't support any scripting language. But this is an interesting idea. Lua could be an option, because it's very fast and has a small c code which could be used without any dependencies.

**Comment by obiltschnig** [comment]
There were some steps into that direction a couple of years ago:
https://github.com/pocoproject/sandbox/tree/master/Script

**Comment by dk1301** [comment]
I think that something similar like pybind11 or boost.python could quite useful since the combination of python and c++ is all the more frequent especially in embedded systems

**Comment by OgreTransporter** [comment]
Python is very popolar but I think for small sized projects lua is a better scripting engine, because it's much smaller than python.
