### ISSUE TITLE
Link error(LNK1104) when building Crypto under Windows. 

### ISSUE THREAD

**Issue by Kvaz1r** [pocoproject/poco#1662]
I need HTTPS request , so I start build POCO.  
As written in [External Dependencies](https://pocoproject.org/download/index.html) I edit buildwin.cmd:

> rem Change OPENSSL_DIR to match your setup
> set OPENSSL_DIR=E:\OpenSSL-Win32
> set OPENSSL_INCLUDE=%OPENSSL_DIR%\include
> set OPENSSL_LIB=%OPENSSL_DIR%\lib;%OPENSSL_DIR%\lib\VC
> set INCLUDE=%INCLUDE%;%OPENSSL_INCLUDE%
> set LIB=%LIB%;%OPENSSL_LIB%

but get error:
```
LINK : fatal error LNK1104: эх єфрхЄё  юЄъЁ√Є№ Їрщы "libeay32.lib" [E:\l
ibrary\poco-1.7.8-all\Crypto\Crypto_vs110.vcxproj]
```

What's I am doing wrong and as fix it?

**Comment by zosrothko** [comment]
poco on Windows does not use anymode imported Open SSL from the internet. It builds it in the openssl directory and uses the lib/dll from.

**Comment by zosrothko** [comment]
Otherwise, you can install the [VS2013.Poco.1.7.8.x64.msi](https://github.com/pocoproject/distro/releases/tag/poco-1.7.8)

**Comment by Kvaz1r** [comment]
@zosrothko thanks, but unfortunately I use VS12.

**Comment by Kvaz1r** [comment]
In version v1.1.0e it files non exist, download v1.0.2k. But still get error. Now as in [this](http://stackoverflow.com/questions/17897441/how-do-i-read-an-unresolved-external-symbol-error-in-visual-studio) question.
