### ISSUE TITLE
Remove warning in Dynamic/VarIterator.h

### ISSUE THREAD

**Issue by sarbjit-longia** [pocoproject/poco#1667]
"include\Poco/Dynamic/VarIterator.h(142): error #780: using-declaration ignored -- it refers to the current namespace"

This warning is casing a build error when using intel compiler to build.

**Comment by aleks-f** [comment]
can you please provide a bit more information about where does this warning occur and how does it produce build error

**Comment by sarbjit-longia** [comment]
As mentioned in the post above the warning occurs because of function swap defined in VarIterator.h.

I think in normal case it would be ok if you have all your warning turned off but in case warnings are treated as errors this cause a build error. I am using Intel compiler v 16.3 to compile my code.

**Comment by aleks-f** [comment]
Swap function is not the problem, it's the `using` that causes the warning. in any case, it was [removed](https://github.com/pocoproject/poco/commit/5f94a7488693340ca43713510aa4062367a138c5) recently and will not be in the next release.
