### ISSUE TITLE
win32 thread don't cleanup on end

### ISSUE THREAD

**Issue by bjrxyz** [pocoproject/poco#1681]
win32 thread don't cleanup on end of thread.
i find threadCleanup function will  only be call in join function,so if the thread run complete with don't call join, it's status will be running forever, and i can't restart thread.

**Comment by bjrxyz** [comment]
oh,get it。
but this can lead to HANDLE leak。

**Comment by micheleselea** [comment]
Join should be always call when you are stopping thread

**Comment by bjrxyz** [comment]
ok，i suggest you add this usage to annotation。i guess someone don‘t know should always call when stopping thread。
