### ISSUE TITLE
Where are the flags defined for Sockets

### ISSUE THREAD

**Issue by daB0bby** [pocoproject/poco#1682]
I'm working with TCP Sockets.

The function `int sendBytes(const void* buffer, int length, int flags = 0);` has a flags parameters.
[Documentation](https://pocoproject.org/docs/Poco.Net.StreamSocket.html)

Where are these flags defined? Couldn't find anything in the docs.

**Comment by obiltschnig** [comment]
POCO does not define any flags for sendBytes(). Use the system-defined ones like MSG_OOB or MSG_DONTROUTE. All other flags are highly system-dependent.

**Comment by gelldur** [comment]
worth to mention that in documentation :)
