### ISSUE TITLE
Poco::Data ODBC impl doesn't bind to unsigned numeric types properly

### ISSUE THREAD

**Issue by nick42** [pocoproject/poco#1683]
More of an FYI than anything else...

autoExtract will fail to bind properly for unsigned numeric types, if the value coming back is out of range for the signed number. I'm not sure if this is only the case for some data types, but I know it fails for SQL Server.

The binding code exists, but the issue is that ODBCMetaColumn::init() does not check the unsigned property for the column, so it doesn't create the extractor correctly. I can post a patch as desired, but it doesn't seem like there's much monitoring on this project...

**Comment by obiltschnig** [comment]
Please submit a pull request.

**Comment by nick42** [comment]
I'm not sure how I could create a pull request for this; my cloned repo is not really "clean", and it's unclear how to do this (sorry). I will attach the diff file for the change though; hopefully this is sufficient to incorporate as desired.

[pullRequest.diff.txt](https://github.com/pocoproject/poco/files/917331/pullRequest.diff.txt)

**Comment by nick42** [comment]
Note that this could certainly be refactored (eg: into another member of the _columnDesc structure); the current code structure was expedient for the fix, but not something I'd fully refactored.
