### ISSUE TITLE
 Address family not supported on FreeBSD

### ISSUE THREAD

**Issue by Dian8** [pocoproject/poco#1684]
Hello!

We are trying the attached web server sample. On windows it works ok, but on FreeBSD 11 we are getting exception
"Net Exception: Address family not supported"

We are using PoCo library installed from pkg - poco-1.7.8

[HTTPFormServer.zip](https://github.com/pocoproject/poco/files/915138/HTTPFormServer.zip)

**Comment by Bjoe** [comment]
Did you compile the pkg on your machine or you use the binary pkg?
Maybe you have the same issue that I found in my issue #1950

**Comment by Dian8** [comment]
I've used binary package from pkg

**Comment by aleks-f** [comment]
fixed in develop, closing this as duplicate, follow #1950 for progress
