### ISSUE TITLE
Derived channel class destructors are protected, should be public?

### ISSUE THREAD

**Issue by JonnyPtn** [pocoproject/poco#1686]
I can't find any previous discussion on this, only a previous pull request of a slightly similiar nature (but with no explanation for the reason behind the decision): #874 

The problem I'm experiencing is that I've tried to create a unique_ptr for my logging channel (I have since seen the examples using AutoPtr, however the API doesn't make this clear). I get this error:
```
/usr/include/c++/4.9/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = Poco::SplitterChannel]’:
/usr/include/c++/4.9/bits/unique_ptr.h:236:16:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = Poco::SplitterChannel; _Dp = std::default_delete<Poco::SplitterChannel>]’
/usr/local/include/Poco/SplitterChannel.h:66:2: error: ‘virtual Poco::SplitterChannel::~SplitterChannel()’ is protected
  ~SplitterChannel();
  ^
```

And the relevent line of my code is just instantiating the member variable:
`m_splitterChannel(std::make_unique<Poco::SplitterChannel>())`

I get the same error for file and console channels, presumably they all have this problem?

I'm happy to make the changes and submit a PR (should be a quick change), just wanted to make sure this hasn't already been discussed, and there isn't a reason why it couldn't/shouldn't be changed. (also if I'm being a plum and doing something stupid, please slap me)

Thanks in advance for any help!

Ubuntu 14.04.5
gcc 4.9
using latest develop branch, at time of writing

**Comment by obiltschnig** [comment]
`Poco::Channel` objects use internal reference counting and must be used with `Poco::AutoPtr<Poco::Channel>` pointers only. As a general rule, every Poco class derived from `Poco::RefCountedObject` must be used with Poco::AutoPtr only.

**Comment by JonnyPtn** [comment]
Thanks for the quick reply. Does that mean you don't intend on changing this?

Just flicking through the docs, I can see some classes derived from RefCountedObject which have public destructors (e.g. RegExpValidator, Context, etc..), so I guess the real question is one of consistency - Do you want to strictly enforce that these objects may **only** be used with AutoPtr, or keep it as a general rule/recommendation, and let the end user take responsibility if they choose not to use it?

**Comment by obiltschnig** [comment]
No intention to change this. For consistency all destructors should normally be protected, but there may be oversights or in some cases specific reasons why they're not.

**Comment by JonnyPtn** [comment]
OK, and what are the advantages of AutoPtr over shared_ptr? is is just for compatibility? And what are the negative reasons why the destructor cannot be public (Because this also prevents just instantiating the objects without any pointers whatsoever)?

I understand my main issue here is a subjective one, because personally I feel like the name AutoPtr isn't terribly clear in code, and I also try to avoid using `new` where possible, so has there been any discussion about changing the API here (for example, `Poco::MakeAuto()` or something?).

Ultimately, these are minor issues for me, and I wouldn't expect you to change functionality for personal preference, so feel free to close this if it won't be changed (although I'd still appreciate answers to my questions above, as I now understand that I should only be using AutoPtr, but it's still not clear exactly **why**)

**Comment by aleks-f** [comment]
Poco::AutoPtr and SharedPtr exist because there was no smart pointers in c++ at the time (except std::auto_ptr, sigh).

**Comment by JonnyPtn** [comment]
I figured that would have been the reason for it, and many libraries have such functionality, but rarely do they prevent using the stdlib smart pointers at the same time.

**Comment by obiltschnig** [comment]
Compared to shared_ptr with make_shared, there aren't really any major advantages. But then, `std::shared_ptr` and `std::make_shared` weren't available 12 years ago when work on Poco has started. `Poco::AutoPtr` is an intrusive smart pointer that requires the object it points to to provide reference counting (in the form of `duplicate()` and `release()` method, such as provided by `Poco::RefCountedObject`). I admit that the name `AutoPtr` is not the best one (especially given the similarity to dreaded std::auto_ptr), but it is what it is now and we have to keep it for backwards compatibility.

Personally I find the "fear" of new in C++ a bit exaggerated; `std::make_unique` is essentially a disguised new (as opposed to `std::make_shared`, which does interesting things besides calling `new`). But then, this is the current fad in C++.

Regarding protected destructors, this is basically to prevent explicit deletion of objects managed by reference counting. I agree we should be more consistent here. Especially, mixing `Poco::AutoPtr` and `std::shared_ptr` or `std::unique_ptr` has some potential for wreaking havoc, so generally it's better to prevent this.

**Comment by JonnyPtn** [comment]
But then wouldn't the object created by `make_shared` be destroyed as soon as the returned value goes out of scope (presuming no other shared_ptrs reference it), whereas the return value of `new` wouldn't?

Regardless, I don't mind AutoPtr existing, and in fact I support it. My main issue here is not being able to use unique_ptr or shared_ptr in my own code (where I can control which c++ version to use). 

In case you missed my edit above, I have researched a bit more, and I now understand that making the destructor protected in base classes does have an advantage, so I do agree that it's a good idea to keep it protected in the Channel class, but in the derived classes, I don't see any reason why it should be protected, as all it acheives is limiting functionality

**Comment by obiltschnig** [comment]
Yes, that's the advantage of `make_shared` and `make_unique`, especially if you're using `auto`.

**Comment by JonnyPtn** [comment]
Absolutely, and the reasoning behind base class destructors being protected is well explained by the mighty Herb Sutter here: http://www.gotw.ca/publications/mill18.htm

Still can't find any reason why derived class destructors should be protected though...

**Comment by obiltschnig** [comment]
For the same reason, mostly. To prevent you from assigning the same XYZChannel object to a Poco::AutoPtr and a std::shared_ptr (or other pointer), and to prevent you from explicitely calling delete on it (while other Poco::AutoPtr instances may still point to it).

**Comment by JonnyPtn** [comment]
Deleting an object which is referenced elsewhere is an inherent problem in c++, and one which not even stdlib smart pointers try to manage, because once a developer get's past the very basic level of learning c++, they should understand how memory management works, and what the potential pitfalls are. deleting an object which is referenced elsewhere is a c++ problem, not a Poco one, and I don't beleive Poco should try to address it

In my humble opinion, **forcing** Poco users to use AutoPtr (and disallowing raw pointers, stdlib smart pointers, or just plain old c++ objects) for a significant number of Poco objects is a very bad idea, and to be quite frank it may put me off using Poco altogether. I don't mean that to sound like a threat, but I'm sure there are others who feel the same way.

I'm not one for flogging dead horses, so if that's your stance and you're sticking to it, I'll leave this open for a few days to see if anyone else has input, then I'll close it
