### ISSUE TITLE
SQLite Notifier has no table information

### ISSUE THREAD

**Issue by petko** [pocoproject/poco#1687]
I would like to use the SQLite update callback mechanism. I've found the `Notifier` class in SQLite directory, but it seems that the only information it provides for the update callback is the row number (`getRow`). I need the table name in order to use it. Is there a way to obtain the table name?

P.S.: It looks like I can use `registerUpdateHandler` in SQLite `Utility` directly, but I still prefer to use the `Notifier` class, if obtaining the table name there is possible.

**Comment by aleks-f** [comment]
Not sure why table was not implemented, but it is [provided](https://github.com/pocoproject/poco/blob/develop/Data/SQLite/src/Notifier.cpp#L159) so it should be simple to implement. Try to implement it and let us know how it goes.

**Comment by petko** [comment]
I will try to implement it and make a pull request for it, if that's fine with you.

**Comment by petko** [comment]
I've made a pull request with this enhancement implemented: #1691
