### ISSUE TITLE
Name collision when compiling a Poco-based Cocoa app in Xcode

### ISSUE THREAD

**Issue by jayfuerstenberg** [pocoproject/poco#1693]
The NumericString.h file in Poco 1.7.8 has a private method Ptr::check which conflicts with macOS 10.12's check macro (in AssertMacros.h - line 1291) and this thwarts the compilation of Cocoa apps.

Renaming the Ptr::check method (ex: isInRange) or surrounding the class with #undef check + #define check appears to resolve the issue.

- OS: macOS 10.12.2
- IDE: Xcode 8.3
- Poco Version: 1.7.8
- Target SDK: OS X 10.8

![error-location](https://cloud.githubusercontent.com/assets/1396225/25107288/5a182f10-2383-11e7-8ce1-cafbc4058223.png)
![macos-check](https://cloud.githubusercontent.com/assets/1396225/25107289/5a1952be-2383-11e7-88a1-49fea5cf28b4.png)

**Comment by jacobsologub** [comment]
Still an issue as of `poco-1.8.1`

**Comment by aleks-f** [comment]
@obiltschnig [fixed](https://github.com/pocoproject/poco/commit/7726d024ab98a35267dae17defca29d29e477039) only in develop, duplicate #1451
