### ISSUE TITLE
Is there a way to detect an aborted HTTP request?

### ISSUE THREAD

**Issue by pathcore-tasos** [pocoproject/poco#1696]
Say my client queues up 50 HTTP requests to be processed, but drops them before they are processed. Is there a way to detect if a connection has been dropped and skip doing unnecessary work?

**Comment by micheleselea** [comment]
queuing an HTTP request means that someone connect socket that is insert in socket queue. If client disconnect from request before your request has been served you should receive a socket error that may throw a network exception, so either the poco HTTP server or your application level should manage the exception. So probably you have already this behavior that should exit process thread as soon as that error is receive (for example when server is ready to read from socket)
