### ISSUE TITLE
Got No message received exception while trying to open the websocket

### ISSUE THREAD

**Issue by joanyiwang** [pocoproject/poco#1701]
Hello,

I am using poco 1.4.6p1. Sometime got the weird "No message received" exception while trying to open a client websocket. Please advise what could be wrong.

Thanks

**Comment by gelldur** [comment]
I'm using 1.9.4 POCO version and occasionally it also happens to me. Maybe there is some kind of data race and input stream isn't ready when trying to read. In my case it usually happens ~200 µs after making request. (Time measured with steady clock) It is weird. 

99% of time I'm making same request to same server but occasionally I get this error. I'm using persistent connection.
