### ISSUE TITLE
API/ABI changes review for POCO libraries

### ISSUE THREAD

**Issue by lvc** [pocoproject/poco#1704]
The review of API/ABI changes for POCO since 1.5.3 version: https://abi-laboratory.pro/tracker/timeline/poco/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker. Hope it will be helpful for users and maintainers of the library.

![poco-1](https://cloud.githubusercontent.com/assets/1517837/25420194/fec2ae7e-2a67-11e7-8209-78c299a308d7.png)
![poco-2](https://cloud.githubusercontent.com/assets/1517837/25420200/0b71dd2a-2a68-11e7-90c0-b76b4a430ce0.png)

## Environment
* Linux x86_64
* GCC 4.9
* POCO 1.5.3 and higher

**Comment by aleks-f** [comment]
thank you @lvc
