### ISSUE TITLE
Page compiler generates 'out << ""  ' instead of nothing

### ISSUE THREAD

**Issue by Zenohate** [pocoproject/poco#1707]
In the case of sections closing and opening right again, Page Compiler doesn't optimize the generation of

```
<%%><%%>
```

And generates a line with

```
out << "" ;
```

This is true for all types of sections. Optimizing this could lead to a non neglectible amount of speedup in very tiny page like those of APIs by avoiding function ping pong.

**Comment by Zenohate** [comment]
I see you have closed the bug report, but was it implemented or not?

**Comment by Kvaz1r** [comment]
No, it was closed because it's created before 2018. More information - https://twitter.com/obiltschnig/status/1122484561747771392?s=20

**Comment by obiltschnig** [comment]
That particular issue has actually been fixed in commit 39e54d714ebd3c375921a13ec7aa5f68f1d66391 for the next release.

**Comment by Kvaz1r** [comment]
@obiltschnig , then how one should separate was issue fixed or was closed just because created before some moment or ... ?  It's really inconveniently.

**Comment by obiltschnig** [comment]
I know it's inconvenient, but there was no way to review all 600+ open issues. That specific enhancement was done independently of this particular issue.
