### ISSUE TITLE
Does poco format support ternary operator on boolean variable

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1710]
Hi all 
I have created a logger based on the logger sample. Everything works great but I faced a problem when I tried to replace a cout that had a boolean variable printout base on the ternary operator like this:
`cout<< "The value is  " <<(boolean_var ? "true" : "false")<< endl;`
I created a logger object and I tried to replace the above command with the following:
`Logger.information("The value is  "%s", boolean_var ? "true" : "false");`
However in the printout I get **[ERRFMT]**
Am I doing something wrong?
Thanks in advance.

**Comment by obiltschnig** [comment]
%s requires a std::string, not a const char*. So the correct code would be:

```
Logger.information("The value is "%s", std::string(boolean_var ? "true" : "false"));
```

**Comment by dk1301** [comment]
Great, that worked perfectly. Thanks a lot for your quick response
