### ISSUE TITLE
Add support for extracting multiple result sets via Poco::Data::RecordSet.

### ISSUE THREAD

**Issue by bobeff** [pocoproject/poco#1711]
As I understood reading [documentation ](https://pocoproject.org/docs/00200-DataUserManual.html) of **Poco::Data** the library supports extraction of [multiple data sets ](https://pocoproject.org/docs/00200-DataUserManual.html#5) using second parameter of `into` function.  But using `into` requires prior knowledge about  the returned data structure. In contrast **Poco::Data::RecordSet** described in [this](https://pocoproject.org/docs/00200-DataUserManual.html#26) section of the manual is generic and it doesn't require such prior knowledge. This allows me to write code like this.

```
template <typename ObjectType>
void ObjectDataLoaderExtractionPolicy<ObjectType>::onFetch(Poco::Data::Statement& stmt)
{
  Poco::Data::RecordSet rs(stmt);

  for (auto& r : rs)
  {
    dataLoader_.onDataObject(ObjectType::bind(r));
  }
}
```

 But it [seems ](http://stackoverflow.com/questions/43743404/how-to-fetch-multiple-result-sets-with-pocodata/43774515#43774515 ) that currently it is not possible to extract multiple data sets using **Poco::Data::RecordSet**. 

Can you add such support in the future versions of **POCO**?

**Comment by aleks-f** [comment]
Yes, but no timeframe for it at this time - if you need it urgently, implement it and send a pull request, we'll consider merging it.
