### ISSUE TITLE
OSAtomicIncrement32 missing on macOS Sierra

### ISSUE THREAD

**Issue by njlr** [pocoproject/poco#1712]
I am using macOS Sierra. When using `AtomicCounter.h` I get this error: 

> pocoproject/foundation/1.7.8/Foundation/include/Poco/AtomicCounter.h:255:9: error: use of 
> undeclared identifier 'OSAtomicIncrement32'
        return OSAtomicIncrement32(&_counter);
               ^
It seems like this line `#include <libkern/OSAtomic.h>` is not being hit due to the preprocessor flags. 

My Poco version is `627392938ae6b64e57fc8e36f3fe517d1571c471`. 

My compiler flags are: `-std=c++14`.

**Comment by skyline75489** [comment]
Have you checked #1487 ?

**Comment by njlr** [comment]
Downgrading to `-std=c++11` seems to work.
