### ISSUE TITLE
Problem with function isInteger() when parsing json

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1715]
Hi all , I have create a json parser with the help of JSONTest.cpp.
Among others I receive an epochtime data in format  ,\\"epochtime\\":\\"1493794800000\\",
When I assign 
`int64_t epochtime = dsPol["epochtime"]; `
then everything works fine and I got the correct value.
When I try to check
`if ( dsPol["epochtime"].isInteger() == true)`
I always get false value even though it contains integer value. I also tried with isNumeric() but the same result
Does anyone has an idea why this happens?

**Comment by baszczewski** [comment]
This is because of brackets inside yours JSON:
```json
"epochtime":"1493794800000",
```
!=
```json
"epochtime":1493794800000,
```

**Comment by mkrivos** [comment]
Maybe this issue is resolved here: https://github.com/pocoproject/poco/pull/1703

**Comment by aleks-f** [comment]
no, quotes make it a string and it ends up [here](https://github.com/pocoproject/poco/blob/develop/Foundation/src/Var.cpp#L405)
