### ISSUE TITLE
Poco::Net::HTTPClientSession with external socket

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1717]
I think something strange happen when we create a HTTPClientSession with a preconnected socket and a global proxy settings
```
Poco::Net::HTTPClientSession::ProxyConfig proxyConfig;
proxyConfig.host="some proxy";
proxyConfig.iport=some_port;
Poco::Net::HTTPClientSession::setGlobalProxyConfig(proxyConfig);
```

suppose you create the client session like:
```
Poco::Net::StreamSocket sSocket;
//connect sSocket
Poco::Net::HTTPClientSession* pSession = new Poco::Net::HTTPClientSession(sSocket);
```
When you do
```
Poco::Net::HTTPResponse res;
//fill req
ostream& ostr = pSession ->sendRequest(req);
```
we do not need to reconnect but function do the code

```
		if (!request.has(HTTPRequest::HOST))
			request.setHost(_host, _port);
		if (!_proxyConfig.host.empty() && !bypassProxy())
		{
			request.setURI(proxyRequestPrefix() + request.getURI());
			proxyAuthenticate(request);
		}
```
that basically put a "corrupted" URI request that screw up connection with server.
So probably we should ignore those steps if the socket is already created or we should let me setProxyHost if I use an extern socket: now that function throw exception because connection is already done.
As a walkaround I'm trying to use bypassProxy to make sendRequest think proxy is no needed.

**Comment by micheleselea** [comment]
Walkaround used: create a subclass with a constructor that set all you need like:
HTTPClientSessionEx(const Poco::Net::StreamSocket& socket, const std::string& host, Poco::UInt16 port, const ProxyConfig& proxyConfig) :
Poco::Net::HTTPClientSession(host, port, proxyConfig)
	{
		attachSocket(socket);
	}

**Comment by micheleselea** [comment]
in function `std::ostream& HTTPClientSession::sendRequest(HTTPRequest& request)` with a _proxyConfig valid comes from global proxy settings, does it makes sense to change:
```
if (!_proxyConfig.host.empty() && !bypassProxy())
{
	request.setURI(proxyRequestPrefix() + request.getURI());
	proxyAuthenticate(request);
}
```
in
```
if (!_proxyConfig.host.empty() && !bypassProxy() && !connected())
{
	request.setURI(proxyRequestPrefix() + request.getURI());
	proxyAuthenticate(request);
}
```
because otherwise if the socket is connect (because you have a socket attached from the outside) the setURI writes a wrong URI.
the problem is that you cannot `setProxyHost `if an already connected socket because it will throw `IllegalStateException`
what do you think @aleks-f ?

**Comment by obiltschnig** [comment]
Seems ok from my point of view.
