### ISSUE TITLE
Is possible to pass Cookie and RequestVerificationToken to a GET or POST  HTTP request with Poco

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1726]
Hi all, 
I'm trying to get info from a modem web api . In order to achive this, one need to send http request with a specific Cookie and RequestVerificationToken , which in curl is done by giving 
`curl -X POST -d "<request><DmzStatus>1</DmzStatus><DmzIPAddress>192.168.8.100</DmzIPAddress></request>" http://192.168.8.1/api/security/dmz -H "Cookie: SessInfo-value" -H "__RequestVerificationToken: TokInfo-value"`

I have so far used the httprequest class but haven't found a way to pass the above fields in a GET http request. Is it possible?

**Comment by micheleselea** [comment]
you can use Poco::Net::HTTPResponse from setCookies and getCookies from Poco::Net::HTTPRequest
for all other HTTP headers you can use  set("Key", "Value");

**Comment by dk1301** [comment]
Ok, thanks a lot for your help.
