### ISSUE TITLE
Does Poco support the creation of named pipe ?

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1728]
Hi all,
I'm trying to implement a interprocess communication between two different c++ apps. I've found the SharedMemory class that will do the job. However I'd like to ask whether there is a way to create a named pipe with Poco , since the class Pipe implements an anonymous pipe.

Thanks in advance

**Comment by zosrothko** [comment]
There is a [forum ](https://pocoproject.org/forum/) for asking help

**Comment by dk1301** [comment]
Thanks
