### ISSUE TITLE
POCO Thread class, and ability to "Kill" thread...

### ISSUE THREAD

**Issue by htartisan** [pocoproject/poco#1731]
I have worked quite a bit with the POCO Libraries, and for the most part been very happy with them. I have used them in a few projects with very positive results.

Recently, I have been trying to convert a few of my projects to using all (or most) POCO based classes (instead of using other libraries as well). One of the issues I have run across is the use of POCO Thread class.

I make use of a thread class (among other reasons) to make synchronous API calls into asynchronous calls, by having threads that perform the synchronous calls in the background. This enables my main application to continue doing other things. One specific place where I do this a lot is when I am performing communications calls (especially over a network or the web), and I can not have the application sit and wait for a replay. Another example is when I have my application execute another process that needs to run in the background, I create a thread that executes the child process and monitors it's execution status.

The problem that I run into (especially with communications calls) is that most thread libraries (such as POCO's thread class) do not allow me to "kill" (terminate) a thread if it has (for some reason) become "hung". An example of this is that I might make a synchronous communications call that (for some reason) never gets a reply. I might assign a "timeout" value for that call, and if the call never returns, I need to "kill" the thread making the call (as opposed to having it hang for the life of the application).

It would be VERY helpful if a "kill thread" method could be added to the POCO thread class, so that errant threads could be terminated.

**Comment by aleks-f** [comment]
There will be no such method, because there is [no way](http://collaboration.cmc.ec.gc.ca/science/rpn/biblio/ddj/Website/articles/DDJ/2008/0805/080401hs01/080401hs01.html) to kill a thread cleanly. T[h]read carefully, and if you are calling a non-interruptible system call, that is an OS, not a POCO obstacle.

**Comment by htartisan** [comment]
Then why is it that I have found another library (ZThread) that can kill threads? 


Sent from Alto
On Wednesday, May 24, 2017 at 2:46 PM Aleksandar Fabijanic <notifications@github.com> wrote:

There will be no such method, because there is no way to kill a thread cleanly. T[h]read carefully, and if you are calling a non-interruptible system call, that is an OS, not a POCO obstacle.

**Comment by aleks-f** [comment]
It is not impossible to kill a thread; it is just impossible to do it **cleanly**, as the article linked above explains.

**Comment by htartisan** [comment]
Hummmm... That doesn't make sense to me.


I have read articles about how it is difficult or "impossible" to terminate a thread and clean up after it.  To me, that is kind of silly.  I think that it is more than no one has invested the time in doing it properly.


Processes can be created and "killed" cleanly.  Classes can be created and destroyed cleanly.  Why not threads?


It would make sense to me that things like allocating memory for a thread should be done in a thread "constructor" (like a class), and that there should be a thread "destructor" (again, like a class) that is call at the end of a thread or after killing a thread.  


Why are the rules for managing memory and resources in a thread any different than those in a class, or any other C++ programming paradime?






-----Original Message-----

**Comment by aleks-f** [comment]
OK. Do it, send a pull request and we'll look at it.

**Comment by aleks-f** [comment]
Before you embark on a fool's errand, check another [explanation](https://stackoverflow.com/a/12207835) why as well as the [difference](https://www.quora.com/What-is-the-difference-between-a-process-and-a-thread/answer/Parth-Shah?srid=8jGS) between threads and processes.
