### ISSUE TITLE
Hello I have a question about using ODBC related Tuple. 

### ISSUE THREAD

**Issue by MyungJaePark** [pocoproject/poco#1736]
Hello I have a question about using ODBC related Tuple.

USE TestCode:
		Poco::Data::Statement select(sql[curID].session());
		select << "{CALL spTest(?)}"
			, in(paramInOut.Input)
			, into(paramSelect1, Poco::Data::Position(0)) <- Result : @@RowCount = 2
			, into(paramSelect2, Poco::Data::Position(1)) <- Result : @@RowCount = 3
			, into(paramSelect3, Poco::Data::Position(2)) <- Result : @@RowCount = 0
			, now;

ParamSelect3 Throw Error : Next row not available.

What I want is that when using Tuple, the @@ RowCount value of 0 is not an error.

Make sure that I am correct. Please.

FixFile : 
std::size_t ODBCStatementImpl::next()
{
	std::size_t count = 0;

	if (nextRowReady())
	{
		Extractions& extracts = extractions();
		Extractions::iterator it    = extracts.begin();
		Extractions::iterator itEnd = extracts.end();
		std::size_t prevCount = 0;
		for (std::size_t pos = 0; it != itEnd; ++it)
		{
			count = (*it)->extract(pos);
			if (prevCount && count != prevCount)
				throw IllegalStateException("Different extraction counts");
			prevCount = count;
			pos += (*it)->numOfColumnsHandled();
		}
		_stepCalled = false;
	}
	else
	{
		if (extractions().size() <= 0)
		{
			throw StatementException(_stmt,
				std::string("Next row not available."));
		}
		_stepCalled = false;
	}

	return count;
}

**Comment by aleks-f** [comment]
@MyungJaePark please provide a [SSCCE](http://www.sscce.org/)
