### ISSUE TITLE
Can this library write the restful services?

### ISSUE THREAD

**Issue by LZS1991** [pocoproject/poco#1745]
I'd like to use this great library to code some restful services, but i can not find an example ,can you help me ?

**Comment by ibroheem** [comment]
> but i can not find an example
Welcome to our world!

**Comment by LZS1991** [comment]
Thank you for your help, i will have a try and see if it can help me.Thank you very much.

**Comment by fbraem** [comment]
Look at my project [MQWeb](http://www.mqweb.org). It's an HTTP server that handles REST services for WebSphere MQ.

**Comment by ibroheem** [comment]
Thanks Man!
I think this is more complete and active... forked!

**Comment by LZS1991** [comment]
OK，i will hava a try!Thank you very much
