### ISSUE TITLE
Build PoCo using PNaCl toolchain

### ISSUE THREAD

**Issue by Ashish-Bansal** [pocoproject/poco#1748]
Hi everyone,

I'm trying to create build recipe for PoCo libs using PNaCl toolchain. I created PNaCl build config file in `build/config/` and specified all the tools from PNaCl required for building PoCo libs.

When I try to build using that config, I get error "Unknown Hardware Architecture."[0]
I went through `Foundation/include/Poco/Platform.h` and found that it defines hardware arch depending on some other ifdefs. I guess those macros are pre-defined by the standard headers files provided by compiler. I'm using `nacl_sdk/pepper_canary/toolchain/mac_pnacl/bin/pclang and pclang++` compilers. As PNaCl toolchain is architecture independent, so it might not have defined those macros.

If anyone has tried creating this in past or can help me in fixing it out, that would be really appreciable.

PS: In [0], you might see  
> -DPOCO_TARGET_OSNAME='"'NaCl'"' -DPOCO_TARGET_OSARCH='"'x86_64'"'
This is because I made changes in the NaCl-x86_64 itself and passing -D__NACL__ flag so that conditional macros defined in [1] could apply for PNaCl too.

[0] https://hastebin.com/etajituwip.rb
[1] https://github.com/pocoproject/poco/search?utf8=%E2%9C%93&q=nacl&type=

Regards,
Ashish Bansal

**Comment by aleks-f** [comment]
I have no experience with either, but from what I understand NaCl and PNaCl are different platforms, PNaCl not being a physical platform. So, I'd guess planting a NaCl "cuckoo egg" to PNaCl may be looking for trouble - you'll have to find a macro that reliably indicates PNaCl platform and then set the endianness etc. If you manage to build, sends us the patch and we'll add it.
