### ISSUE TITLE
double_conversion in NumericString is in conflict with Qt5 Core

### ISSUE THREAD

**Issue by vlebourl** [pocoproject/poco#1750]
Compiler error is:

duplicate symbol __ZN17double_conversion23DoubleToStringConverter19EcmaScriptConverterEv in:
    /usr/local/lib/libPocoFoundation.a(NumericString.cpp.o)
    /usr/local/Qt-5.5.1/lib/libQt5Core.a(double-conversion.o)

I fixed it by patching NumericString.cpp with 
#define double_conversion poco_double_conversion
on line 21

**Comment by orivej** [comment]
This was reported with a patch in #1560
