### ISSUE TITLE
System exception when using an AsyncChannel

### ISSUE THREAD

**Issue by Helvinion** [pocoproject/poco#1757]
Hello,

My code fails when I try to log a basic message using an AsyncChannel. I don't get much information : 

> terminate called after throwing an instance of 'Poco::SystemException'
>  what():  System exception

My code is : 
```
#include <Poco/AutoPtr.h>
#include <Poco/AsyncChannel.h>
#include <Poco/ConsoleChannel.h>
#include <Poco/Logger.h>

int main(int argc, char * argv[])
{
  Poco::AutoPtr<Poco::ConsoleChannel> console = new Poco::ConsoleChannel();
  Poco::AutoPtr<Poco::AsyncChannel> async = new Poco::AsyncChannel(console);
  Poco::Logger& log = Poco::Logger::root();

  log.setChannel(async); // The code works fine when my console channel is given here instead of async
  log.error("Hello ?"); // < It fails here
}
```
What it should do : Print "Hello ?" on the console
What it does        : terminates with the previously given error message

I think that probably comes from my old Linux installation : 

> Linux version 2.6.18-402.el5 (mockbuild@x86-029.build.eng.bos.redhat.com) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-55)) #1 SMP Thu Jan 8 06:22:34 EST 2015

I compiled it with : 

> g++ -I $POCO_HOME/include -L $POCO_HOME/lib -lPocoFoundation -lPocoXML -lPocoJSON -lPocoUtil main.cc -o test && ./test

My poco version is 1.7.8, I compiled and installed it manually for my user account only. The tests seemed to work fine.

What should I do to make it work ? Is it a bug ? Many Thanks

**Comment by obiltschnig** [comment]
Welcome to the wonderful world of multithreaded code. Your main() function returns before the AsyncChannel thread gets a chance to do its work. Try calling 
```
async->close();
```
 after calling `log.error()` to give the logger thread a chance to do its work.

**Comment by Helvinion** [comment]
Ouch, that hurts, I should have known that, shame on me, but thank you so much !

But actually, my real use case configures it's logger from a config file, and I do not have access to the Async Channel, just to loggers that are connected to it. What should I do to wait for it at the end of my code (or to make it wait automatically) ?

Many thanks

**Comment by obiltschnig** [comment]
Calling `Poco::Logger::shutdown()` before your program terminates should also do the trick.

**Comment by Helvinion** [comment]
Well... actually it did not work. I tried on my previous piece of code, and yes, it worked fine. But not on my real one, which loads a config file : 
```
#include <Poco/Util/LoggingConfigurator.h>
#include <Poco/PatternFormatter.h>
#include <Poco/Logger.h>
#include <Poco/Util/PropertyFileConfiguration.h>
#include <Poco/AutoPtr.h>
#include <Poco/Thread.h>                                                                                                                                                                                             

using namespace Poco;

int main(int argc, char** argv)
{
  AutoPtr<Util::PropertyFileConfiguration> config(new Util::PropertyFileConfiguration("conf.cnf"));
  Util::LoggingConfigurator log_config;
  log_config.configure(config);

  Logger& log = Logger::get("PJDOC");

  poco_error(log, "hey");

  Poco::Logger::shutdown();
  //Poco::Thread::sleep(0);                                                                                                                                                                                      
  return 0;
}
```

Calling shutdown() does not remove the error, which is the same as before. However even a thread sleep of 0ms seems to give enough time, during Linux scheduling, to print the message...
Here is my conf.cnf file (in french) : 

> logging.formatters.formatteur_cg2g.class=PatternFormatter
> logging.formatters.formatteur_cg2g.pattern=[%q][%s][%H:%M:%S:%i] %U:%u : %t
> 
> logging.channels.c_fichier.class = FileChannel
> logging.channels.c_fichier.path = poco.log
> logging.channels.c_fichier.formatter = formatteur_cg2g
> 
> logging.channels.c_console.class = ConsoleChannel
> logging.channels.c_console.formatter = formatteur_cg2g
> 
> logging.channels.c_split.class = SplitterChannel
> logging.channels.c_split.channel = c_console, c_fichier
> 
> logging.channels.c_async.class = AsyncChannel
> logging.channels.c_async.channel = c_split
> 
> logging.loggers.root.channel = c_async
> logging.loggers.root.level = trace

Did I fail somewhere ? It is weird because I analyzed Poco source code, and Logger::shutdown should release the different channels... How did I fail ?

Thanks
