### ISSUE TITLE
ClassLoader manifest not found

### ISSUE THREAD

**Issue by jdwieber** [pocoproject/poco#1758]
I'm trying to use Poco::SharedLibrary et a.l. to swap shared objects on the fly. I built a very simple demo, essentially the same as the AbstractPlugin example here https://pocoproject.org/slides/120-SharedLibraries.pdf but in nested namespaces. None of the shared objects load. I get the following exception:

`Cannot load library: No manifest in /bb/sys/lib/64/libtwo.so`

I'm calling the manifest macros in the cpp files:

    POCO_BEGIN_MANIFEST(IPlugin)
        POCO_EXPORT_CLASS(PluginTwo)
    POCO_END_MANIFEST

nm shows meta object symbols:

    nm -X64 lib/64/libtwo.so | grep 'Poco::AbstractMetaObject' | wc -l
       31

What could be going wrong?

Thanks.

**Comment by obiltschnig** [comment]
Are the macros inside your namespace?

**Comment by jdwieber** [comment]
Hi Günter, thanks for the quick response. Yes, they're in the namespace after the class member implementations. The only other difference I see between the example and my code is that I have .h and .cpp files for my concrete classes, but I don't see how that would matter.

**Comment by obiltschnig** [comment]
The macros need to be in the global namespace, but can reference the classes in your namespace:

```
POCO_BEGIN_MANIFEST(YourNamespace::IPlugin)
    POCO_EXPORT_CLASS(YourNamespace::PluginTwo)
POCO_END_MANIFEST
```

**Comment by jdwieber** [comment]
It appears that the issue stemmed from aggressive optimization flags.

**Comment by obiltschnig** [comment]
Oh, interesting and good to know.
