### ISSUE TITLE
Aborted (core dumped) error occurs on release mode in Ubuntu 16.04 distribution

### ISSUE THREAD

**Issue by dkarantonis** [pocoproject/poco#1761]
I have used the following piece of code
```
                ThreadPool  tp(THREAD_POOL_NAME);
                TaskManager tm(tp);

                Poco::AutoPtr<MyClass1> ptrA = new MyClass1;
                tm.start(ptrA.duplicate());
                Poco::AutoPtr<MyClass2> ptrB = new MYClass2;
                tm.start(ptrB.duplicate());

                tp.joinAll();
                ptrA->release();
                ptrB->release();
```

When used in Ubuntu 16.04, aborted (core dumped) occurs.
When I run gdb I get the following error :

> [New Thread 0x7ffff2022700 (LWP 5437)]
> [New Thread 0x7ffff1821700 (LWP 5438)]
> [Thread 0x7ffff1821700 (LWP 5438) exited]
> [Thread 0x7ffff2022700 (LWP 5437) exited]
> 
> Thread 2 "npt" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7ffff405c700 (LWP 5376)]
> 0x00007ffff5880a40 in _int_free (av=0x7fffe4000020, p=<optimized out>, have_lock=0) at malloc.c:4003
> 4003       malloc.c: No such file or directory.

The result of core analysis:

`gdb -c core`

> [New LWP 5288]
> [New LWP 5286]
> [New LWP 5289]
> [New LWP 5290]
> Core was generated by `./npt'.
> Program terminated with signal SIGABRT, Aborted.
> #0  0x00007ffad3d26428 in ?? ()
> [Current thread is 1 (LWP 5288)]

Which I assume is a segmentation fault due to probable double free/delete.

When I removed the release commnands ptrA->release();, ptrB->release(); the code worked without crashes.

When I tried to debug the code in debug mode and the release commands active the code also worked without crashes.

thanks,
Dimitris

**Comment by obiltschnig** [comment]
You are not supposed to call duplicate() and release() on a Poco::AutoPtr yourself.

**Comment by aleks-f** [comment]
In the first attempt, this part was good:
```
tm.start(ptrA.duplicate());
```
but this was not:
```
ptrA->release();
```

**Comment by dkarantonis** [comment]
thanks
