### ISSUE TITLE
"Poco/BufferedStreamBuf.h" not found (1.7.8p3)

### ISSUE THREAD

**Issue by lasote** [pocoproject/poco#1764]
Hi! I'm trying to build the latest 1.7.8p3 with my conan recipe but it fails, any hint?

```
****/poco/ApacheConnector/include/ApacheStream.h:18:10: fatal error: 'Poco/BufferedStreamBuf.h' file not found
#include "Poco/BufferedStreamBuf.h"

````

I'm using apple-clang on OSX.

I'm improving the recipe and updating it to include it in the new curated repository ["conan-center"](https://bintray.com/conan/conan-center) on bintray, I will contact again when ready, would be great to open an organization "pocoproject" to be able to collaborate if possible (we will maintain it anyway but would be great if we get help from the community).

**Comment by lasote** [comment]
After adding some missing include directories to other Poco modules I ran into linking problems, so I disabled the apache connector module in the recipe:

```
/poco/ApacheConnector/src/ApacheConnector.cpp:154:2: error: no matching function for call to 'ap_log_error_'
        ap_log_error(file, line, level, 0, NULL, "%s", text);
        ^~~~~~~~~~~~
/usr/include/apache2/http_log.h:370:22: note: expanded from macro 'ap_log_error'
#define ap_log_error ap_log_error_
                     ^~~~~~~~~~~~~
/usr/include/apache2/http_log.h:372:18: note: candidate function not viable: no known conversion from 'const char [3]' to 'const server_rec *' for 6th argument
AP_DECLARE(void) ap_log_error_(const char *file, int line, int module_index,
                 ^
/Users/luism/.conan/data/Poco/1.7.8p3/conan/testing/build/fe38d7bb078f522af67bd7b83f3c40e4300135a8/poco/ApacheConnector/src/ApacheConnector.cpp:181:19: error: no member named 'remote_ip' in 'conn_rec'
                        r->connection->remote_ip, 
                        ~~~~~~~~~~~~~  ^
/Users/luism/.conan/data/Poco/1.7.8p3/conan/testing/build/fe38d7bb078f522af67bd7b83f3c40e4300135a8/poco/ApacheConnector/src/ApacheConnector.cpp:182:19: error: no member named 'remote_addr' in 'conn_rec'
                        r->connection->remote_addr->port));
                        ~~~~~~~~~~~~~  ^
```

**Comment by obiltschnig** [comment]
ApacheConnector should really be retired (moved to a separate repo, along with some other modules) as it's not maintained anymore.

I have also cloned your [repo](https://github.com/pocoproject/conan-poco), as I'd be happy to take over maintenance of the Conan package(s) for POCO, but need some time to familiarize myself with the package publishing process. In any case, having a pocoproject organization would be great.

**Comment by lasote** [comment]
Ok then! So the disabled option for apache connector is good by now, in the future, we can remove it.
About the organization, great, I'm going to create it in Bintray, please send me a Bintray username to grant you admin access. 

About the maintenance, don't worry, we understand that it can take some time, we can collaborate until you are prepared. I've finished the recipe and binary packages for the latest Poco version, I'll move it to the new organization ASAP and then we can link it to conan-center. If you have time take a look at the latest recipe branch (release/1.7.8p3) in the repository, and tell me if the conanfile.py looks good.

**Comment by obiltschnig** [comment]
Good. I've registered via GitHub, my username is obiltschnig. I have also registered the pocoproject organization, since Bintray asked me for an organization during registration.

**Comment by lasote** [comment]
Could you add "lasote" user with write permissions?
