### ISSUE TITLE
TCPServerConnectionFactory creatConnection bug

### ISSUE THREAD

**Issue by AVFoundation** [pocoproject/poco#1765]
Hello， Recently I refer to timeServer.cpp and write a tcp server. But I find that sometimes the creatConnection can not be invoked.  I don't know anybody have met this problem

**Comment by AVFoundation** [comment]
I use the wireshark to capture the packets. And I find the state is established. I think the problem is socket.poll function. Can anybody give some advice

**Comment by micheleselea** [comment]
never had problem with TCP server, which O.S. are you using? and write some code to check.
Does the timeserver.cpp works for you if you run it?

**Comment by AVFoundation** [comment]
it's my fault. Because the client abnomal shudowns , the tcpServerDispatcher thows exception.
