### ISSUE TITLE
StreamSocket skipping received packets

### ISSUE THREAD

**Issue by daB0bby** [pocoproject/poco#1770]
I don't know if it's an bug or an implementation error on my side.

I have a client that send a lot of data over StreamSocket.
Something like this:
```
while (true)
{
    // get data and calculate size

    const auto sentSize = _socket.sendBytes(data, size);
}
```
Size and sentSize is always the same, so the sata is sent successfully.

On my server-side if have a code like this:
```
auto buffer = new unsigned char[BUFFER_SIZE];

while (...)
{
    // Receive packet
    size = socket().receiveBytes(buffer, BUFFER_SIZE, flags);

    // Shutdown request
    if (size < 1)
        break;

    // Do some calculation with buffer
    // This may take a few seconds
}
```

So the client send all data, but when I print the data at the server side, it seems like some packets got lost.

Do the packets get skipped, if no one is waiting for them? Like `socket().receiveBytes(buffer, BUFFER_SIZE, flags);` is not called because the program still does some calculation within the while iteration?

**Comment by micheleselea** [comment]
packet is lost if socket is broken. If you do not receiveBytes the only thing happen is that you fill your tcp window and on client site you will receive in the end some socket error. Have you try using some
```
try{
size = socket().receiveBytes(buffer, BUFFER_SIZE, flags);
}catch(Poco::Exception& exc){
}
```
to see if something happen?
Have you try use WireShark to sniff eth packets and see what happen?

This code:
```
// Shutdown request
    if (size < 1)
        break;
```
is not the right way to do so, you should use select for check if socket is readable and available bytes are 0: that is the thing tell you socket is closed

**Comment by daB0bby** [comment]
Yes it is within a try-catch. But an exception is never thrown.

**Comment by micheleselea** [comment]
never happen to me, and I use Poco::Socket very often in my softwares. Have you try with wireshark to see if something strange? which OS?

**Comment by aleks-f** [comment]
question is not clear:
- blocking or non-blocking socket?
- with size < 1 socket could either be closed or there could be an error on it
- code is not showing the criteria for while(...) etc.

**Comment by daB0bby** [comment]
- It's a blocking socket

I left it just for simplicity reason but the actual condition is: `while (size != 0)`

How can I determine if there is an error? According tho the decumention [here](https://pocoproject.org/docs/Poco.Net.StreamSocket.html#25049) there is only mentioned that its a shutdown when `size =  0` is received, right?

The thing is that the while loop never breaks (except in shutdown how it is supposed to) and it receives packets, but not all packets arrive.

My test case:
I send 1000 messages from the client with the a value I increment with every message `0..1000` .
I log the data when it's received, but it looks like this
```
0
2
4
5
7
11
12
15
17
...
```

So it seems like not all packages are being received. But the client never throws an error. It sends all of my 1000 messages.

I don't know if it is a bug or an implementation error on my side (which I think it is).
I couldn't find any samples of TCP client or server in this repo. Are there any?

I hope this clears things up.

**Comment by aleks-f** [comment]
> I hope this clears things up.
Not really - if you suspect the error is in your implementation, then we need a [SSCCE](http://www.sscce.org/) for server and client in order to be able to reproduce it. There's also a good chance you'll find the problem while working on SSCCE.

**Comment by daB0bby** [comment]
@aleks-f You're right. Will post it tomorrow.

**Comment by daB0bby** [comment]
I put a small and simple example with the problem in my repo [here](https://github.com/daB0bby/cpp-playground/tree/master/sockets)

**Comment by daB0bby** [comment]
@aleks-f any ideas what might cause the issue?

**Comment by aleks-f** [comment]
can't build your examples with cmake and when I build using clang, it abort traps for some reason, have no time to investigate. 

in any case, from a brief look at the code, the problem is that TCP is a stream, but you seem to expect to receive the integers as you would wish - in 4 byte chunks. that's not how streams work, what if you receive eg. 2 bytes, then 6 bytes? you should accumulate received bytes in a buffer, and when the received size hits (or goes over) 4, extract the integer you expect and trim the buffer

**Comment by aleks-f** [comment]
alternatively, if your read is blocking then ask only 4 bytes at a time

**Comment by daB0bby** [comment]
@aleks-f I see. Thank you. This cleared things up for me 👍 

So there is no option to receive **only one** packet? (The size of the packets is dynamic)

**Comment by micheleselea** [comment]
No, TCP is stream as aleks said. You can use UDP that is not a stream but is a sequence of packets. That is why you usually have some kind of protocol with TCP that let you know how to retrieve your data

**Comment by daB0bby** [comment]
Thank you for your time. Helped me a lot. 👍
