### ISSUE TITLE
Distro Release 1.7.8p3 (2017-06-22) does not reflect POCO as of June 

### ISSUE THREAD

**Issue by hakan-akan** [pocoproject/poco#1771]
I have just downloaded poco-1.7.8p3-all.zip from the web site which I thought would reflect the POCO as of June 2017. This distro does not reflect the current state of the POCO at all. For example, distro does not even include JSONString.cpp which is a file that was added in 2015, according to GitHub file stamp. There are other differences as well.

Am I  missing out something?

**Comment by aleks-f** [comment]
there are differences, @obiltschnig can clarify details

**Comment by obiltschnig** [comment]
Obviously there's a difference between develop branch and master branch (on which the release is based). At this time I don't consider the develop branch fit for general release. However, nothing stops you from using it at your own risk ;-)

There will be an upcoming 1.8 release which will put the master closer to develop, but what's currently in develop will at one point become 2.0.

**Comment by hakan-akan** [comment]
Good to hear master branch will be closer to the development branch. 
Currently, I am using the development branch. 

Thanks.
