### ISSUE TITLE
Why do POCO libraries in pocoproject differ from the ones in macchina.io?

### ISSUE THREAD

**Issue by hakan-akan** [pocoproject/poco#1772]
I  recently wanted to use RemoteNG. I thought since I have been using POCO libraries for a while, it would be a matter of adding the RemoteNG to my current POCO. But this is not the case. One has to reconcile use the macchina.io POCO Foundation and Net instead of proproject Foundation and Net. Is this intentional?

**Comment by obiltschnig** [comment]
Well, you could copy the RemotingNG libs from macchina.io to your POCO-based project. The RemotingNG libs will work with any recent POCO release.

**Comment by hakan-akan** [comment]
That's what I have been doing.
