### ISSUE TITLE
Throwing exception inside of ~BasicBufferedStreamBuf()

### ISSUE THREAD

**Issue by sapharow** [pocoproject/poco#1776]
Hello,

The destructor of BasicBufferedStreamBuf() calls Allocator::deallocate which can throw exceptions. In particular it throws Poco::SystemException when can't lock mutex. 

I've encountered such case in rare cases when application is about to finish and when ~BasicBufferedStreamBuf() is being called from detached thread whilst main thread is already finished and static variables such as Allocator's pool are destroyed. Enclosing body of ~BasicBufferedStreamBuf() into try/catch solves the issue.

References:
https://isocpp.org/wiki/faq/exceptions#ctor-exceptions
http://www.codingstandard.com/rule/15-2-1-do-not-throw-an-exception-from-a-destructor/

**Comment by niparx** [comment]
I wonder, why this fix is not released yet? I mean, you have a fix, you had several releases already. But it still not there. Why?
