### ISSUE TITLE
src/Var.cpp: 2 * sanity check in wrong place ?

### ISSUE THREAD

**Issue by dcb314** [pocoproject/poco#1784]
src/Var.cpp:421]: (style) Array index 'pos' is used before limits check.

src/Var.cpp:450]: (style) Array index 'pos' is used before limits check.

You might also want to have a look at this one:

src/ICMPv4PacketImpl.cpp:237:28: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

Looks like a || / && mixup to me.

**Comment by aleks-f** [comment]
fixed the first one, I see no problem with ICMv4PacketImpl - those are valid checks to ensure int is within valid enum limits

**Comment by dcb314** [comment]
>I see no problem with ICMv4PacketImpl

Suggest look again.

Source code is

       if (code >= TIME_TO_LIVE || code < TIME_EXCEEDED_UNKNOWN)

Substituting enums

       if (code >= 0 || code < 2)

Which is obviously wrong. QED.

**Comment by aleks-f** [comment]
that's been [fixed](https://github.com/pocoproject/poco/commit/e0b64badfed378490f5792ec34cb58e328a552c4#diff-5224a317694f9875f2e71b63e5734ecd) in develop
