### ISSUE TITLE
How to append new key-value pairs in an existing json file?

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1789]
Hi all, 
I ' ve so far created an app that builds a json object and save the result to an external json file.

```
			Poco::JSON::Object::Ptr root = new Poco::JSON::Object();
			Poco::JSON::Object::Ptr menu = new Poco::JSON::Object();

			menuObj->set("value1", "");
			menuObj->set("value2", "");
			root->set("log", menu);
			Poco::Dynamic::Var var(root);
			std::ostringstream os;
			os << var.toString();

			Poco::FileOutputStream fos("log.json", std::ios::app);
			fos << os.str();
			fos.close();
```
However if the app runs twice then the result json ends up with invalid schema.
Apart from manipulating the save json file (remove the last **}** and add a **,** after the next to last **}** ) I was wondering whether there is a way to append new  key-value pair by using poco json library?

Thanks in advance.

**Comment by aleks-f** [comment]
JSON library does not concern itself with files, so the answer is no.
