### ISSUE TITLE
develop: DATA/ODBC testsuite is using a c++11 feature with non c++11 compliant compilers

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#1790]
Hi

In the develop branch, SQLExecutor.h@572 is using a c++11 feature: default template parameter, feature which is not supported by non c++11 compliant compilers like g++ 4.6/4.8 & clang 3.4. Thus all Travis CI jobs are failing.
 
```
	template <typename IntType =
#ifdef POCO_64_BIT
		Poco::Int64 IntType
#else
		Poco::Int32 IntType
#endif
	>
	void internalExtraction(IntType)
```
```
In file included from src/ODBCTest.h:25:0,
                 from src/ODBCDB2Test.h:20,
                 from src/ODBCTestSuite.cpp:14:
src/SQLExecutor.h:567:15: error: expected â€˜>â€™ before â€˜IntTypeâ€™
   Poco::Int64 IntType
               ^
src/SQLExecutor.h:572:33: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
```

**Comment by aleks-f** [comment]
This is not an issue. Develop branch will become 2.0, which will introduce c++11 support. In other words, there is no need to avoid c++11 in develop branch anymore.

**Comment by zosrothko** [comment]
ok but in that case, the poco-c++11 branch should be merged with the develop branch so that the Travis CI jobs use the proper compiler options. (.travis.yml and build directory at least)

**Comment by aleks-f** [comment]
I will look at that soon. Not sure how many conflicts there will be, it's been neglected for a long time:
![image](https://user-images.githubusercontent.com/2429093/27867190-451da3a2-6199-11e7-93c8-71b24de1f96e.png)

**Comment by zosrothko** [comment]
ok
