### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#1793]
It's time. g++4.9, clang3.3 and VS2015 will become minimum compiler versions.

**Comment by ibroheem** [comment]
With g++-4.9, a lot of C++14 features can also creep in.

**Comment by aleks-f** [comment]
@ibroheem there are [defines](https://github.com/pocoproject/poco/blob/c%2B%2B11/Foundation/include/Poco/Config.h#L43) for that

**Comment by ibroheem** [comment]
OK, seen!
So it is C++11/C++14 in reality!

Time to have true asyn lib using lambdas as callbacks!

**Comment by whidbey** [comment]
I still like vs2010.... 
vs2015 is too bigger

**Comment by micheleselea** [comment]
yes! great job...I'll will soon migrate from vs2015 to vs2017

**Comment by micheleselea** [comment]
@whidbey I think vs2010 is the IDE with more bugs MS ever done :D

**Comment by zosrothko** [comment]
@micheleselea Can you have a look to the review [here](https://github.com/pocoproject/poco/pull/1825)

**Comment by micheleselea** [comment]
sorry @zosrothko  do not understand what I should do

**Comment by zosrothko** [comment]
@micheleselea comment the change you made to the source Socket.cpp (why, reference, ...)
