### ISSUE TITLE
Docker-based DB tests

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#1794]
Create scripts along the lines of [MySQL](https://github.com/pocoproject/poco/blob/develop/Data/MySQL/testsuite/run-tests.sh) (improvements thereof welcome, although linux-only solution should be sufficient).

Any takers? @zosrothko @fbraem @intensifi

**Comment by aleks-f** [comment]
Also, if anyone can decrypt what's happening with mysql - after lots of trouble to prevent mysql going to unix socket by default when using `localhost` (thus [127.0.0.1](https://github.com/pocoproject/poco/blob/develop/Data/MySQL/testsuite/src/MySQLTest.cpp#L52)), I was able to run the tests. now, after some updates (parallels tools, ubuntu 16.04), back to square one:
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
8b14dd4c07f2        mysql:latest        "docker-entrypoint..."   6 minutes ago       Up 6 minutes        0.0.0.0:3306->3306/tcp   poco-test-mysql
```
can't conect from outside container (note above that port is exported):
```
$ mysql -h 127.0.0.1 -P 3306 --protocol=tcp -u root -p
Enter password:
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 2
```
but DB is up and running:
```
$ docker exec -it 8b bash
root@8b14dd4c07f2:/# mysql -h 127.0.0.1 -P 3306 --protocol=tcp -u root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.18 MySQL Community Server (GPL)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

**Comment by zosrothko** [comment]
@aleks-f I am not familiar with Docker, nor with MySsql. Sorry
