### ISSUE TITLE
Digest authentication with algorithm SHA-256

### ISSUE THREAD

**Issue by BabuGiri** [pocoproject/poco#1802]
i see default algorithm configured in latest POCO 1.7.8 is MD5 is tis fixed? or there is a way to configure to latest algorithm SHA-256 as per https://tools.ietf.org/html/rfc7616

**Comment by aleks-f** [comment]
Unfortunately, there is currently no way to change it. Since digest auth is a http feature, it is not a high priority, but if you'd like to see the feature quickly please send a pull (with test).
