### ISSUE TITLE
Integer Overflow or Wraparound

### ISSUE THREAD

**Issue by ovidiu-benea** [pocoproject/poco#1803]
Ran a Veracode (https://www.veracode.com) static scan of our application windows 32-bit binaries that are using poco library.
Used the following compiler/linker flags, see "Compilation Instructions for C/C++ on Windows" here:
https://help.veracode.com/reader/4EKhlLSMHm5jC8P8j3XccQ/3Lu03OATx74TyUh~WCn8wQ
It found 1 very high security issue in poco library:
Integer Overflow or Wraparound in: data/sqlite/src/sessionimpl.cpp line: 226

poco version: 1.7.8-all (2017-02-22)

Operating system: Windows 10 Pro

Expected: No very high security issues.

**Comment by obiltschnig** [comment]
I would not call that "very high security" because there's nothing that can go terribly wrong here, but should be fixed anyway.
