### ISSUE TITLE
Untrusted Search Path

### ISSUE THREAD

**Issue by ovidiu-benea** [pocoproject/poco#1806]
Ran a Veracode (https://www.veracode.com) static scan of our application windows 32-bit binaries that are using poco library.
Used the following compiler/linker flags, see "Compilation Instructions for C/C++ on Windows" here:
https://help.veracode.com/reader/4EKhlLSMHm5jC8P8j3XccQ/3Lu03OATx74TyUh~WCn8wQ
It found 1 very high security issue in poco library:
Untrusted Search Path (Process Control ) in: foundation/src/process_win32u.cpp line: 282

poco version: 1.7.8-all (2017-02-22)

Operating system: Windows 10 Pro

Expected: No very high security issues.

**Comment by obiltschnig** [comment]
Don't use Poco::Process::launch() if this is of concern to you, or make sure to pass an absolute path as command.
