### ISSUE TITLE
Question: Redis sorted set support

### ISSUE THREAD

**Issue by kapcino** [pocoproject/poco#1807]
I want to use sorted set of redis, but found there is only set is implemented in Command class.

Can I implement the sorted set by adding the related commands of sorted set in Command class? Do I need to handle the reply as well?

Thanks!

**Comment by fbraem** [comment]
It's possible to use all Redis functions. Even when there is no wrapper function in the Command class:

Use the Redis Array class and the << operator to build the command:

    Array cmd;
    cmd << "ZADD" << "SetName" << ...

or use the Command class:

    Command cmd("ZADD");
    cmd << "SetName" << ...

**Comment by kapcino** [comment]
Great, I just tried, and it works!
Thanks a lot!
