### ISSUE TITLE
Wildcard Certificate verification too lenient?

### ISSUE THREAD

**Issue by Burgch** [pocoproject/poco#1817]
I've been playing with certificates from [Bad SSL](https://badssl.com/), and noticed that the logic used in `Poco::Net::X509Certificate::matchWildcard` seems to be more lenient than the recommendations made in [RFC 6125](https://tools.ietf.org/html/rfc6125#section-6.4.3) - specifically it allows [wrong.host.badssl.com](https://wrong.host.badssl.com/) for a certificate `*.badssl.com`.

Is the Poco implementation intended to be RFC compliant? If so, would you consider using (at least in the `NetSSL_OpenSSL` module) the [X509_check_host](https://www.openssl.org/docs/man1.0.2/crypto/X509_check_host.html) implementation introduced in OpenSSL 1.0.2? Happy to look into creating a Pull Request if so.

**Comment by aleks-f** [comment]
sure, @obiltschnig ?

**Comment by obiltschnig** [comment]
Yes, if we could use X509_check_host in OpenSSL 1.0.2 that would be great. Just add an #if to check if the correct OpenSSL version is available. Otherwise, fall back to the current behaviour, even if it may be incorrect.

**Comment by Burgch** [comment]
Thanks, shall get a Pull Request ready. Are there any test frameworks for X509 certificates within Poco?

**Comment by obiltschnig** [comment]
There is a very basic test case for `Poco::Crypto::X509Certificate` in `Crypto/testsuite/src/CryptoTest.cpp`. Would be nice to have a proper test case for `Poco::Net::X509Certificate::verify()` as well in `NetSSL_OpenSSL/testsuite`.
