### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by sekcheong** [pocoproject/poco#1818]
Hi,

> OS: Windows 10
> Architecture: x64
> Visual Studio: 2017 Enterprise
> POCO: 1.7.8p3
> OpenSSL: 1.0.2L (x64) (see: https://slproweb.com/products/Win32OpenSSL.html)
> Building: Unit, Foundation, Util, JSON, XML, Net, NetSSL, Crypto

I was actually trying hard (around 4  hours or so) to build POCO with following parameter:
`buildwin 150 build shared release x64`

And this is what I get:

> "D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj" (build Ziel) (1) ->
>        (Link Ziel) ->
>          CipherImpl.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "EVP_CIPHER_CTX_reset" in Funktion ""public: virtual __cdecl Poco::Crypto::`anonymous namespace'::CryptoTransformImpl::~CryptoTransformImpl(void)" (?
>        ?1CryptoTransformImpl@?A0xd82eb75d@Crypto@Poco@@UEAA@XZ)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          DigestEngine.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "EVP_MD_CTX_new" in Funktion ""public: __cdecl Poco::Crypto::DigestEngine::DigestEngine(class std::basic_string<char,struct std::char_traits<char>,
>        class std::allocator<char> > const &)" (??0DigestEngine@Crypto@Poco@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_
>        vs150.vcxproj]
>          DigestEngine.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "EVP_MD_CTX_free" in Funktion ""public: virtual __cdecl Poco::Crypto::DigestEngine::~DigestEngine(void)" (??1DigestEngine@Crypto@Poco@@UEAA@XZ)". [
>        D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          OpenSSLInitializer.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "OPENSSL_init_crypto" in Funktion ""public: static void __cdecl Poco::Crypto::OpenSSLInitializer::initialize(void)" (?initialize@OpenSSLIniti
>        alizer@Crypto@Poco@@SAXXZ)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          OpenSSLInitializer.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "OPENSSL_init_ssl" in Funktion ""public: static void __cdecl Poco::Crypto::OpenSSLInitializer::initialize(void)" (?initialize@OpenSSLInitiali
>        zer@Crypto@Poco@@SAXXZ)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          RSAKeyImpl.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "RSA_get0_key" in Funktion ""public: class std::vector<unsigned char,class std::allocator<unsigned char> > __cdecl Poco::Crypto::RSAKeyImpl::decrypti
>        onExponent(void)const " (?decryptionExponent@RSAKeyImpl@Crypto@Poco@@QEBA?AV?$vector@EV?$allocator@E@std@@@std@@XZ)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          X509Certificate.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "OPENSSL_sk_num" in Funktion ""public: void __cdecl Poco::Crypto::X509Certificate::extractNames(class std::basic_string<char,struct std::char_tr
>        aits<char>,class std::allocator<char> > &,class std::set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class st
>        d::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)const " (?extractNames@X509Certificate@Crypto@Poco@@QEBAXAEAV?$basic_string@DU?$char_traits
>        @D@std@@V?$allocator@D@2@@std@@AEAV?$set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V
>        ?$allocator@D@2@@std@@@2@@5@@Z)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          X509Certificate.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "OPENSSL_sk_value" in Funktion ""public: void __cdecl Poco::Crypto::X509Certificate::extractNames(class std::basic_string<char,struct std::char_
>        traits<char>,class std::allocator<char> > &,class std::set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class
>        std::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)const " (?extractNames@X509Certificate@Crypto@Poco@@QEBAXAEAV?$basic_string@DU?$char_trai
>        ts@D@std@@V?$allocator@D@2@@std@@AEAV?$set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@
>        @V?$allocator@D@2@@std@@@2@@5@@Z)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          X509Certificate.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "X509_getm_notBefore" in Funktion ""public: class Poco::DateTime __cdecl Poco::Crypto::X509Certificate::validFrom(void)const " (?validFrom@X509C
>        ertificate@Crypto@Poco@@QEBA?AVDateTime@3@XZ)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          X509Certificate.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "X509_getm_notAfter" in Funktion ""public: class Poco::DateTime __cdecl Poco::Crypto::X509Certificate::expiresOn(void)const " (?expiresOn@X509Ce
>        rtificate@Crypto@Poco@@QEBA?AVDateTime@3@XZ)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          X509Certificate.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "X509_up_ref" in Funktion ""public: __cdecl Poco::Crypto::X509Certificate::X509Certificate(struct x509_st *,bool)" (??0X509Certificate@Crypto@Po
>        co@@QEAA@PEAUx509_st@@_N@Z)". [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]
>          ..\bin64\PocoCrypto64.dll : fatal error LNK1120: 11 nicht aufgel÷ste Externe [D:\Projects\Application\C++\Includes\Poco\build\poco-1.7.8p3-all\Crypto\Crypto_x64_vs150.vcxproj]

Any help is appreciated!

**Comment by zosrothko** [comment]
Works for me with 
```
C:\Users\fandre\Documents\git\poco-poco-1.7.8p3-release>set inc
include=C:\OpenSSL-Win64\include
C:\Users\fandre\Documents\git\poco-poco-1.7.8p3-release>set lib
lib=C:\OpenSSL-Win64;C:\OpenSSL-Win64\lib;C:\OpenSSL-Win64\lib\VC
```
Could you display your environement variables: LIB & INCLUDE?

**Comment by TeodorStamenov** [comment]
I have the same problem as `sekcheong`. Exactly the same settings, only Vsual Studio toolset version is 2015.

**Comment by zosrothko** [comment]
As a bypass, you can also use the NuGet package [Pocoproject.poco.vs140](https://www.nuget.org/packages?q=pocoproject)

**Comment by zosrothko** [comment]
@TeodorStamenov Could you display your environement variables: LIB & INCLUDE?

**Comment by zosrothko** [comment]
WIth those settings
```
include=C:\OpenSSL-Win64\include
lib=C:\OpenSSL-Win64;C:\OpenSSL-Win64\lib;C:\OpenSSL-Win64\lib\VC
```
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++ Building [Crypto_x64_vs150.vcxproj]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  CipherFactory.cpp
  CipherImpl.cpp
  CipherKey.cpp
  CipherKeyImpl.cpp
  DigestEngine.cpp
  OpenSSLInitializer.cpp
  RSACipherImpl.cpp
  RSADigestEngine.cpp
  RSAKey.cpp
  RSAKeyImpl.cpp
  X509Certificate.cpp
  Génération de code en cours...
     CrÚation de la bibliothÞque ..\lib64\PocoCrypto.lib et de l'objet ..\lib64\PocoCrypto.exp
  Crypto_x64_vs150.vcxproj -> C:\Users\fandre\Documents\git\poco-poco-1.7.8p3-release\Crypto\..\bin64\PocoCrypto64.dll
```
