### ISSUE TITLE
Connect Redis server with password field

### ISSUE THREAD

**Issue by kapcino** [pocoproject/poco#1824]
@fbraem Can I specify a password to connect redis server?

I only find the host and port fields in Client class, how should I do when I connect a server requires password?

Thanks!

Update: Just find AUTH command, seems we can send AUTH with password after connect? I will try this method.

**Comment by fbraem** [comment]
The AUTH command is indeed the solution for this.

**Comment by kapcino** [comment]
Yeah, it works, thanks again @fbraem!
