### ISSUE TITLE
Exception is thrown when trying to create a localdatetime from an epoch timestamp

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1829]
Hi all,
I'm trying to create a localdatetime form an epoch time that I get from a server. I use the following code:

```
	Timestamp ts = Timestamp::fromEpochTime(epochTime);
	LocalDateTime ldt(ts);
```

epochtime is a time_t and has the value 1501165748406  which is a valid epoch value.
By using Pocoexception I get the following message:
 **cannot get local time**
 **>= 1 && month <= 12 in file "src\DateTime.cpp", line 205**

I also tried the following:
```
        Timestamp ts = Timestamp::fromEpochTime(epochTime);
	DateTime dt(ts);
	LocalDateTime ldt(dt);
```
But I got the same error.

What I have done wrong? Is there anything else I can do to achieve the same thing?

**Comment by micheleselea** [comment]
I think epochTime you are using for creating Timestamp should be in seconds not milliseconds

**Comment by micheleselea** [comment]
if you have milliseconds epoch time (and you need milliseconds precision) you can use it as is
`Timestamp ts(epochMilliseconds*1000);`

**Comment by dk1301** [comment]
Thanks it solved the problem.
