### ISSUE TITLE
Linking Poco into Visual C++ project interferes with Windows Base API functions

### ISSUE THREAD

**Issue by jonpeachey** [pocoproject/poco#1830]
All of my Windows Base API functions are no longer found when linking Poco into my project.

Error	34	error C3861: 'CreateFile': identifier not found
Error	37	error C2039: 'GetUserName' : is not a member of '`global namespace''
Error	38	error C3861: 'GetUserName': identifier not found
Error	39	error C3861: 'OpenEvent': identifier not found
Error	40	error C2039: 'GetComputerName' : is not a member of '`global namespace''
Error	41	error C3861: 'GetComputerName': identifier not found
Error	42	error C3861: 'CreateFile': identifier not found
Error	43	error C3861: 'CreateEvent': identifier not found

etc

Obviously it's a configuration issue, but I'm not sure where to start.

Thanks!!

**Comment by aleks-f** [comment]
It's a compile (not link), problem. It looks like your environment does not have proper paths to headers. It is hard to tell more from what you have provided, but I suspect it has nothing to do with poco.

**Comment by aleks-f** [comment]
possible also that you are defining something in your project that prevents the right version of the functions to be seen in headers.

**Comment by jonpeachey** [comment]
Thanks @aleks-f.  These errors only started happening once I included Poco in my project.  Might it have something to do with the order of the includes?

**Comment by roycepipkins** [comment]
Could it just be that you need to define POCO_NO_UNWINDOWS in the project
properties?

**Comment by aleks-f** [comment]
Could be many things. The best way to find out is to create a [SSCE](http://sscce.org/) that reproduces it. That will make it easy to find where the problem is and you may even find it yourself while doing it.

**Comment by jonpeachey** [comment]
@roycepipkins - Yes! Thank you! I knew I was missing something simple like that.

@aleks-f -thanks for you help as well!
