### ISSUE TITLE
POCO server TCP SYN/ACK response?

### ISSUE THREAD

**Issue by htartisan** [pocoproject/poco#1831]
I used the Poco library to create an HTTP server. There is a 3rd party client that is sending a TCP "SYN" message to my server. How can I get the server to respond with a TCP "SYN-ACK" ?

**Comment by aleks-f** [comment]
Somewhat strange question. You are using HTTP, which is not concerned with such things as TCP SYN/ACK - that is taken care of by the underlying TCP layer.

Please clarify what exactly are you trying to achieve.

**Comment by micheleselea** [comment]
@htartisan keep in mind that SYN-ACK is the procedure TCP use to open a connection, so it's automatically handled by accept on socket...so as aleks said I think you are talking about a low level packet tcp handling that you don't have to care about with poco tcp or http servers
