### ISSUE TITLE
Visual Studio 2008 cannot find stdint.h

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [pocoproject/poco#1834]
I'm using `poco-1.7.8p3` and Visual Studio 2008. I've tried compiling the Poco Libraries with the shipped `build_vs90.cmd` but the XML module results in an error (sorry, some parts are in german):

```
1>c:\users\...\documents\visual studio 2008\projects\...\poco-1.7.8p3\xml\src\siphash.h(79) : fatal error C1083: Datei (Include) kann nicht geöffnet werden: "stdint.h": No such file or directory
```

After some research, I've found out that the compiler that is bundled with VS2008 does not support the C99 file `stdint.h` which gets included in the file `XML\src\siphash.h`.

I've fixed my local version by adding a `stdint.h`-file (https://stackoverflow.com/a/126285) and making it available to the VS-project (`XML/XML_vs90.vcproj`):

```patch
 XML/XML_vs90.vcproj | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/XML/XML_vs90.vcproj b/XML/XML_vs90.vcproj
index de9d41470..742805a22 100644
--- a/XML/XML_vs90.vcproj
+++ b/XML/XML_vs90.vcproj
@@ -393,6 +393,8 @@
 			<Filter
 				Name="Header Files">
 				<File
+					RelativePath=".\include\Poco\XML\stdint.h"/>
+				<File
 					RelativePath=".\include\Poco\XML\Content.h"/>
 				<File
 					RelativePath=".\include\Poco\XML\Name.h"/>
```

I'm wondering if there is a better way to fix that, maybe a fix for all users? Thanks in advance!

**Comment by aleks-f** [comment]
Thanks, just putting the file there should take care of the problem - no need to modify the project. I don't have the 2008 handy at the moment but will check soon.
