### ISSUE TITLE
Unused parameter warnings

### ISSUE THREAD

**Issue by hakan-akan** [pocoproject/poco#1839]
Can we do something about unused parameters? There are too many of them. (More than 100 warnings generated on my build.) A few examples of source files with many warnings are, DefaultHandler.cpp, XMLWriter.cpp, TextEncoding, etc.

I personally like the 
void f(int *ptr) {
  (void) ptr;
}

Or something like Q_UNUSED(x) macro can be defined where macro defined as

#if defined(Q_CC_RVCT)
template <typename T>
inline void qUnused(T &x) { (void)x; }
#define Q_UNUSED(x) qUnused(x);
#else
#define Q_UNUSED(x) (void)x;
#endif

Maybe even something line this 

template<class ... Ts>
inline void unused(Ts ... ) { }
 
void f(int *p, bool b, const int &k)
{
    unused(p, b, k);
}

**Comment by aleks-f** [comment]
There's [POCO_UNUSED](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Platform.h#L257). Scratch your itch and send a pull :)

**Comment by hakan-akan** [comment]
Fair enough. :)

**Comment by lakshayg** [comment]
Has this issue been resolved? I could find only 2 unused functions when compiling with -Wunused.

**Comment by aleks-f** [comment]
no, see my comment to your pull

**Comment by hakan-akan** [comment]
To my taste POCO_UNUSED is too ugly. I'd rather have something less invasive. Especially the fact that it pollutes the function signature is irksome to me.  

For example,
void f(int POCO_UNUSED blah) // Instead of this 
{
}

void f(int blah)
{
POCO_UNUSED blah; // I would rather have but this but it does not silence warnings. (I use Qt mingw )
(void) blah; //This does silence warnings
}
