### ISSUE TITLE
Issues with Poco HTTPClientSession on ChromeOS (epoll queue not created)

### ISSUE THREAD

**Issue by AbhinavBansal** [pocoproject/poco#1840]
I have built Poco for ChromeOS using the config file: [link](https://github.com/pocoproject/poco/blob/develop/build/config/NaCl-x86_64
)
Most of the regular utilities work such as Foundation, JSON, Crypto etc. However most of the network level stuff is not working. Any help or pointers to fix this will be greatly appreciated..

A simple HTTPClientSession API is returning: `I/O error. 38: Can't create epoll queue`.. SYN packet is sent out and ACK is received but next packet never gets out.

```           
                Poco::URI uri("http://www.example.com");
                Poco::Net::HTTPClientSession session(uri.getHost(), uri.getPort());
                Poco::Net::HTTPRequest req(Poco::Net::HTTPRequest::HTTP_GET, uri.getPathAndQuery(), Poco::Net::HTTPMessage::HTTP_1_1);
                session.sendRequest(req); 
                Poco::Net::HTTPResponse res;
                std::istream& is = session.receiveResponse(res);
```

If I use socket API from sys/socket.h, it appears to work fine. If I use `Poco::Net::SocketAddress`, I see the request completing but the response not getting printed on screen using std::cout  and seems to be stuck in some internal buffer

```
        Poco::Net::SocketAddress sa("www.example.com", 80);
        Poco::Net::StreamSocket socket(sa);
        Poco::Net::SocketStream strx(socket);
        strx << "GET / HTTP/1.1\r\nHost: www.example.com\r\n\r\n";
        strx.flush();
        Poco::StreamCopier::copyStream(strx, std::cout);

```

**Comment by AbhinavBansal** [comment]
If I disable DPOCO_HAVE_FD_EPOLL, I get a `Net Exception. Protocol not available`

**Comment by RangelReale** [comment]
Sockets don't work on NaCl, you are supposed to use NaCl's own [http request library](https://developer.chrome.com/native-client/pepper_stable/cpp/classpp_1_1_u_r_l_loader) to do http requests.

**Comment by AbhinavBansal** [comment]
Hi @RangelReale , Thanks for replying. There are few things which definitely work, for instance, traditional socket API `socket(AF_INET , SOCK_STREAM , 0);` does work and I am able to read/write fine. W.r.t to POCO, DNS resolution works fine `Poco::Net::DNS::hostByName`. 

Even `Poco::Net::StreamSocket` also works fine, however it doesn't copy the response buffer adequately to my output stream until some exception is thrown.

**Comment by RangelReale** [comment]
My ChromeOS project was abandoned so it is more than 1 year since I tried it, but I remember that it was not possible to make HTTP connections directly from the socket, only using the PPAPI classes. But I really don't remeber why.
Some things may have changed in this time, but I'm really not updated on it.
