### ISSUE TITLE
Multithreaded websocket server using Poco

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1841]
Hi all,
I have created an app that implements a websocket server in c++ base on the poco example, which communicates with an web-based front-end. So the front end gives requests , they are received form the server , some calculations are done and then the server responds with the relevant answer to the request.
This works so far fine. 
However I'd like to add the functionality that the web interface to be able to stop these ongoing calculation wheneve the user wants.In my opinion the only way to achieve that is to create a multihtreaded websocket server that is capable of managing multiple requests and the main thread to be informed whenever a stop request has been arrived.
Since I'm quite new in poco multithreading and find it a little bit confusing on concluding what implementation suits my needs e.x threadpool , taskmanager or events, I'd like to ask first of all if this is possible and what is according to your opinion the safest way to begin with my implementation?
A simple example would be more than helpful.

Thanks in advance.

**Comment by micheleselea** [comment]
so you have a main thread that have to be informed of something happen on the websocket server side? If this is the scope you can use delegate or notification center to make websocket thread inform the main that something happen... but I'm not sure if I understand what you need

**Comment by dk1301** [comment]
Thanks for the initial answer in case I have more question regarding the implementation I'll open a new issue
