### ISSUE TITLE
Store pthread_* return values in Event_POSIX usages that may throw exceptions

### ISSUE THREAD

**Issue by dirvens** [pocoproject/poco#1853]
In order to assist with debugging, it would be helpful in Event_POSIX if calls to pthread_* functions that are used in if conditions, that the return values were stored as a local variable. For example, in Event_POSIX, something like the following may be useful:

`inline void EventImpl::setImpl()
{
	int error = 0;
	if ((error = pthread_mutex_lock(&_mutex)))
		throw SystemException("cannot signal event (lock)");
	_state = true;
	if ((error = pthread_cond_broadcast(&_cond)))
	{
		pthread_mutex_unlock(&_mutex);
		throw SystemException("cannot signal event");
	}
	pthread_mutex_unlock(&_mutex);
}`

If in the debugger we can see the error value from pthread_mutex_lock or pthread_cond_broadcast, that may help debug exceptions.

**Comment by aleks-f** [comment]
In Poco 2.0, events will be using [std::condition_variable](https://github.com/pocoproject/poco/blob/c%2B%2B11/Foundation/include/Poco/Event.h).
