### ISSUE TITLE
Poco::JSON::Array is no array for Poco::Dynamic::Var

### ISSUE THREAD

**Issue by JoshuaBehrens** [pocoproject/poco#1860]
I parsed JSON and realized that `Poco::Dynamic::Var<Poco::JSON::Array>::isArray` evaluates to false. I expected it to return true.

Implementation that results to the unexpected behaviour. https://github.com/pocoproject/poco/blob/8392544e83e1ee68e873e7af284b5091ff4bbe3a/JSON/include/Poco/JSON/Array.h#L500

Sample code to reproduce:
```c++
Poco::JSON::Array arr;
arr.add(1); // make it non empty
Poco::Dynamic::Var(arr).isArray();
```
or with the parser:
```c++
Poco::JSON::Parser().parse("[1]").isArray()
```

If this is expected behaviour can I get an explanation why Poco::JSON::Array is interpreted as no array?

**Comment by aleks-f** [comment]
It is expected for the time being because under the hood arrays and objects are pointers; will be fixed.

**Comment by JoshuaBehrens** [comment]
My current workaround is
```c++
Poco::JSON::Parser().parse("[1]").type() == typeid(Poco::JSON::Array::Ptr)
```
