### ISSUE TITLE
Catch Timeout exception in Poco::Net::SecureSocketImpl::mustRetry

### ISSUE THREAD

**Issue by danjal** [pocoproject/poco#1867]
I am using Poco 1.7.7.
I am using the Poco::Net::HTTPServer with a RequestHandlerFactory over a Poco::Net::SecureServerSocket.

When browsing my web-server over HTTPS, I sometimes get a Poco::Exception Timeout and my server crashes.

I have been trying to find out where the exception is thrown, and it is in Poco::Net::SecureSocketImpl::mustRetry when dealing with SSL_ERROR_WANT_READ.

I can reproduce the exception by having Fiddler activated and doing request over HTTPS. The request works fine, I get a correct response, but after 2-3 minutes, the timeout exception appears. This exception also appears when the web-server and browser are on different networks (VPN).

How can I catch this exception in my web-server, so it does not crash?

**Comment by aleks-f** [comment]
See "Thread Error Handling" in [Multithreading](https://pocoproject.org/slides/130-Threads.pdf)
