### ISSUE TITLE
How to make application compatible to future versions of openssl?

### ISSUE THREAD

**Issue by danjal** [pocoproject/poco#1868]
When cross-compiling the Poco project (1.7.7) for Raspberry Pi, I added these lines to the CMakeLists.txt, regarding Openssl:
```
set(CMAKE_TOOLCHAIN_FILE /home/armsdk/projects/platforms/RPi/Toolchain-RPi.cmake)
set(OPENSSL_SSL_LIBRARY /home/armsdk/projects/platforms/RPi/libForLinking/usr/lib/arm-linux-gnueabihf/libssl.so)
set(OPENSSL_LIBRARIES /home/armsdk/projects/platforms/RPi/libForLinking/usr/lib/arm-linux-gnueabihf/libssl.so)
set(OPENSSL_CRYPTO_LIBRARY /home/armsdk/projects/platforms/RPi/libForLinking/usr/lib/arm-linux-gnueabihf/libcrypto.so)
```
The libssl.so is a symbolic link pointing to libssl.so.1.0.0

And in my main project that is using the poco-libraries, I linked to Openssl like this:
set_target_properties(SSL10 PROPERTIES IMPORTED_LOCATION "/home/armsdk/projects/platforms/RPi/libForLinking/usr/lib/arm-linux-gnueabihf/libssl.so")

Now this has been working fine on the Raspbian Jessie.

But on the newest Raspbian Stretch, my application complains, because it wants libssl.so.1.0.0
The Raspbian Stretch does not have libssl.so.1.0.0 – only libssl.so.1.0.2 and libssl.so.1.1

So have do I make my application compatible with Raspbian Jessie and Stretch?
Is the only solution to use static linking - linking to libssl.a?

**Comment by aleks-f** [comment]
> Is the only solution to use static linking - linking to libssl.a?

From your description of the problem that's what it looks like; a RPi forum is probably a better place to ask.
