### ISSUE TITLE
Poco::Data::ODBC::SQLDriverConnect fails on Mac OS X

### ISSUE THREAD

**Issue by JiekeZhu** [pocoproject/poco#1869]
Hey guys,
Have you ever used Poco ODBC to connect Sql Server on Mac OS X ?  Currently I can't connect to my remote Sql Server with Poco Data ODBC library on Mac OS X.
Everything goes well on Windows. Now I'm trying to make it work on Mac OS X so that we can develop at the same time even on two different systems.
I use Visual Studio Code + CMake on Mac OS X, mostly I work on Windows with Visual Studio.
With the CMake and CMake Tools extensions from Visual Studio Code Extension Marketpalce, It's really convenient to build Poco libraries and run the test suites just by using CMake:Build /CMake: Select a Target to Debug commands.
However, you just can't figure it out if you don't knonw how the whole system is going on. 
After got familiar with CMake, learned how to build and debug with VSCode, install and config unixODBC/FreeTDS ... and it still failed when calling Poco::Data::ODBC::SQLDriverConnect in SessionImpl::open method. I'm exhausted.

**Anyone, any advise please! Thanks in advance.**

The failed connectiong string is "DRIVER=FreeTDS;SERVERNAME=MSSqlServerDB0;UID=userId;PWD=XXXX;DATABASE=Experimental;TDS_Version=8.0;Port=1433;"

"DRIVER=FreeTDS;SERVER=X.X.X.X;UID=sc;PWD=XXXX;DATABASE=Experimental;TDS_Version=8.0;Port=1433;"
unixODBC and FreeTDS are configured and tested successfully as "Troubleshooting ODBC connections" says on http://www.freetds.org/userguide/odbcdiagnose.htm.
Maybe I'm not using the VSCode CMake building system correctly because I find the __APPLE__ preprocessor macro has not been defined while building and I have to add_definitions(-D__APPLE__) in CMakelist.txt.

Thanks.  TT_TT

**Comment by aleks-f** [comment]
ODBC was fully tested only on windows, other platforms may be "hit and miss". That said, I do remember majority of MS SQL/FreeTDS tests passing on Linux and Mac long time ago - you may want to experiment a bit with the [testsuite](https://github.com/pocoproject/poco/blob/develop/Data/ODBC/testsuite/src/ODBCSQLServerTest.cpp#L54).

**Comment by JiekeZhu** [comment]
Thanks for the quick response.
After spending another day on this problem, I decide to give up for now. I guess it's because I'm using **MS SQL Server 2016** and the environment is yet not ready.
By following [](http://www.freetds.org/userguide/choosingtdsprotocol.htm) I tried all the FreeTDS versions, all run into **Native Error Code = 20013**.

Microsoft does provide the Microsoft ODBC Driver 13.1 for SQL Server for MacOS.
[](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server)
[](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns)
OS X 10.11 (El Capitan) and macOS 10.12 (Sierra)
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
brew install --no-sandbox msodbcsql mssql-tools

Add it works as command line tool. But SQLDriverConnect returns **Native Error Code = 18456**, when [Driver=ODBC Driver 13 for SQL Server;]. I think it's a little bit close to the answer even though problem is not solved.

So, I give up. Stay on Windows. Do what I can do now.

Again, thanks for the nice work, POCO is great.

**Comment by JiekeZhu** [comment]
Problem has not been solved. So I reopen it.
: )
