### ISSUE TITLE
Portability: all public Poco API  integral parameter should use Poco integral type

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#1870]
Hello

This is a portability issue. Below is resume the length of all native integral types defined in C/C++
```
Type           ILP64   LP64   LLP64
char              8      8       8
short            16     16      16
int              64     32      32
long             64     64      32
long long        64     64      64
pointer          64     64      64
```
All modern Unix compilers and macOS compilers are following the LP64 mode while VisualStudio is following the LLP64 mode. Thus there is a portability issue for the `long` type.  

In order to insure a full portabibility of application using Poco, this issue requests that the integral parameters of all public Poco's API use `only` the corresponding Poco integral types as defined in `Poco/Types.h`

**Comment by zosrothko** [comment]
@obiltschnig @aleks-f  any comment on this issue?

**Comment by aleks-f** [comment]
noble goal, but not small amount of work. FWIW, Poco types are now [aligned with std types](https://github.com/pocoproject/poco/issues/1147) in develop
