### ISSUE TITLE
compile source for android using CMake Error

### ISSUE THREAD

**Issue by lijiayan2015** [pocoproject/poco#1873]
when i compile c++ for android with Cmake on windows,the error:
**CMAKE_SYSTEM_NAME is 'Android' but 'NVIDIA Nsight Tegra Visual Studio Edition' is not installed.**
my cmake params:
         **cmake -DANDROID_NATIVE_API_LEVEL=16 \
	  -DCMAKE_SYSTEM_VERSION=21 \
	  -DCMAKE_TOOLCHAIN_FILE=E:/sdk/android-ndk-r13-windows-x86_64/android-cmake-master/android.toolchain.cmake \
         -DANDROID_NDK=E:/sdk/android-ndk-r13-windows-x86_64/android-ndk-r13 \
         -DCMAKE_BUILD_TYPE=Release \
         -DANDROID_ABI="armeabi-v7a" \
	 -DANDROID_PLATFORM=android-21 \
	 -DANDROID_ARM_NEON=TRUE \
	 -DCMAKE_ANDROID_API=2
         cmake --build .**

help me and tell me what i should to do ？thanks！！
if you have a solution for the error，please email me：lijiayan_mail@163.com.

**Comment by RangelReale** [comment]
Never heard of this NVIDIA Nsight before, there must be something wrong with your CMake configuration, or something changed too much on the android toolchain.
