### ISSUE TITLE
ODBC Session cannot reconnect

### ISSUE THREAD

**Issue by mtangoo** [pocoproject/poco#1875]
Hi,
am using ODBC to connect on remote server via SSH Tunnel. After sometime connection times out. Each time I try to reconnect I get error below. I have tried `Session::reconnect()` and also close and open but they all give me same error. I feel that it is a bug but am not sure if it is a problem in UnixODBC, MariaDB or Poco so I started posting here

All I want to do is reconnect the session without re-entering login credentials.

Thanks for great library!

```
Connection:Not applicable
Server:Not applicable
===========================
ODBC Diagnostic record #1:
===========================
SQLSTATE = 08002
Native Error Code = 0
[unixODBC][Driver Manager]Connection name in use

===========================
ODBC Diagnostic record #2:
===========================
SQLSTATE = 00000
Native Error Code = 0
[ma-3.0.0]


```

**Comment by aleks-f** [comment]
To determine whether this is a poco problem, i'd recommend enabling [ODBC tracing](http://www.easysoft.com/support/kb/kb00945.html) and see if there is anything suspicious happening there. Even better would be to try to reproduce the problem with anther tool/library and se if there is a difference in ODBC API calls compared to poco.

**Comment by mtangoo** [comment]
Hi @aleks-f ,
Do you have any suggestion for a tool that I can use to connect and reconnect?
I'm not sure if [SOCI](https://github.com/SOCI/soci) supports that but I will find time to have a look at it. I will also enable trace to see if I can find any trail!

**Comment by mtangoo** [comment]
I have tried the link put there and no trace was actually recorded. I will try to find if any tool is available to test. So far I have found none.

One more question, I tried to read the error description (and I will paste them in next comment), but I cannot understand which one affects this POCO reconnect. Could, when you find time, explain in Poco context and reconnect specifically what does the error mean?

Thanks

**Comment by mtangoo** [comment]
**SQL STATE:** 08002

**Error:**

Connection name in use

**Can be returned from**

**SQLBrowseConnect** : (DM) The specified connection had already been used to establish a connection with a data source, and the connection was open.

**SQLConnect** (DM) The specified ConnectionHandle  had already been used to establish a connection with a data source, and  the connection was still open or the user was browsing for a  connection.

**SQLDriverConnect** (DM) The specified ConnectionHandle had already been used to establish a connection with a data source, and the connection was still open.

**SQLSetConnectAttr** The Attribute argument was SQL_ATTR_ODBC_CURSORS, and the driver was already connected to the data source.

**Comment by aleks-f** [comment]
Hard to tell which one exactly affects the reconnect, you would need a trace log for that. Since there is no native error, then it is either connection manager poco not cleaning up the state properly on connection drop. Last but not least, there's the possibility that you are not doing something right in your application code.

**Comment by mtangoo** [comment]
Ok so let me post my code so that we are sure its not me doing a wrong thing

```cpp
if(m_session)
	m_session = nullptr; //m_session is std::shared_ptr<Poco::Data::Session>

try
{
	m_connString =  BuildConnString(); // m_connString is std::string
	m_session = std::shared_ptr<Poco::Data::Session>(new Poco::Data::Session("ODBC", m_connString));
	m_session->setConnectionTimeout(86400); //1day TDL make it configurable
}
catch(Poco::Exception &e)
{
	//log errors
	m_session = nullptr;
}
```

and in reconnecting I simply do 

```cpp
if(m_session)
	m_session->reconnect();
```

**Comment by mtangoo** [comment]
Assuming the code is correct, I was looking at where the reconnect is taking place. I observed few thing that I don't understand
1. In Data/src/Session.cpp reconnect is calling close() and open() respectively but neither in that file nor in other (Data/src/SessionImpl.cpp, Data/ODBC/SessionImpl.cpp) is the two functions (open and close) implemented. Where exactly are they implemented?

2. In Data/ODBC/SessionImpl.cpp, I cannot see any implementation of reconnect, so my first guess is, it is either implemented somewhere else I could not see and from there it calls ODBC driver or it is not implemented for ODBC at all and the generic implementation accidentally tries to do something it should not. I guess the first is right and the latter is wrong but I definitely don't know what is true.

Finally is there anywhere where the ODBC (or Data library) is explained as to how it works together and how sources are organized? They are neat as they are but it seems as newbee  to Poco internals am missing something basic.

Thanks for your time.

**Comment by aleks-f** [comment]
1. [ODBC::SessionImpl::close()](https://github.com/pocoproject/poco/blob/poco-1.7.8/Data/ODBC/src/SessionImpl.cpp#L382) is, of course, implemented; there have been some [fixes](https://github.com/pocoproject/poco/commit/e144a1ffbc2166f8943bd9b17293d927fe98cfa3) that have not yet been released and could be causing this problem

2. reconnect() is implemented in [Poco::Data::SessionImpl](https://github.com/pocoproject/poco/blob/poco-1.7.8/Data/src/SessionImpl.cpp#L37)

**Comment by mtangoo** [comment]
>ODBC::SessionImpl::close() is, of course, implemented; 

Mh! I think it slipped off my Ctrl+F in my editor.  What about open()? as of 2. I saw it!

>there have been some fixes that have not yet been released and could be causing this problem

I will be happy to test them (and since my app is in development I would be happy to test bleeding edge version of the library)

Thank you!

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/blob/poco-1.7.8/Data/ODBC/src/SessionImpl.cpp#L96

**Comment by mtangoo** [comment]
let me test. Tomorrow morning I will recompile and check if the problem is gone.
Thanks!

**Comment by mtangoo** [comment]
>https://github.com/pocoproject/poco/blob/poco-1.7.8/Data/ODBC/src/SessionImpl.cpp#L96

Thanks. Any Plan to release those fixes?

**Comment by mtangoo** [comment]
>Thanks. Any Plan to release those fixes?
Sorry reading again I see the link to commit. 
Let me test it
