### ISSUE TITLE
Add OrangePi on build support

### ISSUE THREAD

**Issue by uilianries** [pocoproject/poco#1878]
**What?**  
Add configuration file to fill Make settings for OrangePi.

**Why?**  
[OrangePi](http://www.orangepi.org/) is another embedded board flavor, as BeagleBone and RaspberryPi, very cheap and perform very well for maker projects. Poco could run well on this embedded device.

**How?**  
When build Poco, the definition `POCO_CONFIG=OrangePi` should be supported as well.

**Comment by obiltschnig** [comment]
The problem here is, the OrangePi can run different operating systems (various Linux distros, Android), each requiring a different build configuration file. So there cannot be a single OrangePi config. For Debian or Ubuntu, the standard Linux build configuration will work.

**Comment by uilianries** [comment]
I agree. So, by default we can use Linux, as done for BeagleBone and RaspberryPi.

**Comment by uilianries** [comment]
Thanks!
