### ISSUE TITLE
FTPClientSession::close() error?

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1880]
I probably found a problem in close function of FTPClientSession, here is the function:

```
void FTPClientSession::close()
{
	logout();
	_pControlSocket->close();
	delete _pControlSocket;
	_pControlSocket = 0;
	_serverReady = false;
}
```
it's called in destructor of FTPClientSession as:
```
	try
	{
		close();
	}
	catch (...) 
	{
	}
```
So it's safe: the problem here is in the logout function inside , because it does something like
```
		try { endTransfer(); }
		catch (...) { }
		std::string response;
		sendCommand("QUIT", response);
		_isLoggedIn = false;
```
If, as in my environment, the sendCommand throw exception because socket is broken or whatever, you end up in FTPClientSession::close() exit too early without do the close of the FTP control socket.
Probably in close() function logout should be under try catch

**Comment by micheleselea** [comment]
no probably we shoud try catch the `sendCommand("QUIT", response);` otherwise _isLoggedIn remain true, or move `_isLoggedIn = false;` before

**Comment by micheleselea** [comment]
I changed the code moving` _isLoggedIn = false;` before `sendCommand("QUIT", response);` and now if I call .logout() and .close() of my FTPClient Socket the behavior is ok.
My problem before (especially on Linux) was that with unstable connection I had a lots of CLOSE_WAIT connection that could end in finish total number of file you can open

**Comment by aleks-f** [comment]
@micheleselea can you send a pull for this?

**Comment by micheleselea** [comment]
On develop release should be already fixed with last send I did

**Comment by micheleselea** [comment]
Code is now
```
void FTPClientSession::logout()
{
	if (!isOpen())
		throw FTPException("Connection is closed.");

	if (_isLoggedIn)
	{
		try { endTransfer(); }
		catch (...) { }
		_isLoggedIn = false;
		std::string response;		
		sendCommand("QUIT", response);		
	}
}


void FTPClientSession::close()
{
	try { logout(); }
	catch(...){ }
	_serverReady = false;
	if (_pControlSocket)
	{
		_pControlSocket->close();
		delete _pControlSocket;
		_pControlSocket = 0;
	}
}
```
So logout put false the variable before the instruction that can throw, and logout itself is try catched in close function
