### ISSUE TITLE
HttpclientSession couldn't detect as "HTTP" protocol by wireshark

### ISSUE THREAD

**Issue by whidbey** [pocoproject/poco#1881]
here is the code:
        HTTPClientSession session("localhost");
	session.setKeepAlive(true);
	session.setPort(8086);
	HTTPRequest request(HTTPRequest::HTTP_POST, "/query");
	 
	HTTPResponse response;
	request.setHost("localhost",8086);
	request.setContentType("application/x-www-form-urlencoded");
	request.set("User-Agent","curl/7.29.0");
	request.set("Accept","*/*");
	request.setKeepAlive(true); 
	std::string body2;
	std::string rev="";
	std::string body="q=create database ooo";
	Poco::URI::encode(body,rev,body2);

	request.setContentLength( body2.length() );
	std::ostream& send = session.sendRequest(request);
	 
	send << body2 <<std::flush; 
	std::cout << session.receiveResponse(response).rdbuf();

here is the result response:

POST /query HTTP/1.0
Host: localhost:8086
Content-Type: application/x-www-form-urlencoded
User-Agent: curl/7.29.0
Accept: */*
Connection: Keep-Alive
Content-Length: 25

q=create%20database%20oooHTTP/1.0 200 OK
Connection: close
Content-Type: application/json
Request-Id: 625ad389-95c1-11e7-809c-000000000000
X-Influxdb-Version: 1.2.2
Date: Sun, 10 Sep 2017 00:45:46 GMT

{"results":[{"statement_id":0}]}

yes,is response ok but could not detect as "http" but "tcp" in wireshark.

however.  a curl client could response as "http" and the content is:

POST /query HTTP/1.1
User-Agent: curl/7.29.0
Host: localhost:8086
Accept: */*
Content-Length: 25
Content-Type: application/x-www-form-urlencoded

q=create%20database%20oooHTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Request-Id: 9b15d3a1-95be-11e7-8096-000000000000
X-Influxdb-Version: 1.2.2
Date: Sun, 10 Sep 2017 00:25:53 GMT
Transfer-Encoding: chunked

21
{"results":[{"statement_id":0}]}

0

above code has  a "chunked" flag.

**Comment by obiltschnig** [comment]
You will need to set the HTTP version in your HTTPRequest to HTTP/1.1.

```
HTTPRequest request(HTTPRequest::HTTP_POST, "/query", HTTPMessage::HTTP_1_1);
```

**Comment by whidbey** [comment]
thanks.. I resove it by set Httprequest setVersion function  
powerfull of POCO
