### ISSUE TITLE
TCPServerDispatcher::run() issue

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1884]
I found a possible problem that could end up with unusable tcp server.
In function  `TCPServerDispatcher::run()` the line `std::auto_ptr<TCPServerConnection> pConnection(_pConnectionFactory->createConnection(pCNf->socket()));` create application TCP handler.
If for some reason the creation throw exeption (for example because do something with a broken socket or similar) the thread return in pool and so no problem because try catch is taken but we jump the line 
`--_currentThreads;` so in the end, after some of this issue you will refuse all new connection because in function `void TCPServerDispatcher::enqueue(const StreamSocket& socket)` we check `_currentThreads < _pParams->getMaxThreads()` 
So I think we should put `--_currentThreads;` in a "scoped decrement" class or try catch the createConnection.

**Comment by aleks-f** [comment]
@micheleselea from what I'm reading, the `_currentThreads` is incremented in `beginConnection()`, which is called after successful `pConnection` construction; if `pConnection` construction throws, increment will not happen, so it's ok that decrement does not happen, either.

**Comment by micheleselea** [comment]
I think `_currentThread` is incremented before creating connection so before possible throw of connection constructor...I'll double check it because it was days ago and I can't remember but I end up with no connection possible because `_currentThread` wai not decremented due to operation on socket throw on creating connection. I'll check tomorrow and let you know

**Comment by micheleselea** [comment]
Ok if you look at the code  `_currentThread` is incremented just after  `startWithPriority`.
The problem is in `run()` if line
`std::auto_ptr<TCPServerConnection> pConnection(_pConnectionFactory->createConnection(pCNf->socket()));`
throw exception you will never decrement `_currentThread` so you can wast threads counter.
It's only a "formal" problem, I mean it's enough to say "constructor of connection MUST not throw". We have just to be clear on this. In HttpServer for example there's no problem because the code that do constructor of Http Handler is done inside the try catched run()

**Comment by aleks-f** [comment]
OK, I see that. I was looking at _currentConnections

**Comment by aleks-f** [comment]
here's my fix proposal:

```
λ git diff ../../../Net/include/Poco/Net/TCPServerDispatcher.h
diff --git a/Net/include/Poco/Net/TCPServerDispatcher.h b/Net/include/Poco/Net/TCPServerDispatcher.h
index 3c46d0f26..a755bc019 100644
--- a/Net/include/Poco/Net/TCPServerDispatcher.h
+++ b/Net/include/Poco/Net/TCPServerDispatcher.h
@@ -100,6 +100,30 @@ private:
        TCPServerDispatcher(const TCPServerDispatcher&);
        TCPServerDispatcher& operator = (const TCPServerDispatcher&);

+       class ThreadCountWatcher
+       {
+       public:
+               ThreadCountWatcher(TCPServerDispatcher* pDisp) : _pDisp(pDisp)
+               {
+               }
+
+               ~ThreadCountWatcher()
+               {
+                       FastMutex::ScopedLock lock(_pDisp->_mutex);
+                       if (_pDisp->_currentThreads > 1 && _pDisp->_queue.empty())
+                       {
+                               --_pDisp->_currentThreads;
+                       }
+               }
+
+       private:
+               ThreadCountWatcher();
+               ThreadCountWatcher(const ThreadCountWatcher&);
+               ThreadCountWatcher& operator=(const ThreadCountWatcher&);
+
+               TCPServerDispatcher* _pDisp;
+       };
+
        int _rc;
        TCPServerParams::Ptr _pParams;
        int  _currentThreads;
@@ -112,6 +136,7 @@ private:
        TCPServerConnectionFactory::Ptr _pConnectionFactory;
        Poco::ThreadPool&               _threadPool;
        mutable Poco::FastMutex         _mutex;
+       friend class ThreadCountWatcher;
 };



λ git diff ../../../Net/src/TCPServerDispatcher.cpp
diff --git a/Net/src/TCPServerDispatcher.cpp b/Net/src/TCPServerDispatcher.cpp
index 1c71ee243..fd1737a9e 100644
--- a/Net/src/TCPServerDispatcher.cpp
+++ b/Net/src/TCPServerDispatcher.cpp
@@ -103,6 +103,7 @@ void TCPServerDispatcher::run()

        for (;;)
        {
+               ThreadCountWatcher tcw(this);
                try
                {
                        AutoPtr<Notification> pNf = _queue.waitDequeueNotification(idleTime);
@@ -133,11 +134,7 @@ void TCPServerDispatcher::run()
                }

                FastMutex::ScopedLock lock(_mutex);
-               if (_stopped || (_currentThreads > 1 && _queue.empty()))
-               {
-                       --_currentThreads;
-                       break;
-               }
+               if (_stopped || (_currentThreads > 1 && _queue.empty())) break;
        }
 }
```
//cc @obiltschnig

**Comment by micheleselea** [comment]
I think it's a nice solution
