### ISSUE TITLE
Poco::ZipArchive cannot read Zip files generated by Poco::ZipCompress if there's Zip files inside

### ISSUE THREAD

**Issue by DarioSamo** [pocoproject/poco#1892]
I wrote the following test to help with this.
```
#define POCO_STATIC

#include <fstream>
#include <Poco/Zip/Compress.h>
#include <Poco/Zip/ZipArchive.h>

void generateZip(std::string output_path, bool seekable_out) 
{
	std::ofstream file_stream(output_path, std::ios::out | std::ios::binary);
	Poco::Zip::Compress *zip_compress = new Poco::Zip::Compress(file_stream, seekable_out);
	zip_compress->addFile("poco-poco-1.7.9-release.zip", "poco-poco-1.7.9-release.zip");
	zip_compress->close();
	file_stream.close();
}

void openZip(std::string path) 
{
	std::ifstream inp(path, std::ios::binary);
	Poco::Zip::ZipArchive *zip_archive = new Poco::Zip::ZipArchive(inp);
}

int main(int argc, char *argv[]) 
{
	generateZip("seek-true.zip", true);
	generateZip("seek-false.zip", false);
	openZip("seek-true.zip");
	openZip("seek-false.zip");
	return 0;
}
```

The test does the following:
1. Generate a Zip file with seekableOut set to true with [poco-poco-1.7.9-release.zip](https://github.com/pocoproject/poco/archive/poco-1.7.9-release.zip) inside of it.
2. Generate the same Zip file but with seekableOut set to false.
3. Attempt to open both generated Zip files.

This fails by throwing the exception Poco::DataFormatException("Bad data info header") on Poco::ZipDataInfo when opening "seek-false.zip". (MSVC 2013 x64). "seek-true.zip" opens with no problems.

I can repeat this issue pretty consistently by packing any other Zip files, although there's some odd seemingly random cases where it won't fail. Windows, 7-Zip or WinRAR have no problem opening the file that throws the exception and there's no corruption errors.

While a possible workaround seems fairly obvious, I'm worried this bug could affect other types of files where the header sequence of the Zip appears at random in parts of the file.

**Comment by DarioSamo** [comment]
I've worked around this on the meantime by just using seekableOut on true as the individual files are not large enough to be a problem just yet, but it does mean significantly higher memory usage.

**Comment by aleks-f** [comment]
can't reproduce this (windows/VS 2015/x64/develop branch)

**Comment by DarioSamo** [comment]
Oh sorry, I forgot to mention I tried this with version 1.7.9. I can try it on the development branch and see if the issue has been resolved.
