### ISSUE TITLE
 WebSocketImpl::sendBytes - bug?

### ISSUE THREAD

**Issue by tencek** [pocoproject/poco#1894]
Reading the code of  WebSocket code, I chanced upon this:

https://github.com/pocoproject/poco/blob/d9a6954950d194feb12f3fedef22c529abe84c66/Net/src/WebSocketImpl.cpp#L104

I'm just curious: What happens if the StreamSocket::sendBytes does not send the whole chunk of data in once? The return value is not checked. I would suppose this to be implemented in a do-while loop (which is the way I'm using StreamSocket when implementing data sending).

Or is there some guarantee that all the data are always sent in once? What am I missing?

**Comment by obiltschnig** [comment]
`StreamSocketImpl::sendBytes()` has a loop that guarantees the entire buffer is sent when the socket is blocking. The current WebSocket implementation does not support non-blocking sockets.

**Comment by tencek** [comment]
Thank you, now I see it and understand it.
