### ISSUE TITLE
WebSocket does not allow "not blocking" read

### ISSUE THREAD

**Issue by GalloTeo** [pocoproject/poco#1895]
Hi guys, 
we are still having problems with the SSL stuff and the write retry so i wanted to experiment managing the use of the ssl context and its error. 
I am refering to this error https://github.com/pocoproject/poco/issues/1160
which we think the problem is how poco handle SSL with a single bio. (that is our guess) 

in order to do that i would need to have the socket not blocking in reading, but it seems that socket impl force the flag to true at the connection time and on error. 

i am sure there is a reason for that but i cannot understand it; what is that  ? 
is there a way to use the websocket in non blocking mode ?

**Comment by obiltschnig** [comment]
Currently the WebSocket class does not support non-blocking mode. Supporting it would require a complete re-design of the class. Maybe some time in the future...

**Comment by GalloTeo** [comment]
thank you
