### ISSUE TITLE
Xcode 9 reports many instances of "Possible misuse of comma operator"

### ISSUE THREAD

**Issue by alfeng** [pocoproject/poco#1900]
Building with Xcode 9 reports this warning in 15 places for me, such as line 513 in trees.c:

`if (bits > max_length) bits = max_length, overflow++;`

It appears the code in this case is trying to cap 'bits' to 'max_length' but of course it actually gets set to 'overflow++', which would be a legitimate bug.  This is likely true in all other instances of this warning.

The warnings are mostly in trees.c, but also in deflate.c and pcre_compile.c.

**Comment by obiltschnig** [comment]
These are in included third-party libs (zlib, pcre). The warning can be ignored. The comma operator has the lowest precedence, so the code does the right thing.
