### ISSUE TITLE
Compiling Foundation library with POCO_NO_FPENVIRONMENT in Config.h fails

### ISSUE THREAD

**Issue by treitmayr** [pocoproject/poco#1905]
When compiling the POCO Foundation library with POCO_NO_FPENVIRONMENT set in Config.h (not via configure), then FPEnvironment_C99.cpp is still pulled in. The cause seems to be that in FPEnvironment.cpp the flag POCO_NO_FPENVIRONMENT is not available.

While Poco/Platform.h is included in https://github.com/pocoproject/poco/blob/38c4e35c43a5b377c4e1db1fc1da1dca57c882f8/Foundation/src/FPEnvironment.cpp#L16 , this should be also the case for Poco/Config.h in order to have the flag POCO_NO_FPENVIRONMENT available.

**Comment by aleks-f** [comment]
FPEnvironment.h, which includes Config.h, was included after the check for `POCO_NO_FPENVIRONMENT` for some ancient reasons (Tru64). Moved, should be ok now
/cc @obiltschnig
