### ISSUE TITLE
Unable to receive email message content with MessageHeader

### ISSUE THREAD

**Issue by ZHoscar** [pocoproject/poco#1922]
I can not retrieve content from email with the absence of content-type in the example.
    ///example in the RFC 2882
    ----
    From  : John Doe <jdoe@machine(comment).  example>
   To    : Mary Smith
  
            <mary@example.net>
    Subject     : Saying Hello
    Date  : Fri, 21 Nov 1997 09(comment):   55  :  06 -0600
    Message-ID  : <1234   @   local(blah)  .machine .example>

    This is a message just to say hello.
    So, "Hello".
    ----`

So I can not perform something like this.

    `for ( auto i = messages.begin(); i != messages.begin()+10; ++i )
     {
          MessageHeader header;
          session.retrieveHeader((*i).id, header);
    
          std::cout << "Subject:" << header.get("Subject");
          std::cout << "Content"  << header.get("Content");  
         /// Can't perform the above because there are no "Content:" in the
         /// RFC2822.
     }
    `

And there is no method defined in NameValueCollection.h to deal with situation like this. 
Is there any other way I could retrieve gmail message?

**Comment by aleks-f** [comment]
> Is there any other way I could retrieve gmail message?

yes, with [MailMessage::getContent()](https://github.com/pocoproject/poco/blob/poco-1.7.9/Net/testsuite/src/POP3ClientSessionTest.cpp#L157)

**Comment by ZHoscar** [comment]
Thank you so much.  Solved it!
