### ISSUE TITLE
pd_json.h is missing when installed via CMake in 1.8.0

### ISSUE THREAD

**Issue by bachp** [pocoproject/poco#1923]
The header file is included in `Poco/JSON/ParserImpl.h` but it is not installed when poco is installed. This means projects using the Poco JSON library will not find `pd_json.h`.

I think the best solution would be to move `pd_json.h` into `include/Poco`. As it otherwise might conflict with other versions of `pd_json.h` installed directly into the systems global `include` directory.

@aleks-f What do you think about this proposal?

**Comment by obiltschnig** [comment]
Or maybe we can get rid of the header file dependency through a forward declaration and move `pd_json.h` to `src`?

**Comment by bachp** [comment]
That would be even better :+1:

**Comment by bachp** [comment]
It's fixed on 1.8.0 thanks
