### ISSUE TITLE
TCP Server

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1925]
Hi all, in TcpServer there are code lines:
```
#if defined(POCO_OS_FAMILY_UNIX)
  if (ss.address().family() != AddressFamily::UNIX_LOCAL)
#endif
```
I compiled for linux but I can't compile: so I comment it out because I think it's ok. I do not understand where AddressFamily or UNIX_LOCAL are...

**Comment by aleks-f** [comment]
in [develop](https://github.com/pocoproject/poco/blob/develop/Net/include/Poco/Net/SocketAddress.h#L53) branch. maybe you're mixing develop headers with 1.x sources

**Comment by micheleselea** [comment]
ok probably you are right, I'll check
