### ISSUE TITLE
JSON: stringify serializes doubles with zero fractional part as integers

### ISSUE THREAD

**Issue by pglass** [pocoproject/poco#1927]
The JSON stringify method serializes a double with zero fractional part as an integer (with no fractional part). For example, stringify will convert the double `123.0` to an "integer" representation `123` in the resulting JSON string.

This leads to the following sort of error during deserialization: My code expects a double everywhere but stringify has converted that double to an integer in the serialized JSON string. The JSON Parser sees the integer in the serialized string, so when I try to extract it as a double after parsing, I get a `Bad Cast` exception.

I see this with Poco version `1.7.9` (dynamically linked) installed with brew on OS X (10.12.6).

Some code to demonstrate the issue:

```cpp
#include <iomanip>
#include <iostream>
#include <sstream>
#include <Poco/JSON/Object.h>
#include <Poco/JSON/Parser.h>

void run(double input) {
  std::cout << "Input: " << input << std::endl;

  // serialize the double
  Poco::JSON::Object o;
  o.set("value", input);

  // Here, the double is serialized as an int.
  // For example, 123 instead of 123.0
  std::stringstream ss;
  o.stringify(ss);
  auto json_str = ss.str();
  std::cout << "Serialized: " << json_str << std::endl;

  // Subsequent deserialization that attempts to extract the int as a double
  // results in a bad cast exception.
  Poco::JSON::Parser parser;
  auto var = parser.parse(json_str);
  auto parsed_obj = var.extract<Poco::JSON::Object::Ptr>();

  try {
    double val = parsed_obj->get("value").extract<double>();
    std::cout << "Deserialized: " << val << std::endl;
  } catch (std::exception& e) {
    std::cout << "Exception! " << e.what() << std::endl;
  }

  std::cout << std::endl;
}

int main() {
  // enable sufficient precision to distinguish ints from doubles/floats
  std::cout << std::fixed << std::setprecision(10);
  run(123.1);
  run(123.0);
}
```

This outputs,

```
Input: 123.1000000000
Serialized: {"value":123.1}
Deserialized: 123.1000000000

Input: 123.0000000000
Serialized: {"value":123}
Exception! Bad cast exception
```

**Comment by aleks-f** [comment]
yeah, this is the way double conversion does it - we are using [ToShortest](https://github.com/pocoproject/poco/blob/develop/Foundation/src/NumericString.cpp#L236)

I see where it would make sense to always convert doubes to strings as doubles, even when there's nothing after decimal point. But this will [break](https://github.com/pocoproject/poco/blob/poco-1.7.9/Foundation/testsuite/src/NumberFormatterTest.cpp#L185) existing code depending on that NumberFormatter feature. @obiltschnig ?

**Comment by aleks-f** [comment]
The particular case in this issue I propose to fix by simply appending `.0` to numbers if they have no fractional separator after double-conversion processing -  - it makes sense. The only downside is that we will break some code, but in 2.0 we are breaking code anyway so it is an opportunity to do this right.

**Comment by KartikSoneji** [comment]
Hi, is there any update on the issue?

**Comment by obiltschnig** [comment]
Why not simply use `convert()` instead of `extract()`. If the underlying type is already a `double` this will directly return it. Otherwise it will try to convert.
