### ISSUE TITLE
Verification of SSL Certificate fails with Poco::Net::HTTPRequest on Android OS.

### ISSUE THREAD

**Issue by masapple** [pocoproject/poco#1936]
On Android OS, after generating Context class with the following code, the result of requesting to the server with https, 
"CERTIFICATE_VERIFY_FAILED" is returned as a response from Poco.
In addition, a valid SSL certificate is installed on the destination server.

Code:
<pre>
    HttpManager()
    {
        Poco::Net::initializeSSL();

        Poco::SharedPtr<Poco::Net::InvalidCertificateHandler> certificateHandler = new PrivateCertificateHandler(false);
        Poco::Net::Context::Ptr context = new Poco::Net::Context(Poco::Net::Context::CLIENT_USE,
                     "", "", "", Poco::Net::Context::VERIFY_STRICT, 9, false, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
        Poco::Net::SSLManager::instance().initializeClient(NULL, certificateHandler, context);
    }
</pre>

Output:
<pre>
Poco::Exception.code=0:msg=error:100be07e:SSL routines:ssl3_get_server_certificate:CERTIFICATE_VERIFY_FAILED
</pre>

In addition, as shown below, after setting the path of root certificate to "caLocation" in Poco::Net::Context 
and sending the request to the server at https, a normal response (200) was returned.

Code:
<pre>
    HttpManager()
    {
        Poco::Net::initializeSSL();

        Poco::SharedPtr<Poco::Net::InvalidCertificateHandler> certificateHandler = new PrivateCertificateHandler(false);// Poco::Net::AcceptCertificateHandler(false);
        Poco::Net::Context::Ptr context = new Poco::Net::Context(Poco::Net::Context::CLIENT_USE,
                     "", "", "/storage/emulated/0/hoge/sample.cer", Poco::Net::Context::VERIFY_STRICT, 9, false, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
        Poco::Net::SSLManager::instance().initializeClient(NULL, certificateHandler, context);
    }
</pre>

In the case of Android OS, does SSL certificate validation fail unless "caLocation" is explicitly specified in Poco :: Net :: Context?
Referring to the User Guides and Tutorials of POCO C ++ Libraries, it says that if "caLocation" is empty, OpenSSL certificate will be used.
In Android, does not it work properly?

<pre>
Can be empty if the OpenSSL builtin CA certificates are used
</pre>

In case of iOS, even if the "caLocation" is empty, we confirmed that a normal response (200) is returned by https communication.

Environment:
We checked with the following combination, but the results were all the same.

Case1:
Android OS:6.0
Poco:1.5.0
BoringSSL:6.0.1

Case2:
Android OS:6.0
Poco:1.5.0
BoringSSL:7.1.2

Case3:
Android OS:5.1 and 6.0
Poco:1.5.0
OpenSSL:1.0.2h

**Comment by aleks-f** [comment]
1.5.0 is quite old. can you reproduce this with the most recent release?
