### ISSUE TITLE
Provide some HTML view engine like Rasor used by Asp.net core mvc ?

### ISSUE THREAD

**Issue by JiekeZhu** [pocoproject/poco#1937]
Hi there,
Why not provide some html view engine like Rasor used by Asp.net core mvc ?

I use POCO as my server development tool.
Recently I am learning how to build a website for production and business. 
To find the "best" solution, I have taken a new look at Node.js and Asp.net, and Asp.net core. By the way my main programming languages are C++, C#, Javascript. 
What I've got is that Asp.net core mvc is now at the mature stage and very pure. 

Lots of games' server apps are built with POCO. While comparing POCO with Asp.net core mvc, I find POCO also has got all the same functionalities. Excellent! And the project structures do similar with each other.
But One part is missing: Website. Web pages loading, caching, routing, generating and server-side rendering.

I guess it's not a easy job to implement some module like this. 
I'm just sharing what comes to my mind that I think will make POCO more powerful and complete.

And if there has already been some thing like Rasor to generate website, do share with me. Thanks in advance.

**Comment by aleks-f** [comment]
There's [PageCompiler](https://github.com/pocoproject/poco/tree/develop/PageCompiler).

Personally, I'm not a big fan of "server pages" technologies because they split the client logic between client and server. But, if you are inclined to provide some contributions thereof, feel free to do so :)

**Comment by JiekeZhu** [comment]
Got it. Thanks.
