### ISSUE TITLE
FTPClientSession over http proxy

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#1945]
I've seen that on release 1.8.0 FTP over TLS is going to be supported. I wonder whether it is feasible to support ftp through http proxy as well, so that class FTPClientSession can use methods similar to those of class HTTPClientSession for proxy configuration

**Comment by micheleselea** [comment]
I can have a look to insert proxy connection. Should not be difficult to implement using the same way HTTP does: the only think we should check is that we have always 2 connections in FTP (commands and data) so I have to figure out how ftp proxy works.

**Comment by dk1301** [comment]
Thanks for the response. My request came from a real case when I tried to use the FTPClientSession in order to upload files to a server from a host that contained an http/https proxy and not a dedicated ftp one. Of course I could not make that work and so I was wondering whether it was feasible. I don't know from implementation point of view if its different to support ftp over http/https proxy from ftp over ftp proxy but the majority of the hosts that I've come across do not have a dedicated ftp proxy.
