### ISSUE TITLE
poco audio tag support

### ISSUE THREAD

**Issue by monhi** [pocoproject/poco#1954]
For an IVR (Interactive voice response )system, I am in need of sending ogg files with html 5 audio tag from poco web server to chrome or firefox web clients,

As each page has a lot of audio tags, I come to the conclusion that I use preload="none" option for audio tags and based on customer needs, I send audio files to them.
`
<!DOCTYPE html>
<html>
<body>
<audio controls preload="none">
  <source src="message.ogg" type="audio/ogg">
</audio>
</body>
</html>
`

But now, I do not know how  to use poco to send ogg binary files based on user requests.

I do not know if I change them to base64 form and send them to clients or use other techniques.

Could you please give me some hints in this regard

Best wishes

**Comment by aleks-f** [comment]
does not seem like a poco question - whatever browser expects/accepts, is what you should send

**Comment by monhi** [comment]
Yes, I test Ogg files and without any problem, it works perfect. 
even with large ogg files it has no problem

I have another problem with online radio like audio streaming which I open a new issue to ask.

Best wishes,
Mahdi,
