### ISSUE TITLE
FileStreamBuf add method to get current position

### ISSUE THREAD

**Issue by fenghao119** [pocoproject/poco#1963]
#### Expected behavior
Get current position of FileInputStream
#### Actual behavior
Call FileInputStream::tellg() will call FileStreamBuf::resetBuffers(), and lost all buffer data, performance is low.
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.7.9
#### Compiler and version
all
#### Operating system and version
all
#### Other relevant inofrmation
please add method for FileStreamBuf, return the value of member _pos.

**Comment by aleks-f** [comment]
> please add method for FileStreamBuf, return the value of member _pos.

@fenghao119 would you mind sending a pull request with the change and a test case?

**Comment by fenghao119** [comment]
I commit the code fenghao119@580249efbcbf5a0c411a87544847dfbb64f955c9. The change only for win32, it should apply in POSIX also.

Compiler and version
VS2015, 64bit, shared release 

Operating system and version
 Windows 10 64bit, Surface Book I7 

Output is
```
comparePerformance: create 256MB file
position() load progress 0.5
position() const 0.968297
tellg() load progress 0.5
tellg() cost 35.9739
```

**Comment by aleks-f** [comment]
by applying optimization (adapted from [boost](https://svn.boost.org/trac10/ticket/817)):
```
λ git diff ../src/FileStream_WIN32.cpp
diff --git a/Foundation/src/FileStream_WIN32.cpp b/Foundation/src/FileStream_WIN32.cpp
index 9c9674dc6..8ac051780 100644
--- a/Foundation/src/FileStream_WIN32.cpp
+++ b/Foundation/src/FileStream_WIN32.cpp
@@ -146,7 +146,16 @@ std::streampos FileStreamBuf::seekoff(std::streamoff off, std::ios::seekdir dir,
 {
        if (INVALID_HANDLE_VALUE == _handle || !(getMode() & mode))
                return -1;
-
+
+       if (gptr() != 0                                            // when currently input buffered
+               && dir == std::ios::cur && mode == std::ios::in        // for a relative seek
+               && eback() - gptr() <= off && off <= egptr() - gptr()) // within the buffer
+       {
+               gbump(static_cast<int>(off));
+               off = 0;
+               return static_cast<std::streampos>(_pos - static_cast<std::streamoff>(egptr() - gptr()));
+       }
+
        if (getMode() & std::ios::out)
                sync();
```
it gets much better:
```
create 256MB file
position() load progress 0.5
position() cost 1.64873
tellg() load progress 0.5
tellg() cost 2.86506
```
but, this should be checked by someone with more std streams expertise and some tests should be added, I don't have time at the moment. 

I'm not opposed to also adding the `position()` and `adjust()` members

@obiltschnig?
