### ISSUE TITLE
URI setUserInfo process wrong if  contain special characters

### ISSUE THREAD

**Issue by fenghao119** [pocoproject/poco#1969]
#### Expected behavior
as below
#### Actual behavior
as below
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
```c++
void test() {
	Poco::URI uri("ftp://192.168.56.120/30m"), test;

	uri.setUserInfo("ftptest:123@abc");
	test = Poco::URI(uri.toString());
	assert(test.getUserInfo() == uri.getUserInfo()); // fail

	uri.setUserInfo("ftptest:123%40abc"); // encode '@' as %40
	test = Poco::URI(uri.toString());
	assert(test.getUserInfo() == uri.getUserInfo()); // fail
}
```
#### POCO version
1.7.9
#### Compiler and version
all
#### Operating system and version
all

**Comment by fanyhawu** [comment]
I met the same issue with POCO 1.4.7 , '%40' would be conversed into '@' in uri.toString().
