### ISSUE TITLE
Poco*.cmake files are only generate when using cmake

### ISSUE THREAD

**Issue by jspricke** [pocoproject/poco#1974]
We got a request to include the cmake files in Debian: https://bugs.debian.org/880614. Till now we use configure and make to build Poco and the cmake files are not generated that way. As far as I know this is still the preferred method to build. Is this still correct?

Is there a supported path how to use Poco in cmake projects?

#### Expected behavior

Compiling and installing with configure and cmake produces the same result.

#### Actual behavior

Compiling with cmake produces cmake files (to use Poco in other cmake projects), whereas they are not there when compiling using configure

#### Steps to reproduce the problem

compile and install with configure, find "*.cmake"

#### POCO version

poco-1.7.9p1-release.tar.gz

#### Compiler and version

GNU Make 4.1
gcc (Debian 7.2.0-12) 7.2.1 20171025
cmake version 3.9.3

#### Operating system and version

Debian unstable, updated today.

**Comment by aleks-f** [comment]
> we use configure and make to build Poco and the cmake files are not generated that way

If i understand this correctly, the request is to add the possibility to build using `cmake` from `configure`? If so, that is relatively simple - creating a build directory and running `cmake` and `make` in the created directory.

> As far as I know this is still the preferred method to build. Is this still correct?

For the time being, the `make` build (as well as pre-generated MS VS projects, but that is not relevant here) will remain supported in 2.0. We will see in the future whether it makes sense to abandon those entirely.

**Comment by aleks-f** [comment]
Disclaimer: I am not the author of cmake functionality, nor a cmake expert. @bachp contributed most of cmake and may have something to add here

**Comment by obiltschnig** [comment]
IMO the more promising approach would be to change the Debian package recipe to use CMake, like e.g. the Yocto recipe. This will give you the requested CMake package files.

**Comment by jspricke** [comment]
>If i understand this correctly, the request is to add the possibility to build using `cmake` from `configure`? If so, that is relatively simple - creating a build directory and running `cmake` and `make` in the created directory.

No, only to create the cmake files (as referenced in 
https://github.com/pocoproject/poco/blob/develop/cmake/README) in the 
configure/make build system as well (if they are officially supported by 
the project).

>For the time being, the `make` build (as well as pre-generated MS VS projects, but that is not relevant here) will remain supported in 2.0. We will see in the future whether it makes sense to abandon those entirely.

I read that as a configure/make is supported, cmake is uncertain?

**Comment by aleks-f** [comment]
> I read that as a configure/make is supported, cmake is uncertain?

no, cmake will stay and will be supported

**Comment by obiltschnig** [comment]
And CMake may at one point become the main build system.

**Comment by jspricke** [comment]
That's good to know :). I will evaluate how to move all our build flags to cmake (using cmake in Debian is easy).

**Comment by obiltschnig** [comment]
And, you may also be happy to know that in release 1.8.0 (coming soon) Alex has replaced the JSON-Licensed JSON parser with a public domain one.

**Comment by bachp** [comment]
@jspricke as already mentioned the Yocto recipe uses CMake to build Poco and it's working fine. When I last checked the official source tarballs from pocoproject.org do not contain cmake build files, so the Yocto recipe builds from a git checkout. Not sure if that is an issue for you.

While it would be possible to ship CMake module files also for the non CMake builds, I didn't not invest into that as in that cases you can not use the mechanism CMake provides to create these file but they have to be created manually. For example how Qt5 does it that way.

**Comment by zosrothko** [comment]
Currently, on Windows, CMake does not install the binaries into the target local directories (bin, bin64, lib, lib64) which is mandatory for debugging Poco's module with VisualStudio. So until this be fixed, CMake cannot be the building tool for Windows.

**Comment by jspricke** [comment]
I found an other blocker:

$ wget https://github.com/pocoproject/poco/archive/poco-1.7.9p1-release.tar.gz
$ wget https://pocoproject.org/releases/poco-1.7.9/poco-1.7.9p1-all.tar.gz
$ diff -r poco-1.7.9p1-all poco-poco-1.7.9p1-release | grep CMake
Only in poco-poco-1.7.9p1-release/CppUnit: CMakeLists.txt
Only in poco-poco-1.7.9p1-release/CppUnit/WinTestRunner: CMakeLists.txt

Using poco-1.7.9p1-release.tar.gz as the officially released version, 
results in:

poco-1.7.9p1-all/ $ cmake .. -DENABLE_TESTS=ON

CMake Error at CMakeLists.txt:132 (add_subdirectory):
  The source directory

    /home/jspricke/src/debian/poco/CppUnit

  does not contain a CMakeLists.txt file.

I could add the CMakeLists.txt, but is there a reason it's not included 
in the release?

**Comment by obiltschnig** [comment]
Need to look into it, although I'd recommend to switch to the GitHub archive ( https://github.com/pocoproject/poco/archive/poco-1.7.9p1-release.tar.gz) as a source for packages.

**Comment by bachp** [comment]
@obiltschnig Yocto doesn't accept github tarballs as they used to be regenerated and changing their checksums.

**Comment by obiltschnig** [comment]
I've fixed the build script to include the CMakeLists.txt for CppUnit. New release packages should be up in a few minutes.

**Comment by jspricke** [comment]
The new release (1.8.0.1) with the cmake files in Debian, thanks for the support.
