### ISSUE TITLE
SHA-256 mismatch for poco-1.7.9p1-all.tar.gz

### ISSUE THREAD

**Issue by ilovezfs** [pocoproject/poco#1976]
Homebrew users currently cannot build poco from source due to a SHA-256 checksum mismatch for poco-1.7.9p1-all.tar.gz

2017-11-02 18:08:30 -0400 the checksum was
463f58aac40a7f7f28950b2c5bfe6c25a0dc61a70e5269a2be8c35d76fcbea84

Now it's
76f698d3e537879664f56a3dfde3a88e88f06c13b6474dd6a0ee6ad7f6ab4e4a

Do you have any idea what happened here? To rule out malicious circumstances, we'll need to know why the file has changed before the checksum can be updated in Homebrew. Thanks!

**Comment by obiltschnig** [comment]
We have rebuilt the packages to include two missing CMakeLists.txt for CppUnit. See #1974 for discussion.

**Comment by ilovezfs** [comment]
@obiltschnig OK, thanks. I will update the checksum accordingly. In the future, it would be great if you could bump the release number when the release artifacts have to change after publication.
