### ISSUE TITLE
DefinePlatformSpecific Error

### ISSUE THREAD

**Issue by Maihym** [pocoproject/poco#1977]
#### Expected behavior
After performing "cmake .." the build should compile.
#### Actual behavior
When I execute "cmake .." the build reports an error in the CMakeLists.txt file and the line it's referring to says "include (DefinePlatformSpecific)".
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
Get Ubuntu 14 desktop, execute "sudo apt-get install openssl libssl-dev", "sudo apt-get install libiodbc2 libiodbc2-dev", and "sudo apt-get install libmysqlclient-dev"
Download poco 1.6.1 all and extract it, then merge [these ](https://github.com/danielstuart14/extDB2/tree/master/poco-1.6.1-changes)changes with poco 1.6.1 all. Then do "mkdir cmake_build" then "cd cmake_build" then "cmake .." and you should get that error.
#### POCO version
1.6.1 all
#### Compiler and version
Cmake 3.1
#### Operating system and version
Ubuntu 14 Desktop

**Comment by aleks-f** [comment]
Well, we're about to release 1.8.0 and 2.0. Support for a custom build based on 1.6.1 is a bit too much to ask at this point. Please try 1.7.9 and if you still are experiencing the same problem, let us know by opening a new issue.
