### ISSUE TITLE
Remove OpenVMS support

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1988]
OpenVMS support in Poco has not been maintained for years now and nobody has asked for it, and we no longer have access to a VMS system for testing. Time to remove it from 1.8 and following releases.

**Comment by zosrothko** [comment]
Just by curiousity... Who was using it?

**Comment by obiltschnig** [comment]
Don't know if anyone was ever using it. Back then I added it mostly for the "cross-platform" idea and to get some experience with VMS. Compaq also provided free access to an OpenVMS test system.
