### ISSUE TITLE
Crypto: testsuite: tests should avoid to reference POCO_BASE

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#1992]
It is not allays possible to setup the environement variable POCO_BASE whe  running test (because it depends on the testing tool infra), so it would be preferable to avoid using POCO_BASE in testsuite is possible.

#### Expected behavior
testFullPKCS12: 
testCertsOnlyPKCS12: 

#### Actual behavior
testFullPKCS12: ERRORNot found: POCO_BASE
testCertsOnlyPKCS12: ERRORNot found: POCO_BASE
testPEMReadWrite: ERROR

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
Launch Crypto/testsuite/bin/TestSuite.exe without POCO_BASE set

#### POCO version
develop branch

#### Compiler and version
VS2015

#### Operating system and version
Windows 10

**Comment by aleks-f** [comment]
That's done in multiple tests (json, zip). NotFound exception can be avoided by providing default (""). And there's.only two things we can do: POCO_BASE and pat.

**Comment by aleks-f** [comment]
> NotFound exception can be avoided by providing default (""). 

Actually, I take that back - even if you prevent `Environment::get()` from throwing, the testsuite will throw anyway. `POCO_BASE` is typically last resort; first is `cwd`, so you either have to (1) run tests from the right place in the directory tree or (2) you have to have `POCO_BASE` env. I can think of no way around it.
