### ISSUE TITLE
Register POCO_SERVER_APP as service under non-Admin account?

### ISSUE THREAD

**Issue by OldWolf2** [pocoproject/poco#1995]
I am authoring a Poco Server Application, via `#include "Poco/Util/ServerApplication.h"` and using the `POCO_SERVER_MAIN()` macro.

My users can register as service by executing `MyServer.exe /registerService`. However, this installs the service to run as LocalSystem; and furthermore, elevation is required to start or stop the service.

For security reasons I would like the service to execute as a non-Admin user; and (if possible, but not essential) also allow that user to start/stop the service without elevation.

Does the Poco ServerApplication support this or are there any plans to support it?  Even if it has to be via extra commandline arguments for the `/registerService` option to specify username, password.

I am using POCO 1.6.0 and mingw-w64 x86_64-6.2.0-win32-seh-rt_v5-rev1  , although there don't appear to be any code changes in Poco/Util/src/WinService.cpp between 1.6.0 and 1.8.0.1.

My OS is Windows 10 Home 1703, although I would like this to work on as many flavours as possible.

I realize it is possible to use a third-party installation app such as WiX to perform the service registration, bypassing the Poco Server feature completely. It is also possible to manually edit the service configuration with `sc.exe` or the SCM GUI. However it would be nice to be able to keep using the commandline interface offered by the ServerApplication framework.

**Comment by aleks-f** [comment]
Unfortunately, not currently possible. Luckily, feature is not very hard to add, and we welcome contributions very much :)

Here are the relevant points:

[ServerApplication::defineOptions(()](https://github.com/pocoproject/poco/blob/develop/Util/src/ServerApplication.cpp#L396-L432)
[CreateService API call](https://github.com/pocoproject/poco/blob/develop/Util/src/WinService.cpp#L93-L102)
