### ISSUE TITLE
Why is ProGen removed ?

### ISSUE THREAD

**Issue by JiekeZhu** [pocoproject/poco#1999]
Why is ProGen removed ?
With ProGen and .progen file, I can easily create a new project, lib or dll or exe.
I have added a user macro for Poco root folder path and my projects settle relatively to it.
I think we should enhance ProGen to easily create new projects rather remove it. 
Or is there any other module can replace it ? 

Thanks.

This is my project.progen file.
vc.project.guid = ${vc.project.guidFromName}
vc.project.name = ProjectName
vc.project.target = ProjectName
vc.project.type = executable
vc.project.pocobasemacro = ..\\Poco.Develop\\
vc.project.pocobase = $(PocoBase)
vc.project.outdir = $(PocoBase)
vc.project.platforms = Win32
vc.project.vstools = vs140
vc.project.configurations = debug_shared, release_shared, debug_static_mt, release_static_mt, debug_static_md, release_static_md
vc.project.prototype = ProjectName_vs90.vcproj
vc.project.compiler.include = $(PocoBase)CppUnit\\include;$(PocoBase)Crypto\\include;$(PocoBase)Data\\include;$(PocoBase)Data\\ODBC\\include;$(PocoBase)Foundation\\include;$(PocoBase)Net\\include;$(PocoBase)NetSSL_OpenSSL\\include;$(PocoBase)Nghttp2\\nghttp2\\lib\\includes;$(PocoBase)openssl\\include;$(PocoBase)ProtocolBuffer\\Include;$(PocoBase)Redis\\include;$(PocoBase)Util\\include;$(PocoBase)WinTestRunner\\include;%(AdditionalIncludeDirectories)
vc.project.compiler.defines = 
vc.project.compiler.defines.shared = 
vc.project.compiler.defines.debug_shared =  ${vc.project.compiler.defines.shared}
vc.project.compiler.defines.release_shared = ${vc.project.compiler.defines.shared}
vc.project.linker.dependencies.Win32 = libprotobuf.lib Crypt32.lib ws2_32.lib
vc.project.linker.dependencies.x64 = libprotobuf.lib Crypt32.lib ws2_32.lib
vc.solution.create = true

**Comment by obiltschnig** [comment]
ProGen is based on Visual Studio 2008 projects, from which all other project files are derived. Since we no longer support Visual Studio 2008 and have removed all pre-2015 project files, ProGen is of no use any more. We have decided to make CMake the primary build system starting with 2.0, and will only provide Visual Studio project files for the most recent Visual Studio version, mostly for the convenience of POCO developers.
