### ISSUE TITLE
Build error when using SharedMemory

### ISSUE THREAD

**Issue by WeiChungChang** [pocoproject/poco#2011]
#### Expected behavior
Build successfully.

#### Actual behavior
```
/usr/local/lib//libPocoFoundation.a(SharedMemory.o): In function `Poco::SharedMemoryImpl::SharedMemoryImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, Poco::SharedMemory::AccessMode, void const*, bool)':
SharedMemory.cpp:(.text+0x2ab): undefined reference to `shm_open'
SharedMemory.cpp:(.text+0x31b): undefined reference to `shm_unlink'
/usr/local/lib//libPocoFoundation.a(SharedMemory.o): In function `Poco::SharedMemoryImpl::close()':
SharedMemory.cpp:(.text+0x666): undefined reference to `shm_unlink'
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'test' failed
make: *** [test] Error 1
```
#### Steps to reproduce the problem
Make static lib.
Build an app using SharedMemory.

#### POCO version
poco-1.8.0.1

#### Compiler and version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

#### Operating system and version
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

#### Other relevant information
Magically, if I add a dummy function as below.

```
int dummy()
{
    const char *memname = "sample";
    const size_t region_size = sysconf(_SC_PAGE_SIZE);
    int fd = shm_open(memname, O_CREAT | O_TRUNC | O_RDWR, 0666);
    if (fd == -1)
        return -1;
    int r = shm_unlink(memname);
    if (r != 0)
        return -1;
}
```

It can be successfully built.

The function seems to **touch** shm_open & shm_unlink to make it work.

**Comment by aleks-f** [comment]
what does your build command line look like? Is `-lrt` **after** `-lPocoFoundation`? If not, move it and try again.

**Comment by WeiChungChang** [comment]
Dear @aleks-f 

Thanks a lot for your suggestion.

From your reply & this post 
https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc
I got the right way.

However I still wonder why once I add the dummy function it passes. Do yo know the reason?

Thanks.

**Comment by aleks-f** [comment]
> I still wonder why once I add the dummy function it passes.

`-lrt` is after your application sources and linking of `shm_open` in dummy happens before linking of `shm_open` from poco code. so, by the time linking from poco is attempted, symbol is already resolved.
