### ISSUE TITLE
Poco ODBC for mysql failed in centos7.0

### ISSUE THREAD

**Issue by fighter1999** [pocoproject/poco#2014]
I have installed mysql 5.6.38 x64, mysql connector odbc 5.3.9 x64, unixodbc 2.3.4 in CentOS7.0 64bit. After configure /etc/odbc.ini and /etc/odbcinst.ini, I can succed to use "isql storefeedback" command to connect mysql database. The contents of /etc/odbc.ini is following:
`[root@localhost src]# cat /etc/odbc.ini`
`[storefeedback]`
`Description = The Database for mysql`
`Trace = On`
`TraceFile = stderr`
`Driver = MYSQL`
`SERVER = localhost`
`USER = root`
`PASSWORD = password`
`PORT = 3306`
`DATABASE = mysql`
`CHARSET = UTF8`
`OPTION = 3`
`SOCKET = /var/lib/mysql/mysql.sock`

The contents of /etc/odbcinst.ini is following:
`[root@localhost src]# cat /etc/odbcinst.ini`
`[MYSQL]`
`Driver=/usr/lib/libmyodbc5.so`
`SETUP=/usr/lib/libmyodbc5.so`
`UsageCount=2`

Now I wanted to use the function ODBC of poco1.7.8p3 to connect mysql 5.6.38 x64 database, but Poco::NotFoundException was returned. Can anyone find a solution or give me advice to it? Any help is very appreciated.
My source is following:
<pre><code>
#include "stdio.h"
#include "Poco/Data/MySQL/MySQLException.h"
#include "Poco/Data/MySQL/MySQL.h"
#include "Poco/Data/MySQL/Connector.h"
#include "Poco/Data/Session.h"
using namespace Poco::Data::Keywords;
using namespace Poco::Data;
using Poco::Data::Session;
int main() 
{
  try{
    MySQL::Connector::registerConnector();
    Session sess("ODBC", "DSN=storefeedback");
    if(sess.isConnected()){
      printf("succed to connect\n");
    }else{
      printf("failed to connect\n");
    }
  }
  catch (MySQL::MySQLException& e){
    printf("exception\n");
  }
  catch (Poco::Data::ConnectionFailedException& e){
    printf("connect failed\n");
  }
  catch (Poco::NotFoundException& e){
    printf("not found\n");
  }
  MySQL::Connector::unregisterConnector();
  return 0;
}
<code><pre>

**Comment by aleks-f** [comment]
You are trying to use ODBC with native MySQL. If you want to stick with ODBC, then you have to use  [Poco::Data::ODBC](https://github.com/pocoproject/poco/tree/poco-1.8.0/Data/ODBC), but if you are only dealing with MySQL, then [Poco::Data::MySQL](https://github.com/pocoproject/poco/tree/poco-1.8.0/Data/MySQL) may be a better choice.

**Comment by fighter1999** [comment]
Thank you for your reply. I will modify the source and continue to try later.

**Comment by fighter1999** [comment]
Sorry for answer lately. I modified the source, but  “Segmentation fault (core dumped)” is displayed. Source is following.
<pre><code>
#include "stdio.h"
#include "Poco/Exception.h"
#include "Poco/Data/StatementImpl.h"
#include "Poco/Data/ODBC/Connector.h"
#include "Poco/Data/ODBC/ODBCException.h"
#include "Poco/Data/ODBC/ODBCStatementImpl.h"
#include "Poco/Data/MySQL/MySQLException.h"
#include "Poco/Data/Session.h"
#include "Poco/Data/ODBC/Utility.h"

using namespace Poco::Data::Keywords;
using namespace Poco::Data;
using Poco::Data::Session;
int main() 
{
  try{
    Poco::Data::ODBC::Connector::registerConnector();
    Session sess("ODBC", "DSN=storefeedback");
    if(sess.isConnected()){
      printf("succed to connect\n");
    }else{
      printf("failed to connect\n");
    }
  }
  catch (Poco::Data::NotConnectedException& e){
    printf("not connected exception\n");
  }
  catch (Poco::Data::ConnectionFailedException& e){
    printf("connect failed exception\n");
  }
  catch (Poco::Data::ODBC::StatementException& e){
    printf("statement exception\n");
  }
  catch (Poco::InvalidAccessException& e){
    printf("invalid access exception\n");
  }
  catch (Poco::Data::DataException& e){
    printf("data exception\n");
  }
  catch (Poco::BadCastException& e){
    printf("bad cast exception\n");
  }
  catch (Poco::AssertionViolationException& e){
    printf("assertion violation exception\n");
  }
  catch (Poco::NotFoundException& e){
    printf("not found exception\n");
  }
  catch(...){
    printf("other error\n");
  }
  Poco::Data::ODBC::Connector::unregisterConnector();
  return 0;
}
<code><pre>

**Comment by fighter1999** [comment]
Problem is fixed. Thank you.@aleks-f. The reason is when I compile, I added a rubbish option(PocoDataMySQL):
error compile option:
g++ -o sample sample.cpp -I /opt/poco.1.7.8p3/include -L/opt/poco.1.7.8p3/lib -lPocoDataMySQL -l PocoData -l PocoFoundation -l PocoUtil -l PocoDataODBC -m32 -Wl,-rpath=/opt/poco.1.7.8p3/lib:/usr/local/mysql/lib
current compile option:
g++ -o sample sample.cpp -I /opt/poco.1.7.8p3/include -L/opt/poco.1.7.8p3/lib -l PocoData -l PocoFoundation -l PocoUtil -l PocoDataODBC -m32 -Wl,-rpath=/opt/poco.1.7.8p3/lib:/usr/local/mysql/lib
