### ISSUE TITLE
is there any tools to auto format the code with the poco cpp code style?

### ISSUE THREAD

**Issue by richardor** [pocoproject/poco#2017]
Is there any tools to auto format the code with the poco cpp code style?
thanks.

**Comment by aleks-f** [comment]
not that I know of, but a contribution would be welcome. probably best candidate is [clang-format](http://clang.llvm.org/docs/ClangFormat.html)

**Comment by zosrothko** [comment]
AStyle makes also a pretty good job

**Comment by richardor** [comment]
there are maybe a lot of tools to format the code.
but i want to use the configuration of poco.  can u post them here ? @aleks-f

**Comment by fbraem** [comment]
You can find the poco coding standard here: http://www.appinf.com/download/CppCodingStyleGuide.pdf
