### ISSUE TITLE
Help with using Poco within wxWidgets application

### ISSUE THREAD

**Issue by raananb** [pocoproject/poco#2025]
I would like to load the page "https://www.boursier.com/actions/cours/renault-FR0000131906,FR.html" in a wxWidgets application.

wxWidgets does not provide https connection, and I would like to use Poco as an embedded software (just like sqlite3.c which is compiled with the application).

I wonder if this is part of the Poco design, and if it is, what needs to be included.

Many thanks.

**Comment by zosrothko** [comment]
You could have a look at the [Poco documentation ](https://pocoproject.org/documentation/index.html)that provides summaries with pdfs. There are also samples in the Net, NetSLL_OpenSSL modules.

**Comment by raananb** [comment]
It is not clear to me whether I need to build the libraries or just include specific software sources files.

**Comment by zosrothko** [comment]
Either you can build Poco from the source at GitHub or the [sources ](https://pocoproject.org/releases/), either you can download and install packaged Poco [binaries ](https://github.com/pocoproject/distro/releases) for Windows

**Comment by raananb** [comment]
I downloaded a binary from https://github.com/pocoproject/distro/releases to try and figure out how to proceed.
This did not help at all: while the welcome page of Poco announces Libraries and Tutorials, I found no tutorials within the documentation. It is absolutely not clear to me where one should look for information and how the information is organized: I thought that package NetSSl_OpenSSL/HTTPSClient was where I had to look, but then a header file like Poco/Net/HTTPSClientSession.h implies that there is a folder Poco somewhere. Where? Which one?
A tutorial would have clarified how to address the practical aspects for a new user.
Thanks for your help.

**Comment by CharlesBunders** [comment]
If you grab the source and build it there are folders for "samples" and
"testsuite" under each main section, Net, Util, XML, JSON, etc.

That is where you would find working examples.

**Comment by aleks-f** [comment]
> It is not clear to me whether I need to build the libraries or just include specific software sources files.

[Guided Tour](https://pocoproject.org/docs/00100-GuidedTour.html), first sentence:

If you don't know whether libraries have to be built, then this may not be the right forum to ask.

```
The POCO C++ Libraries are a collection of open source C++ class libraries
```

> there is a folder Poco somewhere. Where? Which one?

[Getting Started](https://pocoproject.org/docs/00200-GettingStarted.html) document:

```
Foundation/                project and make/build files for the Foundation library
    include/
        Poco/              header files for the Foundation library
```

**Comment by raananb** [comment]
Thanks for the information.

I have been working with wxWidgets for many years and never came up with the problem I am facing with Poco! Using Visual Studio wxWidgets builds all the libraries with the provided .sln in 5 minutes, and the system is ready for developing applications.

I was looking for a similar process for setting up Poco, but did not find any. Looking at an example which may do what I am trying to achieve (https://gist.github.com/t-mat) I do not see how it connects to the structure of Poco when Poco is downloaded and unzipped into my file system.

Next, I guess, but it is only a guess, that for that example all the libraries have to be built.

I built Foundation using 'Foundation_vs150.sln' under Visual Studio Community 2017. The default SDK (8.1) had to be changed to 10.0.15063.0 to avoid missing header files (ctype.h).

I then tried to build Crypto and NetSSL_OpenSSL, but both failed with missing files 'openssl/crypto.h' and 'openssl/err.h'.

Progress is slow...

**Comment by aleks-f** [comment]
Please read [the documentation](https://pocoproject.org/docs/00200-GettingStarted.html):

```
On Windows, there are three options:

Use POCO pre-built OpenSSL binaries (simplest and recommended)
Build OpenSSL using scripts from POCO distribution package
Use a third-party pre-built OpenSSL
```
If you are using 3rd party and binaries are not named or located where VS project expects them, clearly there will be a problem.
