### ISSUE TITLE
Add pkg-config support

### ISSUE THREAD

**Issue by yegorich** [pocoproject/poco#2037]
pkg-config provides a comfortable way to search for installed libraries, get their versions etc. It would be very useful if poco would provide/install *.pc files for all of its components like:

- PocoNet.pc
- PocoJSON.pc
- PocoUtil.pc
- PocoFoundation.pc
etc.

**Comment by yegorich** [comment]
As we are talking about enhancing the build system. What is the primary build system for poco? CMake or Makefiles/Solutions?

**Comment by obiltschnig** [comment]
For 1.8 and earlier, Makefiles and VC Solutions. For develop/2.0, CMake.

**Comment by yegorich** [comment]
Closed with #2224
