### ISSUE TITLE
Working example?  Net::HTTPCredentials 'updateAuthInfo'

### ISSUE THREAD

**Issue by snhirsch** [pocoproject/poco#2040]
#### Expected behavior
According to the documentation, I should only need to call 'authenticate' once, then rely on the 'updateAuthInfo' method for subsequent requests in the same session.  
#### Actual behavior
I receive authentication failures from the server when doing so.  Subsequent requests all require 'authenticate'.
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
#### POCO version
1.6.1
#### Compiler and version
g++ 4.8.5
#### Operating system and version
Centos 7.3
#### Other relevant information
I cannot find any example code that demonstrates use of 'authenticate' and 'updateAuthInfo'.  It's quite possible I'm making a basic mistake, but with no reference example it's hard to tell.

**Comment by snhirsch** [comment]
Bump.  Can anyone help with a working example?  Or, is this feature simply broken?

**Comment by aleks-f** [comment]
> Can anyone help with a working example?

a non-working example may speed up the process of producing a working example ...
```
(please make this a SSCCE, if applicable and reasonable)
```

**Comment by snhirsch** [comment]
That may be problematic. since the code belongs to my employer and I certainly cannot post as is.   Let me see what I can do to generate something stand-alone and bare bones.
