### ISSUE TITLE
Android abstract namespace local socket address

### ISSUE THREAD

**Issue by fenghao119** [pocoproject/poco#2042]
#### Expected behavior
create android abstract namespace local socket address
#### Actual behavior
can not
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

Net/include/Poco/Net/SocketAddressImpl.h

```c++
class Net_API LocalSocketAddressImpl: public SocketAddressImpl
{
public:
	LocalSocketAddressImpl(const struct sockaddr_un* addr);
	LocalSocketAddressImpl(const char* path);
	~LocalSocketAddressImpl();
	IPAddress host() const;
	UInt16 port() const;
	poco_socklen_t length() const;
	const struct sockaddr* addr() const;
	int af() const;	
	Family family() const;
	const char* path() const;
	std::string toString() const;
};
```
change the constuctor LocalSocketAddressImpl(const char* path) to LocalSocketAddressImpl(const std::string& path) 

use memcpy instead of strcpy. 

android abstract namespace local socket path start with '\0' and follow a name.

#### POCO version
1.8.0.1
#### Compiler and version
ndk
#### Operating system and version
android

**Comment by fenghao119** [comment]
#### Expected behavior
connect to android abstract socket
#### Actual behavior
can not
#### Steps to reproduce the problem
in android app, java code
```java
new Thread() {
    @Override
    public void run() {
        try {
            final LocalServerSocket server = new LocalServerSocket("com.android.test.abstract");
            for (;;) {
                final LocalSocket client = server.accept();
                Log.d("test", "accept a client");
                // process client
            }
        } catch (Exception ignored) {
        }
    }
}.start();
```
in native c++
```c++
void test_fail() {
  char address[] = "\0com.android.test.abstract";
  std::string addr(address, sizeof(address) - 1);
  StreamSocket sock(SocketAddress(SocketAddress::UNIX_LOCAL, addr));
  // throw exception "Connection refused"
}

void test_ok() {
    char address[] = "\0com.android.test.abstract"; // this end with null
    struct sockaddr_un server_address;
    memset(&server_address, 0, sizeof(server_address));
    server_address.sun_family = AF_UNIX;
    memcpy(server_address.sun_path, address, sizeof(address));
    socklen_t address_length = sizeof(address) - 1 + offsetof(struct sockaddr_un, sun_path);

    StreamSocket sock(SocketAddress::UNIX_LOCAL);

    if (::connect(sock.impl()->sockfd(),
        (const struct sockaddr *) &server_address,
        address_length) < 0)
    {
        throw NetException(errno);
    }
    // success
}
```
#### POCO version
1.8.1
#### Compiler and version
ndk
#### Operating system and version
android 7.1
#### Other relevant information

**Comment by obiltschnig** [comment]
Could you debug into `StreamSocket sock(SocketAddress(SocketAddress::UNIX_LOCAL, addr));` and see what happens to its internal `sockaddr_un` struct?

**Comment by fenghao119** [comment]
Below is Poco original code
```c++
void SocketImpl::connect(const SocketAddress& address)
{
	if (_sockfd == POCO_INVALID_SOCKET)
	{
		init(address.af());
	}
	int rc;
	do
	{
#if defined(POCO_VXWORKS)
		rc = ::connect(_sockfd, (sockaddr*) address.addr(), address.length());
#else
		rc = ::connect(_sockfd, address.addr(), address.length());
#endif
	}
	while (rc != 0 && lastError() == POCO_EINTR);
	if (rc != 0) 
	{
		int err = lastError();
		error(err, address.toString());
	}
}
```
`::connect(sock.impl()->sockfd(), (const struct sockaddr *) &server_address, address_length)`, the third parameter, poco library assume it's equal `address.length()` (same as `sizeof(sockaddr_un)`); this is wrong for abstract namespace socket.

**Comment by aleks-f** [comment]
this is a linux peculiarity, size for abstract namespace socket address should be
```
sizeof(sockaddr_un.sun_family) + strlen(abstract_name) + 1
```
[AF_UNIX sockets and the abstract namespace](http://blog.eduardofleury.com/archives/2007/09/13)

@fenghao119 if you send a pull with testcase, the speed of the fix making it to release increases
