### ISSUE TITLE
Poco::Net::NetworkInterface::list does not list inactive interfaces even when explicitly being asked for it

### ISSUE THREAD

**Issue by killerbot242** [pocoproject/poco#2044]
#### Expected behavior
Enumerate all interfaces when asked for also "disabled" ones (aka upOnly = false)
Poco::Net::NetworkInterface::list(false, false)

I played with the first argument just to see if that might have an impact.

In my scenario I don't get my eth1 and my wlan0.
Same behavior on another system too.

#### Actual behavior
Enumerates only the active interfaces

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.7.7 / 1.8.0.1
#### Compiler and version
gcc 6.3.1 / gcc 7.2
#### Operating system and version
Linux

**Comment by aleks-f** [comment]
From a quick look, it seems to affect only list - map works fine. Will look deeper.
