### ISSUE TITLE
@remote annotation does not work on method level for REST interface

### ISSUE THREAD

**Issue by roelvz** [pocoproject/poco#2045]
I made a small adaptation to the PizzeriaREST example by moving the @remote annotation from class level to method level:
```
class PizzaCollectionEndpoint
{
public:
	PizzaCollectionEndpoint(const std::vector<Pizza>& pizzas);
		/// Creates the PizzaCollectionEndpoint.

	//@ remote
	//@ path="/pizzeria/pizzas"
	std::vector<Pizza> get() const;
		/// Returns a vector containing the available pizzas.
		
private:
	std::vector<Pizza> _pizzas;
};
```
I then ran the RemoteGenNG command to regenerate the generated files.

#### Expected behavior
A GET request to /pizzeria/pizzas returns the list of pizzas

#### Actual behavior
A GET request to /pizzeria/pizzas returns an error:
```
{
error: "Not found",
detail: "/pizzeria/pizzas",
code: 0
}
```

#### Steps to reproduce the problem
- Start from the PizzeriaRest example
- Move the `@remote` and `@path` annotations in PizzaCollectionEndpoint from class to method level
- Regenerate the code using RemoteGenNG
- Start the server
- Make a GET request to /pizzeria/pizzas

#### POCO version
1.7.8p3

#### Compiler and version
Visual Studio 2015

#### Operating system and version
Windows 10 64 bit

**Comment by obiltschnig** [comment]
The `@path` property must be specified at class level. The documentation is wrong here, unfortunately.
