### ISSUE TITLE
[Question] Could Poco provides something like Android's looper, handler & message?

### ISSUE THREAD

**Issue by WeiChungChang** [pocoproject/poco#2046]
#### Expected behavior

_**Question about the usage case**_

#### Actual behavior

_**Handy Multi-thread usage, message passing & task arrangement.**_

#### Steps to reproduce the problem

_**I wonder if Poco provides something like Android's looper, handler & message?**_

_**http://pierrchen.blogspot.tw/2015/08/android-concurrent-programming-looper.html**_

_**They are handy tools both in Android application(JAVA) & framework layer(C++).**_

_**I wonder if it can be achieved by using current components & utilities?**_

**_Thanks_**  

#### POCO version

None.

#### Compiler and version

None.

#### Operating system and version

None.

#### Other relevant information

None.

**Comment by micheleselea** [comment]
You can use NotificationQueue, NotificationCenter and Thread
