### ISSUE TITLE
Support for vs2013 is killed in Foundation

### ISSUE THREAD

**Issue by in7egral** [pocoproject/poco#2047]
This new code in commit "C++11 support #1793 (#1795)":

```
#if defined(_MSC_VER) && (_MSC_VER < 1900)
	#error "_MSC_VER >= 1900 (VS 2015) required"
#endif
```

killed support for all versions earlier than 1900.

**Comment by aleks-f** [comment]
Your observation is a accurate. VS 2013 is largely non-c++11  compliant and will not be supported in 2.0
