### ISSUE TITLE
Why class xxxFileConfiguration destructor to be set to protected

### ISSUE THREAD

**Issue by Missmiaom** [pocoproject/poco#2048]
Hello everyone, I urge you to answer my question， thanks a lot！

#### Expected behavior
Can  class xxxFileConfiguration  be properly destructed? such as PropertyFileConfiguration

https://pocoproject.org/docs/Poco.Util.IniFileConfiguration.html

#### Actual behavior
their destructor to be set to protected，Is not they will not be properly destructed？

#### POCO version
1.8.0.1

#### Compiler and version
Visual Studio 2017

#### Operating system and version
Windows10

**Comment by aleks-f** [comment]
see [Rationale for protected destructor
](https://stackoverflow.com/a/31666480/205386)
