### ISSUE TITLE
AppVeyor: NetSSL_OpenSSL & NetSSL_Win HTTPSClientSessionTest interop test are failing

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#2051]
#### Expected behavior
HTTPSClientSessionTest are failing only on Windows which make all CI build fail on AppVeyor while they are ok on Travis. They were passing some time ago.
 
#### Actual behavior
!!!FAILURES!!!
Runs: 48   Failures: 0   Errors: 1
There was 1 error: 
 1: class CppUnit::TestCaller<class HTTPSClientSessionTest>.testInterop
    "class Poco::TimeoutException: Timeout"
    in "<unknown>", line -1
EchoConnection: SSL connection unexpectedly closed
EchoConnection: SSL connection unexpectedly closed

!!!FAILURES!!!
Runs: 30   Failures: 0   Errors: 1
There was 1 error: 
 1: class CppUnit::TestCaller<class HTTPSClientSessionTest>.testInterop
    "class Poco::TimeoutException: Timeout"
    in "<unknown>", line -1
EchoConnection: SSL Exception: Failed to receive data in handshake
EchoConnection: SSL Exception: Failed to receive data in handshake
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
develop branch

#### Compiler and version
VS2015

#### Operating system and version
Windows

**Comment by zosrothko** [comment]
@micheleselea Can you have a look to those failing tests. Thanks

**Comment by micheleselea** [comment]
Do you think is something I changed? or you need just a point of view from me?

**Comment by zosrothko** [comment]
Since it was working some time ago and you worked on te SSL client side, may be it could be related, hence my request.

**Comment by micheleselea** [comment]
I remember I discuss with @obiltschnig about correct way to shutdown SSL connection, but after using the correct (from API documentation) way you found a problem on Safari, so the change was reverted.
I made change in FTPS client, in HTTPSClientSessionTest I just added a constructor to set specific proxy setting, but if the test do not use it should not be involved in the problem.
I'll try to have a look to the failing test
