### ISSUE TITLE
poco-1.8.0.1 project compile error

### ISSUE THREAD

**Issue by damon-kwok** [pocoproject/poco#2055]
`/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h: In constructor ‘Poco::Net::SocketAcceptor<ServiceHandler>::SocketAcceptor(Poco::Net::ServerSocket&, Poco::Net::SocketReactor&)’:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:83:12: error: invalid use of incomplete type ‘class Poco::Net::SocketReactor’
   _pReactor->addEventHandler(_socket, Poco::Observer<SocketAcceptor,
            ^
In file included from /home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:22:0,
                 from /home/damon/catkin_ws/src/adsim/src/ws.cpp:9:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketNotification.h:30:7: note: forward declaration of ‘class Poco::Net::SocketReactor’
 class SocketReactor;
       ^`

**Comment by aleks-f** [comment]
please provide more information (hint: there's a template for filing issues - use it)

**Comment by damon-kwok** [comment]
`#include <Poco/Net/SocketAcceptor.h>

int main(int argc, char *argv[]) {
  return 0;
}
`
report error：
`In file included from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:0:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h: In constructor ‘Poco::Net::SocketAcceptor<ServiceHandler>::SocketAcceptor(Poco::Net::ServerSocket&, Poco::Net::SocketReactor&)’:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:83:12: error: invalid use of incomplete type ‘class Poco::Net::SocketReactor’
   _pReactor->addEventHandler(_socket, Poco::Observer<SocketAcceptor,
            ^
In file included from /home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:22:0,
                 from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketNotification.h:30:7: note: forward declaration of ‘class Poco::Net::SocketReactor’
 class SocketReactor;
       ^
In file included from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:0:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h: In destructor ‘virtual Poco::Net::SocketAcceptor<ServiceHandler>::~SocketAcceptor()’:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:94:14: error: invalid use of incomplete type ‘class Poco::Net::SocketReactor’
     _pReactor->removeEventHandler(_socket, Poco::Observer<SocketAcceptor,
              ^
In file included from /home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:22:0,
                 from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketNotification.h:30:7: note: forward declaration of ‘class Poco::Net::SocketReactor’
 class SocketReactor;
       ^
In file included from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:0:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h: In member function ‘void Poco::Net::SocketAcceptor<ServiceHandler>::setReactor(Poco::Net::SocketReactor&)’:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:108:17: error: invalid use of incomplete type ‘class Poco::Net::SocketReactor’
   if (!_pReactor->hasEventHandler(_socket, Poco::Observer<SocketAcceptor,
                 ^
In file included from /home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:22:0,
                 from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketNotification.h:30:7: note: forward declaration of ‘class Poco::Net::SocketReactor’
 class SocketReactor;
       ^
In file included from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:0:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h: In member function ‘virtual void Poco::Net::SocketAcceptor<ServiceHandler>::registerAcceptor(Poco::Net::SocketReactor&)’:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:130:12: error: invalid use of incomplete type ‘class Poco::Net::SocketReactor’
   _pReactor->addEventHandler(_socket, Poco::Observer<SocketAcceptor, ReadableNotification>(*this, &SocketAcceptor::onAccept));
            ^
In file included from /home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:22:0,
                 from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketNotification.h:30:7: note: forward declaration of ‘class Poco::Net::SocketReactor’
 class SocketReactor;
       ^
In file included from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:0:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h: In member function ‘virtual void Poco::Net::SocketAcceptor<ServiceHandler>::unregisterAcceptor()’:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:145:13: error: invalid use of incomplete type ‘class Poco::Net::SocketReactor’
    _pReactor->removeEventHandler(_socket, Poco::Observer<SocketAcceptor, ReadableNotification>(*this, &SocketAcceptor::onAccept)
             ^
In file included from /home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:22:0,
                 from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketNotification.h:30:7: note: forward declaration of ‘class Poco::Net::SocketReactor’
 class SocketReactor;
       ^
In file included from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:0:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h: In member function ‘void Poco::Net::SocketAcceptor<ServiceHandler>::onAccept(Poco::Net::ReadableNotification*)’:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:154:12: error: invalid use of incomplete type ‘class Poco::Net::SocketReactor’
   _pReactor->wakeUp();
            ^
In file included from /home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketAcceptor.h:22:0,
                 from /home/damon/catkin_ws/src/adsim/src/ws.cpp:2:
/home/damon/poco-1.8.0.1-all/Net/include/Poco/Net/SocketNotification.h:30:7: note: forward declaration of ‘class Poco::Net::SocketReactor’
 class SocketReactor;
       ^
adsim/CMakeFiles/pub_ws.dir/build.make:62: recipe for target 'adsim/CMakeFiles/pub_ws.dir/src/ws.cpp.o' failed
make[2]: *** [adsim/CMakeFiles/pub_ws.dir/src/ws.cpp.o] Error 1
CMakeFiles/Makefile2:883: recipe for target 'adsim/CMakeFiles/pub_ws.dir/all' failed
make[1]: *** [adsim/CMakeFiles/pub_ws.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

Compilation exited abnormally with code 1 at Tue Dec 19 10:47:42
`

`gcc --version
gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

I found SocketReactor missing from SocketAcceptor.h, and if I add #include "Poco / Net / SocketReactor.h", the problem can be solved.

**Comment by damon-kwok** [comment]
@aleks-f
 i need add #include "Poco / Net / SocketReactor.h" to SocketAcceptor.h,then the problem can be solved. 
SocketAcceptor.h use the SocketReactor.h, but not include,Is this a bug?
