### ISSUE TITLE
Synchronization issue in Poco::Util::Timer at destruction

### ISSUE THREAD

**Issue by SebastianTaube** [pocoproject/poco#2058]
#### Expected behavior
When on a Timer object `cancel()` is called and the object is deleted immediately afterwards, the object's destructor should return.
#### Actual behavior
Dependent on scheduler behavior, constructor returns or is stuck at `_thread.join();`
#### Steps to reproduce the problem
When calling `cancel()` and deleting the Timer object immediately afterwards, first `CancelNotification` is enqueued by `cancel()` and afterwards `StopNotification` is enqueued by `~Timer()`. If inbetween there was no rescheduling to the Timer's thread, the following happens, once the thread is running again:

Due to the execution of `CancelNotification` the `_queue` is being cleared, so the `StopNotification` is being deleted without being executed. As a result, the thread's while loop is not left and `_thread.join();` in `~Timer()` is blocking forever.
#### POCO version
1.7.2
#### Compiler and version
Visual Studio 2015
#### Operating system and version
Windows 7 Build 7601

**Comment by aleks-f** [comment]
I see two solutions:

1) not relying on return from `StopNotification::execute()`, but have stop flag
2) in `CancelNotification`, examine the queue to prevent inadvertent removal of `StopNotification`

But that's just from me reading the code, there may be better solutions.

**Comment by obiltschnig** [comment]
The correct way would be to call `cancel(true)` in that case, which will block until the `CancelNotification` has been processed.
