### ISSUE TITLE
Crash when executing HTTPSClientSession 

### ISSUE THREAD

**Issue by WeiChungChang** [pocoproject/poco#2060]
#### Expected behavior

I built 2 version applications to use HTTPSClientSession.

1st: static link - works fine,
2nd: dynamically link - **crash as**
```
 terminate called after throwing an instance of 'Poco::Net::SSLException'
  what():  SSL Exception
Aborted (core dumped)
```
**They are both built from the same version of Poco and use the same version of libssl & libcrypto.**

#### Actual behavior

Crashed but should not crash when dynamically link.

#### Steps to reproduce the problem

https://drive.google.com/open?id=1QbYpcRiUn0IKKtEZZiTtaf3zZVrce1cV

There are 2 folders. Compile them respectively & execute them by indicating the lib path.

**LD_LIBRARY_PATH="./lib/:$LD_LIBRARY_PATH" ./test**

#### POCO version

poco-1.8.0.1-all

#### Compiler and version

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#### Operating system and version

Ubuntu 5.4.0-6ubuntu1~16.04.5

**Comment by aleks-f** [comment]
A couple of things I noticed (I did not try to build and run):

- your link order is not correct and it seems that you are trying to work around that with `--unresolved-symbols=ignore-in-shared-libs`; Util depends on XML and JSON, so PocoXML and PocoJSON must be **after** PocoUtil

- you are mixing release and debug libs, which may or may not cause problems
