### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by amei** [pocoproject/poco#2061]
#### Expected behavior
It can link success!

#### Actual behavior
we build pocofundation.a   pocoxml.a   poconet.a, then we link those three files in our project. but they give our link error. error like this:

../thirdparties/custom/WeLink/lib/libPocoNet.a(HTTPBufferAllocator.o):HTTPBufferAllocator.cpp:function Poco::Net::HTTPBufferAllocator::allocate(int): error: undefined reference to 'Poco::MemoryPool::get()'
../thirdparties/custom/WeLink/lib/libPocoNet.a(HTTPBufferAllocator.o):HTTPBufferAllocator.cpp:function Poco::Net::HTTPBufferAllocator::deallocate(char*, int): error: undefined reference to 'Poco::MemoryPool::release(void*)'
...

POCO version
60

**Comment by aleks-f** [comment]
> we build pocofundation.a pocoxml.a poconet.a, then we link those three files in our project. but they give our link error

Try

```
PocoXML.a PocoNet.a PocoFoundation.a
```

in that order. 

See [Why does the order in which libraries are linked sometimes cause errors in GCC?
](https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc#409470) for explanation why.

For future reference - posting the build command line would have been much more helpful than dumping pages of link errors.
