### ISSUE TITLE
Can contributors use C++ 11 keywords?

### ISSUE THREAD

**Issue by dylankenneally** [pocoproject/poco#2063]
General query for those wanting to send a pull request... can we use C++11 keywords, such as [`override` ](http://en.cppreference.com/w/cpp/language/override) and [`= default` (constructors)](http://en.cppreference.com/w/cpp/language/default_constructor) etc.?

Ref.  #1793

**Comment by obiltschnig** [comment]
Yes, for everything that goes into develop/2.0. No for 1.x branches.
