### ISSUE TITLE
[Question] Can we choose DNS server to use while resolving?

### ISSUE THREAD

**Issue by MasterGroosha** [pocoproject/poco#2066]
Currently I'm using `resolve` method from [Poco::DNS](https://pocoproject.org/docs/Poco.Net.DNS.html) to resolve hostnames to IPs. Is Poco using system DNS settings for that? Is it possible to change used DNS server to resolve?

#### POCO version
1.8.0.1
#### Compiler and version
gcc 5.4.0
#### Operating system and version
Ubuntu 16.04

**Comment by obiltschnig** [comment]
Poco uses the system-provided DNS resolver so you cannot specify the DNS server.

**Comment by MasterGroosha** [comment]
Thank you, @obiltschnig, this answers my question.

**Comment by yegorich** [comment]
Can I get the system-provided DNS server addresses and default gateway the same way I can get interface's IP, netmask etc.?
