### ISSUE TITLE
Signout problem with Poco

### ISSUE THREAD

**Issue by monhi** [pocoproject/poco#2074]
#### Expected behavior
After signout when I press back button in chrome, I expect page does not come back to previous pages. 
In this way authentication works.
#### Actual behavior
After signout when I press back button in chrome, page comes back to previous one.
I add following line to the header of my html files but when I press back button it does not ask pocowebserver for previous page and autonomously goes to previous page. thus authentication is out of control.
 ```
<META Http-Equiv="Cache-Control" Content="no-cache"/>
<META Http-Equiv="Pragma" Content="no-cache"/>
<META Http-Equiv="Expires" Content="0"/>
```
I use cookies for session control and based on thus cookies I decide if somebody has logged in or not.

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.7.6

#### Compiler and version
visual studio 2013
#### Operating system and version
windows 8.1
#### Other relevant information
I just test my project with final version of Chrome web browser. 
I would like to see when somebody presses the back button in chrome, commands comes from web client to poco web server. but it does not happen.

**Comment by aleks-f** [comment]
This question really belongs to a Chrome forum. In any case, see [HTML Meta Tags and HTTP Headers](https://www.mnot.net/cache_docs/#META) for a good explanation on caching.

**Comment by monhi** [comment]
Yes, By using a meta tag in my HTML files, this problem resolves. 
Thanks a lot for comment,
