### ISSUE TITLE
Configuration: remove raw pointers from interfaces

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#2077]
Similar to Logging.

**Comment by aleks-f** [comment]
same as [here](https://github.com/pocoproject/poco/issues/2076#issuecomment-369418206), although more severe - there were duplicate `add` calls (non-shared and shared version), so adding AutoPtr overloads on top of that seemed like too much; I'm not quite sure why those overloads existed and I'm thinking everything should be shared, simpler and cleaner. If we decide that we really, really want to keep the pointer versions, then those can be reinstated, but I think internally (for Logging and Configuration) things should only be kept as AutoPtr

Note: valgrind reports tons of leaks from the new [PropertyListConfiguration](https://github.com/pocoproject/poco/pull/2184), I guess those should be resolved when [this issue](https://github.com/pocoproject/poco/issues/2075) is taken care of
/cc @DraconPern

**Comment by DraconPern** [comment]
Tracking.  Let me see if I can fix the memory leaks.
