### ISSUE TITLE
MinGW Issues

### ISSUE THREAD

**Issue by dylanetaft** [pocoproject/poco#2079]
Tried 1.8.0.1 core, 
- CMake outright won't build, 
- ./configure --no-tests --no-samples WILL build and install.  Fails on trying to build a simple program and link it
 g++ -std=c++11 main.cpp -o main -U__STRICT_ANSI__ -I/usr/local/include -L/usr/local/lib -lPocoFoundation -lPocoNet -lPocoJSON 
https://pastebin.com/Qu9SHVbW
- MinGW file in build/config OSARCH is hardcoded to i686.   I thought maybe that was maybe causing linking issues, tried switching it to x86_64, same linking issues

git master 
- will not build at all currently in mingw, CMake or ./configure
I am using MSYS2, MINGW GCC 7.2

So, all of these issues are technically separate.  I don't really care which method is used, as long as ONE works.  What is the right way to use Poco in MinGW?  I don't think it'd be productive to start dumping logs for all of the problems with each method.

**Comment by aleks-f** [comment]
try
```
g++ -std=c++11 main.cpp -o main -U__STRICT_ANSI__ -I/usr/local/include -L/usr/local/lib -lPocoNet -lPocoJSON -lPocoFoundation
```
see [Why does the order in which libraries are linked sometimes cause errors in GCC?
](https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc#409470) for an explanation

As for cmake, would need more details to tell what's going on, but the important thing is that Mingw is not officially supported - we currently do not have enough resources to support it. If you have a desire to step in and fill he void, we'll be glad to welcome you to the team :)

**Comment by dylanetaft** [comment]
Changing the link order didn't help
git master cmake builds fail because Thread_STD_WIN32.cpp isn't including <windows.h>, so functions like SetThreadPriority are not defined. There are more issues than that, thread->native_handle() returns an unsigned long long.  SetThreadPriority expects a HANDLE which is void *

This seems impossible to support, unless one forgoes any native thread functionality and just relies on std::thread.

I made an attempt but I think getting this working is behind my skill.

**Comment by dylanetaft** [comment]
No good, it gets past that but bombs later, IP_ADAPTER_ADDRESSES_XP has no member named ReceiveLinkSpeed for NetworkInterface.cpp:1187:46

Or TransmitLinkSpeed for NetworkInterface.cpp:1187:80

Both this problem and the problem above are indicative of MinGW not following MS's latest spec it looks.
As long as Poco offers all of this functionality, it's probably not going to ever be reliable with MinGW.

Both these things seem to be more of a MinGW issue.

**Comment by dylanetaft** [comment]
Reopening.  After some research, we should be passing in WIN32_WINNT=0x600 to get TransmitLinkSpeed and ReceiveLinkSpeed available in those structs.

It builds now with that CFLAG, + including windows.h in NetworkInterface.cpp
Still same trouble linking, any other suggestions?  It's 64 bit.
