### ISSUE TITLE
About version 1.8.1

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2083]
Version is ok, but from my point of view there are 3 things missing:

- SQLite Utility INT and INTEGER should be always 64bit len because sqlite can have INTEGER from 1 to 8 bytes len

- FTPS is still missing

- socket::select has the bug that with POCO_HAVE_FD_EPOLL in linux with gcc 4.9 can cause function bad behavior

**Comment by obiltschnig** [comment]
Do we have an issue for the select/epoll issue? If not, please create one for 1.8.2. FTPS should go into 1.9.0.

**Comment by micheleselea** [comment]
For select/epoll I think there's already a fix https://github.com/pocoproject/poco/issues/2080
