### ISSUE TITLE
https://secure.appinf.com/public/poco/NetSSL.txt seems to be unavailable

### ISSUE THREAD

**Issue by Burgch** [pocoproject/poco#2086]
#### Expected behavior

testInterop passes.

#### Actual behavior

It fails because that page isn't available.

#### Steps to reproduce the problem

Run test

#### POCO version

Any

#### Compiler and version

Any

#### Operating system and version

Any

#### Other relevant information

Seemed fine a few days ago.

**Comment by obiltschnig** [comment]
We're currently doing some work in our IT infrastructure, so secure.appinf.com is temporarily unavailable.

**Comment by Burgch** [comment]
Thanks!
