### ISSUE TITLE
Exception during Zip file decompression

### ISSUE THREAD

**Issue by Ubiquite** [pocoproject/poco#2098]
When I open a zip file generated with the FMI matlab Tool Box I receive an exception : 
**Illegal state: Illegal header in zip file**

Here is the code : 
```
int main(void)
{
    try
    {
        Poco::File temporary_directory = Poco::TemporaryFile::tempName();
        temporary_directory.createDirectory();

        std::ifstream inp("C:/dev/untitled.fmu", std::ios::binary);
        Poco::Zip::Decompress dec(inp, temporary_directory.path());
        dec.decompressAllFiles();
    }
    catch (Poco::IllegalStateException &e)
    {
        std::cerr << e.displayText();
    }
    return 0;
}

```

[zip file](https://drive.google.com/file/d/1WpfW0FwGdRulVHKdtFJjjDnqgmmjMrjI/view?usp=sharing)

#### POCO version
1.7.9
#### Compiler and version
Visual 2013 64bits
#### Operating system and version
Windows 10 64 bits
#### Other relevant information

Maybe the zip file is wrongly formed but of course I can open it with anything but POCO.

**Comment by aleks-f** [comment]
@Ubiquite see #1892 , please try to upgrade to 1.8.1 and se if the error persists
