### ISSUE TITLE
POCO SQLite Data Connector hangs for 20 secs waiting for thread timeouts on Windows

### ISSUE THREAD

**Issue by Framnk** [pocoproject/poco#2108]
#### Expected behavior
When using the SQLite connector it should free resources in a timely fashion.

#### Actual behavior
Simply creating a SQLite session to a local file then closing the session will result in a 20 sec delay on Windows when destroying the session.  This is noticeable when using the SQLite data connector from a Windows DLL and it hangs for 20 secs on unloading.

#### Steps to reproduce the problem

Create a Windows DLL containing the following code:

```
Poco::Data::SQLite::Connector::registerConnector();
Poco::Data::Session* session = new Poco::Data::Session("SQLite", <some local db>);
session->close();
delete session;
```

#### POCO version
Reproduced in POCO 1.8.1

#### Compiler and version
Visual C++ with v120 runtimes

#### Operating system and version
Windows 10

#### Other relevant information
This does not appear to be a connect or login timeout as I can see the connect succeed immediately, it appears to be an issue with how the SQLite connector is using thread pooling.  The SQLite connector creates two thread pool threads and when the SQLite session is closed and destroyed, the thread pool is left to clean itself up and internally each pooled thread has a 10 second wait timeout before deletion occurs.  It would be better if the SQLite connector could signal the threads when the session is closed to allow these threads to exit without waiting for timeout to occur.

**Comment by aleks-f** [comment]
Where is the thread pool in Poco SQLite connector?

The problem is likely the the explicit call to `close()`? SQLite session [destructor](https://github.com/pocoproject/poco/blob/poco-1.8.1/Data/SQLite/src/SessionImpl.cpp#L69) calls it, so it ends up being called twice.

**Comment by Framnk** [comment]
Hi, removing the explicit call to session->close() does not seem to alleviate the issue.

The use of thread pooling appears to be coming from the ActiveConnector type used when the sqlite connector attempts to connect to the DB.  This ends up running the connect in a thread pool thread which subsequently hangs around until it times out (10 seconds) when the module is unloaded.  I haven't figured out where the second thread that is hanging is getting created...

**Comment by aleks-f** [comment]
Ok, ActiveConnection was added by me [9 years ago](https://github.com/pocoproject/poco/commit/68a79674c1c96860d33a4be7a13760031e8074ef#diff-8f3edcaf3959949042145cc3847d024a), based on an issue that was filed on sourceforge at the time and I do not remember details. I have never experienced the described problem and I will try to reproduce it as soon as time permits. if you need fix urgently, the best path is to find the root cause and send pull with a fix.

**Comment by mkrivos** [comment]
Maybe not related, but I have very similar behaviour with our sqlite application (other application are OK).

I am attaching some screenshots from VS debugger, maybe helps ...

![obrazok](https://user-images.githubusercontent.com/3612515/35796734-c1e97682-0a5d-11e8-8479-b26824a9b7ad.png)

Application is after main(), probably in destruction of global objects, ~ThreadPoolSingletonHolder, waits for thread #2, but process has only one thread. Is this correct state?

**Comment by aleks-f** [comment]
I don't know how exactly does this happen, but looking at the commit referenced above, I'm thinking I was probably being too clever - trying to create a threaded timeout handling where none is needed most of the time. In any case, this can probably be handled differently, by just looping for a while calling sqlite3_open.
