### ISSUE TITLE
SSL certificate verify failed 14090086

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2114]
I found a strange issue about SSL verify: to be honest sometime happens in last 2/3 year but did not found a reason.
The application make an HTTPS request to different HTTPS hosts a lot's of time during runtime. All works good and usually I use HTTPSClientSession with no certificate verification VERIFY_NONE. I found that sometimes the software reach a "strange" state that cause all the HTTPS connections giving me:
`SSL Exception: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed`
Not just on one hostname but it's seems on all HttpsClientSessions
After restarting software all works good.
I made some test on datetime trying to modify datetime in past or in the future while software is running but with no success in reproduce error.
It's like HttpsClientSession has some kind of global "context" that become inconsistent.
In that situation killing HttpsClientSession and recreate it do not solve problem.
Do you ever get this behavior? What kind of walkaround can I try with poco lib to recover issue? can I cleanup some global SSL context or status or structures?

**Comment by obiltschnig** [comment]
Strange. Poco itself does not use any global/shared state in NetSSL_OpenSSL. But OpenSSL might.

**Comment by micheleselea** [comment]
That was my thought too...I do not understand...the problem I think it happens in the SSL_connect function, but I do not understand why restarting software make the connection works...

**Comment by micheleselea** [comment]
And another strange thing is: if I configure context with VERIFY_NONE how could be possible that ssl lib give me "certificate verify failed" it makes no sense

**Comment by obiltschnig** [comment]
Do you use the same `Poco::Net::Context` object for all `HTTPSClientSessions` instances?

**Comment by micheleselea** [comment]
yes the same context for all https connections

**Comment by micheleselea** [comment]
```
SharedPtr<InvalidCertificateHandler> ptrCert = new AcceptCertificateHandler(false);//Always accept
	Context::Ptr ptrContext = new Context(Context::CLIENT_USE,
		"",
		"",
		"",
		Context::VERIFY_NONE,
		9,
		bLoadCAFromDefaultPath,
		sCypherList);
	SSLManager::instance().initializeClient(0, ptrCert, ptrContext);
```

**Comment by obiltschnig** [comment]
So that's definitely a candidate worth looking into. You could try using separate `Context` objects and see if it helps. Then we at least know what to look into further.

**Comment by micheleselea** [comment]
So you suggest to use a different Context created every https request?

**Comment by obiltschnig** [comment]
Yes, worth a try.
