### ISSUE TITLE
Poco::DateTime constructed from TIMEVAL_MAX is time min

### ISSUE THREAD

**Issue by mcblady** [pocoproject/poco#2122]
#### Expected behavior
Poco::DateTime constructed from TIMEVAL_MAX should be very very far in the future

#### Actual behavior
Poco::DateTime constructed from TIMEVAL_MAX is 1.1.1970

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#include "Poco/DateTime.h"
const Poco::Timestamp::TimeVal timeMax = Poco::Timestamp::TIMEVAL_MAX;
Poco::DateTime dateTimeMax { Poco::Timestamp(timeMax) };

if (dateTimeMax < Poco::DateTime()) {
//Error
}
else {
//Correct
}

#### POCO version
1.8.0.1-all (2017-11-11)

#### Compiler and version
VS 2017 (not important)

#### Operating system and version
Windows 7 (not important)

**Comment by micheleselea** [comment]
Probably the issue is in line
```
_utcTime(timestamp.utcTime())
```
