### ISSUE TITLE
Poco SSL exception during https get request

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#2125]
#### Expected behavior
Https Response: status= 200, reason= OK
#### Actual behavior
Sometimes I after many successful 200 ok response I get many consecutive "Poco Exception Code: 0 Name: SSL Exception"
#### Steps to reproduce the problem
I just created a httpsclient session:
```
    const Context::Ptr ctx = new Context(Context::CLIENT_USE, "", "", "", Context::VERIFY_NONE, 9, false, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
	HTTPSClientSession session(_uri.getHost(), _uri.getPort(), ctx);
	HTTPRequest request(HTTPRequest::HTTP_GET, path, HTTPMessage::HTTP_1_1);
```
#### POCO version
1.7.8-2
#### Compiler and version
gcc 4.9.2 armhf
#### Operating system and version
armbian debian jessie 
#### Other relevant information
I have the default timeout which is 60s I assume. Is this a timeout due to busy server which get the request or something else? Is there anything I can with my code to minimize these events?

**Comment by vfjpl** [comment]
Is this a bug or I just don't know how to use this class? How does this class behave when the certificate is invalid? Some more descriptic error would be nice. And some documentation updates.
