### ISSUE TITLE
Crypto: Add support for AES-GCM ciphers.

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#2129]
- [ ] Add `EVP_CIPH_GCM_MODE` in `CipherKeyImpl::Mode` and `mode()`. Other newer EVP_CIPH_* possibly too.
- [ ] Make `Cipher` work when passing in "aes-256-gcm" cipher name.

**Comment by SmileGobo** [comment]
This solution use only default size(12) for init vector. After setup by Poco::Crypto::ChiperKey::setIV vector a different size( size != 12) yoy have Exception. If use constructor Poco::Crypto::ChiperKey::ChiperKey with init vector grater size (size > 12) end will be ignored!
