### ISSUE TITLE
compilation error while building poco on solaris 11 sparc

### ISSUE THREAD

**Issue by shradha741** [pocoproject/poco#2131]
#### Expected behavior
clean Poco build
#### Actual behavior
Poco build failing.
"src/ECKeyImpl.cpp", line 88: Error: Could not find a match for Poco::Crypto::EVPPKey::loadKey<Poco::Crypto::EVPPKey::K, Poco::Crypto::EVPPKey::F>(ec_key_st**, extern "C" evp_pkey_st*(__FILE*,evp_pkey_st**,extern "C" int(*)(char*,int,int,void*),void*), extern "C" ec_key_st*(evp_pkey_st*), const std::string, const std::string ) needed in Poco::Crypto::ECKeyImpl::ECKeyImpl(const std::string &, const std::string &, const std::string &).
"src/ECKeyImpl.cpp", line 97: Error: Could not find a match for Poco::Crypto::EVPPKey::loadKey<Poco::Crypto::EVPPKey::K, Poco::Crypto::EVPPKey::F>(ec_key_st**, extern "C" evp_pkey_st*(__FILE*,evp_pkey_st**,extern "C" int(*)(char*,int,int,void*),void*), extern "C" ec_key_st*(evp_pkey_st*), const std::string ) needed in Poco::Crypto::ECKeyImpl::ECKeyImpl(const std::string &, const std::string &, const std::string &).
"src/ECKeyImpl.cpp", line 111: Error: Could not find a match for Poco::Crypto::EVPPKey::loadKey<Poco::Crypto::EVPPKey::K, Poco::Crypto::EVPPKey::F>(ec_key_st**, extern "C" evp_pkey_st*(bio_st*,evp_pkey_st**,extern "C" int(*)(char*,int,int,void*),void*), extern "C" ec_key_st*(evp_pkey_st*), std::istream *, const std::string ) needed in Poco::Crypto::ECKeyImpl::ECKeyImpl(std::istream *, std::istream *, const std::string &).
"src/ECKeyImpl.cpp", line 120: Error: Could not find a match for Poco::Crypto::EVPPKey::loadKey<Poco::Crypto::EVPPKey::K, Poco::Crypto::EVPPKey::F>(ec_key_st**, extern "C" evp_pkey_st*(bio_st*,evp_pkey_st**,extern "C" int(*)(char*,int,int,void*),void*), extern "C" ec_key_st*(evp_pkey_st*), std::istream *) needed in Poco::Crypto::ECKeyImpl::ECKeyImpl(std::istream *, std::istream *, const std::string &).
4 Error(s) detected.
gmake[1]: *** [/home/sgupta5/.git/vcs_tpip/libpoco/src/Crypto/obj/SunOS/sun4v/debug_shared/ECKeyImpl.o] Error 2
gmake[1]: Leaving directory `/home/sgupta5/.git/vcs_tpip/libpoco/src/Crypto'
gmake: *** [Crypto-libexec] Error 2
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

**Comment by likedbyall** [comment]
Is there any update on this issue? I am also facing the same.

I just want to build static poco library using CC compiler v5.12 on Solaris 11 Sparc machine

My poco source directory is kept here:

/poco-1.9.4-all/< all modules are here like Foundation, Crypto, etc >

OpenSSL headers (openssl1.1.1) are kept at:

/poco-1.9.4-all/Crypto/include/openssl

I am using following export variables:

export OSARCH_64BITS=1

export POCO_BASE="/poco-1.9.4-all"

Configuration is done as follows:

./configure --config=SunOS-SunStudio11 --omit=CppUnit,Data,Data/SQLite,Data/MySQL,Data/ODBC,Zip,PageCompiler,PageCompiler/File2Page, --cflags=-KPIC --static --no-tests --no-samples

Getting below errors in Crypto module:

** Compiling src/ECKeyImpl.cpp (debug, shared)

CC -Iinclude -I/poco-1.9.4-all/CppUnit/include -I/poco-1.9.4-all/CppUnit/WinTestRunner/include -I/poco-1.9.4-all/Foundation/include -I/poco-1.9.4-all/Encodings/include -I/poco-1.9.4-all/XML/include -I/poco-1.9.4-all/JSON/include -I/poco-1.9.4-all/Util/include -I/poco-1.9.4-all/Net/include -I/poco-1.9.4-all/Crypto/include -I/poco-1.9.4-all/NetSSL_OpenSSL/include -I/poco-1.9.4-all/Data/include -I/poco-1.9.4-all/Data/SQLite/include -I/poco-1.9.4-all/Data/ODBC/include -I/poco-1.9.4-all/Data/MySQL/include -I/poco-1.9.4-all/Zip/include -I/poco-1.9.4-all/PageCompiler/include -I/poco-1.9.4-all/PageCompiler/File2Page/include -I/poco-1.9.4-all/MongoDB/include -I/poco-1.9.4-all/Redis/include -mt -library=stlport4 -erroff=hidevf -DPOCO_BUILD_HOST='"'vlicsol11sparcbld1'"' -DPOCO_TARGET_OSNAME='"'SunOS'"' -DPOCO_TARGET_OSARCH='"'sun4v'"' -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -D_POSIX_C_SOURCE=199506L -D__EXTENSIONS__ -m64 -g -xs -D_DEBUG= -KPIC -c src/ECKeyImpl.cpp -o /poco-1.9.4-all/Crypto/obj/SunOS/sun4v/debug_shared64/ECKeyImpl.o

"src/ECKeyImpl.cpp", line 85: Error: Could not find a match for Poco::Crypto::EVPPKey::loadKey(ec_key_st**, extern "C" evp_pkey_st*(__FILE*,evp_pkey_st**,extern "C" int()(char,int,int,void*),void*), extern "C" ec_key_st*(evp_pkey_st*), const std::string, const std::string ) needed in Poco::Crypto::ECKeyImpl::ECKeyImpl(const std::string &, const std::string &, const std::string &).

"src/ECKeyImpl.cpp", line 94: Error: Could not find a match for Poco::Crypto::EVPPKey::loadKey(ec_key_st**, extern "C" evp_pkey_st*(__FILE*,evp_pkey_st**,extern "C" int()(char,int,int,void*),void*), extern "C" ec_key_st*(evp_pkey_st*), const std::string ) needed in Poco::Crypto::ECKeyImpl::ECKeyImpl(const std::string &, const std::string &, const std::string &).

"src/ECKeyImpl.cpp", line 108: Error: Could not find a match for Poco::Crypto::EVPPKey::loadKey(ec_key_st**, extern "C" evp_pkey_st*(bio_st*,evp_pkey_st**,extern "C" int()(char,int,int,void*),void*), extern "C" ec_key_st*(evp_pkey_st*), std::istream *, const std::string ) needed in Poco::Crypto::ECKeyImpl::ECKeyImpl(std::istream *, std::istream *, const std::string &).

"src/ECKeyImpl.cpp", line 117: Error: Could not find a match for Poco::Crypto::EVPPKey::loadKey(ec_key_st**, extern "C" evp_pkey_st*(bio_st*,evp_pkey_st**,extern "C" int()(char,int,int,void*),void*), extern "C" ec_key_st*(evp_pkey_st*), std::istream *) needed in Poco::Crypto::ECKeyImpl::ECKeyImpl(std::istream *, std::istream *, const std::string &).

"src/ECKeyImpl.cpp", line 238: Error: The function "strncmp" must have a prototype.

5 Error(s) detected.

Please help. I have browsed entire Internet but didn't find a fix for it. I am also not sure if poco-1.9.4 is compatible with solaris 11 sparc with CC v5.12 or not.
