### ISSUE TITLE
Poco::Net::Context load certificate from string

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2139]
I think should be nice to have Poco::Net::Context to load private key and certificate even from memory buffer or string as well as from file as already does

**Comment by obiltschnig** [comment]
You can load a X509Certificate and a RSAKey from an std::istream, then pass it on to a Context created without a certificate.

**Comment by micheleselea** [comment]
ah...sounds good, I did not found that functions, I'll dig in the Context class, thanks
