### ISSUE TITLE
Poco::PDF

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2154]
I have a question about PDF library. I know is not released, but I'm using it and it's nice. Do you think it's possible to format html to make a table 2x2 with inside 4 images one in each table cell?
can you help me to find out the right syntax?

**Comment by aleks-f** [comment]
Look at the [Template](https://github.com/pocoproject/poco/blob/develop/PDF/samples/Template/src/Template.cpp) example. The functionality was aded recently; it uses HTML table as template, currently you can only put text in tables, but it shouldn't be too hard to add images capability. Send a pull if you if you get it working.

**Comment by micheleselea** [comment]
I made some little changes to use a "relative position" of the images and for configuring h using w and aspect ratio. I even put the code to load bmp images. If you want, when I finish the work, I can send a pull request

**Comment by obiltschnig** [comment]
please ;-)

**Comment by micheleselea** [comment]
I take source from bmp reading from 
https://github.com/chazomaticus/libbmpread
is that ok for PocoLib?

**Comment by obiltschnig** [comment]
zlib license should be OK.
