### ISSUE TITLE
Question on the ProxyRequestPrefix functions 

### ISSUE THREAD

**Issue by buddingspacer** [pocoproject/poco#2156]
Many thanks
I'm trying to understand the difference in the ProxyRequestPrefix functions for HTTPClientSession & HTTPSClientSession  classes?

HTTPClientSession::ProxyRequestPrefix  here it does the actual ProxyRequestPrefix of host & port number.
But the HTTPSClientSession::ProxyRequestPrefix actually returns empty string

We set the URI in the request to be http://x.x.x.x:yyyy:/test/test2
so poco when sending to proxy adds http://x.x.x.x:yyyy/https://x.x.x.x:yyyy:/test/test2
Because of this http request gets rejected by proxy server( with 400 Bad Request) , while the connection made via https get passed in the proxy.

Poco version used: 1.7.8

**Comment by obiltschnig** [comment]
You should set the URI in the request to `/test/test2`, not `http://x.x.x.x:yyyy/test/test2`.

**Comment by obiltschnig** [comment]
The reason why this works with HTTPS is that when using HTTPS through a proxy the client first creates a tunnel through the proxy (via CONNECT), then sends the HTTPS request through the tunnel. For HTTP, the client needs to prepend `http://host:port` to the URI, which will produce an invalid URI if the URI already contains this.

**Comment by buddingspacer** [comment]
Thanks much @obiltschnig for clarifying.
