### ISSUE TITLE
JSON module does not compile for Windows CE using vs2008

### ISSUE THREAD

**Issue by rohaanhamid** [pocoproject/poco#2159]
#### Expected behavior
JSON for Windows CE does not compile using vs90 (vs2008) .

#### Actual behavior
JSON for Windows CE should compile using vs90 (vs2008) .

#### Steps to reproduce the problem
pd_json is unable to resolve "strerror_s" and "errno" in pd_json.c

#### POCO version
Version 1.8.1

#### Compiler and version
vs 2008 SP1 with the Windows CE SDK

#### Operating system and version
Windows CE

#### Other relevant information
None

**Comment by aleks-f** [comment]
those will likely have to be taken from [wcelibcex](https://github.com/pocoproject/poco/tree/develop/Foundation/wcelibcex-1.0) (errno and [strerror](https://github.com/pocoproject/poco/blob/develop/Foundation/wcelibcex-1.0/src/wce_strerror.c#L54), although it's a non-op there). I don't have time at the moment, if you need it urgently, fix it and send a pull.

**Comment by aleks-f** [comment]
should be enough to ifdef [here](https://github.com/pocoproject/poco/blob/poco-1.8.1/JSON/src/pd_json.c#L8) and [here](https://github.com/pocoproject/poco/blob/poco-1.8.1/JSON/src/pd_json.c#L15)

**Comment by rohaanhamid** [comment]
Thank you so much. I was able to compile JSON using your suggestion. 

If you get a chance please look at #2162. Its a weird one and I can't get around it. I want to really want to use POCO for my project and XML is the last library I can't compile.
