### ISSUE TITLE
Unable to compile Foundation module using VS2008 

### ISSUE THREAD

**Issue by rohaanhamid** [pocoproject/poco#2160]
#### Expected behavior
Foundation module does not compile successfully

#### Actual behavior
Foundation module should compile successfully

#### Steps to reproduce the problem
This issue is a duplicate of #1834. I used the steps mentioned in issue to resolve my problem

#### POCO version
1.8.1

#### Compiler and version
VS 2008

#### Operating system and version
Windows CE and Windows

**Comment by obiltschnig** [comment]
For me 1.9.0 builds ok with VS2008
