### ISSUE TITLE
POCO XML does not compile for Windows CE with VS 2008

### ISSUE THREAD

**Issue by rohaanhamid** [pocoproject/poco#2162]
#### Expected behavior
POCO XML should compile for Windows CE with VS 2008

#### Actual behavior

I am trying to build the debug_static_md version and and throws the following error:

"Poco/Platform_WIN32.h(146) : fatal error C1189: #error :  Inconsistent build settings (check for /MD[d])"
The release_static_md configuration seems to compile fine.  
The file before this error is xmlparse.cpp and the file after is TreeWalker.cpp

I am not sure what could be causing this. The preprocessor definitions seem to be fine.

*** EDIT: WORKAROUND FOR COMPILING UTIL WITHOUT XML ***
I only needed to compile XML because the Application package in the UTIL module depends on it for its XMLConfiguration. In case you are in the same position, you can remove the dependency on XML by specifying POCO_UTIL_NO_XMLCONFIGURATION when compiling UTIL.

#### Steps to reproduce the problem
Compile debug_static_md using vs 2008 for Windows CE

#### POCO version
1.8.1

#### Compiler and version
VS 2008 SP1 with WINCE SDK

#### Operating system and version
Windows CE

**Comment by Rune-Thers** [comment]
Try to add DEBUG to the Preprocessor Definitions. I think only _DEBUG is added and a default CE project have both DEBUG and _DEBUG defined.

**Comment by aleks-f** [comment]
Also, try to upgrade the compiler ... it's been 10 years and 2008 does not even support C99, VS2008 support will most likely be gone in 1.9.1
