### ISSUE TITLE
RemoteSyslogChannel should allow the RFC 5424 STRUCTURED-DATA field to be set

### ISSUE THREAD

**Issue by ewoudenberg-jibo** [pocoproject/poco#2173]
#### Expected behavior

A means should be available when logging messages through RemoteSyslogChannel for the STRUCTURED-DATA field of RFC 5424 (syslog) messages to be set.

#### Actual behavior

The STRUCTURED-DATA field is not only not possible to set, the RemoteSyslogChannel message formatter does not put the required "-" in the empty STRUCTURED-DATA field. This fact causes the generated messages to be out of compliance with RFC 5424.

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

A capability is missing -- no demonstration possible.

#### POCO version

1.8.2

#### Compiler and version

All

#### Operating system and version

All

#### Other relevant information

RFC 5424 STRUCTURED-DATA description: https://tools.ietf.org/html/rfc5424#page-15

**Comment by obiltschnig** [comment]
Hm, given that RFC 5424 is dated March 2009 and RemoteSyslogChannel was done in 2006/2007, this must mean that an early draft of RFC 5424 has been used. Also, RemoteSyslogListener has the same issue.

Will use Message parameters to implement SD.

**Comment by ewoudenberg-jibo** [comment]
Thank you @obiltschnig -- I have a change to the output formatter that simply outputs the message parameter named "structured-data" in that field (if available, otherwise "-"), but I haven't done the change to the parser (RemoteSyslogListener.cc) which is why I have not submitted the PR yet. Would you accept the PR without the parser change?

Also, you can imagine a better implementation (better than just looking for a  "structured-data" parameter in a message) where the message parameter keys are dot delimited and the prefix before the dot selects the membership in, and name of, the multiple SD blocks to be output in SD field.

I'm happy to help out or discuss it further.
