### ISSUE TITLE
Poco process library holding onto processes

### ISSUE THREAD

**Issue by ericcurtin** [pocoproject/poco#2176]
#### Expected behavior
Poco should let go of processes and not leave them in defunct state. wait() is never ending.

#### Actual behavior
It only happens sometimes. Poco is leaving zomie processes around and holding onto them forever.

#### Steps to reproduce the problem
Install my tool https://github.com/ericcurtin/sxx
Create a file similar to an ansible hosts file in /etc/sxx/hosts (or symlink an existing ansible one)
Run a command like sxx username@some_group_of_servers "some long running bash command"

#### POCO version
The Ubuntu 16.04 one
libpoco-dev/xenial,now 1.3.6p1-5.1build1 amd64 [installed]
libpoco-doc/xenial,xenial 1.3.6-1 all
libpococrypto9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpococrypto9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpocodata9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpocodata9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpocofoundation9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpocofoundation9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpocomysql9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpocomysql9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpoconet9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpoconet9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpoconetssl9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpoconetssl9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpocoodbc9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpocoodbc9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpocosqlite9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpocosqlite9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpocoutil9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpocoutil9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpocoxml9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpocoxml9v5-dbg/xenial 1.3.6p1-5.1build1 amd64
libpocozip9v5/xenial,now 1.3.6p1-5.1build1 amd64 [installed,automatic]
libpocozip9v5-dbg/xenial 1.3.6p1-5.1build1 amd64

#### Compiler and version
g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#### Operating system and version
xubuntu

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by ericcurtin** [comment]
sxx tool doesn't quit as is waiting for:

```
curtine  10046 10045  0 13:35 pts/6    00:00:00 [ssh] <defunct>
curtine  10047 10045  0 13:35 pts/6    00:00:00 [ssh] <defunct>
curtine  10048 10045  0 13:35 pts/6    00:00:00 [ssh] <defunct>
```

processes to complete and they never do.

**Comment by ericcurtin** [comment]
Easy to reproduce. but doesn't happen everytime

**Comment by ericcurtin** [comment]
I think I'll give Boost Process a try in the meantime to see if it suffers from the same problem... Was hoping to use Poco as my primary C++ lib though, the glob implementation works great!

**Comment by aleks-f** [comment]
@mikedld may be able to help, i vaguely remember the discussion around it some time ago, but can't remember details.

**Comment by aleks-f** [comment]
here's a couple of issues, but to fix it, we'd need someone to look into it good and send a pull, core devs are busy with other things currently:

https://github.com/pocoproject/poco/issues/1070
https://github.com/pocoproject/poco/issues/479

**Comment by ericcurtin** [comment]
This might actually be openssh bug:

https://bugzilla.mindrot.org/show_bug.cgi?id=1988

I'll test it out tomorrow

**Comment by ericcurtin** [comment]
Confirmed openssh bug, doesn't occur on openssh 7.3
