### ISSUE TITLE
Question: IPAddress.cpp operator >> overload and systems not supporting IPv6

### ISSUE THREAD

**Issue by lbakman** [pocoproject/poco#2194]
Poco version 1.8.1 (and develop branch as well)

The following method is defined in IPAddress.cpp:
```
Poco::BinaryReader& operator >> (Poco::BinaryReader& reader, Poco::Net::IPAddress& value)
{
	char buf[sizeof(struct in6_addr)];
	Poco::UInt8 length;
	reader >> length;
	reader.readRaw(buf, length);
	value = Poco::Net::IPAddress(buf, length);
	return reader;
}
```

Shouldn't the line "char buf[sizeof(struct in6_addr)];" be:
```
#if defined(POCO_HAVE_IPv6)
	char buf[sizeof(struct in6_addr)];
#else
	char buf[sizeof(struct in_addr)];
#endif
```

or alternatively:
`	char buf[Poco::Net::IPAddress::MAX_ADDRESS_LENGTH];`

to make sure that systems that do not support IPv6 are handled?

**Comment by aleks-f** [comment]
conceptually yes, but haven't heard of problems thereof. in any case, send a pull and we''l merge it

**Comment by lbakman** [comment]
I am currently building Poco (only Foundation and Net) for an embedded platform that does not support IPv4. I stumbled upon this in that process. 
I will create a pull request as soon as I have made sure that it builds for that platform.

**Comment by lbakman** [comment]
Created pull request for the change. Used poco-1.9.0 as our compiler (embedded) does not support C++11
#2203
