### ISSUE TITLE
Poco MD5 working incorrectly with Openssl in FIPS mode

### ISSUE THREAD

**Issue by AbhinavBansal** [pocoproject/poco#2195]
Hi, 
I am building POCO in static mode and linking with Openssl as a dynamic library.

When I enable FIPS mode by calling `FIPS_mode_set(1);`, I see that it is correctly enabled and even Poco 's API `Poco::Net::SSLManager::instance().isFIPSEnabled();` also returns that FIPS mode is enabled.

Now, I would expect MD5 and other FIPS forbidden APIs to not work. However `Poco::MD5Engine` does work. If I directly use MD5 APIs from `openssl/md5.h`, it fails as expected with error: `OpenSSL internal error, assertion failed: Low level API call to digest MD5 forbidden in FIPS mode!`

Poco working Code:
```
            Poco::MD5Engine md5;
            Poco::DigestOutputStream ostr(md5);
            ostr << data;
            ostr.flush();
            const Poco::DigestEngine::Digest& digest = md5.digest();
            auto v = std::string(digest.begin(), digest.end());
```

Is there anything special that I need to do for POCO to work correctly with FIPS mode? Any help will be appreciated.

**Comment by obiltschnig** [comment]
Poco::MD5Engine (and generally, all digest engines implemented in Poco::Foundation) is not implemented using OpenSSL, so it does not care about OpenSSL FIPS mode.

**Comment by AbhinavBansal** [comment]
oh ok. Thanks for this information
