### ISSUE TITLE
make install error (xmltok.c)

### ISSUE THREAD

**Issue by devjyc** [pocoproject/poco#2198]
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.8.0

#### Compiler and version
arm-arago-linux-gnueabi-g++ -v
Using built-in specs.
COLLECT_GCC=arm-arago-linux-gnueabi-g++
Target: arm-arago-linux-gnueabi
Configured with: /sim/scratch_a0850442/arago-tmp-arago/work/i686-armv7a-sdk-arago-linux-gnueabi/gcc-cross-sdk-4.5-r41.2+svnr170880/gcc-4_5-branch/configure --build=i686-linux --host=i686-linux --target=arm-arago-linux-gnueabi --prefix=/arago-2011.09/armv7a --exec_prefix=/arago-2011.09/armv7a --bindir=/arago-2011.09/armv7a/bin --sbindir=/arago-2011.09/armv7a/bin --libexecdir=/arago-2011.09/armv7a/libexec --datadir=/arago-2011.09/armv7a/share --sysconfdir=/arago-2011.09/armv7a/etc --sharedstatedir=/arago-2011.09/armv7a/share/com --localstatedir=/arago-2011.09/armv7a/var --libdir=/arago-2011.09/armv7a/lib --includedir=/arago-2011.09/armv7a/include --oldincludedir=/arago-2011.09/armv7a/include --infodir=/arago-2011.09/armv7a/share/info --mandir=/arago-2011.09/armv7a/share/man --enable-largefile --disable-nls --enable-ipv6 --with-gnu-ld --enable-shared --enable-languages=c,c++,objc,fortran --enable-threads=posix --disable-multilib --enable-c99 --enable-long-long --enable-symvers=gnu --enable-libstdcxx-pch --program-prefix=arm-arago-linux-gnueabi- --enable-target-optspace --enable-lto --enable-libssp --disable-bootstrap --disable-libgomp --disable-libmudflap --with-float=softfp --with-sysroot=/arago-2011.09/armv7a/arm-arago-linux-gnueabi --with-build-time-tools=/sim/scratch_a0850442/arago-tmp-arago/sysroots/i686-linux/usr/armv7a/arm-arago-linux-gnueabi/bin --with-build-sysroot=/sim/scratch_a0850442/arago-tmp-arago/sysroots/armv7a-arago-linux-gnueabi --disable-libunwind-exceptions --with-mpfr=/sim/scratch_a0850442/arago-tmp-arago/sysroots/i686-linux/usr --with-system-zlib --enable-__cxa_atexit
Thread model: posix
gcc version 4.5.3 20110311 (prerelease) (GCC)

#### Operating system and version
Ubuntu 16
#### Other relevant information

**poco 1.6.1 version cross compile is all OK.
but poco 1.8.0:
make is OK, but make install is FAIL.
what's problem? because gcc version?**

./configure --config=ARM-Linux --prefix=$PREFIX --static \
--sqlite-thread-safe=1 --omit=NetSSL_OpenSSL,Crypto,Data/ODBC,Data/MySQL \
--no-samples --no-tests

make install 
.
.
make -C /prj/build/poco/poco-1.8.1-all/XML
make[1]: Entering directory '/prj/build/poco/poco-1.8.1-all/XML'
** Compiling src/xmltok.c (release, static)
arm-arago-linux-gnueabi-gcc -Iinclude -I/prj/build/poco/poco-1.8.1-all/CppUnit/include -I/prj/build/poco/poco-1.8.1-all/CppUnit/WinTestRunner/include -I/prj/build/poco/poco-1.8.1-all/Foundation/include -I/prj/build/poco/poco-1.8.1-all/XML/include -I/prj/build/poco/poco-1.8.1-all/JSON/include -I/prj/build/poco/poco-1.8.1-all/Util/include -I/prj/build/poco/poco-1.8.1-all/Net/include -I/prj/build/poco/poco-1.8.1-all/Crypto/include -I/prj/build/poco/poco-1.8.1-all/NetSSL_OpenSSL/include -I/prj/build/poco/poco-1.8.1-all/Data/include -I/prj/build/poco/poco-1.8.1-all/Data/SQLite/include -I/prj/build/poco/poco-1.8.1-all/Data/ODBC/include -I/prj/build/poco/poco-1.8.1-all/Data/MySQL/include -I/prj/build/poco/poco-1.8.1-all/Zip/include -I/prj/build/poco/poco-1.8.1-all/PageCompiler/include -I/prj/build/poco/poco-1.8.1-all/PageCompiler/File2Page/include -I/prj/build/poco/poco-1.8.1-all/MongoDB/include -I/prj/build/poco/poco-1.8.1-all/Redis/include  -std=c99 -DPOCO_BUILD_HOST='"'ftrd'"' -DPOCO_TARGET_OSNAME='"'Linux'"' -DPOCO_TARGET_OSARCH='"'armv7l'"' -DSQLITE_THREADSAFE=1 -DXML_NS -DXML_DTD -DHAVE_EXPAT_CONFIG_H -DEXPAT_POCO -D_XOPEN_SOURCE=600 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL -DPOCO_HAVE_ADDRINFO -DPOCO_HAVE_LIBRESOLV  -O2 -DNDEBUG  -c src/xmltok.c -o /prj/build/poco/poco-1.8.1-all/XML/obj/Linux/armv7l/release_static/xmltok.o
In file included from src/xmltok.c:791:0:
src/xmltok_impl.c: In function 'little2_prologTok':
src/xmltok_impl.c:168:5: internal compiler error: in set_jump_prob, at stmt.c:2319
Please submit a full bug report,

**Comment by obiltschnig** [comment]
This is a problem of your (quite outdated) cross-compiler.
```
src/xmltok_impl.c:168:5: internal compiler error: in set_jump_prob, at stmt.c:2319
```
Nothing we can do here. I'd suggest getting a newer version of the Arago toolchain.

**Comment by devjyc** [comment]
thank you, obiltschnig
i got it, but i can't upgrade toolchain. :(
so, i will use poco 1.7.3 version that compiled last version.
