### ISSUE TITLE
Illegal header in zip file exception

### ISSUE THREAD

**Issue by EgorkaKulikov** [pocoproject/poco#2199]
Hello!
I am trying to open the archive [Installer.zip (https://github.com/pocoproject/poco/files/1781235/Installer.zip)
with POCO Zip Library version 1.8.1 on Windows 10 and I catch an exception "Illegal header in zip file".
I suppose that the reason is that byte in entry header on position 4E1B is zero but extra field in that zip entry exists.
Nevertheless, WinRar and 7Zip managed to decompress this archive. Can you help me to decompress it using POCO?

**Comment by obiltschnig** [comment]
Probably dup of #2188

**Comment by EgorkaKulikov** [comment]
@obiltschnig it is not a duplicate, but a different problem. Method IsDirectory works correctly, the difficulty is about extra field in header.

**Comment by obiltschnig** [comment]
That is also the case in the other issue.

**Comment by nikitso** [comment]
@obiltschnig I have the same problem as described above. Is there any patch available for it?

**Comment by obiltschnig** [comment]
OK, fix will be in 1.9.0. Funny thing, that. If a directory is stored with deflate compression method (which is stupid to begin with) there are two extra bytes after the filename which apparently are the result of deflating zero-length data.

**Comment by obiltschnig** [comment]
For reference, fix: 27dc684d774be7d0434b22ea690a1cfd00b35d0c

**Comment by EgorkaKulikov** [comment]
@obiltschnig I tried to decompress the archive attached to issue after your fix, but ZipArchive::parse still throws an exception.

**Comment by obiltschnig** [comment]
@EgorkaKulikov that's maybe because your Zip file is simply corrupted. It also fails to expand with macOS's built in unzip tool and I find no explanation for the extra data behind the local file header. It could be that unzip and others make a better effort of dealing with broken Zip files.

**Comment by obiltschnig** [comment]
OK, added a hack to try to resynchronize if no valid header is found. Now able to expand your file. Not happy with that, but that's just the way it is with Zip files, I guess.
