### ISSUE TITLE
Shared Library/DLL Names for Release 2.0

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#2200]
The names of shared libraries/DLLs for POCO 2.0 should use the Poco2 prefix:

  - libPoco2Foundation.so.n / Poco2Foundation.dll
  - libPoco2XML.so.n / Poco2XML.dll
  - etc.

Rationale: We can restart the shared library version number at 1, instead of 100 (and hope that 1.x releases won't catch up...).

**Comment by JackyWoo** [comment]
@obiltschnig I wanna take this task.
