### ISSUE TITLE
Cannot compile x64 build on Windows 10, Visual Studio v150.

### ISSUE THREAD

**Issue by DaManJ** [pocoproject/poco#2202]
#### Expected behavior
running the following should not have a problem ->

buildwin 150 build shared both x64 nosamples notests msbuild

#### Actual behavior

receive: error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'

Build started 3/6/2018 7:47:22 PM.
     1>Project "C:\Users\Backtest\source\Workspaces\globalprime\poco-1.8.1\CppUnit\CppUnit_x64_vs150.vcxproj" on node 1 (build target(s)).
     1>InitializeBuildStatus:
         Touching "obj64\debug_shared\CppUnit.tlog\unsuccessfulbuild".
       ClCompile:
         All outputs are up-to-date.
       Link:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX86\x86\link.exe /ERRORREPORT:QUEUE /OUT:"..\bin64\CppUni
         t64d.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc3
         2.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"..\bin64\CppUnit64d.pdb" /TLBID:1 /DYNAMICBAS
         E /NXCOMPAT /IMPLIB:"..\lib64\CppUnitd.lib" /MACHINE:X64 /DLL obj64\debug_shared\CppUnitException.obj
         obj64\debug_shared\TestCase.obj
         obj64\debug_shared\TestDecorator.obj
         obj64\debug_shared\TestFailure.obj
         obj64\debug_shared\TestResult.obj
         obj64\debug_shared\TestRunner.obj
         obj64\debug_shared\TestSuite.obj
         obj64\debug_shared\TextTestResult.obj
     1>obj64\debug_shared\CppUnitException.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [C:\Users\Backtest\source
       \Workspaces\globalprime\poco-1.8.1\CppUnit\CppUnit_x64_vs150.vcxproj]
     1>Done Building Project "C:\Users\Backtest\source\Workspaces\globalprime\poco-1.8.1\CppUnit\CppUnit_x64_vs150.vcxproj" (build target(s)) -- FAILED.

Build FAILED.

       "C:\Users\Backtest\source\Workspaces\globalprime\poco-1.8.1\CppUnit\CppUnit_x64_vs150.vcxproj" (build target) (1) ->
       (Link target) ->
         obj64\debug_shared\CppUnitException.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [C:\Users\Backtest\sour
       ce\Workspaces\globalprime\poco-1.8.1\CppUnit\CppUnit_x64_vs150.vcxproj]

    0 Warning(s)
    1 Error(s)

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
run:
buildwin 150 build shared both x64 nosamples notests msbuild

#### POCO version
tried latest 1.8.1 and previous 1.7.9
########################################################################
####
####
########################################################################

The following configurations will be built:
debug_shared
release_shared

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++ Building [CppUnit_x64_vs150.vcxproj]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Microsoft (R) Build Engine version 15.6.82.30579 for .NET Framework

#### Operating system and version

Windows 10

#### Other relevant information

none.

**Comment by DaManJ** [comment]
ok. this was silly.
If you open the standard visual studio command prompt, this loads an x86 environment, and as u can see from the above it was using the x86 cl.exe and link.exe (MSVC\14.13.26128\bin\HostX86\x86)

Solution is to open x64 native tools command prompt and run the build script from there. Then no issues.
Hope someone else finds this helpful.

**Comment by catdsnny** [comment]
Note that if you did a build under X86 and it partially failed, then you will have to "clean" first and then run under under x64 as listed above and yes I made the same mistake; this post was just the answer I was looking for.
