### ISSUE TITLE
ApacheConnector compiling issues

### ISSUE THREAD

**Issue by edson-a-soares** [pocoproject/poco#2206]
**ApacheConnector** is showing the following issues during its compiling:

- It is not compiling because of an abstract method `bool secure() const` defined in **HTTPServerRequest** that is not implemented by **ApacheServerRequest**, one of its derived classes.

    > invalid new-expression of abstract class type `ApacheServerRequest`

    The method must be implemented for correcting the issue.

- Function `ap_log_error` throwing an warning  in `ApacheConnector::log`:

    > passing NULL to non-pointer argument

#### Tools
Poco 1.8.1
GCC6/G++6
Debian 9/Ubuntu 16.04 LTS

**Comment by edson-a-soares** [comment]
It is unfortunate ApacheConnector situation.
Surely I will send a pull to both branches in development as required.

**Comment by aleks-f** [comment]
Thank you @edson-a-soares . 

As for unfortunate situation, that is based on the amount of interest people show for various portions of the framework, commercial and otherwise - if you have a professional or personal stake in the library, you are welcome to take "ownership" and make sure it is kept up to date.

**Comment by edson-a-soares** [comment]
I quite understand it.
I could not really tell for how long I would be able to make the time to do it.
But, it is time enough to making a few improvements for a while.
If that is not a problem, I can do it.

**Comment by aleks-f** [comment]
it is not a problem, of course. i have sent you invitation, so issues can be assigned to you. welcome to the team!

**Comment by lisaforgione** [comment]
Hey, I'm just trying to have a normal cyberlufe, try having an emulator on
u watching n hearing every word and for no reason cuz I'm pretty boring, so
put I t urself in my shoes. I do medicine not computers so I don't know
much about this beside being stalked for a year
