### ISSUE TITLE
Merge Poco DNSSD to Poco

### ISSUE THREAD

**Issue by soroshsabz** [pocoproject/poco#2208]
ITNOA

Hi,

Did you have any plans for merging [Poco-DNSSD](https://github.com/pocoproject/poco-dnssd) to main repository?

Did you have any plans for maintaining [Poco-DNSSD](https://github.com/pocoproject/poco-dnssd) at all?

thanks a lot

**Comment by soroshsabz** [comment]
Hi again,

Any update?

**Comment by obiltschnig** [comment]
No immediate plans for now due to other more pressing issues.

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco-dnssd/pull/6

**Comment by soroshsabz** [comment]
I think we can remove question label for this issue, I create PR for this

**Comment by soroshsabz** [comment]
@aleks-f I think this issue must be reopen

because PRs does not merge yet

#3933 #4323 #4479
