### ISSUE TITLE
UUIDGenerator should allow random seed

### ISSUE THREAD

**Issue by pgtnz** [pocoproject/poco#2217]
#### Actual behavior

UUIDGenerator works fine when only one generator is used. However, this causes a problem when multiple threads are contending for the (fast) mutex. Even more of a problem when those threads number in the tens or hundreds.

The alternative would be to use multiple UUIDGenerator objects so that the contention for the mutex could be reduced. However, there is a high chance for collisions on the time based generation when the UUIDGenerators are all created at the same time because the random number generator is seeded off the create time.

#### Expected behavior

It would be preferable to allow the internal random number generator to be seeded differently for each UUIDGenerator object. Possibly through the constructor.

#### Steps to reproduce the problem

    Poco::UUIDGenerator ugen1;
    Poco::UUIDGenerator ugen2;
    for (int i = 0; i < 10; ++i)
    {
        auto uuid1 = ugen1.createOne();
        auto uuid2 = ugen2.createOne();
        std::cout << uuid1.toString() << std::endl;
        std::cout << uuid2.toString() << std::endl;
        std::cout << std::endl;
    }

results in 

9f5be756-2639-11e8-b471-f894c23a24e1
9f5be756-2639-11e8-b471-f894c23a24e1

9f5be757-2639-11e8-b993-f894c23a24e1
9f5be757-2639-11e8-b993-f894c23a24e1

9f5be758-2639-11e8-9646-f894c23a24e1
9f5be758-2639-11e8-9646-f894c23a24e1

9f5e4a50-2639-11e8-8263-f894c23a24e1
9f5e4a50-2639-11e8-8263-f894c23a24e1

9f5e4a51-2639-11e8-942a-f894c23a24e1
9f5e4a51-2639-11e8-942a-f894c23a24e1

9f5e4a52-2639-11e8-a2c6-f894c23a24e1
9f5e4a52-2639-11e8-a2c6-f894c23a24e1

9f5e4a53-2639-11e8-8a47-f894c23a24e1
9f5e4a53-2639-11e8-8a47-f894c23a24e1

9f5e4a54-2639-11e8-aa75-f894c23a24e1
9f5e4a54-2639-11e8-aa75-f894c23a24e1

9f5e4a55-2639-11e8-86a7-f894c23a24e1
9f5e4a55-2639-11e8-86a7-f894c23a24e1

9f5e4a56-2639-11e8-bd42-f894c23a24e1
9f5e4a56-2639-11e8-bd42-f894c23a24e1

#### POCO version

1.8.0.1 (and current dev)

#### Compiler and version

VisualC++ 2017

#### Operating system and version

Windows 10Pro x64

**Comment by obiltschnig** [comment]
added seed() method
