### ISSUE TITLE
it show me a lot of undefined reference to

### ISSUE THREAD

**Issue by calistochen** [pocoproject/poco#2229]
#### Expected behavior
this is my first time to use POCO,
#### Actual behavior
when i excute g++ main.cpp -o main,it show me a lot of undefined reference to `Poco::@@@::@@@()'
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.8.1
#### Compiler and version
g++ (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
#### Operating system and version
ubuntu 17.10    linux 4.13.0-37-generic
#### Other relevant information
this is my test code
#include <Poco/Thread.h>
#include <Poco/RunnableAdapter.h>
#include <iostream>

class Greeter
{
public:
    void greet()
    {
        std::cout << "Hello, world!" << std::endl;
    }
};
int main(int argc, char** argv)
{
    Greeter greeter;
    Poco::RunnableAdapter<Greeter> runnable(greeter, &Greeter::greet);
    Poco::Thread thread;
    thread.start(runnable);
    thread.join();
    int i = 0 ;
    for(i=0;i<100;i++)
    {
        std::cout << "Hello, main thread!" << std::endl;
    }
    return 0;
}

**Comment by aleks-f** [comment]
you are only compiling your code. In order for the executable to be produced, it needs the library objects, but you are not telling the linker where they are. 

try
```
 g++ main.cpp -o main -lPocoFoundation
```
[Creating Your Own POCO-based Applications](https://pocoproject.org/docs/00200-GettingStarted.html)
The best way to create your first POCO-based application is by copying one of the sample projects and making the desired changes. Examine the project files and Makefiles to see what compiler options must be set for your specific platform.
