### ISSUE TITLE
HTTPS Server Sample

### ISSUE THREAD

**Issue by ghost** [pocoproject/poco#2232]
#### Expected behavior
run success
#### Actual behavior
run failed
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

I complied the poco library [debug-static-mt] with openssl 1.1.0g , then i complied the sample HTTPSTimeServer App , and run it , but it  throws an SSLException as show belows.

SSLManager.cpp   line 263
		throw SSLException("Configuration error: no certificate file has been specified");

I want to know how to run the app correctly. Thanks a lot.

#### POCO version
1.9.0
#### Compiler and version
vs2013
#### Operating system and version
windows 7 ultimate with sp1

**Comment by bstamour** [comment]
Have you been able to get it working? I'm running into the same issue.

**Comment by CingKong** [comment]
In `HTTPSTimeServer::main()`
do `SSLManager::instance().initializeServer()`
before `SecureServerSocket svs(port);`
