### ISSUE TITLE
XML Domwriter stops when umlaut exists

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#2233]
#### Expected behavior
This XML File should be written to Disk:

```xml
<root>
    <Element>Example text</Element>
    <Element1>Text with umlaut: Übermorgen gibt es Regen</Element1>
    <Element2>Text without</Element2>
</root>
```

#### Actual behavior

This file is written to Disk:

```xml
<root>
    <Element>Example text</Element>
    <Element1>Text with umlaut: 
```

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
This is a sample Program which causes this Problem:

```cpp
int main() {

	AutoPtr<Document> pDoc = new Document;
	AutoPtr<Element> pRoot = pDoc->createElement("root");

	AutoPtr<Element> pElement = pDoc->createElement("Element");
	AutoPtr<Text> pText = pDoc->createTextNode("Example text");

	AutoPtr<Element> pElement1 = pDoc->createElement("Element1");
	AutoPtr<Text> pText2 = pDoc->createTextNode("Text with umlaut: Übermorgen gibt es Regen");

	AutoPtr<Element> pElement2 = pDoc->createElement("Element2");
	AutoPtr<Text> pText3 = pDoc->createTextNode("Text without");

	pElement->appendChild(pText);
	pElement1->appendChild(pText2);
	pElement2->appendChild(pText3);

	pRoot->appendChild(pElement);
	pRoot->appendChild(pElement1);
	pRoot->appendChild(pElement2);

	pDoc->appendChild(pRoot);
	

	DOMWriter writer;
	UTF8Encoding utf8Enc;
	writer.setNewLine("\n");
	writer.setEncoding("UTF-8", utf8Enc);
	writer.setOptions(Poco::XML::XMLWriter::PRETTY_PRINT);
	writer.writeNode("D:\\test.xml", pDoc);

}
```

#### POCO version
1.8.1
#### Compiler and version
Microsoft Visual Studio 2017
#### Operating system and version
Windows 10

**Comment by obiltschnig** [comment]
The string you put into the DOM (or XMLWriter) must already be UTF-8 encoded. Your source file is probably using Windows-1252 or similar encoding, so your text node with the Umlaut will contain invalid UTF-8. 
Furthermore, DOMWriter and XMLWriter create UTF-8 encoded XML as default, so there's no need to specify the encoding.

**Comment by KevDi** [comment]
Ok so i have to change the encoding of the String i want to put into the DOM? How can i change it?

**Comment by obiltschnig** [comment]
If you know the encoding of your source file you can use Poco::TextConverter class, e.g.:

```
Poco::Windows1252Encoding win1252;
Poco::UTF8Encoding utf8;

std::string win1252Text("Hellö");
std::string utf8Text;

Poco::TextConverter conv(win1252, utf8);
conv.convert(win1252Text, utf8Text);
```
