### ISSUE TITLE
Are there any plans  to support quic protocol in the near future?

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#2239]
Since you already support udp , is there any plan to support quic protocol ?

**Comment by aleks-f** [comment]
no plan at this time. if someone steps in and sends a pull, we'll gladly review it

**Comment by FreelancerCGN** [comment]
Is there any plan - 4 years later - to support QUIC alias HTTP/3 now in 2022?

**Comment by aleks-f** [comment]
Since in 4 years nobody stepped in to implement it, the answer is stile the same - there is no plan. There was a plan to at least have DTLS (#3281), but already committed sponsor bailed out, so there's not even a fixed plan for that. 

If you really need it, then please consider (1) contributing it directly or (2) sponsoring it.

**Comment by FreelancerCGN** [comment]
Is there any link with more details about the sponsoring?

**Comment by aleks-f** [comment]
We used to have various levels of subscription-based sponsorship, but we switched to direct specific feature/enhancement sponsorships since. The model may change again, depending on circumstances and demand.
For any further info you can email me directly at(alex, dot(pocoproject, org)).

**Comment by zosrothko** [comment]
@aleks-f I will fix it... I am missing only one piece: Where is mysql.h on MacOS Darwin and all build system will work properly: GNUMake/Cmake on Linux, CMake on MacOS, MSBuild/CMake-msvc on Windows

**Comment by aleks-f** [comment]
@zosrothko I am not following - what does mysql have to do with QUIC protocol implementation? sounds like you are commenting on something else
