### ISSUE TITLE
HTTPDigestCredentials.cpp has Problem with the HTTP digest authentication.

### ISSUE THREAD

**Issue by joonsama** [pocoproject/poco#2245]
#### Expected behavior

The HTTP digest should work normally even if no password is set.

#### Actual behavior

If password is empty,  digest() function doesn't add last colon. 
Please refer to the source code below

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.7.8p2
#### Compiler and version
visual studio 2017
#### Operating system and version
windows 10 home edition
#### Other relevant information

The Security-Related Data (A1) is the colon-joined triple of username, realm, and secret password on HTTP digest algorithm.

    MD5 A1 = user:realm:password

If password is empty,  digest() function doesn't add last colon.   

here is code:

```
#include "Poco/DateTime.h"
#include "Poco/DateTimeFormat.h"
#include "Poco/DateTimeFormatter.h"
#include "Poco/Exception.h"
#include "Poco/MD5Engine.h"
#include "Poco/Net/HTTPDigestCredentials.h"
#include "Poco/Net/HTTPRequest.h"
#include "Poco/Net/HTTPResponse.h"
#include "Poco/NumberFormatter.h"
#include "Poco/StringTokenizer.h"


namespace
{
	std::string digest(Poco::DigestEngine& engine,
					   const std::string& a,
					   const std::string& b,
					   const std::string& c = std::string(),
					   const std::string& d = std::string(),
					   const std::string& e = std::string(),
					   const std::string& f = std::string())
	{
		engine.reset();
		engine.update(a);
		engine.update(':');
		engine.update(b);
		if (!c.empty()) 
		{
			engine.update(':');
			engine.update(c);
			if (!d.empty()) 
			{
				engine.update(':');
				engine.update(d);
				engine.update(':');
				engine.update(e);
				engine.update(':');
				engine.update(f);
			}
		}
		return Poco::DigestEngine::digestToHex(engine.digest());
	}
	
	std::string formatNonceCounter(int counter)
	{
		return Poco::NumberFormatter::formatHex(counter, 8);
	}
}

```
>
```
void HTTPDigestCredentials::updateAuthParams(const HTTPRequest& request)
{
	MD5Engine engine;
	const std::string& qop = _requestAuthParams.get(QOP_PARAM, DEFAULT_QOP);
	const std::string& realm = _requestAuthParams.getRealm();
	const std::string& nonce = _requestAuthParams.get(NONCE_PARAM);

	_requestAuthParams.set(URI_PARAM, request.getURI());

	if (qop.empty())
	{
		const std::string ha1 = digest(engine, _username, realm, _password);
		const std::string ha2 = digest(engine, request.getMethod(), request.getURI());

		_requestAuthParams.set(RESPONSE_PARAM, digest(engine, ha1, nonce, ha2));
	}
	else if (icompare(qop, AUTH_PARAM) == 0) 
	{
		const std::string& cnonce = _requestAuthParams.get(CNONCE_PARAM);

		const std::string ha1 = digest(engine, _username, realm, _password);
		const std::string ha2 = digest(engine, request.getMethod(), request.getURI());
		const std::string nc = formatNonceCounter(updateNonceCounter(nonce));

		_requestAuthParams.set(NC_PARAM, nc);
		_requestAuthParams.set(RESPONSE_PARAM, digest(engine, ha1, nonce, nc, cnonce, qop, ha2));
	}
}

```

**Comment by micheleselea** [comment]
I don't get it...why using Digest Authentication if password is empty?

**Comment by joonsama** [comment]
thank you for your comments.
We bought a large number of cameras from vendor a while ago.
Before installing it on the site, we had to set up basic configuration by connecting to the camera. It was difficult to set it as a program using poco library (digest authentication) because no password was set.
The digest algorithm must be used to connect to the camera, but the password is not necessary.

**Comment by micheleselea** [comment]
Ok, strange behavior for a camera: should not ask you the authentication at all if the password is not set, or should have a default password set. I think something is missing from that camera because using an Authentication algorithm without authentication sound strange ;)
Anyway from the point of view of the digest() function the problem is that the function add the element if it's not empty...so it's quite hard to find a solution here: something in that camera do not work as expected...probably the solution here is to re-implement your digest() as you need in your application or to always have a not empty password for camera

**Comment by joonsama** [comment]
As you mentioned, we have resolved the problem by re-implementing the algorithm functions. 
Modification is not difficult and it works very well. So it looks like the issue has been closed, although I have to patch each time new library version is released. 
Thank you for your interest.
