### ISSUE TITLE
Linker error at Visual Studio 2015 regarding to GetAdaptersInfo

### ISSUE THREAD

**Issue by DonChunior** [pocoproject/poco#2254]
#### Actual behavior
I've build the POCO libraries by using the "Visual Studio x64 Win64 Command Prompt (2010)" and the command "buildwin.cmd 140 build all both x64".
I'm not able to create my own Visual Studio project (**x64**) at the moment, because I get following linker error:
**PocoFoundationmt.lib(Environment.obj) : error LNK2001: unresolved external symbol GetAdaptersInfo**

#### POCO version
1.9.0

#### Compiler and version
Visual Studio 2015 (Version 14.0.25431.01 Update 3)

#### Operating system and version
Windows 7 Enterprise SP1 x64

**Comment by aleks-f** [comment]
you should link your application with `Iphlpapi.lib`.

**Comment by DonChunior** [comment]
I just tested your solution and it works - thanks a lot, Aleks!
Interestingly I don't need to link my application with the library iphlpapi.lib, when I use POCO version 1.7.8 instead of 1.9.0.

**Comment by aleks-f** [comment]
you have to link your application with iphlpapi.lib when you are inking with static poco foundation library, otherwise not
