### ISSUE TITLE
IpAddress::tryParse() behavior?

### ISSUE THREAD

**Issue by MasterGroosha** [pocoproject/poco#2256]
#### Expected behavior: 
Return false

#### Actual behavior: 
Returns true

#### Steps to reproduce the problem
```c++
Poco::Net::IPAddress ipAddr;
string test{ "192.168.2.20 comment" };

if (Poco::Net::IPAddress::tryParse(test, ipAddr))
    cout << "Parsed successfully"; // This is what is printed
else
    cout << "Failed to parse"; // This is what should (?) be printed
```

#### POCO version: 
1.8.0.1

#### Compiler and version: 
VS 2015 (Version 14 Update 1) default compiler

#### Operating system and version
Windows 7 x64

**Comment by MasterGroosha** [comment]
Well, as far as I see, Poco's `parse()` method [uses](https://github.com/pocoproject/poco/blob/develop/Net/src/IPAddressImpl.cpp#L256) `inet_addr()` function, which, for example, [on Windows](https://msdn.microsoft.com/en-us//library/windows/desktop/ms738563(v=vs.85).aspx) behaves exactly the same way as Poco's `parse()`.

However, this is not what one might expect. Should this be considered as "bug"?

**Comment by aleks-f** [comment]
> Should this be considered as "bug"?

depends how you look at it. if it is, it should be filed with your platform provider

**Comment by MasterGroosha** [comment]
> it should be filed with your platform provider

Could you explain this please?

**Comment by aleks-f** [comment]
if you think it is a bug, there is nothing we will do about it because ignoring the garbage after the valid IP address part works good enough in practice. whoever implemented the underlying functionality on your platform is the one who should fix it, if you can convince them.

**Comment by obiltschnig** [comment]
It depends on how we define the semantics of `tryParse()`. Right now it's: pass the IP address string to `inet_addr()`, and if it's happy then we're happy too. If your expectation is check if it's a valid IP address and only then parse it, then we have to disappoint you. The description of `tryParse()` says: "Tries to interpret the given address string as an IP address", which admittedly, is a bit vague, but covers the existing behavior.

**Comment by MasterGroosha** [comment]
Fair enough, guess I'll add extra checks myself. Thank you for the answers!
