### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2268]
Hi @obiltschnig @aleks-f because I'm going digging in HTTP/2 I want to implement in my application, and it would be nice if I manage to integrate it in current Poco HTTPServer. Reading some information aroud web I understand that it's completely different protocol (is binary not textual). So my question is: do you think it worth to make a new class instead extend existing, or what do you think is the best way to implement it in current lib?
do you already know some 3rd party lib to use as starting point to implement HTTP/2 and HPACK?

**Comment by micheleselea** [comment]
for example on github I found nghttp2 that could be a good start point, but if you have some better advice...

**Comment by aleks-f** [comment]
a while ago, I've done some work on async http [here](https://github.com/pocoproject/poco/pull/2093). while not ideal, it does work (basically by piping the data from async I/O loop to the existing HTTP stream). alternatively, maybe this would be an opportunity to do a proper async server. in any case, like with the other issue - send it somehow, we'll look at it (eventually :)

**Comment by micheleselea** [comment]
Ok I'm starting to look around the code, so I've nothing for now, I'll keep you informed...I think I'll start from Nghttp2 to check what happens ;)

**Comment by theidexisted** [comment]
Any update on this issue?

**Comment by micheleselea** [comment]
I'm currently use https://nghttp2.org/ because fit http2 into the poco http server was not an easy task, so I had to use it as is. You can have a look event to the proxy http2/http of nghttp2
