### ISSUE TITLE
Brotli compression

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2269]
Few days ago I discover what `Accept-encoding: br` means. So I manage to make a class to implement Brotli compression wrapping the source code from [github Brotli](https://github.com/google/brotli)
It's a raw implementation, but if you think can be useful as starting point I can submit what I have done, so we can discuss about what we need to make it suitable for Poco lib. let me know

**Comment by aleks-f** [comment]
depending on how much you've done, it can go as a separate branch, or perhaps in the [sandbox](https://github.com/pocoproject/sandbox). In any case - send it somehow

as a side note, not to put you on the spot - it is fine if you do not want that - but if you somehow provide us with an an email, we can invite you to [slack](https://pocoproject.slack.com), which is a better place for discussions like that. you can send it to `alex at pocoproject dot org`

**Comment by micheleselea** [comment]
I'll send you the class with an example on how to use it, as soon as I put together the code
