### ISSUE TITLE
HTTPClientSession not supporting binding source address for proxy connect

### ISSUE THREAD

**Issue by roccocorsi** [pocoproject/poco#2270]
#### Expected behavior

When using HTTP proxy with HTTPClientSession class, expecting that source IP address binding is used when connecting to proxy, just like when no proxy is used and connecting directly.

#### Actual behavior

HTTP proxy connects without source IP address binding even if an IPAddress is set with setSourceAddress().

#### POCO version
2.0.0

#### Other relevant information

Related to issue https://github.com/pocoproject/poco/issues/1475

**Comment by roccocorsi** [comment]
Should I rebase my two fixes/features to top of develop?

**Comment by roccocorsi** [comment]
Aleks, made a combined commit as requested.

**Comment by roccocorsi** [comment]
I did get emails that you made some comments, but I can't seem to find the comments directly on github to respond to them. Sorry for my lack of resourcefulness.  :-)

Also someone commented on my cmake modification (two commented lines really) to compile in C++11 the SetSourceIP sample program.  I just put that there is case it might help someone compiling just the SetSourceIP sample program.  Either it doesn't work for my environment (OpenSuse Leap 42.3) without that line or I just don't know how to use cmake.

**Comment by roccocorsi** [comment]
Also Günter marked the commits for 1.10.0. but I thought this was going into 2.0.0 because it is C++11. Did something change and 1.10.0 will now be C+11?

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/804ce9ee594169d3740db83ec9dd1c09836e5a1e
https://github.com/pocoproject/poco/commit/cd850522317074248c492d291c4d81bc6f7104f7
