### ISSUE TITLE
Missing test files

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#2274]
CMake build does not copy (or build) needed files (eg. TestLibrary.so/dll, etc) to the build directory. Not sure how CI does it, but my cmake build has not files where needed. Eg. TestLibrary should be in te same directory as testrunner executable

**Comment by zosrothko** [comment]
"In CMake, adding ‘d’ for debug has been disabled (for whatever reason) and cmake does not even build it on my machines, to start with - don’t know why." This is wrong and should be rollbacked..; the debug version of any dll/so must be suffixed by 'd'...

**Comment by Bjoe** [comment]
@zosrothko It is only disabled for TestLibrary.so and TestApp for SharedLibraryTest.

@aleks-f It is not reproducibly for me in develop branch.

**Comment by aleks-f** [comment]
@Bjoe ok, thanks, it may be something related to clion

however, why [this](https://github.com/pocoproject/poco/blob/develop/Foundation/testsuite/CMakeLists.txt#L57) and [this](https://github.com/pocoproject/poco/blob/develop/Foundation/testsuite/CMakeLists.txt#L63)

**Comment by zosrothko** [comment]
@Bjoe "@zosrothko It is only disabled for TestLibrary.so and TestApp for SharedLibraryTest.". The 'd' suffix for those unittest libraries MUST be rollbacked... and those libraries must be in the path of the testrunner executable, be on Windows or on Linux. I presume that they should be also on some path on OSX

**Comment by zosrothko** [comment]
To summarize this issue
```
Foundation.[so/dll]   must load TestLibrary.[so/dll]
Foundationd.[so/dll] must load TestLibraryd.[so/dll]
Foundation.[so/dll]   must not load TestLibraryd.[so/dll]
Foundationd.[so/dll] must not load TestLibrary.[so/dll]
````

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/pull/2247/commits/f56ac58cfec765bcaf591c3dd17d4323b256db24
https://github.com/pocoproject/poco/pull/2247/commits/1198fbe89e52919ed9dc91865f7c140dfcfdf218
