### ISSUE TITLE
SQLite mismatch open/close API calls

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#2275]
SQLite connection is opened with [sqlite3_open_v2](https://github.com/pocoproject/poco/blob/poco-1.9.0/Data/SQLite/src/SessionImpl.cpp#L161), but closed with [sqlite3_close](https://github.com/pocoproject/poco/blob/poco-1.9.0/Data/SQLite/src/SessionImpl.cpp#L185). Valgrind reports memory leak.

Closing with [sqlite3_close_v2](https://www.sqlite.org/c3ref/close.html) fixes it.

**Comment by micheleselea** [comment]
Ah....interesting bug...I'm going to immediately fix in my version

**Comment by micheleselea** [comment]
even if I do not see any "warning" in SQLite documentation about opening v2 and closing without or vice versa.
https://www.sqlite.org/c3ref/close.html
there's only some specification about closing v2 seams to be better when the system has a garbage collector...I don't know if it's a real leak

**Comment by aleks-f** [comment]
It has to do with close returning busy, but we are ignoring it. Look at the `sqlite3Close()` call in `sqlite3.c` - `sqlite3_close_v2` has `forceZombie` set to 1. `sqlite_close` sends 0, and `sqlite3Close()` shortcuts the return, even if close was unsuccessful, but we ignore the return value.

**Comment by micheleselea** [comment]
Ok, I'm trying  the close function in my current Lib code, I think it's safe anyway
