### ISSUE TITLE
websocket and webserver together

### ISSUE THREAD

**Issue by bnadem** [pocoproject/poco#2279]
can i make with poco framework webserver (http) and websocker run together, websocket for real time data and webserrver for REST (update delete new add device or users, ....) ,

**Comment by micheleselea** [comment]
yes you can. Just have a look to the [websocket server sample](https://github.com/pocoproject/poco/blob/develop/Net/samples/WebSocketServer/src/WebSocketServer.cpp)
is exactly a webserver that use websocket for specific request

**Comment by fbraem** [comment]
My project [MQWeb](http://www.mqweb.org/) does this.

**Comment by bnadem** [comment]
i mean webserver width document root, document stored html and javascript

**Comment by micheleselea** [comment]
You can use javascript WebSocket to comunicate with your server so it's possible to send what you need, even root files, but browser itself doesn't use websocket to download website is not HTTP standard.
If you need a single connection to use your browser and access your webserver you should move to HTTP/2
