### ISSUE TITLE
SQLite implementation

### ISSUE THREAD

**Issue by petko** [pocoproject/poco#2289]
I am trying to use a SQLite extension in my project Nunicode (https://bitbucket.org/alekseyt/nunicode). It provides Unicode collations and redefines some SQLite functions such as `like`.

New collations work as expected, however `like` and the rest of the redefined and added operators do not work for some reason (either producing wrong results or causing SEH under Windows). I've found out that this happens only if I use Poco. If I omit Poco libraries and compile SQLite directly in my test project, things work as expected.

So, I am wondering, does Poco in some way interfere with these SQLite operators? I want to find out what is the reason for this incompatibility..

**Comment by petko** [comment]
It turns out that the problem is caused by the fact that POCO libraries are compiled with the `SQLITE_OMIT_UTF16` define by default. Since the extension adds separate functions for UTF-8 and UTF-16, this somehow corrupts the SQLite session.

Why is `SQLITE_OMIT_UTF16` added by default? Which purposes does it serve for POCO?

I can just remove it every-time I compile POCO, but I am curious why it is there..

**Comment by obiltschnig** [comment]
Most SQLite options are set to reduce the size of SQLite.
