### ISSUE TITLE
Conan with -fPIC

### ISSUE THREAD

**Issue by jano42** [pocoproject/poco#2297]
#### Expected behavior
Use poco library by specifying -fPIC at build time

#### Actual behavior
Throught conan framework, it is not possible to set -fPIC options

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
All

#### Compiler and version
All

#### Operating system and version
All

#### Other relevant information
I follow this guide https://github.com/Yadoms/yadoms/wiki/For-Ubuntu#poco to build my poco library.
I had to manually edit STATICOPT_CC && STATICOPT_CXX.
Please upgrade conan recipies to allow specifyning such args.

**Comment by aleks-f** [comment]
please post this in [conan-poco](https://github.com/pocoproject/conan-poco)

**Comment by jano42** [comment]
Can't post on conan-poco (issue tabs is not available)

**Comment by aleks-f** [comment]
fixed, try now
