### ISSUE TITLE
TLSV1_2_CLIENT_USE not working as expected?

### ISSUE THREAD

**Issue by AbhinavBansal** [pocoproject/poco#2299]
I have created a SSLContext with TLSV1_2_CLIENT_USE and I am using this context in HTTPSClientSession. However I see that client doesn't use TLS1.2, instead it uses TLS1.0

 ``` 
auto ctx = new Poco::Net::Context(Poco::Net::Context::TLSV1_2_CLIENT_USE, "", "", "", Poco::Net::Context::VERIFY_STRICT, 9, false, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
 Poco::Net::HTTPSClientSession session(uri.getHost(), uri.getPort(), ctx);
```

However If I call Openssl API then client starts using TLS1.2:

`                SSL_CTX_set_ssl_version(ctx->sslContext(), TLSv1_2_method());
`
Is this an expected behavior with TLSV1_2_CLIENT_USE? If not, how can this be fixed. Any pointers will be helpful.

Poco Version: 0x17238016 compiled in static mode
OpenSSLVersion: OpenSSL 1.0.2o-fips  27 Mar 2018 linked as a dylib on OSX

**Comment by micheleselea** [comment]
I think you should enter in function
`void Context::createSSLContext()`
and check how context is created

**Comment by AbhinavBansal** [comment]
Thanks.

I see special handling for FIPS causing the issue:


```if (SSLManager::isFIPSEnabled())
	{
		_pSSLContext = SSL_CTX_new(TLSv1_method());
	}
```

Any reason why it is restricted to TLSv1? Will changing it to TLS1.2 cause issues?

**Comment by micheleselea** [comment]
don't know I'm using OpenSSL1.1.0 without FIPS, we should ask to @obiltschnig

**Comment by AbhinavBansal** [comment]
I have changed it to TLS1_2_client_method() and that works. So closing the issue.
