### ISSUE TITLE
How to send a binary data block over HTTP using Poco?

### ISSUE THREAD

**Issue by htartisan** [pocoproject/poco#2303]
I have a C++ "REST-ful" interface (HTTP command interface) that I created, based on Poco HTTP classes.

I am now working on an application where I need to reply to a command by sending a binary data block from the (Poco based) server application to the (Poco based) client application via HTTP.
  (**IE:** The client sends a "REST-ful" command, and the server responds back with a binary data block.)

Any suggestions on how to do it  (or better yet, example code that you can point me to)???

**Comment by obiltschnig** [comment]
You can simply send binary data in the HTTP body by writing it to the response stream. Just send the Content-Type accordingly, so that the client knows what he gets. No need to encode in base64.
