### ISSUE TITLE
I found a bug in  Poco::Util::JSONConfiguration in handle of  JOSN Object Array

### ISSUE THREAD

**Issue by hemmingway** [pocoproject/poco#2304]
I Create  a JSONConfiguration() object,  than create 2D-array json object,   the result get chaos

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
0x02000000

#### Compiler and version
Microsoft Visual Studio Enterprise 2017 Preview
Visual C++ 2017   00369-90000-00000-AA107

#### Operating system and version
Windows 10 教育版

**Comment by hemmingway** [comment]
here is the sampe test code

`
void testBug()
{
	AutoPtr<JSONConfiguration> pConfig(new JSONConfiguration());

	pConfig->setInt("wave[0].test1", 1);
	pConfig->setInt("wave[0].test2", 2);

	pConfig->setInt("wave[4].test1", 3);
	pConfig->setInt("wave[4].test2", 5);


	std::string path("ggg.json");
	FileOutputStream fos(path);
	if (fos.good())
	{
		OutputLineEndingConverter lec(fos);

		pConfig->save(lec, 4);
		lec.flush();
		fos.flush();
		fos.close();
	}
}
`

there is output file result:
`
{
    "wave" : [
        {
            "test1" : 1,
            "test2" : 2
        },
        {
            "test1" : 3
        },
        {
            "test2" : 5
        }
    ]
}

`


but, i thank, the correct result should be:

`
{
    "wave" : [
        {
            "test1" : 1,
            "test2" : 2
        },
        {
        },
      {

      },
       {

      },
       {
            "test1" : 3,
            "test2" : 5
        }
    ]
}

`

**Comment by hemmingway** [comment]
This code is correct work!

void testBug()
{
	AutoPtr\<JSONConfiguration\> pConfig(new JSONConfiguration());

	pConfig->setInt("wave[0].test1", 1);
	pConfig->setInt("wave[0].test2", 2);

	pConfig->setInt("wave[1].test1", 3);
	pConfig->setInt("wave[1].test2", 5);


	std::string path("ggg.json");
	FileOutputStream fos(path);
	if (fos.good())
	{
		OutputLineEndingConverter lec(fos);

		pConfig->save(lec, 4);
		lec.flush();
		fos.flush();
		fos.close();
	}
}


Output file get ok!

{
    "wave" : [
        {
            "test1" : 1,
            "test2" : 2
        },
        {
            "test1" : 3,
            "test2" : 5
        }
    ]
}

**Comment by timrprobocom** [comment]
Perhaps it's better to call this a "documentation bug".  If you refer to an array index that doesn't exist, the code creates one new entry and uses that.  Thus, your code is the same as
```C
pConfig->setInt("wave[0].test1", 1);
pConfig->setInt("wave[0].test2", 2);
pConfig->setInt("wave[1].test1", 3);
pConfig->setInt("wave[2].test2", 5);
```

Handling arbitrary sparse arrays is not really practical.
