### ISSUE TITLE
Why does Poco explicitly define _WIN32_WINNT?

### ISSUE THREAD

**Issue by Dimension4** [pocoproject/poco#2306]
In *Poco/UnWindows.h* the `_WIN32_WINNT` is defined to be 0x0501 (which is Windows XP). After that *windows.h* is included (which means, if we don't specify the version explicitly, Poco includes the Windows XP headers). And later on, in *Poco/Platform_WIN32.h*, `_WIN32_WINNT` is redefined to be Windows 8.1.

A detailed description and problem caused by that mechanism can be found on [stackoverflow](https://stackoverflow.com/a/50042314/6205379).

What is the reason for this behavior? Why does Poco explicitly define `_WIN32_WINNT`, when it also can be defined in *sdkddkver.h* (which is included in *windows.h*)?

Configuration:
Windows 10 Pro x64 1709 (Build 16299,371)
Windows SDK 10.0.16299.0 (and 10.0.15063.0 and 10.0.14393.0)
Toolset version 141
Visual Studio 15.6.6
Poco version 1.8.1-1 (x64 via vcpkg package manager)
C++17 (/std:c++latest)

**Comment by aleks-f** [comment]
some ancient reason that i vaguely remember had to do with one or two things (network interface and/or critical sections) during the funny xp/vista period. probably can be removed, but build should be tested on all windows versions later than win7

**Comment by OgreTransporter** [comment]
I can remember _WIN32_WINNT is required for some features of Comctl32 (Windows controls), but poco is not using this library. Redefining _WIN32_WINNT to Windows 8.1 might create problems on Win7.
