### ISSUE TITLE
packages for vcpkg supported?

### ISSUE THREAD

**Issue by bangusi** [pocoproject/poco#2311]
Does the Poco project officially support (provide ) packages for vcpkg?
I attempted to install Poco using vcpkg and got a broken build and was wondering who supports this port.

**Comment by aleks-f** [comment]
omg, yet another packaging tool. not supported as far a s I know

**Comment by bangusi** [comment]
Looks like some guy at Microsoft.
https://github.com/Microsoft/vcpkg/tree/master/ports/poco
It would be nice if this port got some support because vcpkg is becoming a very popular means of acquiring libraries on Windows;  more so than conan I think.

**Comment by aleks-f** [comment]
see with @zosrothko , he is in charge of those things

**Comment by ras0219-msft** [comment]
Both of the problems posed in the issue on vcpkg have been addressed in the latest master (`mt` suffix and version).

@zosrothko I'd be happy to chat via vcpkg@microsoft.com

**Comment by aleks-f** [comment]
@ras0219-msft I have sent you slack invitation, check your inbox

**Comment by aleks-f** [comment]
@zosrothko probably best to create a separate repo, like conan

**Comment by ras0219-msft** [comment]
Vcpkg doesn't require a separate repo; we host the scripts in a central repo (like homebrew)

**Comment by zosrothko** [comment]
All packaging stuff are going onto this directory: `poco/packaging`. Windows related packaging should be located under `poco/packaging/Windows` and vcpkg stuff should go there `poco/packaging/Windows\vcpgk` along the `Nuget` and `WiX` directory
