### ISSUE TITLE
Access violation in CryptTestSuite/PBKDF2EngineTest under VS2015

### ISSUE THREAD

**Issue by akmalk** [pocoproject/poco#2333]
#### Expected behavior
Test should pass without access violation exception
#### Actual behavior
CryptTestSuite fails (crashes) with access violation exception on PBKDF2EngineTest::testPBKDF2a test and other PBKDF2Engine tests
#### Steps to reproduce the problem
Build Poco Foundation and TestSuite under VS2015 with release_static_md build configuration and run CryptTestSuite test.

#### POCO version
Poco 1.9.0
#### Compiler and version
Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
#### Operating system and version
Windows 10

#### Other relevant information

**Comment by aleks-f** [comment]
Can't reproduce:
```
C:\Users\alex\source\repos\pocoproject\poco\Foundation\testsuite\bin64\static_md (devel -> origin)
λ .\TestSuite.exe PBKDF2EngineTest

testPBKDF2a:
testPBKDF2b:
testPBKDF2c:
testPBKDF2e:
testPBKDF2f:

OK (5 tests)
```
