### ISSUE TITLE
Precompiled Libraries?

### ISSUE THREAD

**Issue by CingKong** [pocoproject/poco#2339]
Just want to know if theres plan to provide procompiled libraries of Poco for users to download, sometimes it could be hard for inexperienced users to compile themselves (yes im talking about myself).

Like this project, [Urho3D](https://urho3d.github.io/), they provide prebuilt binaries for the platforms the library supports, its extremely useful for a new user to try the library.

**Comment by zosrothko** [comment]
1. For Windows, there is a  [Nuget package](https://bintray.com/pocoproject/nuget) and a [MSI package ](https://github.com/pocoproject/poco/releases)

2. For Linux, there are a Fedora rpm and a Debian pkg (ask your favorite distro website)

3. For MacOS, there is a [vcpkg ](https://github.com/Microsoft/vcpkg/tree/master/ports/poco), I am not aware of a brew packaging btw @aleks-f ?

4. There is aloas a  [conan-io package](https://github.com/pocoproject/conan-poco)

**Comment by CingKong** [comment]
There is a brew package named [poco](https://bintray.com/homebrew/bottles/poco). 
What about Android and iOS? Mobile platforms are the hardest, at least for me they are xD

**Comment by zosrothko** [comment]
For Android and iOS, there is no Poco package per se. For Android, you can have a look to this [jobs ](https://travis-ci.org/pocoproject/poco/jobs/381013455/config)that build Poco for Android at Travis CI

**Comment by zosrothko** [comment]
[Look there](https://travis-ci.org/pocoproject/poco/builds/378416758)

**Comment by CingKong** [comment]
Sry for my ignorance, what is Traivs-CI, just a testing suite or cloud compiler thing?

**Comment by CingKong** [comment]
I forked this repo and copied the config from one of the successful build jobs, but failed building again?

https://travis-ci.com/CingKong/poco/builds/73910239

**Comment by zosrothko** [comment]
I can't help you. I do not master Android.

**Comment by CingKong** [comment]
OK, built Android libraries using Conan's "--build missing" argument, tried simple test with Poco::Net::DatagramSocket and it worked fine!

But I didnt manage to find some useful docs about the iOS platform, guess im just gonna leave that one, so sad :(

Thx for the help anyway.
