### ISSUE TITLE
Strange SocketAddress behavior in OSX

### ISSUE THREAD

**Issue by pqvst** [pocoproject/poco#234]
I just downloaded the latest 1.5.2-release. Creating socket addresses in OSX is behaving very strangely. I have tested various ways of creating a socket address:

``` c++
SocketAddress addr1("0.0.0.0:9512");
addr1.toString(); // returns: 0.2.37.40:0
SocketAddress addr2("0.0.0.0:1234");
addr2.toString(); // returns: 0.2.37.40:0
SocketAddress addr3("192.168.1.1:1234");
addr3.toString(); // returns: 0.2.4.210:0
```

I have also tested other constructors:

``` c++
int port = 9512;
IPAddress ip = IPAddress::wildcard(IPAddress:IPv4);
ip.toString(); // returns 0.0.0.0 (ok!)
SocketAddress addr(ip, port);
addr.toString(); // returns 0.2.37.40:0
```

Simple constructors for other classes cause strange outcomes as well:

``` c++
// throws Net Exception: 
// Address family not supported
ServerSocket socket(9512); 

// throws Net Exception:
// Cannot assign requested address: 0.2.37.39:0
DatagramSocket(9512); 

```

The same code worked as expected in 1.5.1.

**Comment by constructs** [comment]
Hello,
I tried to use Poco 1.6.0-all on Darwin for 32 and 64 bit architectures, but seem to run into the same problem.

I have posted a detailed log here:
http://pocoproject.org/forum/viewtopic.php?f=12&t=6574#p12172

Can you please help?

**Comment by aleks-f** [comment]
see #1950
