### ISSUE TITLE
Errors in WebSocket's ducumentation.

### ISSUE THREAD

**Issue by AnDevi** [pocoproject/poco#2351]
#### Documentation's error.

Your documentation says that:

https://pocoproject.org/docs/Poco.Net.WebSocket.html#26046

`Returns the number of bytes received. A return value of 0 means that the peer has shut down or closed the connection.`
but it's not true.
When you are receiving Ping frame, this frame can be 0 bytes lenght and it doesn't mean that peer has shut down or closed the connection.

This is confirmed in  WebSocket protocol specification:

https://tools.ietf.org/html/rfc6455#section-5.5.2

`The Ping frame contains an opcode of 0x9.
  A Ping frame MAY include "Application data".`

#### POCO version
Poco version 1.9.0

**Comment by gelldur** [comment]
I agree. Recently I had this issue. Server is sending me 0 but it doesn't mean this.
Beside that I was making one mistake with restarting my socket. Should I report this as separate issue ?

I was creating WebSocket from session. (I keep session object for later reuse to create new(after restart) WebSocket).

During creation of WebSocket I get Invalid Argument exception as:

```
	if (!dynamic_cast<SecureStreamSocketImpl*>(impl()))
		throw InvalidArgumentException("Cannot assign incompatible socket");
```

I really didn't understand this issue. After some debugging I figure out that when creating WebSocket code calls detachSocket on session, as documentation mentions it will detach and create new default socket for that session. I need to mention I was using HTTPSClientSession

So I suggest 2 fixes:
1. Improve documentation that session should be only used to upgrade and use then WebSocket and from now there is no "connection" between WebSocket and Session objects.
2. I think there is a bug in HTTPSClientSession in detachSocket ?

**Comment by doginatree** [comment]
Just a note - I recently ran into the very same issue and came here.  I find it interesting to see the example code posted in #2541  actually resets the length of the data received to work-around this.
