### ISSUE TITLE
develop branch does not build

### ISSUE THREAD

**Issue by zhulika** [pocoproject/poco#2354]
#### Expected behavior

msbuildwin to work

#### Actual behavior

it fails at the MySQL stage with:

`++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++ Building [MySQL_vs150.vcxproj]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

msbuild /clp:NoSummary /nologo /v:minimal /p:UseEnv=true /m /t:build /p:Configuration=debug_shared /p:Platform=Win32 MySQL_vs150.vcxproj
  Utility.cpp
c:\program files\mysql\mysql server 8.0\include\mysql\client_plugin.h(108): error C2371: 'MYSQL': redefinition; differe
nt basic types [D:\work\github\poco\SQL\MySQL\MySQL_vs150.vcxproj]
  d:\work\github\poco\sql\mysql\include\poco\sql\mysql\utility.h(26): note: see declaration of 'MYSQL'
d`

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

1. git clone this repo
2. delete openssl folder and "git clone https://github.com/pocoproject/openssl"
3. install MySql and set the INCLUDE / LIB evars
4. run "buildwin 150 build all both Win32"

#### POCO version

git commit 45903ed071df1becb26bae9add6cb9cbd3e460e6

#### Compiler and version

Microsoft Visual Studio 2017

#### Operating system and version

Windows 10

#### Other relevant information

I restarted buildwin at least once, because I failed to install OpenSSL correctly the first time. Does it cope with being restarted after I fix each problem (I'm too lazy to try to get everything right first time!)

**Comment by aleks-f** [comment]
you need mysql client headers and libraries in order to build mysql. this is the case for any external dependency (mysql, postgresql, openssl)

**Comment by zhulika** [comment]
I'm a bit confused, though this may be because I am not familiar enough with what you are saying.

Is the error message not coming from the duplicate definition that the compiler is finding inside a MySQL client header file?

**Comment by aleks-f** [comment]
yes, you are right, I did not look past `error C2371: 'MYSQL`. I have never seen that problem and our CI builds mysql. if you can find a solution that will fix it send a pull and we'll merge it

**Comment by DynasoulStudio** [comment]
Just confirming this issue over here:

`poco-1.9.0-all\data\mysql\include\poco\data\mysql\mysqlexception.h(26): error C2371: 'MYSQL': redefinition; different basic types
2>c:\program files\mysql\mysql server 8.0\include\mysql.h(293): note: see declaration of 'MYSQL'`
