### ISSUE TITLE
RSA encryption without private key

### ISSUE THREAD

**Issue by Archivist062** [pocoproject/poco#2367]
#### Expected behavior

RSA Cipher requires only the public key to generate a valid ciphertext

#### Actual behavior

Without a private key supplied on encryption, the ciphertext generated is not decipherable. An exception whose `.what()` is `I/O Error` is thrown by `decryptString`.

#### Steps to reproduce the problem
```
    auto decrypt_key = new Poco::Crypto::RSAKey(
        std::string("./key.pub"),
        std::string("./key.priv"),
        std::string("")
    );
    auto encrypt_key = new Poco::Crypto::RSAKey(
        std::string("./key.pub")
    );

    Poco::Crypto::CipherFactory factory;
    auto iengine= factory.createCipher(*encrypt_key);
    auto oengine= factory.createCipher(*decrypt_key);

    std::string SS = "test_str";
    auto enc = iengine->encryptString(SS);
    auto SS2 = oengine->decryptString(enc);
    assert(SS==SS2);

    delete decrypt_key;
    delete encrypt_key;
```
`key.pub` being a valid public key for `key.priv`

#### POCO version

1.9.0

#### Compiler and version

GCC 7.3.0

#### Operating system and version

Debian/Linux testing x64

**Comment by aleks-f** [comment]
can't reproduce
