### ISSUE TITLE
Question regarding timeout of icmp client

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#2369]
I have implemented an app according to the poco ping example poco/Net/samples/Ping/src/Ping.cpp
with the following icmpclient 
`Poco::Net::ICMPClient icmpClient(Poco::Net::IPAddress::IPv4,48, 128, 5000);`
I want to ask whether the 5 seconds timeout refers to each ping reply wait timeout or for all repetitions like the linux command `ping -w deadline` , because when I chose 10 repetitions I saw additional time for all repetitions greater than 5 seconds.
If the the timeout is for each reply, can one achieve  a `ping -w deadline`  behavior  by throwing timeout exception on methods onBegin, onReply, onError, onReply, onEnd and then rethrowing exception so as to leave the delegates, or there is no way to stop the asynchronous delegates?

**Comment by dk1301** [comment]
I put timeout 5 seconds to  icmp client . I tried 10 repetitions and measured each time the reply time. 
So there were times that the whole time to execute all 10 repetitions was greater than the 5 seconds.
I assume that according to your answer "Every repetition has its own socket" it means that every repetition has 5 second limit timeout. What I want ot achieve is a timeout that may stop the execution of some repetitions . For example supposedly that I run 10 repetitions and I measure the time since the beginning of the first repetition. As soon as the watch reaches the 5 seconds I want to stop the remaining repetitions if any. This is what command `ping -w deadline` achieves. 
The  eventArgs error  refers to each repetition and each socket tiemout.
But is there a safe way to force the delegates to stop entirelly at specific time which is different than the socket timeout?

**Comment by aleks-f** [comment]
> But is there a safe way to force the delegates to stop entirelly at specific time which is different than the socket timeout?

As it is currently, no - the whole thing is synchronous and it will run it's course, with any errors reported to the Args. The only exception to this rule would be if a std exception is thrown during the process - that would escape internal catches and propagate exception to the caller.

The functionality you are looking for can be achieved in two ways:

- additional parameter flag to immediately give up on timeout (or any error)
- add ICMPClient::pingAsync(), then you can stop it from outside

**Comment by dk1301** [comment]
The throwing of the std::exception did the job. Thanks a lot for the support and the quick response.
