### ISSUE TITLE
Cannot include FTP and FTPS stream factories into 1 file

### ISSUE THREAD

**Issue by Good-Pudge** [pocoproject/poco#2376]
#### Expected behavior
Including `FTPStreamFactory.h` and `FTPSStreamFactory.h` into 1 file should not cause error. 

#### Actual behavior
But it cause because of `FTPPasswordProvider` class was defined in both files.

#### Steps to reproduce the problem
Compile source code:
```cpp
#include <Poco/Net/FTPStreamFactory.h>
#include <Poco/Net/FTPSStreamFactory.h>

int main()
{
    Poco::Net::FTPStreamFactory::registerFactory();
    Poco::Net::FTPSStreamFactory::registerFactory();
    return 0;
}
```

#### POCO version
`develop` branch

#### Compiler and version
MinGW-w64 x64 8.1.0

#### Operating system and version
Windows 10 x64 1803

#### Other relevant information
Compiler error look like this:
![](https://i.imgur.com/14BJQxU.png)

**Comment by aleks-f** [comment]
@micheleselea can you look at this?

**Comment by micheleselea** [comment]
yes I'm going to check



*Michele Pradella*
/R&D Software Engineer
/ michele.pradella@selea.com <mailto:michele.pradella@selea.com>
Office: +39 0375 889091

------------------------------------------------------------------------
	
------------------------------------------------------------------------
Selea s.r.l

V. Aldo Moro, 69
46019 Cicognara MN - Italy
Phone: +390375889091
Fax: +390375889080
http://www.selea.com

	

Note: The information contained in this message may be privileged and 
confidential and protected from disclosure. If the reader of this 
message is not the intended recipient, or an employee or agent 
responsible for delivering this message to the intended recipient, you 
are hereby notified that any dissemination, distribution or copying of 
this communication is strictly prohibited. If you have received this 
communication in error, please notify us immediately by replying to the 
message and deleting it from your computer. Thank you.

Il 29/06/2018 16.47, Aleksandar Fabijanic ha scritto:

**Comment by micheleselea** [comment]
I think the problem is I left FTPPasswordProvider in FTPSSteamFactory.cpp too
I'm going to update the code, probably the best way to fix it is to move FTPPasswordProvider in a different file. Let me know @aleks-f  if you prefer

**Comment by aleks-f** [comment]
@micheleselea yes, different file best

**Comment by Good-Pudge** [comment]
I close issue. It was fixed
