### ISSUE TITLE
ApacheConnector is not compiling on release 1.9.0, but it is on the development branch

### ISSUE THREAD

**Issue by edson-a-soares** [pocoproject/poco#2379]
**ApacheConnector** is not compiling on release 1.9.0. 
But, the development branch is compiling normally.

Both, those two below-as-yet-unmentioned items, are missing in the release, and available in the `development` branch. They just need to be added to the release code.

- It is not compiling because of an abstract method **bool secure() const** defined in **HTTPServerRequest** that is not implemented by **ApacheServerRequest**, one of its derived classes.

- Also, It is not compiling because, in the release version, it is missing the piece of code that adds support for a few functions that were renamed in **Apache 2.4**. As it is in the comments:
    > The properties conn_rec->remote_ip and conn_rec->remote_addr have undergone significant changes in Apache 2.4. Validate Apache version for using conn_rec->remote_ip and conn_rec-> remote_addr proper versions.

**Tools**
Poco 1.9.0
GCC6/G++6
Debian 9/Ubuntu 16.04 LTS

**Comment by aleks-f** [comment]
cherry-pick from development into [1.9.1 branch](https://github.com/pocoproject/poco/tree/poco-1.9.1), send pull, and it will be in the next release

**Comment by edson-a-soares** [comment]
Unfortunately, a cherry-pick won't work without penalties. A few validations were made directly in the last release version. They are not present in the `development` branch. A cherry-pick would override them. Would it not be better to do the same validations, for cxx11, in this case, and after that pull into `development` and `1.9.1 branch`?
