### ISSUE TITLE
iOS how to set TextField text value

### ISSUE THREAD

**Issue by mizhdi** [pocoproject/poco#2385]
`poco("Table").child("Cell")[0].child("TextField").set_text('text')`

`poco.exceptions.InvalidOperationException: "Unable to set attribute "text" of node "{'name': 'TextField', 'payload': {'type': 'TextField', 'isEnabled': '1', 'name': 'TextField', 'size': [0.6106666666666667, 0.06746626686656672], 'pos': [0.652, 0.18515742128935533], 'zOrders': {'local': 0, 'global': 0}, 'anchorPoint': [0.5, 0.5], 'visible': True}, '__parent__': <poco.freezeui.hierarchy.Node object at 0x10f86f978>}"." of "UIObjectProxy of "Table/Cell[0]/TextField""`

**Comment by aleks-f** [comment]
looks like you're posting in the wrong place
