### ISSUE TITLE
How to properly stop and exit a Poco::Redis::AsyncReader ?

### ISSUE THREAD

**Issue by HW201807** [pocoproject/poco#2387]
#### Expected behavior
calling stop() on the reader will at some point cause the thread to stop, so that deleting it will not hang indefinitely.
#### Actual behavior
calling stop does set the activity flag, but the readers runActivity function is using a blocking read. So without another reply from the server, the reader never exits. 

#### Steps to reproduce the problem
            redis_client.connect(host, port, t);
            reader = new AsyncReader(redis_client);
            reader->start();
            reader->stop();
            delete reader; // this will not return, since it waits for the thread to exit

#### POCO version
1.9.0

#### Compiler and version
gcc
#### Operating system and version
ubuntu 18.04
#### Other relevant information
I tried sending a last message to the server so the reader will actually get out of its loop, but disconnecting the redis_client before the reader has processed the reply will cause a crash. So i would have to add some kind of unmotivated Thread::sleep call to wait until the reader is finished, or wait for the reply to be processed. Doesn't really work if the reply never arrives because the server went away.
I also noticed the reader is using
if (!_activity.isStopped()) Thread::trySleep(100);
I don't see how that will do any good if the actual call
 RedisType::Ptr reply = _client.readReply();
is blocking anyway.

**Comment by fbraem** [comment]
It's possible to stop the reader in the redisResponse event by calling the stop method of RedisEventArgs. You can see a sample in the [test code](https://github.com/pocoproject/poco/blob/develop/Redis/testsuite/src/RedisTest.cpp). When disconnecting the client, I would expect that a redisException event is triggered.

**Comment by HW201807** [comment]
thank you for the reply. I'll try disconnecting the client and stopping the reader in the the error handler, if one is thrown.
It still seems strange that there is a stop function at all then, if it can't be used. And having to disconnect from the redis server just to stop the reader that is using the connection seems wrong too.
