### ISSUE TITLE
Dynamic::Var::convert throw SyntaxException

### ISSUE THREAD

**Issue by SmileGobo** [pocoproject/poco#2394]
#### Expected behavior
By a documentation this method throw only InvalidAccess, Range and NotImplemented exceptions, but next code generate SyntaxException.
#### Steps to reproduce the problem
```cpp
#include <iostream>
#include <Poco/Dynamic/Var.h>

void PrintFloatValue(const Poco::Dynamic::Var& value = Poco::Dynamic::Var()) {
    
    try{
        std::cout << "value is = " << value.convert<float>() << std::endl; 
    }
    catch (Poco::RangeException& ) {
        std::cerr << "wrong value type" << std::endl;
    }
    catch(Poco::InvalidAccessException& ) {
        std::cerr << "detect empty val" << std::endl;
    }
}
   
   
int main() {

    const std::string wrong = "wrong data value";
    const float valid = 3.343;
    PrintFloatValue(valid); //ok type convert success
    PrintFloatValue(wrong); //RangeException is expeted  but throw SyntaxException
    PrintFloatValue();      // ok detect empty val

}
```
#### POCO version
1.9.0
#### Compiler and version
gcc 4.8
#### Other relevant information
I'm detected this behavior, when I use Poco::JSON::Object

**Comment by aleks-f** [comment]
`"wrong data value"` is wrong datatype for a float, not out of range value. `SyntaxException` is coming from [NumberParser](https://github.com/pocoproject/poco/blob/poco-1.9.0/Foundation/include/Poco/NumberParser.h#L125)

**Comment by SmileGobo** [comment]
This is not an obvious behavior, the documentation does not say this. It is even more unclear about this in the documentation of *Poco::JSON::Object(Array)* methods. I want to get an unambiguous exception about a bad type(BadcastException for example), and not a set of randomly reproducible exceptions.

P.S.
When I try to get a value from the object's json field, will I get some more non-documented behavior?

**Comment by aleks-f** [comment]
If you follow the link above, you will see that this exception is, in fact, (a) documented and (b) there's nothing ambiguous about it - a string that does not contain characters interpretable as a floating point number is syntactically invalid in the NumberParser conversion to float context. 

If you want documentation for every class to spell every exception that can be thrown by every one of its members, please do update the documentation and send a pull request; we will consider it for merging.

Not directly applicable in this case, but related: I recommend reading [Deprecating Exception Specifications](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3051.html), specifically:

> In practice, only two forms of exception-throwing guarantees are useful: an operation might throw an exception (any exception) or an operation will never throw any exception.
