### ISSUE TITLE
Minimum Win API version

### ISSUE THREAD

**Issue by Good-Pudge** [pocoproject/poco#2412]
Have POCO CMake variable to set minimum Win API version? I think, it would be useful.

**Comment by OgreTransporter** [comment]
See https://github.com/pocoproject/poco/issues/2306

Also, by using C++11 you've a pre-selection of the compiler which leads to a minimum Windows version.

**Comment by aleks-f** [comment]
My understanding of the original request is that it wants to introduce `POCO_WINSDK_VERSION` equivalent define of what we find on the system. Which is fine, but no going back to redefining system macros found on the system - that was a fix at one point, for some old problems and does not apply anymore.

**Comment by Good-Pudge** [comment]
But how I can set minimum Win SDK version? For example: I use Win10, but I need library support since WinXP. Do I should to use WinXP?

**Comment by Good-Pudge** [comment]
I want to introduce `POCO_WINSDK_VERSION` to set `_WIN32_WINNT` and `WINVER`.

**Comment by aleks-f** [comment]
> I want to introduce POCO_WINSDK_VERSION to set _WIN32_WINNT and WINVER.

we've just got rid of that, see #2306
