### ISSUE TITLE
SecureServerSocket doesn't work with IpV6

### ISSUE THREAD

**Issue by dudym** [pocoproject/poco#2418]
Should be able to bind socket of SecureServerSocket to IPv6 socket

It actually causes a crash when calling socket.listen()

**Comment by bselu-cso** [comment]
Although this has been fixed over two years ago this is still not part of the latest release 1.10.1. In the changelog of 1.10.0 this is claimed though: https://github.com/pocoproject/poco/blob/master/CHANGELOG

Seems like this has been merged to develop-experimental only. Maybe this slipped through?
