### ISSUE TITLE
Build Error Poco 1.9.0 with OpenSSL 1.1.0h

### ISSUE THREAD

**Issue by NeoDreamer4** [pocoproject/poco#2425]
I tried to build POCO library v1.9.0 with OpenSSL 1.1.0h. But it was fail with link error.
I use OpenSSL from https://slproweb.com/products/Win32OpenSSL.html
The below log is a part of build log.

++++ Building [Crypto_vs100.vcxproj]
    :
         obj\Crypto\debug_shared\ECKeyImpl.obj
            Creating library ..\lib\PocoCryptod.lib and object ..\lib\PocoCryptod.exp
     1>ECKey.obj : error LNK2019: unresolved external symbol _EVP_PKEY_cmp referenced in function "public: __thiscall Poco::Crypto::ECKey::ECKey(class Poco::Crypto::ECKey const &)" (??0ECKey@Crypto@Poco@@QAE@ABV012@@Z) [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>ECKeyImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>RSAKeyImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>PKCS12Container.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>EVPPKey.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>ECDSADigestEngine.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>CipherFactory.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>RSACipherImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>RSADigestEngine.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>RSAKey.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>ECKey.obj : error LNK2001: unresolved external symbol _EVP_PKEY_type [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     1>ECKeyImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_type [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
     :
     1>Done Building Project "E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj" (build target(s)) -- FAILED.

Build FAILED.

       "E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj" (build target) (1) ->
       (Link target) -> 
         ECKey.obj : error LNK2019: unresolved external symbol _EVP_PKEY_cmp referenced in function "public: __thiscall Poco::Crypto::ECKey::ECKey(class Poco::Crypto::ECKey const &)" (??0ECKey@Crypto@Poco@@QAE@ABV012@@Z) [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         ECKeyImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         RSAKeyImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         PKCS12Container.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         EVPPKey.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         ECDSADigestEngine.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         CipherFactory.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         RSACipherImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         RSADigestEngine.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         RSAKey.obj : error LNK2001: unresolved external symbol _EVP_PKEY_cmp [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         ECKey.obj : error LNK2001: unresolved external symbol _EVP_PKEY_type [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         ECKeyImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_type [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         RSAKeyImpl.obj : error LNK2001: unresolved external symbol _EVP_PKEY_type [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]
         :
        ..\bin\PocoCryptod.dll : fatal error LNK1120: 129 unresolved externals [E:\DevWork\Poco\poco-1.9.0-all_mysql_5720_openssl_102o\Crypto\Crypto_vs100.vcxproj]

    0 Warning(s)
    227 Error(s)

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX  BUILD FAILED. EXITING. XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by aleks-f** [comment]
well, if you are using your own OpenSSL, then you have to tell the build system where the binaries are. clone our [custom-built openssl](https://github.com/pocoproject/openssl/tree/master) into poco directory, and all should be in place

**Comment by NeoDreamer4** [comment]
Thanks for reply but I do not use my own OpenSSL. I use the OpenSSL from Shining Light Productions by introduction on the Poco homepage.

> "The easiest way to install OpenSSL on Windows is to use a binary (prebuild) release, for example the installer from Shining Light Productions."

Is there any problem with Poco 1.9 about OpenSSL or Shining Light Productions?
How to use [custom-built openssl](https://github.com/pocoproject/openssl/tree/master)?
Do I need to build  [custom-built openssl](https://github.com/pocoproject/openssl/tree/master)?

**Comment by zosrothko** [comment]
On Windows system, Poco is providing its own build of the OpenSSL library. You should import the OpenSSL package with:
`git submodule update --init --recursive --remote openssl`
then just rebuild poco as usual

**Comment by aleks-f** [comment]
known problems with pre-built non-poco openssl 1.1.x binaries are described on our openssl github page under notes. as far as I know, they apply to static builds and shining light suffers from those, but they probably do not apply in this case, which is  obviously linking with binaries that somehow don't have EVP* functions exported or there's something else (eg. stale intermediate binaries or something similar)

**Comment by NeoDreamer4** [comment]
Thanks all. I did it.
