### ISSUE TITLE
What happened to NetConf? 

### ISSUE THREAD

**Issue by rohaanhamid** [pocoproject/poco#2427]
#### Expected behavior
I see a module called NetConf in a few older versions of POCO. Has it been completely removed or has it been reintegrated somewhere else in the code? I am specifically looking for a C++ implementation of SNMP.

If that hasn't been done or hasn't already been planned, I can look at porting Net SNMP to POCO.

#### Actual behavior
N/A
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.9.0
#### Other relevant information
https://www.appinf.com/docs/poco-2008.2/NetconfUserGuide.html
http://www.net-snmp.org

**Comment by aleks-f** [comment]
Was commercial, never part of boost licensed poco, afaik abandoned.
