### ISSUE TITLE
POCO Net build fails with clang-cl 6.00 on Windows

### ISSUE THREAD

**Issue by rokel** [pocoproject/poco#2428]
#### Expected behavior

Can compile POCO on Windows with clang-cl 6.00.

#### Actual behavior

 Build fails with the following:

```
[build] ..\Core\externals\OSAL\externals\POCO\Foundation\include\Poco/Tuple.h(4492,45):  error: missing 'typename' prior to dependent type name 'TypeWrapper<IPAddress>::TYPE'
[build]                 typename TypeWrapper<T1>::CONSTTYPE& t1 = POCO_TYPEWRAPPER_DEFAULTVALUE(T1),
[build]                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] ..\Core\externals\OSAL\externals\POCO\Foundation\include\Poco/Tuple.h(29,42):  note: expanded from macro 'POCO_TYPEWRAPPER_DEFAULTVALUE'
[build] #define POCO_TYPEWRAPPER_DEFAULTVALUE(T) TypeWrapper<T>::TYPE()
[build]                                          ^~~~~~~~~~~~~~~~~~~~
```

As clang-cl defines _MSC_VER for compatibility, but this is then used in Tuple.h to omit the `typename` keyword, presumably for compatibility with MSVC.

Note this is the only build error, which is impressive!

#### POCO version

1.9.1

#### Compiler and version

Clang 6.0.0

#### Operating system and version

Windows 10 x64

#### Other relevant information

Seems like this is an easy fix - remove the `#ifdef` conditional [here](https://github.com/pocoproject/poco/blob/poco-1.9.1/Foundation/include/Poco/Tuple.h#L28) and never omit typename.

At the very least it seems to work fine with MSVC 2017. If it fails with earlier MSVC compilers then this fix seems equally easy, only omit if version is less than 2017.

**Comment by aleks-f** [comment]
as if it's not enough to have multiple compilers to deal with,  now we also have a compiler pretending to be all other compilers. anyway, thanks and see if the fix works for you

**Comment by rokel** [comment]
Indeed. Thanks for the quick fix, worked perfectly.
