### ISSUE TITLE
Poco ODBC SQL_LONGVARCHAR & SQLServer

### ISSUE THREAD

**Issue by rAndom69** [pocoproject/poco#243]
Poco (1.4.6) ODBC parameter binder uses SQL_LONGVARCHAR.
This however does not seem to be SQLServer express compatible (however only in WHERE clause where source field is VARCHAR or CHAR - for example INSERTs are working fine), SQL_VARCHAR is.

To make myself clear
INSERT INTO Table (VarcharColumn) VALUES (?), use(std::string) works
SELECT * FROM Table WHERE VarcharColumn = ?, use(std::string) does _not_ work

Per MSDN this type has no mapping in SQL-92 (thus I would expect it to work in less cases than "adequate" SQL_VARCHAR).
Is there a reason (different database which _needs_ SQL_LONGVARCHAR) for this ?

**Comment by aleks-f** [comment]
Both SQL_VARCHAR and SQL_LONGVARCHAR are [legitimate ODBC types](http://msdn.microsoft.com/en-us/library/ms710150(v=vs.85).aspx), the only difference is that max SQL_LONGVARCHAR length is datasource-specific fixed value.
