### ISSUE TITLE
Debug libraries with cmake

### ISSUE THREAD

**Issue by swt2c** [pocoproject/poco#2448]
Using poco 1.9.0, when building with the UNIX Makefiles (ie, ./configure and make), the debug versions of the library are automatically built (e.g, libPocoFoundationd.so).  When building with cmake, however, these versions are not built.  How do I get cmake to produce the debug versions of the library?

**Comment by Bjoe** [comment]
When I build poco 1.9.0 with cmake as debug type, I have a libPocoFoundationd.so and libPocoFoundationd.so.60
With which parameters you execute cmake and can you add your build output here?

**Comment by swt2c** [comment]
> When I build poco 1.9.0 with cmake as debug type

How do I build poco with cmake as debug type?

**Comment by Bjoe** [comment]
cmake -DCMAKE_BUILD_TYPE=Debug .....

**Comment by Bjoe** [comment]
See also https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

**Comment by swt2c** [comment]
Thanks.
