### ISSUE TITLE
http client timeout on Windows 7 and Server 2008 R2

### ISSUE THREAD

**Issue by tomaz-beltram** [pocoproject/poco#2451]
#### Expected behavior
The sample application "httpget.exe http://google.com/" should return the requested page.
#### Actual behavior
The sample application returns a timeout error.
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
- build poco with ENABLE_SAMPLES
- run httpget against a web page using http (not https!)
#### POCO version
1.9.1 and develop (as of 3.9.2018)
#### Compiler and version
VS2017
#### Operating system and version
Windows Server 2008R2, Windows 7 Home, both 32 and 64 bit versions
#### Other relevant information
Using bisection I was able to find the offending commit on develop branch 86897d that was merged to 1.9.1 branch. Same problem exists also there and was introduced with changes for #2330.

Windows 10 works fine.

**Comment by aleks-f** [comment]
@tomaz-beltram can you please send pull?

**Comment by aleks-f** [comment]
ah, now i see it, thanks

**Comment by aleks-f** [comment]
08183659851a25a73488ee9b2c753eb00cd91ccd
f140808fabbb6d80aa4367f92c2f8d3a7b8c00c5

**Comment by Diversus23** [comment]
I have this error repeated in my own http server application. Works in Win 10 and does NOT work in Win2008 and Win7.
Is this fix fixed in 0818365 and f140808 commits?
Thank you for your work!

**Comment by tomaz-beltram** [comment]
Yes, the fix is on develop and poco-1.9.1 and it works for me.
