### ISSUE TITLE
Poco::Redis after executing "auth" command next command always return "OK"

### ISSUE THREAD

**Issue by foxhlchen2** [pocoproject/poco#2457]
After You run Redis auth command,  whatever command executed next would always return a string "OK".
It seems that the result of the auth command remains in the buffer and will be fetched by your next command execution.

      Client client("host:port");
       Array array;

       array << "auth" << "passwd";
       client.execute<void>(array);

       array.clear();
       array << "GET" << "key";
       client.execute<string>(array);       <----- always get "OK", instead of value of _key_

       array.clear();
       array << "GET" << "key";
       client.execute<BulkString>(array);      <----- now you can get correct value of _key_

#### Expected behavior
return the result of your execution

#### Actual behavior
always return "OK"

#### Steps to reproduce the problem
run auth command first, then run GET command you will always get the result "OK".

#### POCO version
1.9.0

#### Compiler and version
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

#### Operating system and version
Ubuntu 18.04 LTS

#### Other relevant information
none

**Comment by fbraem** [comment]
The result of the command [auth](https://redis.io/commands/auth) is a string. So you need to execute auth as follows:

`client.execute<string>(array)`

**Comment by foxhlchen** [comment]
I did try that. Raised type conversion error. In fact, I’ve  tried all of
types, only void can work normally.

**Comment by fbraem** [comment]
Can you check if the sendAuth method of the Client class works for you?

**Comment by foxhlchen** [comment]
I didn’t notice the Client class has this method. It’s not in the manual
https://pocoproject.org/docs/Poco.Redis.Client.html

**Comment by fbraem** [comment]
It seems that sendAuth is currently only available in the develop branch.

**Comment by foxhlchen** [comment]
Ok, hope it would be released sooner.  I'm using my temporary solution by getting random key immediately after Auth for now.

**Comment by fbraem** [comment]
I've tried the AUTH command with the testsuite and I get OK. I used the **develop** branch of POCO.

    void RedisTest::testAUTH()  
    {  
        Array command;  
        command << "AUTH" << "foobared";  
        std::string result = _redis.execute<std::string>(command);  
        std::cout << "Result: " << result;  
    }  

And this is the result:

    ./testrunnerd testAUTH
    Connected to [127.0.0.1:6379]

    testAUTH: Result: OK

    OK (1 tests)

    Disconnected from [127.0.0.1:6379]
