### ISSUE TITLE
Parsing and printing out UTF-8 XML containing umlauts.

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#2460]
#### Expected behavior
Read in XML File which has UTF-8 Encoding (verified via Notepad++) and print the content to the Screen
#### Actual behavior
Any word with umlauts in it are not display/stored correctly.
More information are provided in the next section.
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

This is the `XML` File I try to read.
```XML
<?xml version="1.0" encoding="UTF-8"?>
<Buecherei>
    <Mitarbeiterliste>
        <Mitarbeiter id="42">
            <Vorname>Max</Vorname>
            <Nachname>Müller</Nachname>
        </Mitarbeiter>
        <Mitarbeiter id="44">
			<Vorname>Erika</Vorname>
            <Nachname>Möller</Nachname>
        </Mitarbeiter>
    </Mitarbeiterliste>
</Buecherei>
```

This is the Code to read the `XML` File:

```cpp
int main()
{	
	DOMParser parser;
	std::ifstream in("D:\\umlauteXML.xml");
	InputSource src{ in };
	AutoPtr<Document> pDoc = parser.parse(&src);

	std::string nachname = pDoc->getNodeByPath("/Buecherei/Mitarbeiterliste/Mitarbeiter[0]/Nachname")->innerText();
	std::cout << nachname << std::endl;
}
```

On the Screen `M├╝ller` gets displayed instead of `Müller`.
The Variable `nachname` contains this value: `MÃ¼ller`.

Did I had to change something on the Encoding for the DOM Parser?
#### POCO version
1.9.0
#### Compiler and version
Visual Studio 2017 (Plattform Toolset is v141, SDK Version is 10.0.17134.0)
#### Operating system and version
Windows 10
#### Other relevant information
If information are missing please let me know and I update this post.

**Comment by micheleselea** [comment]
be sure you are giving UTF8 string to the parser. It's quite normal that printing out UTF string give you strange result, you should convert for example to Latin1 before printing out.
The content of the variable you see is probably the UTF8 encoding for u umlaut
