### ISSUE TITLE
QNX cross compile giving Error In src/File_UNIX.cpp:29:24: fatal error: sys/statfs.h: No such file or directory

### ISSUE THREAD

**Issue by bakkiraju** [pocoproject/poco#2462]
#### Expected behavior
Poco Foundation compilation should succeed
#### Actual behavior
Compilation terminates with error 
#### Steps to reproduce the problem
1.In build/config/QNX set
CCVER   = 5.4.0,gcc_ntoaarch64le

2. configure for QNX
./configure --config=QNX --omit=NetSSL_OpenSSL,Crypto,Data/ODBC,Data/MySQL  --static  --no-tests --no-samples

3. Build
make -j

#### POCO version
1.9.0
#### Compiler and version
 5.4.0,gcc_ntoaarch64le

Compiler that came with QNX 7.0 Software developer platform, Momentics download

#### Operating system and version
Linux 4.15.0-33-generic #36~16.04.1-Ubuntu

#### Other relevant information
NA

**Comment by bakkiraju** [comment]
Fixed the issue by adding the following change in File_UNIX.cpp

#elif (POCO_OS == POCO_OS_SOLARIS) || (POCO_OS == POCO_OS_QNX)
#include <sys/statvfs.h>
#else

QNX7.0 seems to be using header <sys/statvfs.h> instead of <sys/statfs.h>

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/61a49ccb98ceac75be2913f18e63ff6ad58793b9
