### ISSUE TITLE
Operating system specific thread ID is not available any more in Logger/Formatter.

### ISSUE THREAD

**Issue by tomaz-beltram** [pocoproject/poco#2465]
#### Expected behavior
Logger should be able to report operating system specific thread ID.
#### Actual behavior
The std native_handle is returned instead when using the %O Formatter parameter.
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
Add %O option to Foundation/samples/Logger/Logger.cpp and check output.
#### POCO version
develop as of 13 Sep 2018.
#### Compiler and version
gcc 5.4
#### Operating system and version
Ubuntu 16.04
#### Other relevant information
This used to work until the C++11 changes were merged in on 20 Sep 2017 and std::thread is used across all platforms.

**Comment by tomaz-beltram** [comment]
Added pull request for OS specific thread ID: https://github.com/pocoproject/poco/pull/2466.

**Comment by matejk** [comment]
Logging displays 0 for %O unless Poco threads are used. Furthermore, std::thread ID are very long handles unrelated to system IDs.
