### ISSUE TITLE
Application::processOptions()

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2468]
the OptionProcessor throw an exception if we give it an argument not configured in defineOptions().
The problem is that the exception is thrown out of the main application so is uncatchable.
Is there a way to handle it? so for example simply ignore command line unknown? or could be an option of OptionSet?

**Comment by aleks-f** [comment]
Looking through the code, it seems there's no way to control it. Perhaps `Application::processOptions` could be made virtual and protected. I've done some work recently where I found the logic quite constraining for some fairly complex option logic.
