### ISSUE TITLE
UNIX FileImpl::copyToImpl permissions

### ISSUE THREAD

**Issue by syvex** [pocoproject/poco#247]
Is there any reason to mask out all file permissions except those for the user in the UNIX implementation of FileImpl::copyToImpl? I would expect the permissions to be preserved for any file copy.

```
    int dd = open(path.c_str(), O_CREAT | O_TRUNC | O_WRONLY, st.st_mode & S_IRWXU);
```

**Comment by aleks-f** [comment]
[fixed](https://github.com/pocoproject/poco/commit/8f15c1cf24eedbe22e367c4528dd4da54d396be2#diff-76dd74a8d4a4278f23550a8aaa9d0f8c)
