### ISSUE TITLE
Failed to generate Poco::Remoting sources

### ISSUE THREAD

**Issue by definename** [pocoproject/poco#2472]
#### Expected behavior
Generate code with RemoteGenNG tool

#### Actual behavior
I have this error: "could not read the bin file"

#### Steps to reproduce the problem
Here is how I call Poco RemoteGenNG tool:

RemoteGenNG --compiler=gcc --define=POCO_BASE=$POCO_BASE myxmlfile.xml

#### POCO version
1.7.6

#### Compiler and version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

#### Operating system and version
Description:	Ubuntu 16.04.5 LTS

#### Other relevant information
POCO was not installed with *.tar.gz archive provided from your web side instead of that POCO sources were copied into my project source directory and environment variables were configured in .bashrc file in this way:

export POCO_BASE=/home/olehk/pocopro
export PATH=$PATH:$POCO_BASE/bin/Linux/x86_64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$POCO_BASE/lib/Linux/x86_64

Here is example of calling RemoteGenNG tool:

![2018-09-19 18_12_59-virtualbox](https://user-images.githubusercontent.com/9870947/45762981-449b0280-bc38-11e8-897f-ebc4495b908a.png)

**Comment by aleks-f** [comment]
LOL, the question looks like a FOIA release - how can we help if we can't see what's in the XML file? Besides, this is part of PocoPro, and probably not relevant anymore for you, but I'll leave it open for the time being.
