### ISSUE TITLE
Documentation update regarding SQL over Data under Poco namespace

### ISSUE THREAD

**Issue by milligan22963** [pocoproject/poco#2474]
Going by the example regarding RecordSet
https://pocoproject.org/docs/00200-DataUserManual.html#26

I believe it should indicate to use the namespace Poco::SQL opposed to Poco::Data as described in the guide.  The sample code [(TypeHandler.cpp)](https://github.com/pocoproject/poco/blob/develop/SQL/samples/TypeHandler/src/TypeHandler.cpp) under Poco/SQL looks correct.

#### Expected behavior
No build errors

#### Actual behavior
error: namespace alias ‘Poco::Data’ not allowed here, assuming ‘Poco::SQL’
 namespace Data {

#### Steps to reproduce the problem
namespace Poco {
namespace Data {
....

#### POCO version
1.9.0

#### Compiler and version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

#### Operating system and version
Ubuntu 5.4.0-6ubuntu1~16.04.10

**Comment by obiltschnig** [comment]
You are referring to the develop branch which has not been released yet and which has the change from Data to SQL namespace. The current release (1.9.0) still has the Data namespace.

**Comment by milligan22963** [comment]
Ok thanks for the information.
