### ISSUE TITLE
extracting a single file from a JAR file doesn't work

### ISSUE THREAD

**Issue by wolfgang-f** [pocoproject/poco#2477]
#### Expected behavior
Extracting a single file from a zip archive as described in the zip user guide should work.

#### Actual behavior
Extracting a single file from a JAR file as described in the user guide is not working.

#### Steps to reproduce the problem
            std::ifstream inp(_zipFile.c_str(), std::ios::binary);
            poco_assert(inp);
            Poco::Zip::ZipArchive arch(inp);
            Poco::Zip::ZipArchive::FileHeaders::const_iterator it = arch.findHeader("plugin.properties");
            poco_assert(it != arch.headerEnd());
            Poco::Zip::ZipInputStream zipin(inp, it->second);

            std::ostringstream out(std::ios::binary);
            std::size_t bytes = Poco::StreamCopier::copyStream(zipin, out);
            std::cout << "bytes copied: " << bytes << std::endl;
=> produces:
bytes copied: 0
(should be 279 bytes according to 7-zip)

Use the JAR-file included in this zip-file to reproduce the problem:
[org.eclipse.core.runtime_3.13.0.v20170207-1030.zip](https://github.com/pocoproject/poco/files/2411117/org.eclipse.core.runtime_3.13.0.v20170207-1030.zip)

#### POCO version
1.9.0

#### Compiler and version
VS 2017 Version 15.2

#### Operating system and version
Windows 7 64 Bit SP1

**Comment by obiltschnig** [comment]
The `inp` stream is in EOF state after finding the header.
Adding a `inp.clear();` before creating the `ZipInputStream` fixes this.
