### ISSUE TITLE
Data/SQLite in develop does not support automatic retry 

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#248]
This was implemented in 1.3.4 and was available up to 1.4.6, but has not been integrated to develop. While at it, also check that all other SQLite improvements added in 1.3.x and 1.4.x have been integrated to develop.

See also: http://stackoverflow.com/questions/17863464/retries-with-locked-sqlite-databases-in-poco-1-5-x

**Comment by DomXC** [comment]
Thanks! I had the same problem... anyway, @cristiantm, could you also check #1729, please?
