### ISSUE TITLE
websocket's file descriptor is not accessible

### ISSUE THREAD

**Issue by bakkiraju** [pocoproject/poco#2482]
#### Expected behavior
I  want to pass a websocket fd to a child process that is spawned  by the websocket server,so that child process can reply back to the client. For that I was expecting I can do something like  ws.sockfd()

#### Actual behavior
No public API to do the above

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.9.0

#### Compiler and version
qcc 7.0 toolchain
#### Operating system and version
QNX

**Comment by Boneau2007** [comment]
Actually you should be able to access it. If you create your Websocket with a HTTPClientSession for example. You can access the fd aligned to it with something like session.socket().socketfd(). That should give you the socket descriptor for this specific socket. Just look in the Websocket() Doc then to the HTTPClientSession (which derives its socket() function from HTTPSession) to StreamSocket (which derives its socketfd() function from Socket)

**Comment by himacro** [comment]
I found a workaround:  `ws.impl()->sockfd()`. Hope it could  help.
