### ISSUE TITLE
How to make a cmake file (CMakeLists.txt) for an application that uses Poco?

### ISSUE THREAD

**Issue by Diversus23** [pocoproject/poco#2483]
Hi! Thank You for your work. Poco is a good project. But I faced the following problem. Please tell me how to make a cmake file (CMakeLists.txt) for an application that uses Poco? How and what dependencies to specify, etc.
Now I'm writing using Visual Studio, but I'm going to use the application on Linux.
Documentation on this topic I have not found.
Thank you!

**Comment by Bjoe** [comment]
Add in your CMakeList.txt following:

```
find_package(Poco REQUIRED .....) 
```
As ... add here the components that your are needed. For example:

```
find_package(Poco REQUIRED Foundation Net NetSSL JSON)
```

After that, you can add for example the ``Poco::NetSSL`` target/component into ``target_link_libraries`` ...

For example:
```
target_link_libraries(<your_project_target_name> PUBLIC
...
  Poco::NetSSL
...
)
```

That`s it.

**Comment by killerbot242** [comment]
what did you use in order to have this IMPORTED targets being active, since cmake does not povide a FindPoco.cmake ?

**Comment by briandilley** [comment]
This only works if the pkg-config files are available for Poco

**Comment by pkeir** [comment]
I ran `pkg-config --list-all | grep -i poco` which produced nothing on Ubuntu 19.10.

**Comment by TheMaverickProgrammer** [comment]
find_package(...) for poco adds extra libs like zlib and pcre.lib that fails to compile. You have to manually remove these from your project dependecnies...

**Comment by Bjoe** [comment]
If you install poco project, they also installed the cmake config-moduls, so you can "use" it as I said on https://github.com/pocoproject/poco/issues/2483#issuecomment-425129053

If you didn't like to install it, here is an easy example to use poco: https://github.com/pocoproject/cmake-sample

**Comment by Bjoe** [comment]
> what did you use in order to have this IMPORTED targets being active, since cmake does not povide a FindPoco.cmake ?

cmake will never be provide a "FindPoco.cmake" :-) ... but poco provides it :-)

**Comment by killerbot242** [comment]
indeed the cmake-sample, make use of FetchContent, which is a very good solution, just source consume the poco project.
One thing which is very important is that projects, like in this scenario poco, should never assume they are the top project, and as such when they are not, should not decide on compiler flags (CMAKE_CXX_FLAGS) the standard version. They should set the compiler flags,, options on their targets.

For example poco now is not doing a good job for setting the C++ standard, if I recall correctly. Once started investigating, should pick this up again for improvement.

**Comment by themightyoarfish** [comment]
Where is the usage in CMake documented? I've searched far and wide the only mention of how to use this is in github issues.
