### ISSUE TITLE
Compiler error when using const value in Poco::Data::Keywords::use

### ISSUE THREAD

**Issue by petko** [pocoproject/poco#2486]
The following code triggers Poco assertion about passing const ref to `use`:

```
    const std::string id = UuidToStdString(attribute.GetId());

    session_ << "DELETE FROM attribute WHERE id = :id", use(id), now;
```

I am passing const std::string value, not reference. Why I am getting this error?

P.S.: The same error happens when using `const std::size_t var`..
P.P.S.: Using Poco 1.9.0 in Visual Studio 2017 15.8.5.

**Comment by aleks-f** [comment]
It is `const std::string&` in the function.
It is not allowed to prevent this:
```
Statement stmt = (session_ << "DELETE FROM attribute WHERE id = :id", use("id"));
```
where "id" becomes `const std::string&` that likely does not exist any more when this happens:
```
stmt.execute();
```
So we force users to bind (ie. use the version of call that makes a copy).
