### ISSUE TITLE
testLaunch tests fail on armv7l

### ISSUE THREAD

**Issue by nikitarulz** [pocoproject/poco#2488]
testLaunch test cases are failing on armv7l architecture

```
There were 4 failures: 
 1: N7CppUnit10TestCallerI11ProcessTestEE.testLaunch
    "rc == 3"
    in "src/ProcessTest.cpp", line 63
 2: N7CppUnit10TestCallerI11ProcessTestEE.testLaunchRedirectIn
    "rc == 100"
    in "src/ProcessTest.cpp", line 91
 3: N7CppUnit10TestCallerI11ProcessTestEE.testLaunchRedirectOut
    "s == "Hello, world!""
    in "src/ProcessTest.cpp", line 120
 4: N7CppUnit10TestCallerI11ProcessTestEE.testLaunchEnv
    "s == "test""
    in "src/ProcessTest.cpp", line 153
```

Poco version: 1.7.5-all

**Comment by nikitarulz** [comment]
Found out the solution:

These failure test cases are dependent on TestApp and TestAppd library files. Either copy these files in /usr/lib or set $LD_LIBRARY_PATH to directory where these libraries are present.

**Comment by zosrothko** [comment]
@nikitarulz Not exactly. The proper solution is to add the path of the directory containing those `TestApp`& `TestAppd`into the PATH variable. LD_LIBRARY_PATH is used for shared library.

**Comment by nikitarulz** [comment]
@zosrothko I tried the way you suggested. But If I include the directory (where `TestApp` and `TestAppd` are present) into PATH variable, the failures will not go away. But including the same path in `LD_LIBRARY_PATH` variable, make the tests pass.
