### ISSUE TITLE
Compiling error for Android in QT C++ application

### ISSUE THREAD

**Issue by unimaxis** [pocoproject/poco#2491]
#### Expected behavior
When compiling POCO with Android QT app, I get errors:
src/Socket.cpp:305: error: undefined reference to '__FD_SET_chk'
src/Socket.cpp:316: error: undefined reference to '__FD_SET_chk'
src/Socket.cpp:327: error: undefined reference to '__FD_SET_chk'
src/Socket.cpp:359: error: undefined reference to '__FD_ISSET_chk'
src/Socket.cpp:370: error: undefined reference to '__FD_ISSET_chk'
src/Socket.cpp:381: error: undefined reference to '__FD_ISSET_chk'
src/SocketImpl.cpp:718: error: undefined reference to '__FD_SET_chk'
src/Mutex_POSIX.cpp:128: error: undefined reference to 'pthread_mutex_timedlock'
src/Thread_POSIX.cpp:43: error: undefined reference to 'sigemptyset'
src/Thread_POSIX.cpp:44: error: undefined reference to 'sigaddset'
src/Thread_POSIX.cpp:331: error: undefined reference to 'sigemptyset'
src/Thread_POSIX.cpp:332: error: undefined reference to 'sigaddset'
src/Thread_POSIX.cpp:333: error: undefined reference to 'sigaddset'
src/Thread_POSIX.cpp:334: error: undefined reference to 'sigaddset'

#### Actual behavior
Toolchain for POCO build as
$ndk_path/Android/android-ndk-r17b/build/tools/make-standalone-toolchain.sh --arch=arm --platform=android-21 --install-dir=$poco_toolchain_path

Poco configure an build as static
./configure --config=Android --no-samples --no-tests --static
make -s -j3 CXXFLAGS='-std=c++11' ANDROID_ABI=armeabi-v7a

#### Steps to reproduce the problem
Simple example of httprest server
[PocoAndroidTest.zip](https://github.com/pocoproject/poco/files/2455595/PocoAndroidTest.zip)

#### POCO version
1.9.1

#### Compiler and version
Android NDK r17b GCC 4.9

#### Operating system and version
Ubuntu 16.04 x64

**Comment by Bjoe** [comment]
First quick question that I have, have you try to use the cmake build system? The cmake build system is the prefered way, at least the cmake build system is tested for android on travis.
So try this:
```
.../android-sdk/cmake/3.6.4111459/bin/cmake -Hpoco-src -Bcmake-build -G'Android Gradle - Ninja' -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=.../android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-21 -DCMAKE_MAKE_PROGRAM=.../android-sdk/cmake/3.6.4111459/bin/ninja -DANDROID_STL="c++_static" -DANDROID_CPP_FEATURES="exceptions rtti" -DENABLE_TESTS=OFF -DBUILD_SHARED_LIBS=OFF && .../android-sdk/cmake/3.6.4111459/bin/cmake --build cmake-build --target all && cd cmake-build
```
.../android-sdk  -> path to your Android-sdk installation.

For more information about the cmake build system see: https://github.com/pocoproject/poco/blob/poco-1.9.1/doc/00200-GettingStarted.page Section: Building using CMake

BTW. this standalone toolchain shell script is obselete and will be removed in the future NDK. Android NDK is using the cmake build system as default.

**Comment by unimaxis** [comment]
@Bjoe 
I rebuilt the POCO library according to your method. But errors in the assembly project has become even more

a small part of them:
`
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/ios:756: error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/__locale:212: error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/ios:529: error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/ostream:739: error: undefined reference to 'std::__ndk1::ios_base::__set_badbit_and_consider_rethrow()'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/ostream:0: error: undefined reference to 'std::__ndk1::ctype<char>::id'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/ios:529: error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/ios:529: error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/ostream:955: error: undefined reference to 'std::__ndk1::ios_base::__set_badbit_and_consider_rethrow()'
/opt/keboxcontrib/lib-armeabi-v7/libPocoFoundationd.a(Bugcheck.cpp.o):Bugcheck.cpp:typeinfo for std::__ndk1::basic_ios<char, std::__ndk1::char_traits<char> >: error: undefined reference to 'typeinfo for std::__ndk1::ios_base'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/ios:690: error: undefined reference to 'std::__ndk1::ios_base::init(void*)'
/home/maxim/work/kebox/poco-1.9.1/Foundation/src/Debugger.cpp:0: error: undefined reference to 'vtable for std::__ndk1::ios_base'
/home/maxim/dev/Android/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
../Foundation/include/Poco/AbstractEvent.h:155: error: undefined reference to 'Poco::FastMutex::FastMutex()'
../Foundation/include/Poco/AbstractEvent.h:170: error: undefined reference to 'Poco::FastMutex::~FastMutex()'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/stdexcept:136: error: undefined reference to 'std::logic_error::logic_error(char const*)'
/home/maxim/dev/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/include/stdexcept:136: error: undefined reference to 'std::logic_error::logic_error(char const*)'
/home/maxim/work/kebox/poco-1.9.1/Net/src/HTTPResponse.cpp:156: error: undefined reference to 'Poco::NumberParser::parse(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, char)'
/home/maxim/work/kebox/poco-1.9.1/Net/src/HTTPResponse.cpp:0: error: undefined reference to 'Poco::DateTimeFormat::HTTP_FORMAT'
../Foundation/include/Poco/DateTimeFormatter.h:158: error: undefined reference to 'Poco::DateTime::DateTime(Poco::Timestamp const&)'
../Foundation/include/Poco/DateTimeFormatter.h:160: error: undefined reference to 'Poco::DateTime::~DateTime()'
../Foundation/include/Poco/DateTimeFormatter.h:160: error: undefined reference to 'Poco::DateTime::~DateTime()'
`

**Comment by unimaxis** [comment]
@Bjoe 
You did not quite understand me. Library managed to collect. But the assembly of the project is made with errors. And I think I understand the reason.

A project in qt is built by NDK using the g++ compiler and gnustl. The POCO library, in turn, is compiled with clang and libc++. In turn, gnustl is not compatible with libc++.

How can I build a POCO with gnustl support?

**Comment by unimaxis** [comment]
Thank  you @Bjoe. The solved the problem. I build QT for android cross compiling with support clang

`
home_dir='/home/maxim'
sdk_path=$home_dir/dev/Android/Sdk
ndk_path=$home_dir/dev/Android/android-ndk-r17b
prefix=$home_dir/Qt/5.11.0/android-armv7_clang

./configure -confirm-license -opensource -xplatform android-clang -nomake tests -nomake examples -android-ndk $ndk_path -android-sdk $sdk_path -android-ndk-host linux-x86_64 -android-toolchain-version 4.9 -no-warnings-are-errors -no-pkg-config -qt-zlib -qt-freetype -android-arch arm64-v8a -android-ndk-platform android-21 -android-arch armeabi-v7a -prefix $prefix -skip qttranslations -skip qtserialport && make -j3 && make install
`
and fix file
Src/qtbase/mkspecs/android-clang/qmake.conf
QMAKE_CFLAGS += -DANDROID_HAS_WSTRING --sysroot=$$NDK_ROOT/sysroot \
replace on
QMAKE_CFLAGS += -DANDROID_HAS_WSTRING --sysroot=$$ANDROID_PLATFORM_ROOT_PATH 

add 
QMAKE_CFLAGS += -DANDROID_HAS_WSTRING --sysroot=$$NDK_ROOT/sysroot \
on end of 
QMAKE_CFLAGS +=

ANDROID_CXX_STL_LIBS = -lc++
replace on
ANDROID_CXX_STL_LIBS = -lc++_shared
