### ISSUE TITLE
Build with VS 2017: Unknown Switch : p:Platform=Win32

### ISSUE THREAD

**Issue by shamusn** [pocoproject/poco#2499]
#### Expected behavior
build a solution file and project files without error.

#### Actual behavior
Invalid Command Line. Unknown Switch : p:Platform=Win32
It still proceeded to create Crypto_vs150.sln.
How can I get rid of this "Invalid"?
Is it safe to ignore?
thanks

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
1. download zip from git
2. open Developer Command Prompt for VS 2017
3. run build_vs150.cmd from .\poco-develop

#### POCO version
2.0.0
#### Compiler and version
Visual Studio 2017
VCToolsVersion=14.15.26726
VisualStudioVersion=15.0

#### Operating system and version
Windows 7

**Comment by shamusn** [comment]
When I open C:\dev\poco\poco-develop\Foundation\Foundation_vs150.sln and build solution, I get the fatal link error below.  Any ideas?

1>Generating Code...
1>   Creating library ..\lib\PocoFoundationd.lib and object ..\lib\PocoFoundationd.exp
1>Foundation_vs150.vcxproj -> C:\dev\poco\poco-develop\Foundation\..\bin\PocoFoundationd.dll
1>Done building project "Foundation_vs150.vcxproj".
2>------ Build started: Project: TestSuite, Configuration: debug_shared Win32 ------
3>------ Build started: Project: TestLibrary, Configuration: debug_shared Win32 ------
2>LINK : fatal error LNK1104: cannot open file 'PocoCppUnitd.lib'
2>Done building project "TestSuite_vs150.vcxproj" -- FAILED.
3>   Creating library bin\TestLibraryd.lib and object bin\TestLibraryd.exp
3>TestLibrary_vs150.vcxproj -> C:\dev\poco\poco-develop\Foundation\testsuite\bin\TestLibraryd.dll
========== Build: 2 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by shamusn** [comment]
Taking a step back, I want to state our objective.
We are currently using POCO version 1.7.8.3 built with VS 2013 to get the following libraries
        .\POCO.FOUNDATION.V120.1.7.8.3\LIB\POCOFOUNDATIONMDD.LIB
        .\POCO.CRYPTO.V120.1.7.8.3\LIB\POCOCRYPTOMDD.LIB
.
I am looking to generate the equivalent using version 2.0.0 and build with VS 2017.
What is the easiest way to achieve this?
thanks

**Comment by zosrothko** [comment]
@shamusn Hold on some times. " cannot open file 'PocoCppUnitd.lib'" is an issue being fixed soon.

**Comment by shamusn** [comment]
After looking closer at the intent of buildwin.cmd, I manually typed the devenv command are arguments:
devenv Foundation_vs150.sln /build "debug_static_md|Win32" /useenv /Project Foundation_vs150.vcxproj

This produced the desired lib file.
![image](https://user-images.githubusercontent.com/40246237/46826832-025f6f80-cd65-11e8-9f30-b532bd9e1530.png)

**Comment by shamusn** [comment]
I tried https://github.com/pocoproject/openssl but some of the sites are blocked on my side.  Going to try and download zip from https://github.com/openssl/openssl.  Signing off for the day.

**Comment by zosrothko** [comment]
You should update the git submodule used by Poco with the command below:
`git submodule udpate --init --recursive --remote openssl`

**Comment by zosrothko** [comment]
Fixed by the latest commit @develop

**Comment by shamusn** [comment]
thanks... I have to switch to something else for a few days.  I will try this next week and let you know how we get on.

**Comment by shamusneville** [comment]
thanks for the help.  can you please explain where I am supposed to run the git submodule command from.  I tried running from git bash /c/dev/git/poco and /c/dev/git/poco/openssl and I get a usage dialog box.
![image](https://user-images.githubusercontent.com/32251203/47468335-b5e64c00-d7c8-11e8-841b-958e74730a2c.png)

**Comment by shamusneville** [comment]
Looking at gettingStarted page openSSL section, I am running the following:
  $ cd %POCO_BASE%
  $ rmdir /s /q openssl
  $ git clone https://github.com/pocoproject/openssl
  PS C:\dev\git\poco\openssl> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
.\build.ps1 -openssl_release 1.1.0 -vs_version 150 -config release -platform Win32 -library static

packages are downloading and extracting.  will continue another time.

**Comment by shamusneville** [comment]
![image](https://user-images.githubusercontent.com/32251203/47469218-be8d5100-d7cd-11e8-92f0-39c8fe17bca4.png)
![image](https://user-images.githubusercontent.com/32251203/47469306-4bd0a580-d7ce-11e8-8e00-3b391cf691db.png)
![image](https://user-images.githubusercontent.com/32251203/47469326-5db24880-d7ce-11e8-8fee-445520ec1858.png)
![image](https://user-images.githubusercontent.com/32251203/47469343-728edc00-d7ce-11e8-9b11-6bd7dc2807f7.png)

If I use the x86 Native Tools Command Prompt for VS 2017, nmake path is set.  Will the build.ps1 work in VS command prompt?  The Getting Started page suggested using a clean cmd window. 'i.e. not in the one provided by Visual Studio for 32/64-bit
builds '.
