### ISSUE TITLE
VS2017-Poco-1.9.0-x64.msi

### ISSUE THREAD

**Issue by bambuo** [pocoproject/poco#2502]
#### Expected behavior
.h .lib .dll It should all exist
#### Actual behavior
There is no .h files
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.9.0
#### Compiler and version
MSVC1.58
#### Operating system and version
Windows10 X64
#### Other relevant information
How does this library work without an. H file?

**Comment by zosrothko** [comment]
@420116199208022715 : This MSI delivery was in error and I forget to remove from the release panel. Could you consider to use the Nuget equivalent package found [here](https://bintray.com/pocoproject/nuget)

**Comment by 420116199208022715** [comment]
> @ 420116199208022715：此MSI传送出错，我忘记从发布面板中删除。你能考虑使用[这里](https://bintray.com/pocoproject/nuget)找到的Nuget等效包吗？[](https://bintray.com/pocoproject/nuget)

No valid packages

**Comment by zosrothko** [comment]
What do you mean? I am using it without any problem? Can you translate in English?

**Comment by 420116199208022715** [comment]
> What do you mean? I am using it without any problem? Can you translate in English?

Sorry, the reply language is not uniform when using automatic translation of web pages. I checked which link you gave didn't find a useful download package.

**Comment by zosrothko** [comment]
[https://bintray.com/pocoproject/nuget/Pocoproject.Poco.vs150.x64](https://bintray.com/pocoproject/nuget/Pocoproject.Poco.vs150.x64)
[https://bintray.com/pocoproject/nuget/Pocoproject.Poco.vs150.x86](https://bintray.com/pocoproject/nuget/Pocoproject.Poco.vs150.x86)
