### ISSUE TITLE
Which branch support C++11?

### ISSUE THREAD

**Issue by mrunix** [pocoproject/poco#2507]
Where I can get C++11 supported codes? Thank you very much.

**Comment by zosrothko** [comment]
The branch `develop`at https://github.com/pocoproject/poco

**Comment by mrunix** [comment]
> The branch `develop`at https://github.com/pocoproject/poco

Thank you!

**Comment by Bjoe** [comment]
Also poco-1.9.1 ... at least in the cmake build if the compiler supports C++11 ... you will see this in the cmake output.
