### ISSUE TITLE
Negative precision in NumberFormatter::format()

### ISSUE THREAD

**Issue by mkrivos** [pocoproject/poco#2511]
#### Expected behavior
return string "0.00576283006"

#### Actual behavior
Assertion in debug mode

Thread #1 [testunit2] 2716 [core: 2] (Suspended : Signal : SIGABRT:Aborted)	
	raise() at 0x7ffff4f2ad7f	
	abort() at 0x7ffff4f15672	
	__assert_fail_base.cold.0() at 0x7ffff4f15548	
	__assert_fail() at 0x7ffff4f23396	
	poco_double_conversion::DoubleToStringConverter::DoubleToAscii() at double-conversion.cc:366 0x7ffff5688f31	
	poco_double_conversion::DoubleToStringConverter::ToFixed() at double-conversion.cc:220 0x7ffff5688827	
	Poco::doubleToFixedStr() at NumericString.cpp:286 0x7ffff568b6d9	
	Poco::doubleToFixedStr[abi:cxx11]() at NumericString.cpp:354 0x7ffff568bd0a	
	Poco::NumberFormatter::format[abi:cxx11]() at NumberFormatter.h:625 0x555555d7c03b	
	GeometryUtilityTest_DoubleToStringTest_Test::TestBody() at GeometryUtilityTest.cpp:28 

#### Steps to reproduce the problem

    double badNumber = 0.0057628300599999998;
    Poco::NumberFormatter::format(badNumber, -1);

#### POCO version
latest develop branch

#### Compiler and version
gcc 8.2.1

#### Operating system and version
Linux, 4.18

**Comment by aleks-f** [comment]
a negative precision is obviously allowed, but I wouldn't call it valid
