### ISSUE TITLE
SecureSocketImpl isLocalHost check for isLoopback

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2520]
When checking certificate with verifyPeerCertificateImpl the function isLocalHost is used to check for local address and not STRICT verification. The isLocalHost use IPAddress::isLoopback() and not isSiteLocal, is that correct?

**Comment by aleks-f** [comment]
This just states some facts ad then asks if they are correct, which is obvious from the code. 
What exactly is the issue here?

**Comment by micheleselea** [comment]
mmm...I really do not remember...was 2018...let's close it
