### ISSUE TITLE
Poco+OpenSSL certificate verify failed no openssl error code returned

### ISSUE THREAD

**Issue by p-neels** [pocoproject/poco#2528]
#### Expected behavior
When SSL_conenct to an endpoint fails the below exception is thrown.
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

The exact openssl  error code due to which verify failed is not returned to the caller.
There are multiple failure codes as mentioned in below link which caller would be interested in.
https://www.openssl.org/docs/man1.0.2/apps/verify.html

Is there any other recommended approach here?

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.9.0

**Comment by aleks-f** [comment]
there will be `getError()` utility function in 1.12 but not yet applied to every case in the libraries:
https://github.com/pocoproject/poco/commit/45c456653f19633c9bdcc4da14a0a02cc99320b4#diff-954814fea8964f60476eda8865526bdcad90483e3aba5f5c1e55974ace4eb0baR177
