### ISSUE TITLE
When I cross compile poco for QNX, ODBC report error

### ISSUE THREAD

**Issue by darbee** [pocoproject/poco#2536]
I cross compile for QNX using command 
`./configure  --config=QNX --omit=NetSSL_OpenSSL,Crypto,Data/ODBC,Data/MySQL`
 And it return 
`Configured for QNX`
indicating no error when I passing parameter to configure.

And --omit means I **do not**  build this modules including **ODBC** 

But after I executing  make command, It report error:
`make[1]: Leaving directory '/home/dabin/Documents/poco/SQL'
make -C /home/dabin/Documents/poco/SQL/ODBC
make[1]: Entering directory '/home/dabin/Documents/poco/SQL/ODBC'
ODBC.make:63: *** No ODBC library found. Please install unixODBC or iODBC or specify POCO_ODBC_LIB or set the correct libodbc library path by using --odbc-lib as option to 'configure' script and try again.  Stop.
make[1]: Leaving directory '/home/dabin/Documents/poco/SQL/ODBC'
Makefile:274: recipe for target 'SQL/ODBC-libexec' failed
make: *** [SQL/ODBC-libexec] Error 2`

Are there any mistakes in my procedures?

Thanks you all.

**Comment by aleks-f** [comment]
apparently, you are compiling develop branch, where Data was moved to SQL, so you should adjust the configure command accordingly
