### ISSUE TITLE
Start thread with throw NullPointerException

### ISSUE THREAD

**Issue by wherewindblow** [pocoproject/poco#2537]
#### Expected behavior
Can start a thread and without hold it.

#### Actual behavior
When I start my program in normal mode will throw NullPointerException in new thread, but it's infrequence when start program via gdb. I start thread in the following way.
```c++
void WorkScheduler::start()
{
    using namespace details;
    auto scheduler = SchedulerImpl::instance();
    if (scheduler->run_state == SchedulerImpl::STOPED)
    {
        scheduler->run_state = SchedulerImpl::STARTING;
        Poco::Thread thread;
        thread.start(*scheduler);
    } // Destroy thread.
    else if (scheduler->run_state == SchedulerImpl::STARTED)
    {
        LIGHTS_ASSERT(false && "scheduler already started");
    }
}
```
And the follwing is the code that throw exception.
```c++
void* ThreadImpl::runnableEntry(void* pThread)
{
    ...
    ThreadImpl* pThreadImpl = reinterpret_cast<ThreadImpl*>(pThread);
    AutoPtr<ThreadData> pData = pThreadImpl->_pData;  // Get thread data.
    try
    {
        pData->pRunnableTarget->run();
    }
    catch (Exception& exc)
    {
        ErrorHandler::handle(exc);
    }
    catch (std::exception& exc)
    {
        ErrorHandler::handle(exc);
    }
    catch (...)
    {
        ErrorHandler::handle();
    }
    pData->pRunnableTarget = 0; // Throw NullPointerException in here.
    pData->done.set();
    return 0;
}
```
Throw `NullPointerException` means pData not owning thread data and get thread data failure.
After start thead will encounter right brace and destroy thread. `pThread` in `runnableEntry` is this thread object and now any operation of `pThread` is undefined behavior. Why not just pass `pThreadImpl->_pData ` into `runnableEntry`?
To avoid this problem just need to keep thread object is available when thread is running.
```c++
void WorkScheduler::start()
{
    using namespace details;
    auto scheduler = SchedulerImpl::instance();
    if (scheduler->run_state == SchedulerImpl::STOPED)
    {
        scheduler->run_state = SchedulerImpl::STARTING;
        static Poco::Thread thread; // Make is as static.
        thread.start(*scheduler);
    }
    else if (scheduler->run_state == SchedulerImpl::STARTED)
    {
        LIGHTS_ASSERT(false && "scheduler already started");
    }
}
```

In the newest version, there may have some different, but it also pass `ThreadImpl` into `runnableEntry`.

#### POCO version
1.8.0.1

**Comment by obiltschnig** [comment]
You are creating a `Poco::Thread` in a local scope. The thread object will be deleted immediately after calling `start()`, at the end of the `if` block. Whether the thread will actually start before its `Poco::Thread` object is deleted, or whether the thread is still alive or already destroyed when accessed is nondeterministic.

**Comment by aleks-f** [comment]
At the time when runnableEntry() accesses thread local data, thread must still exist, but your code has no guarantee for that; thread will be [detached](https://github.com/pocoproject/poco/blob/poco-1.9.1/Foundation/src/Thread_POSIX.cpp#L97) if it **was started** and **wasn't joined** at destruction time.
