### ISSUE TITLE
Poco::Data::Session::connector() returns empty string for MySQL session.

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#2538]
#### Expected behavior

Poco::Data::Session::connector() return "MySQL" for MySQL session.

#### Actual behavior

Poco::Data::Session::connector() returns empty string for MySQL session.

#### POCO version

all

**Comment by sildeag** [comment]
Wouldn't this be `Poco::SQL::Session::connector()`,  I thought `Poco::Data` was replaced by `Poco::SQL` in the git version.

**Comment by obiltschnig** [comment]
For the develop branch it's Poco::SQL, for the 1.9.1 branch it's still Poco::Data.
