### ISSUE TITLE
Sending a Websocket ping is not accepted by Chrome or Firefox

### ISSUE THREAD

**Issue by ALTinners** [pocoproject/poco#2541]
#### Expected behavior
Sending out Websocket Pings with no payload or a defined payload appears to give out an invalid op code. Chrome's frame inspector shows ` (Opcode -1)` for the bad frame in question. This may be my bad usage of the API in POCO but doing a very similar response for a Ping doesn't cause issues. Wireshark recognises the correct opcode in the packets.

#### Actual behavior
A WS ping should be able to be sent with any or no payload as per [specs](https://tools.ietf.org/html/rfc6455#section-5.5.2)

#### Steps to reproduce the problem
https://github.com/ALTinners/poco-ping-example contains a reproducable example.  

From a standard install on 1.90 on Ubuntu 16.04 this compiles and runs using `cmake . ; make; ./POCO_TEST`

#### POCO version
1.9.0

#### Compiler and version
gcc version 5.4.0 20160609 

#### Operating system and version
Ubuntu 16.04 

#### Other relevant information
See line 251 in main.cpp for the ping attempts. Both are recognized as pings via Wireshark.

**Comment by obiltschnig** [comment]
When you send a PING frame, you have to send it with `WebSocket::FRAME_OP_PING | WebSocket::FRAME_FLAG_FIN`, otherwise (without `FRAME_FLAG_FIN`) the browser expects a multi-fragment message, which is not valid for a PING.
Example:
```
ws.sendFrame(buffer, 0, WebSocket::FRAME_OP_PING | WebSocket::FRAME_FLAG_FIN);
````
