### ISSUE TITLE
MySQL session state is not cleared in SessionPool

### ISSUE THREAD

**Issue by Erbengi** [pocoproject/poco#2546]
#### Expected behavior
Session returned by `SessionPool::get()` isn't affected by it's previous usage (only MySQL).

#### Actual behavior
Session returned by `SessionPool::get()` has state from it's previous usage (only MySQL).

#### Steps to reproduce the problem
It is quite difficult to simulate it. Lets say we have 2 sessions in `SessionPool`: *session1* and *session2*.

Get *session1* by call `SessionPool::get()` and use it to insert some data to table:
```sql
INSERT INTO my_table ("test");
```
Get *session2* from session pool and use it to remove row from table:
```sql
DELETE FROM my_table WHERE column="test";
```
Get *session1* from session pool and try to find deleted data:
```sql
SELECT column FROM my_table WHERE column="test"
```
The statement found the row which was deleted with *session2*

#### POCO version
1.9.0

#### Compiler and version
gcc 7.3.0

#### Operating system and version
Ubuntu 18.04, Ubuntu 16.04

#### Other relevant information
This issue can be fixed by using [mysql_reset_connection()](https://dev.mysql.com/doc/refman/5.7/en/mysql-reset-connection.html) when `Session` is returned to the `SessionPool`.

**Comment by aleks-f** [comment]
@Erbengi not that fixing it in develop does not fix it for 1.x series of releases. for those, you should send pull to poco-1.9.1

**Comment by Erbengi** [comment]
I already did, see #2547
