### ISSUE TITLE
Assertion violation: !_path.empty() in file file_win32u.cpp, line 94

### ISSUE THREAD

**Issue by tuhdo** [pocoproject/poco#2551]
#### Expected behavior
The program with POCO built-in (static) should run normally like in other machines. 

#### Actual behavior
Here, I got this weird error as in the title.

#### Steps to reproduce the problem
Use Poco::File library. When I run the binary on a freshly installed Windows 7 VM, the same error occured, but on some other machines (real laptops), it did not. Maybe something is missing?

#### POCO version
1.9.0

#### Compiler and version
MSVC 2017

#### Operating system and version
Windows 10 1803

I guess some DLL is missing on my Windows?

**Comment by soumyaranjanbej** [comment]
I see the similar issue. Is it resolved ?
