### ISSUE TITLE
Poco::MongoDB test cases failed in Linux on IBM z

### ISSUE THREAD

**Issue by liming** [pocoproject/poco#2552]
#### Expected behavior

Able to pass following test cases:
`./MongoDB/testsuite/bin/Linux/s390x/testrunner -all`

#### Actual behavior

All test cases failed with:
`IOException("Failed to read from socket");`

#### Steps to reproduce the problem

1. Find a Linux on IBM z with s390 or s390x architecture
2. Install and start MongoDB
3. Build Poco library
4. Run Poco::MongoDB test cases

`
./MongoDB/testsuite/bin/Linux/s390x/testrunner -all
`

#### POCO version

1.8.0.1

#### MongoDB version

3.0 and above

#### Compiler and version

`
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
`
#### Operating system and version

Linux on IBM z with s390 or s390x architecture

#### Other relevant information

The problem is because MongoDB wire protocol message and BSON document both need serialized in little-endian format. But Poco::MongoDB not define little-endian format on all the BinaryWriter.

**Comment by liming** [comment]
This issue affect all the system with big-endian architecture. I have raised a PR.

**Comment by obiltschnig** [comment]
backported to 1.9.1
