### ISSUE TITLE
socketreactor  Bug

### ISSUE THREAD

**Issue by ghost** [pocoproject/poco#2554]
removEventhandler   only delete  observer ,  not  delete  event from  pollset  when observer  >1.
It  cause some   poll event still in  pollset  .

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/c4e676d36dabb76d567477a2a23528efdb186785#diff-6e6cfaa4dff1ef8d06979aadef21ebaa555d055a9254133e75e0cd1a093427a5R203
