### ISSUE TITLE
How to build an application using static Poco and static OpenSSL in Linux?

### ISSUE THREAD

**Issue by Diversus23** [pocoproject/poco#2556]
#### Expected behavior
How to build an application that uses OpenSSL and static Poco on Linux? The application is compiled, but I get errors:

> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoXML.a(XMLWriter.cpp.o): In function `Poco::XML::XMLWriter::XMLWriter(std::ostream&, int)':
> /media/sf_Projects/SLS/poco/XML/src/XMLWriter.cpp:77: undefined reference to `Poco::OutputStreamConverter::OutputStreamConverter(std::ostream&, Poco::TextEncoding const&, Poco::TextEncoding const&, int)'
> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoXML.a(XMLWriter.cpp.o): In function `Poco::XML::XMLWriter::XMLWriter(std::ostream&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::TextEncoding&)':
> /media/sf_Projects/SLS/poco/XML/src/XMLWriter.cpp:100: undefined reference to `Poco::OutputStreamConverter::OutputStreamConverter(std::ostream&, Poco::TextEncoding const&, Poco::TextEncoding const&, int)'
> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoXML.a(XMLWriter.cpp.o): In function `Poco::XML::XMLWriter::XMLWriter(std::ostream&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::TextEncoding*)':
> /media/sf_Projects/SLS/poco/XML/src/XMLWriter.cpp:125: undefined reference to `Poco::OutputStreamConverter::OutputStreamConverter(std::ostream&, Poco::TextEncoding const&, Poco::TextEncoding const&, int)'
> /media/sf_Projects/SLS/poco/XML/src/XMLWriter.cpp:131: undefined reference to `Poco::OutputStreamConverter::OutputStreamConverter(std::ostream&, Poco::TextEncoding const&, Poco::TextEncoding const&, int)'
> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoZip.a(ZipStream.cpp.o): In function `Poco::Zip::ZipStreamBuf::~ZipStreamBuf()':
> /media/sf_Projects/SLS/poco/Zip/src/ZipStream.cpp:144: undefined reference to `Poco::Checksum::~Checksum()'
> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoZip.a(ZipStream.cpp.o): In function `Poco::Zip::ZipStreamBuf::ZipStreamBuf(std::istream&, Poco::Zip::ZipLocalFileHeader const&, bool)':
> /media/sf_Projects/SLS/poco/Zip/src/ZipStream.cpp:47: undefined reference to `Poco::Checksum::Checksum(Poco::Checksum::Type)'
> /media/sf_Projects/SLS/poco/Zip/src/ZipStream.cpp:70: undefined reference to `Poco::InflatingInputStream::InflatingInputStream(std::istream&, Poco::InflatingStreamBuf::StreamType)'
> /media/sf_Projects/SLS/poco/Zip/src/ZipStream.cpp:47: undefined reference to `Poco::Checksum::~Checksum()'
> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoZip.a(ZipStream.cpp.o): In function `std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<std::istream*>(std::istream*)':
> /usr/include/c++/5/bits/shared_ptr_base.h:578: undefined reference to `Poco::InflatingInputStream::~InflatingInputStream()'
> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoZip.a(ZipStream.cpp.o): In function `Poco::Zip::ZipStreamBuf::ZipStreamBuf(std::ostream&, Poco::Zip::ZipLocalFileHeader&, bool)':
> /media/sf_Projects/SLS/poco/Zip/src/ZipStream.cpp:99: undefined reference to `Poco::Checksum::Checksum(Poco::Checksum::Type)'
> /media/sf_Projects/SLS/poco/Zip/src/ZipStream.cpp:99: undefined reference to `Poco::Checksum::~Checksum()'
> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoCrypto.a(Cipher.cpp.o): In function `Poco::Crypto::Cipher::encrypt(std::istream&, std::ostream&, Poco::Crypto::Cipher::Encoding)':
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:89: undefined reference to `Poco::HexBinaryEncoder::HexBinaryEncoder(std::ostream&)'
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:95: undefined reference to `Poco::HexBinaryEncoderIOS::close()'
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:89: undefined reference to `Poco::HexBinaryEncoder::~HexBinaryEncoder()'
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:92: undefined reference to `Poco::HexBinaryEncoderIOS::rdbuf()'
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:92: undefined reference to `Poco::HexBinaryEncoderBuf::setLineLength(int)'
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:89: undefined reference to `Poco::HexBinaryEncoder::~HexBinaryEncoder()'
> /media/sf_Projects/SLS/SoftonitLicenceServer/src/../../../Poco/lib/linux/x32/libPocoCrypto.a(Cipher.cpp.o): In function `Poco::Crypto::Cipher::decrypt(std::istream&, std::ostream&, Poco::Crypto::Cipher::Encoding)':
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:128: undefined reference to `Poco::HexBinaryDecoder::HexBinaryDecoder(std::istream&)'
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:128: undefined reference to `Poco::HexBinaryDecoder::~HexBinaryDecoder()'
> /media/sf_Projects/SLS/poco/Crypto/src/Cipher.cpp:128: undefined reference to `Poco::HexBinaryDecoder::~HexBinaryDecoder()'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
> (.text+0xa): undefined reference to `dlopen'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
> (.text+0x20): undefined reference to `dlsym'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
> (.text+0x2a): undefined reference to `dlclose'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
> (.text+0x32d): undefined reference to `dlsym'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
> (.text+0x3ad): undefined reference to `dlerror'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
> (.text+0x42d): undefined reference to `dlsym'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
> (.text+0x4ad): undefined reference to `dlerror'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
> (.text+0x518): undefined reference to `dlopen'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
> (.text+0x575): undefined reference to `dlclose'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
> (.text+0x5ae): undefined reference to `dlerror'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
> (.text+0x641): undefined reference to `dladdr'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
> (.text+0x6a1): undefined reference to `dlerror'
> /usr/lib/i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
> (.text+0x70b): undefined reference to `dlclose'

#### POCO version
Last from github
#### Compiler and version
GCC
#### Operating system and version
Ubuntu 16 x86
#### Other relevant information

**How to build an application using static Poco and static OpenSSL in Linux?**

**Comment by Bjoe** [comment]
In short: there is a missing library for the linker `-ldl` .....

Which build system you are using? CMake?

**Comment by Diversus23** [comment]
Yes CMake, and I'am compiling with 
```
if(CMAKE_COMPILER_IS_GNUCXX)
	message(STATUS "GCC detected, adding compile flags")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fPIC -pedantic -Wall -Wextra -O3 -pthread -ldl")
	set(CMAKE_CXX_FLAGS_RELEASE "-O3")
	set(BUILD_SHARED_LIBS OFF)
	#set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
else()
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
	set(CMAKE_GENERATOR_TOOLSET "v141_xp" CACHE STRING "CMAKE_GENERATOR_TOOLSET" FORCE)
	set(CMAKE_VS_PLATFORM_TOOLSET "v141_xp" CACHE STRING "CMAKE_VS_PLATFORM_TOOLSET" FORCE)	
	set(CMAKE_VERBOSE_MAKEFILE on)
	set(CMAKE_SYSTEM_VERSION 7.0 CACHE TYPE INTERNAL FORCE)
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")	
endif(CMAKE_COMPILER_IS_GNUCXX)
```
with -ldl

**Comment by Bjoe** [comment]
First some cmake hints:

For `-std=c++11` you should use maybe [target_compile_features](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html) or with [CMAKE_CXX_STANDARD](http://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html) like
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

For `-fPIC` you should use [CMAKE_POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html) like
```
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```

Than your compiler settings is independent from the compiler :-)

You sould not set `-O3` on `CMAKE_CXX_FLAGS` because, when you build a debug version, you will not have `-O3` :-). Remove `-O3` and set `CMAKE_BUIDL_TYPE` when you execute `cmake` like: `cmake -DCMAKE_BUILD_TYPE=Release ...` or `cmake -DCMAKE_BUILD_TYPE=Debug ...`
With `Release` build type, cmake is set `-O3 -DNDEBUG` as compile flag, in `Debug` cmake is set `-g` and for `RelWithDebInfo` they set `-O2 -g -DNDEBUG`

For `-pthread` you should use [find_package(Threads REQUIRED)](https://cmake.org/cmake/help/latest/module/FindThreads.html) and import this like:
```
target_link_libraries(your_target_name Threads::Threads)
```
This cmake module figured out if `-pthread` is needed or not. On some linux platforms, pthread is included in glibc and -pthread is not needed and give an error back.

For `set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")` you should set on [target_link_libraries(your_target_name -static)](https://cmake.org/cmake/help/latest/command/target_link_libraries.html)

For `-ldl` you should also set this on [target_link_libraries(your_target_name dl)](https://cmake.org/cmake/help/latest/command/target_link_libraries.html) but it should be set when you import poco targets in cmake.
I don't know how you import poco into cmake build, but it should be like:
```
...
find_package(Poco REQUIRED Zip Net)
...
target_link_libraries(your_target_name Poco::Net Poco::Zip)
...
```
So how you are include Poco into cmake ? And wich latest branch you are using? `develop`? `poco-1.9.1`?
Can you send an verbose linker output from the error please.

Btw. you can enable vebose compile output:
For make based build
```
cmake --build <your_build_directory> -- VERBOSE=1
```
For ninja based build
```
cmake --build <your_build_directory> -- -v
```
