### ISSUE TITLE
issue binding std::string, exception text

### ISSUE THREAD

**Issue by poco7** [pocoproject/poco#2557]
I seem to have an issue to bind std::string column. The following generates an exception
        prepareStmt << "cusip=?";
        prepareStmt.bind(std::string("3130A8DB6"));

Binding an integer column works fine
        prepareStmt << "pstatus=?";
        prepareStmt.bind(1);

Another issue - the exception that comes upon any error (like in this case, or in case of SELECT of non-existing column etc.) looks like
"ODBC handle exception"
which is not very helpful to debug issues ...

#### POCO version
1.9.0 ODBC for Microsoft SQL Server

#### Compiler and version
gcc 5.3.1

#### Operating system and version
Linux RedHat 5.3.1

**Comment by aleks-f** [comment]
binding a temporary, see [Things NOT To Do](https://docs.pocoproject.org/current/00200-DataUserManual.html)
