### ISSUE TITLE
What happens with joinAll when there are two taskmamagers and two threadpools

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#2558]
#### POCO version
1.7.8.p2
#### Compiler and version
gcc 5.4.0
#### Operating system and versioN
Ubuntu 16.04 amd64
#### Other relevant information
Since it's difficult to reproduce the case I just need the following clarification:
In case there are two Taskmanagers and two different Threadpools one for each manager in the code then method joinall() applies to each Taskamanager's threads  or applies to every open thread regardless of pool and manager ?
e.x. you have the following:

```
ThreadPool  tp1("Pool1");
TaskManager tm1(tp);

ThreadPool  tp2("Pool2");
TaskManager tm2(tp);

tm1.joinAll(); -> this waits only the threads in Pool1?

tm2.joinAll(); -> this waits only the threads in Pool2?
```

Thanks in advance

**Comment by aleks-f** [comment]
yes
