### ISSUE TITLE
SSL Server&Client examples?

### ISSUE THREAD

**Issue by CingKong** [pocoproject/poco#2560]

**Comment by Bjoe** [comment]
Network overview:
* https://pocoproject.org/slides/200-Network.pdf

HTTPS Server example:
* https://github.com/pocoproject/poco/blob/develop/NetSSL_OpenSSL/samples/HTTPSTimeServer/src/HTTPSTimeServer.cpp

HTTPS Client example:
* https://github.com/pocoproject/poco/blob/develop/NetSSL_OpenSSL/samples/download/src/download.cpp

And look in the testsuite, there are a lot of nice "usage examples" :-)
* https://github.com/pocoproject/poco/tree/develop/NetSSL_OpenSSL/testsuite/src

And I recommend also the API documentation:
* https://pocoproject.org
* https://pocoproject.org/documentation.html
* https://pocoproject.org/documentation.html#slides
* https://pocoproject.org/docs/

**Comment by CingKong** [comment]
😂 I tried to followed the testsuite, but the line of code below threw exception already. 
`SecureServerSocket svs(0);`
and the exception says "Illegal state"

**Comment by CingKong** [comment]
Ok i happened to make it work.

```
class EchoConnection: public TCPServerConnection
{
public:
    EchoConnection(const StreamSocket& s): TCPServerConnection(s){}

    void run()
    {
        StreamSocket& ss = socket();
        try
        {
            char buffer[256];
            int n = ss.receiveBytes(buffer, sizeof(buffer));
            ss.sendBytes(buffer, n);
            while (n > 0)
            {
                ss.sendBytes(buffer, n);
                n = ss.receiveBytes(buffer, sizeof(buffer));
            }
        }
        catch (Poco::Exception& exc)
        {
            std::cerr << "EchoConnection: " << exc.displayText() << std::endl;
        }
    }
};

int main(int argc, char *argv[])
{
    Context::Ptr ptrContext = new Context(Context::SERVER_USE, "key.pem", "certificate.pem", "rootcert.pem", Context::VERIFY_RELAXED, 9, false, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
    SSLManager::instance().initializeServer(0, 0, ptrContext);
    Context::Ptr ptrContext2 = new Context(Context::CLIENT_USE, "", "", "rootcert.pem", Context::VERIFY_RELAXED, 9, false, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
    SharedPtr<InvalidCertificateHandler> ptrCert2 = new AcceptCertificateHandler(false);
    SSLManager::instance().initializeClient(0, ptrCert2, ptrContext2);

    SecureServerSocket svs(0);
    TCPServer srv(new TCPServerConnectionFactoryImpl<EchoConnection>(), svs);
    srv.start();

    SocketAddress sa("127.0.0.1", srv.socket().address().port());
    SecureStreamSocket ss1(sa);
    std::string data("hello, world");
    ss1.sendBytes(data.data(), (int) data.size());
    char buffer[256];
    memset(buffer, '\0', 256);
    ss1.receiveBytes(buffer, sizeof(buffer));
    std::cout << buffer << std::endl;
    ss1.close();
}
```

now i got a new question
the EchoConnection object goes destructed right after  `EchoConnection::run()`
whats the "correct" way to keep the connection if i needed it for further usage?
putting it in deadloop does not look good

**Comment by Spixmaster** [comment]
I had the error  "Illegal state" too. Thank you for the code. It works now!
