### ISSUE TITLE
POCO logger initialization question

### ISSUE THREAD

**Issue by DerkachAlex** [pocoproject/poco#2561]
Hi there!
I'm using POCO logger implementation.
I can initialize it when I pass a path to the separate config file with a necessary options to PropertyFileConfiguration constructor. 
File content like this:

```
logging.loggers.root.level = debug
logging.loggers.root.channel.channel = defaultFileChannel
logging.channels.defaultFileChannel.class = FileChannel
..etc.
```

But I also have a one more config file - for my main application. 
And I want to 'merge' these files together in the one config file, like this
```
[dbInfo]
...any db info
[something else]
...
[logger]
logging.loggers.root.level = debug
logging.loggers.root.channel.channel = defaultFileChannel
logging.channels.defaultFileChannel.class = FileChannel
..etc.
```

**Question:**
Would it be correct to pass this file to PropertyFileConfiguration constructor as I did before with a separate logger config file 
or should I iterate the whole [logger] lines and set those properties manually ?

My current C++ code is:
 
```
 void initializeLogging(std::string const& loggingConfPath)
 {
  using namespace Poco::Util;
 
  Poco::AutoPtr<PropertyFileConfiguration> pConfig = new PropertyFileConfiguration(loggingConfPath);
  Poco::AutoPtr<SystemConfiguration> systemConfiguration = new SystemConfiguration;
  Poco::AutoPtr<ConfigurationView> defaultConfiguration = new ConfigurationView("default", pConfig);
 
  Poco::AutoPtr<LayeredConfiguration> layeredConfiguration = new LayeredConfiguration;
 
  layeredConfiguration->add(pConfig);
  layeredConfiguration->add(systemConfiguration);
  layeredConfiguration->add(defaultConfiguration);
 
  LoggingConfigurator configurator;
  configurator.configure(layeredConfiguration);
 }
```

**Comment by obiltschnig** [comment]
You can merge both together using the `LayeredConfiguration`, as you did. However, unless you specify a priority value with `add()`, configurations added later will have precedence over those added earlier. So if you have more than one `logging.loggers.root.level`, only the one in the last configuration added will count.

You are also adding a `ConfigurationView` for `default` on the same config file. Not sure what you'd like to achieve with this.

Regarding your usage of INI-File-style section headers (`[logger]`), you could also use a `Poco::Util::IniFileConfiguration`, with a`ConfigurationView` for the `logger` section.

**Comment by DerkachAlex** [comment]
Thanks for response and explanations. It works correctly!

```
  Poco::AutoPtr<IniFileConfiguration> iniConfiguration(new IniFileConfiguration(loggingConfPath));
  Poco::AutoPtr<ConfigurationView> pConfig(new ConfigurationView("logger", iniConfiguration));
```
