### ISSUE TITLE
Calls the previous dialled number when the last number didn't connect and user is still on the contacts screen

### ISSUE THREAD

**Issue by SonalSmriti** [pocoproject/poco#2567]
#### Expected behavior
If the last called number didn't connect due to some issues with network at caller or called party side and user is still on the Call screen, the phone dials the previous called number

#### Actual behavior
If the last called number didn't connect due to some issues with network at caller or called party side and user is still on the Call screen, the phone SHOULD NOT dial any previous called numbers

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
1.Try to call a number from your POCO phone
2.Call doesn't connect due to network issue at your side or the called person's side
3.Screen should show the number as Didn't connect
4.Be on the call screen only dont navigate to any other screen and observe the behavior in few seconds

#### POCO version
details in the snapshot attached

**Comment by obiltschnig** [comment]
Wrong project
