### ISSUE TITLE
poco support android arm64

### ISSUE THREAD

**Issue by daijinguo** [pocoproject/poco#2577]
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### Operating system and version
android arm64 support

**Comment by Bjoe** [comment]
Hi, I'm already building and testing `poco-1.9.1` and `develop` branch for `arm64-v8a` all the day but I didn't get in any trouble. 
Can you please give some more information about your trouble?
