### ISSUE TITLE
vcpkg build does not include Poco/Data/ODBC

### ISSUE THREAD

**Issue by faburaya** [pocoproject/poco#2580]
#### Expected behavior
When building poco via vcpkg, the component Poco/Data/ODBC should be built.

#### Actual behavior
vcpkg does not build Poco/Data/ODBC and there is no message about that.

#### Steps to reproduce the problem
Just run "vcpkg install poco".

#### POCO version
1.9.0

#### Compiler and version
g++ 7.3

#### Operating system and version
Ubuntu 18.04 x64

#### Other relevant information
My system did not have previously installed any ODBC lib.

**Comment by zosrothko** [comment]
The pocoproject team is not involved in such packaging tool. You should adress your issue to this [repo](https://github.com/Microsoft/vcpkg)
