### ISSUE TITLE
Deadlock with notification posted from notification handler

### ISSUE THREAD

**Issue by guitarflow** [pocoproject/poco#2581]
Sorry this is more of a question than a real issue.

I'm using Poco as part of a C++ app and I've run into an issue I don't quite understand. The app was translated from Obj-C and made heavy use of Apple's NSNotificationCenter.

To make the transition as painless as possible, I decided to use Poco's NotificationCenter instead. It works fine but I had some users reporting deadlocks I'm now trying to resolve.

Given the fact that NotificationCenter's postNotification method always iterates over all observers (AFTER locking one and before checking if the type of the notification matches using a dynamic typecast), I'm assuming that posting a notification from a notification handler MUST always cause a deadlock as it would also try to access the observer where itself is called from and will wait forever on the lock in NObserver::notify()? 

From the process samples my users sent me it looks like my assumption is correct.

But for some reason this doesn't appear to happen in most cases (I never experienced it ever myself). I just stepped through with the debugger and couldn't make it lock up. Can anyone help me understand, please?

Thanks very much!

**Comment by wtiandong** [comment]
Hi guitarflow,
Here is the postNotification method (Foundation/NotificationCenter.cpp):
```C++
void NotificationCenter::postNotification(Notification::Ptr pNotification)
{
	poco_check_ptr (pNotification);

	ScopedLockWithUnlock<Mutex> lock(_mutex);
	ObserverList observersToNotify(_observers);
	lock.unlock();
	for (ObserverList::iterator it = observersToNotify.begin(); it != observersToNotify.end(); ++it)
	{
		(*it)->notify(pNotification);
	}
}
```

You can see that notification center gets observer list with lock protected, and then releases lock before iterator observers. So it will not cause deadlock even if you post another notification in notification handler.

**Comment by guitarflow** [comment]
Hmm, ok. I just made a demo project and can't reproduce the deadlock there as well. 
I thought that the lock within the notify() function would be locking but it looks like it doesn't as the observers are copied (I guess as a shallow copy).

Can you think of a scenario where this could be causing a deadlock?

Thanks a lot in advance!

**Comment by arsu-leo** [comment]
Hello,
I experienced a lookalike problem. The issue happens when you have 2 different threads that notify stuff and you are using NObserver.
Here is the notify method (Foundation/include/Poco/NObserver.h) from
https://github.com/pocoproject/poco/blob/master/Foundation/include/Poco/NObserver.h#L76
```
void notify(Notification* pNf) const
	{
		Poco::Mutex::ScopedLock lock(_mutex);

		if (_pObject)
		{
			N* pCastNf = dynamic_cast<N*>(pNf);
			if (pCastNf)
			{
				NotificationPtr ptr(pCastNf, true);
				(_pObject->*_method)(ptr);
			}
		}
	}
```
The NObserver locks on thread level before even trying to cast, which means that the order of your observers may have side effects.

Example where this issue is produced
Given the following observer list:
- ObserverA\<NotificationTypeA>
- ObserverB\<NotificationTypeB>
- ObserverC\<NotificationTypeC>

Let's asume **NotificationTypeC** is used by different components to just emit a message to some kind of logging listener for instance, both **ObserverA** and **ObserverB** will raise a single **NotificationTypeC** as part of their work.

Thread timeline scenario:
- On a first thread **NotificationTypeB** is raised, **ObserverA** is locked,  the cast fails and unlocked, then **ObserverB** is locked and it starts a heavy load operation (Something that takes long).
- On a second thread **NotificationTypeA** is raised, **ObserverA** is locked and it starts a heavy load operation (Something that takes long).

When the first to raise **NotificationTypeC** is the first thread, the following will happen:
- First thread it will try lock the **ObserverA**, (It already locked by this thread itself so it's ok, it will go on), cast will fail and is going to notify for **ObserverB** which is locked by the second thread and it will wait here until the second thread releases **ObserverB** lock.
- Now the second thread raises a **NotificationTypeC**, it will try to lock **ObserverA**, **ObserverA** is locked by the first thread so the second thread will wait for the first thread to release this lock.
Currently both threads are waiting each other's locks thus creating a **deadlock**.

Not sure if is well explained, working example:
```
//============================================================================
// Name        : NotificationCenterDeadlock.cpp
// Author      : Leo
// Description : Working example of Poco NObserver deadlock on a multithread scenario where a notification chain exists (A->C, B->C)
//============================================================================

#include <iostream>
#include <Poco/NotificationCenter.h>
#include <Poco/AutoPtr.h>
#include <Poco/Notification.h>
#include <Poco/NObserver.h>
#include <Poco/Thread.h>

using namespace std;

class BaseNotification: public Poco::Notification
{
public:
	BaseNotification(std::string name) : Poco::Notification(), name(name)
	{}

	std::string getName() const
	{
		return this->name;
	}
private:
	std::string name;
};

class DomainEvent1: public BaseNotification
{
public:
	DomainEvent1(std::string name) : BaseNotification(name) {}
};

class DomainEvent2: public BaseNotification
{
public:
	DomainEvent2(std::string name) : BaseNotification(name) {}
};


class LoggableEvent: public BaseNotification
{
public:
	LoggableEvent(std::string name, std::string msg) : BaseNotification(name), message(msg) {}

	std::string getMessage() const
	{
		return this->message;
	}
private:
	std::string message;
};

class Component
{
public:
	Component(Poco::NotificationCenter& nc) : notificationCenter(nc){}


	void handleDomainEvent1(const Poco::AutoPtr<DomainEvent1>& pNf)
	{
		std::cout << "Component::handleDomainEvent1::start::" << pNf->getName() << std::endl;
		//Perform a time consuming operation
		Poco::Thread::sleep(500);
		std::cout << "Component::handleDomainEvent1::Time consuming done, now log::" << pNf->getName() << std::endl;
		//Notify my task is done
		LoggableEvent* notification = new LoggableEvent("Component::handleDomainEventA", "SUCCESS");
		this->notificationCenter.postNotification(notification);
		std::cout << "Component::handleDomainEvent1::DONE:" << pNf->getName() << std::endl;
		// Returning here would unlock the mutex
	}
	void handleDomainEvent2(const Poco::AutoPtr<DomainEvent2>& pNf)
	{
		std::cout << "Component::handleDomainEvent2::start::" << pNf->getName() << std::endl;
		//Perform a time consuming operation
		Poco::Thread::sleep(1000);
		std::cout << "Component::handleDomainEvent2::Time consuming done, now log::" << pNf->getName() << std::endl;
		//Notify my task is done
		LoggableEvent* notification = new LoggableEvent("Component::handleDomainEvent2", "SUCCESS");
		this->notificationCenter.postNotification(notification);
		std::cout << "Component::handleDomainEvent2::DONE:" << pNf->getName() << std::endl;
		// Returning here would unlock the mutex
	}

private:
	Poco::NotificationCenter& notificationCenter;
};

class LoggingListener
{
public:

	void handleLoggableEvent(const Poco::AutoPtr<LoggableEvent>& pNf)
	{
		std::cout << "LoggingListener::handleLoggableEvent::" << pNf->getName() << ":" << pNf->getMessage() << std::endl;
	}
};

int main() {
	Poco::NotificationCenter nc;

	std::cout << "Creating targets" << std::endl;
	Component component1(nc);
	Component component2(nc);
	LoggingListener loggingListener;

	std::cout << "Creating observers" << std::endl;

	Poco::NObserver<Component, DomainEvent1> domainObserver1(component1, &Component::handleDomainEvent1);
	Poco::NObserver<Component, DomainEvent2> domainObserver2(component2, &Component::handleDomainEvent2);
	Poco::NObserver<LoggingListener, LoggableEvent> loggingObserver(loggingListener, &LoggingListener::handleLoggableEvent);

	std::cout << "Adding observers" << std::endl;

	// IMPORTANT: Note that observer 2 was added first on the list (You can't allways control when someone adds itself as observer can you?)
	nc.addObserver(domainObserver2);
	nc.addObserver(domainObserver1);
	nc.addObserver(loggingObserver);

	std::cout << "Creating threads" << std::endl;
	Poco::Thread thread1("Thread1");
	Poco::Thread thread2("Thread2");

	std::cout << "Launching threads" << std::endl;
	//Lambda function
	thread1.startFunc([&nc]()
	{
		//We notify something relevant on our domain happened, possibly, some component will react
		DomainEvent1* domainEvent = new DomainEvent1("DomainEvent1");
		// This lock the SECOND observer
		nc.postNotification(domainEvent);
	});
	thread2.startFunc([&nc]()
	{
		//We notify something relevant on our domain happened, possibly, some component will react
		DomainEvent2* domainEvent = new DomainEvent2("DomainEvent2");
		//This will lock the FIRST observer
		nc.postNotification(domainEvent);
	});

	/* Order stuff happens on the time line
	 * Thread 1:
	 *  locks the SECOND observer on the observer list
	 *  Starts a heavy load operation
	 * Thread 2:
	 *  locks the FIRST observer on the list
	 *  Starts a heavy load operation
	 * Thread 1:
	 *   ends it's heavy load taks and raises a notification
	 * 	 Notification center tries to send the event to the FIRST observer
	 * 	 First observer is locked by thead 2, so until it't unlocked we are blocked here
	 * Thread 2:
	 * 	ends it's heavy load task and raises a notification
	 * 	Notification center tries to send the event to the first observer
	 * 	First observer is locked by this same thread so it goes on on that lock, tries to cast, fails and goes to the next observer
	 * 	The second observer is locked by another thread, so it waits untill its released by thread 1
	 *
	 *	Now we have a deadlock, both threads are locked by each other
	 */



	// Now we just wait stuff to end, we add some sleep so this message doesn't plolutes the output
	Poco::Thread::sleep(2000);
	std::cout << "Joining threads" << std::endl;
	//Join order doesnt matter
	std::cout << "Waiting thread 2 to end" << std::endl;
	thread2.join();
	std::cout << "Waiting thread 1 to end" << std::endl;
	thread1.join();

	std::cout << "Removing observers" << std::endl;
	nc.removeObserver(domainObserver1);
	nc.removeObserver(domainObserver2);
	nc.removeObserver(loggingObserver);

	//Done
	std::cout << "BYE" << std::endl;
	return 0;
}
```
Maybe this is not the right component for the behaviour I'm looking for.

Thanks in advance and correct anything you may see
