### ISSUE TITLE
[NetSSL] Certificate validation error: Unacceptable certificate: application verification failure

### ISSUE THREAD

**Issue by CingKong** [pocoproject/poco#2585]
```
Context::Ptr ptrContext2 = new Context(Context::CLIENT_USE, "", "", "certificate.pem", Context::VERIFY_RELAXED, 9, false, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
SharedPtr<InvalidCertificateHandler> ptrCert2 = new ConsoleCertificateHandler(false);
SSLManager::instance().initializeClient(0, ptrCert2, ptrContext2);
SocketAddress sa("127.0.0.1", 9999);
//SocketAddress sa("192.168.8.191", 9999);
auto ss1 = new SecureStreamSocket(sa);
std::string data("16C1N4NheheD4Dhehe");
ss1->sendBytes(data.data(), (int) data.size());
char buffer[256];
ss1->receiveBytes(buffer, sizeof(buffer));
std::cout << buffer << std::endl;
delete  ss1;    
```
#### Actual behavior
if i use network interface address instead of loopback address it throws exception
`Certificate validation error: Unacceptable certificate from 192.168.8.191: application verification failure`

#### POCO version
Pocoproject.Poco.vs150.x64.1.9.0
#### Compiler and version
Vs2017 x64
#### Operating system and version
Windows 10 17763

**Comment by CingKong** [comment]
if i change verification mode to Context::VERIFY_NONE it of cuz pass, but why does address type matter in relaxed mode?

**Comment by CingKong** [comment]
figured out a temporary solution: set CN to exactly the server ip (in this case "192.168.8.191")

**Comment by CingKong** [comment]
wish someone can detail the reason :|

**Comment by avovana** [comment]
@CingKong the reason is that:
cert(with CN in) should be used on some address(that is CN)

When SSL handshaking is going client asks server cert. And see what is in CN.
If (CN != address where the server is up) => ERROR of verification.
