### ISSUE TITLE
SocketReactor SIGSEGV

### ISSUE THREAD

**Issue by TheAifam5** [pocoproject/poco#2594]
Version: 1.9.0
OS: ArchLinux x64
Package: archlinux.org/packages/community/x86_64/poco

```
 _logger.information ("Registering readable handler");
  _reactor.addEventHandler (
      _socket,
      NObserver<HltAbstractClient, ReadableNotification> (*this, &HltAbstractClient::onSocketReadable)
  );

  _logger.information ("Registering writable handler");
  _reactor.addEventHandler (
      _socket,
      NObserver<HltAbstractClient, WritableNotification> (*this, &HltAbstractClient::onSocketWritable)
  );

  _logger.information ("Registering shutdown handler");
  _reactor.addEventHandler (
      _socket,
      NObserver<HltAbstractClient, ShutdownNotification> (*this, &HltAbstractClient::onSocketShutdown)
  );

  _logger.information ("Registering error handler");
  _reactor.addEventHandler (
      _socket,
      NObserver<HltAbstractClient, ErrorNotification> (*this, &HltAbstractClient::onSocketError)
  );

  _logger.information ("Registering timeout handler");
  _reactor.addEventHandler (
      _socket,
      NObserver<HltAbstractClient, TimeoutNotification> (*this, &HltAbstractClient::onSocketTimeout)
  );

void HltAbstractClient::run () {
  _socket.connect (_address);
  _reactor.run ();
}
```

<pre>2019-01-26 00:52:08 Information  HltServerRequestHandlerFactory - Connection incoming
2019-01-26 00:52:08 Information  HltServerRequestHandler - Parsing request
2019-01-26 00:52:08 Information  HltServerRequestHandler - Creating new client
2019-01-26 00:52:08 Information  HltLegacyClient-c6076376-df71-4488-9dd4-293c5666e645 - Registering readable handler
2019-01-26 00:52:08 Information  HltLegacyClient-c6076376-df71-4488-9dd4-293c5666e645 - Registering writable handler
2019-01-26 00:52:08 Information  HltLegacyClient-c6076376-df71-4488-9dd4-293c5666e645 - Registering shutdown handler
2019-01-26 00:52:08 Information  HltLegacyClient-c6076376-df71-4488-9dd4-293c5666e645 - Registering error handler
2019-01-26 00:52:08 Information  HltLegacyClient-c6076376-df71-4488-9dd4-293c5666e645 - Registering timeout handler
2019-01-26 00:52:08 Information  HltLegacyClient-c6076376-df71-4488-9dd4-293c5666e645 - Connection created
2019-01-26 00:52:08 Information  HltLegacyClient-c6076376-df71-4488-9dd4-293c5666e645 - Stopping reactor
2019-01-26 00:52:08 Information  HltLegacyClient-c6076376-df71-4488-9dd4-293c5666e645 - Closing

Thread 3 &quot;program&quot; received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff37fe700 (LWP 11549)]
0x00007ffff7ecfc25 in Poco::Net::SocketReactor::run() () from /usr/lib/libPocoNet.so.60
LEGEND: <font color="#FFC135">STACK</font> | <font color="#42A5F5">HEAP</font> | <font color="#FF5252">CODE</font> | <font color="#D81B60">DATA</font> | <u style="text-decoration-style:single">RWX</u> | RODATA
<font color="#42A5F5">──────────────────────────────────────────────────────────────────────────────────[ REGISTERS ]───────────────────────────────────────────────────────────────────────────────────</font>
 <b>RAX </b> 0x0
 <b>RBX </b> 0x0
 <b>RCX </b> 0x0
 <b>RDX </b> 0x0
 <b>RDI </b> 0x1
 <b>RSI </b> 0x0
 <b>R8  </b> <font color="#D81B60">0x7ffff3ffe710</font> ◂— 0x1
 <b>R9  </b> <font color="#D81B60">0x616000002fa8</font> —▸ 0x200000004 ◂— 0x0
 <b>R10 </b> 0xfffffffffffff5fc
 <b>R11 </b> <font color="#FF5252">0x7ffff7ecfae0 (Poco::Net::SocketReactor::run())</font> ◂— <font color="#AFD700">push</font><font color="#F5F5F5">   </font><font color="#5FD7FF">r15</font>
 <b>R12 </b> 0x0
 <b>R13 </b> <font color="#D81B60">0x7ffff3ffe6b8</font> ◂— 0x13fa8c0ffff0000
 <b>R14 </b> <font color="#D81B60">0x616000002e98</font> ◂— 0xbebebebebebe0001
 <b>R15 </b> <font color="#D81B60">0x616000002f28</font> ◂— 0x0
 <b>RBP </b> <font color="#D81B60">0x7ffff3ffe698</font> ◂— &apos;Connecti&apos;
 <b>RSP </b> <font color="#D81B60">0x7ffff37fdbc0</font> ◂— 0x0
 <b>RIP </b> <font color="#FF5252">0x7ffff7ecfc25 (Poco::Net::SocketReactor::run()+325)</font> ◂— <font color="#AFD700">mov</font><font color="#F5F5F5">    </font><font color="#5FD7FF">rdx</font><font color="#F5F5F5">, </font><font color="#5FD7FF">qword</font><font color="#F5F5F5"> </font><font color="#5FD7FF">ptr</font><font color="#F5F5F5"> [</font><font color="#5FD7FF">rbx</font><font color="#F5F5F5"> + </font><font color="#AF87FF">0x30</font><font color="#F5F5F5">]</font>
<font color="#42A5F5">────────────────────────────────────────────────────────────────────────────────────[ DISASM ]────────────────────────────────────────────────────────────────────────────────────</font>
<font color="#C3D82C"><b> ►</b></font> <font color="#C3D82C"><b>0x7ffff7ecfc25</b></font> <font color="#C3D82C"><b>&lt;Poco::Net::SocketReactor::run()+325&gt; </b></font>   <font color="#AFD700"><b>mov</b></font><font color="#F5F5F5"><b>    </b></font><font color="#5FD7FF"><b>rdx</b></font><font color="#F5F5F5"><b>, </b></font><font color="#5FD7FF"><b>qword</b></font><font color="#F5F5F5"><b> </b></font><font color="#5FD7FF"><b>ptr</b></font><font color="#F5F5F5"><b> [</b></font><font color="#5FD7FF"><b>rbx</b></font><font color="#F5F5F5"><b> + </b></font><font color="#AF87FF"><b>0x30</b></font><font color="#F5F5F5"><b>]</b></font>
   0x7ffff7ecfc29 &lt;Poco::Net::SocketReactor::run()+329&gt;    <font color="#AFD700">test</font><font color="#F5F5F5">   </font><font color="#5FD7FF">rdx</font><font color="#F5F5F5">, </font><font color="#5FD7FF">rdx</font>
   0x7ffff7ecfc2c &lt;Poco::Net::SocketReactor::run()+332&gt;    <font color="#AFD700"><b>je</b></font><font color="#F5F5F5">     </font><font color="#AF87FF">Poco::Net::SocketReactor::run()+701</font> &lt;<font color="#FF5252">0x7ffff7ecfd9d</font>&gt;
    ↓
   0x7ffff7ecfd9d &lt;Poco::Net::SocketReactor::run()+701&gt;    <font color="#AFD700">mov</font><font color="#F5F5F5">    </font><font color="#5FD7FF">edi</font><font color="#F5F5F5">, </font><font color="#AF87FF">0x38</font>
   0x7ffff7ecfda2 &lt;Poco::Net::SocketReactor::run()+706&gt;    <font color="#AFD700"><b>call</b></font><font color="#F5F5F5">   </font><font color="#5FD7FF">qword</font><font color="#F5F5F5"> </font><font color="#5FD7FF">ptr</font><font color="#F5F5F5"> [</font><font color="#5FD7FF">rip</font><font color="#F5F5F5"> + </font><font color="#AF87FF">0x4b268</font><font color="#F5F5F5">]</font> &lt;<font color="#FF5252">0x7ffff795ab90</font>&gt;
 
   0x7ffff7ecfda8 &lt;Poco::Net::SocketReactor::run()+712&gt;    <font color="#AFD700">xor</font><font color="#F5F5F5">    </font><font color="#5FD7FF">esi</font><font color="#F5F5F5">, </font><font color="#5FD7FF">esi</font>
   0x7ffff7ecfdaa &lt;Poco::Net::SocketReactor::run()+714&gt;    <font color="#AFD700">mov</font><font color="#F5F5F5">    </font><font color="#5FD7FF">r12</font><font color="#F5F5F5">, </font><font color="#5FD7FF">rax</font>
   0x7ffff7ecfdad &lt;Poco::Net::SocketReactor::run()+717&gt;    <font color="#AFD700">mov</font><font color="#F5F5F5">    </font><font color="#5FD7FF">rdi</font><font color="#F5F5F5">, </font><font color="#5FD7FF">rax</font>
   0x7ffff7ecfdb0 &lt;Poco::Net::SocketReactor::run()+720&gt;    <font color="#AFD700"><b>call</b></font><font color="#F5F5F5">   </font><font color="#5FD7FF">qword</font><font color="#F5F5F5"> </font><font color="#5FD7FF">ptr</font><font color="#F5F5F5"> [</font><font color="#5FD7FF">rip</font><font color="#F5F5F5"> + </font><font color="#AF87FF">0x4c29a</font><font color="#F5F5F5">]</font> &lt;<font color="#FF5252">0x7ffff7b5d400</font>&gt;
 
   0x7ffff7ecfdb6 &lt;Poco::Net::SocketReactor::run()+726&gt;    <font color="#AFD700"><b>jmp</b></font><font color="#F5F5F5">    </font><font color="#FF5252">0x7ffff7e57ed7</font>
 
   0x7ffff7ecfdbb &lt;Poco::Net::SocketReactor::run()+731&gt;    <font color="#AFD700">nop</font><font color="#F5F5F5">    </font><font color="#5FD7FF">dword</font><font color="#F5F5F5"> </font><font color="#5FD7FF">ptr</font><font color="#F5F5F5"> [</font><font color="#5FD7FF">rax</font><font color="#F5F5F5"> + </font><font color="#5FD7FF">rax</font><font color="#F5F5F5">]</font>
<font color="#42A5F5">────────────────────────────────────────────────────────────────────────────────────[ STACK ]─────────────────────────────────────────────────────────────────────────────────────</font>
00:0000│ <b>rsp </b> <font color="#D81B60">0x7ffff37fdbc0</font> ◂— 0x0
... ↓
02:0010│ <b>    </b> <font color="#D81B60">0x7ffff37fdbd0</font> —▸ <font color="#D81B60">0x7ffff37fdc70</font> ◂— 0x0
03:0018│ <b>    </b> <font color="#D81B60">0x7ffff37fdbd8</font> —▸ <font color="#D81B60">0x7ffff37fdc60</font> ◂— 0x0
04:0020│ <b>    </b> <font color="#D81B60">0x7ffff37fdbe0</font> ◂— 0x0
05:0028│ <b>    </b> <font color="#D81B60">0x7ffff37fdbe8</font> —▸ <font color="#D81B60">0x7ffff3ffe710</font> ◂— 0x1
06:0030│ <b>    </b> <font color="#D81B60">0x7ffff37fdbf0</font> ◂— 0x0
... ↓
<font color="#42A5F5">──────────────────────────────────────────────────────────────────────────────────[ BACKTRACE ]───────────────────────────────────────────────────────────────────────────────────</font>
 ► f 0     7ffff7ecfc25 Poco::Net::SocketReactor::run()+325
   f 1     55555569a1bd HltAbstractClient::run()+61
   f 2     7ffff7bd25c0 Poco::PooledThread::run()+176
   f 3     7ffff7bce35f Poco::ThreadImpl::runnableEntry(void*)+159
   f 4     7ffff7a73a9d start_thread+253
</pre>

**Comment by obiltschnig** [comment]
Likely related to #2593.
