### ISSUE TITLE
How to create thread and stop it?

### ISSUE THREAD

**Issue by TheAifam5** [pocoproject/poco#2595]
Hey!
I could not find any information how can I achieve that.
What I exactly want is to create a thread and later then when I execute `ThreadPool::defaultPool ().stopAll ()` to call the stop function (after the HTTPServer stops).

That code is in `HTTPRequestHandler` which creates the `HltLegacyClientHandler` every HTTP request. I can make a `Runnable` class, but I dont see the "stop" function/callback there. I could also use `new` and pass it to the `start` function but then how that could be deallocated?

(Pseudocode)
```
StreamSocket socket;
SocketReactor reactor;
HltLegacyClientHandler client (socket, reactor);
socket.connectNB (SocketAddress ("example.com", 80));
ThreadPool::defaultPool ().start (reactor);
```

Regards,
TheAifam5

**Comment by aleks-f** [comment]
You don't stop a thread, you stop the runnable, then join the thread that was running it to make sure the runnable has completed.
