### ISSUE TITLE
Built DLLs don't export Poco::Net::HTTPRequest::HTTP_GET, HTTP_POST and others

### ISSUE THREAD

**Issue by angelmixu** [pocoproject/poco#2598]
#### Expected behavior
When using DLL/dynamic linkage on windows, it shouldn't show any link error messages.

#### Actual behavior
When linking with my application, there are these errors on Visual Studio 2017:
```
1>myNet.lib(Connection.obj) : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const Poco::Net::HTTPRequest::HTTP_POST" (?HTTP_POST@HTTPRequest@Net@Poco@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
1>myNet.lib(Connection.obj) : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const Poco::Net::HTTPRequest::HTTP_GET" (?HTTP_GET@HTTPRequest@Net@Poco@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
1>myNet.lib(Connection.obj) : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const Poco::Net::HTTPMessage::HTTP_1_1" (?HTTP_1_1@HTTPMessage@Net@Poco@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
```

#### Steps to reproduce the problem
* Download Poco 1.9.0 from zip file https://pocoproject.org/releases/poco-1.9.0/poco-1.9.0.zip
* Compile with Developer Command Prompt for VS2017 using buildwin 150
* Use PocoNet.lib to link with my project.
* Use this line of code on a default main:
    `Poco::Net::HTTPRequest request(Poco::Net::HTTPRequest::HTTP_GET, "/", Poco::Net::HTTPMessage::HTTP_1_1);`

#### POCO version
1.9.0

#### Compiler and version
Visual Studio 2017 15.9.6

#### Operating system and version
Windows 10 Home 1809 OS Build 17763.194

#### Other relevant information
In my application I have this line:
`Poco::Net::HTTPRequest request(Poco::Net::HTTPRequest::HTTP_GET, path, Poco::Net::HTTPMessage::HTTP_1_1);`
where I can find the link errors.
As I can see, HTTP_GET, HTTP_POST and others, are not exported correctly.
I can include it with no problems, but the implementation on HTTPRequest.cpp is not exported correctly.
In the meantime I can declare the missing HTTP_GET/etc. in my code for making it work.

Should this be fixed, or should I use static libraries instead?
Thanks!

**Comment by andzno1** [comment]
I am experiencing the exact same issue.
#### vcpkg version
2018.11.23-nohash

#### POCO version
poco:x64-windows 1.9.0-1

#### Compiler and version
Visual Studio 2017 15.9.7

#### Operating system and version
Windows 10 Education 1803 Build 17134.590
