### ISSUE TITLE
Handle request cancellation in HttpRequestHandler

### ISSUE THREAD

**Issue by nvartolomei** [pocoproject/poco#2601]
Hello,

I'm looking for a way to handle request cancellation/connection closed in HttpRequestHandler in order to avoid doing any expensive work.

Is there any way to achieve this?

**Comment by nvartolomei** [comment]
I guess one way would be to get socket handle from the http session and try to read from it while preparing the response and see if it fails then cancel work. Caveat, breaks http pipelining, but who cares :)

Let me know if there are better ways to achieve it.

**Comment by nvartolomei** [comment]
```cpp
Poco::Net::StreamSocket & socket = dynamic_cast<Poco::Net::HTTPServerRequestImpl &>(request).socket();

/// Assume that at the point this method is called no one is reading data from the socket any more.
/// True for read-only queries.
try
{
    char b;
    int status = socket.receiveBytes(&b, 1, MSG_DONTWAIT | MSG_PEEK);
    if (status == 0)
        context.killCurrentQuery();
}
catch (Poco::TimeoutException &)
{
}
catch (...)
{
    context.killCurrentQuery();
}
```

**Comment by obiltschnig** [comment]
Another option would be to call `poll()` on the socket with a very small/zero timeout. If it indicates the socket is readable you know the client has either closed the connection or sent additional data, or the next request.

**Comment by nvartolomei** [comment]
Couldn’t figure out how to differentiate closed the connection from sent additional data using poco’s poll implementation.

Do you have a hint?
