### ISSUE TITLE
Default ServerSocket uses IPv4 only, StreamSocket defaults to IPv6

### ISSUE THREAD

**Issue by MayaPosch** [pocoproject/poco#2605]
#### Expected behavior

When I create a server (based on TCPServer) and client (using StreamSocket), I expected that they can connect without any issues or further configuration required.

#### Actual behavior

The TCPServer (ServerSocket) only listens on IPv4, not IPv6. The StreamSocket attempts to connect using IPv6, fails and throws a connection refused error.

#### Steps to reproduce the problem

Build and run the NymphRPC test server and client from: https://github.com/MayaPosch/NymphRPC

#### POCO version

POCO 1.9.0.

#### Compiler and version

gcc version 8.2.1 20181207 (Rev1, Built by MSYS2 project)

#### Operating system and version

Windows 7 x64 Ultimate.

#### Other relevant information

The same code used to work fine with older (~1.7) versions of POCO. Suspicion is that something got changed.

**Comment by obiltschnig** [comment]
That's because on most systems today "localhost" is resolved to ::1 (IPv6) first, followed by 127.0.0.1, and the StreamSocket uses the first resolved IP address, thus attempting to connect over IPv6 while the default ServerSocket is on IPv4.

The issue here is the SocketAddress constructor, which only takes the first resolved IP address.

**Comment by obiltschnig** [comment]
Btw, the reason why it worked in previous version is that we re-ordered the address list returned by the DNS lookup so that IPv4 addresses would be moved to the front. People complained about that (rightfully, as it was a hack), so it was changed.

**Comment by MayaPosch** [comment]
But what is the reasoning behind a TCPServer/default ServerSocket only listening on IPv4?
Is the only 'fix' for that to create one's own ServerSocket, bind6() it and assign it to the new TCPServer instance?

**Comment by zosrothko** [comment]
The proper fix IMO would be to setup an environment variable which would give the order of the DNS resolution so that a same program would work fine both on IPv4 only network as well as IPv6 one.

**Comment by obiltschnig** [comment]
Not sure I like the idea with the environment variable.
Maybe create a socket listening on both IPv6 and IPv4 by default, with the option to use IPv4 or IPv6 only. See https://stackoverflow.com/questions/1618240/how-to-support-both-ipv4-and-ipv6-connections for a possible solution.

**Comment by benignbala** [comment]
Hi @obiltschnig, Is it ok if I try and submit a PR with your suggestion ? Thanks
