### ISSUE TITLE
1.9.0: Poco::MongoDB::ElementTraits<Poco::MongoDB::Document> not defined

### ISSUE THREAD

**Issue by Archivist062** [pocoproject/poco#2608]
#### Expected behavior

`Poco::MongoDB::Document` is recursively convertible to string for the requirements of `Poco::MongoDB::ElementTraits<Poco::MongoDB::Document>` and also matches the rest of those requirements

#### Actual behavior

`Poco::MongoDB::Document` has no definition of `Poco::MongoDB::ElementTraits<Poco::MongoDB::Document>` found from including `<Poco/MongoDB/Document.h>`

#### Steps to reproduce the problem

```cpp
auto doc = Poco::SharedPtr<Poco::MongoDB::Document>{};
auto doc2 = Poco::MongoDB::Document{};
doc2.add("other", doc);
```

#### POCO version

1.9.0 (compiled from github on february 10th 2019 from tag `poco-1.9.0-release`)

#### Compiler and version

gcc version 8.2.1 20181215 (Red Hat 8.2.1-6) (GCC) 

#### Operating system and version

Fedora 28

#### Other relevant information

I may not understand fully how I am supposed to do including a document in a document, If I actually don't, I'll gladly make additional doc on it once I understand.

**Comment by agrebenyuk** [comment]
@Archivist062 have you actually found how to add Document inside Document ? Their documentation is so pour

**Comment by agrebenyuk** [comment]
Found the solution myself:

to add Document inside document you need to use Document::Ptr rather than just Document using `add` method:
 
```
 Poco::MongoDB::Document::Ptr sub_document = new Poco::MongoDB::Document();
 doc.add("sub_document_name", sub_document);
```

same with arrays

```
  Poco::MongoDB::Array::Ptr sub_doc_array = new Poco::MongoDB::Array();
  doc.add("sub_document_array", sub_doc_array);
```
