### ISSUE TITLE
Secure datagram socket not timing out

### ISSUE THREAD

**Issue by rohitgoyal2112** [pocoproject/poco#2618]
#### Expected behavior
The secure datagram socket in MacOS is not timing out if the firewall DROPS the UDP 443 packets.
#### Actual behavior
The connect() socket call succeeds without any error or exception.
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
1. Use Mac packet filter to drop all UDP 443 packets
2. connect the Secure Datagram socket with timeout set. 
3. Socket connect succeeds.
4. Call completeHandshake() on the socket. It gets struck forever and does not return.

#### POCO version
1.9
#### Operating system and version
MacOS 10.14.3

**Comment by bridgewaterrobbie** [comment]
What "Secure datagram" are you using? I don't think Poco supports that yet in general?
