### ISSUE TITLE
[Feature Request] SevenZip Create Archive

### ISSUE THREAD

**Issue by seppy87** [pocoproject/poco#2622]
Hallo Poco Community,

is a SevenZip class planned which is able to create Archives and compress folders? 

Greetings

**Comment by obiltschnig** [comment]
No, nothing's planned regarding 7zip.

**Comment by seppy87** [comment]
There is QArchive which is under BSD-3 License. It uses QString and other Qt Parts. Maybe BSD License is compatible to your boost so you can rewrite the code and add it. So you don't need to reinvent the wheel ;)
