### ISSUE TITLE
Poco::Zip::Decompress non ascii filenames 

### ISSUE THREAD

**Issue by skardile** [pocoproject/poco#2626]
#### Expected behavior
On Windows I expect to see non ascii filenames when a zip archive is extracted using decompressAllFiles (Poco::Zip::Decompress) is used to decompress zip archive

#### Actual behavior
On Windows when a zip file archive (test£.zip) with file name (test£.txt) is extracted using decompressAllFiles the folder name is test(instead of test£) and also text file name is test.txt (instead of test£.txt)

I have taken care of unicode strings and have given proper filepaths. 

The issue happens only on Windows. On linux, I see the expected behavior with proper non ascii filenames.

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

create a zip folder "test£.zip" with one text file "test£.txt"

Followed the code snippet mentioned in the following documentation:
https://pocoproject.org/docs/ZipUserGuide.html

std::ifstream inp(ZIPFILEPATH, std::ios::binary);
poco_assert (inp);
// decompress to current working dir
Decompress dec(inp, Poco::Path()); 
// if an error happens invoke the ZipTest::onDecompressError method
dec.EError += Poco::Delegate<ZipTest, std::pair<const Poco::Zip::ZipLocalFileHeader, const std::string> >(this, &ZipTest::onDecompressError);
dec.decompressAllFiles();
dec.EError -= Poco::Delegate<ZipTest, std::pair<const Poco::Zip::ZipLocalFileHeader, const std::string> >(this, &ZipTest::onDecompressError);
 

#### POCO version
1.7.8
#### Operating system and version
Windows 10

**Comment by skardile** [comment]
Can you please confirm if it is indeed a limitation on Windows platform ? If yes, are there any workaround ? Thank you for your help.

**Comment by obiltschnig** [comment]
Properly UTF-8 encoded filenames should work on both Linux and Windows. When creating the Zip file, you just have to make sure that filenames are actually UTF-8 encoded. If you create the Zip file with Poco::Zip, this should be so on Windows. On a Linux machine, a UTF-8 locale should be used. On Windows, results will depend on which tool you've used to create the Zip file. Some may use the current Windows code page to encode the filename. Unfortunately, AFAIK Zip has no way to specify the actual encoding used for filenames.
