### ISSUE TITLE
Poco::Zip::Decompress: How to get file attributes on Linux / mac

### ISSUE THREAD

**Issue by skardile** [pocoproject/poco#2628]
#### Expected behavior
When I create Poco::Zip::ZipArchive::FileInfos::const_iterator I expect to access external file attributes of an archive entry file which will help me to check if the archive entry was a symbolic link or also preserve file permissions on Linux and mac.

#### Actual behavior
I do not see any method to access these file attribute. Or any way to check if the archive entry was symbolic link or its file permissions. 

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.9

**Comment by skardile** [comment]
@obiltschnig  : please let me know if it is possible to check if the archive entry is symbolic link and also check permissions while decompressing a zip archive.

Thank you so much in advance for your help !!

**Comment by skardile** [comment]
Please let me know if it is a limitation ? or is there any way I can access external file attributes from central directory file header assuming createHeader() returns central directory file header and not local file header? I need to get set the correct permissions on the extracted files and also preserve symbolic links if there were any in the original zip archive.

Your help is very much appreciated. 

Thanks.

**Comment by obiltschnig** [comment]
Unix file attributes and symbolic links are not supported.
