### ISSUE TITLE
How to relocation the istream which receiveResponse return after copyStream?

### ISSUE THREAD

**Issue by toranger** [pocoproject/poco#2632]
#### Expected behavior
When use Poco::StreamCopier::copyStreamthe the src data can reuse.

#### Actual behavior
When use Poco::StreamCopier::copyStream the src stream position can not relocation

#### Steps to reproduce the problem
I use poco session to receive the http response and copy the recv_stream to the DigestOutputStream to check the MD5, I use the tellg() to rember to pos, when finish copy seek the postion to the front. But after checking the MD5 continue use  copyStream to copy stream into file stream found that the return size is 0 and the location file is empty. 
`

        std::istream& recv_stream = session->receiveResponse(res);
        //  check the md5
        if (is_check_md5 && !StringUtil::IsV4ETag(etag)
            && !StringUtil::IsMultipartUploadETag(etag)) {
            Poco::MD5Engine md5;
            Poco::DigestOutputStream dos(md5);
            std::streampos pos = recv_stream.tellg();
            Poco::StreamCopier::copyStream(recv_stream, dos);
            recv_stream.clear();
            recv_stream.seekg(pos);
            dos.close();
            std::string md5_str = Poco::DigestEngine::digestToHex(md5.digest());

            if (etag != md5_str) {
                ret = -1;
            }
        }
        // There the size is 0
        int size = Poco::StreamCopier::copyStream(recv_stream, resp_stream);
`

#### POCO version
1.9.0-all
#### Compiler and version
g++ 6.3.0
#### Operating system and version
Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

**Comment by noelfarrugia09** [comment]
@toranger Did you manage to solve this issue?
