### ISSUE TITLE
DeflatingOutputStream throws IOException on close

### ISSUE THREAD

**Issue by not-sungard** [pocoproject/poco#2633]
#### Expected behavior
Writting to the DeflatingOutputStream should complete normally.

#### Actual behavior
A Poco::IOException is thrown when the close() method is called.

#### Steps to reproduce the problem
```
#include <vector>
#include <random>
#include <fstream>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <limits>

#include <Poco/Base64Encoder.h>
#include <Poco/Base64Decoder.h>
#include <Poco/DeflatingStream.h>
#include <Poco/InflatingStream.h>
#include <Poco/Exception.h>

#ifdef max
#undef max
#endif

constexpr size_t DATA_SIZE = 2147483648;
constexpr size_t INTEGER_COUNT = DATA_SIZE / sizeof(int);
static_assert(DATA_SIZE % sizeof(int) == 0, "Data size must be a multiple of int size");

int main()
{
	// Large array of integers
	std::vector<int> large;
	large.reserve(INTEGER_COUNT);

	try
	{
		// Fill integer array with random numbers
		{
			std::random_device rd;
			std::mt19937_64 gen(rd());
			std::uniform_int_distribution<> dist(0, std::numeric_limits<int>::max());

			for (size_t count = INTEGER_COUNT; count > 0; --count)
				large.push_back(dist(gen));
		}

		// Build a JSON document
		std::ostringstream buf;
		buf << '{'
			<< std::quoted("name") << ':' << std::quoted("LARGE") << ','
			<< std::quoted("data") << ':' << '"';

		// Compress & encode integers
		{
			Poco::Base64Encoder encoder(buf);
			encoder.rdbuf()->setLineLength(0);
			Poco::DeflatingOutputStream zipper(encoder, Poco::DeflatingStreamBuf::STREAM_GZIP, 1);
			zipper.write(reinterpret_cast<const char *>(large.data()), DATA_SIZE);
			zipper.close();		// throws exception here
			encoder.close();
		}

		// end of document
		buf << '"' << '}';

		std::string json_doc = buf.str();
		// TODO: something with the document

		std::cout << "OK" << std::endl;
	}
	catch (const Poco::Exception& e)
	{
		std::cerr << "Error. " << typeid(e).name() << ": " << e.displayText() << std::endl;
	}

    return 0;
}
```

#### POCO version
1.9.0

#### Compiler and version
Visual Studio 2015, 14.0.25431.01 Update 3

#### Operating system and version
Microsoft Windows 10 Enterprise
10.0.16299 Build 16299

**Comment by not-sungard** [comment]
More info:

This seems to be related to how difficult the data is to compress.
If you replace the array filling code with:

```
		// Fill with consecutive values
		{
			for (int i = 0; i < INTEGER_COUNT; ++i)
				large.push_back(i);
		}

```
Then the repro code will succeed (no exception thrown).

**Comment by not-sungard** [comment]
Any update on this issue?
There is a note above saying it's added for the release 1.9.1 milestone, but 1.9.3 is now released.

**Comment by obiltschnig** [comment]
You could be reaching some internal restriction of the zlib library or iostreams here - a series of random numbers is next to impossible to deflate, and your resulting stream could actually be larger than 2 GB, which on a 32-bit system could be problematic. What is the exception text you're seeing?

**Comment by not-sungard** [comment]
Yes, I do realise that random data is uncompressable and will likely get bigger when attempting to compress. It still shouldn't throw an exception though. I'm running 64-bit so the 2GB limit isn't a problem.

**Comment by not-sungard** [comment]
The exception text is: "I/O error"

**Comment by obiltschnig** [comment]
What you're seeing is an error caused by the `ostringstream`; I assume out of memory. The exception is thrown after writing the deflated data to the output stream failed with the stream going into bad state. Did a quick test replacing the `ostringstream` with Poco::NullOutputStream and it ran through. So it looks nothing we can fix here.

**Comment by obiltschnig** [comment]
I did fix the misleading (empty) exception messages though.
