### ISSUE TITLE
CMake install command does not work

### ISSUE THREAD

**Issue by ruurdadema** [pocoproject/poco#2635]
#### Expected behavior
As per documentation on the website (https://pocoproject.org/download.html), when invoking `cmake --install .` the built libraries should be installed in `/usr/local/lib` (default).

#### Actual behavior
CMake only generates, but does not install

#### Steps to reproduce the problem
```
mkdir cmake-build && cd cmake-build
cmake .. && cmake --build .
sudo cmake --install .
```

However,
`cmake --build . --target install` or `sudo make install` do work

#### POCO version
1.9.0

#### Compiler and version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
cmake version 3.12.0

#### Operating system and version
System Version: macOS 10.14.3 (18D109)
Kernel Version: Darwin 18.2.0

#### Other relevant information
It should probably be changen in the docs and on the website

**Comment by Bjoe** [comment]
I recommended this:
$ cmake -H. -Bcmake-build
$ cmake --build cmake-build 
$ cmake --build cmake-build --target install

I have already updated the "Getting Started" docs:
https://github.com/pocoproject/poco/blob/poco-1.9.1/doc/00200-GettingStarted.page
See Building using CMake.

Is this working for you?
Btw. which generator you are using?

@obiltschnig As I mentioned before the cmake part should be updated on the website

**Comment by obiltschnig** [comment]
updated the website

**Comment by ruurdadema** [comment]
> I recommended this:
> $ cmake -H. -Bcmake-build
> $ cmake --build cmake-build
> $ cmake --build cmake-build --target install

> Is this working for you?

Yes!

> Btw. which generator you are using?

The default (generator unspecified), so thats Makefiles on OS X.
