### ISSUE TITLE
JSON integer parsing breaking backwards compatibility with 1.8.0 onwards.

### ISSUE THREAD

**Issue by Burgch** [pocoproject/poco#2636]
#### Expected behavior

The behaviour of JSON parsing when switching to pdjson in 1.8.0 onwards is the same as JSON parsing before; i.e. when parsing integers (signed or unsigned) which fit into a 32 bit datatype, that datatype is used, instead of everything being `(U)Int64`.

#### Actual behavior

Everything is handled as a `(U)Int64`.

#### Steps to reproduce the problem

Add a testcase which checks the type of the `Poco::Dynamic::Var` after parsing a number in `testNumberProperty` - this would have previously been `int` or `unsigned` but is now `Poco::Int64` or `Poco::UInt64`.

#### POCO version

1.8.0 onwards

#### Compiler and version

Any

#### Operating system and version

Any

**Comment by obiltschnig** [comment]
We'll stay with the post 1.8 behavior.
