### ISSUE TITLE
PocoNetSSLWin64 - DLL works, Static lib DNS Error: EAI: 10093

### ISSUE THREAD

**Issue by seppy87** [pocoproject/poco#2642]
#### Expected behavior
Expected that DLL and the static lib will behave exactly and download the file.

#### Actual behavior
DLL will work. Static Lib will throw Exception: DNS Error: EAI 10093.

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
I used NetSSL_Win_x64_vs150.sln to compile (BATCH all static and all shared) to make it.
I used #pragma comment(lib,"Crypt32.lib") for including the windows crypt library

#### POCO version
poco-develop - I cloned the github

#### Compiler and version
MSVC 2017 15.9.7

#### Operating system and version
Windows 10

**Comment by aleks-f** [comment]
On windows you must initialize networking - it won't happen automatically for static poco library.
