### ISSUE TITLE
Make mc.exe (Message Compiler) optional, for supporting MinGW cross-compiling

### ISSUE THREAD

**Issue by qwertychouskie** [pocoproject/poco#2645]
Currently POCO will not build on systems without `mc.exe`.  This is fine on Windows systems, where the Windows SDK can just be installed.  However, this creates problems for cross-compiling Windows binaries on Linux.  A pre-made header (see https://github.com/pocoproject/poco/issues/2356#issuecomment-473149465 for one made for 1.9.0) should be included, and used whenever `mc.exe` is not available.

**Comment by zosrothko** [comment]
Why don't you develop an portable Message Compiler compliant with the Windows Message Compiler? (With Poco of course!)

**Comment by qwertychouskie** [comment]
Seems overkill just for a header or two that need to be generated.  Just including the header is a much simpler change.

**Comment by mydatamodels** [comment]
In package mingw64-binutils-2.30-6.fc30.x86_64.rpm there is /usr/bin/x86_64-w64-mingw32-windmc, but to let it find by Poco cmake I had to create a symbolic link to mc.exe

**Comment by ark0f** [comment]
MinGW has `windmc.exe` for same purposes. [There](https://github.com/pocoproject/poco/pull/2432/files#diff-82e3d124ee074792da499bfe90b93c77R41) is example how it can look.

**Comment by iuridiniz** [comment]
In order to compile in ubuntu, I have to do:

```
ln -s /usr/bin/x86_64-w64-mingw32-windmc /usr/bin/mc.exe
```

**Comment by akshaybabloo** [comment]
Poco unable to find `windmc.exe`, had to rename the file to `mc.exe` to work.

**Comment by nwrkbiz** [comment]
It also works by simply specifying the full path to cmake via `-DCMAKE_MC_COMPILER=/path/to/x86_64-w64-mingw32-windmc`
