### ISSUE TITLE
ServerApplication exit when setting breakpoint

### ISSUE THREAD

**Issue by ikapica** [pocoproject/poco#2646]
#### Expected behavior
When debugging server application it should be possible to set new breakpoint.

#### Actual behavior
When server application is being debug (using CLion + gdb) and new breakpoint is set server application exits (waitForTerminationRequest() exits). 

#### Steps to reproduce the problem
- create simple server application that does some processing in another thread while application waitForTerminationRequest()
- start application in debugger
- set breakpoint in e.g. processing thread code

#### POCO version
1.9

#### Compiler and version
gcc 6

#### Operating system and version
Linux 16.04 LTS

**Comment by obiltschnig** [comment]
You can set the environment variable `POCO_ENABLE_DEBUGGER` before launching the application to prevent `waitForTerminationRequest()` from returning on `SIGINT`, which is sent when setting a breakpoint.
