### ISSUE TITLE
[Poco::Data::PostgreSQL] Avoid using prepared statements

### ISSUE THREAD

**Issue by astlin** [pocoproject/poco#2653]
Hi, I've used to work with PostgreSQL via SessionPooling, and it worked well while connecting directly to PostgreSQL DB. But now they are using pg_bouncer in front of PostgreSQL and I started to get into troubles. Pg_bouncer doesn't support prepared statements and I'm getting exceptions like this:

`PostgreSQL: [PostgreSQL]: postgresql_stmt_describe error: ERROR:  prepared statement "pa1211138p4c03p11e9p9486pac1f6b01bc0a" does not exist`

Digging docs I've found out that using Poco::Data::now keyword in statement forces Poco not to use prepared_statements but it doesn't help.

And this code:
```
Poco::SharedPtr<RecordSet> rs;

try {
  Poco::Data::Session sess(_sessionPool->get());
  rs = new Poco::Data::RecordSet(sess, commandSelect);
} catch {
...
}
```
also throws 'prepared statement does not exist' exception. Please help, how to 'not prepare' statements?

Poco 1.9.1, FreeBSD 11

**Comment by vmato** [comment]
Is there a way to disable prepared statements?
