### ISSUE TITLE
Inconsistent output seen when "ps -ef | grep -i  'firefox'" is launched with ProcessHandle 

### ISSUE THREAD

**Issue by shailcompsit** [pocoproject/poco#2660]
#### Expected behavior
The behavior should be consistent with below output 
```
Return Value = 0
Output = root     21267 21265  0 11:57 pts/0    00:00:00 grep -i firefox
```
#### Actual behavior
The output is inconsistent as posted below  

```
$ ./program
Return Value = 0
Output = root     21267 21265  0 11:57 pts/0    00:00:00 grep -i firefox

$./program
Return Value = 1
Output =
```

#### Steps to reproduce the problem
Program:
```
    Poco::Pipe inPipe,outPipe,errPipe;
    std::string sudo="sudo";
    std::string cmd="ps -ef | grep -i 'firefox'";

    std::vector<std::string> args;
    args.push_back("sh");

    ProcessHandle ph = Process::launch(sudo, args , &inPipe, &outPipe, &errPipe);
    Poco::PipeOutputStream ostr(inPipe);
    ostr << cmd;
    ostr.close();
    cout<<"Return Value = "<<ph.wait()<<endl;

    Poco::PipeInputStream istr(outPipe);
    std::stringstream gotStr;
    Poco::StreamCopier::copyStream(istr, gotStr);
    std::string outPut = gotStr.str();
    istr.close();
    cout<<"Output = "<<outPut<<endl;

```
2. Compilation 
`g++ program.cpp -o program -I3rdparty/poco/include/ -L3rdparty/poco/lib/ -lPocoUtil -lPocoFoundation -lPocoXML -lPocoJSON -g
`
#### POCO version
1.9.0
#### Compiler and version
g++ 4.9.2
#### Operating system and version
```
$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```
#### Other relevant information

When run the program multiple times, we see the inconsistent output.

**Comment by obiltschnig** [comment]
You are not launching a single executable, you are launching a shell command - two programs connected via a pipe. In order to do that, you have to launch a shell (`sh`) and pass the entire command line to it as a single argument with `-c`. See #2389 for an example.

**Comment by shailcompsit** [comment]
@obiltschnig Appreciate your reply.

Additional Information: 
1. Using "sudo" is not an issue, works with other commands too.
    e.g. cat /etc/passwd | grep -i 'root'
2. As you suggested in above comment, I'm launching the a shell(sh), "sh" is provided in "args" vector as shown in the program snippet. 
3. The shell command is passed as inPipe.

**Comment by obiltschnig** [comment]
I would not recommend sending the command via pipe, use `sh -c` instead. Also, you are not sending a `\n` after the command, probably also should not close the PipeOutputStream before you've read the output.
My recommendation would be to launch `sudo`, with arguments `sh`, `-c` and the command line (`cmd`).
