### ISSUE TITLE
Poco::Zip::ZipArchive cannot load new tomcat.zip file

### ISSUE THREAD

**Issue by hop2286** [pocoproject/poco#2661]
#### Expected behavior
Poco::Zip::ZipArchive load zip archive

#### Actual behavior
throws an exception Assertion violation

#### Steps to reproduce the problem
download tomcat version 9.0.17
http://tux.rainside.sk/apache/tomcat/tomcat-9/v9.0.17/bin/apache-tomcat-9.0.17-windows-x64.zip
try to unzip by Poco::Zip::ZipArchive

#### POCO version
poco-1.9.0-all

#### Compiler and version
visual studio 2017

#### Operating system and version
windows 10 x64

#### Other relevant information
tomcat 9.0.16 and higher

#include "pch.h"
#include <iostream>
#include <fstream>
#include "d:\Poco_test\poco-1.9.0-all\Zip\include\Poco\Zip\ZipArchive.h"

int main()
{
    std::string folderName = "d:\\Downloads\\apache-tomcat-9.0.17-windows-x64.zip";
    std::ifstream inp(folderName, std::ios::binary);
    poco_assert(inp);
    try
    {
        Poco::Zip::ZipArchive arch(inp);       
    }
    catch (std::exception& e)
    {
        std::cout << e.what();
    }
}

**Comment by OgreTransporter** [comment]
I loaded the file from https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.17/bin/apache-tomcat-9.0.17-windows-x64.zip and tried it with the unzip example:

> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Assertion violation: size >= 8 [in file "D:\poco-dev\poco\Zip\src\ZipLocalFileHeader.cpp", line 168]
[call trace not available]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Assertion violation: size >= 8 in file "D:\poco-dev\poco\Zip\src\ZipLocalFileHeader.cpp", line 168
[call trace not available]

**POCO version**
develop branch

**Compiler and version**
Visual Studio 2017 (15.9.11)

**Operating system and version**
Windows 10 x64 (1809)

**Comment by obiltschnig** [comment]
I may already have a fix for that sent by a customer.

**Comment by hop2286** [comment]
It still not working. I have tried 1.9.1 and 1.9.2. and same error.
http://tux.rainside.sk/apache/tomcat/tomcat-9/v9.0.22/bin/apache-tomcat-9.0.22-windows-x64.zip
thanks

**Comment by obiltschnig** [comment]
Looks like same bug, but in another file.
