### ISSUE TITLE
State of POCO Postgresql branch

### ISSUE THREAD

**Issue by mtangoo** [pocoproject/poco#2664]
Well not a bug really, but in coming few weeks I will have an assignment of integrating Database functionalities in my App and MySQL/Mariadb and Postgresql are two things I will need. The condition of MySQL is clear but I wanted to know about PGS.

Just as a footnote, we opted out of ODBC because of a lot of headache that comes with it (We used it previously and didn't really satisfy us)

So what is the state of PGS branch, usability as well as the versions it supports?
TIA

**Comment by aleks-f** [comment]
Status is "should work". I did not use it in production (did not have a need yet), did some work on preparing it for release, but it is not released yet.

**Comment by mtangoo** [comment]
That's great. I will keep this thread open for a feedback.
Thank you again!

**Comment by astlin** [comment]
We do use PostgreSQL in production (poco 1.9.1). With [this](https://github.com/pocoproject/poco/pull/2677) patch it works fine. The only significant problem are prepared statements, that seems can't be turned off, in case of using pgbouncer.

**Comment by mtangoo** [comment]
Thanks @astlin
I'll keep that in mind.  I will alse

**Comment by mtangoo** [comment]
Thanks @astlin
I'll keep that in mind.  I will also test the patch at home

**Comment by mtangoo** [comment]
Accidental closure
