### ISSUE TITLE
Linking error while using static_mt Windows x64 libs in VS2015 project

### ISSUE THREAD

**Issue by pruthig** [pocoproject/poco#2667]
#### Expected behavior
Application should link successfully with PoCo libs.

#### Actual behavior
Getting linking errors while building the project.

#### Steps to reproduce the problem
1. Install VS2015 (140 toolset)
2. Build the static_mt (64-bit) PoCo libs (v1.9) using the following command
`buildwin.cmd 140 rebuild static_mt release x64 nosamples notests msbuild env normal'
The command needs to be executed via VS2015 x64 Native tools command prompt.
3. Create a VS2015 project which will use these libs.
3. Supply path to the libs in Visual studio project.
4. Try building the project and check the output window.

#### POCO version 
1.9

#### Compiler and version
VS2015 (ver.# 14.0.25420.01 Update 3)

#### Operating system and version
Windows 7 64-bit

#### Other relevant information
Getting the following linking errors:
```
Error	LNK2001	unresolved external symbol "public: __cdecl Poco::Net::HTTPServer::HTTPServer(class Poco::SharedPtr<class Poco::Net::HTTPRequestHandlerFactory>,class Poco::Net::ServerSocket const &,class Poco::RefPtr<class Poco::Net::HTTPServerParams>)" (??0HTTPServer@Net@Poco@@QEAA@V?$SharedPtr@VHTTPRequestHandlerFactory@Net@Poco@@@2@AEBVServerSocket@12@V?$RefPtr@VHTTPServerParams@Net@Poco@@@2@@Z)	server	C:\Users\gpruthi\demo_project\server\server\server_impl.obj	1	

Error	LNK2001	unresolved external symbol "protected: virtual void __cdecl Poco::Util::ServerApplication::waitForTerminationRequest(void)" (?waitForTerminationRequest@ServerApplication@Util@Poco@@MEAAXXZ)	server	C:\Users\gpruthi\demo_project\server\server\main.obj	1	

Error	LNK2001	unresolved external symbol "protected: virtual unsigned long __cdecl Poco::Util::ServerApplication::handleDeviceEvent(unsigned long,void *)" (?handleDeviceEvent@ServerApplication@Util@Poco@@MEAAKKPEAX@Z)	server	C:\Users\gpruthi\demo_project\server\server\main.obj	1	

```

Following libs have been placed in the lib directory:

- PocoEncodingsmt
- PocoFoundationmt
- PocoJSONmt
- PocoNetmt
- PocoUtilmt
- PocoXMLmt

**Comment by pruthig** [comment]
Linking errors were because of incorrect ordering of linked libraries. Closing the issue.

**Comment by aslucky** [comment]
what's the correct ordering?

release mode not working, debug mode ok.

#pragma comment(lib, "PocoFoundation.lib")
#pragma comment(lib, "PocoJSON.lib")
#pragma comment(lib, "PocoXML.lib")
#pragma comment(lib, "PocoNet.lib")
#pragma comment(lib, "PocoUtil.lib")

switch order 

#pragma comment(lib, "PocoUtil.lib")
#pragma comment(lib, "PocoFoundation.lib")
#pragma comment(lib, "PocoJSON.lib")
#pragma comment(lib, "PocoXML.lib")
#pragma comment(lib, "PocoNet.lib")

not working , I switch every order, still not working..

 error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual void __thiscall Poco::Util::ServerApplication::waitForTerminationRequest(void)" (__imp_?waitForTerminationRequest@ServerApplication@Util@Poco@@MAEXXZ)
1>pocoHttpServer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual unsigned long __thiscall Poco::Util::ServerApplication::handleDeviceEvent(unsigned long,void *)" (__imp_?handleDeviceEvent@ServerApplication@Util@Poco@@MAEKKPAX@Z)
