### ISSUE TITLE
400 Bad Request when redirecting from POST

### ISSUE THREAD

**Issue by h3ndrk** [pocoproject/poco#2670]
#### Expected behavior

1. Browser submits `<form action="post">` to `Poco::Net::HTTPServer` (with data via `application/x-www-form-urlencoded`), this results in a `POST`-request with form-encoded data in the body
2. The derived `Poco::Net::HTTPRequestHandler` responds with `302 Found` via:

```cpp
void Handler::handleRequest(HTTPServerRequest &request, HTTPServerResponse &response) {
    response.redirect("/somepath/512.html");
}
```

which results in:

```
HTTP/1.1 302 Found
Date: Wed, 03 Apr 2019 06:23:33 GMT
Connection: Keep-Alive
Content-Length: 0
Location: /somepath/512.html
```

3. The browser reuses the connection and requests a second `GET /somepath/512.html`
4. The server responds with the correct result, e.g. `200 OK`

#### Actual behavior

The actual response in 4. is:

```
HTTP/1.1 400 Bad Request
Connection: Close
```

The problem relies in:

https://github.com/pocoproject/poco/blob/2d43f4d61c8a5eb3fefbebfd00bc8e81b0e76771/Net/src/HTTPRequest.cpp#L216-L217

There, `method` contains the first 32 characters of the previous `POST`-request's form-data body, e.g. `place=1&name=Hello+Poco&comment=` and `ch` contains `&` which is obviously not a space and therefore not a valid HTTP method.

It seems that the input stream is not advanced by the `Content-Length` of the previous request, so it still holds the old form-data.

Is it the fault of my implementation that I do not read the `POST` message body and only doing a `response.redirect(...)`? Am I expected to read all data of a `POST`-request before issueing a `response.redirect(...)`?

My current workaround is to close the connection:

```cpp
void Handler::handleRequest(HTTPServerRequest &request, HTTPServerResponse &response) {
    response.setKeepAlive(false);
    response.redirect("/somepath/512.html");
}
```

#### Steps to reproduce the problem

If needed, I can extract my code from our product and build a [SSCCE](http://www.sscce.org/) example.

#### POCO version

644c00e42f414732a3e17dba4dd71ff9807fca24

#### Compiler and version

MSVC 14.0, Visual Studio 2015

#### Operating system and version

Windows 10, 64Bit, 1809

**Comment by obiltschnig** [comment]
You have to read all of the POST request body before sending the response.

**Comment by NIPE-SYSTEMS** [comment]
Thanks for the quick answer. The following makes it work (`Poco::Net::HTMLForm` reads the complete request body.):

```cpp
void Handler::handleRequest(HTTPServerRequest &request, HTTPServerResponse &response) {
    // credit: https://stackoverflow.com/a/29404436
    HTMLForm form(request, request.stream());
    response.redirect("/somepath/512.html");
}
```

Maybe improve the documentation of `redirect()`? Should I file a pull request?

**Comment by noboruma** [comment]
@obiltschnig is that behavior backed by any HTTP specification? 
I am genuinely interested to know how we are supposed to terminate an illegal POST request (e.g. unauthorized requests) without spending time reading the request body. 
More specifically, why is the stream not cleared out once the HTTPServerResponse is destroyed?

**Comment by obiltschnig** [comment]
It has nothing to do with the HTTP specification, it's an implementation detail. In this particular case, the choice was made that the `HTTPRequestHandler` is responsible for consuming the entire request body.

**Comment by NIPE-SYSTEMS** [comment]
1. Is there a way to advance the stream without spending time reading the request body? Maybe with [`std::istream::seekg()`](https://en.cppreference.com/w/cpp/io/basic_istream/seekg)?
2. Where is the choice that the `HTTPRequestHandler` is responsible for consuming the entire request body documented? How do we improve it eventually? (See my suggestion [above](https://github.com/pocoproject/poco/issues/2670#issuecomment-479372316).)

Thanks!

**Comment by noboruma** [comment]
@NIPE-SYSTEMS, regarding your first point, [`std::istream::ignore`](http://www.cplusplus.com/reference/istream/istream/ignore/) might be a safer approach. That said I am curious to know if `std::istream::seekg()` would suffice, since it is possibly faster.
