### ISSUE TITLE
how to use poco in x64

### ISSUE THREAD

**Issue by gufei2016** [pocoproject/poco#2673]
I use poco in my projects use vc12.0 x64 release:

in my .h script I write
#include <Poco/Event.h>
Poco::Event                        Handle;

and in the .cpp script I write
bool  Event::Clear()
{
    MutexedLock Lock(mLock);

    mSignaled = false;

    bool ret = true;
    try {
      Handle.reset();
    } catch (Poco::SystemException &){
      ret = false;
    }

    return ret;
}

but it says:
\Poco/Platform_WIN32.h(38): fatal error C1189: #error :  Inconsistent build settings (check for /MD[d])
I dont know why

**Comment by seppy87** [comment]
seems like something wants to mix MT(d) and MDd. Mave you included your lib by yourself or did you use the automatic inclusion?
