### ISSUE TITLE
develop is failed to compile on big-endian system

### ISSUE THREAD

**Issue by agalanin** [pocoproject/poco#2683]
#### Expected behavior
Successful compilation.

#### Actual behavior

```
/build/poco-develop/Foundation/src/SHA3Engine.cpp: In function 'void Poco::KeccakP1600_Permute_24rounds(void*)':
/build/poco-develop/Foundation/src/SHA3Engine.cpp:232:61: error: 'fromBytesToWords' was not declared in this scope
  fromBytesToWords(stateAsWords, (const unsigned char *)state);
                                                             ^
/build/poco-develop/Foundation/src/SHA3Engine.cpp:234:55: error: 'fromWordsToBytes' was not declared in this scope
  fromWordsToBytes((unsigned char *)state, stateAsWords);
                                                       ^
make[2]: *** [Foundation/CMakeFiles/Foundation.dir/build.make:1428: Foundation/CMakeFiles/Foundation.dir/src/SHA3Engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:188: Foundation/CMakeFiles/Foundation.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

#### Steps to reproduce the problem
Build using the following command sequence:
```bash
export PATH=/opt/freeware/bin:$PATH
rm -rf cmake-build
mkdir cmake-build
cd cmake-build
cmake \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_CXX_COMPILER=g++ \
    -DCMAKE_C_FLAGS="-maix64 -Wl,-b64 -pthread" \
    -DCMAKE_CXX_FLAGS="-maix64 -Wl,-b64 -pthread" \
    -DCMAKE_SHARED_LINKER_FLAGS="-maix64 -Wl,-b64" \
    ..
make
```

#### POCO version
develop (bd98f5cedf298148a053bf2f7142847351f64fb9) + patch from https://github.com/pocoproject/poco/pull/2682

#### Compiler and version
GCC 6.3.0

#### Operating system and version
AIX 7.2

#### Other relevant information
cpu architecture is PowerPC

**Comment by Bjoe** [comment]
Hm `fromWordsToBytes()` and `fromByetsToWords()` are missing at all in poco.
I see a function in https://github.com/XKCP/XKCP/blob/8f447eb59d43fef72297f5f1560e2cefea093b32/lib/low/KeccakP-1600/Reference/KeccakP-1600-reference.c#L258
and https://github.com/XKCP/XKCP/blob/8f447eb59d43fef72297f5f1560e2cefea093b32/lib/low/KeccakP-1600/Reference/KeccakP-1600-reference.c#L269 but I have no clue about this code.
I see in the commit ecaa7887a1ea6d18ca25f54c169d92bd5aac7d73 that Ogre implemnts this.

@OgreTransporter Can you say more?

Or maybe you try your self when you implement tihs function based on the function https://github.com/XKCP/XKCP/blob/8f447eb59d43fef72297f5f1560e2cefea093b32/lib/low/KeccakP-1600/Reference/KeccakP-1600-reference.c#L258
and https://github.com/XKCP/XKCP/blob/8f447eb59d43fef72297f5f1560e2cefea093b32/lib/low/KeccakP-1600/Reference/KeccakP-1600-reference.c#L269 and create a pull request.

**Comment by OgreTransporter** [comment]
I have added the two functions. Unfortunately I can't test it because I don't have big endian systems.

**Comment by agalanin** [comment]
> I have added the two functions. Unfortunately I can't test it because I don't have big endian systems. Please test and give feedback.

SHA3Engine compiled successfully. Unfortunately I don't know how to test it.

**Comment by OgreTransporter** [comment]
You could run the poco tests. There is a testsuite for SHA included.

**Comment by agalanin** [comment]
> You could run the poco tests. There is a testsuite for SHA included.

How to run the test suite? I am using cmake as the build system and don't see any target like 'test' in a generated Makefile. Or may be you know how to call ./configure on AIX to use GCC as a compiler?
