### ISSUE TITLE
How to set socket5 proxy by Poco https client and wss client?

### ISSUE THREAD

**Issue by allen2015555** [pocoproject/poco#2687]
Expected behavior
Success when https client post/get and wss send/recv in use socket5 proxy

Actual behavior
When https client set proxy, it will failed!
example:
HttpsClietnSession cs;
cs.setProxyUsername("username");
cs.setProxyPassword("password");
cs.setProxy("xxx.xxx.xxx.xxx", 5555 );
// other code
try {
    std::ostream& os = cs.sendRequest(request);  // will failed
} catch(Poco::Exception& e) {
    cout << e.displayText() << endl;  // show "No message received"
}

The ip "xxx.xxx.xxx.xxx:5555" can be pinged.
I apologize my english is poor.

POCO version
1.9.0
Compiler and version
msvc14.1 

Operating system and version
Win10 64bit Enterprise Edition

**Comment by obiltschnig** [comment]
The SOCKS protocol is not supported.

**Comment by sumnayono** [comment]
@obiltschnig Do you have any plans to support him?

**Comment by obiltschnig** [comment]
Not for now.
