### ISSUE TITLE
Multithread AsyncChannel log Crashs  on Win7

### ISSUE THREAD

**Issue by ViviAka** [pocoproject/poco#2696]
Develop brach , Win7 vs2017 
Thread_STD_WIN32.cpp  --> setPriorityImpl-->thread->native_handle()
must cause crashs in multithread.

handle must be get before  like blow:

HANDLE handle = reinterpret_cast<HANDLE>(_pData->thread->native_handle());
if (SetThreadPriority(handle, _pData->prio) == 0)
	throw SystemException("cannot set thread priority");

**Comment by Matthew-McRaven** [comment]
I can confirm this bug exists in Windows 10.

This crash occurred for me when creating an `AsyncChannel`. I managed to track it down to `Poco::Thread::Impl::_pData` being unitialized. In fact, creating any `Poco::Thread` and then immediately calling setPriority() caused this crash.

I can provide a minimum working example if this would help.
