### ISSUE TITLE
Win10 SDK Registry Key - Message Compiler

### ISSUE THREAD

**Issue by FBaumeister** [pocoproject/poco#2698]
Hello,
I experienced some problems when configuring Poco 1.9 with Win10 SDK and cmake (3.14.4).
It looks like the Registry Key in cmake/PocoMacros.cmake is wrong. It always points to C:/ProgramFiles/Windows Kits/10 although with me its in C:/Program Files (x86)/Windows Kits/.
This one points to the correct folder (Win10, all updates, Visual Studio 2019, Win10SDK 10.0.18362):
HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10

Fix:
get_filename_component(kit10_dir "[HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10]" REALPATH)

Can you confirm?

**Comment by OgreTransporter** [comment]
Yes, see pr #2694 and #2719

**Comment by FBaumeister** [comment]
Thank you!
