### ISSUE TITLE
[windows bug]  pollset  WSAPoll with non blocking socket will not report error  

### ISSUE THREAD

**Issue by ViviAka** [pocoproject/poco#2706]
#### Expected behavior
If host cannot reach or no route to host. WSAPoll[pollset ] will report error
#### Actual behavior
WSAPoll not report error [but select/epoll report error]
#### Steps to reproduce the problem
use socketconnector  connect a host which can not reach
#### POCO version
all version include pollset (win wsapoll)
#### Compiler and version
vs2017  
#### Operating system and version
win7 sp1

**Comment by pacoteinnov** [comment]
Hi @obiltschnig, do you have a workaround for this issue?  It prevents us from upgrading.
Thanks!

**Comment by aleks-f** [comment]
> Hi @obiltschnig, do you have a workaround for this issue? It prevents us from upgrading. Thanks!

There is [a fix ready](https://github.com/pocoproject/poco/issues/3339) for the windows WSAPoll mess, and it will be in 1.12.
