### ISSUE TITLE
Trying to Compile with emscripten: Target architecture was not detected as supported by Double-Conversion

### ISSUE THREAD

**Issue by suriya1611** [pocoproject/poco#2707]
Trying to compile the poco (1.9.0) libraries using emscripten compiler. Getting error in utils.h file in double-conversion.
I guess latest double-conversion is not updated in poco source code. 
Can you please add the latest version of double-conversion?
Or is it available already in develop branch?

**Comment by mahergreg** [comment]
As a temporary fix you could manually add the following  to the end of the architecture list:
` defined(__EMSCRIPTEN__)`
just before the line 
`#define DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS 1`

**NOTE 1**: 
Also do a project search and replace for (ther are only a couple):
`defined(EMSCRIPTEN)` to `defined(__EMSCRIPTEN__)`

I read that the former is not **always** defined but the latter is.

**NOTE 2**: 
You may get errors on the NET library also (as raw sockets are not supported in Emscripten), to fix this add the following to the main CMakeLists.txt file
`add_definitions(-DPOCO_NO_LINUX_IF_PACKET_H)`

To compile with cmake do the following:

`
mkdir -p ./cmake_build
rm -r ./cmake_build/*
cd cmake_build
emconfigure cmake -S .. -B .
emmake make
`

**Comment by matejk** [comment]
Initially reported issue with double conversion was fixed in 1.12 (commit d294391c94ea0f0c31bdc2ba71d0c9d1035792f7).

Other issues are being resolved for release 1.13.
