### ISSUE TITLE
VC++ MFC Detected memory leaks!

### ISSUE THREAD

**Issue by libaineu2004** [pocoproject/poco#2711]
I used VS2015 to create a new MFC multi-document project, and then introduced the POCO library into the project, only the private declaration in the class:
#include "Poco/Thread.h"
Poco::Mutex m_mutex;
When the software exits, it prompts memory leaks.

Detected memory leaks!
Dumping objects ->
{251} normal block at 0x00296F38, 32 bytes long.
 Data: <%<>{}|\"^`!*'()$> 25 3C 3E 7B 7D 7C 5C 22 5E 60 21 2A 27 28 29 24 
{250} normal block at 0x002988A8, 8 bytes long.
 Data: <l       > 6C 86 EE 0F 00 00 00 00 
{249} normal block at 0x00298870, 8 bytes long.
 Data: <        > C0 86 EE 0F 00 00 00 00 
{248} normal block at 0x00298838, 8 bytes long.
 Data: <        > 88 86 EE 0F 00 00 00 00 
{246} normal block at 0x00298800, 8 bytes long.
 Data: <        > A4 86 EE 0F 00 00 00 00 
{245} normal block at 0x002987C8, 8 bytes long.
 Data: <        > DC 86 EE 0F 00 00 00 00 
{244} normal block at 0x00298790, 8 bytes long.
 Data: <        > C0 85 EE 0F 00 00 00 00 
{243} normal block at 0x00298758, 8 bytes long.
 Data: <        > 8C 85 EE 0F 00 00 00 00 
{242} normal block at 0x00294D08, 44 bytes long.
 Data: < M)  M)  M)     > 08 4D 29 00 08 4D 29 00 08 4D 29 00 01 01 CD CD 
{241} normal block at 0x00298720, 8 bytes long.
 Data: <        > E4 84 EE 0F 00 00 00 00 
{240} normal block at 0x002986E8, 8 bytes long.
 Data: <        > 1C 85 EE 0F 00 00 00 00 
{239} normal block at 0x002986B0, 8 bytes long.
 Data: <8       > 38 85 EE 0F 00 00 00 00 
{238} normal block at 0x00298678, 8 bytes long.
 Data: <        > 00 85 EE 0F 00 00 00 00 
{237} normal block at 0x00296EE8, 32 bytes long.
 Data: <# Log file creat> 23 20 4C 6F 67 20 66 69 6C 65 20 63 72 65 61 74 
{236} normal block at 0x00298640, 8 bytes long.
 Data: <        > A4 84 EE 0F 00 00 00 00 
{235} normal block at 0x00298608, 8 bytes long.
 Data: <        > 18 84 EE 0F 00 00 00 00 
{234} normal block at 0x002985D0, 8 bytes long.
 Data: <        > FC 83 EE 0F 00 00 00 00 
{233} normal block at 0x00298598, 8 bytes long.
 Data: <        > E0 83 EE 0F 00 00 00 00 
{232} normal block at 0x00298410, 8 bytes long.
 Data: <        > C4 83 EE 0F 00 00 00 00 
{231} normal block at 0x002983D8, 8 bytes long.
 Data: <        > A8 83 EE 0F 00 00 00 00 
{230} normal block at 0x002983A0, 8 bytes long.
 Data: <        > 8C 83 EE 0F 00 00 00 00 
{229} normal block at 0x00298368, 8 bytes long.
 Data: <p       > 70 83 EE 0F 00 00 00 00 
{228} normal block at 0x00298330, 8 bytes long.
 Data: <T       > 54 83 EE 0F 00 00 00 00 
{227} normal block at 0x002982F8, 8 bytes long.
 Data: <8       > 38 83 EE 0F 00 00 00 00 
{226} normal block at 0x002982C0, 8 bytes long.
 Data: <        > 00 83 EE 0F 00 00 00 00 
{225} normal block at 0x00298288, 8 bytes long.
 Data: <        > 1C 83 EE 0F 00 00 00 00 
{224} normal block at 0x00298250, 8 bytes long.
 Data: <        > 00 82 EE 0F 00 00 00 00 
{223} normal block at 0x00298218, 8 bytes long.
 Data: <p       > 70 81 EE 0F 00 00 00 00 
{222} normal block at 0x002981E0, 8 bytes long.
 Data: <        > C4 81 EE 0F 00 00 00 00 
{221} normal block at 0x002981A8, 8 bytes long.
 Data: <        > A8 81 EE 0F 00 00 00 00 
{220} normal block at 0x00298170, 8 bytes long.
 Data: <        > 8C 81 EE 0F 00 00 00 00 
{219} normal block at 0x00298138, 8 bytes long.
 Data: <8       > 38 80 EE 0F 00 00 00 00 
{217} normal block at 0x00298100, 8 bytes long.
 Data: <p       > 70 80 EE 0F 00 00 00 00 
{216} normal block at 0x002980C8, 8 bytes long.
 Data: <        > C4 80 EE 0F 00 00 00 00 
{215} normal block at 0x00298090, 8 bytes long.
 Data: <        > 18 81 EE 0F 00 00 00 00 
{214} normal block at 0x00298058, 8 bytes long.
 Data: <T       > 54 80 EE 0F 00 00 00 00 
{213} normal block at 0x00298020, 8 bytes long.
 Data: <        > E0 80 EE 0F 00 00 00 00 
{212} normal block at 0x00297FE8, 8 bytes long.
 Data: <        > A8 80 EE 0F 00 00 00 00 
{211} normal block at 0x00297FB0, 8 bytes long.
 Data: <        > 8C 80 EE 0F 00 00 00 00 
{210} normal block at 0x00297F78, 8 bytes long.
 Data: <        > FC 80 EE 0F 00 00 00 00 
{209} normal block at 0x00297F40, 8 bytes long.
 Data: <        > CC 7F EE 0F 00 00 00 00 
{208} normal block at 0x00297F08, 8 bytes long.
 Data: <        > E8 7F EE 0F 00 00 00 00 
{207} normal block at 0x00297ED0, 8 bytes long.
 Data: <        > 04 80 EE 0F 00 00 00 00 
{206} normal block at 0x00297E98, 8 bytes long.
 Data: <        > B0 7F EE 0F 00 00 00 00 
{205} normal block at 0x00295148, 4 bytes long.
 Data: <    > F0 B9 E2 0F 
{204} normal block at 0x00297E60, 8 bytes long.
 Data: <L}      > 4C 7D EE 0F 00 00 00 00 
{203} normal block at 0x00297E28, 8 bytes long.
 Data: <0}      > 30 7D EE 0F 00 00 00 00 
{202} normal block at 0x00297DF0, 8 bytes long.
 Data: < }      > 14 7D EE 0F 00 00 00 00 
{201} normal block at 0x00297DB8, 8 bytes long.
 Data: < |      > F8 7C EE 0F 00 00 00 00 
{200} normal block at 0x00297D80, 8 bytes long.
 Data: < |      > DC 7C EE 0F 00 00 00 00 
{199} normal block at 0x00297D48, 8 bytes long.
 Data: < |      > C0 7C EE 0F 00 00 00 00 
{198} normal block at 0x00297D10, 8 bytes long.
 Data: < |      > A4 7C EE 0F 00 00 00 00 
{197} normal block at 0x00297CD8, 8 bytes long.
 Data: < |      > 88 7C EE 0F 00 00 00 00 
{196} normal block at 0x00297CA0, 8 bytes long.
 Data: <l|      > 6C 7C EE 0F 00 00 00 00 
{195} normal block at 0x00297C68, 8 bytes long.
 Data: <P|      > 50 7C EE 0F 00 00 00 00 
{194} normal block at 0x002967C8, 8 bytes long.
 Data: <4|      > 34 7C EE 0F 00 00 00 00 
{193} normal block at 0x00296790, 8 bytes long.
 Data: < |      > 18 7C EE 0F 00 00 00 00 
{192} normal block at 0x00296758, 8 bytes long.
 Data: <H~      > 48 7E EE 0F 00 00 00 00 
{191} normal block at 0x00296720, 8 bytes long.
 Data: <,~      > 2C 7E EE 0F 00 00 00 00 
{190} normal block at 0x002966E8, 8 bytes long.
 Data: < ~      > 10 7E EE 0F 00 00 00 00 
{189} normal block at 0x002966B0, 8 bytes long.
 Data: < }      > F4 7D EE 0F 00 00 00 00 
{188} normal block at 0x00296678, 8 bytes long.
 Data: < }      > D8 7D EE 0F 00 00 00 00 
{187} normal block at 0x00296640, 8 bytes long.
 Data: < }      > BC 7D EE 0F 00 00 00 00 
{186} normal block at 0x00296608, 8 bytes long.
 Data: < }      > A0 7D EE 0F 00 00 00 00 
{185} normal block at 0x00296E98, 32 bytes long.
 Data: <%Y-%m-%d %H:%M:%> 25 59 2D 25 6D 2D 25 64 20 25 48 3A 25 4D 3A 25 
{184} normal block at 0x002965D0, 8 bytes long.
 Data: < {      > A8 7B EE 0F 00 00 00 00 
{183} normal block at 0x00296E48, 32 bytes long.
 Data: <%w %b %f %H:%M:%> 25 77 20 25 62 20 25 66 20 25 48 3A 25 4D 3A 25 
{182} normal block at 0x00296598, 8 bytes long.
 Data: < {      > E0 7B EE 0F 00 00 00 00 
{181} normal block at 0x00296DF8, 32 bytes long.
 Data: <%W, %e %b %y %H:> 25 57 2C 20 25 65 20 25 62 20 25 79 20 25 48 3A 
{180} normal block at 0x00296560, 8 bytes long.
 Data: < }      > 84 7D EE 0F 00 00 00 00 
{179} normal block at 0x00296DA8, 32 bytes long.
 Data: <%W, %e-%b-%y %H:> 25 57 2C 20 25 65 2D 25 62 2D 25 79 20 25 48 3A 
{178} normal block at 0x00296528, 8 bytes long.
 Data: < {      > FC 7B EE 0F 00 00 00 00 
{177} normal block at 0x00296D58, 32 bytes long.
 Data: <%w, %d %b %Y %H:> 25 77 2C 20 25 64 20 25 62 20 25 59 20 25 48 3A 
{176} normal block at 0x002964F0, 8 bytes long.
 Data: < ~      > 9C 7E EE 0F 00 00 00 00 
{175} normal block at 0x00296D08, 32 bytes long.
 Data: <%w, %e %b %Y %H:> 25 77 2C 20 25 65 20 25 62 20 25 59 20 25 48 3A 
{174} normal block at 0x002964B8, 8 bytes long.
 Data: < ~      > 80 7E EE 0F 00 00 00 00 
{173} normal block at 0x00296CB8, 32 bytes long.
 Data: <%w, %e %b %y %H:> 25 77 2C 20 25 65 20 25 62 20 25 79 20 25 48 3A 
{172} normal block at 0x00296480, 8 bytes long.
 Data: <h}      > 68 7D EE 0F 00 00 00 00 
{171} normal block at 0x00296C68, 32 bytes long.
 Data: <%Y-%m-%dT%H:%M:%> 25 59 2D 25 6D 2D 25 64 54 25 48 3A 25 4D 3A 25 
{170} normal block at 0x00296448, 8 bytes long.
 Data: < {      > C4 7B EE 0F 00 00 00 00 
{169} normal block at 0x00295888, 32 bytes long.
 Data: <%Y-%m-%dT%H:%M:%> 25 59 2D 25 6D 2D 25 64 54 25 48 3A 25 4D 3A 25 
{168} normal block at 0x00296410, 8 bytes long.
 Data: <d~      > 64 7E EE 0F 00 00 00 00 
{167} normal block at 0x002963D8, 8 bytes long.
 Data: <L{      > 4C 7B EE 0F 00 00 00 00 
Object dump complete.
The program "[16216] MFCApplication2.exe" has exited with a return value of 0 (0x0).

POCO version
1.9.0

Compiler and version
Visual Studio 2015

Operating system and version
Windows 7

**Comment by WillGorski** [comment]
Hi! I have memory leak problem too. Can we have a talk about how to use poco library?
I am from china.  qq:1438613610
BTW: I use httpserver

**Comment by aleks-f** [comment]
Probably some statics still lingering at program shutdown. To see if you have memory leaks, you have to declare runtime checkpoints and see if there is any memory leaked between them. See [LeakDetector](https://github.com/pocoproject/sandbox/blob/master/LeakDetector/Foundation/testsuite/src/LeakDetectorTest.cpp) in sandbox.
