### ISSUE TITLE
File_WIN32.cpp(168): error C2065: “_upath”:Undeclared identifier

### ISSUE THREAD

**Issue by libaineu2004** [pocoproject/poco#2712]
I build poco with MFC Extension DLLs projects, not the windows DLL
Compile error, the focus is on these two error messages：
poco\foundation\src\File_WIN32.cpp(168): error C2065: “_upath”:Undeclared identifier
poco\foundation\src\File_WIN32.cpp(399): error C2065: “upath”: Undeclared identifier

A more detailed report is：
1>------ Started build: Project: Foundation, Configuration: debug_shared Win32 ------
1>File.cpp
1>Compiling POCO on Windows without #define POCO_WIN32_UTF8 is deprecated.
1>c:\users\firecat\source\repos\mfcapplication2\poco\foundation\src\File_WIN32.cpp(168): error C2065: "_upath": Undeclared identifier
1>c:\users\firecat\source\repos\mfcapplication2\poco\foundation\src\File_WIN32.cpp(168): error C2228: The left side of ".c_str" must have class/structure/federated
1>c:\users\firecat\source\repos\mfcapplication2\poco\foundation\src\File_WIN32.cpp(168): note: type is "unknown-type"
1>c:\users\firecat\source\repos\mfcapplication2\poco\foundation\src\File_WIN32.cpp(332): error C2143: Syntax error: Missing ";" (before "}")
1>c:\users\firecat\source\repos\mfcapplication2\poco\foundation\src\File_WIN32.cpp(399): error C2065: "upath": Undeclared identifier
1>c:\users\firecat\source\repos\mfcapplication2\poco\foundation\src\File_WIN32.cpp(399): error C2228: ".c_str" must have class/structure/join on the left side
1>c:\users\firecat\source\repos\mfcapplication2\poco\foundation\src\File_WIN32.cpp(399): note: type is "unknown-type"

#### POCO version
1.9.0
#### Compiler and version
VS2015
#### Operating system and version
Win7

**Comment by OgreTransporter** [comment]
Working with shared MFC library and static MFC library at my computer.

**POCO version**
development

**Compiler and version**
VS2017 (15.9.12)

**Operating system and version**
Win10

**Comment by obiltschnig** [comment]
As build output says:
```
Compiling POCO on Windows without #define POCO_WIN32_UTF8 is deprecated.
```
and not tested any longer.
