### ISSUE TITLE
About Poco Project future

### ISSUE THREAD

**Issue by paulocoutinhox** [pocoproject/poco#2716]
Hi,

Whats the future of poco project?

The project was abandoned?

Will have new releases?

Thanks.

**Comment by obiltschnig** [comment]
There will be a 1.10 release (and releases after that) in the next few weeks, as soon as time permits.

**Comment by prsolucoes** [comment]
Hi,

Ok. Im waiting for the new release a long time. 

Thanks anyway, i understand.

**Comment by OgreTransporter** [comment]
I have a question, too. Is there a special reason why a C++ parser was written with a complicated program (PocoDoc) to document the API? Why not just Doxygen? Doxygen runs on all platforms, PocoDoc I haven't gotten to run under Windows with MSVC yet. Will there be an improvement in the future?

**Comment by obiltschnig** [comment]
Mostly because I didn't like the output of Doxygen and I'm still not excited about its documentation format. Maybe things with Doxygen have improved in the meantime (that was 15 years ago), but at this point adapting the documentation format to whatever Doxygen can handle will be a lot of work.
