### ISSUE TITLE
OAuth10Credentials creates invalid signatures

### ISSUE THREAD

**Issue by gyee-penguin** [pocoproject/poco#2717]
#### Expected behavior
I'm trying to use OAuth10Credentials to create a request token and using http://oauthbin.com/ as a reference server.  I should get a JSON message back like the following:

```
oauth_token=requestkey&oauth_token_secret=requestsecret
```

I can confirm that I get this output when I use a simple python client (based on this library https://github.com/joestump/python-oauth2) to connect.

#### Actual behavior
I get an 'Invalid signature' error message from the server.  Here's the output:

```
2019-06-10 15:59:38.736:DD:(9):Invalid signature
<hr />
OAuthRequest Object
(
    [parameters:protected] => Array
        (
            [oauth_consumer_key] => key
            [oauth_nonce] => MkF0BRAqn0aC4y8z1M3GWuCDBIFecdFysaeCqRLN0
            [oauth_signature] => mpnO51h+RQhDiqPJ5xHzeLliwSE=
            [oauth_signature_method] => HMAC-SHA1
            [oauth_timestamp] => 1560182378
            [oauth_version] => 1.0
        )

    [http_method:protected] => POST
    [http_url:protected] => http://oauthbin.com:/v1/request-token
    [base_string] => POST&http%3A%2F%2Foauthbin.com%2Fv1%2Frequest-token&oauth_consumer_key%3Dkey%26oauth_nonce%3DMkF0BRAqn0aC4y8z1M3GWuCDBIFecdFysaeCqRLN0%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1560182378%26oauth_version%3D1.0
```

#### Steps to reproduce the problem
I followed the OAuth10Credentials documentation for requesting an OAuth request token (it's the second numbered list of instructions).

https://pocoproject.org/docs/Poco.Net.OAuth10Credentials.html#24471

#### POCO version
1.9.0

#### Compiler and version
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

#### Operating system and version
CentOS Linux release 7.6.1810 (Core)

**Comment by obiltschnig** [comment]
Works for me. Make sure that you pass in the correct URI to `authenticate()`.

Here's a snippet that works for me:
```
		URI uri("http://oauthbin.com/v1/request-token");
		std::string path(uri.getPathAndQuery());
		if (path.empty()) path = "/";

		HTTPClientSession session(uri.getHost(), uri.getPort());
		HTTPRequest request(HTTPRequest::HTTP_GET, path, HTTPMessage::HTTP_1_1);
		HTTPResponse response;

		Poco::Net::OAuth10Credentials oauth("key", "secret");
		oauth.authenticate(request, uri);
```

**Comment by gyee-penguin** [comment]
You are correct -- I was not passing in the correct URI.  Thank you!
