### ISSUE TITLE
Does Poco have official build config for android arm64?

### ISSUE THREAD

**Issue by elite-sheep** [pocoproject/poco#2722]
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.10.0
#### Other relevant information
Currently if we want to build Poco for android platform, we will use the config in Poco/build/config/Android. Unfortunately, it only supports armeabi and x86. Does Poco have official build config or plan to have one?

**Comment by OgreTransporter** [comment]
There are two ways:

1. Windows+MSVC+CMake (Visual Studio 2017 Update 4 and above offer an ARM64 toolchain)
2. Linux+CMake (use https://github.com/taka-no-me/android-cmake/blob/master/android.toolchain.cmake)

**Comment by Aaron19960821** [comment]
> There are two ways:
> 
> 1. Windows+MSVC+CMake (Visual Studio 2017 Update 4 and above offer an ARM64 toolchain)
> 2. Linux+CMake (use https://github.com/taka-no-me/android-cmake/blob/master/android.toolchain.cmake)

I can build with Linux+make by modifying the config, let me send a pr about this.

**Comment by Bjoe** [comment]
Well, I don't know if you already know but the android NDK is providing a android toolchain for cmake and the android build system (gradle) is using cmake.

If you have also the android SDK then try:
So try:
<pre>
<path_to_android_sdk>/cmake/<cmake_version>/bin/cmake 
-H<path_to_poco_sourcen> 
-B/tmp/poco-build 
-G'Ninja' 
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_INSTALL_PREFIX=<path_to_install_libs>
-DCMAKE_MAKE_PROGRAM=<path_to_android_sdk>/cmake/<cmake_version>/bin/ninja
-DCMAKE_TOOLCHAIN_FILE=<path_to_android_sdk>/ndk-bundle/build/cmake/android.toolchain.cmake
-DANDROID_NATIVE_API_LEVEL=24
-DANDROID_ABI=arm64

cmake --build /tmp/poco-build --target install
</pre>

if you have only the NDK then you should have only [download the cmake](https://cmake.org/download/) binary and try:
<pre>
cmake 
-H<path_to_poco_sourcen> 
-B/tmp/poco-build 
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_INSTALL_PREFIX=<path_to_install_libs>
-DCMAKE_TOOLCHAIN_FILE=<path_to_android_ndk>/build/cmake/android.toolchain.cmake
-DANDROID_NATIVE_API_LEVEL=24
-DANDROID_ABI=arm64

cmake --build /tmp/poco-build --target install
</pre>

After that you will found the compiled libs in <path_to_install_libs>

I also updated the [android platform notes](https://github.com/pocoproject/poco/blob/poco-1.10.0/doc/99300-AndroidPlatformNotes.page)

**Comment by HandyP94** [comment]
> I also updated the [android platform notes](https://github.com/pocoproject/poco/blob/poco-1.10.0/doc/99300-AndroidPlatformNotes.page)

I used the method denoted in the platform notes to generate current versions static libraries.
When adding the updated libraries in my code, I got the following errors when building:

![Build Errors](https://user-images.githubusercontent.com/20842916/60595730-e8106a80-9da7-11e9-8811-4dfaee0e90dd.png)

It seems like following the guide the build messes up somehow, as the header files haven't really changed compared to the previously used version, which is why I expected it to work just fine.
