### ISSUE TITLE
Please add support for the Deflate64 compression method.

### ISSUE THREAD

**Issue by PG-Devs** [pocoproject/poco#2724]
#### Expected behavior
Zip files with Deflate64 compression method can be decompressed.

#### Actual behavior
Access violation (#2723) or `Poco::NotImplementedException`.

#### Steps to reproduce the problem
1. Create a new file with some contents, e.g. a simple text file test.txt.
2. Use 7z to compress the file with the following settings:
    -- Archive format: zip
    -- Compression level: Ultra (probably doesn't matter)
    -- Compression method: Deflate64 (this is the cause of the problem)
    -- Dictionary size: 64 KB (default)
    -- Word size: 128 (default)
3. Try to decompress this file with poco.

#### POCO version
poco-1.9.0-release

#### Compiler and version
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27031.1 for x86

#### Operating system and version
Windows 10 Pro 1809 17763.557

#### Other relevant information
The .zip format specification (https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) lists a bunch more compression methods, of which poco seem to currently support only "store" (0) and "deflate" (8). See the constructor for `ZipStreamBuf`. It would be nice if other (i.e. all) compression methods were supported too.

**Comment by OgreTransporter** [comment]
Wikipedia (https://en.wikipedia.org/wiki/DEFLATE#Deflate64/Enhanced_Deflate):

> Deflate64, specified by PKWARE, is a proprietary variant of the Deflate procedure. The fundamental mechanisms remain the same. What has changed is the increase in dictionary size from 32 KB to 64 KB, an extension of the distance codes to 16 bits so that they may address a range of 64 KB, and the length code, which is extended to 16 bits so that it may define lengths of three to 65,538 bytes. This leads to Deflate64 having a slightly higher compression ratio and a slightly lower compression time than Deflate. Several free and/or open source projects support Deflate64, such as 7-Zip, while others, such as zlib, do not, as a result of the proprietary nature of the procedure and the very modest performance increase over Deflate.

**Comment by obiltschnig** [comment]
Compression in Zip library is handled by zlib, so unless zlib adds support for DEFLATE64, it's unlikely we will implement this.
