### ISSUE TITLE
I recommend adding a Future/Promise C++ library

### ISSUE THREAD

**Issue by libaineu2004** [pocoproject/poco#2725]
#### Expected behavior
I recommend adding a Future/Promise C++ library, similar to the scala programming language for future and promise implementations.

Future/Promise
There are already a lot of implementations of Future mechanism in C++:
std::future - no API at all, except very basic operations like retrieve value and wait for it. There is a Concurrency TS with .then, but it is still not in the standard.
boost::future - almost the same as std::future.
Folly - Folly futures are also inspired by Scala ones (but different ones, from Twitter framework) and have good API but are a part of huge framework which is too hard to use partially.

But the above libraries are either imperfect or have a lot of dependencies, which is not easy to install and use.So why not to create another one?

In this way, the poco library will be more advantageous and attractive.

Thank you！

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

**Comment by obiltschnig** [comment]
We already have [`Poco::ActiveResult`](https://pocoproject.org/docs/Poco.ActiveResult.html) which is basically a Future for use with [`Poco::ActiveMethod`](https://pocoproject.org/docs/Poco.ActiveMethod.html) (and we've had that for 10+ years, way before everyone was crazy about that sh*t). We'd just need to basically add a `then()` method taking a lambda or std::function to make it composable.

**Comment by libaineu2004** [comment]
> We already have [`Poco::ActiveResult`](https://pocoproject.org/docs/Poco.ActiveResult.html) which is basically a Future for use with [`Poco::ActiveMethod`](https://pocoproject.org/docs/Poco.ActiveMethod.html) (and we've had that for 10+ years, way before everyone was crazy about that sh*t). We'd just need to basically add a `then()` method taking a lambda or std::function to make it composable.

Okay thank you. In addition to the then method, will there be when-all, when-any, when-N methods?

**Comment by obiltschnig** [comment]
Would you be interested in contributing to that?

**Comment by libaineu2004** [comment]
> Would you be interested in contributing to that?

I want to participate in my heart, but I am afraid that my level is not enough.

**Comment by libaineu2004** [comment]
> Would you be interested in contributing to that?
[https://github.com/loveyacper/ananas](url)
This is a project of a friend of mine, he implemented the then, future_all, when_any and other methods of future/promise. Perhaps he is interested in getting involved.

**Comment by libaineu2004** [comment]
> Would you be interested in contributing to that?


This is a project of a friend of mine, [https://github.com/loveyacper/ananas](url)
he implemented the then, future_all, when_any and other methods of future/promise. Perhaps he is interested in getting involved.

**Comment by libaineu2004** [comment]
> Would you be interested in contributing to that?

This is a project of a friend of mine, [](https://github.com/loveyacper/ananas)
he implemented the then, future_all, when_any and other methods of future/promise. Perhaps he is interested in getting involved.

**Comment by libaineu2004** [comment]
> Would you be interested in contributing to that?

This is a project of a friend of mine, https://github.com/loveyacper/ananas
he implemented the then, future_all, when_any and other methods of future/promise. Perhaps he is interested in getting involved.
