### ISSUE TITLE
Emscripten support

### ISSUE THREAD

**Issue by isc30** [pocoproject/poco#2726]
Seems like latest emscripten compiler throws some errors regarding not detected compiler features when trying to use the lib as a submodule.
Is emscripten suposed to be part of the supported compilers?

**Comment by isc30** [comment]
```
CMake Error at thirdparty/poco/Foundation/CMakeLists.txt:117 (target_compile_features):
  target_compile_features The compiler feature
  "cxx_defaulted_move_initializers" is not known to CXX compiler "Clang" version 6.0.1.

CMake Error at thirdparty/poco/JSON/CMakeLists.txt:30 (target_compile_features):
  target_compile_features The compiler feature "c_variadic_macros" is not
  known to C compiler "Clang" version 6.0.1.
```

**Comment by Bjoe** [comment]
Which cmake version you are using and which branch ?

**Comment by isc30** [comment]
I'm using the emscripten docker image for building (it contains a modern
cmake) and master branch
