### ISSUE TITLE
postgreSQL SessionPool transaction getting session is unstable ?

### ISSUE THREAD

**Issue by reillyzhen** [pocoproject/poco#2727]
#### Actual behavior
When i get a session from the sessionpool , it's can successful in every times,the transaction line more than 1000 to run,and i test in TI am437x platform.
but i create an session instance by manual,it's normal

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
develop-1.9.1

**Comment by obiltschnig** [comment]
not sure what's the actual issue, closing
