### ISSUE TITLE
Error using CMake gui - latest version

### ISSUE THREAD

**Issue by PaTiToMaSteR** [pocoproject/poco#2736]
#### Expected behavior
No errors using CMake gui
#### Actual behavior
See error log with CMake
#### Steps to reproduce the problem
Just try to configure the project using CMake gui
#### POCO version
1.9.1
#### Compiler and version
VS 2017
#### Operating system and version
Win10
#### Other relevant information
The C compiler identification is MSVC 19.16.27031.1
The CXX compiler identification is MSVC 19.16.27031.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Poco package version: 1.9.1
Checking for C++11 compiler
Checking for C++11 compiler - available
Checking for C++14 compiler
Checking for C++14 compiler - available
CMake Error at cmake/PocoMacros.cmake:33 (message):
  message compiler not found: required to build
Call Stack (most recent call first):
  CMakeLists.txt:86 (include)

Configuring incomplete, errors occurred!
See also "G:/Git/poco-poco-1.9.1-release/bin/CMakeFiles/CMakeOutput.log".

**Comment by obiltschnig** [comment]
Could you please verify the poco-1.9.2 branch builds for you with CMake?
