### ISSUE TITLE
Unbundled build cmake failed on window 

### ISSUE THREAD

**Issue by fenghao119** [pocoproject/poco#2739]
#### Expected behavior
Set **POCO_UNBUNDLED ON**, prebuilt the zlib/pcre/expat dynamic version library
Build the Foundation, XML, NET, UTIL 
#### Actual behavior
PocoUtil module build failed, because not found expat.h
PocoFoundation test failed, because ```add_definitions( -DPCRE_STATIC)```

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.9.1
#### Compiler and version
vs2017 cmake 3.12.1
#### Operating system and version
Windows 10

**Comment by Bjoe** [comment]
I think this should be fixed in `poco-1.10.0` branch. Can you please try?
