### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by packetq** [pocoproject/poco#2742]
Hello All,

I am having some difficulty building Poco on Windows. I have followed the documentation, but the build fails when building the tests. It tries to link PocoFoundation.lib before it has been compiles itself. Any help would be much appreciated.

#### Expected behavior
Build all library versions

#### Actual behavior
Fails trying to link PocoFoundation.lib (which hasn't been built yet)

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
buildwin 140 build all release x64 nosamples notests devenv

#### POCO version
1.9.2
#### Compiler and version
VS 2015

#### Operating system and version
Windows 8.1 64bit

#### Other relevant information
Tests are being built regardless of flags. The build compiles the tests first and then tries to link PocoFoundation.lib, which has not been compiled/built yet.

**Comment by seppy87** [comment]
Have you tried to load the sln and build them there?

**Comment by zosrothko** [comment]
This is a true issue. We are working on it.
