### ISSUE TITLE
Poco::Crypto windows library throwing linker errors when used with custom compiled Openssl 1.1.1 version.

### ISSUE THREAD

**Issue by p-neels** [pocoproject/poco#2754]
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.9.0

#### Compiler and version
VS_Version 110 32 bit

**Comment by obiltschnig** [comment]
Re-compile with the POCO_EXTERNAL_OPENSSL macro set accordingly (see `Foundation/include/Poco/Config.h`):

```
// OpenSSL on Windows
//
// Poco has its own OpenSSL build system.
// See <https://github.com/pocoproject/openssl/blob/master/README.md>
// for details.
//
// These options are Windows only.
//
// To disable the use of Poco-provided OpenSSL binaries,
// define POCO_EXTERNAL_OPENSSL.
//
// Possible values:
//   POCO_EXTERNAL_OPENSSL_SLPRO:
//     Automatically link OpenSSL libraries from OpenSSL Windows installer provided
//     by Shining Light Productions <http://slproweb.com/products/Win32OpenSSL.html>
//     The (global) library search path must be set accordingly.
//   POCO_EXTERNAL_OPENSSL_DEFAULT:
//     Automatically link OpenSSL libraries from standard OpenSSL Windows build.
//     The (global) library search path must be set accordingly.
//   empty or other value:
//     Do not link any OpenSSL libraries automatically. You will have to edit the
//     Visual C++ project files for Crypto and NetSSL_OpenSSL.
// #define POCO_EXTERNAL_OPENSSL POCO_EXTERNAL_OPENSSL_SLPRO
```

**Comment by p-neels** [comment]
Thanks a lot for the inputs.

I tried recompiling with above option POCO_EXTERNAL_OPENSSL enabled  but still seeing below errors in final exe linking.

Any further inputs can you provide for same?

1>PocoCryptomdd.lib(X509Certificate.obj) : error LNK2019: unresolved external symbol _sk_num referenced in function "public: void __thiscall Poco::Crypto::X509Certificate::extractNames(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)const " (?extractNames@X509Certificate@Crypto@Poco@@QBEXAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV?$set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@@Z)
1>PocoCryptomdd.lib(X509Certificate.obj) : error LNK2019: unresolved external symbol _sk_value referenced in function "public: void __thiscall Poco::Crypto::X509Certificate::extractNames(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)const " (?extractNames@X509Certificate@Crypto@Poco@@QBEXAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV?$set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@@Z)
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _CRYPTO_num_locks referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _CRYPTO_set_locking_callback referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _CRYPTO_set_dynlock_create_callback referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _CRYPTO_set_dynlock_lock_callback referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _CRYPTO_set_dynlock_destroy_callback referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _OPENSSL_add_all_algorithms_noconf referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _EVP_cleanup referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _SSL_load_error_strings referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _SSL_library_init referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _ERR_free_strings referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2019: unresolved external symbol _CONF_modules_free referenced in function __catch$??1OpenSSLInitializer@Crypto@Poco@@QAE@XZ$0
1>PocoNetSSLmdd.lib(Context.obj) : error LNK2019: unresolved external symbol _SSLv23_server_method referenced in function __catch$?init@Context@Net@Poco@@AAEXABUParams@123@@Z$0
1>PocoNetSSLmdd.lib(Context.obj) : error LNK2019: unresolved external symbol _SSLv23_client_method referenced in function __catch$?init@Context@Net@Poco@@AAEXABUParams@123@@Z$0
1>C:\ProjectData\EventReporting\UsingPoco\TestClient\Debug\TestClient.exe : fatal error LNK1120: 15 unresolved externals
