### ISSUE TITLE
MYSQL LONGTEXT

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#2755]
#### Expected behavior
LONGTEXT data type correctly supported

#### Actual behavior
Using LONGTEXT cause the select statement throw exception in function 
` void assignRaw(const T* ptr, std::size_t count)
/// Assigns raw content to internal storage.
{
poco_assert_dbg (ptr);
LOB tmp(ptr, count);
swap(tmp);
}`
in LOB.h
just because the _metadata column description has 0 len. TEXT and MEDIUMTEXT is working

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
latest 

#### Compiler and version
VS2015

#### Operating system and version
Windows 10 64bit

**Comment by obiltschnig** [comment]
@aleks-f could you have a look at it please?
