### ISSUE TITLE
Poco::Data::Statement::execute returns wrong value when zero results (ODBC) 

### ISSUE THREAD

**Issue by nmarandi** [pocoproject/poco#2758]
#### Expected behavior
When I execute a select or update statement and there is no row with selected condition, execute return 1 instead of zero. 
#### POCO version
1.9.0
#### Compiler and version
MSVC 2015
#### Operating system and version
Windows 10
#### Other relevant information
microsoft SQL server 2014

**Comment by bmulder-innoseis** [comment]
I still have this issue. Can you tell me what the problem was and how you fixed it?

**Comment by nmarandi** [comment]
@bmulder-innoseis 
I couldn't fix it. I closed the issue, because no one would answered it.

**Comment by bmulder-innoseis** [comment]
I found this might be a duplicate of #1670

**Comment by nmarandi** [comment]
> I found this might be a duplicate of #1670

The version of Poco that I used was different. What is the version you are using? @bmulder-innoseis

**Comment by bmulder-innoseis** [comment]
1.9.0 as well
but this appears to have been in 1.8 already but has not been fixed since

**Comment by nmarandi** [comment]
> 1.9.0 as well
> but this appears to have been in 1.8 already but has not been fixed since

Yeah you are right. Then I will close it again. What I did for fix it, was to check the value returns by query. It always returns 0 but I never had value 0 in a table. It's not a clean way but at least fixs my problem. @bmulder-innoseis

**Comment by bmulder-innoseis** [comment]
yeah, only does that not work for me since 0 is also a valid and common value in the table.
