### ISSUE TITLE
use postman can not recieve http server response

### ISSUE THREAD

**Issue by tyler2018** [pocoproject/poco#2771]
use poco NET example  HTTPTimeServer
modify to fit api service, but use postman can not get response often,  sometimes is ok.

POCO version
1.9.3 release

this is the main code to response.
response.setChunkedTransferEncoding(false);
		response.setStatus(Poco::Net::HTTPResponse::HTTP_OK);
		response.setContentType("application/json;charset=UTF-8");
		response.setKeepAlive(false);
		
		{
			g_logger->info("send to http request: {}", strResp);
			std::ostream& ostr = response.send();
			ostr << strResp;
			ostr.flush();
			response.setContentLength(strResp.size());
		}
use wireshark also not reponse recieved.

And this is another question. sometimes failed.
Software caused connection abort

**Comment by fbraem** [comment]
Set the content length before you call send()

**Comment by tyler2018** [comment]
I tried already , same result

**Comment by obiltschnig** [comment]
This should be sufficient to send the response:

```
response.setContentType("application/json;charset=UTF-8");
response.setContentLength(strResp.size());
std::ostream& ostr = response.send();
ostr << strResp;
```

**Comment by tyler2018** [comment]
thanks，so far so good. 
need more time to confirm.

**Comment by tyler2018** [comment]
After these days use. It's working.
