### ISSUE TITLE
Allow Poco::Net::Context::usePrivateKey to accept ECKey and/or general EVPPKey

### ISSUE THREAD

**Issue by bridgewaterrobbie** [pocoproject/poco#2780]
Poco's context can handle ECKeys loaded from a file during the object construction, but the usePrivateKey function exclusively allows only RSAKey objects. It is possible to make it work with an ECKey by manipulating the raw SSL object.

**Comment by obiltschnig** [comment]
The poco-1.10.0 branch has 
```
void Context::usePrivateKey(const Poco::Crypto::EVPPKey& pkey)
```
which should solve this.
