### ISSUE TITLE
Building with cmake on windows (msvc) fails due to wrong library names.

### ISSUE THREAD

**Issue by MartB** [pocoproject/poco#2782]
https://github.com/pocoproject/poco/blob/62a925469204f4d4c434286620968a2d81949293/Foundation/include/Poco/Foundation.h#L74-L99

The if/else chain here is incorrect when a standalone cmake is used to generate the project files.
The files a simple cmake-gui run produces, are called libame**d**.lib for debug even with library postfix set to MT. Im not sure where this is coming from but i wanted to make people aware of this issue.

**Comment by zosrothko** [comment]
Could you explain more the problem you are facing because this sequence of if/else is running since years...

**Comment by MartB** [comment]
@zosrothko Let me explain in greater detail quickly, because im not sure if anyone is using this way of building atm.

Im running Visual Studio 2017/2019 and a CMAKE project which contains the following lines:
```cmake
set(Poco_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../vendor/poco/vs2019/Poco/)
find_package(Poco REQUIRED COMPONENTS Net NetSSL Util)
if (Poco_FOUND)
	target_link_libraries(kitchencpp PUBLIC Poco::Util Poco::Net Poco::NetSSL)
endif(Poco_FOUND)
```

The poco/vs2019/Poco folder gets generated by a cmake run with the following settings:
```
BUILD_SHARED_LIBS off
POCO_MT on
STATIC_POSTFIX mt (this one gets auto generated)
```

Yet whenever i build my project that uses this as dependency the linker fails to find the right libraries because it keeps searching for mtd but a cmake run with x86 export to vs160 project files only generates the filename with a d omitting the mt part.

The generated libraries are indeed statically linked though as no dll files get generated. 

If you have any additional questions feel free to ask.

**Comment by MartB** [comment]
I redid everything and it somehow managed to generate mtd libraries now, im puzzled.
I assume cmake cache was somehow corrupt.

Sorry for the noise.
