### ISSUE TITLE
Documentation Error regarding Dynamic Var and Object::getValue

### ISSUE THREAD

**Issue by bridgewaterrobbie** [pocoproject/poco#2792]
The documentation for Object, Var and Varholder lead me to believe that given the following setup:
```  
std::vector<DynamicStruct> testList;
  Object t1;
  t1.set("name","com.tl");
  t1.set("num1",false);
  Object j;
  j.set("testval",testList);
```

The following call would let me extract the values (similar to my other use of `Object` with primitives and basic strings)

`  auto retBack = j.getValue<std::vector<DynamicStruct>>("testval");`

However, this results in a compile-time failure of `no matching member function for call to 'convert`. Simplifying this to only be setting a `DynamicStruct` and getting the same still results in the same compile time failure.

I am aware that I can extract the values by doing the following: 
```  
auto testBack = j.get("testval");

  auto extract = testBack.extract<std::vector<DynamicStruct>>();
``` 
But the current documentation does not make this fact clear.

In my opinion, ideally ` auto retBack = j.getValue<std::vector<DynamicStruct>>("testval");` would be valid but failing that the documentation for getValue should clarify it's limitations, and point users of DynamicStruct and Vectors (Which are valid vars per Varholder documentation) to the second method, which works fine.

(I'd like to note that I really appreciate what Poco provides, I'm just wanting to help future users of it who might run into this)

**Comment by leohard12** [comment]
2 millionaire 2 crypt for portfolio 10 millionaires me necessary financing soon crisis creation криптовалюты, she free of charge from confiscation women in индонезии forbidden opened account now all credits such situation on us, but if would was currency which all had access and can call her his currency not knowledge border and freedom from confiscation half population country but this 3 billion man does not have access to bank account and on appearance from perhaps will more, but 2023 on their all will new phone with application hard coin or another can create portfolio криптовалют procedure not complex hard coin or another currency they taking all titles to be called already hard my crypt will predict events on external market and адоптироваться in world policy they say what money spoil people but not pay attention as people spoil money hard coin place this end on this big stability than any from digital currencies this in beta version but this works initial capital 100000 $ on creation portfolio 1000000 $ this will allow create me prototype later need 12 million on one crypt this we together find major investors traditional banks and bank services stay in situ and not develop digital currency this train leaves you запрыгиваете in this or остаётесь on station i i will find another investors corporation opening interested soon bankruptcy end can invest
