### ISSUE TITLE
Issues building NetSSL_OpenSSL on windows using supplied binaries and CMake

### ISSUE THREAD

**Issue by bridgewaterrobbie** [pocoproject/poco#2795]
I was following the getting started process for Poco on windows, and went with the suggestion to do the following:
```
$ cd %POCO_BASE%
$ rmdir /s /q openssl
$ git clone https://github.com/pocoproject/openssl
```
And then tried to point to this directory using
`-DOPENSSL_ROOT_DIR= %POCO_BASE%\openssl\build` (Also tried some variations)
Doing this gave me the cmake error:
`Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found version "1.1.0")`
(Note: Not passing anything, or most other values would cause an additional error of missing the OPENSSL_INCLUDE)

In order to get the cmake build to work, I had to flatten the structure of the openssl directory, such that OPENSSL_ROOT_DIR points to a folder with an `include` and `lib` folder, with `lib` containing the contents of `openssl/build/win32/bin/debug` (Not lib).

This was a bit confusing, and I am sure that there is likely a better way to do this using only cmake, but the getting started guide does not currently make this clear. 

Thanks

EDIT: Setting the following also seems to work without flattening the directory structure:
```
set(OPENSSL_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/openssl/build/win32/bin/debug")
set(OPENSSL_INCLUDE_DIR" ${CMAKE_CURRENT_SOURCE_DIR}/openssl/build/include")
```
So having this as one possible configuration in the main CMakeLists.txt might resolve things.

**Comment by zosrothko** [comment]
Which Poco branch are you refering to?

**Comment by bridgewaterrobbie** [comment]
Master, with 1.9.4

**Comment by zosrothko** [comment]
With the branch 1.10.0, you don't need to setup up yourself the OpenSSL subsystem. Poco is using itq own prebuild OpenSSL and the CMake of poco-1.10.0 is taking care of getting the prebuild libraries and linking with.

**Comment by RaidersII** [comment]
Hi,
My branch is : Master, with 1.10.1

I have the same issue. Forcing POCO_DISABLE_INTERNAL_OPENSSL to OFF and ENABLE_NETSSL or ENABLE_CRYPTO to ON worked for me. I see in the CMakeList.txt that ENABLE_NETSSL/ENABLE_CRYPTO was initialized after this line of code (line 75) :
```
if((NOT POCO_DISABLE_INTERNAL_OPENSSL) AND (ENABLE_NETSSL OR ENABLE_CRYPTO OR (ENABLE_DATA_MYSQL AND MINGW)))
	include(UseEmbeddedOpenSSL)
endif()
```
The result was :
`-- Found OpenSSL: optimized;C:/poco/openssl/build/win32/bin/release/libcrypto.lib;debug;C:/poco/openssl/build/win32/bin/debug/libcryptod.lib (found version "1.1.0")`
