### ISSUE TITLE
build with cmake and modern c++ standards : not correctly handled

### ISSUE THREAD

**Issue by killerbot242** [pocoproject/poco#2797]
I wanted to create a pull request to add C++17, and as such I had a look at the current situation in CMakeLists.txt and CXX1x.cmake and there seems to be a lot of issues, according to me.
Could you clarify what was the intent.
For my analysis of : 
``
if (DISABLE_CPP11 OR DISABLE_CPP14)
    add_definitions(-DPOCO_DISABLE_CPP11)

    if (DISABLE_CPP14)
        add_definitions(-DPOCO_DISABLE_CPP14)
    endif()
else()
    # C++11/14 compiler flags
    include(CXX1x)
    check_for_cxx11_compiler(CXX11_COMPILER)

    # If a C++11 compiler is available, then set the appropriate flags
    if(CXX11_COMPILER)
        enable_cxx11()
        check_for_cxx14_compiler(CXX14_COMPILER)

        # If a C++14 compiler is available, then set the appropriate flags
        if(CXX14_COMPILER)
            enable_cxx14()
        endif()
    endif()
endif()
``
==> the disable is not correct, suppose that only disable C++14 was requested, it will nevertheless disable C++11. Which is not correct ?

What the following an intent : when you disable C++11 ==> no C++14 since once could look at that as a progression/extension. 
That;s actually what the else thing tries to do, if compiler support C++11 ==> 11 it is, and then lets see if it support C++14, then 14 it is. But that means that for disable it should be similar...

So in order to create a correct pull request I need to know what you had in mind.
I will already work on one, based upon this progressive approach.

Note also that there is : 
check_for_cxx11_compiler()
enable_cxx11_compiler()
and similar for 14

I think here again it is not correct, it gives the impression we CHECK (and then if possible we activate) so we combine 2 actions, but this gives the impression that the first check should not change anything, but it does in case of Clang, it already adjusts CMAKE_CXX_FLAGS to add the std library.

So either combine them  check_and_activate or have a real correct separation, where check does not modify anything.

What do you think ?

**Comment by killerbot242** [comment]
I had created a patch, but that one is, now it seems, only usable for the release 1.9.
On the develop branch, the world has changed a bit, so creating a new patch for that one.

How to deal with also a patch for the 1.9.x ?

**Comment by Chichele** [comment]
I got the similiar question...
In my case,I would like to only enable CPP11 and disable CPP14，but I found that I can't get that while I turn DISABLE_CPP11 off and set DISABLE_CPP14 on.With these settings, it just **TOTALLY** disable the both!!!
Am I wrong ? I need some help, pls.

**Comment by Bjoe** [comment]
I wanted to delete this about a year ago because there is a better way to set the compiler version via cmake `target_compile_features()`. But it was not possible because of the compile definitions `POCO_DISABLE_CPPxx` or `POCO_ENABLE_CPPxx` .... 

Now I see that is not any more used ... so I will try to remove this now :-) ....

@Chichele Did you try the release version 1.10.0 ?
