### ISSUE TITLE
sleep calls in threadpool cause the whole pool to sleep? 

### ISSUE THREAD

**Issue by CingKong** [pocoproject/poco#2798]
I was just messing the bundled in `HTTPTimeServer` sample when i found this interesting bug/feature?

`Poco::Net::HTTPServer` is supposed to work in a ThreadPool mode (it can take a ThreadPool reference as parameter in constructor, so i assume it is). and printing `Poco::Thread::currentTid()` inside `TimeRequestHandler::handleRequest()` makes me sure about that, it prints differnet results.

everything looked fine until i did `Poco::Thread::current()->sleep(10000);` for a thread inside `TimeRequestHandler::handleRequest()`, i opened tons of chrome tabs for testing, and seemed when this specific thread went into sleeping, every other threads slept too (all tabs were kept in loading state). and the server was not printing out thread ids anymore. Things worked smoothly in between this thread waking up and next sleep call.

Not sure whats the cuz of it. havent really read the Poco code yet. becuz this single `HTTPServer` involves too many other classes, its a nightmare for me as a beginner to dive into :/

OS is GNU/Linux, ide using Qt Creator (not using any Qt class in the test), Poco is a static 1.9.4 build built yesterday.

**Comment by obiltschnig** [comment]
If you put `Poco::Thread::current()->sleep(10000);` into your `handleRequest()` method, all request handler threads will go to sleep. It's not the sleep in one thread affecting the other threads, it's actually all your request handler threads going to sleep when they reach the `sleep()` call.

**Comment by CingKong** [comment]
Warning, stupid code incoming =P

i defined these two variables
```
std::unordered_map<unsigned long, int> threadIds;
Poco::Thread *theThread = nullptr;
```

and these are the `sleep` code in `TimeRequestHandler::handleRequest()`
```
    if (theThread)
    {
        if (Poco::Thread::current() == theThread)
        {
            std::cout << threadIds.size() << ": " << threadIds.at(Poco::Thread::currentTid()) << ": " << Poco::Thread::currentTid() << " is going to sleep" << std::endl;
            std::this_thread::sleep_for(std::chrono::seconds(10));
        }
    }
    else
        if (threadIds.size() == 3) // no4 thread
            theThread = Poco::Thread::current();

    threadIds.emplace(Poco::Thread::currentTid(), threadIds.size());

    std::cout << threadIds.size() << ": " << threadIds.at(Poco::Thread::currentTid()) << std::endl;
```
im sure the sleep calls only happen in the 4th thread

**Comment by CingKong** [comment]
```
HTTPStreamFactory::registerFactory();
FTPStreamFactory::registerFactory();
try
{
    URI uri(argv[1]);
    auto future = std::async(std::launch::async, [uri](){
        std::shared_ptr<std::istream> pStr(URIStreamOpener::defaultOpener().open(uri));
    });
    for (int i = 0; i < 100000; i++)
    {
        future = std::async(std::launch::async, [uri](){
            std::shared_ptr<std::istream> pStr(URIStreamOpener::defaultOpener().open(uri));
        });
    }
    future.get();
}
catch (Exception& exc)
{
    std::cerr << exc.displayText() << std::endl;
    return 1;
}
```

I also did this simple test. and the server stopped responding when "theThread" went into sleep too.
But here is the magic, if i start another test program at the same time, the server will become responsive again, regardless of  "theThread"'s status. i have totally no clue for this one either.

(Suffering from slow internet connection, cannot really upload video of it. )

**Comment by CingKong** [comment]
Couldn't draw much attention + the issue is most likely an environment issue + turning to NGINX + PHP for help, closing.
