### ISSUE TITLE
Compile error using XCode 10.0.1 on Mac OSX 10.14

### ISSUE THREAD

**Issue by muyushifang07** [pocoproject/poco#2806]
./configure --config=iPhone-clang-libc++ --no-tests --no-samples --omit=Data/MySQL,Data/ODBC --static --include-path=/usr/local/opt/openssl/include --prefix=/Users/suning/Desktop/Xcode-poco/armv7
make IPHONE_SDK_VERSION_MIN=7.0 POCO_TARGET_OSARCH=armv7 install

Termimal error log:

-lPocoJSONd -lPocoFoundationd  -ldl
ld: -bind_at_load and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/Users/suning/Desktop/poco-master/PageCompiler/bin/iPhoneOS/armv7/static/cpspcd] Error 1
make: *** [PageCompiler-libexec] Error 2
lxx-Mac-mini:poco-master suning$

**Comment by obiltschnig** [comment]
PageCompiler (and generally, all executables included in Poco) cannot be built for iOS; simply omit it from the build.
