### ISSUE TITLE
Failed to insert Poco::Nullable< Poco::Data::Date> data into MSSQL using ODBC

### ISSUE THREAD

**Issue by zhe-ma** [pocoproject/poco#2808]
Code:
```
  Poco::Nullable< Poco::Data::Date> date;
  session << "insert into student( birth) values(?)", use(date), now;
```

Error:
```

SQLExecute()
Requested SQL statement: insert into student( birth) values(?)
Native SQL statement: insert into student( birth) values(?)
: Connection:NetConn: 041B6E68
Server:Not applicable
===========================
ODBC Diagnostic record #1:
===========================
SQLSTATE = 22018
Native Error Code = 206
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Operand type clash: tinyint is incompatible with date

===========================
ODBC Diagnostic record #2:
===========================
SQLSTATE = 42000
Native Error Code = 8180
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared.
```

**Comment by rastocny** [comment]
Problem is caused by an invalid SQL data type in `SQLBindParameter` function. This cannot be solve without redesign of `Poco::Data::AbstractBinder` probably, which does not preserve c++ data type for NULL data. I hotfixed this issue by following changes https://github.com/rastocny/poco/commit/105e65815b9387b5957d01694ffe74ec172fd8fb

**Comment by aleks-f** [comment]
@matejk This looks like `Poco::Date`-specific, possibly also SQL server specific, problem. Other datatypes (including `Poco::DateTime`) seem to work fine for both inset and select. I will look into it

**Comment by aleks-f** [comment]
The problem was fixed (and too small in some cases) size of the binding. [This](https://github.com/pocoproject/poco/commit/8e958f685fc4f864a85190fa4a6058dc8be57465#diff-b05906cd3654122ddfe26e2773d624a1a7b3d4b4566b187a873436293626feacL381) fixed it.
