### ISSUE TITLE
Poco::Buffer: full on creation?

### ISSUE THREAD

**Issue by mikekaganski** [pocoproject/poco#2821]
Consider the code:

```
Poco::Buffer<char> buffer(200);
assert(buffer.empty());
```

This fails the assertion - because `Buffer::Buffer(std::size_t capacity)` at [include/Poco/Buffer.h:41](https://github.com/pocoproject/poco/blob/b95393dcc3640807838e8323b4e600e54d2e8116/Foundation/include/Poco/Buffer.h#L41) sets `_used` to the passed `capacity`. Any following `append` would increase the buffer size; and any read from `begin()` to `end()` would give leading garbage.

The same happens in the `Buffer::Buffer(T* pMem, std::size_t length)` telling "Supplied pointer is considered blank".

Additionally, calling `buffer.assign(nullptr, 0)` would not reset _used to 0 (but likely should) - it would be just a noop. `buffer.resize(0)`, however, would do that luckily; that's a workaround for now calling it after creation - but not a workaround for the case of `Buffer::Buffer(T* pMem, std::size_t length)`, where buffer doesn't own the buffer, and would throw. So following code would always throw:

```
char buf[200];
Poco::Buffer<char> buffer(buf, 200);
buffer.append("abcde", 5);
```

**Comment by obiltschnig** [comment]
Changing that behavior (independent of whether it's the right behavior) could break a lot of existing code, so we'll keep it as it is. A Buffer is not a string or a vector.

**Comment by dboyce-gh** [comment]
I agree with the OP on this - it's sub-optimal behaviour.  The documentation should at least state that `Buffer::Buffer(std::size_t capacity)` followed by `Buffer.append()` always results in a reallocation of the underlying buffer to accommodate the appended data.  `Buffer.append()` should also document that `Buffer::resize()` can be used beforehand to adjust the point at which data is appended with particular reference to `resize(0)` for re-using the buffer.

**Comment by NaourezALOUI** [comment]
**Exemple:** Poco::Buffer<char> buffer(2); -> the creation of a buffer with 50 size. (Poco transform **2** to its **code ASCII 50**) and reserve the memory with 50 bytes.
buffer.size(); -> 50.
buffer.clear(); buffre=0000000000000000000000000...... (50 times and not earse it all the memory.
buffer.resize(0); buffer empty
------------> **Solution:** Poco::Buffer<char> buffer(0);   (creation of an empty buffer with no need to resize it from the beginning).

**Comment by aleks-f** [comment]
> (Poco transform **2** to its **code ASCII 50**) and reserve the memory with 50 bytes.

@NaourezALOUI how exactly did you arrive at that conclusion? can you show a code that compiles and produces such result?

eg, what does this do for you:

```
Poco::Buffer<char> buffer(2);
std::cout << buffer.size() << std::endl;
```

**Comment by gelldur** [comment]
This also implies issue when using with `Poco::Net::Websocket` 

See: `WebSocketImpl::receiveBytes`

```
int WebSocketImpl::receiveBytes(Poco::Buffer<char>& buffer, int, const Poco::Timespan&)
{
	char mask[4];
	bool useMask;
	int payloadLength = receiveHeader(mask, useMask);
	if (payloadLength <= 0)
		return payloadLength;
	std::size_t oldSize = buffer.size();
	buffer.resize(oldSize + payloadLength);
	return receivePayload(buffer.begin() + oldSize, payloadLength, mask, useMask);
}
```

We can't use Websocket + Buffer (as reusable buffer) as it will always allocate extra memory. There is no way to set `_used` to 0 in Buffer.

----

Poco::Buffer ctor:
```
	Buffer(std::size_t length):
		_capacity(length),
		_used(length),
		_ptr(0),
		_ownMem(true)
		/// Creates and allocates the Buffer.
	{
		if (length > 0)
		{
			_ptr = new T[length];
		}
	}
```

`_used` is set to length now when we call `webSocket->receiveFrame`
```
int WebSocketImpl::receiveBytes(Poco::Buffer<char>& buffer, int, const Poco::Timespan&)
{
	char mask[4];
	bool useMask;
	int payloadLength = receiveHeader(mask, useMask);
	if (payloadLength <= 0)
		return payloadLength;
	std::size_t oldSize = buffer.size();
	buffer.resize(oldSize + payloadLength);
	return receivePayload(buffer.begin() + oldSize, payloadLength, mask, useMask);
}
```

`oldSize` will be: `_used`

**Comment by obiltschnig** [comment]
Added documentation describing the behavior. Closing.
