### ISSUE TITLE
Poco::Environment missing UTF8/wstring support on Windows

### ISSUE THREAD

**Issue by ngjermundshaug** [pocoproject/poco#2824]
Windows Username: **Sławomir** (pay attention to the ł)
User Folder: **C:\Users\Sławomir**

**Poco::Environment::get("LocalAppData")** returns **"C:\Users\Slawomir\AppData\Local"** 
It should return **"C:\Users\Sławomir\AppData\Local"**

**_wgetenv(L"LocalAppData")** returns **C:\Users\S**ł**awomir\AppData\Local** - which is correct.

Poco 1.9.0-release - Windows 10.

**Comment by obiltschnig** [comment]
Note: `Environment.cpp` does not `#include Environment_WIN32U.cpp` if `POCO_WIN32_UTF8` is `#define`d.
