### ISSUE TITLE
Cannot upload file to server

### ISSUE THREAD

**Issue by Spixmaster** [pocoproject/poco#2828]
Good day.
I write a Telegram Bot Api in C++ and for some functions I need upload via multipart/form-data. I already got in in libcurl until I noticed that curl has some serious issues with memory leaks. Poco fortunately does not.
I searched for hours now and I do not find a solution. Could anyone help me, please? The code is below. I reduced my original a little bit for better overview.

```
void HttpClient::send_post_req()
{
	Poco::Net::HTTPResponse::HTTPStatus http_response_code = Poco::Net::HTTPResponse::HTTPStatus::HTTP_BAD_REQUEST;;
	std::string http_response_txt;

	try
	{
		//uri
		Poco::URI uri(m_uri);
		std::string path_query = uri.getPathAndQuery();
		if(path_query.empty())
			path_query = "/";

		//request
		const Poco::Net::Context::Ptr context = new Poco::Net::Context(
			Poco::Net::Context::CLIENT_USE, "", "", "",
			Poco::Net::Context::VERIFY_NONE, 9, false,
			"ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
		Poco::Net::HTTPSClientSession session(uri.getHost(), uri.getPort(), context);
		session.setTimeout(Poco::Timespan(150L, 0L));
		Poco::Net::HTTPRequest req(Poco::Net::HTTPRequest::HTTP_GET, path_query, Poco::Net::HTTPMessage::HTTP_1_1);

			//html form
		Poco::Net::HTMLForm form(Poco::Net::HTMLForm::ENCODING_MULTIPART);
				//add each field
		form.addPart("photo", new Poco::Net::FilePartSource("/home/karl/Bilder/Hintergrundbilder/4k-wallpaper-bay-beach-2521619.jpg"));

		form.prepareSubmit(req);
		form.write(session.sendRequest(req));

		//response
		Poco::Net::HTTPResponse response;
		std::ostringstream oss;
		std::istream  &in = session.receiveResponse(response);
		http_response_code = response.getStatus();
		Poco::StreamCopier::copyStream(in, oss);
		http_response_txt = oss.str();
	}
	catch(std::exception &e)
	{
		std::cerr << e.what() << std::endl;
	}
}
```

**Comment by obiltschnig** [comment]
Couple of issues:

1. A file upload with a `GET` request won't work. Replace `HTTP_GET` with `HTTP_POST` when you create the `HTTPRequest` object.
2. You should also pass a filename and a correct MIME type ("image/jpeg") to the `FilePartSource`.

**Comment by Spixmaster** [comment]
@obiltschnig That was it! I thank you very much.
I apologize for this stupid error.

_Kurz auf deutsch: Meinen ausdrücklichsten Dank an Sie. Die Antwort war extrem schnell. Nebenher, mit Poco haben Sie mir eine Menge Arbeit erspart. Nachdem ich merkte, dass libcurl kontinuierlich bei jeder Anfrage Memory Leaks erzeugt, war die Suche nach einer Alternative nicht einfach, vor allem, wenn man boost::asio direkt ausschließt, weil es viel zu kompliziert ist._
