### ISSUE TITLE
Wrong cancelation of the fix: incorrect type of store name parameter in CertOpenStore API call into NetSSL_Win. Release 1.10.0

### ISSUE THREAD

**Issue by maxim-voronko** [pocoproject/poco#2834]
Wrong cancelation of the fix: incorrect type of store name parameter in CertOpenStore API call into NetSSL_Win.

I created next pull request: https://github.com/pocoproject/poco/pull/2773

Then the fix was commited to release 1.10.0:
https://github.com/pocoproject/poco/commit/0784665ce86d240841bd3dbaa5a5b2fe04bdfaba

But then fix was canceled by next commit:
https://github.com/pocoproject/poco/commit/5d455b6ed53ae16781ea5ab792b9c5219372dacb#diff-0343c296dab285073bef69fa12352b2c

The cancelation was wrong. 
The fact is that for CertOpenStore Windows API function does not exist CertOpenStoreW overload. According the documentation https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certopenstore  if CertOpenStore function uses 'CERT_STORE_PROV_SYSTEM' parametr the pvPara parameter must point to a Unicode string that contains the name of the system storage. But in the commit https://github.com/pocoproject/poco/commit/5d455b6ed53ae16781ea5ab792b9c5219372dacb#diff-0343c296dab285073bef69fa12352b2c
 ANSI string was used.
If you want to use ANSI string here, please use  CERT_STORE_PROV_SYSTEM_A parameter instead of CERT_STORE_PROV_SYSTEM.

We tested the issue. If we use 'CERT_STORE_PROV_SYSTEM'  and ANSI string we can not  use the Windows certificate store with the OPT_USE_MACHINE_STORE option enabled.
Now we use  'CERT_STORE_PROV_SYSTEM' parameter with Unicode string in our production and we can use  Windows certificate store with the OPT_USE_MACHINE_STORE option enabled.

**Comment by maxim-voronko** [comment]
Hello. In Release 1.10.0 changelog you mentioned:
- GH #2773: Fix the issue with incorrect type of store name parameter in CertOpenStore API call into NetSSL_Win

But actualy there is wrong. We have same bug with incorrect type of store name parameter. You can find the details above.

**Comment by obiltschnig** [comment]
Hopefully fixed for good now.
