### ISSUE TITLE
Using unicode strings with DirectoryIterator

### ISSUE THREAD

**Issue by florianschieder** [pocoproject/poco#2839]
Hello there,
when I'm initializing a `DirectoryIterator` with `DirectoryIterator it(string);` and `string` is of `std::wstring` or `const wchar_t*`, this leads to reading the "wrong" directory (example: I want to list L"C:\\Windows\\", but it lists contents of C:\ instead).
Using ANSI types (`std::string` or `const char*`) instead of unicode types, it's working as expected. This is alright if there are not any directory or file names with non-ASCII characters (accented vocals like á, ó etc. or the German ä, ö, ü, ....).
I am not sure if I messed up something with my Poco configuration. Is there any way to make `DirectoryIterator` work with unicode strings?

I will provide any further information to facilitate giving a descriptive answer, please excuse if the information I delivered aren't enough so far.

Thanks very much in advance for your support,
Florian

**Comment by Kvaz1r** [comment]
Under C++11 you can easily convert std::wstring to std::string and DirectoryIterator should works correct (I've tested it myself). 

```
        std::wstring string_to_convert = L"T:/Файлы";
        //setup converter
        std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> converter;
        //use converter (.to_bytes: wstr->str, .from_bytes: str->wstr)
        Poco::DirectoryIterator it(converter.to_bytes(string_to_convert));
```

Code was taken from [SO answer](https://stackoverflow.com/a/18374698).

**Comment by florianschieder** [comment]
Thank you very much for your answer, this works for me.
