### ISSUE TITLE
Android: Poco::BadCastException when extracting pointer from Poco::Dynamic::Var

### ISSUE THREAD

**Issue by Jabba** [pocoproject/poco#2844]
OS: Android 32-bit
LibPoco: version 1.8.0
NDK: 20.0.5594570

My company develops a cross platform library and using libpoco we have the code below working succesfully on Linux and Windows environments to parse a response from one of our servers.

I'm succesfully compiling LibPoco for Android using the following cmake command:

`cmake -H./ -B/root/poco-build -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/android/Sdk/ndk/20.0.5594570/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DANDROID_ABI=armeabi-v7a -DENABLE_DATA_SQLITE=False -DENABLE_NETSSL=True -DOPENSSL_CRYPTO_LIBRARY=/root/${OPENSSL_DIR}/libcrypto.so -DOPENSSL_SSL_LIBRARY=/root/${OPENSSL_DIR}/libssl.so -DOPENSSL_INCLUDE_DIR=/root/${OPENSSL_DIR}/include`

and simply build the project using `ninja`.

During runtime on Android, however, I encounter the following issue:

```
Poco::Dynamic::Var result;
  try
  {
    result = parser.parse( text );
  }
  catch( Poco::JSON::JSONException )
  {
    throw std::runtime_error( "Error parsing JSON" );
  }

  // BadCastException is thrown below.
  Poco::JSON::Object::Ptr result_ptr = result.extract<Poco::JSON::Object::Ptr>(); 
```

From ADB I get the following message:
```
11-26 10:17:53.471 19599 19599 F libc    : /usr/local/google/buildbot/src/android/ndk-release-r20/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: 
abort_message: assertion "terminating with uncaught exception of type Poco::BadCastException" failed
```

Before this code a form is submitted using `Poco::Net::HTMLForm` and the response is a string in JSON format which is stored in `text`; I've verified that Poco can succesfully submit the form to our server and the response string is correctly formatted.

In the code snippet, parsing the `text` string does not throw any exception but when we try to extract the pointer from the `Poco::Dynamic::Var result` we get a `BadCastException`. 

I've read in an old issue about problems related to `ParserHandler` and `arm64` builds which a compiler flag could fix, but adding the compiler flag didn't help me either: https://github.com/pocoproject/poco/issues/1275

**Comment by Jabba** [comment]
I've tried building the project both for `armeabi-v7a` and `arm64-v8a` targets, both builds fail with the `BadCastException`.

**Comment by Jabba** [comment]
We've done some more investigation with the following snippet:

```
  Poco::Dynamic::Var result;
  try
  {
    result = parser.parse( text );
  }
  catch( Poco::JSON::JSONException )
  {
    throw std::runtime_error( "Error parsing JSON" );
  }

  // Lets manually compare the types
  Poco::Dynamic::VarHolder* pHolder = auth_result.content();
  if (pHolder) {
      __android_log_print(ANDROID_LOG_VERBOSE, "JNI",  "%s", pHolder->type().name() );
      __android_log_print(ANDROID_LOG_VERBOSE, "JNI",  "%s", typeid(Poco::JSON::Object::Ptr).name() );
      __android_log_print(ANDROID_LOG_VERBOSE, "T1 == T2?",  "%d", pHolder->type() == typeid(Poco::JSON::Object::Ptr) );
  }

  // BadCastException is thrown below.
  Poco::JSON::Object::Ptr result_ptr = result.extract<Poco::JSON::Object::Ptr>(); 

```

Which generates the following log output:

```
11-26 18:13:30.674 27544 27544 V JNI: N4Poco9SharedPtrINS_4JSON6ObjectENS_16ReferenceCounterENS_13ReleasePolicyIS2_EEEE
11-26 18:13:30.674 27544 27544 V JNI: N4Poco9SharedPtrINS_4JSON6ObjectENS_16ReferenceCounterENS_13ReleasePolicyIS2_EEEE
11-26 18:13:30.674 27544 27544 V T1 == T2?: 0
11-26 18:13:30.685 27544 27544 V JNI BadCastException: what=Bad cast exception msg=Can not convert [ERRFMT] to [ERRFMT].
```

It fails on comparison of two similar objects, also like mentioned in issue #1275.

**Comment by Jabba** [comment]
Is there anything else I can provide? 
Its a big issue in our cross-platform development.. currently the only hope we have is to upgrade to `1.9.4` and hope it works there, but this is a big amount of extra work, and there is no guarantee.

**Comment by aleks-f** [comment]
Well, this looks like some awkward platform-specific thing. There's always the [commercial support](https://pocoproject.org/support.html) option.

**Comment by jngd** [comment]
@Jabba what is the type of "text" std::istream or std::string?

**Comment by Jabba** [comment]
@jngd sorry for not seeing this earlier, but its of type `std::string`
