### ISSUE TITLE
Poco::format function is invalid by ndk-26

### ISSUE THREAD

**Issue by wjyan1985** [pocoproject/poco#2845]
Poco::format function is invalid by ndk-26
throught trace, I found ostringstream is not runs；
for example:
std::ostringstream os;
std::string test = "ffff";
os << test;

then os.str() is empty

**Comment by wjyan1985** [comment]
Anybody here?

**Comment by obiltschnig** [comment]
You have to be more specific what the actual issue is.

**Comment by wjyan1985** [comment]
Poco::format function is invalide 
poco compile by ndk-r20

the function invalide is ：ostringstream problem

for example:
std::ostringstream os;
std::string test = "ffff";
os << test;

then os.str() is empty

**Comment by wjyan1985** [comment]
@obiltschnig

**Comment by obiltschnig** [comment]
I don't think this is something we can fix. Not much we can do if your C++ standard library is broken.

**Comment by wjyan1985** [comment]
may be 
thank u

**Comment by Bjoe** [comment]
I assume with NDK you mean the Android NDK? There are still exists also some other NDK on some other embedded platforms ....

And when it is android, with which API level/android platform you are compile your app?

**Comment by wjyan1985** [comment]
NDK my mean is Android NDK;
Application.mk

APP_STL := c++_shared
APP_PLATFORM := android-26
APP_CPPFLAGS := -frtti -std=c++11
APP_CPPFLAGS += -fexceptions
APP_ABI := armeabi-v7a
APP_MODULES := Message

but  APP_STL use c++_static  which is ok

**Comment by Bjoe** [comment]
Hm ok, now I got it. NDK with API level 26 ... let me see if I found something. Give me some time, I will come back if I found the root cause.

**Comment by wjyan1985** [comment]
thanks

**Comment by Bjoe** [comment]
Here my result:

I build poco library for android with following parameters:
Branch: `develop`
```
ANDROID_ABI:STRING=armeabi-v7a                                                                                                                                                               
ANDROID_CPP_FEATURES:STRING=exceptions rtti                                                                                                                                                  
ANDROID_PLATFORM:STRING=android-26                                                                                                                                                           
ANDROID_STL:STRING=c++_static      
                                                                                                                                                          
```
NDK revision: 20.0.5594570
Compiler: `/opt/androidSdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++`

Execute Foundation test: testFormat
On my Samsung SM-G930F with Android 8

Test are passed.

**Comment by Bjoe** [comment]
The same with: `c++_shared` also passed

**Comment by wjyan1985** [comment]
if use parameter -std=c++11  to compile
then run 

that is ok?
