### ISSUE TITLE
Poco::Net::FTPClient support for MODE Z compression?

### ISSUE THREAD

**Issue by throstur62** [pocoproject/poco#2856]
Hi,
Does Poco::Net::FTPClient support Zlib compressoin?
At least I can not find any documentation for it nor anything in the source that indicates so.

If not, are there any plans addint it?
Best regards,
  TJ

**Comment by obiltschnig** [comment]
Currently not supported. If you want to give it a shot implementing it, we'll happily accept it, though. Unfortunately, no time at the moment to do it myself.
