### ISSUE TITLE
WinService timeout

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#2858]
I have a short question on the `WinService` class. I have noticed that the `start` Method uses a Timeout to check if the Service was started successfully. 
The `stop` Method does not. Should the Method also use a timeout or should there a second `stop` Method added with the use of a timeout like in the `start`? 
If so there should also be a `start` Method without the timeout I think but how should that Method be named?

Maybe I could add this to the class depending on the way you think it's the best.

**Comment by obiltschnig** [comment]
Maybe it could make sense. I don't really know for sure, though, as I wrote that code more than 10 years ago.
