### ISSUE TITLE
SessionImpl begin

### ISSUE THREAD

**Issue by petko** [pocoproject/poco#2864]
I want to start a SQLite transaction in `Session` using `BEGIN EXCLUSIVE`. However in `SessionImpl` `begin` is hard-coded to use `BEGIN DEFERRED` and there is currently no way to change that.

Would you accept a pull request with a function, which allows to specify the transaction mode used by the `Session` object? If so, what would be the proposed API for doing it in order it to be consistent with the rest of the POCO library?

**Comment by aleks-f** [comment]
It would be best done using a session property. for an example, see how `connectionTimeout` property is [done](https://github.com/pocoproject/poco/blob/poco-1.10.1/Data/SQLite/src/SessionImpl.cpp#L60)
