### ISSUE TITLE
HTTPServerParams for websocket

### ISSUE THREAD

**Issue by danielstock** [pocoproject/poco#2868]
what's the different between timeout and keepalivetimeout?
                ///   - timeout:              60 seconds
		///   - keepAlive:            true
		///   - maxKeepAliveRequests: 0
		///   - keepAliveTimeout:     10 seconds

the definition comments are just the same:
void setTimeout(const Poco::Timespan& timeout);
		/// Sets the connection timeout for HTTP connections.
void setKeepAliveTimeout(const Poco::Timespan& timeout);
		/// Sets the connection timeout for HTTP connections.
		

BTW, i'm using Poco version 1.8.1

**Comment by obiltschnig** [comment]
setKeepAliveTimeout() sets the keep-alive timeout for persistent connections. Docs updated for poco-1.10.0
