### ISSUE TITLE
Poco::Net::Websocket throws “SSL connection unexpectedly closed”

### ISSUE THREAD

**Issue by abhiarora4** [pocoproject/poco#2870]
I am using `Poco` Websocket for my project. I am getting exception "SSL connection unexpectedly closed" sometimes when I try to read Frames with `receiveFrame`.

Initially I was thinking there could be some issue with the Server. However, I came across [this link][1]. It looks like `Poco` could have some issues/bugs and that could be reason for this exception. I am unable to move forward with this issue in my mind. Below is the code part that sometimes throws that exception. 

        Poco::Net::HTTPSClientSession httpsClient(uri.getHost(), uri.getPort(), getSSLContext());
        Poco::Net::HTTPRequest request(Poco::Net::HTTPRequest::HTTP_GET, "/", Poco::Net::HTTPMessage::HTTP_1_1);
        Poco::Net::HTTPResponse response;

        httpsClient.setTimeout(Poco::Timespan(8000 * 1000));
        append_headers(request);

        regFailCount_ = 0;
        // TODO: Use shared_ptr
        webSocket_ = new Poco::Net::WebSocket(httpsClient, request, response);

     while (true) {
     int len = 0;
     webSocket_->setReceiveTimeout(Poco::Timespan(1000));    // 1 millisecond
     if ((len = webSocket_->receiveFrame(buffer, sizeof(buffer), flags)) < 0)
         continue;
     // Process the buffer
     }

**Poco Version is 1.7.8**

  [1]: https://github.com/pocoproject/poco/issues/1160

**Comment by mikallos** [comment]
Maybe related to #2832 ?

**Comment by tanmay2798** [comment]
@abhiarora4 did you solve this issue?
