### ISSUE TITLE
modern/better cmake in 1.9.5 ?

### ISSUE THREAD

**Issue by killerbot242** [pocoproject/poco#2873]
While looking at the CMakeLists.txt (in order to improve them) I noticed already nice improvements being present, which are not in 1.9.4 (Eg : the namespaced aliases like Poco::Foundation). Will this come in 1.9.5 please ?

I would also suggest to using the proposed naming conventions usggested in the "Professional CMake" book in order to avoid name conflicts. Because source consumption of the libaries is a very important use case (FetchContent...)
For example in our codebase we were 1 character short for a name clash, we have a "Util" library, and poco has "Utils".
The suggestion in the book is to prefix with an underscore the libraries, something like "Poco_Foundation", with alias "Poco::Foundation".

What do you think ?

I can always try to help out.

**Comment by Bjoe** [comment]
Poco version 1.10.0 is using now the modern cmake style ... :-)

> The suggestion in the book is to prefix with an underscore the libraries, something like "Poco_Foundation", with alias "Poco::Foundation".

Hm, should be possible ... I will try this, let me see......

Btw. I also updated in [hunter the poco version](https://hunter.readthedocs.io/en/latest/packages/pkg/PocoCpp.html) ... maybe this is also an option :-)
