### ISSUE TITLE
Cannot extract .zip file 

### ISSUE THREAD

**Issue by tamndse62381** [pocoproject/poco#2877]
I cannot extract zip file after I zipped it Poco::Zip::Compress. Here is my situation :
- Compress by Poco -> Decompress by Winrar or 7z = Success
- Compress by Winrar or 7z -> Decompress by Poco = Success
- Compress by Poco -> Decompress by Poco = Unsuccess 
Here is my Compress code :

	if (tempFile.exists())
	{
		set <string> extensionsSet;
		std::ofstream outStream(target, ios::binary);

		Poco::Zip::Compress compress(outStream, false, false);
		for (int i = 0; i < extensions.Size(); i++) {
			string ext = std::dynamic_pointer_cast<String>(extensions.operator[](i))->GetPrimitive();
			ext = "^" + ext + "$";
			findAndReplaceAll(ext, "*", ".+");
			findAndReplaceAll(ext, "?", ".");
			extensionsSet.insert(ext);
		}
		compress.setStoreExtensions(extensionsSet);//set extensions List 
		if (tempFile.isDirectory())
		{
			Poco::Path sourceDir(sourcePath.string());
			sourceDir.makeDirectory();
	        
     compress.addRecursive(sourceDir,Poco::Zip::ZipCommon::CompressionMethod::CM_AUTO,
				Poco::Zip::ZipCommon::CL_NORMAL, false);
		}
		else if (tempFile.isFile())
		{
			Poco::Path path(tempFile.path());
			compress.addFile(path, path.getFileName(), Poco::Zip::ZipCommon::CompressionMethod::CM_AUTO,
				Poco::Zip::ZipCommon::CL_NORMAL);
		}
		compress.close(); // MUST be done to finalize the Zip file
		outStream.close();
	}

And my Decompress code : 

fs::path sourcePath = fs::path(source);
		std::ifstream inp(sourcePath.string(), ios::binary);
		fs::path targetPath = fs::path(target);
		Poco::Path targetDir(targetPath.string());
		Poco::Zip::Decompress dec(inp, targetDir, false, true);
		// if an error happens invoke the ZipHandlingLib::onDecompressError method
		dec.EError += Poco::Delegate<UnzipStruct, std::pair<const Poco::Zip::ZipLocalFileHeader, const std::string>>(this, &UnzipStruct::onDecompressError);
		dec.decompressAllFiles();
		dec.EError -= Poco::Delegate<UnzipStruct, std::pair<const Poco::Zip::ZipLocalFileHeader, const std::string>>(this, &UnzipStruct::onDecompressError);
		inp.close();

The exception I often got is AssertViolationException, I wonder why because my Decompress function can extract other zip files that were compressed by Winrar or 7z but not Poco instead. Thanks in advanced.

**Comment by KevDi** [comment]
What Version of Poco do you use?
Does the Exception happens when you try to decompress a single file or folder?
I just gave it a try and for me it works to compress a file with Poco and then decompress it again.

**Comment by tamndse62381** [comment]
> What Version of Poco do you use?
> Does the Exception happens when you try to decompress a single file or folder?
> I just gave it a try and for me it works to compress a file with Poco and then decompress it again.
> Did you try to debug your code to see on which line the exception is thrown?

Thanks for replies, I was actually a bug from Poco 1.9.0 and was already resolved when I update to version 1.9.4.
