### ISSUE TITLE
Can ProGen be used in the [poco-1.4.2p1-all] version? 

### ISSUE THREAD

**Issue by OneTop4458** [pocoproject/poco#2878]
Hello
My project is currently using the poco-1.4.2p1-all version.
I am going to proceed with the migration to Visual Studio 2008 -> 2017.

First of all, I want to upload the version of the Poco library, but the project is too big and there are many customers, so I think it will be difficult.
[ poco-1.4.2p1-all ] doesn't officially support Visual Studio 2017 compilation, but can I create a Visual Studio 2017 sln file for [po-1.4.2p1-all ] if I use ProGen like the latest version?

I'd appreciate it if you could let me know if there's any good way.

**Comment by zosrothko** [comment]
Why don't you switch to the latest release poco-1.9.4 ?

**Comment by OneTop4458** [comment]
I'd like to switch to the latest release, but the project I'm using is too big and won't let the top of the company go because of cost, manpower, and time problems.

**Comment by Kvaz1r** [comment]
Modern VS should be able properly update project files from old version. You can open old file and let VS convert it.
