### ISSUE TITLE
Handle negative DST offset

### ISSUE THREAD

**Issue by petermarko** [pocoproject/poco#2882]
Poco handles DST as +3600s, however there exists also negative DST offset (-3600s).
Example is Europe/Dublin timezone, where poco erroneously returns offset 7200 instead of 0 during winter with recent tzdata/tzinfo package under Linux.

This line of code causes this behaviour:
https://github.com/pocoproject/poco/blob/poco-1.9.4-release/Foundation/src/Timezone_UNIX.cpp#L79

For background on this, see https://github.com/tzinfo/tzinfo/issues/95#issuecomment-479639994

**Comment by obiltschnig** [comment]
Proper fix would be writing code to read the `zoneinfo` database. 

Intermediate fix could be detecting that specific timezone (`IST`?) and adjusting the offset accordingly, but this would break things if an older `zoneinfo` database is used.

**Comment by obiltschnig** [comment]
See https://github.com/pocoproject/poco/commit/6aa29ade172818db8095a3f2af441ec6ecdbf569

**Comment by obiltschnig** [comment]
Proposed fix apparently breaks Windows, so need to rework.
