### ISSUE TITLE
SocketImpl::bind --> bind wrong config

### ISSUE THREAD

**Issue by AdrianGersbach-EH** [pocoproject/poco#2892]
Until v1.9.0 SocketImpl::bind used to look like this
void SocketImpl::bind(const SocketAddress& address, bool reuseAddress)
{
	bind(address, reuseAddress, **true**);
}

Starting with v1.9.1 SocketImpl::bind changed the true to reuseAddress.
void SocketImpl::bind(const SocketAddress& address, bool reuseAddress)
{
	bind(address, reuseAddress, **reuseAddress**);
}

I think this is incorrect since bind6 still uses true for reusePort.
void SocketImpl::bind6(const SocketAddress& address, bool reuseAddress, bool ipV6Only)
{
    bind6(address, reuseAddress, **true**, ipV6Only);
}

**Comment by obiltschnig** [comment]
related to #2616

**Comment by AdrianGersbach-EH** [comment]
As I understand it you have now changed 

void SocketImpl::bind6(const SocketAddress& address, bool reuseAddress, bool ipV6Only)
{
**from:**
bind6(address, reuseAddress, **true**, ipV6Only);
**to:**
bind6(address, reuseAddress, **reuseAddress**, ipV6Only);
}

In my post or bug report I was wondering if bind for IPv4 should be changed
void SocketImpl::bind(const SocketAddress& address, bool reuseAddress)
{
**from:**
bind(address, reuseAddress, **reuseAddress**);
**to:**
bind(address, reuseAddress, **true**);
}

Starting with POCO v1.9.1 I am no longer able to start multiple instances of Poco::Net::RemoteSyslogListener using the same port. If I set the reusePort to true in e.g. POCO v1.9.4 it works again.
