### ISSUE TITLE
Add support for SameSite attribute in HTTPCookie for Poco 1.9

### ISSUE THREAD

**Issue by gyee-penguin** [pocoproject/poco#2896]
This has already been added to Poco 1.10.  Can this support be added to Poco 1.9 for products that are dependent on earlier versions of GCC?  CentOS 7 build environments come with GCC 4.

**Comment by obiltschnig** [comment]
I don't plan an official 1.9.5 release for now as I'm busy with other things, but I can create a 1.9.5 branch on GitHub for eventual backporting.

**Comment by obiltschnig** [comment]
I've created a poco-1.9.5 branch. Feel free to send a PR.

**Comment by gyee-penguin** [comment]
Thanks.  Unfortunately the SameSite attribute support is going to be needed on Feb 4, when Chrome 80 is released and we can not wait until after that date to find a solution.

**Comment by obiltschnig** [comment]
I'd suggest do the backporting and send a pull request against poco-1.9.5.

**Comment by gyee-penguin** [comment]
Understood.  I will submit a pull request against poco-1.9.5.

**Comment by gyee-penguin** [comment]
I've submitted a pull request against 1.9.5 with a cherry-pick of 4ec5d35060b3d4eae1a31dfb27fb2f4bd0fd94df.

**Comment by gyee-penguin** [comment]
Thank you for the fast response!
