### ISSUE TITLE
poco 1.10/ NetSSL / openssl < 1.1 : default server usage changed (compare to 1.9.4)

### ISSUE THREAD

**Issue by SpitchAG** [pocoproject/poco#2898]
with poco.1.9.4 with old openssl stack (=1.0.x or less), when initializing a SSL Server context with TLS_SERVER_USAGE, openssl stack was initialized with flexible 'all versions' method (tls_server_method())
  -> you could connect TLS1.2 clients,

with 1.10 this method is now replaced with lot more restrictive TLSv1_server_method() so you cannot even connect tls1.2 clients, which doesn't look good.

furthermore, when setting requireMinimumProtocol() with TLS1.3, no exception is thrown (which is incoherent with the fact that when initializing the context with usage=TLS_1.3 you do receive Invalid arg exception.

**Comment by obiltschnig** [comment]
@SpitchAG please review the fix in 81624a2

**Comment by SpitchAG** [comment]
we tried the patch it looks ok,
we noticed that SSLv3 is not surported when setting the Context::Usage to TLS_SERVER_USE (ion 1.9.4 we observe the same). I guess this is as expected ....?
