### ISSUE TITLE
LocalDateTime::timestamp() not converting to UTC

### ISSUE THREAD

**Issue by martyparty86** [pocoproject/poco#2899]
The following code asserts:
```
Poco::LocalDateTime originalLocalDateTime( 2020, 1, 30 );
Poco::Timestamp timestamp = originalLocalDateTime.timestamp();
Poco::LocalDateTime newLocalDateTime = timestamp;
assert( originalLocalDateTime == newLocalDateTime );
```
According to the headerfile of `Poco::Timestamp`, timestamps are in UTC, see [Timestamp documentation](https://pocoproject.org/docs/Poco.Timestamp.html). If a `Timestamp` can be created from a `LocalDateTime`, and a `LocalDateTime` can be created from a `Timestamp`, the expected behavior for the library is to convert between UTC and local time accordingly.

Poco: 1.9.4

**Comment by micheleselea** [comment]
Did you try?
`Poco::Timestamp timestamp = originalLocalDateTime.utc().timestamp();`

**Comment by martyparty86** [comment]
Yes, that "works". This report is more about the semantics of *Timestamps are UTC (Coordinated Universal Time) based and thus independent of the timezone in effect on the system.* from the documentation in the Timestamp header. Which isn't true if the timestamp is created with LocalDateTime::timestamp().
