### ISSUE TITLE
POCO_NO_AUTOMATIC_LIBS does not work anymore?

### ISSUE THREAD

**Issue by MrHacky** [pocoproject/poco#2901]
We're linking to a static (POCO_STATIC=ON) poco library we compile ourselves. We use POCO_NO_AUTOMATIC_LIBS when compiling our code and using absolute paths to link the poco .lib files we use. Since 2637aa6610ae6a446892725611cdd77b486e10e5 this broke because we get an error about linking to "pocofoundationmd.lib" which can't be found, so it seems POCO_NO_AUTOMATIC_LIBS is broken somehow.

I'm guessing this happens because poco itself is compiles without POCO_NO_AUTOMATIC_LIBS, so the .lib files depending on libfoundation now contain a link reference to "pocofoundationmd.lib", which gets pulled in when linking to those .lib files, even when POCO_NO_AUTOMATIC_LIBS is defined...

**Comment by Bjoe** [comment]
Hm, I remove it ... I can not yet remember why I remove it, but as the [CHANGELOG](https://github.com/pocoproject/poco/blob/poco-1.10.0/CHANGELOG#L2243) said: 
> To disable this, compile POCO with the preprocessor symbol POCO_NO_AUTOMATIC_LIBS #define'd
>  (see Poco/Foundation.h and Poco/Config.h)

Is that what you mean with:
> We use POCO_NO_AUTOMATIC_LIBS when compiling our code

Or how you compile poco with POCO_NO_AUTOMATIC_LIBS ?

**Comment by MrHacky** [comment]
> Is that what you mean with:
> 
> > We use POCO_NO_AUTOMATIC_LIBS when compiling our code
> 
> Or how you compile poco with POCO_NO_AUTOMATIC_LIBS ?

No, what i mean here is when we compile our application, we define POCO_NO_AUTOMATIC_LIBS (and it will be picked up by the Foundation.h and Config.h headers when we include them).

So when compiling poco, POCO_NO_AUTOMATIC_LIBS is indeed not defined anymore due to 2637aa6610ae6a446892725611cdd77b486e10e5. What would be the recommended way to enable this again then? I didn't find any cmake variable for this i can pass to cmake.

**Comment by pcipriano** [comment]
I had the same issue, but the problem for me was the OpenSSL libraries being included in Crypto library. After many attempts the solution was to build POCO with Cmake using a tool chain file:
-DCMAKE_TOOLCHAIN_FILE="Path to file"

And in that file only have the contents:
add_compile_definitions(POCO_NO_AUTOMATIC_LIBS)

Ideally this should be configurable with an option in the POCO Cmake files.
