### ISSUE TITLE
Error while compiling HTTPFormServer.cpp in Net folder.

### ISSUE THREAD

**Issue by rohanvivek** [pocoproject/poco#2903]
I'm trying to compile HTTPFormServer.cpp program in Net folder using command "g++ -o HTTPFormServer HTTPFormServer.cpp -lPocoNet" and I'm getting error as

" /usr/bin/ld: /tmp/cc2jMKJL.o: undefined reference to symbol '_ZN4Poco20NullPointerExceptionD1Ev'
//usr/local/lib/libPocoFoundation.so.70: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status"

Help me in running this particular program.

**Comment by aleks-f** [comment]
Add -lPocoFoundation

**Comment by rohanvivek** [comment]
> Add -lPocoFoundation

After using your suggested term 
"g++ -o HTTPFormServer HTTPFormServer.cpp -lPocoFoundation"
I'm getting another error as 

"/tmp/ccw80jmR.o: In function `main':
HTTPFormServer.cpp:(.text+0x51): undefined reference to `Poco::Util::ServerApplication::run(int, char**)'
/tmp/ccw80jmR.o: In function `Poco::Net::Impl::IPv4SocketAddressImpl::host() const':
HTTPFormServer.cpp:(.text._ZNK4Poco3Net4Impl21IPv4SocketAddressImpl4hostEv[_ZNK4Poco3Net4Impl21IPv4SocketAddressImpl4hostEv]+0x28): undefined reference to `Poco::Net::IPAddress::IPAddress(void const*, unsigned int)'
/tmp/ccw80jmR.o: In function `Poco::Net::Impl::IPv6SocketAddressImpl::host() const':
HTTPFormServer.cpp:(.text._ZNK4Poco3Net4Impl21IPv6SocketAddressImpl4hostEv[_ZNK4Poco3Net4Impl21IPv6SocketAddressImpl4hostEv]+0x2e): undefined reference to `Poco::Net::IPAddress::IPAddress(void const*, unsigned int, unsigned int)'
/tmp/ccw80jmR.o: In function `Poco::Util::Application::instance()':
HTTPFormServer.cpp:(.text._ZN4Poco4Util11Application8instanceEv[_ZN4Poco4Util11Application8instanceEv]+0x7): undefined reference to `Poco::Util::Application::_pInstance'"






Can you please specify where and what command to use to run this program

**Comment by KevDi** [comment]
I think you also need to add `-lPocoUtil`

**Comment by rohanvivek** [comment]
> I think you also need to add `-lPocoUtil`

I tried this getting the same error

"/usr/bin/ld: /tmp/cc2Xifa2.o: undefined reference to symbol '_ZN4Poco20NullPointerExceptionD1Ev'
//usr/local/lib/libPocoFoundation.so.70: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status"

please help!!

**Comment by aleks-f** [comment]
> After using your suggested term
> "g++ -o HTTPFormServer HTTPFormServer.cpp -lPocoFoundation"
> I'm getting another error as

I did not say "remove -lPocoNet". Obviously you will need -lPocoUtil as well. But, before doing anything, you should [understand the basics of building software](https://lmgtfy.com/?q=order+of+libraries+for+the+linker).

**Comment by rohanvivek** [comment]
Thank you, sir, for your help
 Actually I'm an intern and got to work on this library.
