### ISSUE TITLE
Support environments without hardware floating point

### ISSUE THREAD

**Issue by mauropasse** [pocoproject/poco#2904]
Hi! When crosscompiling to mips/musl, I get this error:
```
poco_vendor/poco-1.8.0.1-release-prefix/src/poco-1.8.0.1-release/Foundation/include/Poco/FPEnvironment_C99.h:34:30: error: 'FE_DOWNWARD' was not declared in this scope
   FP_ROUND_DOWNWARD_IMPL   = FE_DOWNWARD,
```
This is fixed with this patch: 
https://sources.debian.org/patches/poco/1.9.0-5/0006-fp-support-environments-without-hardware-floating-po.patch/

Do you think you can apply and merge it for future releases?

**Comment by aleks-f** [comment]
Best to send a pull request
