### ISSUE TITLE
Append new file to existed zip file

### ISSUE THREAD

**Issue by tamndse62381** [pocoproject/poco#2905]
```
//Then I append it to the existed file
Poco::Zip::ZipManipulator manipulator(target, true);
for (auto &file : files) {
manipulator.addFile(target, file.generic_u8string(),
Poco::Zip::ZipCommon::CompressionMethod::CM_DEFLATE,
Poco::Zip::ZipCommon::CL_NORMAL);
}
manipulator.commit();// This is where I get the error
```
I'm using Poco::Zip::ZipManipulator to append new files to the existed zip file which I created earlier. 

>     const std::string & zipPath -- is it the directory of my existed zip file?
>     e.g : C:/Users/Emotive/Desktop/lua.zip
>     const std::string & localPath -- is it the directory of my new file? 
>     e.g : C:/Users/Emotive/Desktop/lua/gas.txt

I wonder if I used this correctly, I have tried several ways but none of them successfully append new files to the zip. I'm using Window OS, Visual Studio 2017 and poco 1.9.4, hope someone can help me up here. Thanks in advance.

**Comment by KevDi** [comment]
@tamndse62381 
This code works for me:

```
int main()
{
    Poco::File zip{ "D:\\test.zip" };
    Poco::Zip::ZipManipulator zm(zip.path() , false);

    Poco::Path pathToFile{ "D:\\newFile.txt" };
    
    zm.addFile(pathToFile.getFileName(), pathToFile.toString());
    auto archive = zm.commit();
}
```

The arguments of the Function `addFile` are the following:
```
zipPath = Path/Name of the File inside the Zip
localPath = Path to the File which should be added to the Zip
```

**Comment by tamndse62381** [comment]
@KevDi Thanks, I will give it a try.
