### ISSUE TITLE
Memory leak in Poco::Net::SecureSocketImpl::connectSSL(bool)

### ISSUE THREAD

**Issue by psekara** [pocoproject/poco#291]
System: Mac OS X 10.8.4
Poco: poco-1.4.6p1-all
Using libraries: libssl.0.9.8.dylib, libcrypto.0.9.8.dylib

Call Tree:
Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest &)
  Poco::Net::HTTPClientSession::reconnect()
    Poco::Net::HTTPSClientSession::connect(Poco::Net::SocketAddress const &)
      Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const &)
        Poco::Net::SecureStreamSocketImpl::connect(...)
          Poco::Net::SecureSocketImpl::connect(...)
            Poco::Net::SecureSocketImpl::connectSSL(bool)
              ssl23_connect (libssl.0.9.8.dylib)
  and other system library calls

**Comment by aleks-f** [comment]
Possibly due to [this](https://github.com/pocoproject/poco/commit/03deea59c5b1276f012968395640b6b472250f0b). Very old issue, closing.
