### ISSUE TITLE
Poco Logger crashes if String Value contains percentage (%)

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#2913]
In Version `1.10` this Code crashs:

```cpp
std::string example{"This is a %s message"};
poco_information_f1(logger, "Log Message: %s", example);
```

It seems that the function `format` in `Format.cpp` appends the string but continues to iterate over it. So it will detect the % inside the string and tries to replace them. 
In Poco Version 1.9 the code runs without any problems

**Comment by KevDi** [comment]
@obiltschnig do you know if there is a workaround or fix for this issue?

**Comment by obiltschnig** [comment]
What platform and compiler? Seems to work fine at least on macOS and Windows, with poco-1.10.1.

**Comment by KevDi** [comment]
I used Poco-1.10.0 on Windows 10. 
I build an application in 32Bit and 64Bit Mode using Visual Studio 2019

**Comment by KevDi** [comment]
@obiltschnig i think i have found the error.
Let's assume we are using the same code as i wrote in my initial comment:

```
std::string example{"This is a %s message"};
poco_information_f1(logger, "Log Message: %s", example);
```

The following steps now happens:

The Macro call looks like this (taken from `Logger.h`):

```
if ((logger).information()) (logger).information(Poco::format((fmt), (arg1)), __FILE__, __LINE__); else (void) 0
```

Here the first call to `Poco::format` is made. This call works without any problems. 
Now the Function `information` from the Logger is called like this:

```
logger.information("Log Message: This is a %s message", <Filename>, <Linenumber>)
``` 

Thats the point where the crash happens because the Function `logger.information` has the following implementation:

```
template <typename T, typename... Args>
void information(const std::string &fmt, T arg1, Args&&... args)
{
	log(Poco::format(fmt, arg1, std::forward<Args>(args)...), Message::PRIO_INFORMATION);
}
``` 

Inside the function another call to `Poco::format` is made which then leads to the crash.
From my side of view i think the second call to Poco::Format is not necessary pls correct me if i'm wrong. 
Hope i could show the root cause of the error.

**Comment by obiltschnig** [comment]
That's what I was suspecting, but I wonder why it's calling the wrong overload in your case. There is an overload of `information(const std::string& fmt, const char* file, int line)` that it actually should call (and does on my machine).

**Comment by KevDi** [comment]
@obiltschnig 
I'm also wonder because i want to reproduce the crash in the `Foundation` Project Testsuite with an Unittest. But in that case it uses the right overloaded Function. 
I also created a dummy Application (just a main program which logs a message) and there it also crashes.

**Comment by obiltschnig** [comment]
On my machine (Win 10, VS 2019 latest, 64-bit) your dummy application works as expected. Wondering if maybe you have mixed up headers and libraries (older version?) on your machine that causes these issues?

**Comment by obiltschnig** [comment]
Interestingly, I found a bug in RefAnyCast (introduced in 1.10.0), which was called in that specific case, which explains the crash. But not why the wrong overload is called in the first case.

**Comment by obiltschnig** [comment]
One more thing... are you sure you're using the final 1.10.0 branch? Especially check that you have 701a34f2e74ffa0c6e2a3d225ce379caf4b3f7da

**Comment by KevDi** [comment]
@obiltschnig i'm working currently on the latest 1.10.1 branch.

**Comment by KevDi** [comment]
@obiltschnig 
The strange thing is, if i add that `Example` Class to the Poco Foundation Logger Test and call the functions it only calls the `Non Template Function`

**Comment by obiltschnig** [comment]
Are you using the latest Visual Studio 2019 (16.4.5)?

**Comment by obiltschnig** [comment]
As I said I have a potential solution (renaming the methods called by the macros), but I'd like to avoid it if at all possible.

**Comment by KevDi** [comment]
@obiltschnig 
Ok now things gets really strange. I just changed the Project Configuration of the Dummy Project.
In the defaults Visual Studio sets the `Debug Information Format` to `/ZI` which leads to the error with the `__LINE__` Macro. Setting that to `/Zi` resolves the issue.
According to the Documentation from Microsoft `/ZI` is incompatible with the `__LINE__` Macro
[Debug Information Format](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019#zi-1)

**Comment by obiltschnig** [comment]
That pretty much explains it. We should probably put a note somewhere, but the question is where.

**Comment by KevDi** [comment]
Maybe print out a compiler warning when `ZI` is set? (If possible)

**Comment by obiltschnig** [comment]
Was my idea, but it seems it's not possible to detect at compile time.

**Comment by aleks-f** [comment]
Since `__LINE__` is only banned as template non-type argument, perhaps extracting it out of the template function call may help. Not sure about `__FILE__`, but if it works, I'd take them both out.

```
if ((logger).information()) { int file = __FILE__, line = __LINE__; (logger).information(Poco::format((fmt), (arg1)), file, line); else (void) 0 }
```
@KevDi can you try?
@obiltschnig that RefAnyCast bug was mine, lurking in develop for two years, sorry

**Comment by aleks-f** [comment]
sorry, looking now it's a dumb proposal, let me think a bit more

**Comment by aleks-f** [comment]
I guess int would work for __LINE__, __FILE__ would have to be std::string or char*, but maybe not even needed to be touched

**Comment by obiltschnig** [comment]
I would not spend too much time on this. It's clearly a bug in the Visual C++ compiler, even [documented](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019#zi-1).

**Comment by aleks-f** [comment]
If this simple fix does it, I'd be in favor of doing it - a thing like this can cost a lot of time someone not aware of it.

**Comment by obiltschnig** [comment]
`file` could simply be `const char*`. I can, however, see the reason why MS claims __LINE__ is incompatible with `/ZI`, because if you change your code at runtime, all your compiled-in __LINE__ directives may be off. Only god (and maybe someone in the MSVC team) knows what idiotic thing they are doing in the compiler so that __LINE__ no longer expands to an integer constant during preprocessing.

**Comment by KevDi** [comment]
With `__FILE__` there is no problem. It's only `__LINE__` because with `/ZI` you are able to change code during debugging and use the changes in the same debugging session. As far as I know and understand it

**Comment by obiltschnig** [comment]
One could also try `static_cast<int>(__LINE__)`, but it will make the code look stupid and will require a lengthy comment explaining why we're doing such idiocy.

**Comment by yinkaisheng** [comment]
I tested that __LINE__ in VS debug mode is a long int,  

add a long int version function to class Logger may work:

	void information(const std::string& msg, const char* file, int line);
	void information(const std::string& msg, const char* file, long int line); // add this one, do the same thing as the int version
