### ISSUE TITLE
Question regarding usage of pcre_ucd.c and pcre_tables.c in Poco Foundation

### ISSUE THREAD

**Issue by Thomas-Barbier-1A** [pocoproject/poco#2916]
Hello,

I create an issue but in fact this is more a question.
I would like to know if there is any plan to remove the pcre internal code (pcre_ucd.c and pcre_tables.c) from Poco Foundation
https://github.com/pocoproject/poco/blob/master/Foundation/CMakeLists.txt#L42

We have an issue with a project that depend on both Poco and libpcre when build statically as there are symbol collision
(symbol like "_pcre_ucd_stage1" that are present in both Poco and libpcre).
Actually I could do like in this unofficial patch from https://github.com/pocoproject/poco/issues/120#issuecomment-15488808 
which rename the pcre symbols inside poco so they don't collide but I wanted to know first if there is any plan in the future to remove this Poco's dependency toward this internal code of pcre.

Cheers
Thomas

**Comment by obiltschnig** [comment]
There's no plan to remove the PCRE dependency for now. I'd say the hack with renaming PCRE symbols using the preprocessor would be acceptable. Could you send a PR against devel or poco-1.10.1?

**Comment by Thomas-Barbier-1A** [comment]
Thanks for your answer.
I have submitted a PR against the devel branch that is a backport of the old unofficial patch mentioned in the other issue.
Let me know if the change is acceptable.

**Comment by obiltschnig** [comment]
Thanks, merged.
