### ISSUE TITLE
how about implement own Unicode string(like use UFT16LE or UTF8)?

### ISSUE THREAD

**Issue by sgf** [pocoproject/poco#2917]
Give up on using std :: string and
 implement default string by  a Unicode  encoding.

just like QT(utf16le),C#(utf16le),java(utf16le),rust(utf8),go(utf8)
dont let ppl use defferents encoding in the string.

If people need to use other encoding strings, let them convert to default string(dixed encoding), or they can do it themselves(develop the XXString what they want).

**Comment by aleks-f** [comment]
For UTF8, we have [a companion set of functions](https://github.com/pocoproject/poco/blob/poco-1.10.1/Foundation/include/Poco/UTF8String.h#L27), and we have [typedefs for UTF encodings](https://github.com/pocoproject/poco/blob/poco-1.10.1/Foundation/include/Poco/UTFString.h#L274-L298), so I think that's about it - we may improve what we currently have, but I do not see us ditching std::string in favor of some homegrown string monster.

**Comment by sgf** [comment]
tks reply
