### ISSUE TITLE
1.10 cmake build fails on FreeBSD 11.2 Release

### ISSUE THREAD

**Issue by phollida** [pocoproject/poco#2922]
Trying to cmake build 1.10 Poco using FreeBSD 11.2 yields:

`$ cmake -H. -Bcmake-build -GNinja -DENABLE_PDF=OFF -DENABLE_TESTS=ON && cmake --build cmake-build --target all`

-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for C++14 compiler
-- Checking for C++14 compiler - available
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.0.2o")
-- Found APR: /usr/local/include/apr-1 (found version "1.7.0")
-- Found APRUTIL: /usr/local/include/apr-1 (found version "1.6.1")
-- Could NOT find Apache2 (missing: APACHE2_INCLUDE_DIR)
-- Could NOT find MYSQL (missing: MYSQL_INCLUDE_DIR MYSQL_LIBRARY)
-- Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR)
-- Could NOT find ODBC (missing: ODBC_LIBRARY ODBC_INCLUDE_DIR)
-- Building with unittests & samples
-- Using internal sqlite, zlib, pcre, expat, ...
-- SQLite Support Enabled
-- MySQL Support Disabled
-- PostgreSQL Support Disabled
-- ODBC Support Disabled
-- CMake 3.16.4 successfully configured Poco using Ninja generator
-- Poco package version: 1.0.0
-- Building dynamic libraries
-- [cmake] Installation target path: /usr/local
-- [cmake] Bulid for OS type:      FreeBSD
-- [cmake] Build for OS version:   11.2-RELEASE
-- [cmake] Build for CPU type:     amd64
-- [cmake] Build type:             RelWithDebInfo
-- [cmake] Build with cxx flags:   -O2 -g -DNDEBUG
-- [cmake] Build with c flags:     -O2 -g -DNDEBUG
-- Building: Encodings
-- Building: XML
-- Building: JSON
-- Building: Util
-- Building: Net
-- Building: MongoDB
-- Building: Redis
-- Building: JWT
-- Building: NetSSL_OpenSSL
-- Building: Crypto
-- Building: Data
-- Building: Zip
-- Building: PageCompiler
-- Building: File2Page
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/home/pho/poco/cmake-build
[13/1075] Building CXX object Foundation/CMakeFiles/Foundation.dir/src/ArchiveStrategy.cpp.o
FAILED: Foundation/CMakeFiles/Foundation.dir/src/ArchiveStrategy.cpp.o
/usr/bin/c++  -DFoundation_EXPORTS -DPOCO_ENABLE_CPP11 -DPOCO_ENABLE_CPP14 -DPOCO_HAVE_FD_POLL -DPOCO_OS_FAMILY_UNIX -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -D_THREAD_SAFE -I../Foundation/include -I../Foundation/src -O2 -g -DNDEBUG -fPIC   -std=gnu++14 -MD -MT Foundation/CMakeFiles/Foundation.dir/src/ArchiveStrategy.cpp.o -MF Foundation/CMakeFiles/Foundation.dir/src/ArchiveStrategy.cpp.o.d -o Foundation/CMakeFiles/Foundation.dir/src/ArchiveStrategy.cpp.o -c ../Foundation/src/ArchiveStrategy.cpp
In file included from ../Foundation/src/ArchiveStrategy.cpp:15:
In file included from ../Foundation/include/Poco/ArchiveStrategy.h:25:
../Foundation/include/Poco/NumberFormatter.h:206:21: error: class member cannot be redeclared
        static std::string format(Int64 value);
                           ^
../Foundation/include/Poco/NumberFormatter.h:101:21: note: previous declaration is here
        static std::string format(long value);
                           ^
../Foundation/include/Poco/NumberFormatter.h:209:21: error: class member cannot be redeclared
        static std::string format(Int64 value, int width);
                           ^
../Foundation/include/Poco/NumberFormatter.h:104:21: note: previous declaration is here
        static std::string format(long value, int width);
                           ^
../Foundation/include/Poco/NumberFormatter.h:213:21: error: class member cannot be redeclared
        static std::string format0(Int64 value, int width);
                           ^
../Foundation/include/Poco/NumberFormatter.h:109:21: note: previous declaration is here
        static std::string format0(long value, int width);
                           ^
../Foundation/include/Poco/NumberFormatter.h:218:21: error: class member cannot be redeclared
        static std::string formatHex(Int64 value, bool prefix = false);
                           ^
../Foundation/include/Poco/NumberFormatter.h:114:21: note: previous declaration is here
        static std::string formatHex(long value, bool prefix = false);
                           ^
../Foundation/include/Poco/NumberFormatter.h:224:21: error: class member cannot be redeclared
        static std::string formatHex(Int64 value, int width, bool prefix = false);
                           ^
../Foundation/include/Poco/NumberFormatter.h:120:21: note: previous declaration is here
        static std::string formatHex(long value, int width, bool prefix = false);
                           ^
../Foundation/include/Poco/NumberFormatter.h:231:21: error: class member cannot be redeclared
        static std::string format(UInt64 value);
                           ^
../Foundation/include/Poco/NumberFormatter.h:128:21: note: previous declaration is here
        static std::string format(unsigned long value);
                           ^
../Foundation/include/Poco/NumberFormatter.h:234:21: error: class member cannot be redeclared
        static std::string format(UInt64 value, int width);
                           ^
../Foundation/include/Poco/NumberFormatter.h:131:21: note: previous declaration is here
        static std::string format(unsigned long value, int width);
                           ^
../Foundation/include/Poco/NumberFormatter.h:238:21: error: class member cannot be redeclared
        static std::string format0(UInt64 value, int width);
                           ^
../Foundation/include/Poco/NumberFormatter.h:136:21: note: previous declaration is here
        static std::string format0(unsigned long value, int width);
                           ^
../Foundation/include/Poco/NumberFormatter.h:243:21: error: class member cannot be redeclared
        static std::string formatHex(UInt64 value, bool prefix = false);
                           ^
../Foundation/include/Poco/NumberFormatter.h:141:21: note: previous declaration is here
        static std::string formatHex(unsigned long value, bool prefix = false);
                           ^
../Foundation/include/Poco/NumberFormatter.h:248:21: error: class member cannot be redeclared
        static std::string formatHex(UInt64 value, int width, bool prefix = false);
                           ^
../Foundation/include/Poco/NumberFormatter.h:146:21: note: previous declaration is here
        static std::string formatHex(unsigned long value, int width, bool prefix = false);
                           ^
../Foundation/include/Poco/NumberFormatter.h:427:14: error: class member cannot be redeclared
        static void append(std::string& str, Int64 value);
                    ^
../Foundation/include/Poco/NumberFormatter.h:336:14: note: previous declaration is here
        static void append(std::string& str, long value);
                    ^
../Foundation/include/Poco/NumberFormatter.h:430:14: error: class member cannot be redeclared
        static void append(std::string& str, Int64 value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:339:14: note: previous declaration is here
        static void append(std::string& str, long value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:434:14: error: class member cannot be redeclared
        static void append0(std::string& str, Int64 value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:344:14: note: previous declaration is here
        static void append0(std::string& str, long value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:439:14: error: class member cannot be redeclared
        static void appendHex(std::string& str, Int64 value);
                    ^
../Foundation/include/Poco/NumberFormatter.h:349:14: note: previous declaration is here
        static void appendHex(std::string& str, long value);
                    ^
../Foundation/include/Poco/NumberFormatter.h:443:14: error: class member cannot be redeclared
        static void appendHex(std::string& str, Int64 value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:353:14: note: previous declaration is here
        static void appendHex(std::string& str, long value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:449:14: error: class member cannot be redeclared
        static void append(std::string& str, UInt64 value);
                    ^
../Foundation/include/Poco/NumberFormatter.h:359:14: note: previous declaration is here
        static void append(std::string& str, unsigned long value);
                    ^
../Foundation/include/Poco/NumberFormatter.h:452:14: error: class member cannot be redeclared
        static void append(std::string& str, UInt64 value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:362:14: note: previous declaration is here
        static void append(std::string& str, unsigned long value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:456:14: error: class member cannot be redeclared
        static void append0(std::string& str, UInt64 value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:367:14: note: previous declaration is here
        static void append0(std::string& str, unsigned long value, int width);
                    ^
../Foundation/include/Poco/NumberFormatter.h:461:14: error: class member cannot be redeclared
        static void appendHex(std::string& str, UInt64 value);
                    ^
../Foundation/include/Poco/NumberFormatter.h:372:14: note: previous declaration is here
        static void appendHex(std::string& str, unsigned long value);
                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[15/1075] Building CXX object Foundation/CMakeFiles/Foundation.dir/src/AsyncChannel.cpp.o
ninja: build stopped: subcommand failed.
$`
Looks like preprocessor defines are not being set correctly by cmake configure for FreeBSD

**Comment by RorkXander** [comment]
Building the Library on Cygwin fails.

This is a reopen of this issue:  https://github.com/pocoproject/poco/issues/2922

Solved it by adding  || POCO_OS == POCO_OS_CYGWIN at the same line
