### ISSUE TITLE
MSVC CMake error `invalid option: /MP`

### ISSUE THREAD

**Issue by linquize** [pocoproject/poco#2924]
Commit: 27f24c578328dee1c9f22d49240b968d684efdbd
MSVC 2017/2019 + CMake:

When compiling `DLLVersion.rc`, 
`invalid option: /MP`

Since https://github.com/pocoproject/poco/commit/75a86ad868027f2c07b1934960a743d644328710#diff-af3b638bc2a3e6c650974192a53c7291R61, 
`ENABLE_MSVC_MP` is `ON` by default, which causes this issue.

Setting CMake `ENABLE_MSVC_MP` to `OFF` solves the problem.

Should we change back to `OFF` by default?

**Comment by Bjoe** [comment]
Yep, I think it was accidentally switch `ON` ...

@obiltschnig We should change this value back to `OFF` ... or?

**Comment by obiltschnig** [comment]
We can switch it off for now, but if it remains an option we should either fix it or remove it.

**Comment by Bjoe** [comment]
I think we should remove it ... there is a cmake way see https://stackoverflow.com/a/50883540

**Comment by obiltschnig** [comment]
OK, removed it in a3d827d80eb7f3329c58e73eb2906cb7ba829019.

**Comment by linquize** [comment]
done
