### ISSUE TITLE
ParallelSocketAcceptor bug? cause cpu 100%

### ISSUE THREAD

**Issue by lightwinglc** [pocoproject/poco#293]
I used ParallelSocketAcceptor in 1.5.2,which like 
ParallelSocketAcceptor<MyServiceHandler, SocketReactor> acceptor(svs, reactor);
and when program run, which cost 100% cpu useage.

Who knowns what's the problem?

**Comment by aleks-f** [comment]
[fixed](https://github.com/pocoproject/poco/commit/2f20f801c5d8d1bdd9f214d9a1a348faab4edd1a);  check the onWritable notification as well; since sockets are writable most of the time, the handler will be called frequently and, if it does nothing, can cause the reported symptom.
