### ISSUE TITLE
unable to build the project

### ISSUE THREAD

**Issue by rohanvivek** [pocoproject/poco#2931]
I'm using "cmake --build . --config Release" to build 
and getting error as 

"[ 68%] Built target Net
[ 69%] Linking CXX shared library ../lib/libPocoNet.so
/usr/bin/ld: cannot find"

**Comment by obiltschnig** [comment]
Please state POCO version, operating system version, compiler version, etc. if you want help.

**Comment by rohanvivek** [comment]
Sir,
I Belive that I'm using the latest version of Poco i.e., 1.10.1 on Ubuntu 18.04.4 and the GCC version is 7.4.0.

**Comment by obiltschnig** [comment]
And what's the exact error message you're getting. It's best to include the complete cmake output.
