### ISSUE TITLE
API change from raw pointer to AutoPtr "compatible" but breaking existing code

### ISSUE THREAD

**Issue by Ecordonnier** [pocoproject/poco#2939]
Hello,
we updated our application from Poco version 1.8.0.1 to version 1.10.1. Our code is calling LoggingConfigurator::configure.

API in version 1.8.01: `void configure(AbstractConfiguration* pConfig);`
API in version 1.10.1: `void configure(AbstractConfiguration::Ptr pConfig);` (AbstractConfiguration::Ptr is an AutoPtr)

Note that because of the constructor of Poco::AutoPtr taking a raw pointer as parameter, our existing code compiles fine with the new API:
```
    AutoPtr(C* ptr): _ptr(ptr)
    {   
    }  
```

However, this means that the destructor of the config object we are passing as parameter to "configure()" is getting called, which is not at all what the code is supposed to do...

I think this makes it quite dangerous to update Poco, because the code still compiles but breaks in subtle ways.

One solution to this issue would be to make the constructor of AutoPtr which takes a raw pointer explicit. See also https://stackoverflow.com/questions/11367933/why-is-unique-ptrtt-explicit

**Comment by aleks-f** [comment]
Yeah, that was an unfortunate interface design from some different times long time ago; but even then it was best practice to pass in `AutoPtr`. 

Making that constructor explicit would break a lot of code, one troubling case I can think of is where  automatic conversion from `Child*` to `AutoPtr<Parent>` is utilized.
