### ISSUE TITLE
Poco::delegate API Question

### ISSUE THREAD

**Issue by friguimahdi** [pocoproject/poco#2941]
Hello, been using poco for several months now , so far so good. I have a question about the poco::delegate api with basic events is it possible to use it with a funtion pointer ? here is how the code looks like : 
void Class1::Function1(void (*CallbackFunction)(uint8t* ))
{
   Event+= Poco::delegate(this,CallbackFunction);
}
Im getting this error when compiling the project :
error: no matching function for call to 'delegate(Conti::RemoteAccessService::IRemoteAccessServicesImpl*, void (*&)(uint8_t*))'
     EtatPrincipSevEvent += Poco::delegate(this,CallbackFunction);

is possible to do it and if not do you have any suggestion or a workaround please.

**Comment by aleks-f** [comment]
It is possible, but it looks like you are trying to register a freestanding function pointer as pointer to member. Plus, callback parameters are passed by reference.

Try this:

```
void CallbackFunction1(uint8t&) { /* ... */ }

class Class1
{
  Poco::BasicEvent<uint8_t> ev;
public:
  void Function1(void (CallbackFunction)(uint8_t&))
  {
    ev += Poco::delegate(CallbackFunction);
  }

  void Notify1()
  {
    uint8_t i = 0;
    ev.notify(this, i);
  }
};

Class1 cls;
cls.Function1(CallbackFunction1);
cls.Notify1();

```

**Comment by friguimahdi** [comment]
Thank you @aleks-f, it worked like a charm.
