### ISSUE TITLE
PocoCrypto fails to build on Windows.

### ISSUE THREAD

**Issue by fishnet37222** [pocoproject/poco#2944]
I'm trying to build Poco on Windows using CMake.  Everything seems to work correctly until it tries to link the PocoCrypto library.  I get the error messages shown below at that point.

`[ 78%] Linking CXX shared library ..\bin\PocoCryptod.dll
LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\Crypto.dir\objects1.rsp /out:..\bin\PocoCryptod.dll /implib:..\lib\PocoCryptod.lib /pdb:C:\Users\Dave\Downloads\poco-1.10.1-all\build-cmake\bin\PocoCryptod.pdb /dll /version:71.0 /machine:x64 /debug /INCREMENTAL ..\lib\PocoFoundationd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib iphlpapi.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\Crypto.dir/intermediate.manifest CMakeFiles\Crypto.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'libcrypto.lib'
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.`

Please let me know if you need any other information.

**Comment by fishnet37222** [comment]
After looking into this to see if I could fix it on my own, it seems the issue is with the "FindOpenSSL.cmake" file. It appears that it doesn't recognize that the compiler I'm using is MSVC.

**Comment by big-brain** [comment]
> After looking into this to see if I could fix it on my own, it seems the issue is with the "FindOpenSSL.cmake" file. It appears that it doesn't recognize that the compiler I'm using is MSVC.

have you solved?
