### ISSUE TITLE
Iterating over Var containing empty container throws "Out of range" exception

### ISSUE THREAD

**Issue by akete** [pocoproject/poco#2945]
When iterating over `Poco::Dynamic::Var` that contains empty continer (e. g. `Poco::Dynamic::Vector`), iteration loop is entered and "Out of range" exception is thrown when dereferencing `VarIterator`.

```c++
Poco::Dynamic::Var v{Poco::Dynamic::Vector()};
int i = 0;
for (auto it = v.begin(); it != v.end(); ++it) {
    *it = ++i;
}
```

**Comment by aleks-f** [comment]
Your fix is fine, however `begin()` and `end()` should throw `InvalidAccessException` on isEmpty() - it does not make sense to allow creation of iterators for empty Var.
When done, please send pull to devel branch. 
CC @obiltschnig
