### ISSUE TITLE
JSON does not support ASCII

### ISSUE THREAD

**Issue by xinlengyuer** [pocoproject/poco#2952]
JSON does not support Chinese ASCII

	JSON::Object pthis;
	pthis.set("语文", "数学");

	std::ostringstream  jsnOstream;
	pthis.stringify(jsnOstream, 0);

	JSON::Parser doc;
	const char* str = jsnOstream.str().c_str();f
	std::cout << str << "\r\n";

	Dynamic::Var var =doc.parse(str);  // **the parse is error**

found that pdjson does not support Chinese acsii。

**Comment by crew1274** [comment]
我想應該是你IDE的編碼沒設定為UTF-8，要不然就是你執行環境沒有libiconv
