### ISSUE TITLE
[Q]: Cpp stdlib requirement

### ISSUE THREAD

**Issue by Krzmbrzl** [pocoproject/poco#2954]
In the README it is mentioned that cpp14 is required to build Poco. We have been wondering though if that is due to Poco requiring cpp14 Syntax elements or whether it needs elements from the stdlib that were introduced with cpp14? 

I'm asking because we'd need it to run with a cpp11 stdlib. Having cpp14 Syntax for compiling wouldn't be a problem though.

**Comment by obiltschnig** [comment]
It should be possible to compile with C++11 for now (1.10.1). However, this may change in the coming releases as we may start to use more C++14 features.

**Comment by Krzmbrzl** [comment]
Okay thank you very much! :)
