### ISSUE TITLE
SocketReactor loads one core of CPU up to 100%

### ISSUE THREAD

**Issue by dmitry-pozdniakov** [pocoproject/poco#2966]
I have found a bug in SocketReactor for Linux. This is relevant for v1.10.1.

Steps to reproduce:
1. Create and run the reactor.
2. Create a socket and connect to a remote host.
3. Subscribe to various types of events by using SocketReactor::addEventHandler() method. For example: ReadableNotification, WritableNotification and TimeoutNotification.
4. Send some data to the socket.
5. Wait for the WritableNotification event and unsubscribe from this event by using SocketReactor::removeEventHandler() method.

Voila!

It happened because your forgot to update _pollSet and remove the corresponding epoll event. As a result, _pollSet.poll() immediately returns with an event that doesn't have handle (in this example PollSet::POLL_WRITE). This happens over and over without any delay and loads the processor.

I have provided you with a simple fix for this error.

[poco.patch.txt](https://github.com/pocoproject/poco/files/4393662/poco.patch.txt)

Let me know if I was wrong. Thanks

**Comment by dmitry-pozdniakov** [comment]
Updated fix.

[poco.patch.txt](https://github.com/pocoproject/poco/files/4514595/poco.patch.txt)

**Comment by lingyphone** [comment]
I have exact problem as you and similar fix, but only the first line difference:

        if (has(socket)) {

**Comment by woytaz** [comment]
Thanks for the patch. It helped a lot!

It happens on 1.10.1 on Windows too as well as the freshly released 1.11.0. However, the attached patch doesn't help on 1.11.0 (probably due to fixes for issues with `PollSet`). You can make a hack and patch `PollSet.cpp` to force using the select-based implementation.

**Comment by obiltschnig** [comment]
According to a customer b89baaa fixes this for 1.11.0.
