### ISSUE TITLE
build Poco Net failed MinGW [TIMESTAMP_REQUEST enum vs macro]

### ISSUE THREAD

**Issue by sk-landry** [pocoproject/poco#2967]
Good morning, 

I'm building POCO from Github's master branch. (commit = 3fc3e5f5b8462f7666952b43381383a79b8b5d92) 
I use MinGW 7.3 32bits bundled in QT. I am on Windows 10.
The build of POCO NET failed because of the enum TIMESTAMP_REQUEST define in ICMPv4PackekImpl.h

> enum MessageType
> {
> 	TIMESTAMP_REQUEST ,
> };

The error indicates that there is a macro TIMESTAMP_REQUEST define somewhere, I don't know where but it is causing a conflict

My solution was to rename the enum from TIMESTAMP_REQUEST  to simply TIMESTAMP.

For information, I've previously built POCO 1.9.0-release without any issues with the same environment.

**Comment by iSLC** [comment]
It conflicts with a macro named `TIMESTAMP_REQUEST` inside the `wincrypt.h` header.

```c
#define TIMESTAMP_REQUEST ((LPCSTR) 78)
```

**Comment by matejk** [comment]
When trying to compile with MinGW 11 there are more compile issues with current state of devel.

Will fix and create pull request.
