### ISSUE TITLE
Error on #include <mysql.h> on file Data/MySQL/MySQLException.h

### ISSUE THREAD

**Issue by ayrtoncavalieri** [pocoproject/poco#2974]
When compiling an application using this header the compiler complains about the missing include file. Upon revision on Ubuntu 18.04LTS, Fedora 32, and Fedora 33, I found that when I use the include as `#include <mysql/mysql.h>` the compilation works just fine.
The connector library was installed from the official MySQL repository on all the tested distros. And the include file was on `/usr/include/mysql`, and not on `/usr/include`, which is the defeault location if you don't specify the `mysql` folder.
I'm using Poco 1.10.1 and MySQL connector 8.0.19.

**Comment by aleks-f** [comment]
assuming you are using cmake, that does not belong in sources; it should be set [here](https://github.com/pocoproject/poco/blob/master/cmake/FindMySQL.cmake#L36), something like [here](https://github.com/pocoproject/poco/blob/master/Data/MySQL/Makefile#L10)
