### ISSUE TITLE
SharedMemoryImpl x64 size error

### ISSUE THREAD

**Issue by trublemaker** [pocoproject/poco#2976]
i use SharedMemory with x64,
while i set size > 4G , then error,
        std::size_t size = 1024LL * 1024 * 1024 * 4;
	SharedMemory mem("MySharedMemory", size, SharedMemory::AM_WRITE); 

and i find the define of _size is DWORD, while size_t is 
#ifdef _WIN64
    typedef unsigned __int64 size_t;
....
and _size(static_cast<DWORD>(size)) may lose high

**Comment by trublemaker** [comment]
and 	  
	_memHandle = CreateFileMappingW(INVALID_HANDLE_VALUE, NULL, _mode, 0, _size, utf16name.c_str());

dwMaximumSizeHigh always set 0, and   it should  be _size>>32

**Comment by Spaky** [comment]
Hey @aleks-f,
i created an improvement that allows SharedMemory greater than 4GB on x64 for win32.
Currently the win32 jobs on GitHub are failing because the paging file is too small,
but on my local machine the new test is successful.

Do you think it is okay, when i create a PR for this issue?

**Comment by pavledragisic** [comment]
@aleks-f  This commit https://github.com/pocoproject/poco/commit/df656fc51d254ffe83781d713d5875b99d4aeeee ended up here by mistake. It was supposed to go to the issue [2978](https://github.com/pocoproject/poco/issues/2978)

**Comment by aleks-f** [comment]
> @aleks-f This commit [df656fc](https://github.com/pocoproject/poco/commit/df656fc51d254ffe83781d713d5875b99d4aeeee) ended up here by mistake. It was supposed to go to the issue [2978](https://github.com/pocoproject/poco/issues/2978)

@pavledragisic you should [--amend](https://www.atlassian.com/git/tutorials/rewriting-history) it
