### ISSUE TITLE
waitForTermination is unreliable on Linux.

### ISSUE THREAD

**Issue by IneptProgrammer** [pocoproject/poco#2978]
ServerApplication::[waitForTerminationRequest](https://github.com/pocoproject/poco/blob/poco-1.10.0-release/Util/src/ServerApplication.cpp#L543)() creates a signal mask blocking SIGINT, SIGTERM, and SIGQUIT . Pthreads inherit the signal mask of the creating thread. A Poco Server Application's main method is supposed to call waitForTerminationRequest() at the end. So all the threads that get created before this point don't inherit the mask blocking these signals. This basically means all of the threads created by the application, besides the main thread, do not inherit this signal mask and do not block these signals.

From signal(7): 

> A process-directed signal may be delivered to any one of the threads that does not currently have the signal blocked.  If more than one of the threads has the signal unblocked, then the kernel chooses an arbitrary thread to which to deliver the signal.

ServerApplication::[terminate](https://github.com/pocoproject/poco/blob/poco-1.10.0-release/Foundation/src/Process_UNIX.cpp#L289)() uses a process directed signal to break out of waitForTerminationRequest(). This signal may get delivered to any thread. If it is not delivered to the main thread it causes the process to terminate immediately with a SIGINT exit code.

The application I work in is heavily threaded (hundreds of threads), but I only see this behavior on occasion when calling terminate. (It seems like it should happen most of the time terminate gets called). I took a look at the Linux source code and it looks like if multiple threads, including the main thread, can receive a signal the kernel tries to prioritize the main thread. However, it is not guaranteed to choose the main thread (for instance if the main thread already has Pending signals it will choose another thread).

The signals waited for in waitForTerminationRequest need to be blocked before other threads are created. It looks like there is code to do something similar for SIGPIPE in[ Thread_POSIX.cpp](https://github.com/pocoproject/poco/blob/poco-1.10.0-release/Foundation/src/Thread_POSIX.cpp#L44).

This is related to to issue: [SIGTERM is not always handled properly in ServerApplication](https://github.com/pocoproject/poco/issues/2774)

**Comment by aleks-f** [comment]
@pavledragisic

- add an optional parameter to `TestApp` to launch a number of threads
- add optional capability to `Thread` to block signals to itself (in this case, we want to block `SIGINT`, but it should be possible to block any signal for a thread)
- add this test case to `ProcessRunner` tests checking that it always gets zero exit code from the process

Linux only. Tentatively for 1.13.0, but we can push it down the road if we run out of time
