### ISSUE TITLE
memory leaks in Poco::Any 

### ISSUE THREAD

**Issue by xiezh** [pocoproject/poco#2980]
if POCO_NO_SOO not set，and sizeof(ValueType) > POCO_SMALL_OBJECT_SIZE，call operator=(const ValueType&) and operator=(const Any&) will be memory leaks。

**Comment by aleks-f** [comment]
@xiezh can you elaborate how exactly does leak happen? 
note that the [destructor](https://github.com/pocoproject/poco/blob/poco-1.10.1/Foundation/include/Poco/Any.h#L184-L195) is aware of the storage type and does the cleanup.

**Comment by xiezh** [comment]
when any has valid value object,and then reassign a new value object use operator=, the old value object will not be destructor or pHolder pointer will not be deleted. eg: Poco:Any<std:string> a(“123”); a=“456”; the content of “123” will not be deleted or destructor
