### ISSUE TITLE
CryptoTransformImpl::setPadding(int padding) incorrect for OpenSSL >= 1.1

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#2992]
See https://github.com/pocoproject/poco/commit/75a7ee4b0fdd1e5deb3e253b97b18d49e6b8b082#commitcomment-38887669

**Comment by bytedreamer** [comment]
Created a pull request of a verified fix

**Comment by obiltschnig** [comment]
fixed (duplicate issue)
