### ISSUE TITLE
undefined reference to `Poco::Crypto::CipherKey::CipherKey

### ISSUE THREAD

**Issue by sia72abedi** [pocoproject/poco#3011]
I am trying to compile the exact code in [poco website:](https://pocoproject.org/docs/Poco.Crypto.Cipher.html)
`    Poco::Crypto::CipherFactory& factory = Poco::Crypto::CipherFactory::defaultFactory();
// Creates a 256-bit AES cipher
    Poco::Crypto::Cipher* pCipher = factory.createCipher(Poco::Crypto::CipherKey("aes-256"));`
but I face below error:

> undefined reference to `Poco::Crypto::CipherKey::CipherKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> collect2: error: ld returned 1 exit status

I use Conan as package manager and Cmake(VERSION 2.8.12) and also my poco version is poco/1.10.1(even with poco/1.9.4)

**Comment by bas524** [comment]
1. Have you got a libPocoCrypto in your conan-poco package?
2. CMake 2.8.12 is too old, try to use 3.*

**Comment by sia72abedi** [comment]
@bas524 
I use cmake version 3.15.3, but still the problem exist

**Comment by sia72abedi** [comment]
It is Link error and headers file attached to the project. It seems that the body of functions are not there

**Comment by bas524** [comment]
There are two problems which can be cause this problem:
1. Your build doesn't support crypto and some libraries were not compiled
2. You have one installed version of poco-libs and try to build another.
