### ISSUE TITLE
Usage with gcc 4.8.4

### ISSUE THREAD

**Issue by cdigruttola** [pocoproject/poco#3029]
Hi,

I'd like to use POCO with Ubuntu 14.04 but reading the cmake/CXX1x.cmake the version of gcc must be at least 4.9.2. Is there any problem with the older version of gcc?

**Comment by obiltschnig** [comment]
The current release may work, or it may not work. I haven't tested with older compilers, as we have an explicit C++14 requirement. You could still use an older release, such as 1.9.4, which works with older compilers.

**Comment by cdigruttola** [comment]
Hi, I've just tested the build on gcc 4.8.4 and it works (modifying the CXX1x.cmake file).
