### ISSUE TITLE
It is convenience if making JSONString support std::wstring.

### ISSUE THREAD

**Issue by jpsn123** [pocoproject/poco#3030]
///VarHolder.cpp
```
bool isJSONString(const Var& any)
{
	return any.type() == typeid(std::string) ||
		any.type() == typeid(std::wstring) ||  //add wstring support
		any.type() == typeid(char) ||
		any.type() == typeid(char*) ||
		any.type() == typeid(Poco::DateTime) ||
		any.type() == typeid(Poco::LocalDateTime) ||
		any.type() == typeid(Poco::Timestamp);
}
```

**Comment by jpsn123** [comment]
And, also making DynamicStruct JSON::Object Dynamic::Var can Convert std::wstring.

**Comment by aleks-f** [comment]
sorry, but I don't think we'll go down the `std::wstring` rabbit hole. `std::wstring` has different widths on different platforms, so Poco is UTF-8 based by design. If you must wide strings, use the conversion utility functions appropriate for your platform.

**Comment by jpsn123** [comment]
@aleks-f  ok, thanks your reply. I'm not very thoughtful.
