### ISSUE TITLE
Fresh CMake build for Poco 1.10.1 fails with libcrypto.lib missing (Windows 10 + VS2019)

### ISSUE THREAD

**Issue by omatai** [pocoproject/poco#3034]
I have a fresh copy of Poco 1.10.1 extracted from zip file. I have 2 x fresh installs of OpenSSL (32-bit, 64-bit) and an OPENSSL_ROOT_DIR define set according to the platform I'm building for.

For 32-bit build I use:
    cmake -HS:\3rdparty\Poco -B S:\3rdparty\Poco-build32 -G "Visual Studio 16 2019" -A win32
    cmake --build s:\3rdparty\Poco-build32 --config RelWithDebInfo

64-bit build uses "build64" folder and -A x64 option. Both identify OpenSSL version correctly. But both builds fail to link to libcrypto:

    LINK : fatal error LNK1104: cannot open file 'libcrypto.lib' [S:\3rdparty\Poco-build32\Crypto\Crypto.vcxproj]

**Comment by omatai** [comment]
P.S. All other components appear to build correctly - PocoFoundation.dll, PocoNet.dll, etc are all built

**Comment by omatai** [comment]
Note: what is really weird/annoying about this error is (1) that there is NO MENTION anywhere in the vcxproj file of libcrypto.lib - only libcrypto32MD.lib and (2) that the build process already correctly accesses OpenSSL in C:\Program Files (x86)\OpenSSL-win32... which contains libcrypto.lib directly in the lib folder where it should be! It's a very explicit case of "everything looks correct" that I find impossible to resolve in any obvious way.

**Comment by aleks-f** [comment]
see [here](https://github.com/pocoproject/poco/blob/poco-1.10.1/Crypto/include/Poco/Crypto/Crypto.h#L92)

there are also [prebuilt binaries](https://github.com/pocoproject/openssl), which should build out of the box, but I'm not familiar with cmake, @Bjoe knows how to achieve the right thing

**Comment by omatai** [comment]
OK - I understand why it is trying to link libcrypto.lib... but not why it can't find it. It also needs PocoFoundation.lib, so I try to cheat by making a copy there... but that doesn't work either.

I'm also not familiar with cmake - I would prefer to build using buildwin... but had too many problems, so changed to cmake since documentation says it is preferred. But 2 hours ago, I gave up on cmake, and went back to buildwin.

The problem(s) with cmake might be related to:
 * I need to build both Win32 and x64 versions of Poco including OpenSSL. OpenSSL only uses 1 lib/bin/include folder whereas Poco uses bin64 and lib64. (but I get the same error in all cmake builds)
 * I have tried using prebuilt binaries - it does not build "out of the box". It only seems to build if I ALSO download an OpenSSL installation from https://wiki.openssl.org/index.php/Binaries. - I think a clear layout of the openSSL folder structure (like at top of https://pocoproject.org/docs/00200-GettingStarted.html) would be very useful.
 * OpenSSL urges upgrade to version 1.1.1... but pocoproject/openssl appears to be based on openSSL 1.1.0. I think I have mixed versions :-( But I only mixed the versions after this cmake problem occurred.

Now using buildwin, I can now produce all DLLs... but I cannot prove that they are viable DLLs - so far I get exceptions from openSSL - SSL Exception: error:1408F10B:SSL routines:ssl3_get_record:wrong version number. I think this is probably because I am building with a mix of openSSL 1.1.0 and 1.1.1

**Comment by omatai** [comment]
I think the big problem is lack of clarity about what EXACTLY should be in %POCO_BASE%\OpenSSL. And perhaps also if there MUST be some environment variable set for %OPENSSL_ROOT_DIR%... or only if the OpenSSL installation is not in %POCO_BASE%\OpenSSL.

I have now tried all combinations of ways to build OpenSSL into Poco - they all fail :-( I get close via buildwin, but somehow I mix versions of OpenSSL.

I cannot "build out of the box" - when I use the git clone command in "Getting Started", the include folder is NOT in %POCO_BASE%\OpenSSL - it is a level lower down. If I move the include folder up one level, I cannot find a solution.

Directly inside %POCO_BASE%\OpenSSL is "buildall.cmd" and "build.ps1". buildall makes it clear that both 32-bit and 64-bit should build side-by-side - exactly what I want. But buildall fails to find many things - first it cannot find "Env\VS120COMNTOOLS, then vcvars32.bat, then it does not copy any openSSL include files into openssl/VS_120/include... so everything else fails)

You may believe the instructions are clear to you - they are not clear to me. I have been trying all week to build Poco with OpenSSL :-( I have reinstalled 5 times so far...

**Comment by aleks-f** [comment]
It's hard to tell at what state is your development system now. But, if you have this satisfied, you should be fine with either supported openssl version:

1. VS projects (Crypto and NetSSL_OpenSSL) have OpenSSL includes path configured
2. VS projects (Crypto and NetSSL_OpenSSL) have OpenSSL lib path configured
3. OpenSSL DLLs corresponding to 1. and 2. are found at runtime

**Comment by omatai** [comment]
OK - I can now build Poco via buildwin. And I have proven that both 32-bit and 64-bit DLLs generated are viable. I could not achieve this "out of the box" with the openssl from github.com/pocoproject/openssl... but I could achieve it by downloading both 32-bit and 64-bit OpenSSL pre-compiled binaries from http://slproweb.com/products/Win32OpenSSL.html. Here's what I needed to do:

* Start command line tool from Visual Studio
* Invoke vcvars32.bat or vcvars64.bat to ensure environment is correct for Win32 or x64 build
  - I found these scripts in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
* Ensure buildwin.cmd script is configured to specify location of OpenSSL include and lib sub-folders
  - be sure to modify the script between builds if building both 32- and 64-bit builds
* Edit the Poco "components" file to eliminate any components not required that will stop build
* Invoke buildwin, e.g.:
  - buildwin 160 shared both Win32 samples notests
  - buildwin 160 shared both x64 samples notests

This is what I tried from the outset... but I missed vcvars64.bat - NOT mentioned in the "Getting Started" help file. So I switched to CMake, and encountered other problems. If I get some time, I will try to identify what I was missing with the CMake build. But for now, I'll close the issue.
