### ISSUE TITLE
Poco errors with _DEBUG and NDEBUG

### ISSUE THREAD

**Issue by babywonderland** [pocoproject/poco#3039]
Poco's platform_win32.h for some reason raises a compile-time error if it finds both NDEBUG and _DEBUG to be defined. These control different behaviors and are not mutually exclusive. Poco should not error when both are set.

I think the check and #error can simply be removed.

[poco.patch.txt](https://github.com/pocoproject/poco/files/4797444/poco.patch.txt)

**Comment by zosrothko** [comment]
May be in other projects, NDEBUG and _DEBUG could be active at the same time, but not in Poco: The #pragma used to link automatically the .lib for building a .dll is different between _DEBUG and NDEBUG.

_DEBUG generates a lib that ends with 'd' while NDEBUG does not add this suffix. Thus your patch cannot be applied.

**Comment by babywonderland** [comment]
Thanks for the explanation. I reviewed all of the #pragma comment(lib...)s. Most are controlled by a separate *_EXPORTS #define not connected to either _DEBUG or NDEBUG, and those that aren't, exclusively use _DEBUG (and #else, as they ought). None depend on NDEBUG.

NDEBUG usage is rare outside of SQLite. I think this patch is harmless to SQLite and it won't hurt expat -- the only other place it's used.

(By the way, the POCO_NO_AUTOMATIC_LIBS usage is very inconsistent; that option probably doesn't work.)

**Comment by babywonderland** [comment]
So can this be applied? Should I make a merge request?

**Comment by zosrothko** [comment]
There is  this  #error statement in `poco-1.10\Foundation\include\Poco\Platform_WIN32.h`
```
// Check debug/release settings consistency
#if defined(NDEBUG) && defined(_DEBUG)
	#error Inconsistent build settings (check for /MD[d])
#endif

```

and also this code below in `poco-1.10\Foundation\src\SharedLibrary_WIN32U.cpp`
```
std::string SharedLibraryImpl::suffixImpl()
{
#if defined(_DEBUG) && !defined(POCO_NO_SHARED_LIBRARY_DEBUG_SUFFIX)
	return "d.dll";
#else
	return ".dll";
#endif
}
```
So unless you convince @obiltschnig  or @aleks-f , it won't be applied.

**Comment by babywonderland** [comment]
With the Platform_WIN32.h check removed as I've suggested, the SharedLibrary_WIN32U.cpp code you mention would continue to do the right thing -- whether POCO_NO_SHARED_LIBRARY_DEBUG_SUFFIX is defined or not. All the other code in Poco that I've looked at would also still behave correctly.

Another option is to change this from #error to a message. It alerts downstream, but at least isn't fatal. There are some hacks to emit a warning, which downstream projects could at least then control (output, ignore, or error) in the same way they control other warnings. Or if you feel such a check is truly necessary, the detect_mismatch pragma is probably the proper way to achieve what you're trying to do.

@obiltschnig and @aleks-f, if you want to me test linking or anything else to show this is safe, just let me know what you'd like to see.

For what it's worth, out of the many other dependencies used (Boost, tcl, Python, Qt, expat, nsis, openssl, sqlite, zlib, ...) no others have a similar check. Poco is the only one. Nobody -- certainly not me -- wants to vendor a library for a 3-line change that doesn't even affect the output, nor have to maintain that, and force our downstreams to vendor as well if they want to build the same way.

**Comment by babywonderland** [comment]
This is still an issue and I'd still like it fixed. I'm still willing to test if necessary. If @obiltschnig and @aleks-f have seen this and rejected the request, then close it, but otherwise I'd like to stop carrying a fork of Poco just for this.
