### ISSUE TITLE
Upgrading PCRE to 8.44 is it in immediate plan?

### ISSUE THREAD

**Issue by p-neels** [pocoproject/poco#3044]
PCRE 8.43 is having below mentioned Vulnerability.
https://vuldb.com/?id.156752

**Comment by p-neels** [comment]
@obiltschnig Is there any date planned for release of 1.10.2 version of POCO?

**Comment by obiltschnig** [comment]
Probably some time in August, as time permits.

**Comment by hanusek** [comment]
```The older, but still widely deployed PCRE library, originally released in 1997, is at version 8.45. This version of PCRE is now at end of life, and is no longer being actively maintained. Version 8.45 is expected to be the final release of the older PCRE library, and new projects should use PCRE2 instead.```
