### ISSUE TITLE
Base64Decoder does not validate input

### ISSUE THREAD

**Issue by sirzooro** [pocoproject/poco#3048]
Base64Decoder does not validate input. I tried to decode some invalid base64 string (with invalid characters) and it did not complain.

**Comment by FastInvite2k2** [comment]
At least it didn't crash!

**Comment by obiltschnig** [comment]
It does validate input and it will complain by setting the stream state to bad.

**Comment by sirzooro** [comment]
Thanks for update. Could you update documentation for Base64Decoder? It does not say anything about validation and code does not throw exception, so I thought that there is no validation.

**Comment by obiltschnig** [comment]
That behavior (just setting the bad bit) is pretty standard for iostreams, though, as the higher-level iostreams operations swallow any exceptions thrown by streambuf operations.
