### ISSUE TITLE
Compile error on RHEL 7.8 platform with devtoolset-9-9.1 toolchain

### ISSUE THREAD

**Issue by elemings** [pocoproject/poco#3054]
https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/Data/PostgreSQL/src/SessionHandle.cpp#L554

** Compiling src/SessionHandle.cpp (debug, shared)
g++ -Iinclude -I/Develop/Sources/poco-1.10.1-all/CppUnit/include -I/Develop/Sources/poco-1.10.1-all/Foundation/include -I/Develop/Sources/poco-1.10.1-all/Encodings/include -I/Develop/Sources/poco-1.10.1-all/XML/include -I/Develop/Sources/poco-1.10.1-all/JSON/include -I/Develop/Sources/poco-1.10.1-all/Util/include -I/Develop/Sources/poco-1.10.1-all/Net/include -I/Develop/Sources/poco-1.10.1-all/Crypto/include -I/Develop/Sources/poco-1.10.1-all/NetSSL_OpenSSL/include -I/Develop/Sources/poco-1.10.1-all/JWT/include -I/Develop/Sources/poco-1.10.1-all/Data/include -I/Develop/Sources/poco-1.10.1-all/Data/SQLite/include -I/Develop/Sources/poco-1.10.1-all/Data/ODBC/include -I/Develop/Sources/poco-1.10.1-all/Data/MySQL/include -I/Develop/Sources/poco-1.10.1-all/Data/PostgreSQL/include -I/Develop/Sources/poco-1.10.1-all/Zip/include -I/Develop/Sources/poco-1.10.1-all/PageCompiler/include -I/Develop/Sources/poco-1.10.1-all/PageCompiler/File2Page/include -I/Develop/Sources/poco-1.10.1-all/MongoDB/include -I/Develop/Sources/poco-1.10.1-all/Redis/include   -Wall -Wno-sign-compare -DPOCO_BUILD_HOST='"'bcu-wks041.nix1.grn.bouco.ngc'"' -DPOCO_TARGET_OSNAME='"'Linux'"' -DPOCO_TARGET_OSARCH='"'x86_64'"'  -D_XOPEN_SOURCE=600 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -c src/SessionHandle.cpp -o /Develop/Builds/poco-1.10.1-all/Data/PostgreSQL/obj/Linux/x86_64/debug_shared/SessionHandle.o
src/SessionHandle.cpp: In member function 'Poco::Data::PostgreSQL::SessionParametersMap Poco::Data::PostgreSQL::SessionHandle::connectionParameters() const':
src/SessionHandle.cpp:554:24: error: 'PQconninfo' was not declared in this scope; did you mean 'PQconninfoFree'?
  554 |   ptrConnInfoOptions = PQconninfo(_pConnection);
      |                        ^~~~~~~~~~
      |                        PQconninfoFree
make[1]: *** [/Develop/Sources/poco-1.10.1-all/build/rules/compile:57: /Develop/Builds/poco-1.10.1-all/Data/PostgreSQL/obj/Linux/x86_64/debug_shared/SessionHandle.o] Error 1
make[1]: Leaving directory '/Develop/Sources/poco-1.10.1-all/Data/PostgreSQL'
make: *** [Makefile:297: Data/PostgreSQL-libexec] Error 2
[1]+  Exit 2                  make &>make.`dts`

**Comment by songxiaokui** [comment]
I have the same problem, how to solve it， please

**Comment by songxiaokui** [comment]
err info:

[ 94%] Building CXX object Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/src/SessionHandle.cpp.o
/home/yskj/hhsy/devops/centos_install/poco-poco-1.10.1-release/Data/PostgreSQL/src/SessionHandle.cpp: In member function ‘Poco::Data::PostgreSQL::SessionParametersMap Poco::Data::PostgreSQL::SessionHandle::connectionParameters() const’:
/home/yskj/hhsy/devops/centos_install/poco-poco-1.10.1-release/Data/PostgreSQL/src/SessionHandle.cpp:554:24: error: ‘PQconninfo’ was not declared in this scope; did you mean ‘PQconninfoFree’?
  554 |   ptrConnInfoOptions = PQconninfo(_pConnection);
      |                        ^~~~~~~~~~
      |                        PQconninfoFree
gmake[2]: *** [Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/build.make:141: Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/src/SessionHandle.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:804: Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
