### ISSUE TITLE
Inconsistent behavior ConsoleChannel vs. WindowsConsoleChannel

### ISSUE THREAD

**Issue by felfert** [pocoproject/poco#3056]
Current behavior:

Poco::ConsoleChannel uses std::clog by default, which implies output to **stderr**.
Poco::WindowsConsoleChannel writes (hardcoded) to **stdout** instead.

Correct behavior:

WindowsConsoleChannel should write to stderr by default as well, because this does not interfer with "regular" output to stdout.

Should be trivial to fix (just replacing 2 occurrences of STANDARD_OUTPUT_HANDLE by STANDARD_ERROR_HANDLE in WindowsConsoleChannel.cpp). Do you want a PR for that?

Cheers
 -Fritz

**Comment by obiltschnig** [comment]
Makes sense, yes, please.
