### ISSUE TITLE
SocketImpl::bind --> bind wrong config

### ISSUE THREAD

**Issue by AdrianGersbach-EH** [pocoproject/poco#3061]
Hi there,

In our project we have to run multiple Syslog server instances. This was possible up to Poco v1.9.0. With Poco v1.9.1 the void SocketImpl::bind(const SocketAddress& address, bool reuseAddress) changed and it was no longer possible. In order to still be able to run multiple instances we have to tweak the Poco lib every time a new version is released. I was wondering why the change in the SocketImpl::bind method was made from v1.9.0 to v1.9.1 and if it is correct / needed? Would it be possible to revert the change to the v1.9.0? The change has later also been applied to SocketImpl::bind6.

If "true" for reuse port is not correct shouldn't there be an additional parameter e.g. bool reusePort instead of using reuseAddress also for the port!? 

Until v1.9.0 SocketImpl::bind used to look like this
void SocketImpl::bind(const SocketAddress& address, bool reuseAddress)
{
bind(address, reuseAddress, **true**);
}

Starting with v1.9.1 SocketImpl::bind changed the true to reuseAddress.
void SocketImpl::bind(const SocketAddress& address, bool reuseAddress)
{
bind(address, reuseAddress, **reuseAddress**);
}

**Comment by obiltschnig** [comment]
Setting reusePort to true turned out to be a not-so-good idea, so this was changed.

The actual issue here is providing an option to pass the reusePort flag to RemoteSyslogListener (see #2892), so this is what we'll do in 1.10.2.

**Comment by obiltschnig** [comment]
See #3242
