### ISSUE TITLE
Linux -> Windows MinGW-w64 cross-compile broken and/or not supported

### ISSUE THREAD

**Issue by ghost** [pocoproject/poco#3063]
I can't seem to cross-compile Poco for Windows from Linux via MinGW-w64. After several days, I'm past the point of optimism. I have poked at Poco's cmake files, and they are confusing.

The first step (make includes in Foundation/include/Poco/UnWindows.h lowercase for host filesystem/headers) is easy, but a bunch of other issues deriving from Poco's use of UNIX flags and kin break the build, because Windows is not Unix. The host platform is Unix, but the target platform (the one that really matters) is Windows/MinGW and does not have access to Unix stuff.

I feel like I am missing the vital key to making this work, so please suggest/help. Thank you.

**Comment by bas524** [comment]
Did you try to use cmake.toolchain file? I mean, you can create this file and try to build poco like you build it for arm from x86

**Comment by fluffrabbit** [comment]
@bas524 I tried to use this:

```
# Modified Linux-Win32 cross-compilation toolchain. Original version at:
# https://cmake.org/Wiki/images/c/c2/Toolchain-cross-mingw32-linux.cmake

# the name of the target operating system
SET(CMAKE_SYSTEM_NAME Windows)

# Choose an appropriate compiler prefix

# for classical mingw32
# see http://www.mingw.org/
#set(COMPILER_PREFIX "i586-mingw32msvc")

# for 32 or 64 bits mingw-w64
# see http://mingw-w64.sourceforge.net/
set(COMPILER_PREFIX "i686-w64-mingw32")
#set(COMPILER_PREFIX "x86_64-w64-mingw32"

# which compilers to use for C and C++
find_program(CMAKE_RC_COMPILER NAMES ${COMPILER_PREFIX}-windres)
#SET(CMAKE_RC_COMPILER ${COMPILER_PREFIX}-windres)
find_program(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-gcc)
#SET(CMAKE_C_COMPILER ${COMPILER_PREFIX}-gcc)
find_program(CMAKE_CXX_COMPILER NAMES ${COMPILER_PREFIX}-g++)
#SET(CMAKE_CXX_COMPILER ${COMPILER_PREFIX}-g++)


# here is the target environment located
SET(CMAKE_FIND_ROOT_PATH  /usr/${COMPILER_PREFIX})

# adjust the default behaviour of the FIND_XXX() commands:
# search headers and libraries in the target environment, search 
# programs in the host environment
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

No luck though. x86 Linux -> ARM Linux is still Linux. I'm on the path to replacing Poco with Boost now, so it's not a big deal if this doesn't work.

**Comment by bas524** [comment]
@fluffrabbit 
You tried to build 32bit poco with mingw-w64 on x86_84 Linux. Am I right?

**Comment by fluffrabbit** [comment]
Yes. Just so there's no confusion, MinGW-w64 has completely superseded original MinGW, and comes with 32-bit and 64-bit variants. The errors were related to Unix vs Windows APIs, not linker issues or register size.

**Comment by bevinhex** [comment]
Been trying to get poco cross compiled for windows for weeks now, 1.9.4 compiles for linux 64/32 bit fine with conan, but not for windows with mingw
here is my conanfile.txt
```
[requires]
#boost/1.69.0
#poco/1.9.4
poco/1.10.1

[options]
poco:enable_data_mysql=False
poco:enable_data_postgresql=False

[generators]
cmake
```
here I had to disable mysql/postgresql in order to remobe apr dependencies, apr is not compiling for platforms other than linux 64bit.

here is CMaleLists.linux.64:
```
cmake_minimum_required(VERSION 3.13.4)
project(ipb-residential)

add_definitions("-std=c++11")

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_library(adder src/lib.cpp)
target_link_libraries(adder ${CONAN_LIBS})

add_executable(${PROJECT_NAME} src/main.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE adder)
```
CMakeLists.Linux.32
```
cmake_minimum_required(VERSION 3.13.4)
project(ipb-residential)

add_definitions("-std=c++11")
set(CMAKE_CXX_FLAGS "-m32")
set(CMAKE_C_FLAGS "-m32")

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_library(adder src/lib.cpp)
target_link_libraries(adder ${CONAN_LIBS})

add_executable(${PROJECT_NAME} src/main.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE adder)
```
CMakeLists.windows.64:
```
cmake_minimum_required(VERSION 3.13.4)
project(ipb-residential)

add_definitions("-std=c++11")

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_EXE_LINKER_FLAGS "-static")
set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_MC_COMPILER x86_64-w64-mingw32-windmc)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_library(adder src/lib.cpp)
target_link_libraries(adder ${CONAN_LIBS})

add_executable(${PROJECT_NAME} src/main.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE adder)
```

with files above , I'm stuck making it work for windows, had trouble finding `mc.exe` earlier, so I created a link for `mingw-windmc` but now giving errors about not finding `WinSocks.h`, read in some thread saying mingw is supported, but I doubt it is working

**Comment by bevinhex** [comment]
so far can compile both 1.9.4 for linux, 1.10.1 for linux (with mysql/postgres disabled to avoid apr problem), but not for windows
