### ISSUE TITLE
Unable to build x64 Poco libraries with MS Visual Studio 2019

### ISSUE THREAD

**Issue by htartisan** [pocoproject/poco#3085]
I have tried a few different versions of the Poco library (including the latest version here), and I have been unable to build an x64 version of Poco using VisualStudio2019.  

**Note**: I have been able to build 32 bit versions in the past.

**Comment by bas524** [comment]
You can have those problem when old version of poco-headers visible in new build. Did you try build poco on clean virtual machine with msvc2019?
