### ISSUE TITLE
Support for building Arm64 Apple Silicon

### ISSUE THREAD

**Issue by jarrocha** [pocoproject/poco#3097]
Hello guys,
Do you currently have a way to build for arm64?
I have seen this parameter being used: POCO_TARGET_OSARCH=arm64
But, do you recommend also specifying a certain SDK?

Just wondering if any one has tried this before? Thanks.

**Comment by jarrocha** [comment]
For those needing guidance, I created a config based on Darwin64-clang-libc++, I changed x86_64 to arm64. Also during the compilation process I added this to the make command. For the minimum version, I don't know if it is required.

`make MACOSX_DEPLOYMENT_TARGET=11.0 MACOSX_SDK_VERSION_MIN=10.15 SDKROOT=/Applications/Xcode12Beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk`

**Comment by obiltschnig** [comment]
re-open as a reminder for 1.10.2

**Comment by obiltschnig** [comment]
Build configs should now build for the native architecture. Cross-compiling possible in the usual way by specifying `POCO_TARGET_OSARCH`, e.g., `POCO_TARGET_OSARCH=arm64`.
