### ISSUE TITLE
PocoMacros.cmake incorrectly detects MSYS2/MINGW64 

### ISSUE THREAD

**Issue by HFTrader** [pocoproject/poco#3110]
When going through the Conan tutorial under MSYS2, I hit `conan install` and then all libraries compile fine except for Poco, which breaks on PocoMacros.cmake line 64. Apparently it is strying to find Visual Studio message compiler on all windows platforms. Therefore it is not prepared for the case where one is compiling under a Mingw64 environment. 

```
-- Poco package version: 1.9.4
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Checking for C++14 compiler
-- Checking for C++14 compiler - available
-- Setting Poco build type - Release
CMake Error at source_subfolder/cmake/PocoMacros.cmake:46 (message):
  message compiler not found: required to build
Call Stack (most recent call first):
  source_subfolder/CMakeLists.txt:86 (include)

```

By the way, if you wish to replicate this, install MSYS2 (https://www.msys2.org/) then install pip3/conan then create a `msys2` profile with the following content:

```
$ conan profile show msys2
Configuration for profile msys2:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

Then follow the Conan tutorial (https://docs.conan.io/en/latest/getting_started.html). It should break on Poco, the last library.

```
$ git clone https://github.com/conan-io/examples.git && cd examples/libraries/poco/md5
$ mkdir build && cd build
$ conan install .. --profile=msys2 --build=missing
```

**Comment by dentra** [comment]
msys2 already have a patch for this https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-poco/011-cmake-mingw.patch
