### ISSUE TITLE
MySQL C connector version 8.0

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3111]
Something changed in MySQL connector 8.xxx I don't know if in the v7 too but before I was using the v6 without problem.
With 8 the MySQL backend did not compile correctly.
the problems are:

- There's no more my_bool that now seems to be a real bool not a char like before
- the structures  MYSQL MYSQL_STMT are now already declared
- MYSQL_SECURE_AUTH define is no longer supported

I'm going to see if I can make it work and than if I succeed I can make a pull request

**Comment by obiltschnig** [comment]
Hm, this should have been fixed in 1.10.

**Comment by micheleselea** [comment]
Ah....ok sorry I did not realized, I was just going to switch to 1.10 today ;)

**Comment by micheleselea** [comment]
@obiltschnig correct all is working fine with 1.10.1, sorry for the posted issue
