### ISSUE TITLE
SocketReactor 1.10.1

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3113]
I think something wrong in new socket reactor 1.10 that was correct before. I try to explain.
The point is the onTimeout and onBusy functions.
If you connect to a socketreactor with a telnet like application, all works good, because the `_pollSet.poll(_timeout)` do the job to wait timeout before call onTimeout if you do not send bytes.
The problem is if you connect to the socket reactor making an SSL connection. After the handshake the `_pollSet.poll(_timeout)` become useless and returns immediately with a onBusy and onTimeout call.
I don't know why before the behavior was good, perhaps `Socket::select(readable, writable, except, _timeout)` works a little bit different.
I think the solution is to put a `Thread::trySleep(static_cast<long>(_timeout.totalMilliseconds()));` or something like that in the onTimeout function.
Do you think it's clear enough? @obiltschnig do you think is there a better solution?

**Comment by micheleselea** [comment]
I'm using windows, so the old Socket::select was doing  `::select` instead the `.poo() `is doing the `WSAPoll`
probably that is the difference

**Comment by micheleselea** [comment]
that is not good...
https://daniel.haxx.se/blog/2012/10/10/wsapoll-is-broken/

**Comment by micheleselea** [comment]
we can have the same problem in the `HTTPServerSession::hasMoreRequests()` that use the
 `socket().poll(getTimeout(), Socket::SELECT_READ);` or `socket().poll(_keepAliveTimeout, Socket::SELECT_READ);`
both end up to the WSAPoll funtion

**Comment by micheleselea** [comment]
I think probably there something wrong with my writable notifications, hold on, I'm going to dig into and let you know

**Comment by micheleselea** [comment]
the `HTTPServerSession::hasMoreRequests()` works without problem so is something related to the add/remove of onreadable or onwritable notifications

**Comment by micheleselea** [comment]
I think the problem is in the difference between the preview implementation of `SocketReactor::addEventHandler` and the new one.
before
```
void SocketReactor::addEventHandler(const Socket& socket, const Poco::AbstractObserver& observer)
{
	NotifierPtr pNotifier;
	{
		FastMutex::ScopedLock lock(_mutex);
		
		EventHandlerMap::iterator it = _handlers.find(socket);
		if (it == _handlers.end())
		{
			pNotifier = new SocketNotifier(socket);
			_handlers[socket] = pNotifier;
		}
		else pNotifier = it->second;
	}
	if (!pNotifier->hasObserver(observer))
		pNotifier->addObserver(this, observer);
}
```
after
```
void SocketReactor::addEventHandler(const Socket& socket, const Poco::AbstractObserver& observer)
{
	NotifierPtr pNotifier = getNotifier(socket, true);

	if (!pNotifier->hasObserver(observer)) pNotifier->addObserver(this, observer);

	int mode = 0;
	if (pNotifier->accepts(_pReadableNotification)) mode |= PollSet::POLL_READ;
	if (pNotifier->accepts(_pWritableNotification)) mode |= PollSet::POLL_WRITE;
	if (pNotifier->accepts(_pErrorNotification))    mode |= PollSet::POLL_ERROR;
	if (mode) _pollSet.add(socket, mode);
}
```
in the old implementation a sequence of addEventHandler on the same onReadable has no effect, just the first one was take. In the new one the add/remove handler is much more critical because you can end up with a pollset having _pollfds with the same socket pushed a lot of time.
Now probably I'm doing something wrong with add/remove handler, and I'm going to check it, but the behavior is changed.

For example you can reproduce the issue if you do an addEventHandler for ReadableNotification inside the onReadable callback, you will see the _pollfds fill with the same socket handler more times. That is obviously a misuse of addEventHandler, but I think it's what I'm somehow end up with

**Comment by micheleselea** [comment]
I'm trying using `hasEventHandler` before adding or removing observer but I still end up with a wrong _pollfds. It's quite tricky...I have to figure out what is the problem...

**Comment by micheleselea** [comment]
PollSet+SocketReactor it's a tricky join :)
Not able yet to figure out how to make it work. Something happen in .add .remote functions of PollSet
Maybe the _addMap _removeSet and _pollfds have somthing to change but I have to figure out how

**Comment by micheleselea** [comment]
the problem with the PollSet is that if you enable the Readable Error and Writeble notification on reactor, and than you try to remove only the Writable, you remove even the Readable and Error..that is the main problem, so for every remove you should add the other, but if you do an Add before really do the poll() you end up with two socket. I don't know if I misuse the notifications or something is missing

**Comment by micheleselea** [comment]
I manage to use the SocketReactor with the new PollSet, basically you cannot ever do any remove observer in your code except the remove you need to close all, otherwise something bad will happen for sure.
Another strange thing happen to me is that if you register an observer in the end you have a Socket map like 
`EventHandlerMap::iterator it = _handlers.find(socket);`
that is quite tricky because if you switch from socket to securesocket that map is not guarantee to match the same socket again: PollSet use fd so it's safe to upgrade to secure socket

**Comment by micheleselea** [comment]
I think EventHandlerMap should take fd ad key andò noto socket classe, because in the end you want to add  an handler to the socket not to the class socket

**Comment by obiltschnig** [comment]
cc @aleks-f

**Comment by micheleselea** [comment]
Somethink like that
https://github.com/pocoproject/poco/pull/3115
at least to make a uniform behavior between Socket reactor and PollSet
the add/remove handler is still a problem I think

**Comment by micheleselea** [comment]
ok now https://github.com/pocoproject/poco/pull/3116 the EventHandlerMap and PollSet have the same key so the same behavior.
We should check the methods add and removeof the PollSet. Basically the problem is the vector _pollfds that is filled using che _addMap and _removeSet
The main problem is that if you want to remove only one between Readable Writable or Error, you can't. And if you do two add for the same socket between two poll() request you end up with multiple times the same socket in _pollfds. Probably the best way is to update directly the _pollfds vector
