### ISSUE TITLE
Sample for FTPSClientSession produces exception, the message not meaningful

### ISSUE THREAD

**Issue by meolic** [pocoproject/poco#3118]
On Linux, I have compiled the sample poco-1.10.1-all/NetSSL_OpenSSL/samples/download/src/download.cpp. Then I have copied rootcert.pem next to the executable and tried to connect to my SFTP server. I got an exception that does not help me to understand the problem. Like this:

~~~bash
./download ftps://user:passwd@server:22/file.txt
FTP Exception: Cannot receive status message: SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
~~~

It would be enough to mention the explanation and solution in the source code.

**Comment by meolic** [comment]
This is the report from using sftp program on the same computer.

~~~
$ sftp -v user:passwd@server:22/file.txt
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /home/user/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to server [IP] port 22.
debug1: Connection established.
debug1: identity file /home/user/.ssh/id_rsa type 0
debug1: identity file /home/user/.ssh/id_rsa-cert type -1
debug1: identity file /home/user/.ssh/id_dsa type -1
debug1: identity file /home/user/.ssh/id_dsa-cert type -1
debug1: identity file /home/user/.ssh/id_ecdsa type -1
debug1: identity file /home/user/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/user/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/user/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/user/.ssh/id_ed25519 type -1
debug1: identity file /home/user/.ssh/id_ed25519-cert type -1
debug1: identity file /home/user/.ssh/id_ed25519_sk type -1
debug1: identity file /home/user/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/user/.ssh/id_xmss type -1
debug1: identity file /home/user/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4p1 Debian-10+deb9u7
debug1: match: OpenSSH_7.4p1 Debian-10+deb9u7 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to server:22 as 'passwd'
...
~~~

**Comment by micheleselea** [comment]
FTPSClientSession support explicit FTPS connections. SFTP instead use ssh protocol usually over port 22 or 993 implicit SSL. FTPS use explicit SSL connection over port 21

**Comment by micheleselea** [comment]
The error you receive is about the reading of welcome message that the client can't receive from server probably because server want to established an SSL connection implicitly

**Comment by meolic** [comment]
Oh, my mistake. I mixed up SFTP anf FTPS services. In fact, I want to get a file from SFTP on port 22. Although, this is not Q&A, can I get a small suggestion, how to do this (which class to use or which sample to check as a starting point). I can create question on SO if you prefer that.

**Comment by micheleselea** [comment]
I never managed to use an FTO over explicit SSL connection. I think that basically you should create your own SecureStreamSocket than use FTPSClientSession giving the secure socket and context.
Probably we can extend the behavior to support it out of the box, but right now if you want you can try that way

**Comment by meolic** [comment]
Maybe, SCP is supported?

**Comment by micheleselea** [comment]
do you mean the secure copy file of linux? it's not an FTP connection, so it's not supported

**Comment by meolic** [comment]
On some old code from GitHub (2007), I can see reference to #include "Poco/SSH/SCPStream.h". Obviously, not included in Poco::Net in the actual package. Thank you a lot, I suggest closing this issue because it is not a real issue - just a feature on the wish list.

**Comment by aleks-f** [comment]
@meolic https://github.com/pocoproject/sandbox/blob/master/SSH/include/Poco/SSH/SCPStream.h
