### ISSUE TITLE
Error building with MinGW from a Hunter package

### ISSUE THREAD

**Issue by steinio** [pocoproject/poco#3121]
I am adding PocoCpp as specified in the hunter example, using the latest hunter tag with cmake version 3.17.3 that came with MSYS2, compiling with mingw gcc version 10.1.0.

Error is 
`
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/mprapi.h:16,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/iprtrmib.h:12,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/Iphlpapi.h:15,
                 from C:/Users/steinito/.hunter/_Base/43ffd06/a2d374d/647ab83/Build/PocoCpp/Source/Foundation/include/Poco/UnWindows.h:33,
                 from C:/Users/steinito/.hunter/_Base/43ffd06/a2d374d/647ab83/Build/PocoCpp/Source/Foundation/include/Poco/Platform_WIN32.h:22,
                 from C:/Users/steinito/.hunter/_Base/43ffd06/a2d374d/647ab83/Build/PocoCpp/Source/Foundation/include/Poco/Foundation.h:100,
                 from C:/Users/steinito/.hunter/_Base/43ffd06/a2d374d/647ab83/Build/PocoCpp/Source/Net/include/Poco/Net/ICMPPacket.h:21,
                 from C:\Users\steinito\.hunter\_Base\43ffd06\a2d374d\647ab83\Build\PocoCpp\Source\Net\src\ICMPPacket.cpp:15:
C:/Users/steinito/.hunter/_Base/43ffd06/a2d374d/647ab83/Build/PocoCpp/Source/Net/include/Poco/Net/ICMPv4PacketImpl.h:72:3: error: expected identifier before '(' token
   72 |   TIMESTAMP_REQUEST,
`

I can build the same project on ubuntu without any errors, and I can also build it with Visual Studio 2017 using cmake as well, , so the project and CMakeLists.txt does not seem to have any errors.

I have noticed someone posting duplicate error for Conan as well, without any answers yet in that issue, on the conan git page.

**Comment by madebr** [comment]
I can reproduce this with poco 1.10.1.

`Net/include/Poco/Net/ICMPv4PacketImpl.h` defines `TIMESTAMP_REQUEST` here:
https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/Net/include/Poco/Net/ICMPv4PacketImpl.h#L72

mingw-headers defines `TIMESTAMP_REQUEST` here:
https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/wincrypt.h#l1584
