### ISSUE TITLE
cross compile for qnx 7.0.0 failed

### ISSUE THREAD

**Issue by zoro0312** [pocoproject/poco#3124]
I am trying to compile poco with qnx sdp700. I compile with cmake:

cmake .. -DCMAKE_TOOLCHAIN_FILE=qnx.cmake

and I got this error:

[  0%] Building CXX object Foundation/CMakeFiles/Foundation.dir/src/Var.cpp.o                                                                                           
In file included from /media/lyq/Exten/Qualcomm/8155/13.1/qnx700_1301/target/qnx7/usr/include/c++/v1/algorithm:628:0,                                                   
                 from /media/lyq/Exten/Qualcomm/8155/13.1/qnx700_1301/target/qnx7/usr/include/c++/v1/string:439,                                                        
                 from /media/lyq/Exten/ROS/melodic_src/3rd-party/poco/Foundation/include/Poco/Bugcheck.h:22,                                                            
                 from /media/lyq/Exten/ROS/melodic_src/3rd-party/poco/Foundation/include/Poco/Foundation.h:159,                                                         
                 from /media/lyq/Exten/ROS/melodic_src/3rd-party/poco/Foundation/include/Poco/Dynamic/Var.h:21,                                                         
                 from /media/lyq/Exten/ROS/melodic_src/3rd-party/poco/Foundation/src/Var.cpp:15:                                                                        
/media/lyq/Exten/Qualcomm/8155/13.1/qnx700_1301/target/qnx7/usr/include/c++/v1/memory: In instantiation of 'struct std::__1::allocator_traits<std::__1::allocator_traits
<std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var> > >::rebind_alloc<tsl::de
tail_ordered_hash::bucket_entry> >':
/media/lyq/Exten/Qualcomm/8155/13.1/qnx700_1301/target/qnx7/usr/include/c++/v1/vector:338:54:   required from 'class std::__1::__vector_base<tsl::detail_ordered_hash::b
ucket_entry, std::__1::allocator_traits<std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::
Dynamic::Var> > >::rebind_alloc<tsl::detail_ordered_hash::bucket_entry> >'
/media/lyq/Exten/Qualcomm/8155/13.1/qnx700_1301/target/qnx7/usr/include/c++/v1/vector:458:29:   required from 'class std::__1::vector<tsl::detail_ordered_hash::bucket_e
ntry, std::__1::allocator_traits<std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic
::Var> > >::rebind_alloc<tsl::detail_ordered_hash::bucket_entry> >'
/media/lyq/Exten/ROS/melodic_src/3rd-party/poco/Foundation/include/Poco/ordered_hash.h:945:47:   required from 'class tsl::detail_ordered_hash::ordered_hash<std::__1::p
air<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var>, tsl::ordered_map<std::__1::basic_string<char, std::__1::
char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >
 >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_strin
g<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var> >, std::__1::deque<std::__1::pair<std::__1::basic_string<char, std::__1::char_trai
ts<char>, std::__1::allocator<char> >, Poco::Dynamic::Var>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloc
ator<char> >, Poco::Dynamic::Var> > > >::KeySelect, tsl::ordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynami
c::Var, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1
::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<cha
r> >, Poco::Dynamic::Var> >, std::__1::deque<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var>, 
std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var> > > >::ValueSelect, std::_
_1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<
char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dy
namic::Var> >, std::__1::deque<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var>, std::__1::allo
cator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var> > > >'
/media/lyq/Exten/ROS/melodic_src/3rd-party/poco/Foundation/include/Poco/ordered_map.h:106:43:   required from 'class tsl::ordered_map<std::__1::basic_string<char, std::
__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
ar> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_
string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var> >, std::__1::deque<std::__1::pair<std::__1::basic_string<char, std::__1::char
_traits<char>, std::__1::allocator<char> >, Poco::Dynamic::Var>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::
allocator<char> >, Poco::Dynamic::Var> > > >'

**Comment by aleks-f** [comment]
yeah, well QNX became somewhat exotic platform; unless you are willing to fix it yourself and send pull request, I suggest considering the [paid support](https://pocoproject.org/support.html) route

**Comment by zoro0312** [comment]
Thanks for reply. I saw there is qnx build configuration in  source code,  so isn't it been tested?

**Comment by aleks-f** [comment]
it was, Poco used to compile and run on QNX, but it was long time ago.

**Comment by obiltschnig** [comment]
Well, not that long ago, about 3 years - at least that's when I last worked on making things work on QNX for a customer.
Main reason why we no longer do any regular work on QNX is because apparently it's no longer possible to get free QNX licenses for testing, an a regular QNX license would be too expensive given the circumstances.

**Comment by Bjoe** [comment]
In the past, poco was also building on BB10 (BB10 used as platform QNX). They used [dinktum](http://dinkumware.com/) as standard library. I'm not sure if this is still the case.
You use the `qnx.cmake` toolchain file also for "other" projects and it works?

**Comment by aleks-f** [comment]
@wenzuoyi we can help you, but please read the answers above, the parts about QNX license and paid support in particular
