### ISSUE TITLE
POCO_STATIC has been deprecated

### ISSUE THREAD

**Issue by DevByStarlight** [pocoproject/poco#3133]
```
CMake Warning at CMakeLists.txt:57 (message):
  POCO_STATIC has been deprecated.  Please use BUILD_SHARED_LIBS instead.
```
Cool. Sounds fine to me.
However, subtle thing, maybe this could read as:
```... Please use BUILD_SHARED_LIBS=OFF instead.```

(When I initially saw this warning I "panicked" and thought "what, no more static builds?")

**Comment by obiltschnig** [comment]
See #3217
