### ISSUE TITLE
parse multipart/form-data lost key of file

### ISSUE THREAD

**Issue by qinzhenyi1314** [pocoproject/poco#3142]
I have post request in postaman  Content-Type is multipart/form-data
after i parse  request i find lost the key of file 

postman i set like this
`curl --location --request POST 'http://10.0.10.7:9991/sap/process' \`
`--header 'Content-Type: application/json;charset=UTF-8' \`
`--form 'img_data=@/E:/source/20200514143541093_0.jpg' \`
`--form 'img_size=1025244' \`
`--form 'img_id=qin' \`
`--form 'img_type=jpg'`

poco parse code like this 
`CDownPartHandler partHandler;`
`Poco::Net::NameValueCollection::ConstIterator it;`
`Poco::Net::HTMLForm  form(request, request.stream(), partHandler);`

but i only get three of img_size img_id img_type ,i can not get  **img_data** ,i print stream  it have  img_data 

stream print like this
`
----------------------------905311281546385092305379
Content-Disposition: form-data; name="img_data"; filename="20200514143541093_0.jpg"
Content-Type: image/jpeg

HIJK9璬?3ff056c3fd7002f1
......
......
......
媥峺拀憒寋寋寊媨墊垀?坹妟墇坺媫寑墎?墊厈厈噡??唨?墊墌厐儈厊儈剗唥坿墍噥唥厁剎厈剗剓厇唞剒儂€{倈倉儈噠墋坿墋
----------------------------905311281546385092305379
Content-Disposition: form-data; name="img_size"

1025244
----------------------------905311281546385092305379
Content-Disposition: form-data; name="img_id"

qin
----------------------------905311281546385092305379
Content-Disposition: form-data; name="img_type"

jpg
----------------------------905311281546385092305379--
 `

![Snipaste_2020-11-17_23-53-13](https://user-images.githubusercontent.com/22737593/99412788-1278ae80-2930-11eb-9587-ba912a78724c.png)

![错误图片](https://user-images.githubusercontent.com/22737593/99412634-ec530e80-292f-11eb-993f-a6f874f3a11c.png)

**Comment by qinzhenyi1314** [comment]
Can anyone help me? Thanks a lot~

**Comment by Mironenko** [comment]
```
void HTMLForm::readMultipart(std::istream& istr, PartHandler& handler)
{
	static const int eof = std::char_traits<char>::eof();

	int fields = 0;
	MultipartReader reader(istr, _boundary);
	while (reader.hasNextPart())
	{
		if (_fieldLimit > 0 && fields == _fieldLimit)
			throw HTMLFormException("Too many form fields");
		MessageHeader header;
		reader.nextPart(header);
		std::string disp;
		NameValueCollection params;
		if (header.has("Content-Disposition"))
		{
			std::string cd = header.get("Content-Disposition");
			MessageHeader::splitParameters(cd, disp, params);
		}
		if (params.has("filename"))
		{
			handler.handlePart(header, reader.stream());
			// Ensure that the complete part has been read.
			while (reader.stream().good()) reader.stream().get();
		}
		else
		{
			std::string name = params["name"];
			std::string value;
			std::istream& istr = reader.stream();
			int ch = istr.get();
			while (ch != eof)
			{
				value += (char) ch;
				ch = istr.get();
			}
			add(name, value);
		}
		++fields;
	}
}
```

The part you are missing has got "filename" param in it, so it won't be added to name-value collection. You need to handle this field in your `CDownPartHandler partHandler`.

**Comment by qinzhenyi1314** [comment]
> readMultipart

Thanks a lot,i handle in CDownPartHandler and got file~
