### ISSUE TITLE
A sample how to use HTTPChunkedStreamBuf.

### ISSUE THREAD

**Issue by lazyfish** [pocoproject/poco#3143]
I've been using Poco HTTPServer for handling simple GET requests.
Now I'm looking for a way to send a binary file, which is generated on the fly. It seems that using HTTPChunkedStreamBuf is the way to go. Unfortunately I cannot figure out how to introduce HTTPChunkedStreamBuf into my code, based on HTTPTimeServer sample. Documentation saying "This is the streambuf class used for reading and writing HTTP message bodies in chunked transfer coding" does not help much really. 
Please, a simple sample.

**Comment by obiltschnig** [comment]
You don't use `HTTPChunkedStreamBuf` directly. In your request handler, you simply add:
```
response.setChunkedTransferEncoding(true);
```
and then write your content to the response stream, as can be seen in the [HTTPTimeServer sample](https://github.com/pocoproject/poco/blob/master/Net/samples/HTTPTimeServer/src/HTTPTimeServer.cpp#L68).

**Comment by lazyfish** [comment]
Thank you for your time.

Considering it takes time to generate my file to send and I want to send it by chunks while it's still being generated:
Is there a max chunk size?
Is the same handler's handleRequest called after I do send some data (so I should keep some handler id)? 
Is it ok to write nothing if no data ready yet?
How do I notify client of end of file?
