### ISSUE TITLE
throw NoMessageException When reuse  HTTPClientSession 

### ISSUE THREAD

**Issue by 1bbb** [pocoproject/poco#3150]
Hi:

I'm building a simple http client using Poco 1.10.0 with Visual Studio 2017 on Windows 10

when I reuse  **global_session**  ,  There is a chance that  threw  **NoMessageException**

```
std::string getRequest(const std::string& relativeUrl) {
	try {
		HTTPRequest request(HTTPRequest::HTTP_GET, relativeUrl, HTTPMessage::HTTP_1_1);
		global_session.sendRequest(request);
		HTTPResponse response;
		std::istream& rs = global_session.receiveResponse(response);
		std::string msg{};
		StreamCopier::copyToString(rs, msg);
		return msg;
	}
	catch (Poco::Net::NoMessageException& e) {		
	}
	catch (Poco::Exception& e) {		
	}
	return "";
}

HTTPClientSession global_session("220.181.38.148", 8080);
void main() {
      global_session.setKeepAlive(true);
      global_session.setKeepAliveTimeout(Poco::Timespan(300,0));
      int count = 100;
      while(count --){
        getRequest("\v1");
    }
     return ;
}
```
Thanks for helping me out

**Comment by Mironenko** [comment]
Did you check, what happens on the network level, using Wireshark?

**Comment by 1bbb** [comment]
> Did you check, what happens on the network level, using Wireshark?

low probability，so I didn't check the  network data

**Comment by 1bbb** [comment]
> Did you check, what happens on the network level, using Wireshark?
I studied the source code, HTTPClientSession may not be reused

**Comment by Mironenko** [comment]
> I studied the source code, HTTPClientSession may not be reused

Still don't get the basis for that conclusion. `HTTPSession::refill` is called from `HTTPSession::get`, and it's called from `HTTP*Stream::readFromDevice`. There seems to be no problem with `HTTPSession::refill`.

The error you get may happen if you do not fully consume the previous response. Try fixing your code this way:
```
                std::string msg{};
		StreamCopier::copyToString(rs, msg);
                rs.ignore(std::numeric_limits<unsigned int>::max());
		return msg;
```

See https://github.com/pocoproject/poco/issues/2977 and https://pocoproject.org/docs/Poco.Net.HTTPClientSession.html#23006 for the explanation:

> It must be ensured that the response stream is fully consumed before sending a new request and persistent connections are enabled. Otherwise, the unread part of the response body may be treated as part of the next request's response header, resulting in a Poco::Net::MessageException being thrown.

**Comment by 1bbb** [comment]
> > I studied the source code, HTTPClientSession may not be reused
> 
> Still don't get the basis for that conclusion. `HTTPSession::refill` is called from `HTTPSession::get`, and it's called from `HTTP*Stream::readFromDevice`. There seems to be no problem with `HTTPSession::refill`.
> 
> The error you get may happen if you do not fully consume the previous response. Try fixing your code this way:
> 
> ```
>                 std::string msg{};
> 		StreamCopier::copyToString(rs, msg);
>                 rs.ignore(std::numeric_limits<unsigned int>::max());
> 		return msg;
> ```
> 
> See #2977 and https://pocoproject.org/docs/Poco.Net.HTTPClientSession.html#23006 for the explanation:
> 
> > It must be ensured that the response stream is fully consumed before sending a new request and persistent connections are enabled. Otherwise, the unread part of the response body may be treated as part of the next request's response header, resulting in a Poco::Net::MessageException being thrown.

thank you so much, I'll try your method

**Comment by 1bbb** [comment]
> > > I studied the source code, HTTPClientSession may not be reused
> > 
> > 
> > Still don't get the basis for that conclusion. `HTTPSession::refill` is called from `HTTPSession::get`, and it's called from `HTTP*Stream::readFromDevice`. There seems to be no problem with `HTTPSession::refill`.
> > The error you get may happen if you do not fully consume the previous response. Try fixing your code this way:
> > ```
> >                 std::string msg{};
> > 		StreamCopier::copyToString(rs, msg);
> >                 rs.ignore(std::numeric_limits<unsigned int>::max());
> > 		return msg;
> > ```
> > 
> > 
> > See #2977 and https://pocoproject.org/docs/Poco.Net.HTTPClientSession.html#23006 for the explanation:
> > > It must be ensured that the response stream is fully consumed before sending a new request and persistent connections are enabled. Otherwise, the unread part of the response body may be treated as part of the next request's response header, resulting in a Poco::Net::MessageException being thrown.
> 
> thank you so much, I'll try your metho

**Comment by 1bbb** [comment]
> > I studied the source code, HTTPClientSession may not be reused
> 
> Still don't get the basis for that conclusion. `HTTPSession::refill` is called from `HTTPSession::get`, and it's called from `HTTP*Stream::readFromDevice`. There seems to be no problem with `HTTPSession::refill`.
> 
> The error you get may happen if you do not fully consume the previous response. Try fixing your code this way:
> 
> ```
>                 std::string msg{};
> 		StreamCopier::copyToString(rs, msg);
>                 rs.ignore(std::numeric_limits<unsigned int>::max());
> 		return msg;
> ```
> 
> See #2977 and https://pocoproject.org/docs/Poco.Net.HTTPClientSession.html#23006 for the explanation:
> 
> > It must be ensured that the response stream is fully consumed before sending a new request and persistent connections are enabled. Otherwise, the unread part of the response body may be treated as part of the next request's response header, resulting in a Poco::Net::MessageException being thrown.

I modified the code to follow the example, but it still throw NoMessageException.
https://stackoverflow.com/questions/8980392/pocohttpclientsession-receiveresponse-throws-nomessageexception-without-any

**Comment by Mironenko** [comment]
I managed to reproduce getting `NoMessageException` from `receiveResponse`. It my case it happens when the server closes connection after the timeout shorter than expected by client. Are you sure 5 minutes is a proper timeout value for the server you access?

Still, network traffic dump would be a great help in investigating the issue. What is almost certain: connection gets closed before response is received. What causes it is the question.

By the way, there is no good solution for the race condition described: https://en.wikipedia.org/wiki/HTTP_persistent_connection#Disadvantages
> Also a race condition can occur where the client sends a request to the server at the same time that the server closes the TCP connection.[12] A server should send a 408 Request Timeout status code to the client immediately before closing the connection. When a client receives the 408 status code, after having sent the request, it may open a new connection to the server and re-send the request.[13] Not all clients will re-send the request, and many that do will only do so if the request has an idempotent HTTP method.

**Comment by 1bbb** [comment]
> I managed to reproduce getting `NoMessageException` from `receiveResponse`. It my case it happens when the server closes connection after the timeout shorter than expected by client. Are you sure 5 minutes is a proper timeout value for the server you access?
> 
> Still, network traffic dump would be a great help in investigating the issue. What is almost certain: connection gets closed before response is received. What causes it is the question.
> 
> By the way, there is no good solution for the race condition described: https://en.wikipedia.org/wiki/HTTP_persistent_connection#Disadvantages
> 
> > Also a race condition can occur where the client sends a request to the server at the same time that the server closes the TCP connection.[12] A server should send a 408 Request Timeout status code to the client immediately before closing the connection. When a client receives the 408 status code, after having sent the request, it may open a new connection to the server and re-send the request.[13] Not all clients will re-send the request, and many that do will only do so if the request has an idempotent HTTP method.

I set the timeout to 5 seconds, and hasn't  thrown `NoMessageException `  yet.
Thanks a lot
