### ISSUE TITLE
Poco::JSON::Object::getNames() is missing on Unix

### ISSUE THREAD

**Issue by nrkramer** [pocoproject/poco#3152]
Tested against version 1.10.1.

It seems that the no-argument version of `Poco::JSON::Object::getNames()` is missing on Unix, and compiler errors ensue when attempting to use the _documented_ function. The compiler suggest instead using `Poco::JSON::Object::getNames(std::vector<std::string>)`, which is available everywhere.

It's a bit difficult to create a cross-platform app when one of the functions is missing on one of the platforms.

**Comment by obiltschnig** [comment]
Both overloads of `getNames()` are available on all platforms, as the source code is the same for all platforms. Your error must come from somewhere else. We may be able to help if you show the exact compiler error you're seeing.

**Comment by nrkramer** [comment]
This is the exact compiler error on Ubuntu Linux:
`error: no matching function for call to ‘Poco::JSON::Object::getNames()`

- The CXX compiler identification is GNU 9.3.0
- bionic/universe amd64 libpoco-dev amd64 1.8.0.1-1ubuntu4

**Comment by aleks-f** [comment]
This likely has nothing to do with compiler or platform but rather with some code on your side. But how can we possibly know what causes it? [SSCCE](http://www.sscce.org/) maybe?

**Comment by Mironenko** [comment]
>     * bionic/universe amd64 libpoco-dev amd64 1.8.0.1-1ubuntu4

It's slightly different from version 1.10.1. Version 1.8.0 haven't got `Poco::JSON::Object::getNames()`, that's true.
