### ISSUE TITLE
Delegate Class Implementation Question

### ISSUE THREAD

**Issue by rafalasry** [pocoproject/poco#3154]
Hey,

I'm new to POCO and I was wondering why the Delegate class was implemented entirely in a header file instead of a regular cpp file.

Thanks in advance

**Comment by Mironenko** [comment]
Hi! 
Delegate is a template class. This thread explains why template classes are implemented in header files: https://stackoverflow.com/questions/495021/why-can-templates-only-be-implemented-in-the-header-file .

**Comment by rafalasry** [comment]
Cool, thanks :)
