### ISSUE TITLE
Question on Poco::Thread::current()

### ISSUE THREAD

**Issue by rafalasry** [pocoproject/poco#3156]
When calling _Poco::Thread::current()_, I expected to get the current _ThreadImpl_ but instead I got NULL.
I'm calling this static method from MacchinaServer.cpp as follows:

```c
Poco::Thread *t = Poco::Thread::current();
```
After looking at the Thread_POSIX implementation (I'm running on Ubuntu 16), I can see that the actual pthread is retrieved by calling _get_ at _CurrentThreadHolder_:
```c
pthread_getspecific(_key);
```
However, that key was not set before. I see there is a _set_ method in the same class that sets the key to hold the actual pthread object. So I'm guessing that the _set_ method should be called before calling _Poco::Thread::current()_?

So, I should I properly call the _Poco::Thread::current()_ method?

**Comment by Mironenko** [comment]
It's all in docs. https://pocoproject.org/docs/Poco.Thread.html#19417

> static Thread * current();
> Returns the Thread object for the currently active thread. If the current thread is the main thread, 0 is returned.
