### ISSUE TITLE
Debug Assertion fail

### ISSUE THREAD

**Issue by jano42** [pocoproject/poco#3161]
OS : Windows 10 v19042.630 (20H2)
VisualStudio 2019 : 16.8.2
Poco : 1.10.1

In our oss project (yadoms.com) we use Poco 1.9.4
We start to upgrade it to 1.10.1 but we have bugs.

Our issue has been revealed in our unit tests around configuration. (Poco::Util::AbstractConfiguration...)

Since 1.10 the AbstractConfiguration now use AutoPtr instead of raw pointer, which (I think) introduce memory deletion problems. (like it is explained in #2939 with no explicit AutoPtr contructor)

In fact we have such mockup code (simplified):

```cpp
   //--------------------------------------------------------------
   /// \class Default application options loader
   /// This loader get each option from :
   /// - the command line first, if not provided
   /// - in config file, if not provided
   /// - the default value
   //--------------------------------------------------------------
   class CStartupOptions
   {
   public:
      //--------------------------------------------------------------
      /// \brief                          Constructor
      /// \param [in]   configContainer   The configuration container
      //--------------------------------------------------------------
      explicit CStartupOptions(Poco::Util::AbstractConfiguration & configContainer)
	   :m_configContainer(configContainer)
	  {
	  }

      //--------------------------------------------------------------
      /// \brief	   Destructor
      //--------------------------------------------------------------
      virtual ~CStartupOptions()
	  {
	  }

      //--------------------------------------------------------------
      /// \brief	   Define StartupOptions
      //--------------------------------------------------------------
      void defineOptions(Poco::Util::OptionSet& options) const
	  {
		  options.addOption(
			 Poco::Util::Option("port", "p", "set the web server port number")
			 .required(false)
			 .repeatable(false)
			 .argument("port")
			 .validator(new Poco::Util::IntValidator(1, 65535))
			 .binding("server.port", &m_configContainer));
	  }

      unsigned short getWebServerPortNumber() const
	  {
		return static_cast<unsigned short>(m_configContainer.getUInt("server.port", 8080));
	  }

   private:
      //--------------------------------------------------------------
      /// \brief	   Reference for the configuration container
      //--------------------------------------------------------------
      Poco::Util::AbstractConfiguration & m_configContainer;
   };

   class CStartupOptionMockup
   {
   public:
      CStartupOptionMockup(int argc, char* argv[], bool unixStyle)
         : m_options(m_config)
      {
         Poco::Util::OptionSet os;
         m_options.defineOptions(os);
         Poco::Util::OptionProcessor processor(os);
         processor.setUnixStyle(unixStyle);
         for (auto i = 0; i < argc; ++i)
         {
            std::string name;
            std::string value;
            if (processor.process(argv[i], name, value))
            {
               if (!name.empty()) // "--" option to end options processing or deferred argument
               {
                  handleOption(os, name, value);
               }
            }
         }
         processor.checkRequired();
         
      }

      CStartupOptions& options()
      {
         return m_options;
      }

      Poco::Util::AbstractConfiguration& config()
      {
         return m_config;
      }

   private:
      void handleOption(Poco::Util::OptionSet& os, const std::string& name, const std::string& value)
      {
         const auto& option = os.getOption(name);
         if (option.validator())
         {
            option.validator()->validate(option, value);
         }
         if (!option.binding().empty())
         {
            m_config.setString(std::string(option.binding()), std::string(value));
         }
         if (option.callback())
         {
            option.callback()->invoke(name, value);
         }
      }


      CStartupOptions m_options;

      class CMyConf : public Poco::Util::MapConfiguration
      {
      public:
         CMyConf()
         {
         }

         virtual ~CMyConf()
         {
         }
      };

      CMyConf m_config;
   };
```

We use this class in a simple test case

```cpp

   BOOST_AUTO_TEST_CASE(Different_Port_p_Initialisation)
   {
      char* argv[] = {"./TestLoader", "--port:2000"};

      CStartupOptionMockup loader(2, argv, true);

      BOOST_CHECK_EQUAL(loader.options().getWebServerPortNumber(), static_cast<unsigned int>(2000)) ;
   }

```

When I debug my test, then it crashes at end of CStartupOptionMockup constructor

![image](https://user-images.githubusercontent.com/3135683/101487186-1495c200-395e-11eb-969d-f0ab46f2aee4.png)

The stack trace

![image](https://user-images.githubusercontent.com/3135683/101487308-44dd6080-395e-11eb-8ea6-b0f36c8c0c44.png)

It seems to be an AbstractConfiguration::Ptr which make the crash.

We haven't change nothing in our code, and in 1.9.4 it works well.

I've tried to a lot of things to fix it, but always without success.
Could you help me on fixing the issue ?

**Comment by jano42** [comment]
I've make lower debugging and I find the problem.

I think it's placed in Poco::Util::Option

When creating an option with a binding (call function : `Option& binding(const std::string& propertyName, AbstractConfiguration* pConfig)`)
Then it takes a pointer and place it into an AutoPtr (_config member)
At class Option destructor, then the AutoPtr is destroyed, and then the configuration pointer too. 

In fact if creating two options, using the same AbstractConfiguration, then at deletion it fails, because trying to delete AbstractConfiguration more than one time.

In actual case, the code can not work. I don't think there's any workaround in my code, the only way would be to update Poco code. (maybe changing 
`Option& binding(const std::string& propertyName, AbstractConfiguration* pConfig)` to `Option& binding(const std::string& propertyName, AbstractConfiguration::Ptr pConfig)`....

**Comment by Mironenko** [comment]
Is it compiled alright with `-Wall`? Looks like you are using uninitialized object here:
```
      CStartupOptionMockup(int argc, char* argv[], bool unixStyle)
         : m_options(m_config)
```

`m_config` is constructed after `m_options`.
Is the error still reproducing if the order of declaration of members `m_options` and `m_config` is reverted?

**Comment by jano42** [comment]
Fixed.
I rewrite completly my Mockup class implementation.
This issue was introduced by my bad first implementation.
