### ISSUE TITLE
Poco Static 

### ISSUE THREAD

**Issue by leopalazzi** [pocoproject/poco#3174]
Hello,

I am trying to use Poco as static library but it's not working.

I am building my application with CMake on Ubuntu20.04.

I tried to add Poco as static in CmakeList.txt :  
```
FIND_PACKAGE(Poco REQUIRED COMPONENTS Util NetSSL)
set(POCO_STATIC ON)
target_link_libraries(HBService PUBLIC Poco::NetSSL)
```

But I am getting this error :

/HBService: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/libPocoNet.so.71)

Can someone help me with this ?

Thank you !

**Comment by kerry-Cho** [comment]
```cmake
add_definitions( -DPOCO_STATIC )
option(BUILD_SHARED_LIBS OFF)
```

**Comment by Bjoe** [comment]
Well the correct solution is: `cmake -H[poco-sources] -Bbuild-output -DBUILD_SHARED_LIBS=ON`

See https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html
