### ISSUE TITLE
Why SharedLibrary destructor does nothing?

### ISSUE THREAD

**Issue by daohu527** [pocoproject/poco#3176]
As I know `SharedLibrary` use a handle to hold the loaded library. When we create a new "shared library" and then leave the scope, then we can't unload the library forever.

```c++
void func(const string& path) {
  SharedLibrary shared_library = new SharedLibrary(path);
  ...
}
```

So why not we unload the library in the destructor?
```c++
SharedLibrary::~SharedLibrary()
{
  unload()
}
```

**Comment by daohu527** [comment]
any update?

**Comment by hesham1salem** [comment]
is any solution or work around  ?
