### ISSUE TITLE
Poco::Process:launch on MacOS BigSur

### ISSUE THREAD

**Issue by tim2000** [pocoproject/poco#3182]
Hi,

We came across a problem were when using `Poco::Process::launch` on a MacOS BigSur, this creates processes that takes 100% of the cpu core their running on.

In Process_UNIX.cpp l122 we have this for:
`for (int i = 3; i < sysconf(_SC_OPEN_MAX); ++i)`

It seems that `sysconf(_SC_OPEN_MAX)` is slow and return a very big value on this new OS, it's evaluated on each loop of the for so it takes ages and a lot of CPU to run.

This thread reports the same problem: https://github.com/warmcat/libwebsockets/issues/2116

**Comment by obiltschnig** [comment]
Note: a similar behavior has been observed in Docker containers.
