### ISSUE TITLE
Supporting of iso-2022-jp encoding for MessageHeader parsing

### ISSUE THREAD

**Issue by SandakovMM** [pocoproject/poco#3185]
Hello
Seems like poco does not support iso-2022-jp encoding. I get a problem when working with emails that contain this encoding in headers. So I checked out TextEncodingManager and poco *Encoding.h/cpp files and did not find any mentions of this encoding.
Can you please add support of this encoding? I think this is going to be very helpful.

---

I can try to make PR with this functionality if you agree that change is really needed. As far as I understood it needs to add *Encoding.h/cpp files just like Latin1Encoding.h/cpp with the right name and _charMap table. And add a new Encoding class to TextEncodingManager.

**Comment by obiltschnig** [comment]
A proper place for such an encoding would be the Encodings library. However, I am not sure whether the class framework we use for implementing character encodings can support stateful character encodings such as ISO-2022.
