### ISSUE TITLE
[NetSSL] e-mail sending fails with: "Unacceptable certification: Application verification failure"

### ISSUE THREAD

**Issue by erl987** [pocoproject/poco#3187]
Hi,

trying to send an e-mail using this simple example code, I get this error both on Windows 7 (with Poco 1.9.2 from `vcpkg`) as well as on Debian 10 (Poco 1.9.0 as OS-package):

`Certificate validation error: Unacceptable certificate from 212.227.17.190: application verification failure`.

This is the error obtained from the provider GMX.

I have tried sending mails through two very large providers (GMX and Strato), so I would not expect that they have a certificate problem. This code is extracted from a large application that has run over years without problems with Poco 1.6.x. The difficulties are now occurring when trying to update the application and there is a new Poco version and also new OS-version.

I would appreciate any ideas about what the problem could be.

```cpp
#include <iostream>
#include <Poco/Net/SecureSMTPClientSession.h>
#include <Poco/Net/StringPartSource.h>
#include <Poco/Net/SecureStreamSocket.h>
#include <Poco/Net/ConsoleCertificateHandler.h>
#include <Poco/Net/SSLManager.h>
#include <Poco/Net/KeyConsoleHandler.h>
#include <Poco/Net/MailMessage.h>


// configuration
std::string hostName = "mail.gmx.net";
unsigned short port = 465;
std::string senderAddress = "some-user@gmx.de";
std::string userName = "Some User";
std::string password = "password";

std::string recepientName = "Other User";
std::string recipientAddress = "other-user@gmx.de";


int main()
{
	using namespace Poco;
	using namespace Poco::Net;

	// SSL-initialization
	Poco::Net::initializeSSL();

	Context::Ptr sslContext;
	SharedPtr<InvalidCertificateHandler> certHandler = new ConsoleCertificateHandler(false);

	sslContext = new Context(Context::CLIENT_USE, "", Context::VERIFY_RELAXED, 9, true, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
	SSL_CTX_set_default_verify_paths(sslContext->sslContext());

	SSLManager::instance().initializeClient(0, certHandler, sslContext);

	try
	{
		// generate the mail message
		MailMessage message;
		message.setSender(senderAddress);
		message.addRecipient(MailRecipient(MailRecipient::PRIMARY_RECIPIENT, recipientAddress, recepientName));

		message.setContentType("text/plain; charset=UTF-8");
		message.setSubject(MailMessage::encodeWord("Test message", "UTF-8"));
		message.addContent(new StringPartSource("Test message content", "text/plain; charset=UTF-8"));

		// login
		SMTPClientSession mailSession(SecureStreamSocket(SocketAddress(hostName, port)));
		mailSession.login(SMTPClientSession::AUTH_PLAIN, userName, password);

		// send the message
		mailSession.sendMessage(message);
		mailSession.close();

		std::cout << "E-mail sending successful";
	}
	catch (Poco::Exception& e) {
		std::cout << "An error has occurred: " << e.displayText();
	}
	catch (std::exception& e) {
		std::cout << "An error has occurred: " << e.what();
	}

	Poco::Net::uninitializeSSL();

	return 0;
}
```

**Comment by erl987** [comment]
I have tried to debug into the Poco source code to learn more about this issue. It is quite clear to me that Poco is verifying the server certificate `CN` against the **IP-address** and not the **host name** provided by the application - and this can not work.

It is interesting that the `SocketAddress` does not seem to actually store the host name, but the IP-address. Maybe this is the reason for the behaviour described above. This simple code shows this:

```
auto socketAddress = SocketAddress("mail.gmx.net", 465);
std::cout << socketAddress.host() << std::endl; // prints out: "212.227.17.190" instead of "mail.gmx.net"
```

For me this clearly looks like a bug in Poco, the server address provided to the socket seems to be never stored within the object.

**Comment by erl987** [comment]
The code in the issue description is working flawlessly with Poco 1.7.7 on Debian Linux 10 (with a manually compiled Poco).

**Comment by erl987** [comment]
This issue is still present in Poco 1.12.4 and 1.10.0 (which the version shipped with the current Debian 11).

This bug makes the e-mail sending functionality of Poco basically useless.

**Comment by obiltschnig** [comment]
`Poco::Net::SecureStreamSocket` has a constructor that takes the host name (for certificate verification) in addition to the SocketAddress. Use that one and verification should work.

**Comment by erl987** [comment]
Thanks for the hint. Using this syntax, the sample code actually starts to work:

```cpp
// ...
// login
SMTPClientSession mailSession(SecureStreamSocket(SocketAddress(hostName, port), hostName));
// ...
```
