### ISSUE TITLE
Cannot add TLS to HTTP client or server on unix-domain socket

### ISSUE THREAD

**Issue by sirzooro** [pocoproject/poco#3207]
I tried to add TLS to HTTP client and server running on top of Unix-domain socket. In both cases POCO thrown exception from Poco::Net::Impl::LocalSocketAddressImpl::host. In client this is thrown during connection to server. Server started without issues, but later when client tried to connect the same exception was thrown too. I used some sample OpenSSL sample app modified to use unix-domain socket to verify that server has the same problem.

**Comment by micheleselea** [comment]
if you are using localhost:port for connection try with 127.0.0.1:port

**Comment by aleks-f** [comment]
> if you are using localhost:port for connection try with 127.0.0.1:port

He is talking about unix-domain sockets, so none of those things apply.

**Comment by sirzooro** [comment]
Yes, I mean unix-domain sockets.
