### ISSUE TITLE
Poco::Data::PostgreSQL Prepared statements

### ISSUE THREAD

**Issue by astlin** [pocoproject/poco#3225]
Hello. 
Can't get how to use prepared statements in Poco::Data::PostgreSQL connection. I'm using connection pool and raw sql i.e. "update names set name='abcd' where id = 555" all works fine. But when I'm trying to use or bind to variables I run into a problem even I do everything like a "POCO Data User Guide" said.

My code:

```
Poco::SharedPtr<Poco::Data::SessionPool> dbSessionPool = new Poco::Data::SessionPool("PostgreSQL", "connstring");
Poco::Data::Session sess(dbSessionPool->get());
std::string name = "abcd";
int id = 555;

Poco::Data::Statement statement = (sess << "update names set name = ? where id = ?", Poco::Data::Keywords::use(name), Poco::Data::Keywords::use(id));

statement.execute();
Poco::Data::PostgreSQL::Connector::unregisterConnector();

```
Exception I got:

```
Exception: PostgreSQL: [PostgreSQL]: postgresql_stmt_prepare error: ERROR:  syntax error at or near "where"
LINE 1: update names set name = ? where id = ?
                                  ^
 update names set name = ? where id = ?
```
Please help. 

Poco 1.10.0 x64 Ubuntu 20.04

**Comment by aleks-f** [comment]
try this:

`update names set name = $1 where id = $2`

**Comment by aleks-f** [comment]
that's PostgreSQL peculiarity that has nothing to do with poco - for us, the SQL string is a "black box" and it is always somewhat dependent on the back end
