### ISSUE TITLE
FPEnvironment_C99.h and macros

### ISSUE THREAD

**Issue by wolpers** [pocoproject/poco#323]
FPEnvironment_C99.h fails to compile on BB10 SDK because 'isinf' is a macro here (cmath just pulls in math.h) and that conflicts with the qualified std::isinf call that is currently used.  Same for the other methods. 
From what I understand in C99 'isinf' etc. are defined to be macros, in C++ 2003 they are not defined (not sure) while in C++ 2011 they are supposed to be in the 'std' namespace. I think the following snippet could be a solution to make it work in most cases. 

```
{
#if defined(isinf)
    return isinf(value) != 0;
#else
    return std::isinf(value) != 0;
#endif
}
```

**Comment by aleks-f** [comment]
@wolpers is this still the case for QNX? 
/c @Bjoe

**Comment by wolpers** [comment]
cannot say.  don't even have an environment to test it, sorry.

**Comment by aleks-f** [comment]
@Bjoe do you have any interest pursuing this or can I close it?

**Comment by wolpers** [comment]
close it i guess.  thanks.
