### ISSUE TITLE
All tests fail on macOS because DYLD_LIBRARY_PATH isn't set

### ISSUE THREAD

**Issue by ryandesign** [pocoproject/poco#3243]
Hi! When building poco 1.10.1 with cmake with shared libraries on macOS, `make test` does not work at all. You build a bundled copy of cppunit, which has a libcppunit.dylib library that it needs, and `make test` fails to find it. The solution is to set DYLD_LIBRARY_PATH to the directory where the library is located at build time. This patch worked for me:

https://github.com/macports/macports-ports/blob/cce69045edb12649e6e3f1996f7ad11d3a12349c/devel/poco/files/DYLD_LIBRARY_PATH.patch

I haven't submitted it as a PR yet because maybe you have a different idea about how it should be fixed.

**Comment by Bjoe** [comment]
@ryandesign Thanks, I will take you patch and will introduce this with a "proper" fix.
