### ISSUE TITLE
Arbitrary indent of 2 applied to JSON string objects Var conversion

### ISSUE THREAD

**Issue by Coder666** [pocoproject/poco#3253]
The following code in "JSON/Object.h" VarHolder, enforces an arbitrary indent of 2 causing new line characters to appear in stringified JSON even when an indent of 0 has been specified.   This produces unexpected behaviour when an indent of 0 in the top level stringify is specified.

void convert(std::string& s) const
{
    std::ostringstream oss;
    _val->stringify(oss, 2);
    s = oss.str();
}

**Comment by Coder666** [comment]
This is still an issue.  It completly breaks JSON formatting if you want an indent other than 2.

**Comment by aleks-f** [comment]
please send a pull request to branch [poco-1.12.0](https://github.com/pocoproject/poco/tree/poco-1.12.0), with corresponding test case

**Comment by Coder666** [comment]
You basically need to create a JSON object and then use indent of zero when formatting it.  The expected output is a single line of JSON without carriage return characters.  i.e.   `{ "foo" : { "bar" : 123 }  }`

Instead you get carriage return characters added because an arbitrary indent of 2 is applied in this function:

```void convert(std::string& s) const
{
std::ostringstream oss;
_val->stringify(oss, 2);
s = oss.str();
}```

which completly ignores the indent of zero previously specified.

**Comment by aleks-f** [comment]
@Coder666 I understand what is happening, I am not asking for more prose about it. I am asking for code and a pull request.

**Comment by Coder666** [comment]
Yes, unfortunately I don't have time to spare in order to do this.
