### ISSUE TITLE
Upgrade to PCRE2 latest version

### ISSUE THREAD

**Issue by Harvey-H** [pocoproject/poco#3261]
Since any new features of PCRE will be added to PCRE2, and not to the PCRE 8.x series.
For current version of PCRE is vulnerable to denial-of-service (DoS) via a buffer overread triggered by \X characters in non-UTF strings.
Can the PCRE be updated to PCRE2 latest version?

**Comment by jspricke** [comment]
The Debian project discusses to drop PCRE at some point, so would be great if poco could switch to PCRE2:
https://lists.debian.org/debian-devel/2021/11/msg00176.html

**Comment by aleks-f** [comment]
#3663
