### ISSUE TITLE
Poco::Net::X509Certificate does not inherit from Poco::Crypto::X509Certificate

### ISSUE THREAD

**Issue by hubbergit** [pocoproject/poco#3273]
I am using POCO Version 1.10.1 on Windows 10.

According to the docs (https://pocoproject.org/docs/Poco.Net.X509Certificate.html) the class `Poco::Net::X509Certificate` inherits from `Poco::Crypto::X509Certificate`.

But the header file of `Poco::Net::X509Certificate` shows that this is not true. Therefore for example the method `equals` does not exist in `Poco::Net::X509Certificate`, but according to the docs it should have been inherited from the base class.

BTW: Are the docs not generated from the sources?

**Comment by obiltschnig** [comment]
Not sure where you've found this, but:

https://github.com/pocoproject/poco/blob/master/NetSSL_OpenSSL/include/Poco/Net/X509Certificate.h#L36

shows that Poco::Net::X509Certificate inherits from Poco::Crypto::X509Certificate, as it should.

**Comment by hubbergit** [comment]
I found it here:

https://github.com/pocoproject/poco/blob/master/NetSSL_Win/include/Poco/Net/X509Certificate.h

However I am using POCO installed by vcpkg. Maybe there has been a packaging mistake. Obviously they take the header files from NetSSL_Win.

**Comment by hubbergit** [comment]
So after having digged further into this issue I guess that the header files from `NetSSL_OpenSSL` and `NetSSL_Win` are all copied over to the `Net` include directory during the installation step. This operation seems to overwrite the files from NetSSL_OpenSSL with the files from NetSSL_Win.

Unfortunately I was not able to verify this theory as I was not able to build POCO from the sources myself. The build complains about a missing Windows 8.1 SDK, which I indeed do not have installed. I have installed a Windows 10 SDK. The documentation does not mention a certain Windows SDK as a prerequisite at all. Never mind this is just a side note that should explain why I could not verify my guess above.

**Comment by hubbergit** [comment]
I now rebuild/reinstalled POCO with vcpkg, but modified the portfile of vcpkg such that it does not build NetSSL_Win. Voila! All my header files are as expected now and my problem disappeared.

But how should we proceed now? It seems to me that the problem is still not related to vcpkg, but a problem with POCO.

Can anyone confirm that when building POCO with cmake using the build parameters ENABLE_NET=ON, ENABLE_NETSSL=ON and ENABLE_NETSSL_WIN=ON, the header files of NetSSL_OpenSSL are overwritten with those from NetSSL_Win during installation step?

If this is not the case, then I will create a ticket for the port of POCO in vcpkg.
