### ISSUE TITLE
JSON Fuzzing: Undefined-shift in poco_double_conversion::DiyFpStrtod

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#3284]
Status: New
Owner: ----
CC: a...@adalogics.com, guen...@pocoproject.org 
Labels: Restrict-View-Commit ClusterFuzz Reproducible Stability-UndefinedBehaviorSanitizer Engine-libfuzzer OS-Linux Reported-2021-05-25 Proj-poco
Type: Bug

New issue 34669 by ClusterFuzz-External: poco:json_parser_fuzzer: Undefined-shift in poco_double_conversion::DiyFpStrtod
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34669

Detailed Report: https://oss-fuzz.com/testcase?key=6319817075326976

Project: poco
Fuzzing Engine: libFuzzer
Fuzz Target: json_parser_fuzzer
Job Type: libfuzzer_ubsan_poco
Platform Id: linux

Crash Type: Undefined-shift
Crash Address: 
Crash State:
  poco_double_conversion::DiyFpStrtod
  poco_double_conversion::ComputeGuess
  poco_double_conversion::Strtod
  
Sanitizer: undefined (UBSAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_ubsan_poco&revision=202105250612

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=6319817075326976

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

If you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.

This bug is subject to a 90 day disclosure deadline. If 90 days elapse
without an upstream patch, then the bug report will automatically
become visible to the public.

**Comment by obiltschnig** [comment]
This is likely an issue in double-conversion. See #3313.

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/558324f672d824300498060aff63356bc6bb8097
