### ISSUE TITLE
template <typename ValueType> ValueType* AnyCast(Any* operand) fails for typeid for the same types on Android ARM64 build

### ISSUE THREAD

**Issue by AleksaJanjatovic** [pocoproject/poco#3289]
This issue was noticed on *poco-1.9.0-all*
Next function call causes *Bad cast exception: Failed to convert between Any types*
```
Poco::Data::Statement select(*m_DatabaseSession);
    select << "SELECT name FROM sqlite_master WHERE type='table' AND name=?;",
            use(TABLE_SETTINGS),
            now;
```
With previous m_DatabaseSession initialization:
`    m_DatabaseSession=new Poco::Data::Session("SQLite", "databaseFile");`

After further examination, I've found out that the error is caused in the AnyCast<std::string> call. More specifically, it is caused by *operand->type() == typeid(ValueType)* line of Any.h file:
```
template <typename ValueType>
ValueType* AnyCast(Any* operand)
	/// AnyCast operator used to extract the ValueType from an Any*. Will return a pointer
	/// to the stored value. 
	///
	/// Example Usage: 
	///	 MyType* pTmp = AnyCast<MyType*>(pAny).
	/// Will return NULL if the cast fails, i.e. types don't match.
{
	return operand && operand->type() == typeid(ValueType) 
				? &static_cast<Any::Holder<ValueType>*>(operand->content())->_held
				: 0;
}
```
I've managed to print the actually *type_info.name()* for both operator *operand->type()* and *typeid(ValueType)* and I've noticed that the string values are the same:
```
E/AnyCast.h: Help 9: operatorChar: 0 valueTypeChar: 0
    Help 10: operatorChar: 78 valueTypeChar: 78
    Help 7: FALSE
    Help 8: TRUE
    Help 3: NSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE
    Help 4: NSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE
    Help 5: TRUE
```
_Note that these are my custom logs that I've placed in the library and that I've subsequently fetched from the android studio LOGCAT. The line *Help 3* and *Help 4* are lines that represent the prints of the type_info.name() return values for the above mentioned *operand->type()* and *typeid(ValueType)*. As we can all see, they are the same._

After that conclusion, I've examined the *typeinfo* header file that can be found on the android-ndk-r21d NDK that can be fetched [here](https://developer.android.com/ndk/downloads).  I've noticed that the *typeinfo* header contains multiple implementations of the *type_info::operator==* depending on the actually used platform (*__unique_impl, _non_unique_impl, __non_unique_arm_rtti_bit_impl*). On the current build setup, I've noticed that __unique_impl is used, which is implemented in this way:
```
    static bool __eq(__type_name_t __lhs, __type_name_t __rhs) _NOEXCEPT {
      return __lhs == __rhs;
    }
```
Implementation is chosen here:
```
  typedef

#if defined(__APPLE__) && defined(__LP64__) && !defined(__x86_64__)
    __non_unique_arm_rtti_bit_impl
#elif _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT == 0
    __non_unique_impl
#elif _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT == 1
    __unique_impl
#else
#   error invalid configuration for _LIBCPP_HAS_MERGED_TYPEINFO_NAMES_DEFAULT
#endif
     __impl;
```
My question is: Has anyone else ever encountered this problem on ARM64 Android platforms, and if so, what was the solution? Do I need to parse a specific *cmake* option while building poco, or is it handled the the Poco cmake configuration itself? 
_Note 1: The *type_info* implementation seems to be a prevailing problem on the android ndk side since multiple bug-fixes can be found related to it._ 
_Note 2: The attachment is actually a .h file of the *type_info*, I've just changed the extension to .pdf so I could upload it._ 
[typeinfo.pdf](https://github.com/pocoproject/poco/files/6562037/typeinfo.pdf)

**Comment by aleks-f** [comment]
Yes, the issue on Android was [reported before](https://github.com/pocoproject/poco/issues/3289https://github.com/pocoproject/poco/issues/3289), but the solution was not provided. I can't say that I understand completely how/why this happens, `==` for two same `typeinfo`s returns `false`?

Be all that as it may, if it's truly a platform bug, a possible fix for android would be to compare the `type_info.name()`. Not sure how much performance impact that would have, though. And I'd like to understand how exactly it happens that
