### ISSUE TITLE
A variation on Issue 949 comes back to life?

### ISSUE THREAD

**Issue by omatai** [pocoproject/poco#3295]
I am trying a simple `SELECT * FROM table` type query via Poco on a **PostgreSQL** database. As in [Issue #949](https://github.com/pocoproject/poco/issues/949) I am getting a "Data type not supported" exception because one of the two columns in the table I am selecting from has TEXT data type. I am using Poco 1.10.1.

Following guidance at the top of the doc page for [Poco::Data::RecordSet](https://www.appinf.com/docs/poco-2008.2/Poco.Data.RecordSet.html) I am trying this:

    void MyDBWrapper::RunQuery( const std::string & queryString )
    {
        Statement query( *m_pSession );
        query << queryString;    // e.g. queryString is "SELECT * FROM table"
        query.execute();
        // all subsequent code using RecordSet recSet( query ) rendered irrelevant due to exception...
    }

The `m_pSession` variable in `MyDBWrapper` is a `std::unique_ptr<Session>`. It is dynamic so that I can call `PostgreSQL::Connector::registerConnector()` in the wrapper constructor before I create the session. This works fine so long as there are no CLOB columns in the table I put in the query. But the moment the table has a CLOB column, `query.execute()` throws an exception. Am I missing something?

**Comment by omatai** [comment]
I just reworked the code to eliminate the `std::unique_ptr<Session>` so that `query( *m_pSession )` can become `query( m_session)`  - used a `MyConnector` class to encapsulate `PostgreSQL::Connector::registorConnector()` , then construct an instance of it in `MyDBWrapper` constructor prior to constructing `m_session`. Same result.

It makes me wonder: did the fix from [PR 2677](https://github.com/pocoproject/poco/pull/2677) make it into the 1.10.0 (and 1.10.1) branches? (Insufficiently familiar with github to answer that question myself...)

**Comment by obiltschnig** [comment]
fixed in 1.11.0
