### ISSUE TITLE
Poco Foundation Fails to Compile With POCO_ENABLE_SOO Defined

### ISSUE THREAD

**Issue by andrewauclair** [pocoproject/poco#3297]
With POCO_ENABLE_SOO defined, the Poco Foundation library fails to compile in Any.h at lines 525, 567 and 592.

**Comment by aleks-f** [comment]
yeah, it's currently a non-default config option, so not auto-tested. probably time to make it work and default now that alignment is standardized

**Comment by andrewauclair** [comment]
That would great. We use Poco::DynamicAny in a pretty core piece of our system, but 95% of it is 'unsigned int', 'float', 'double', etc. So with the SOO on we would save a decent bit of CPU time.

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/c032c16f68830fd32b35bf27593c75334a366c0e
