### ISSUE TITLE
Poco considers zip archive empty even though it is not

### ISSUE THREAD

**Issue by Krzmbrzl** [pocoproject/poco#3300]
In my code I am trying to iterate over the entries in a zip archive and what I am doing is this:
```cpp
std::ifstream zipInput(<my path>);
Poco::Zip::ZipArchive archive(zipInput);

auto it = archive.fileInfoBegin();

while (it != archive.fileInfoEnd()) {
    // Do stuff
}
```

This works fine on Linux but on Windows this causes trouble. I was unable to pin down the issue exactly but for some zip files (e.g. created using Windows10 standard tools `Send To > Compressed (zipped) directory`) this works but for others (e.g. created using 7zip to create a `.zip` file as well) the loop never does a single iteration even though I can inspect the zip file with various other programs to see that it does indeed contain multiple files.

Any idea what might be going on here?

**Comment by obiltschnig** [comment]
Make sure you open the `std::ifstream` in binary mode, or use a `Poco::FileInputStream`.

**Comment by Krzmbrzl** [comment]
Thanks! I will try that and come back with the results :)

**Comment by Krzmbrzl** [comment]
Okay so I am now using a `Poco::Foundation::FileInputStream` instead of the `std::ifstream` but the issue persists.

**Comment by Krzmbrzl** [comment]
Scratch that. I have been stupid xD
My program actually didn't compile and thus I was using the old version which obviously still contains the reported error. Now that I fixed the typo and it actually compiled the error is fixed.

Thanks for your help!
