### ISSUE TITLE
MSVC: Poco hides warnings (C4996) for the C++14 attribute [[deprecated]]

### ISSUE THREAD

**Issue by andrewauclair** [pocoproject/poco#3302]
Noticed this while attempting to deprecate some functions in one of our classes. I was not receiving the C4996 warning for any of the calls. This happens because of all the #pragma warning lines (specifically 4996) at the bottom of Foundation/include/PocoPlatform_WIN32.h.

Now that Poco officially supports C++14 in 1.10.0, I think something should be done to fix this. I looked and there's only a few files causing C4996 warnings. Ideally, Poco should be using #pragma warning (push) and #pragma warning (pop) so that you're not hiding warnings in user code.

I can attempt a pull request for this if I have time.

**Comment by obiltschnig** [comment]
@andrewauclair a pull request against poco-1.11.0 branch would be appreciated.
