### ISSUE TITLE
projects using poco-1.10.1 needs to explicitly specify using C language

### ISSUE THREAD

**Issue by strahlc** [pocoproject/poco#3308]
After switching from poco-1.9.4 to poco-1.10.1, my library doesn't compile any more, because cmake complains about missing C language feature.

With the old version I was using:

```cmake
project(myLib CXX)

find_package(Poco REQUIRED COMPONENTS Data DataSQLite Foundation Net NetSSL Util)
...
```

with the new poco version I get this error from cmake:

```
-- Configuring done
CMake Error in src/CMakeLists.txt:
  Cannot use features from non-enabled language C
```

If I change the project command to ```project(myLib CXX C)```, everything works like before.

It is unexpected to me, that I have to enable `C` language in order to use poco. Please change poco to the previous behavior.

**Comment by aornugent** [comment]
Agreed - this is a breaking change for our project.
