### ISSUE TITLE
 error can find "CreateSymbolicLinkW" in windows xp sp2

### ISSUE THREAD

**Issue by xiaobingcaicai** [pocoproject/poco#3316]
i read the not from [https://pocoproject.org/docs/99100-ReleaseNotes.html](url)，that say can support xp sp2，
but when i run on xp sp2,there is a error "can not find application point CreateSymbolicLinkW",
and i read the code find 
`#if _WIN32_WINNT >= 0x0600 && defined(SYMBOLIC_LINK_FLAG_DIRECTORY)
		DWORD flags = 0;
		if (isDirectoryImpl()) flags |= SYMBOLIC_LINK_FLAG_DIRECTORY;
#ifdef SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE
		flags |= SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE;
#endif
		if (CreateSymbolicLinkW(upath.c_str(), _upath.c_str(), flags) == 0)
			handleLastErrorImpl(_path);
#else
		throw Poco::NotImplementedException("Symbolic link support not available in used version of the Windows SDK");
#endif`

**Comment by obiltschnig** [comment]
Try an older version of Poco. Current versions no longer support WinXP.

**Comment by xiaobingcaicai** [comment]
> Try an older version of Poco. Current versions no longer support WinXP.

emmm..
which old version will be ok？if u dont know,i have to try one by one..

**Comment by obiltschnig** [comment]
`File::linkTo()` was added in 1.8.1, so any version before that should work.

**Comment by xiaobingcaicai** [comment]
> `File::linkTo()` was added in 1.8.1, so any version before that should work.

ok tks.
