### ISSUE TITLE
Subscribing to a continuous stream of data

### ISSUE THREAD

**Issue by vectar31** [pocoproject/poco#3319]
Hey, 
I just found this library and I am trying to use it to connect to the websocket stream provided by binance. The details of the stream is as follows:

- The base endpoint is: wss://stream.binance.com:9443
- Combined streams are accessed at /stream?streams=<streamName1>/<streamName2>/<streamName3> . Example of this would be /stream?ethusdt@trade/btcusdt@trade
- A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark
- The websocket server will send a ping frame every 3 minutes. If the websocket server does not receive a pong frame back from the connection within a 10 minute period, the connection will be disconnected. Unsolicited pong frames are allowed.

I tried to connect to the stream using the following:

`Poco::Net::SocketAddress address = Poco::Net::SocketAddress("stream.binance.com", 9443);
	Poco::Net::StreamSocket *sock = new Poco::Net::StreamSocket(address);`

How do I specify stream names as well? I think I am able to create a connection but I can't find any reference on how to specify the path /stream?ethusdt@trade/btcusdt@trade

I am fairly new to network programming so please bear with me. Thank you for your time.

**Comment by aleks-f** [comment]
You are connecting to web socket using TCP socket. Use [WebSocket](https://github.com/pocoproject/poco/blob/master/Net/include/Poco/Net/WebSocket.h#L37) instead.
