### ISSUE TITLE
Conan + MacOs + apple-clang 12.0 => can't include apr/1.7.0

### ISSUE THREAD

**Issue by dhait** [pocoproject/poco#3324]
Poco has a dependency on Apache apr/1.7.0.  When including the poco conan package in a build, it can't build with the apr due to there being no apr conan package for apple-clang 12.0.

If we go back to 11.0, a whole other host of problems crop up with other libraries.

Looks like Apache apr/1.7.0 is from 2019 with no more recent releases.

Can this dependency be eliminated?

**Comment by aleks-f** [comment]
It is possible to omit ApacheConnector when building Poco. If conan can not handle it, then [conan-poco](https://github.com/pocoproject/conan-poco) seems like an appropriate forum for this question.
