### ISSUE TITLE
[Question] JSON support in SQLite

### ISSUE THREAD

**Issue by ep-cslim** [pocoproject/poco#3327]
Hello,

I am exploring JSON support in SQLite (https://www.sqlite.org/loadext.html).

However, it seems like POCO does not support the "Run-Time Loadable Extensions" feature at the moment.

Am I correct? Any suggestion on how to support JSON?

Thank you.

**Comment by aleks-f** [comment]
See [SharedLibraries](https://pocoproject.org/slides/120-SharedLibraries.pdf)
