### ISSUE TITLE
Apple Silicon ARM64 :  Invalid access: Can not convert empty value.

### ISSUE THREAD

**Issue by asmaan** [pocoproject/poco#3331]
I have compiled poco for arm64 for Apple Silicon Native support. But for arm devices JSON parsing fails even for simplest json contracts. Please see below code snippet.

```
std::string json = "{\"clientConfig\" : \"Franky\"}";
        Poco::JSON::Parser jsonParser;
        Poco::Dynamic::Var jsonObject = jsonParser.parse(json);
        Poco::JSON::Object::Ptr jsonPtr = jsonObject.extract<Poco::JSON::Object::Ptr>();
        std::string testStr = jsonPtr->getValue<std::string>("clientConfig"); -> Here I get that exception.
```
If I check` jsonPtr->get("clientConfig").isEmpty()` , it returns true as well.

I tried to compile with -fvisibility=hidden as well but same result.
If I compiled for x86_64 and run on Silicon Macs(through rosetta), it work fine. On iOS it works fine too.
If I run in debug mode on Apple Silicon Mac, it works fine, issue is only in release mode.

Any ideas what's causing this?

**Comment by asmaan** [comment]
@obiltschnig Can you please take a quick look?

**Comment by obiltschnig** [comment]
I don't have an Apple Silicon Mac available. I can do a quick test on iOS maybe. I remember a similar issue on Android.

**Comment by obiltschnig** [comment]
Probably related: #2844

**Comment by asmaan** [comment]
Can you please guide me to android issue? I found few but they were not specific to this particular error.
On iOS it works for me, issue is specific to ARM based Macs only.
Another thing to add, If I run in debug mode, it works fine, issue is only in release mode.(Will put in description as well)

**Comment by asmaan** [comment]
@obiltschnig 
I looked at the android issue and it looks similar to that.Any workarounds you can suggest?

**Comment by asmaan** [comment]
My suspicion is that this issue is under this snippet in Var.h where pHolder is nil
```
template <typename T>
	T convert() const
		/// Invoke this method to perform a safe conversion.
		///
		/// Example usage:
		///     Var any("42");
		///     int i = any.convert<int>();
		///
		/// Throws a RangeException if the value does not fit
		/// into the result variable.
		/// Throws a NotImplementedException if conversion is
		/// not available for the given type.
		/// Throws InvalidAccessException if Var is empty.
	{
		VarHolder* pHolder = content();

		if (!pHolder)
			throw InvalidAccessException("Can not convert empty value.");

		if (typeid(T) == pHolder->type()) return extract<T>();

		T result;
		pHolder->convert(result);
		return result;
	}
```

**Comment by asmaan** [comment]
Finally managed to figure it out. Set `ENABLE_TESTABILITY to NO` in your target's Release mode build settings . This will fix the issue. I don't know why poco needs this privilege to run. @obiltschnig Can you please help me understand why poco need this entitlement?

**Comment by obiltschnig** [comment]
Could you provide the detailed clang command line XCode uses in release build with both ENABLE_TESTABILITY set to on and off. It likely has to do with some compiler setting (`-fvisibility` maybe) that influence the way RTTI works across dylib boundaries.

**Comment by asmaan** [comment]
I can only see `export ENABLE_TESTABILITY\=YES` , no trace of this flag in clang command line. See below clan command.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -target arm64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu++1z -stdlib\=libc++ -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/zsbuilder/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/testuser/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -DDEVELOPMENT_TEAM\=\"TTTTTTTT\" -Dtray\=1 -DNS_BLOCK_ASSERTIONS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wno-strict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -iquote /


BuildProductsPath/Release -D_DARWIN_UNLIMITED_SELECT -DFD_SETSIZE\=65536 -MMD -MT dependencies -MF 
```

**Comment by zhangshaoju1987** [comment]
### 

> I have compiled poco for arm64 for Apple Silicon Native support. But for arm devices JSON parsing fails even for simplest json contracts. Please see below code snippet.
> 
> ```
> std::string json = "{\"clientConfig\" : \"Franky\"}";
>         Poco::JSON::Parser jsonParser;
>         Poco::Dynamic::Var jsonObject = jsonParser.parse(json);
>         Poco::JSON::Object::Ptr jsonPtr = jsonObject.extract<Poco::JSON::Object::Ptr>();
>         std::string testStr = jsonPtr->getValue<std::string>("clientConfig"); -> Here I get that exception.
> ```
> 
> If I check` jsonPtr->get("clientConfig").isEmpty()` , it returns true as well.
> 
> I tried to compile with -fvisibility=hidden as well but same result. If I compiled for x86_64 and run on Silicon Macs(through rosetta), it work fine. On iOS it works fine too. If I run in debug mode on Apple Silicon Mac, it works fine, issue is only in release mode.
> 
> Any ideas what's causing this?

Hi Friends:
     Could you guide me how to comiple arm64 version ? I complie poco-1.11.0 on mac Big Sur . but cmake detect my cpu is x86_64 . CMAKE_SYSTEM_PROCESSOR does not work.  I think this is cmake's bug

**Comment by obiltschnig** [comment]
Still no access to Apple Silicon Mac to reproduce. Moving to 1.13.

**Comment by matejk** [comment]
Latest version from devel works properly on Apple Silicon (M1 Pro Max) for the snipped provided by the submitter.

```
% c++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix

% sw_vers 
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68
```

**Comment by bas524** [comment]
> However few other tests fail:
> 
> ```
> There were 3 errors: 
>  1: N7CppUnit10TestCallerI8JSONTestEE.testValidJanssonFiles
>     "N4Poco17NotFoundExceptionE:
> Not found: POCO_BASE"
>     in "<unknown>", line -1
>  2: N7CppUnit10TestCallerI8JSONTestEE.testInvalidJanssonFiles
>     "N4Poco17NotFoundExceptionE:
> Not found: POCO_BASE"
>     in "<unknown>", line -1
>  3: N7CppUnit10TestCallerI8JSONTestEE.testInvalidUnicodeJanssonFiles
>     "N4Poco17NotFoundExceptionE:
> Not found: POCO_BASE"
>     in "<unknown>", line -1
> ```

It is not an error, please set environment variable POCO_BASE, which contains path to the poco source directory

**Comment by xzzh999** [comment]
in macos M1 arm64, i found Array::Ptr Object::getArray always get empty array , and this test failed:
`
it->second.type() == typeid(Array::Ptr)
`
but i print the name is the same, strage ...

**Comment by matejk** [comment]
An additional unit tests was added in PR #4315 that covers issues reported in this ticket. The test passes on macOS running on Apple M1.

**Comment by mbhaskar98** [comment]
I am building a framework for iOS  (arm64) and the same code crashes in release mode with -fvisibility=hidden compiler flags. 

It works fine for simulator (x86_64), release mode iOS without the above flags and debug mode. 

Xcode's `ENABLE_TESTABILITY` setting also set to no for release mode.

**Comment by matejk** [comment]
The problem can be reproduced on macOS with CMAKE if:
* CMAKE_BUILD_TYPE is Release
* set(CMAKE_CXX_VISIBILITY_PRESET hidden) is set
