### ISSUE TITLE
clarification on releases

### ISSUE THREAD

**Issue by killerbot242** [pocoproject/poco#3332]
Hi,

I noticed there is no more distinction between "minimal" poco and "all" poco.

I noticed the release file is now called (according to the link) : poco-1.11.0-release.tar.gz

However when you download this it ends up being called : poco-poco-1.11.0-release.tar.gz

And this now contains .git and .vccode, is that wanted ?

Next I saw the older releases are now also available in that style (though they use to have the minimal/all) distinction.
And moreover their content has changed, for example when comparing:
* poco-1.9.4-all.tar.gz
* poco-1.9.4-release.tar.gz
the latter (newer) one suddenly contains libraries that originally were not there:
* ApacheConnector
* CppParser
* NetSSL_win
* PDF
* PocoDoc
* ProGen
* SevenZip

Was that the intention that older releases are suddenly different ?

**Comment by obiltschnig** [comment]
You are probably mixing the files from the GitHub release page with the files available from the website (https://pocoproject.org/releases). The former are basically just a snapshot of the Git repository, the latter are generated by a script (same as in the past).

**Comment by killerbot242** [comment]
thanks, but I did not see the path on the home page to end up at "https://pocoproject.org/releases/".
Looking a bit better I found it, personally I consider it a bit confusing that these "signed packages" are somewhere in the middle.
While GET POCO button takes you directly go git. The get poco menu indeed takes you to a page where after, git, conan, .. they finally pop-up.

**Comment by killerbot242** [comment]
Just did a little compare between the "all" and that "git release",
the all is missing:
* ApacheConnector
* CppParser
* Encodings/Compiler
* NetSSL_win
* PDF
* PocoDoc
* ProGen
* SevenZip

So all is not all ;-) ?

**Comment by obiltschnig** [comment]
Well, "all" is all that is officially supported for use in your projects. The rest is internal tools (CppParser, Encodings/Compiler, PocoDoc, ProGen) or use-at-your-own-risk (no longer supported/not properly maintained, like ApacheConnector, SevenZip, PDF, NetSSL_Win).

**Comment by killerbot242** [comment]
thanks for the clarification.
