### ISSUE TITLE
NamedMutex does not work on Linux distributions where fs.protected_regular=1

### ISSUE THREAD

**Issue by jngrb** [pocoproject/poco#3338]
Prequisite: A Linux system with
sysctl fs.protected_regular=1
(i.e. with a [a recent systemd](https://github.com/systemd/systemd/commit/2732587540035227fe59e4b64b60127352611b35))

Due to restrictions in the kernel, how and under which curmcumstances sticky, world-readable files such as those in tmp can be opened, Poco's NamedMutex fails to work for root after a regular user previously used (and released) the same mutex.

**How to reproduce**: Compile the following minimal example:
```
#include <iostream>

#include "Poco/NamedMutex.h"
#include "Poco/Exception.h"

int main()
{
    try
    {
        Poco::NamedMutex mutex("testfile");

        mutex.lock();
        std::cout << "Holding mutex... (press enter)" << std::endl;
        while (1)
        {
            if ('\n' == getchar())
                break;
        }

        return 0;
    }
    catch (Poco::Exception& e)
    {
        std::cerr << "Error: Cannot get mutex !" << std::endl;
        std::cerr << "Exception: " << e.displayText() << std::endl;
    }
}
```

Run your program with a regular user and then with a root user:
```
./poco_mutex_protected_regular 
Holding mutex... (press enter)

sudo ./poco_mutex_protected_regular
Error: Cannot get mutex !
Exception: System exception: cannot create named mutex /tmp/testfile.mutex (lockfile): testfile
```

The _problem_ is that the program run as root cannot correctly open the file `/tmp/testfile.mutex` owned by the regular user.
A _workaround_ is to delete the mutex file owned by the regular user.
The **proper solution** is to change the open flags in NamedMutex_UNIX.cpp appropriately.

see also [this issues](https://unix.stackexchange.com/questions/503111/group-permissions-for-root-not-working-in-tmp)

_Note 1_: It doesn't matter whether the sudo program is run while the regular-user program runs or after that was terminated with ENTER. The error is the same.

_Note 2_: Otherwise, mutex exclusivity works properly. Open the program two times in parallel with a regular user (or both with root) to see the effect.

_Note 3_: due to the special conditions for this but, running as root first and then running as regular user works:
```
rm /tmp/testfile.mutex
sudo ./poco_mutex_protected_regular 
Holding mutex... (press enter)

./poco_mutex_protected_regular
Holding mutex... (press enter)

```

**Comment by cheese** [comment]
I met the same issue when I try to re-run the testsuite of Foundation on Fedora 34. I have to manually delete `/tmp/TestEvent.event` and `/tmp/TestMutex.mutex`.

**Comment by jngrb** [comment]
@obiltschnig , what's the chances that the solution will be part of Release 1.11.2 ?
I propose to change the path of NamedMutexes to another location if requested by the application. In order not to break backwards compatibility, the default constructor might use the old default path, but a special constructor should be offered for this purpose. I think there are other reasons why /tmp is not the best location for a mutex. So user should be free to use /dev/shm or another location at will.
