### ISSUE TITLE
Logger translate Notice Level to Information Type on EventLogChannel

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#3343]
I'm currently working with the `EventLogChannel`, would it not be better to map the `Notice Logger Level` also to the EventLog Information Type``? Because on a release build the lowest possible level is `Information`. And i like to use the information level for logging a lot of more informations then the notice level. And from my point of view Notice Logs are not warnings for me.
So maybe it would make sense to map also the Notice Level to the Information Type when using the EventLogChannel?.

**Comment by aleks-f** [comment]
I don't know - notice indicates something out of ordinary, so it fits better into warning then information category. But I don't use this functionality and I also don't fully understand the release/debug build logic - why does windows event log care, and how does it know whether the application is built as debug or release?

**Comment by KevDi** [comment]
@aleks-f There are some Preprocessor Checks in the Logger Code. If the `_DEBUG` is set (which is the case on Debug Builds on Windows) then logging to `Debug` is possible. If you build on Release this Preprocessor definition is not there so that logging to debug are not written to any logging output.

**Comment by KevDi** [comment]
But from your point of view, notice is sometihng out of ordinary, it makes sense that it is mapped to warning instead of information.
