### ISSUE TITLE
The lock &_mutex is possibly released twice?

### ISSUE THREAD

**Issue by jenny-cheung** [pocoproject/poco#3348]
Hi, developers, thank you for your checking. It's possible for the lock  `&_mutex` to be released twice in the method `EventImpl::waitImpl()`?

https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/Foundation/src/Event_POSIX.cpp#L108

https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/Foundation/src/Event_POSIX.cpp#L114

```
void EventImpl::waitImpl()
{
	if (pthread_mutex_lock(&_mutex))
		throw SystemException("wait for event failed (lock)");
	while (!_state)
	{
		if (pthread_cond_wait(&_cond, &_mutex))
		{
			pthread_mutex_unlock(&_mutex);
			throw SystemException("wait for event failed");
		}
	}
	if (_auto)
		_state = false;
	pthread_mutex_unlock(&_mutex);
}
```

**Comment by okkenator** [comment]
The throw SystemException prevents the second unlock from executing in that case.  Therefore there is no double unlock.

**Comment by jenny-cheung** [comment]
Ok, thank you!
