### ISSUE TITLE
Consider renaming ActiveRecord binary from arc

### ISSUE THREAD

**Issue by swt2c** [pocoproject/poco#3349]
On multiple Linux distributions, there is already binary named `arc` for the ARC file archiver/compressor: http://arc.sourceforge.net/.  It's old and probably not too widely used anymore, but it has been around for a long time in the /usr/bin/arc slot.

Perhaps the poco utility could instead be `poco_arc` or something?

**Comment by FederAndInk** [comment]
One bigger problem that I just encountered is a clash with arcanist `arc` binary from phabricator: https://github.com/phacility/arcanist

**Comment by stkw0** [comment]
According to debian popularity stats (https://qa.debian.org/popcon-graph.php?packages=arc%2C+libpoco-dev&show_installed=on&want_legend=on&want_ticks=on&from_date=&to_date=&hlght_date=&date_fmt=%25Y&beenhere=1 ) arc is very popular. See below the stats
![imagen](https://user-images.githubusercontent.com/4865946/167291302-7ab9fd5b-d5c0-4834-9d56-04754cd0f673.png)

I also think it would be a good thing to rename it.

**Comment by swt2c** [comment]
Still an issue.
