### ISSUE TITLE
Base64Encoder remove last character

### ISSUE THREAD

**Issue by nakoukal** [pocoproject/poco#3362]
Hello can me anybody help with base64encoding from string stream. I used encoder with stringstream and when is source greater 9 characters then output is after decoding shorter by one character .
Here is code :

`
int main(int argc, char** argv)
{
	std::string sresult = "abcdefghij";

	std::istringstream istr(sresult);

	std::ostringstream ostr;

	Base64Encoder encoder(ostr);

	StreamCopier::copyStream(istr, encoder,sresult.size());

	auto res = ostr.str();	
     

	return 0;
}
`
res is after encode : YWJjZGVmZ2hp
this is after decode : abcdefghi

Compiled on W10 vs2019 poco-1.11.0-release

**Comment by obiltschnig** [comment]
You forgot to call `encoder.close();`.

**Comment by nakoukal** [comment]
Many Thanks.
