### ISSUE TITLE
Poco-1.11.0 failure of Testsuite

### ISSUE THREAD

**Issue by BalajiMalar** [pocoproject/poco#3365]
**I fetched the latest Poco release 1.11.0 and built using cmake on Ubuntu-18.04. 
I am trying to run the tests available for Foundation, Net, Util, JSON and Xml which were provided by the test suite.**
**the below tests are failed in JSON**

!!!FAILURES!!!
Runs: 44   Failures: 0   Errors: 3

There were 3 errors: 
 1: N7CppUnit10TestCallerI8JSONTestEE.testValidJanssonFiles
    "N4Poco17NotFoundExceptionE: Not found"
    in "<unknown>", line -1
 2: N7CppUnit10TestCallerI8JSONTestEE.testInvalidJanssonFiles
    "N4Poco17NotFoundExceptionE: Not found"
    in "<unknown>", line -1
 3: N7CppUnit10TestCallerI8JSONTestEE.testInvalidUnicodeJanssonFiles
    "N4Poco17NotFoundExceptionE: Not found"
    in "<unknown>", line -1

1 runs, 1 failed.

Failed: JSON

**The below tests are failed in Net**
!!!FAILURES!!!
Runs: 284   Failures: 0   Errors: 8

There were 8 errors: 
 1: N7CppUnit10TestCallerI13RawSocketTestEE.testEchoIPv4
    "N4Poco11IOExceptionE: I/O error"
    in "<unknown>", line -1
 2: N7CppUnit10TestCallerI13RawSocketTestEE.testSendToReceiveFromIPv4
    "N4Poco11IOExceptionE: I/O error"
    in "<unknown>", line -1
 3: N7CppUnit10TestCallerI14ICMPClientTestEE.testPing
    "N4Poco11IOExceptionE: I/O error"
    in "<unknown>", line -1
 4: N7CppUnit10TestCallerI14ICMPClientTestEE.testBigPing
    "N4Poco11IOExceptionE: I/O error"
    in "<unknown>", line -1
 5: N7CppUnit10TestCallerI14ICMPSocketTestEE.testSendToReceiveFrom
    "N4Poco11IOExceptionE: I/O error"
    in "<unknown>", line -1
 6: N7CppUnit10TestCallerI14ICMPSocketTestEE.testAssign
    "N4Poco11IOExceptionE: I/O error"
    in "<unknown>", line -1
 7: N7CppUnit10TestCallerI14ICMPSocketTestEE.testMTU
    "N4Poco11IOExceptionE: I/O error"
    in "<unknown>", line -1
 8: N7CppUnit10TestCallerI13NTPClientTestEE.testTimeSync
    "N4Poco11IOExceptionE: I/O error"
    in "<unknown>", line -1

1 runs, 1 failed.

Failed: Net

**The below test are failed in Util**
****************************************
*** Linux x86_64 Util
****************************************

./testrunner: error while loading shared libraries: libPocoXML.so.80: cannot open shared object file: No such file or directory

1 runs, 1 failed.

Failed: Util

**Comment by bas524** [comment]
It's difficult to understand where is a problem. Can you highlight the difference between your build and ci from poco https://github.com/pocoproject/poco/blob/master/.github/workflows/ci.yml ?

**Comment by BalajiMalar** [comment]
> It's difficult to understand where is a problem. Can you highlight the difference between your build and ci from poco https://github.com/pocoproject/poco/blob/master/.github/workflows/ci.yml ?

The test suite was failed eventhough i followed the same build instructions you have mentioned and the only difference is that my VM is Ubuntu 18.04 and i have installed the library from poco-1.11.0.tar.gz

**Comment by buiquanganh85** [comment]
have you tried "sudo ldconfig" to reload library paths before the test ?

**Comment by BalajiMalar** [comment]
Yes, i tried the command "sudo ldconfig" before running the test and yet the same result

**Comment by aleks-f** [comment]
@BalajiMalar json tests are likely because [files](https://github.com/pocoproject/poco/tree/poco-1.11.0/JSON/testsuite/data) are not found; most net errors (if not all) due to permissions (try running as root)

**Comment by BalajiMalar** [comment]
Thank you for the suggestion , i am able to run the Net tests with 3 errors(that is due to my VPN restrictions).
