### ISSUE TITLE
OpenSSL 3.0.0

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3370]
Hi all, I have tested beta2 version of OpenSSL and from my point of view everything should work fine with poco libs.
The only thing we should change in Poco::Crypto is in mapPaddingMode because RSA_SSLV23_PADDING was removed
so probably we should change something like:
```
int mapPaddingMode(RSAPaddingMode paddingMode)
{
		switch (paddingMode)
		{
		case RSA_PADDING_PKCS1:
			return RSA_PKCS1_PADDING;
		case RSA_PADDING_PKCS1_OAEP:
			return RSA_PKCS1_OAEP_PADDING;
#if OPENSSL_VERSION_NUMBER < 0x030000000L
		case RSA_PADDING_SSLV23:
			return RSA_SSLV23_PADDING;
#endif
		case RSA_PADDING_NONE:
			return RSA_NO_PADDING;
		default:
			poco_bugcheck();
			return RSA_NO_PADDING;
		}
	}
```
remember that some encryption algorithm (like for example Blowfish) are no longer automatically loaded because they moved to legacy encryption.
To enable legacy encryption you can call 
`OSSL_PROVIDER* legacy = OSSL_PROVIDER_load(NULL, "legacy");`
once in your code (in main function at the beginning for example)
remember than `OSSL_PROVIDER_unload(legacy);`

[ref openssl 3.0.0 providers](https://wiki.openssl.org/index.php/OpenSSL_3.0)
regards

**Comment by obiltschnig** [comment]
`RSA_PADDING_SSLV23` has already been removed from poco-1.11.0.

**Comment by micheleselea** [comment]
Good, I was going to update this morning ;)
Ok so I think OpenSSL3.0.0 should compile without problem
