### ISSUE TITLE
SocketReactor::getNotifier 1.11.0

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3371]
I think the function
`SocketReactor::NotifierPtr SocketReactor::getNotifier(const Socket& socket, bool makeNew)`
was not changed to reflect the change you made to PollSet.
`getNotifier` use socket and not `socket.impl()->sockfd();`
Probably you end up with that solution that is ok anyway? I remember the reason was that if the fd change (for example when you need to upgrade from non SSL to SSL connection inside handler) something can go wrong...but was almost 1 year ago and I don't know if I remember correctly

**Comment by aleks-f** [comment]
yeah, the change is in [devel](https://github.com/pocoproject/poco/blob/devel/Net/src/SocketReactor.cpp#L180), but not in release

**Comment by micheleselea** [comment]
ah ok, thanks
