### ISSUE TITLE
xmlparser.cpp 1.11.0 strange NON call to function sip24_valid

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3373]
In file xmlparser.cpp line 6729 there's this line of code:
`(void)sip24_valid;`
visual studio give me compilation warning because sip24_valid it's a void function, so I think should be called like
`(void)sip24_valid();`
or do you think should be ok even if just `(void)sip24_valid;`?

**Comment by aleks-f** [comment]
this is a question for expat forum, we can get involved int modifying embedded foreign code and then patching it on every upgrade

**Comment by micheleselea** [comment]
@aleks-f I wrote to forum, let's see what they reply
