### ISSUE TITLE
PollSet::SocketModeMap poll(const Poco::Timespan& timeout) hasSignaledFDs issue slow down connections

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3375]
I think I read something about that should be changed and reverted to old select, anyway that function has a problem in the actual implementation. When you have a socket that is signaled for readable but not writable, what happen to me is that the poll slow down because that piece of code:
```
if ((remainingTime > 0) && (rc > 0) && !hasSignaledFDs())
{
	rc = -1;
	WSASetLastError(WSAEINTR);
}
```
I commented it out for now, but I'm trying to change hasSignaledFDs to do the job, in the meanwhile take care that function make slow down network exchange

**Comment by coolan2013** [comment]
hey,hasSignaledFDs() has bug？
(pollfd.**revents | **POLLOUT)  should be (pollfd.**events &** POLLOUT) ？？？？？

			if ((pollfd.**revents |** POLLOUT) &&
				(_wantPOLLOUT.find(pollfd.fd) != _wantPOLLOUT.end()))
			{
				return true;
			}

**Comment by micheleselea** [comment]
Probably has some kind of error, I look in my code, and I changed to not use that function anymore, like that
`
#ifdef _WIN32
			rc = WSAPoll(&_pollfds[0], static_cast<ULONG>(_pollfds.size()), static_cast<INT>(remainingTime.totalMilliseconds()));
			// see https://github.com/pocoproject/poco/issues/3248
			/*if ((remainingTime > 0) && (rc > 0) && !hasSignaledFDs())
			{
				rc = -1;
				WSASetLastError(WSAEINTR);
			}*/
#else
			rc = ::poll(&_pollfds[0], _pollfds.size(), remainingTime.totalMilliseconds());
#endif
`

**Comment by aleks-f** [comment]
as of 1.12 release, we're going back to select on windows; AFAICT WSAPoll is still broken, even after MS claims they fixed it in W10 2004

**Comment by micheleselea** [comment]
I think it's the only solution, I tried a lot of different combination...never get the right behavior
