### ISSUE TITLE
PollSet function setMode 1.11.0 cause while(1) on windows

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3378]
pre 1.11.0 implementation of network events was
```
if (it->second & PollSet::POLL_READ)
	pfd.events |= POLLIN;
if (it->second & PollSet::POLL_WRITE)
	pfd.events |= POLLOUT;
```

that was updated in 1.11.0 in

```
void setMode(poco_socket_t fd, short& target, int mode)
{
	if (mode & PollSet::POLL_READ)
		target |= POLLIN;

	if (mode & PollSet::POLL_WRITE)
		_wantPOLLOUT.insert(fd);
	else
		_wantPOLLOUT.erase(fd);
	target |= POLLOUT;
}
```

the problem  is that we always set `target |= POLLOUT;`
so even if we dont want the WSaPoll trigger always that events without wait for timeout and that cause while(1) with the timeout function

I think the solution is

```
void setMode(poco_socket_t fd, short& target, int mode)
{
	if (mode & PollSet::POLL_READ)
		target |= POLLIN;

	if (mode & PollSet::POLL_WRITE) 
	{
		target |= POLLOUT;
		_wantPOLLOUT.insert(fd);
	}
	else 
	{
		_wantPOLLOUT.erase(fd);
	}
}
```

**Comment by aleks-f** [comment]
see #3339

**Comment by micheleselea** [comment]
I alredy found your 3339 post and I understand next version we will switch to select, I agree that is the best solution. I write this post just to warn about someone upgrade to 1.11.0
Next week I'll start to try the select version in my software

**Comment by aleks-f** [comment]
> Next week I'll start to try the select version in my software

please do and let us know of any issues - I've spent an inordinate amount of time on this issue, and still bugs crept in; from what I've seen, even different windows versions (I used 10 and Server 2019 for this) behave differently.
thanks for your help!
