### ISSUE TITLE
Poco::Data::ODBC - dbEncoding property not used for insert/update

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#3396]
Looks like the `dbEncoding` property for the ODBC session is only used for extracting data from the database, not for inserting/updating. In case of insert or update, transcoding should happen as well.

**Comment by aleks-f** [comment]
That functionality, for both extraction and binding, should be moved up to the Data library. it won't be automatically done for all the implementations, but at least it will be readily available.

**Comment by obiltschnig** [comment]
As long as it does not negatively affect performance I'm fine with that. Although it's probably not needed as pretty much all decent DBMSs (including SQL Server since 2019) support UTF-8.

**Comment by aleks-f** [comment]
It won't do anything unless explicitly invoked by implementation.

**Comment by aleks-f** [comment]
#3396
