### ISSUE TITLE
buildwin.ps1 with openssl

### ISSUE THREAD

**Issue by Mike4Online** [pocoproject/poco#3405]
buildwin.ps1 still expects to see separate vcxproj files for Win32 and x64 builds.  These separate project files were merged a while agio, so Win32 and x64 build configurations now live within the same project file.  buildwin.ps1 was never updated to support this change.

**Comment by Mike4Online** [comment]
### Further development needed for buildwin.ps1 and other Windows-specific scripts and projects

I was about to create a new pull request to offer my modifications to `buildwin.ps1` (this time in the `devel` branch) when I found a bunch of additional issues with this script's support for OpenSSL.  

The [Poco Getting Started](https://github.com/pocoproject/poco/blob/master/doc/00200-GettingStarted.page) documentation page suggests [cloning a GitHub repository of pre-built OpenSSL libraries for Windows](https://github.com/pocoproject/openssl), each contained in distinct sub-folders by platform and build configuration.  I.E. multiple `lib` folders.  However the `buildwin.ps1` script's command-line parameter `-openssl_base` expects the specified `$(openssl_base)` folder to have a single `lib` sub-folder containing the OpenSSL libraries.  This won't work when building multiple builds of Poco at one time, i.e. when specifying `-config both`, unless the VC++ projects account for this.

The `poco\Crypto\Crypto_VS90.vcproj` handles this gracefully by copying the appropriate DLL, PDB and LIB files from the platform-and-build-config-specific subfolders under `$(openssl_base)\build` to the `$(openssl_base)\lib` path via PreBuild events (which are unique for each build configuration).  **But none of the newer Visual Studio projects for Crypto do this.**

**Related Issues:**

1. [The related script for building OpenSSL from source](https://github.com/pocoproject/openssl/blob/develop/build.ps1) does not specify the latest OpenSSL source URL.  It still points to [https://www.openssl.org/source/](https://www.openssl.org/source/), when it should be fetching from [https://github.com/openssl/openssl](https://github.com/openssl/openssl), or perhaps from [https://git.openssl.org](https://git.openssl.org/).  

2. The OpeenSSL `build.ps1` script's help content does not explicitly indicate support for building OpenSSL 1.1.1 (though it might build fine once the base URL for downloading the source is corrected).  I believe Poco supports OpenSSL 1.1.1 since Poco 1.9.4. 

To resolve these issues, [the build.ps1 script for OpenSSL hosted by Poco](https://github.com/pocoproject/openssl/blob/develop/build.ps1) needs some revisions to ensure it can successfully fetch OpenSSL source and build it (including OpenSSL 1.1.1 versions).  Then Poco's `buildwin.ps1` script and/or Visual C++ project files need modifications to ensure the proper OpenSSL libraries can be located when building Poco with `-linkmode all` and/or `-config both`.

I'll keep at it and post again here once I have another round of pull requests ready.


**More related Issues (for reference):**

3. I need to do more testing to ensure `buildwin.ps1` can properly build when the specified tool is `devenv`.  When building my company's applications I've run into difficulties with more recent builds of Visual Studio 2019, where `devenv.exe` returns control to the calling script immediately (like a true Windows application), rather than waiting for the `devenv` process to finish.  The difficulty with this is that the PowerShell script or batch file needs to wait, and it then needs to check the `ERRORLEVEL` to detect whether the build succeeded.  Older versions of `devenv.exe` would wait before returning and provide an `ERRORLEVEL`, but newer Visual Studio builds do not behave this way.  I tried launching `devenv.exe` with `start /wait`, but that was problematic.  I also tried running `devenv.com`, which waits for the process to complete and returns an `ERRORLEVEL` (and provides for redirecting console output), but that was problematic, too.  Ultimately I switched the build scripts for my company's apps to MSBuild to resolve these issues.

4. The `buildwin.ps1` script does not check to see whether it is being run from a Visual Studio x86 or x86_64 Native Tools Command Prompt or a regular environment.  Normally this is not required, because the script will call `VCVARSALL.BAT` when building with MSBuild, while `devenv.exe` (or `devenv.com`) should not require a native tools environment.  But this, too, should be tested.

5. The vs150 and vs160 versions of the VC++ project files for Poco do not specify a `WindowsTargetPlatformVersion`.  This may lead Visual Studio to utilize a different Windows SDK than projects which do specify this value.  It might be worth noting this in the Poco documentation, or perhaps updating the VC++ project files to specify `10.0` as the `WindowsTargetPlatformVersion`.  Even if `10.0` is unsuitable for some developers, it would be easier for these developers to revise the `WindowsTargetPlatformVersion` value if it already exists in the `.vcxproj` files (via global search and replace, rather than having to add this value manually).  

6. The vs150 and vs160 versions of the VC++ project files for Poco specify `MultiByte` CharacterSet values.  Shouldn't they be `Unicode`? 

7. Poco includes `Windows.h` via `Foundation\include\Poco\UnWindows.h`.  But it is a good practice to include a `targetver.h` file before including `Windows.h`, in order to specify the target platform version (i.e. defining `WINVER`, `_WIN32_WINNT` and `NTDDI_VERSION`), which might be for Windows 8.1 (or older) rather than Windows 10.  Perhaps the Poco maintainers could add a `targetver.h` file to Poco, to be configured by the library consumers.

8.  VC++ projects for Visual Studio 2022 are needed.  There may be another open issue for this.

**Comment by aleks-f** [comment]
@Mike4Online if you want this in 1.12.0 release, now is the time to send pull

**Comment by Mike4Online** [comment]
@aleks-f , thanks for the notification.  I've been tied up lately and may not have it ready in time for the Poco 1.12 release.

It may be just as well, as I haven't yet upgraded to Visual Studio 2022 to ensure those builds work properly via the PowerShell script.  And I have not yet understood how OpenSSL 3 fits in, specifically:

1. Is the latest Poco code compatible with OpenSSL 3?
2. Must OpenSSL 3 be built with an --api parameter set for version 1.1, in order to be compatible with Poco?

**Comment by aleks-f** [comment]
1. Yes
2. No
