### ISSUE TITLE
Use ServerApplication Got priviledge error:Cannot open Service Control Manager

### ISSUE THREAD

**Issue by zhangshaoju1987** [pocoproject/poco#3408]
I regist my Application as window service. But on some computers got some error。

run this command:
`C:\apps\host_service.exe /registerService   /displayName="host_service" /description="local service" /startup="automatic"
`
got error below(even if I run as manager , still got the error)
Cannot open Service Control Manager

Does anyone else know what reason caused that. is there some priviledges missing?

**Comment by micheleselea** [comment]
host_service has to be administrator. So you have to run command shell as administrator
