### ISSUE TITLE
When using the poco library built with mt

### ISSUE THREAD

**Issue by freeyang** [pocoproject/poco#3412]
When using the poco library built with mt
Declare poco::TaskManager g_task_manager; globally.
Then, a crash occurs because defaultPool has not been declared yet.

namespace
{
	static ThreadPoolSingletonHolder sh;
}

ThreadPool& ThreadPool::defaultPool()
{
	
	return *sh.pool();
}

I bypassed it by making the following changes.
Is there any other way other than the way I know?

ThreadPool& ThreadPool::defaultPool()
{
	static ThreadPoolSingletonHolder sh;
	return *sh.pool();
}

**Comment by micheleselea** [comment]
Probably you can try with something like
`std::unique_ptr<Poco::TaskManager> g_task_manager;`
and than
`g_task_manager = std::make_unique<Poco::TaskManager>();`
