### ISSUE TITLE
The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.

### ISSUE THREAD

**Issue by xiekai-aiai** [pocoproject/poco#3429]
i  insert data to mysql(8.0.25) by poco(1.11.0)  SessionPool ,  sometimes happend exception: insert capture info happend exception:MySQL: [MySQL]: [Comment]: mysql_stmt_prepare error	[mysql_stmt_error]: The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.	[mysql_stmt_errno]: 4031	[mysql_stmt_sqlstate]: HY000	[statemnt]

mysql url exampe: "host=192.168.0.11;port=3306;db=test;user=root;password=test;compress=true;auto-reconnect=true"

i check SessionPool  class, find SessionImpl::isGood function maybe have a  bug,  if _lastError is 0,  long time no have data,  when call isGood function, never call _handle.ping(),  this connection maybe closed by mysql server becase wait_timeout and interactive_timeout. so when i use this connetion, it will cause an exception。

**Comment by xiekai-aiai** [comment]
> For Ubuntu: /etc/mysql/mysql.conf.d/mysqld.cnf
> 
> In the [mysqld] section (min = 1,max = 31536000 / For Windows max = 2147483):
> 
> > [mysqld]
> > wait_timeout = 31536000
> > interactive_timeout =31536000

thanks for your reply,  i find SessionImpl::isGood function maybe have a bug, if _lastError is 0, long time no have data, when call isGood function, never call _handle.ping(), this connection maybe closed by mysql server becase wait_timeout and interactive_timeout. so when i use this connetion, it will cause an exception。so just modify wait_timeout  and interactive_timeout  does not slove this problem.

**Comment by fredpalmer** [comment]
So the `wait_timeout` on this issue has elapsed

**Comment by matejk** [comment]
Contributions in the form of PR are welcome.
