### ISSUE TITLE
Base64Decoder could not decode any string with a bit complex  !

### ISSUE THREAD

**Issue by zhangshaoju1987** [pocoproject/poco#3440]
std::istringstream istr(contentInBase64);
Poco::Base64Decoder decoder(istr);
std::string content;
decoder >> content;

I use the upper code decodes the below base64 String , but after decode content is: # . 
I found that any string with just a bit complex , poco could not decode it!!!

https://www.base64decode.org/

`IyBXZWJSVEPmnrbmnoQNClvmmJ/lvaLmnrbmnoTlkoznvZHnirbmnrbmnoRdKGh0dHBzOi8vd3d3LmNuYmxvZ3MuY29tL0hhaWp1bnpodS9wLzQyMzg0NDcuaHRtbCkgIA0KIyMg572R54q25p625p6EDQojIyMg5L2/55So5Zy65pmvDQogICAg5bCP5Z6L5Lya6K6uNOaWuemAmuivne+8jOavlOWmguaIkeS7rOWFrOWPuOWQhOS4quWfuuWcsO+8iOaIkOmDve+8jOWMl+S6rO+8jOa3seWcs++8jOatpuaxie+8ieW8gOS8mueahOaXtuWAme+8jOWPr+S7pemHh+eUqOe9keeKtuaetuaehOaooeW8j+OAguavj+S4quiKgueCueS5i+mXtOmDveS8muaehOW7uuS4gOadoemTvui3r+OAgg0KIyMjIOS8mOWKvw0KICAgIOmAmuS/oei0qOmHj+mrmO+8jOeos+WumuaAp+Wlve+8iOS4uuWwj+iMg+WbtOmAmuS/oeaPkOS+m+acgOmrmOeahOi0qOmHj+S/neivge+8iQ0KICAgIOacjeWKoeWZqOerr+avlOi+g+i9u+advu+8jOWPqumcgOimgeaOqOa1geWwseihjO+8jOacgOWkp+WMluWIqeeUqOWuouaIt+err+eahOi1hOa6kA0KIyMjIOe8uueCuQ0KICAgIOesrDHkuKrkurrliqDlhaUgICAgIOaWsOWinjDmnaHpk77ot68NCiAgICDnrKwy5Liq5Lq65Yqg5YWlICAgICDmlrDlop4x5p2h6ZO+6LevDQogICAg56ysM+S4quS6uuWKoOWFpSAgICAg5paw5aKeMuadoemTvui3rw0KICAgIOesrDTkuKrkurrliqDlhaUgICAgIOaWsOWinjPmnaHpk77ot68NCiAgICDnrKw15Liq5Lq65Yqg5YWlICAgICDmlrDlop405p2h6ZO+6LevDQogICAg56ysNuS4quS6uuWKoOWFpSAgICAg5paw5aKeNeadoemTvui3rw0KICAgIOesrDfkuKrkurrliqDlhaUgICAgIOaWsOWinjbmnaHpk77ot68NCiAgICDnrKw45Liq5Lq65Yqg5YWlICAgICDmlrDlop435p2h6ZO+6LevDQogICAg56ysOeS4quS6uuWKoOWFpSAgICAg5paw5aKeOOadoemTvui3rzQuNC4NCiAgICDmiYDku6XmgLvlhbHlu7rnq4soMSsyKzMrLi4uLis4KT00Kjk9MzbmnaHpk77ot68NCiAgICDlj6/ku6XnnIvlh7rmnaXov5nkuKrnvZHnu5zku6Pku7fmmK/pnZ7luLjlpKfnmoQNCg0KDQojIyDmmJ/lvaLmnrbmnoQNCiAgICDljp/nkIbmmK/miYDmnInpgJror53mlrnlsIbmlbDmja7pg73lj5Hnu5nmnI3liqHlmajvvIzmnI3liqHlmajnu4/ov4fmt7fpn7PlkIjmiJDlpITnkIblj5HpgIHnu5nlhbbku5blkITmlrkNCiMjIyDkvb/nlKjlnLrmma8NCiAgICDlpJrmlrnpgJror53vvIjlj6/ku6XmianlsZXliLDlh6Dnmb7lj7fkurrvvInpmL/ph4zpkonpkonmianlsZXliLDkuoYzMDDlpJrlj7fkurrvvIzohb7orq/lpb3lg4/kuZ/og73mianlsZXliLAxMDDlpJrlj7fkurrjgILov5nkuKrln7rmnKzkuIrlj6/ku6XorqTkuLrmmK/kuIDlj7DmnI3liqHlmajlkIzml7blj6rog73mnI3liqHkuIDkuKrkvJrorq7jgILmiYDku6XlnKjku4rlubTmmKXoioLnlqvmg4XmnJ/pl7TvvIzpmL/ph4zpkonpkonku5jlh7rnmoTmiJDmnKzmmK/pnZ7luLjmmILotLXnmoTjgIINCiAgICDmnIDlhbjlnovnmoTlsLHmmK/ov5znqIvlip7lhazvvIzlvIDpm4blm6LkvJrorq7vvIzkupLliqjpl67nrZTlnovmlZnlraYNCg0KIyMjIOS8mOeCuQ0KICAgIOS9v+eUqOWcuuaZr+abtOWKoOW5v+azm++8jOmFjee9ruS9v+eUqOavlOi+g+eBtea0uw0KIyMjIOe8uueCuQ0KICAgIOmAmuivnei0qOmHj+eojeW+ruS4i+mZje+8jOeos+WumuaAp+ayoeaciee9keeKtumrmA0KICAgIOacjeWKoeWZqOaIkOacrOmrmO+8jOmcgOimgeacieW+iOW8uueahOehrOS7tuino+eggeiDveWKm++8jOmcgOimgeeJueWumueahOacjeWKoeWZqOOAgg0KDQoNCg0KIyMjIFBsYW5BDQogICAg5pyA5pep5pyf55qEd2VicnRj5Y2P6K6u54mI5pysDQogICAg5LiA5Liq6L+e5o6l5LiA5Liq5aqS5L2T5rWB77yIb25lIFBlZXJDb25uZWN0aW9uIG9uZSBTdHJlYW3vvIkNCiAgICBTdHJlYW0g5Y+v5Lul5L2/55SoRGF0YUNoYW5uZWwg5Y+R6YCB6Z+z6aKR77yM6KeG6aKR77yM5paH5a2X77yM5paH5Lu2DQogICAg5aaC5p6c5pyJ5aSa5Liq5a6i5oi356uv77yM5bCx5ZGI546w5Ye6572R54q25p625p6E55qE54m554K5DQohW1BsYW5B6YCa5L+h57uT5p6E5Zu+XShodHRwczovL2tub3dsZWRnZWJhc2UubXN5aWRhaS5jb20vbWF0ZXJpYWwvdmlldy85OWE1YjY0OS1mMGY3LTRkNjQtOTAyYS1kZTAzNGFhYjhiYWEpDQogICAg6L+Z56eN5Y2P6K6u5p625p6E5Yaz5a6a5LqG5Y+q6IO96L+b6KGM5b6I5bCR55qE5a6i5oi356uv5LmL6Ze06L+b6KGM6YCa5L+hDQoNCg0KIyMjIFBsYW5C77yIU0RQ77yJDQpbUGxhbkLnmoTmj4/ov7BdKGh0dHBzOi8vd2VicnRjZ2xvc3NhcnkuY29tL3BsYW4tYi8pICAgDQogICAg5b2T5YmN55qEd2VicnRj5Y2P6K6u54mI5pysDQogICAg5LiA5Liq6L+e5o6l5aSa5Liq5aqS5L2T5rWBKG9uZSBQZWVyIG9uZSBTdHJlYW0pICANCiAgICBbUGxhbkLpgJrkv6Hnu5PmnoTlm75dKGh0dHBzOi8vYmxvZy5jc2RuLm5ldC9EaXR0eUNoZW4vYXJ0aWNsZS9kZXRhaWxzLykNCg0KICAgIOWSjFBsYW5B5a+55q+U77yM5o6l5pS25aSa5Liq5a6i5oi356uv55qE5pWw5o2u55SxUGVlcuaUueaIkOS6hlN0cmVhbSzpgJrov4fkvb/nlKjlpJrkuKpTdHJlYW3mnaXmjqXmlLblj5HpgIHlkozlpJrkuKrlrqLmiLfnq6/nmoTmlbDmja7jgILlip/og73vvIzmgKfog73lop7lvLrkuobvvIzlj6/ku6XmlK/mjIHmm7TlpJrnmoTlrqLmiLfnq6/mjqXlhaXjgIINCg0KIyMjIFVuZmllZFBsYW7vvIhkcmFmdC1pZXRmLXJ0Y3dlYi1KU0VQ77yJDQogICAg5Y2z5bCG6KaB5q2j5byP5oiQ5Li66KeE6IyD55qE54mI5pys77yM55uu5YmN5rWP6KeI5Zmo5bey57uP6KOF5aSH5LqG77yM5L2G5piv5rKh5pyJ6buY6K6k5ZCv55So44CC6ZyA6KaB5omL5Yqo5ZCv55So44CCDQogICAgW0pTRVDlvIDlj5HmipXkuqforqHliJLkuaZdKGh0dHBzOi8vd2VicnRjLm9yZy9nZXR0aW5nLXN0YXJ0ZWQvdW5pZmllZC1wbGFuLXRyYW5zaXRpb24tZ3VpZGUpDQogICAg5pyA57uIUGxhbkLkvJrlnKjmtY/op4jlmajph4zpnaLooqvliKDpmaTjgIINCiAgICAyMDE4LTA5IOW8gOWPkeWujOaIkA0KICAgIDIwMTktMDEg56iz5a6a77yM6KeC5a+f6Zi25q6177yM5YeG5aSH5YiH5o2i5bm25Yig6ZmkUExBTi1CDQogICAg`

**Comment by obiltschnig** [comment]
Your problem is the usage of [`operator >> (std::string)`](https://www.cplusplus.com/reference/string/string/operator%3E%3E/) to read from the decoded stream.

> Notice that the istream extraction operations use whitespaces as separators; Therefore, this operation will only extract what can be considered a word from the stream. To extract entire lines of text, see the string overload of global function getline.

Use `std::istream::get()` or `std::istream::read()` to read from `Poco::Base64Decoder`.
