### ISSUE TITLE
Is the distanceMatrix in topologies/internet2.topo.mat wrong?

### ISSUE THREAD

**Issue by Spongebob-bear** [pocoproject/poco#3441]
Hello, I used the coordinate data in internet2.topo.mat to compute the distance of every pair of nodes, and I found that the value was different from the data in distanceMatrix. I wonder how the distanceMatrix is computed and I would appreciate it if you could offer a discription about the data in internet2.topo.mat. Thank you very much.

**Comment by obiltschnig** [comment]
wrong project?
