### ISSUE TITLE
cmake "uninstall" CMP0002 error

### ISSUE THREAD

**Issue by wyzwzz** [pocoproject/poco#3454]
my project has multi uninstall target, and it will cause cmake CMP0002 error that multi target conflict with the same target name.
perhaps the cmakelists may be modified as follows:
```cmake
if(not Target uninstall)
configure_file(
	"${CMAKE_CURRENT_SOURCE_DIR}/cmake/cmake_uninstall.cmake.in"
	"${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake"
	IMMEDIATE @ONLY)

add_custom_target(uninstall
	"${CMAKE_COMMAND}" -P "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake"
)
endif()
```

**Comment by TotteKarlsson** [comment]
We are having this same problem as well, forcing us to build Poco separately, which is inconvenient. 

Is there a way to fix this without touching Pocos CMake files?
