### ISSUE TITLE
Add Windows 11 detection to Environment_WIN32U

### ISSUE THREAD

**Issue by thunderbolt10** [pocoproject/poco#3472]
Windows 11 uses the same Major and Minor versions as Windows 10. However, the build number for Windows 11 should be at least 22000. 
EnvironmentImpl::osDisplayNameImpl() should be updated to reflect this.

**Comment by obiltschnig** [comment]
See [292d137](https://github.com/pocoproject/poco/commit/292d137909a40c2670ec317775fa0766dc888ce6)
