### ISSUE TITLE
Should the Array::operator[] throw?

### ISSUE THREAD

**Issue by steffenhk** [pocoproject/poco#3495]
`Array::operator[]` uses `poco_assert` which throws an exception if the index is out of range.
Is that intentional?
The documentation comment does not indicate that it will throw and there is already an `at()` method that throws when the index is out of range.
https://github.com/pocoproject/poco/blob/master/Foundation/include/Poco/Array.h#L95

**Comment by obiltschnig** [comment]
Should probably be `poco_assert_dbg()` instead.
