### ISSUE TITLE
How to install poco with RelWithDebInfo?

### ISSUE THREAD

**Issue by zhang-qiang-github** [pocoproject/poco#3498]
I can suceed compile poco, then I want to install it. 

First, I find the dll name of Release/RelWithDebInfo is the same, and the installation is failed. 

Then, I want to set the postfix for poco. I find the changing in CMake GUI is useless, because the CMakeLists set the CMAKE_RELWITHDEBINFO_POSTFIX as "" by force in poco/cmake/DefinePlatformSpecifc.cmake;:

```
# Add a d postfix to the debug libraries
if(BUILD_SHARED_LIBS)
	set(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Set Debug library postfix" FORCE)
	set(CMAKE_RELEASE_POSTFIX "" CACHE STRING "Set Release library postfix" FORCE)
	set(CMAKE_MINSIZEREL_POSTFIX "" CACHE STRING "Set MinSizeRel library postfix" FORCE)
	set(CMAKE_RELWITHDEBINFO_POSTFIX "" CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
else(BUILD_SHARED_LIBS)
	set(CMAKE_DEBUG_POSTFIX "${STATIC_POSTFIX}d" CACHE STRING "Set Debug library postfix" FORCE)
	set(CMAKE_RELEASE_POSTFIX "${STATIC_POSTFIX}" CACHE STRING "Set Release library postfix" FORCE)
	set(CMAKE_MINSIZEREL_POSTFIX "${STATIC_POSTFIX}" CACHE STRING "Set MinSizeRel library postfix" FORCE)
	set(CMAKE_RELWITHDEBINFO_POSTFIX "${STATIC_POSTFIX}" CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
endif()
```

Then, I modify it, and set CMAKE_RELWITHDEBINFO_POSTFIX  as "rd". Then, the compiling is failed: can not open "PocoFoundation.lib". I think the reason may be: (Foundation CMakeLists.txt)

```
target_compile_definitions(Foundation
	PUBLIC
		$<$<CONFIG:Debug>:_DEBUG>
		$<$<BOOL:${DISABLE_CPP14}>:POCO_DISABLE_CPP14>
		$<$<NOT:$<BOOL:${DISABLE_CPP14}>>:POCO_ENABLE_CPP14>
		$<$<BOOL:${DISABLE_CPP11}>:POCO_DISABLE_CPP11>
		$<$<NOT:$<BOOL:${DISABLE_CPP11}>>:POCO_ENABLE_CPP11>
)
```
Is that means the dll of Debug should be PocoFoundation`d`.dll, while other should be PocoFoundation.dll? If I want to install dll for RelWithDebInfo, what else should I do ?

**Comment by kblaschke** [comment]
It's meant to be the same and used as a replacement for Release in the CMake concepts (same goes for MinRelSize). Only "Debug" is special in that regard. But I concur that forcibly setting these postfix variables to a specific string isn't the right way of doing it, so I also _strongly_ vote for removing the `FORCE` in all the above `set` commands.
