### ISSUE TITLE
OpenSSL 3 compatibility

### ISSUE THREAD

**Issue by andy9a9** [pocoproject/poco#3504]
I was trying to compile the application with OpenSSL 3 crypto libs, but looks like is it's not compatible.
```
PKCS12Container::PKCS12Container(std::istream& istr, const std::string& password): _pKey(0)
{
	std::ostringstream ostr;
	Poco::StreamCopier::copyStream(istr, ostr);
	const std::string& cont = ostr.str();

	BIO *pBIO = BIO_new_mem_buf(const_cast<char*>(cont.data()), static_cast<int>(cont.size()));
	if (pBIO)
	{
		PKCS12* pPKCS12 = 0;
		d2i_PKCS12_bio(pBIO, &pPKCS12);
		BIO_free(pBIO);
		if (!pPKCS12) throw OpenSSLException("PKCS12Container(istream&, const string&)");
--->		load(pPKCS12, password);
	}
	else
	{
<---		throw Poco::NullPointerException("PKCS12Container(istream&, const string&)");
	}
}
		
void PKCS12Container::load(PKCS12* pPKCS12, const std::string& password)
{
	if (pPKCS12)
	{
		X509* pCert = 0;
		STACK_OF(X509)* pCA = 0;
--->		if (PKCS12_parse(pPKCS12, password.c_str(), &_pKey, &pCert, &pCA))
		{
		...
		}
		else
		{
			PKCS12_free(pPKCS12);
<---			throw OpenSSLException();
		}

Unable to parse PKCS#12 container: "error:0308010C:digital envelope routines::unsupported"
```
Would it be possible to make it compatible also with OpenSSL 3?

**Comment by andy9a9** [comment]
I made the tests based on `poco-1.11.2` branch, but still no success:
```
 'Unable to parse PKCS#12 container: error:12800067:DSO '

 'Unable to parse PKCS#12 container: error:078C0105:common libcrypto routines::init fail'
```

**Comment by andy9a9** [comment]
@obiltschnig wouldn't be possible to use legacy provider for now?

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/3fb001f39742c6cf7659f679bb8bbe51403fdb99

**Comment by andy9a9** [comment]
I tried it with the latest version from the testing branch, but the errors are still there.

**Comment by obiltschnig** [comment]
@andy9a9 Can you verify that you have the OpenSSL legacy provider available in your version of OpenSSL 3?
It should be a file named `legacy.so`. You could also try to set environment variable `OPENSSL_MODULES`.
See https://www.openssl.org/docs/man3.0/man3/OSSL_PROVIDER_load.html for more information.

**Comment by andy9a9** [comment]
@obiltschnig I verified, that `/usr/lib/ossl-modules/legacy.so` is part of the rootfs. I guess, that it has to be loaded automatically via `OSSL_PROVIDER_load(NULL, "legacy")`, so touching `OPENSSL_MODULES` is not necessary.

I double checked it, the first error `"error:0308010C:digital envelope routines::unsupported"` is gone, so legacy provider was loaded correctly.

But looks like, that there is a certificate problem. I'm expecting the `ecdsa-with-SHA256` algorithm, but it's returning `ecdsa-with-SHA384`. Same for serialnumber, subject... . Couldn't the verification chain somehow mixed up? Strange...

**Comment by aleks-f** [comment]
@andy9a9 I’m having trouble following what exactly is going on here. It was my understanding that this issue was fixed by pull #3448 

If that is not the case, please send a test case pull (or make a gist) exhibiting the problem.

**Comment by andy9a9** [comment]
Fine, there was an "error", that certificates have now reverse order.
```
+ #include <Poco/Version.h>
+ #if POCO_VERSION >= 0x010B0200L
+		// The P12 container returns the certificates in order root -> inter -> cert
+		// but we need cert -> inter -> root
+		// so let's reverse it
+		std::reverse(certs.begin(), certs.end());
+ #endif
```
so this issue is solved.

I've founded an another one in different component when gtest is going to close.
```
Program received signal SIGABRT, Aborted.

#0  0x0000fffff71157c8 in pthread_rwlock_rdlock ()
   from rootfs/lib/libc.so.6
#1  0x0000fffff76e41c0 in CRYPTO_THREAD_read_lock ()
   from rootfs/usr/lib/libcrypto.so.3
#2  0x0000fffff76d34a0 in ?? ()
   from rootfs/usr/lib/libcrypto.so.3
#3  0x0000fffff76e1114 in ?? ()
   from rootfs/usr/lib/libcrypto.so.3
#4  0x0000fffff76e1c5c in ?? ()
   from rootfs/usr/lib/libcrypto.so.3
#5  0x0000fffff76df21c in OSSL_PROVIDER_unload ()
   from rootfs/usr/lib/libcrypto.so.3
#6  0x0000fffff7e69260 in Poco::Crypto::OpenSSLInitializer::uninitialize() ()
   from rootfs/usr/lib/libPocoCrypto.so.82
#7  0x0000fffff7ec4d08 in Poco::Net::Context::~Context() () from rootfs/usr/lib/libPocoNetSSL.so.82
#8  0x0000fffff7ed34bc in Poco::Net::SSLManager::shutdown() () from rootfs/usr/lib/libPocoNetSSL.so.82
#9  0x0000fffff7ed38c4 in Poco::Net::SSLManager::~SSLManager() () from rootfs/usr/lib/libPocoNetSSL.so.82
#10 0x0000fffff7ed5fd4 in ?? () from rootfs/usr/lib/libPocoNetSSL.so.82
#11 0x0000fffff70d074c in __cxa_finalize () from rootfs/lib/libc.so.6
#12 0x0000fffff7ec34b4 in ?? () from rootfs/usr/lib/libPocoNetSSL.so.82
#13 0x0000fffff7fc84b8 in ?? () from rootfs/lib/ld-linux-aarch64.so.1
#14 0x0000fffff70d0178 in ?? () from rootfs/lib/libc.so.6
#15 0x0000fffff70d02a0 in exit () from rootfs/lib/libc.so.6
#16 0x0000fffff70bb234 in ?? () from rootfs/lib/libc.so.6
#17 0x0000fffff70bb30c in __libc_start_main () from rootfs/lib/libc.so.6
#18 0x0000aaaaaae8bc70 in _start () at ../sysdeps/aarch64/start.S:81
```

**Comment by aleks-f** [comment]
please open another issue with [SSCCE](http://sscce.org/)

**Comment by andy9a9** [comment]
After some analysis, looks like, that problem is on our side. I will raise an issue, if there something broken on our side.
