### ISSUE TITLE
Reference counting for bound configuration in Util::Option is broken

### ISSUE THREAD

**Issue by kblaschke** [pocoproject/poco#3507]
**Issue:**
In commit 1bf40a0, the type of the `_pConfig` member was changed from a raw pointer to `Poco::AutoPtr`, but the `duplicate()`/ `release()` calls in the implementation were not adapted accordingly. In most cases, the usage counter is now incremented twice, but not in a call to `binding()`, because the function still takes a raw pointer and assignment of a raw pointer to AutoPtr does not increment the counter. Since the Option destructor will call `release()` twice (once manually, once in the AutoPtr destructor), counter is decremented by 2.

If more than one option is bound to the same configuration object, this will result in an early free of the associated AbstractConfiguration object, and subsequent destructors will dereference a deleted pointer and cause a crash.

**How to reproduce:**
- Create a class based on `Poco::Util::Application`.
- Add a member of type `Poco::Util::MapConfiguration::Ptr` to the app and initialize it.
- Define two options in `defineOptions()` bound to the configuration above.
- Run the application.

**Expected result:**
The application should terminate without error.

**Actual result:**
Depending on the compiler and OS, the application will crash with a C library error or segmentation fault. It's not totally reliable though, depending on memory layout.

Debugging with a breakpoint in `Poco::Util::Option::~Option()` and watching pConfig will always show the behaviour.

**Comment by obiltschnig** [comment]
Fixed slightly different in [010cf8b](https://github.com/pocoproject/poco/commit/010cf8b7d0a33694168af3cd85354720622de440) by changing the `binding()` argument type to an `AbstractConfiguration::Ptr`, which relieves us from manual reference counting.

**Comment by kblaschke** [comment]
Was my first idea too, but was not sure about introducing a potentially breaking API/ABI change. Glad to see this is an option!

**Comment by obiltschnig** [comment]
(Potentially) breaking API changes are always a concern, but in this case it seems like the better option overall, as it simplifies things, is consistent with the rest of the Configuration APIs and should not break any existing code. Furthermore, it should have been changed back in 1.10.0, when the Configuration APIs have been updated to use `Poco::AutoPtr`.

**Comment by stuaxo** [comment]
This seems to be the version of poco I have with ubuntu, is there an upstream bug to get this version bumped there ?

**Comment by kblaschke** [comment]
> This seems to be the version of poco I have with ubuntu, is there an upstream bug to get this version bumped there ?

Sadly, poco versions in distros cannot be easily bumped, as this would require rebuilding/republishing all packages using poco as a dependency. It may also break third-party builds made to run on Ubuntu, if those use OS libraries.

Reason being that poco doesn't have a stable ABI between releases, being a C++ framework. So once you've published a certain version, you could only backport fixes not affecting the ABI. Which, in this particular case, sadly isn't possible as it also changes the API as well (using differerent pointer types).

It would work though by only applying my initial proposal, which just fixed the logic issue within the class.

So I fear Ubuntu and other Debian dervates are stuck with the affected release unless they update to a more recent version (>=1.12.0) in a future release.

**Comment by stuaxo** [comment]
Thanks, that's good to know.

So, for messing around with ProjectM, a music vis, the best option is probably for me to build my own libpoco.

This will solve a tangential issue I had where installing it wanted to uninstall mariadb related packages and install the mysql equivalents.
