### ISSUE TITLE
_host not set when HTTPClientSession is created with a StreamSocket

### ISSUE THREAD

**Issue by ShailishThakur** [pocoproject/poco#3512]
When creating a HTTPClientSession with a StreamSocket, in the constructor, https://github.com/pocoproject/poco/blob/master/Net/src/HTTPClientSession.cpp#L54, _host is not set.
While creating a HTTPRequest, with http 1.1 version, I always need to set the host manually using HTTPRequest::setHost(host) before calling  HTTPClientSession::sendRequest(request). If this is not done, I get 400 No Host Error as the host header for the request is empty.
Why is _host not set when HTTPClientSession is created with a StreamSocket?Is there any specific reason for this?
Can we not have _host(socket.address().host().toString()) added in this constructor (https://github.com/pocoproject/poco/blob/master/Net/src/HTTPClientSession.cpp#L54) ?

**Comment by jacobfriedman** [comment]
Bump- I've also found that given an HTTPRequest request, request.read does not read the host protocol (http://) - thus, a session created using uri.getHost will not execute correctly. (Host not found)..
