### ISSUE TITLE
Fix OpenSSL 3.0 deprecated warnings

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#3516]
Building Crypto and NetSSL_OpenSSL with OpenSSL 3.0 basically works, but there are a ton of deprecated warnings. These should be fixed by replacing the deprecated functions with their OpenSSL 3.0 counterparts.

**Comment by obiltschnig** [comment]
@andy9a9 could you guys help fixing this?

**Comment by andy9a9** [comment]
@obiltschnig Sure, could you please post here the warnings, that I can directly search for them?

**Comment by andy9a9** [comment]
I've founded only some deprecation:
```
warning: 'int EVP_PKEY_set1_EC_KEY(EVP_PKEY*, ec_key_st*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  344 |         if (!EVP_PKEY_set1_EC_KEY(_pEVPPKey, pKey))
      |              ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
```
From openssl include I can find:
```h
#  ifndef OPENSSL_NO_EC
struct ec_key_st;
OSSL_DEPRECATEDIN_3_0
int EVP_PKEY_set1_EC_KEY(EVP_PKEY *pkey, struct ec_key_st *key);
OSSL_DEPRECATEDIN_3_0
const struct ec_key_st *EVP_PKEY_get0_EC_KEY(const EVP_PKEY *pkey);
OSSL_DEPRECATEDIN_3_0
struct ec_key_st *EVP_PKEY_get1_EC_KEY(EVP_PKEY *pkey);
#  endif
```
The reason is, that `EC_KEY` should be replaced by `EVP_KEY`, but I'm not sure if it's possible.
Other option could be to add some flag like ` -Wno-error=deprecated-declarations` to disable the warning.

**Comment by aleks-f** [comment]
@obiltschnig replacing all the pre-3.0 deprecated code is not possible without a significant breakage of users' code - essentially, accessing `RSA` and `EC` directly is deprecated (`EVP` API should be used now) and we have those structures in public interfaces. For this release, I'll replace what can be replaced, mark the rest as deprecated, and the rest of the warnings will be silenced.
