### ISSUE TITLE
Incorrect WindowsTargetPlatformVersion in Foundation*.vcxproj

### ISSUE THREAD

**Issue by tpzworks** [pocoproject/poco#3542]
Foundation_*.vcxproj sets WindowsTargetPlatformVersion to 8.1
<WindowsTargetPlatformVersion>8.1</WindowsTargetPlatformVersion>

This prevents compiling under VS2022 because 10.0 SDK is installed by default.
Other vcxproj files do not set WindowsTargetPlatformVersion.

**Comment by hmartinez82** [comment]
I think this was fixed in https://github.com/pocoproject/poco/pull/3607
