### ISSUE TITLE
Crosscompiling using mingw-w64 invalid filename on case sensitive filesystem

### ISSUE THREAD

**Issue by clauderobi** [pocoproject/poco#3556]
Hi, I am trying to compile using mingw-w64 on Ubuntu. I am making progress.... 

One of the issue I am seeing is that Winsock2.h and Iphlpapi.h are actually winsock2.h and iphlpapi.h on my Ubuntu machine.

What is the correct remedy?

I am using 1.10.1

**Comment by steffenhk** [comment]
I have the same issue.

I'm pretty sure the files should be lowercase in UnWindows.h (and possibly other places as well):
https://github.com/pocoproject/poco/blob/master/Foundation/include/Poco/UnWindows.h#L32

You will probably also run into the issue with message compiler: https://github.com/pocoproject/poco/issues/2645#issuecomment-843718740
