### ISSUE TITLE
Using ProcessHandle in a class 

### ISSUE THREAD

**Issue by clauderobi** [pocoproject/poco#3560]
Hi,

I am running into an issue where I can not create a wrapper class for Process because the empty constructor for ProcessHandle is private. There are various reason for having a wrapper (command validation, raw pipe handler to extract lines, support for std::future and async operation, keeping a state allowing to implement a terminate method, etc.). In particular, my terminate method needs to call kill, which in turn needs an handle. 
I am stuck at finding a design pattern that works.

**Comment by wuxianshen** [comment]
I use a map to manage the ProcessHandle pointers, like:

std::map<std::string, Poco::ProcessHandle*> mMediaProcessMap;

And the pointers are newed by copy constructor, which is public:

Poco::ProcessHandle media_ph = Poco::Process::launch(media_cmd_path, mMediaArgsMap[media_id].getArgs());
mMediaProcessMap[media_id] = new Poco::ProcessHandle(media_ph);
