### ISSUE TITLE
SSLException "error:0A000126:SSL routines::unexpected eof while reading" when reading response body after file upload

### ISSUE THREAD

**Issue by ghosttie** [pocoproject/poco#3568]
I'm a C# developer using Poco (and C++) for the first time.  I'm trying to upload a file to an HTTPS endpoint and get the id returned in the response.

I believe the server side is fine, because I can test it using Postman and it works correctly.

However when I use Poco, the response status is 200 but the response is empty.

If I tell VS to break when any Exception is thrown, I can see that a `Poco::Net::SSLException` 
> error:0A000126:SSL routines::unexpected eof while reading

is thrown in `\poco-1.11.1-all\NetSSL_OpenSSL\src\SecureSocketImpl.cpp`

My code is:

```c++
SharedPtr<InvalidCertificateHandler> certHandler = new AcceptCertificateHandler(false);
const Context::Ptr context = new Context(Context::TLS_CLIENT_USE, "");
SSLManager::instance().initializeClient(0, certHandler, context);

const URI uri("https://localhost:44397/api/PDFDocument/UploadDocument");

HTTPSClientSession session(uri.getHost(), uri.getPort());

HTTPRequest req(HTTPRequest::HTTP_POST, uri.getPath());
req.add("Accept", "application/json");
			
HTMLForm form;
form.setEncoding(HTMLForm::ENCODING_MULTIPART);
form.addPart("file", new FilePartSource(in1, "application/pdf"));
form.prepareSubmit(req);

std::ostream& stream = session.sendRequest(req);

form.write(stream);

HTTPResponse res;

if (res.getStatus() != HTTPResponse::HTTPStatus::HTTP_OK) {
	out1 = "Error uploading file";

	return;
}
		
std::istream& responseStream = session.receiveResponse(res);
		
std::string rawJson;
StreamCopier::copyToString(responseStream, rawJson);
```

**Comment by codgunt** [comment]
Are you sure that the server side is correct? Some versions of IIS (for example) are broken and do not honour the SSL spec properly and unless you can pass the SSL_OP_IGNORE_UNEXPECTED_EOF to openssl you will get that error.  Other tools may have a custom version of OpenSSL compiled in or have added that flag themselves.
