### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nobody93** [pocoproject/poco#3582]
I just run git clone the source and build it in ubuntu 18.04, but failed at MySQL:

$ make
[ 30%] Built target Foundation
[ 35%] Built target Encodings
[ 47%] Built target XML
[ 49%] Built target JSON
[ 54%] Built target Util
[ 71%] Built target Net
[ 74%] Built target MongoDB
[ 75%] Built target Redis
[ 79%] Built target Crypto
[ 80%] Built target JWT
[ 85%] Built target NetSSL
[ 90%] Built target Data
[ 92%] Built target DataSQLite
[ 93%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/SessionHandle.cpp.o
/build/Poco/poco/Data/MySQL/src/SessionHandle.cpp: In member function ‘void Poco::Data::MySQL::SessionHandle::reset()’:
/build/Poco/poco/Data/MySQL/src/SessionHandle.cpp:187:6: error: ‘mysql_reset_connection’ was not declared in this scope
  if (mysql_reset_connection(_pHandle) != 0)
      ^~~~~~~~~~~~~~~~~~~~~~
/build/Poco/poco/Data/MySQL/src/SessionHandle.cpp:187:6: note: suggested alternative: ‘mysql_real_connect_cont’
  if (mysql_reset_connection(_pHandle) != 0)
      ^~~~~~~~~~~~~~~~~~~~~~
      mysql_real_connect_cont
Data/MySQL/CMakeFiles/DataMySQL.dir/build.make:206: recipe for target 'Data/MySQL/CMakeFiles/DataMySQL.dir/src/SessionHandle.cpp.o' failed
make[2]: *** [Data/MySQL/CMakeFiles/DataMySQL.dir/src/SessionHandle.cpp.o] Error 1
CMakeFiles/Makefile2:850: recipe for target 'Data/MySQL/CMakeFiles/DataMySQL.dir/all' failed
make[1]: *** [Data/MySQL/CMakeFiles/DataMySQL.dir/all] Error 2
Makefile:151: recipe for target 'all' failed

I did installed mysql:

$ dpkg -l | grep mysql
ii  libmysqlclient20:amd64                     5.7.34-0ubuntu0.18.04.1                          amd64        MySQL database client library
ii  libmysqlcppconn-dev:amd64                  1.1.9-1                                          amd64        MySQL Connector for C++ (development files)
ii  libmysqlcppconn7v5:amd64                   1.1.9-1                                          amd64        MySQL Connector for C++ (library)
ii  libreoffice-sdbc-mysql                     1:7.1.4~rc2-0ubuntu0.18.04.1~lo1                 amd64        MariaDB/MySQL SDBC driver for LibreOffice
ii  mysql-common                               5.8+1.0.4                                        all          MySQL database common files, e.g. /etc/mysql/my.cnf

What could I be missing?

**Comment by aleks-f** [comment]
you are missing `libmysqlclient-dev`
