### ISSUE TITLE
Poco::Net::WebSocketImpl::_buffer was not used

### ISSUE THREAD

**Issue by back2now** [pocoproject/poco#3590]
I wish Poco's websocket implementation takes a buffer to cache the next layer data.
If so, I can safely call websocket::receiveFrame() with timeout succussively without corrupting the websocket stream, like this:

```
Poco::Net::Websocket ws;
ws.setReceiveTimeout(20ms);
std::vector<uint8_t> ws_msg;
while (1) {
    // ...
    ws.receiveFrame(ws_msg.data(), ws_msg.size());
    if (timeout) {
        continue;
    }
    // ...
    handleMsg();
}
```

**Comment by aleks-f** [comment]
What's preventing you to do this:
```
ws.receiveFrame(&ws_msg[0], ws_msg.size());
```

**Comment by back2now** [comment]
If a websocket frame is sent by two tcp packet with more than 20ms timeval, then the next calling to `ws.receiveFrame` can not read correct message as the websocket stream is corrupted (just because the library didn't store the incomplete bytes). If this is by design, then websocket timeout is an unrecoverable exception.

**Comment by aleks-f** [comment]
from what I'm reading, frames are either [read completely](https://github.com/pocoproject/poco/blob/191cbdc97e1d9de023b8a65e0dc844911c06f6a8/Net/src/WebSocketImpl.cpp#L230), or else exception is thrown; but you can express your complaint in code (fix and corresponding test) and send pull request for review
