### ISSUE TITLE
Support for redis SELECT db command

### ISSUE THREAD

**Issue by tzankot** [pocoproject/poco#3593]
Hi,
Poco.Redis does not appear to have support for database select command, e.g. select 2 
Logging this in case I've missed it and someone can suggest a solution.
I've tried sending SELECT with client.sendCommand and client.execute, but am getting an error back of the type: ERR unknown command 'SELECT'.
This is a question only. 
Regards

**Comment by jiangwenkkkk** [comment]
Foundation/testsuite/src/SharedPtrTest.cpp:204
`	SharedPtr<DerivedObject, Poco::ReferenceCounter, Poco::ReleaseArrayPolicy<DerivedObject>> ptr6(new DerivedObject[10]());
	ptr5=ptr6;
`
sorry, i have a bad english.
array pointer can ansign to a object pointer;
when destroy it may be use delete  ptr,not use delete [] ptr;
it will make memory leck;

**Comment by anklean** [comment]
you can use    
    Poco::Redis::Array cmd;
    Poco::Redis::BulkString sdb="3";
    cmd.add("SELECT").add(sdb).end();    
    std::string response;

    try {
        response = _redis.execute<std::string>(cmd);
    }
