### ISSUE TITLE
SharedPtr for arry can assign to SharedPtr for a single object

### ISSUE THREAD

**Issue by jiangwenkkkk** [pocoproject/poco#3599]
`	
	SharedPtr<TestObject> ptr5;
	ptr5=ptr2;
	int* ptr7= new int[10]{0,1,2,3,4,5,6,7,8,9};
	SharedPtr<DerivedObject, Poco::ReferenceCounter, Poco::ReleaseArrayPolicy<DerivedObject>> ptr6(new DerivedObject[10]());
	ptr5=ptr6;`

ptr5 = ptr6, that can make memory leak

**Comment by andrewauclair** [comment]
You should probably make a better example that's actually understandable and formatted correctly. I don't see what you mean. Bad names, bad formatting and an incomplete example don't help.

**Comment by jiangwenkkkk** [comment]
Foundation/testsuite/src/SharedPtrTest.cpp:204
SharedPtr<DerivedObject, Poco::ReferenceCounter, Poco::ReleaseArrayPolicy<DerivedObject>> ptr6(new DerivedObject[10]()); ptr5=ptr6;
sorry, i have a bad english.
array pointer can ansign to a object pointer;
when destroy it may be use delete ptr,not use delete [] ptr;
it will make memory leck;
