### ISSUE TITLE
Missing `</File>` closing tag in Util_vs90.vcproj

### ISSUE THREAD

**Issue by hmartinez82** [pocoproject/poco#3609]
I stumbled upon this while running ProGen for the Utils project.
I was using a debug_static_mt build of ProGen.

**Steps to repro:**
- Build ProGen debug static_mt for x64
- Run ProGen for the Utils project

ProGen fails with: `SAXParseException: Tag mismatch in 'D:\Dev\Github\poco\Util\Util_vs90.vcproj', line 597 column 5`

I tracked down the error to this line https://github.com/pocoproject/poco/blob/master/XML/src/xmlparse.cpp#L3039

It seems that the parser is trying to match a `<File>` tag with the closing of a `</Filter>` tag. 

But I have no idea how to fix this, :-(

**Comment by aleks-f** [comment]
```diff
λ git diff ../Util/Util_vs90.vcproj
diff --git a/Util/Util_vs90.vcproj b/Util/Util_vs90.vcproj
index bf81a867d..aab41663b 100644
--- a/Util/Util_vs90.vcproj
+++ b/Util/Util_vs90.vcproj
@@ -574,6 +574,7 @@
                                <File
                                        RelativePath=".\include\Poco\Util\LocalConfigurationView.h"
                                        >
+                               </File>
                                <File
                                        RelativePath=".\include\Poco\Util\LoggingConfigurator.h"
                                        >
```

**Comment by aleks-f** [comment]
@hmartinez82 I'l leave the fix to you since you're already working on generating project files
