### ISSUE TITLE
PocoNET TestSuite fails to build with Visual Studio projects

### ISSUE THREAD

**Issue by hmartinez82** [pocoproject/poco#3614]
The testsuite fails to build with

`1>SocketsTestSuite.obj : error LNK2019: unresolved external symbol "public: static class CppUnit::Test * __cdecl SocketProactorTest::suite(void)" (?suite@SocketProactorTest@@SAPEAVTest@CppUnit@@XZ) referenced in function "public: static class CppUnit::Test * __cdecl SocketsTestSuite::suite(void)" (?suite@SocketsTestSuite@@SAPEAVTest@CppUnit@@XZ)`

The offending line is: https://github.com/pocoproject/poco/blob/devel/Net/testsuite/src/SocketsTestSuite.cpp#L35

I noticed that the SocketProactor.h/.cpp files are not in the Net project and that the respective test classes are also not in the TestSuite project, but all the 4 files are in the filesystem.
I couldn't find documentation online about the SocketProactor class. So my question is:
- Is this a deprecated class and the fix is just to remove the offending line, or
- Should the class and its unit test be added to `TestSuite_vs90.vcproj` and then ProGen'd ?

**Comment by aleks-f** [comment]
These are new classes, should be added.

**Comment by aleks-f** [comment]
@hmartinez82 do you have time to fix this?

**Comment by hmartinez82** [comment]
Yes
