### ISSUE TITLE
CppUnit `notEqualsMessage` causing compile errors

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#3615]
[This change](https://github.com/pocoproject/poco/commit/0c242e9b2ad606fb6b893233e9672be70c8aabc7#diff-9dfe208db8a75d1872b7a5ffbcd4f95a9c532992b493d954d552b98d2224d0deR158) caused char*/string comparisons compile errors. After [this fix](https://github.com/pocoproject/poco/commit/a17a7bf0276a900c091ddd73461c45bd132dae1b#), there are still problems with enums comparison (MSVC resolves them to void*)

**Comment by obiltschnig** [comment]
Well, it would not be C++ if one would not have to come up with an overly complex solution for a simple problem.
