### ISSUE TITLE
ConfigurationView and JSON is broken for array access

### ISSUE THREAD

**Issue by Coder666** [pocoproject/poco#3635]
Hi,

When using `JSONConfiguration` in combination with `ConfigurationView` there is an issue with array access

For example, the following code does not work as expected:

```
std::string json = R"json(   { "foo" : [ "bar" ] }   )json";

std::shared_ptr< Poco::Util::JSONConfiguration > pConfig = std::make_shared< Poco::Util::JSONConfiguration >();
std::istringstream stream(json);
pConfig->load(stream);

Poco::Util::AbstractConfiguration::Ptr pView = pConfig->createView( "foo" );

//now grab item 0 which should be "bar"

std::string shouldBeBar = pView->getString("[0]");

//now grab item 1 which is not valid and should throw an exception

std::string shouldThrow= pView->getString("[1]");

// ERROR!! <--- No exception is thrown
```

In the code above, `shouldThrow` is set to the string `{ "foo" : [ "bar" ] }` which is incorrect.

The error can be tracked to this code in the `ConfigurationView`, the first term evaluates to false (not found) then the second term is evaluated and returns true, also setting value to `{ "foo" : [ "bar" ] }` clearly this is not expected behaviour.

```
bool ConfigurationView::getRaw(const std::string& key, std::string& value) const
{
	std::string translatedKey = translateKey(key);
	return _pConfig->getRaw(translatedKey, value) || _pConfig->getRaw(key, value);
}
```

At the moment I am able to hack in a fix by removing the second term with no ill effects.  However this may impact other configuration types.  Needs some serious investigation...

```
bool ConfigurationView::getRaw(const std::string& key, std::string& value) const
{
	std::string translatedKey = translateKey(key);
	return _pConfig->getRaw(translatedKey, value);
}
```

Cheers

Tom

**Comment by aleks-f** [comment]
@KevDi

**Comment by KevDi** [comment]
@aleks-f what are the values for `translatedKey` and `value` for the `getRaw` call? And what are the values of `key` and `value` for the second call to `getRaw`? During the development of the `LocalConfigurationView` i saw that the first call to `getRaw` just searches the current viewed area of the config, where the second call also looks in the outher Parts of the Config.

**Comment by aleks-f** [comment]
@KevDi I don't know off the top of my head - please understand that we have to deal with hundreds of issues and contributions. It's ok when we have to dig into details of bug reports, but when it comes to contributing new features, it would be really nice if the contribution would not break things and, when it does, the contributor would take care of it. 

I have accepted your contribution based on tests passing. But, apparently the tests do not cover all aspects of it; so, if you could please look into the details of this and fix, it will be appreciated

**Comment by KevDi** [comment]
Ok seems like my respond via email was not added here however :D 
@Coder666 Regarding your issue i had some more or less similar issue where i want to check if a specific key exists in a specific part of a XML Configuration. With the Standard `ConfigurationView` i was unable to check because the same key exists also in the outer part of the configuration. Because of the `return _pConfig->getRaw(translatedKey, value) || _pConfig->getRaw(key, value);` both the viewed part and also the outer parts are searched for the given Key. Thats mostly because otherwise Placeholder Support would not work.

As a way around this i introduced the `LocalConfigurationView` Class. 

@aleks-f  This issue is not affected by my Pull Request #3529 
@Coder666 Your "hack" is the way on how i implemented the `LocalConfigurationView` so feel free to take a look at the Pull Request #3529 .
As you are currently working with the Codebase for the `1.12.0` Release feel free to test this class.
Your example should then look like this:

```
std::string json = R"json(   { "foo" : [ "bar" ] }   )json";

std::shared_ptr< Poco::Util::JSONConfiguration > pConfig = std::make_shared< Poco::Util::JSONConfiguration >();
std::istringstream stream(json);
pConfig->load(stream);

Poco::Util::AbstractConfiguration::Ptr pView = pConfig->createLocalView( "foo" ); //Change is made here

//now grab item 0 which should be "bar"

std::string shouldBeBar = pView->getString("[0]");

//now grab item 1 which is not valid and should throw an exception

std::string shouldThrow= pView->getString("[1]"); // should now throw an exception
```

**Comment by aleks-f** [comment]
@KevDi ok, sorry - I mixed `ConfigurationView` and `LocalConfigurationView`

**Comment by KevDi** [comment]
According to my first observation the issue mentioned was the case why I added the `LocalConfigurationView`. In the above issue it's the problem I also had with the standard `ConfigurationView`. If you just want to look for a specific key in a viewed part of the configuration and that key is also available outside of that viewed part this is not possible with the standard `ConfigurationView`. The "Hack" that was mentioned is exactly what I have done in the `LocalConfigurationView`. So if he uses the current dev version of Poco with my Pull Request Merged in his code should work if he just replace `creatrView` with `creatrLocalView`. Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Aleksandar Fabijanic ***@***.***>Datum: So., 12. Juni 2022, 15:00An: pocoproject/poco ***@***.***>Cc: Kevin Dick ***@***.***>, Mention ***@***.***>Betreff: Re: [pocoproject/poco] ConfigurationView and JSON is broken for array access (Issue #3635)
@KevDi I don't know off the top of my head - please understand that we have to deal with hundreds of issues and contributions. It's ok when we have to dig into details of bug reports, but when it comes to contributing new features, it would be really nice if the contribution would not break things and, when it does, the contributor would take care of it.
I have accepted your contribution based on tests passing. But, apparently the tests do not cover all aspects of it; so, if you could please look into the details of this and fix, it will be appreciated
