### ISSUE TITLE
ProGen does not properly generate Target Name

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#3666]
![image](https://user-images.githubusercontent.com/2429093/177521330-d62eb24c-5ca4-4ccd-b60d-7b66edb4fb66.png)

**Comment by hmartinez82** [comment]
@aleks-f Is this affecting all VS versions or just VS2022?

**Comment by hmartinez82** [comment]
Regarding the Target Name, I can't reproduce it. Using the devel branch, I built progen with VS2019 and progen'd the Crypto and Net projects just to see if Target Name was being set. And it is. The Test Suite projects are correct too for all archs (Win32 screenshot below):
![image](https://user-images.githubusercontent.com/1100440/182047752-282ea8c6-4767-47e8-9a90-eae8585948bf.png)

**Comment by aleks-f** [comment]
I guess I'll have to check why/how I experienced this. I believe it was with VS 2015.

**Comment by aleks-f** [comment]
It would be good to have a [CI](https://github.com/pocoproject/poco/blob/master/.github/workflows/ci.yml) entry where progen regenerates all release libraries projects and builds them. right now we only have cmake-based windows CI.
