### ISSUE TITLE
NumberFormatter: add Options enum for controlling prefix and lowercase

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#3667]
Following up the discussion in #3657, let's fix this before 1.12 release.

**Comment by aleks-f** [comment]
@matejk please modify [this](https://github.com/pocoproject/poco/pull/4306/files#diff-4c35bdf6a4c7fdd32b9ab1a8e02c9acb610c600a670dde0f8d53e97ad00cd399) like [this](https://github.com/pocoproject/poco/pull/3657#issuecomment-1174184075) and this
