### ISSUE TITLE
HTTPClientSession::receiveResponse() not timing out on Windows

### ISSUE THREAD

**Issue by MarcusTomlinson** [pocoproject/poco#3672]
I have the same code compiled on Windows and macOS:

```
Poco::Net::HTTPClientSession session( "localhost", 9894 );
session.setTimeout( Poco::Timespan( 0, 100 ) );

...

std::ostream& reqOs = session.sendRequest( req );

...

Poco::Net::HTTPResponse res;
std::istream& resIs = session.receiveResponse( res );
```

(`localhost:9894` waits for 10 seconds in it's `HTTPRequestHandler` before returning)

On macOS `receiveResponse()` throws `TimeoutException` after 100ms as expected, but on Windows it will block for the full 10s and return the stream happily.

**Comment by jngrb** [comment]
I also observed a timeout issues (with SSL connections) on Windows, see #3806 - it could be that these are related

Please state the library and OS versions that your are using.

**Comment by MarcusTomlinson** [comment]
I experienced this on Windows 11, using POCO 1.11.3 with plain HTTP.
