### ISSUE TITLE
Make socket reactor more easy to use

### ISSUE THREAD

**Issue by JackyWoo** [pocoproject/poco#3678]
I use `SocketReactor` in Poco.  And I found that user must do resource management in `UDF Handler` which can be improved by handling it in `SocketReactor`.

Resource management means:
1. remove all  events in `NObserver`
2. delete `UDF Handler`

In my case there is a uncaught error in my `UDF Handler` and it lead to 100% CPU usage.

Possible fix:

1. Clear  events `SocketReactor::dispatch` reveive error.
2. Create a new `NObserver` whose `_pObject`  is a `RefCountedObject`

This change may lead to compatibility issue.

**Comment by JackyWoo** [comment]
SSCCE ：

Use `Net/samples/EchoServer/src/EchoServer.cpp` just modify `onSocketWritable` which throw something.

```
        void onSocketWritable(const AutoPtr<WritableNotification>& pNf)
	{
		try
		{
			_socket.sendBytes(_fifoOut);
			throw 1;
		}
		catch (Poco::Exception& exc)
		{
			Application& app = Application::instance();
			app.logger().log(exc);
			delete this;
		}
	}
```

**Comment by JackyWoo** [comment]
@aleks-f How about the idea `Make socket reactor more easy to use`? Expecting for reply.

**Comment by aleks-f** [comment]
It's quite a big diff, did not have time to look at it yet. There are conflicts in the pull now, fix and I'll review as soon as I get a chance.

**Comment by JackyWoo** [comment]
@aleks-f Conflicts are fixed. Pls review when you have a change.
