### ISSUE TITLE
Question: Adding Prometheus to existing Server

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#3680]
Nice to see that Poco Supports Prometheus. 
In the Example i saw that there was created a `MetricsServer` to expose the metrics via the `\metrics` Endpoint.

But is it also possible to add the `/metrics` Endpoint to an existing `HTTPServer`? I already have an `HTTPServer` which exposes some `REST Endpoints` and it would be nice to add also the `/metrics` Endpoint to it.

**Comment by obiltschnig** [comment]
Yes, just create a `Poco::Prometheus::MetricsRequestHandler` in your `Poco::Net::HTTPRequestHandlerFactory` for the `/metrics` (or whatever you want) path.
