### ISSUE TITLE
SIGSEGV in OSSL_PROVIDER_unload with static OpenSSL3

### ISSUE THREAD

**Issue by andreya108** [pocoproject/poco#3686]
**Describe the bug**
SIGSEGV occurs when OSSL_PROVIDER_unload is invoked during OpenSSL deinitialization in POCO if OpenSSL3 is used as static libraries.
This issue appeared in POCO 1.12.0.
All is ok with POCO version 1.11.3

**To Reproduce**
Just using HTTPSClientSession + static OpenSSL3

**Expected behavior**
No SIGSEGV.

**Screenshots**
[![wjjEoG.md.png](https://iili.io/wjjEoG.md.png)](https://freeimage.host/i/wjjEoG)

**Please add relevant environment information:**
 - Linux x86_64 Ubuntu 22.04
 - POCO Version 1.12.0
 - OPENSSL 3.0.5 no-shared no-module

**Comment by aleks-f** [comment]
#3562
c976c32e5249cb8a2433e7abfa095c1fe8dc4f8e
