### ISSUE TITLE
Linking Crypto-testrunner fails

### ISSUE THREAD

**Issue by FreelancerCGN** [pocoproject/poco#3688]
Poco 1.12.1
Ubuntu 20.04.4 LTS
CMake 3.16.3
The linking of Crypto-testrunner fails.

[ 89%] Linking CXX executable ../../bin/Crypto-testrunner

/usr/bin/ld: ../../lib/libPocoCryptod.a(Envelope.cpp.o): in function `std::iterator_traits<Poco::Any const*>::iterator_category std::__iterator_category<Poco::Any const*>(Poco::Any const* const&)':
/home/poco/poco-1.12.1-all/Crypto/include/Poco/Crypto/Envelope.h:154: multiple definition of `Poco::Crypto::Envelope::getContent() const'; CMakeFiles/Crypto-testrunner.dir/src/EnvelopeTest.cpp.o:/home/poco/poco-1.12.1-all/Crypto/include/Poco/Crypto/Envelope.h:154: first defined here

/usr/bin/ld: ../../lib/libPocoCryptod.a(Envelope.cpp.o): in function `std::operator!=(std::allocator<unsigned char> const&, std::allocator<unsigned char> const&)':
/home/poco/poco-1.12.1-all/Crypto/include/Poco/Crypto/Envelope.h:160: multiple definition of `Poco::Crypto::Envelope::setContent(std::vector<unsigned char, std::allocator<unsigned char> > const&)'; CMakeFiles/Crypto-testrunner.dir/src/EnvelopeTest.cpp.o:/home/poco/poco-1.12.1-all/Crypto/include/Poco/Crypto/Envelope.h:160: first defined here

collect2: error: ld returned 1 exit status

make[2]: *** [Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/build.make:215: bin/Crypto-testrunner] Error 1

make[1]: *** [CMakeFiles/Makefile2:5146: Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/all] Error 2

make: *** [Makefile:163: all] Error 2

**Comment by aleks-f** [comment]
Can't reproduce
```
Scanning dependencies of target Crypto-testrunner
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/CryptoTest.cpp.o
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/CryptoTestSuite.cpp.o
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/DigestEngineTest.cpp.o
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/Driver.cpp.o
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/ECTest.cpp.o
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/EVPTest.cpp.o
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/EnvelopeTest.cpp.o
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/PKCS12ContainerTest.cpp.o
[ 87%] Building CXX object Crypto/testsuite/CMakeFiles/Crypto-testrunner.dir/src/RSATest.cpp.o
[ 88%] Linking CXX executable ../../bin/Crypto-testrunner
[ 88%] Built target Crypto-testrunner
```
```
# lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

```
# cmake --version
cmake version 3.16.3
```
```
# g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

**Comment by aleks-f** [comment]
strangely enough, it was an issue indeed but no compiler complained
