### ISSUE TITLE
VS2022 compilation issues

### ISSUE THREAD

**Issue by marrak** [pocoproject/poco#3693]
Poco 1.12.1
Windows 10, VS2022 v17.2.6

1) Net -> Net_vs170.vcxproj includes VS2019 configuration (1.42 instead of 1.43 etc.)
After manually fixed above there is another issue:
```
error C2039: "SpinlockMutex"
```
due to 
```
#if __cplusplus >= 201103L
```
in Mutex.h

2) Crypto -> EVPCipherImpl missing in Crypto_vs170.vcxproj
```
CipherFactory.obj : error LNK2019:  "public: __cdecl Poco::Crypto::EVPCipherImpl::EVPCip
herImpl(class Poco::Crypto::EVPPKey const &)" (??0EVPCipherImpl@Crypto@Poco@@QEAA@AEBVEVPPKey@12@@Z)  "public: class Poco::Crypto::Cipher * __cdecl Poco::Crypto::CipherFactory::createCipher(class Poco::Crypto::EVPPKey
const &)" (?createCipher@CipherFactory@Crypto@Poco@@QEAAPEAVCipher@23@AEBVEVPPKey@23@@Z)
```

Please fix or explain if I'm doing something wrong.
Regards

**Comment by aleks-f** [comment]
it needs `/Zc:__cplusplus`, see https://github.com/pocoproject/poco/issues/3665

will regenerate all VS projects for 1.12.2; in the meantime, you can do it yourself, manually or using [ProGen](https://github.com/pocoproject/poco/tree/master/ProGen)

**Comment by marrak** [comment]
Thx, works for us in 1.12.2 :)
