### ISSUE TITLE
Support log stack trace

### ISSUE THREAD

**Issue by JackyWoo** [pocoproject/poco#3696]
**Is your feature request related to a problem? Please describe.**
Add stack trace to `Exception` to help user understanding exceptions. When log exception user can get output like Java.

**Describe the solution you'd like**
1. Add stack trace which  implemented by libunwind or something else to `Exception`.
2. Add log exception API to `Logger`

**Comment by JackyWoo** [comment]
@aleks-f   @obiltschnig How about the idea? Expecting for reply.

**Comment by aleks-f** [comment]
Idea is good and useful; implement it as a separate group of class(es).

Adding it to exceptions should be done carefully, if at all (exceptions already accept strings, so whoever needs/wants stack trace info can propagate it as a string):
- a new constructor, taking stack trace
- must be an optional exception content

I suggest you start with creating a stack trace class(es), then we can see how and whether to add that to exceptions.

**Comment by JackyWoo** [comment]
Thanks, I wonder whether we should introduce `libunwind ` for stack trace catching?

**Comment by aleks-f** [comment]
Well, any such embedding is a "double-edged sword" - on one side, (+) beside the mainstream linux and osx (and clang on windows), libunwind covers lots of platforms; however, by introducing it, (-) we'd be introducing yet another chunk of foreign code to be synced and maintained. (+)License (MIT) seems to be ok for poco embedding. (+/-)MSVC would have to be coded separately for windows support, but this is the case any way we go.
I'd say yes, but let's wait and see what @obiltschnig has to say, if anything.

**Comment by JackyWoo** [comment]
Thanks. I will focus on the `SocketReactor` first.
