### ISSUE TITLE
VS2019 failing to compile 'Crypto' in 1.12.0

### ISSUE THREAD

**Issue by Boris-Stefanov** [pocoproject/poco#3697]
OS Windows 10 Enterprise; also tested on Windows Server 2016 Standard;
Poco 1.12.0
OpenSSL 3.0.5
compiler VS2019 x64

MSBuild fails to compile libraries for 'Crypto'.

Stack trace:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++ Building [Crypto_vs160.vcxproj]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

msbuild /clp:NoSummary /nologo /v:minimal /p:UseEnv=true /m /t:build /p:Configuration=debug_shared /p:Platform=x64 Crypto_vs160.vcxproj
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(517,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\jenkins\workspace\build_poco_windows_64_vs2019\poco-1.12.0-all\Crypto\Crypto_vs160.vcxproj]
  Cipher.cpp
  CipherFactory.cpp
  CipherImpl.cpp
  CipherKey.cpp
  CipherKeyImpl.cpp
  CryptoException.cpp
  CryptoStream.cpp
  CryptoTransform.cpp
  DigestEngine.cpp
  ECDSADigestEngine.cpp
  ECKey.cpp
  ECKeyImpl.cpp
  EVPPKey.cpp
  KeyPair.cpp
  KeyPairImpl.cpp
  OpenSSLInitializer.cpp
  PKCS12Container.cpp
  RSACipherImpl.cpp
  OpenSSL 3.0.5 5 Jul 2022
  RSADigestEngine.cpp
  RSAKey.cpp
  RSAKeyImpl.cpp
  X509Certificate.cpp
     Creating library ..\lib64\PocoCryptod.lib and object ..\lib64\PocoCryptod.exp
CipherFactory.obj : error LNK2019: unresolved external symbol "public: __cdecl Poco::Crypto::EVPCipherImpl::EVPCipherImpl(class Poco::Crypto::EVPPKey const &)" (??0EVPCipherImpl@Crypto@Poco@@QEAA@AEBVEVPPKey@12@@Z) referenced in function "public: class Poco::Crypto::Cipher * __cdecl Poco::Crypto::CipherFactory::createCipher(class Poco::Crypto::EVPPKey const &)" (?createCipher@CipherFactory@Crypto@Poco@@QEAAPEAVCipher@23@AEBVEVPPKey@23@@Z) [C:\jenkins\workspace\build_poco_windows_64_vs2019\poco-1.12.0-all\Crypto\Crypto_vs160.vcxproj]
..\bin64\PocoCrypto64d.dll : fatal error LNK1120: 1 unresolved externals [C:\jenkins\workspace\build_poco_windows_64_vs2019\poco-1.12.0-all\Crypto\Crypto_vs160.vcxproj]

**Comment by OneTop4458** [comment]
Look at the
https://github.com/pocoproject/poco/issues/3693
