### ISSUE TITLE
SIGABRT in OSSL_PROVIDER_unload with static OpenSSL3

### ISSUE THREAD

**Issue by andreya108** [pocoproject/poco#3698]
**Describe the bug**
SIGABRT occurs when OSSL_PROVIDER_unload is invoked during OpenSSL deinitialization in POCO if OpenSSL3 is used as static libraries.
This issue appeared in POCO 1.12.1.
SIGSEGV in POCO 1.12.0 (fixed).
All is ok with POCO version 1.11.3

**To Reproduce**
Just using HTTPSClientSession + static OpenSSL3

**Expected behavior**
No SIGABRT.

**Screenshots**
[![wUKVyB.md.png](https://iili.io/wUKVyB.md.png)](https://freeimage.host/i/wUKVyB)

**Please add relevant environment information:**
 - Linux x86_64 Ubuntu 22.04
 - POCO Version 1.12.1
 - OPENSSL 3.0.5 no-shared no-module

**Comment by aleks-f** [comment]
please try 1.12.2 branch before we release (likely monday)

**Comment by andreya108** [comment]
I've tried poco-1.12.2 branch and looks like now the issued is fixed, thank you!
