### ISSUE TITLE
Net/NetSSL_OpenSSL/NetSSL_Win - include problem

### ISSUE THREAD

**Issue by muffmolch** [pocoproject/poco#3706]
We are updating from v1.9.0 to v1.12.1
In CMake I have enabled Enable_NET, Enable_NETSSL and Enable_NETSSL_Win. Paths and libs all set correctly (static build).

And now we get lots of Net::Context errors when compiling our program:
```

1>E:\DitecLibs\Packages\poco\poco_1_12_1_0\include\Poco/Net/SocketDefs.h(29,1): warning C4005: 'FD_SETSIZE': macro redefinition
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(133): message : see previous definition of 'FD_SETSIZE'
1>..\..\Shared\Http\HTTPSslInit.cpp(17,214): error C2661: 'Poco::Net::Context::Context': no overloaded function takes 8 arguments
1>..\..\Shared\Http\HTTPSslInit.cpp(19,11): error C2039: 'enableSessionCache': is not a member of 'Poco::Net::Context'
1>E:\DitecLibs\Packages\poco\poco_1_12_1_0\include\Poco/Net/SSLManager.h(45): message : see declaration of 'Poco::Net::Context'
```

As I said, I configured the Poco package with CMAke, built the libs with VS2022 and then installed them with the INSTALL project. 
However, it seems that only the "Net\include" folder is copied. But we use the Context from SSL. 
So my question: what exactly is the procedure here? Which headers should one use? Since they have the same name, I assumed that CMake would already do the right thing ...

Do I have to set the preprocesser POCO_NETSSL_WIN somewhere?

**Comment by muffmolch** [comment]
In `detail: the `git-zip-file contains these `Context.h` files: 
```
E:\ProgalSrc\Libs4.5.0\Poco\poco-poco-1.12.1-release\ActiveRecord\include\Poco\ActiveRecord\Context.h
E:\ProgalSrc\Libs4.5.0\Poco\poco-poco-1.12.1-release\NetSSL_OpenSSL\include\Poco\Net\Context.h
E:\ProgalSrc\Libs4.5.0\Poco\poco-poco-1.12.1-release\NetSSL_Win\include\Poco\Net\Context.h
```
After **installing** only these are inside my package:
`C:\Program Files (x86)\Poco\include\Poco\Net\Context.h
C:\Program Files (x86)\Poco\include\Poco\ActiveRecord\Context.h`

whereas the `C:\Program Files (x86)\Poco\include\Poco\Net\Context.h` equals `E:\ProgalSrc\Libs4.5.0\Poco\poco-poco-1.12.1-release\NetSSL_Win\include\Poco\Net\Context.h´

**Comment by muffmolch** [comment]
Really? No one?  
My simple goal:
How do I get the NetSSL headers to end up in Include\Net instead of the Net headers after "install"?

**Comment by aleks-f** [comment]
The github archives are not the official release - they are only snapshot at the time of the release and contain everything in the repository. Official releases are at https://pocoproject.org/download.html#packages

If you get the official release, you'll notice that NetSSL_Win is not there - it is one of the unreleased "use at your own risk" libraries.

**Comment by muffmolch** [comment]
Thanks, Aleks! Meanwhile I deactivated this option and everything seems to be fine

**Comment by muffmolch** [comment]
![image](https://user-images.githubusercontent.com/6783248/180985268-a1367e48-8dc8-4e4e-bcde-fd711839eb1b.png)
But this option is also in the official download! But not the "NetSSL_Win" folder
