### ISSUE TITLE
Compiling with clang_cl_x64_x64 on Visual Studio 2022 failed

### ISSUE THREAD

**Issue by shakilodim** [pocoproject/poco#3716]
POCO master
Windows 10
Visual Studio 2022, 17.2.6, CMake, toolset clang_cl_x64_x64 failed with output:

>   [430/631] Building CXX object Net\CMakeFiles\Net.dir\src\PollSet.cpp.obj
  FAILED: Net/CMakeFiles/Net.dir/src/PollSet.cpp.obj 
  C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\Llvm\x64\bin\clang-cl.exe  /nologo -TP -DNet_EXPORTS -DPOCO_ENABLE_CPP11 -DPOCO_ENABLE_CPP14 -DPOCO_NO_AUTOMATIC_LIBS -DPOCO_OS_FAMILY_WINDOWS -DUNICODE -D_DEBUG -D_UNICODE -IC:\Users\shaki\source\github\poco\Net\include -IC:\Users\shaki\source\github\poco\Net\src -IC:\Users\shaki\source\github\poco\Foundation\include -m64 -fdiagnostics-absolute-paths  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /Zc:__cplusplus /MDd /Zi /Ob0 /Od /RTC1 -std:c++14 /showIncludes /FoNet\CMakeFiles\Net.dir\src\PollSet.cpp.obj /FdNet\CMakeFiles\Net.dir\ -c -- C:\Users\shaki\source\github\poco\Net\src\PollSet.cpp
C:\Users\shaki\source\github\poco\Net\src\PollSet.cpp(76,26): error : ordered comparison between pointer and zero ('void *' and 'int')
                  if ((err) || (_epollfd < 0))
                                ~~~~~~~~ ^ ~
C:\Users\shaki\source\github\poco\Net\src\PollSet.cpp(89,16): error : ordered comparison between pointer and zero ('void *' and 'int')
                  if (_epollfd >= 0) close(_epollfd);
                      ~~~~~~~~ ^  ~
C:\Users\shaki\source\github\poco\Net\src\PollSet.cpp(144,17): error : ordered comparison between pointer and zero ('void *' and 'int')
                          if (_epollfd < 0) SocketImpl::error();
                              ~~~~~~~~ ^ ~
  3 errors generated.

**Comment by aleks-f** [comment]
well, try to `static_cast` it to `int` and send pull to devel branch if it works. MSVC compiler seems to have no problem with it
