### ISSUE TITLE
PocoCrypto fails to build with Visual Studio projects

### ISSUE THREAD

**Issue by OneTop4458** [pocoproject/poco#3721]
`1>CipherFactory.obj : error LNK2019: "public: __thiscall Poco::Crypto::EVPCipherImpl::EVPCipherImpl(class Poco::Crypto::EVPPKey const &)" (??0EVPCipherImpl@Crypto@Poco@@QAE@ABVEVPPKey@12@@Z)"public: class Poco::Crypto::Cipher * __thiscall
 Poco::Crypto::CipherFactory::createCipher(class Poco::Crypto::EVPPKey const &)" (?createCipher@CipherFactory@Crypto@Poco@@QAEPAVCipher@23@ABVEVPPKey@23@@Z) 함수에서 참조되는 확인할 수 없는 외부 기호 [C:\Users\WDAGUtilityAccount\Downloads\poco\Crypto\Cry
pto_vs170.vcxproj]
..\bin\PocoCrypto.dll : fatal error LNK1120: 1개의 확인할 수 없는 외부 참조입니다. [C:\Users\WDAGUtilityAccount\Downloads\poco\Crypto\Crypto_vs170.vcxproj]`

The offending line is: https://github.com/pocoproject/poco/blob/devel/Crypto/src/CipherFactory.cpp#L21

`2>CryptoTestSuite.obj : error LNK2019: "public: static class CppUnit::Test * __cdecl EnvelopeTest::suite(void)" (?suite@EnvelopeTest@@SAPAVTest@CppUnit@@XZ)"public: static class CppUnit::Test * __cdecl CryptoTestSuite::suite(void)" (?suit
e@CryptoTestSuite@@SAPAVTest@CppUnit@@XZ) 함수에서 참조되는 확인할 수 없는 외부 기호 [C:\Users\WDAGUtilityAccount\Downloads\poco\Crypto\testsuite\TestSuite_vs170.vcxproj]
bin\TestSuite.exe : fatal error LNK1120: 1개의 확인할 수 없는 외부 참조입니다. [C:\Users\WDAGUtilityAccount\Downloads\poco\Crypto\testsuite\TestSuite_vs170.vcxproj]`

The offending line is: https://github.com/pocoproject/poco/blob/devel/Crypto/testsuite/src/CryptoTestSuite.cpp#L24

I noticed that the Envelope.h/.cpp, EVPCipherImpl.h/.cpp, EnvelopeTest.h/.cpp files are not in the Crypto project and that the respective test classes are also not in the TestSuite project, but all the 6 files are in the filesystem.

Missing haters identified include:
Crypto -> Envelope.h, EVPCipherImpl.h
Crypto TestSuite -> EnvelopeTest.h

When I checked, it seems that there are headers missing in MSVC for projects other than Crypto.
Looks like the whole Poco project needs MSVC build check.

**Comment by OneTop4458** [comment]
Reference Issue
https://github.com/pocoproject/poco/issues/3614

**Comment by OneTop4458** [comment]
Related Issues
https://github.com/pocoproject/poco/issues/3697
https://github.com/pocoproject/poco/issues/3693

**Comment by aleks-f** [comment]
@hmartinez82 could do one more review of all the generated VS projects for 1.12.2 release and fix the ones not properly generated (ie. no arm arch or missing files)? It looks like some of them were not properly generated, or perhaps some changes got lost during merging.

**Comment by hmartinez82** [comment]
Will do

**Comment by hmartinez82** [comment]
@aleks-f  I looked at the project files. They seem to have the important bits. Did I forget to completely progen Crypto before for ARM64?

**Comment by aleks-f** [comment]
@hmartinez82 either that, or your changes got lost in the merging process - devel was out of sync with release branches for a while before 1.12.0, so there was a lot going on before that release

**Comment by aleks-f** [comment]
@hmartinez82 I also saw this progen problem at some point, can you please check it: https://github.com/pocoproject/poco/issues/3666

**Comment by hmartinez82** [comment]
@aleks-f ok I confirm that ARM64 is broken in Crypto. `ec1fa5aaf0716b61496c8a8ac0fb0fe19c2ebb29` is the commit that removed it. The VS2022 solution files are not even loading due to missing configurations in the .vcxproj files. 

I think that the progen call there didn't add ARM64 with `progen.bat Win32,x64,ARM64`
