### ISSUE TITLE
Poco 1.12.1 Any.h crashes MSVC compiler in C++20 or latest mode

### ISSUE THREAD

**Issue by RazielXYZ** [pocoproject/poco#3728]
**Describe the bug**
When attempting to include and use Poco in a project, if building under MSVC with the /std:c++20 or /std:c++latest flags, the compiler crashes and the build cannot complete, due to the Poco\Any.h file.

**To Reproduce**
Attempt usage of Poco in an MSVC project using /std:c++20 or /std:c++latest, including Poco Any.h.

**Expected behavior**
No errors.

**Logs**
```
1>..\Include\Poco\Any.h(124,1): fatal error C1001: Internal compiler error.
1>(compiler file 'msc1.cpp', line 1693)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>If possible please provide a repro here: https://developercommunity.visualstudio.com
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>..\Include\Poco\Any.h(210): message : see reference to class template instantiation 'Poco::Placeholder<PlaceholderT,SizeV>' being compiled
1>INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe'
1>    Please choose the Technical Support command on the Visual C++
1>    Help menu, or open the Technical Support help file for more information
```

**Please add relevant environment information:**
 - OS: Windows 10
 - POCO 1.12.1
 - Visual Studio 2022, running Toolset v143, subversion 14.32, Windows SDK 10.0.22621.0

**Comment by RazielXYZ** [comment]
Probably duplicate of https://github.com/pocoproject/poco/issues/3682, now that I look at the issues more

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/8fdc04d652708fcc44bd81e351a3d9a4a0353766

**Comment by SvenRoederer** [comment]
Sadly dd not make it into [Release 1.12.2](https://github.com/pocoproject/poco/milestone/44)
