### ISSUE TITLE
bindImplLOB zero size (or NULL) HY104 "Invalid precision value"

### ISSUE THREAD

**Issue by ostropik** [pocoproject/poco#3744]
**Describe the bug**
Connection:NetConn: 031088B8
Server:Not applicable
===========================
ODBC Diagnostic record #1:
===========================
SQLSTATE = HY104
Native Error Code = 0
[Microsoft][SQL Server Native Client 11.0]Invalid precision value

**To Reproduce**
- CREATE TABLE Person (Name VARCHAR(30), Address VARCHAR(30), blob IMAGE)
```
void blobStmt()
{
	using namespace  Poco::Data;
	using namespace Poco::Data::Keywords;

	std::string Name("name");
	std::string address("Address");
	//CLOB blob("0123456789", 10);
	CLOB blob;
	auto ses = DbConnector::Get().GetSession();

	int count = 0;
	Statement ins = (ses << "INSERT INTO Person VALUES (?,?,?)", use(Name), use(address), use(blob));
	ins.execute();
	try { 
		ses << "SELECT COUNT(*) FROM Person", into(count), now; 
	}
	catch (...) { 
		std::cout << "Errr" << std::endl; 
	}
}
```

**Expected behavior**
Record with NULL in column 'blob'

**Comment by ostropik** [comment]
I don't know where is the magic, but I found the following:	
Poco is using this approach to allocate environment:
```
	ret = SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &_henv);
	ret = SQLSetEnvAttr(_henv, SQL_ATTR_ODBC_VERSION, (SQLPOINTER)SQL_OV_ODBC3, 0);
```
MS MFC CDatabase::OpenEx()

is using
`ret = SQLAllocEnv(&_henv);`
and issue with empty BLOB not appearing

**Comment by ostropik** [comment]
```
//"Driver={SQL Server Native Client 11.0};Server=127.0.0.1,49922;Database=MyDB;Uid=****;Pwd=****;APP=myApp;"
	SWORD nResult;
	TCHAR szInfo[64]; // "03.80.0000"
	SQLGetInfo(_hdbc, SQL_ODBC_VER, szInfo, sizeof(szInfo), &nResult);
```

**Comment by ostropik** [comment]
IMHO missing important info. How to bind NULL value.

```
	int nDataLen = 0;
	unsigned char * pData = NULL;
	SQLLEN* pLenIn = new SQLLEN;
	*pLenIn = nDataLen;
	int nColSize = 1; // 0 does't work "Invalid precision value", but work with 1. Not doccumented magic)

	ret = SQLBindParameter(
		hStmt,
		colNum,
		SQL_PARAM_INPUT,
		SQL_C_BINARY,
		SQL_LONGVARBINARY,
		nColSize,//ColumnSize
		0,
		(SQLPOINTER)pData,
		0,
		pLenIn);// What must be here for correct flow : SQL_NULL_DATA or pointer to zero ??
```

**Comment by aleks-f** [comment]
Did you try to follow the [Data User Guide](https://docs.pocoproject.org/current/00200-DataUserManual.html), the **Handling NULL entries** chapter in particular?

The approach recommended there seems to work here:

https://github.com/pocoproject/poco/blob/be19dc4a2f30eb97cc9bdd7551460db11cc27353/Data/ODBC/testsuite/src/SQLExecutor.cpp#L3934-L3981

But if there is a bug specific to `LOB`s, we'll look into it.
