### ISSUE TITLE
Poco 1.12.2 - Building DataMySQL still fails (issue #3689)

### ISSUE THREAD

**Issue by FreelancerCGN** [pocoproject/poco#3748]
Poco 1.12.2
Ubuntu 20.04.4 LTS
CMake 3.16.3

Building DataMySQL still fails, issue #3689 
@hmartinez82

```
Scanning dependencies of target DataMySQL
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/Connector.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/Extractor.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/MySQLException.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/MySQLStatementImpl.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/ResultMetadata.cpp.o
/home/poco/poco-1.12.2-all/Data/MySQL/src/ResultMetadata.cpp: In function ‘Poco::Data::MetaColumn::ColumnDataType {anonymous}::fieldType(const MYSQL_FIELD&)’:
/home/poco/poco-1.12.2-all/Data/MySQL/src/ResultMetadata.cpp:136:8: error: ‘MYSQL_TYPE_JSON’ was not declared in this scope; did you mean ‘MYSQL_TYPE_BLOB’?
  136 |   case MYSQL_TYPE_JSON:
      |        ^~~~~~~~~~~~~~~
      |        MYSQL_TYPE_BLOB
make[2]: *** [Data/MySQL/CMakeFiles/DataMySQL.dir/build.make:128: Data/MySQL/CMakeFiles/DataMySQL.dir/src/ResultMetadata.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5259: Data/MySQL/CMakeFiles/DataMySQL.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

```
# cmake --version
cmake version 3.16.3
```

```
# g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

**Comment by hmartinez82** [comment]
What's the version of the mysql sdk that you are using?

**Comment by FreelancerCGN** [comment]
> What's the version of the mysql sdk that you are using?

5.7.x as written here already 26 days ago: https://github.com/pocoproject/poco/issues/3689#issuecomment-1189556224

:-)

**Comment by hmartinez82** [comment]
The X matters. That's the issue.  What's the exact version?

**Comment by FreelancerCGN** [comment]
5.6.51 and 5.7.9

We can't upgrade the system with 5.6.51 due to special reasons.

But here https://github.com/pocoproject/poco/issues/3689#issuecomment-1193939455 another developer uses 5.6

**Comment by hmartinez82** [comment]
Ok. I'll investigate. The fix should've have taken care of 5.6 already, and JSON support was added in 5.7.8 so you should have not have this problem.

**Comment by hmartinez82** [comment]
Ugh. How did I miss this. I missed one line to also surround with #ifdefs! Fixing soon!

**Comment by hmartinez82** [comment]
@FreelancerCGN Just to clarify. Is it only failing to compile with 5.6.51?

**Comment by FreelancerCGN** [comment]
@hmartinez82 As of yesterday Poco 1.12.2 can't be compiled with MySQL 5.6.51 and 5.6.50.

**Comment by hmartinez82** [comment]
@FreelancerCGN but it is working with  5.7.9, correct?

**Comment by FreelancerCGN** [comment]
@hmartinez82 I can't test it with 5.7.9 at the moment, sorry.

**Comment by hmartinez82** [comment]
@FreelancerCGN Sorry I'm unable to test it locally. I don't have access to such older versions of the SDK. I only have access to MySQL 8 and took me hours just to get 5.7.38 to confirm a header support. Can you try with these two lines added to `Data/MySQL/src/ResultMetadata.cpp` ? See https://github.com/pocoproject/poco/pull/3753/files

**Comment by FreelancerCGN** [comment]
@hmartinez82 

ResultMetadata.cpp compiles now without errors

But now MySQLTest.cpp fails:


```
Scanning dependencies of target DataMySQL
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/Connector.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/Extractor.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/MySQLException.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/MySQLStatementImpl.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/ResultMetadata.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/SessionHandle.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/SessionImpl.cpp.o
[ 94%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/StatementExecutor.cpp.o
[ 95%] Building CXX object Data/MySQL/CMakeFiles/DataMySQL.dir/src/Utility.cpp.o
[ 95%] Linking CXX static library ../../lib/libPocoDataMySQLd.a
[ 95%] Built target DataMySQL
Scanning dependencies of target DataMySQL-testrunner
[ 95%] Building CXX object Data/MySQL/testsuite/CMakeFiles/DataMySQL-testrunner.dir/src/Driver.cpp.o
[ 95%] Building CXX object Data/MySQL/testsuite/CMakeFiles/DataMySQL-testrunner.dir/src/MySQLTest.cpp.o
In file included from /home/poco/poco-1.12.2-all/Data/MySQL/testsuite/src/MySQLTest.cpp:12:
/home/poco/poco-1.12.2-all/Data/MySQL/testsuite/src/MySQLTest.cpp: In static member function ‘static CppUnit::Test* MySQLTest::suite()’:
/home/poco/poco-1.12.2-all/Data/MySQL/testsuite/src/MySQLTest.cpp:979:37: error: ‘testJSON’ is not a member of ‘MySQLTest’
  979 |  CppUnit_addTest(pSuite, MySQLTest, testJSON);
      |                                     ^~~~~~~~
/home/poco/poco-1.12.2-all/CppUnit/include/CppUnit/TestCaller.h:92:58: note: in definition of macro ‘CppUnit_addTest’
   92 |  suite->addTest(new CppUnit::TestCaller<cls>(#mth, &cls::mth))
      |                                                          ^~~
make[2]: *** [Data/MySQL/testsuite/CMakeFiles/DataMySQL-testrunner.dir/build.make:76: Data/MySQL/testsuite/CMakeFiles/DataMySQL-testrunner.dir/src/MySQLTest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5289: Data/MySQL/testsuite/CMakeFiles/DataMySQL-testrunner.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by hmartinez82** [comment]
@FreelancerCGN Thanks for helping me out: Two more lines https://github.com/pocoproject/poco/pull/3753/commits/3cb29644838cb095e3a15c9cc4c0d3bab5043e2e

**Comment by FreelancerCGN** [comment]
@hmartinez82 

Thank you for both patches, it works now.

**Comment by zosrothko** [comment]
Hi everybody. I am close to fix the <mysql.h> issue for all build systems (CMake, GNUMake, MSBuild on Linux and Windows) and I am missing the location of this include on MacOS Darwin which is the last to fix from the CI. 

Could someone tell me where are the locations to find out this include?

**Comment by FreelancerCGN** [comment]
> I am close to fix the <mysql.h> issue for all build systems

This would be great, @zosrothko

**Comment by hmartinez82** [comment]
@zosrothko I've never used a Mac in my life, sry :(

**Comment by hmartinez82** [comment]
@zosrothko The fix was already added in https://github.com/pocoproject/poco/pull/3753

**Comment by FreelancerCGN** [comment]
> @zosrothko The fix was already added in #3753

@hmartinez82

He talks about a different issue regarding the "mysql.h" include with wrong paths.

This is still a problem, but I decided to change the generated files "MySQL.h" and "MySQLException.h" with the right path to "mysql.h" instead.

**Comment by hmartinez82** [comment]
@andyhewenhui you need 1.12.3 or apply the two patches above

**Comment by zosrothko** [comment]
Could all of you check that the Data/MySQL compiles without any errors from the branch `devel` from this repo [Kampbell/poco](https://github.com/Kampbell/poco/tree/devel) and let me know the result?

Thanks

**Comment by hmartinez82** [comment]
@zosrothko I can't do it because I don't have access to such old versions of MySQL

**Comment by zosrothko** [comment]
@hmartinez82 Understand your point for the old version of MySQL but, the fix should  or better must work with also the version you have

**Comment by hmartinez82** [comment]
@zosrothko oh, it  has always worked with the versions I have access to  (it's also working on POCO's continuous integration)

**Comment by zosrothko** [comment]
@hmartinez82 @aleks-f @FreelancerCGN This last commit `c023404a03668c179a0ee78a85093153313cb3b8` on the `devel`branch fixes the issue about Data/MySQL (`include <mysql.h> not found`. The real problem is coming from the CLang compiler that is looking for` <mysql.h>` into the system include diretories only when the include is in a ".h" file. When the `#include <mysql.h>` directory is in a *.cpp file, CLang is looking first in the local source directory. Then in Data/MySQL/scr, CLang found `"MySQL.H`" that is the wrong `<mysql.h>` include. 

Look at the errors below
```
In file included from src/Utility.cpp:17:
In file included from include/Poco/Data/MySQL/Utility.h:21:
include/Poco/Data/MySQL/mysql.h:22:10: error: 'mysql.h' file not found with <angled> include; use "quotes" instead
#include <mysql.h>
         ^~~~~~~~~
         "mysql.h"
In file included from src/Utility.cpp:17:
include/Poco/Data/MySQL/Utility.h:23:10: error: 'mysql.h' file not found with <angled> include; use "quotes" instead
#include <mysql.h>
         ^~~~~~~~~
         "mysql.h"
src/Utility.cpp:18:10: fatal error: 'mysql.h' file not found
#include <mysql.h>
         ^~~~~~~~~
3 errors generated.
```

So the fix is consisting in removing all` #include <mysql.h>` from the Data/MySQL/src files and reference the` <mysql.h>` include only in `Data/MySQL/include/Poco/Data/MySQL/MySQL.h`

**Comment by hmartinez82** [comment]
@zosrothko but the issue you are seeing now is unrelated to JSON support for MYSQL, right?

**Comment by zosrothko** [comment]
Yes rigth...That not the proper issue to put a comment. Sorry. I remove it.

**Comment by andyhewenhui** [comment]
> @andyhewenhui you need 1.12.3 or apply the two changes above from https://github.com/pocoproject/poco/pull/3753/files

👌
