### ISSUE TITLE
Poco::Util::Application VxWorks main is incorrect

### ISSUE THREAD

**Issue by spencercoward** [pocoproject/poco#3763]
**Describe the bug**

The POCO_APP_MAIN macro in the Application class resolves to the incorrect version for VxWorks RTPs. The program fails to link, due to the macro using int pocoAppMain(const char* appName, ...) \ version, this is supposed to be used in a kernel context.

**To Reproduce**
Steps to reproduce the behavior. If feasible, please provide a [SSCCE](http://www.sscce.org/) - usually, it will make the process much easier and faster.

In order to reproduce, try to compile a simple Poco::Util::Application as an RTP for VxWorks

**Expected behavior**

The program compiles and links correctly.

**Logs**
If applicable, add logs to help explain your problem.

N/A

**Screenshots**

N/A

**Please add relevant environment information:**
 - OS Type and Version
 - POCO Version
 - Third-party product (eg. database or library) type and version
 
OS: VxWorks 7 Workbench SR660
POCO: Latest

**Additional context**

**Comment by spencercoward** [comment]
https://github.com/pocoproject/poco/blob/be19dc4a2f30eb97cc9bdd7551460db11cc27353/Util/include/Poco/Util/Application.h#L523

**Comment by spencercoward** [comment]
currently to get this to work something like 

#elif defined(POCO_VXWORKS) && !defined(POCO_VXWORKS_RTP)

could solve this issue

**Comment by aleks-f** [comment]
if you ned this fixed, please fix and send a pull, we don't have the development or CI environment readily available

**Comment by spencercoward** [comment]
> if you need this fixed, please fix and send a pull, we don't have the development or CI environment readily available

PR was made.
