### ISSUE TITLE
RegularExpression 1.12.2 match options problem

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3766]
I think something wrong using RegularExpression match with options. At least using RE_NOTEMPTY it throw me a BAD option exeption

**Comment by aleks-f** [comment]
PCRE2 was introduced in 1.12, can you produce a test case demonstrating the problem?

**Comment by micheleselea** [comment]
```
Poco::RegularExpression reTest("(.*[0-9].*[0-9].*[0-9])");
reTest.match("XYZ", 0, mtchInfo, Poco::RegularExpression::RE_NOTEMPTY);
```
