### ISSUE TITLE
Any.h VisualStudio 2022 compiler error

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3768]
the Any.h file cause a "fatal  error C1001: Internal compiler error." when compiling with std:c++ greater than 17

the problem seems to be here
```
template<typename T, typename V,
		typename std::enable_if<TypeSizeGT<T, Placeholder::Size::value>::value>::type* = nullptr>
	PlaceholderT* assign(const V& value)
	{
		erase();
		pHolder = new T(value);
		setLocal(false);
		return pHolder;
	}
```

**Comment by micheleselea** [comment]
And I have a question about line
`new (reinterpret_cast<PlaceholderT*>(holder)) T(value);`
how does that works?

**Comment by aleks-f** [comment]
> to this `static const unsigned int value = SizeV;`
> 
> let me know what you think about

https://github.com/pocoproject/poco/issues/3692

**Comment by aleks-f** [comment]
> And I have a question about line `new (reinterpret_cast<PlaceholderT*>(holder)) T(value);` how does that works?

https://www.cs.technion.ac.il/users/yechiel/c++-faq/placement-new.html
