### ISSUE TITLE
Compilation error under QNX

### ISSUE THREAD

**Issue by yg9326** [pocoproject/poco#3772]
I compiled under QNX, after make -j8 is normal, but make install error, the some  error is as follows：

/opt/qnx/sv-ipu02-qnx-system-sdk/host/linux/x86_64/usr/bin/qcc -V5.4.0,gcc_ntoaarch64le -V5.4.0,gcc_ntoaarch64le  -DPOCO_BUILD_HOST='"'ubuntu'"' -DPOCO_TARGET_OSNAME='"'Linux'"' -DPOCO_TARGET_OSARCH='"'x86_64'"'  -D_QNX_SOURCE  -g -Wl,-rpath,/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/lib/Linux/x86_64 -o /home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/bin/Linux/x86_64/cpspcd /home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/Page.o /home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/PageReader.o /home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/CodeWriter.o /home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/ApacheCodeWriter.o /home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/OSPCodeWriter.o /home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/PageCompiler.o -L/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/lib/Linux/x86_64   -lPocoNetd -lPocoUtild -lPocoXMLd -lPocoJSONd -lPocoFoundationd  -lm -lsocket
/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/Page.o: In function `std::__1::ios_base::ios_base()':
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:333: undefined reference to `vtable for std::__1::ios_base'
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:333: undefined reference to `vtable for std::__1::ios_base'
/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/Page.o: In function `std::__1::basic_ios<char, std::__1::char_traits<char> >::basic_ios()':
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:633: undefined reference to `vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >'
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:633: undefined reference to `vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >'
/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/Page.o: In function `std::__1::basic_ios<char, std::__1::char_traits<char> >::init(std::__1::basic_streambuf<char, std::__1::char_traits<char> >*)':
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:670: undefined reference to `std::__1::ios_base::init(void*)'
/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/Page.o: In function `std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_stringbuf(unsigned int)':
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/sstream:242: undefined reference to `std::__1::basic_streambuf<char, std::__1::char_traits<char> >::basic_streambuf()'
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/sstream:244: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/Page.o: In function `std::__1::ios_base::ios_base()':
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:333: undefined reference to `vtable for std::__1::ios_base'
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:333: undefined reference to `vtable for std::__1::ios_base'
/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/Page.o: In function `std::__1::basic_ios<char, std::__1::char_traits<char> >::basic_ios()':
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:633: undefined reference to `vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >'
/opt/qnx/sv-ipu02-qnx-system-sdk/target/qnx7/usr/include/c++/v1/ios:633: undefined reference to `vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >'
/home/yangg/3rdparty/poco/poco-poco-1.9.4-release/PageCompiler/obj/Linux/x86_64/debug_shared/Page.o: In function `std::__1::basic_ios<char, std::__1::char_traits<char> >::init(std::__1::basic_streambuf<char, std::__1::char_traits<char> >*)':

**Comment by aleks-f** [comment]
You have a very old version of POCO; please upgrade, and if the error persists, send a pull request with a fix (we have no QNC dev environment readily available).
