### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [pocoproject/poco#378]
Some parameters (like "[${CMAKE_BINARY_DIR}/lib](https://github.com/pocoproject/poco/blob/aa0218fa9a290199c7927d85d44b0ff2e86f6766/CMakeLists.txt#L23)" and "[${CMAKE_SOURCE_DIR}/Foundation/src](https://github.com/pocoproject/poco/blob/fefdee93f71178cc375ee7f59be490c04c035554/Foundation/CMakeLists.txt#L210)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like spaces.

I would recommend to apply [advices from a Wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by bachp** [comment]
@obiltschnig Most cases should be covered by now. I would not do a systematic search for potential problems. If problems arise they should be addressed then.
I think we can close this issue.
