### ISSUE TITLE
HTTPServer Applications Slow to Terminate

### ISSUE THREAD

**Issue by sbalousek** [pocoproject/poco#3796]
When an HTTPServer application is sent a termination signal, it takes up to ten seconds for the application to terminate. It's expected that HTTPServer applications will terminate in a more reasonable amount of time.

This test script shows the bug which occurs after two or more requests are made to the HTTPServer:

```
#!/bin/bash
./cmake-build/bin/HTTPFormServer &
sleep 1
curl --noproxy '*' -s http://127.0.0.1:9980 >/dev/null
curl --noproxy '*' -s http://127.0.0.1:9980 >/dev/null

terminated_at="$(date +%s)"
echo "Terminating HTTPFormServer"
pkill HTTPFormServer
wait

terminated_in="$(($(date +%s) - terminated_at))"
echo "HTTPFormServer took ${terminated_in} seconds to terminate"
```

**Comment by vm2mv** [comment]
The problem remains with a separate thread pool and setKeepAlive=true.
When I built the library without POCO_HAVE_FD_EPOLL then the problem is not reproduced.
