### ISSUE TITLE
Poco::Redis reconnect issue

### ISSUE THREAD

**Issue by Jihadist** [pocoproject/poco#3799]
Hello, looks like redis client does not support reconnect. I connect to redis via vpn. If vpn connection will be dropped and reconnected again redis client might be broken.
For example

```c++
Poco::Redis::Client client("127.0.0.1:6379");
if (Redis.isConnected())
{
//// OK
logger().log(Poco::Message("app", "Redis connected", Poco::Message::PRIO_INFORMATION, __FILE__, __LINE__));
}
// here can be some commands
// drop vpn
// reconnect vpn
if (Redis.isConnected())
{
//// still connected (but really not)
logger().log(Poco::Message("app", "Redis connected", Poco::Message::PRIO_INFORMATION, __FILE__, __LINE__));
}
// try to send any another command
catch IOException("No buffer space available", 10054);
```
![изображение](https://user-images.githubusercontent.com/26579016/190587407-e2b186d2-52d7-429c-bbf8-ef3893c6b624.png)

Windows 10 x64 with poco 2b11cb50bf0ff84cd08acf755faac0e4170337a9

**Comment by Jihadist** [comment]
not completed

**Comment by aleks-f** [comment]
@Jihadist Complete it and send a pull and it will be

**Comment by Jihadist** [comment]
> @Jihadist Complete it and send a pull and it will be

I couldn't find any fix
