### ISSUE TITLE
Unresolved overloaded function type when using LogStream operator<<

### ISSUE THREAD

**Issue by stampeed** [pocoproject/poco#3803]
![image](https://user-images.githubusercontent.com/8228132/191099990-1e9715d8-ee25-4b81-bc8e-ced1030b1131.png)

I'm getting an error using LogStream, "error : invalid operands of types ‘&lt;unresolved overloaded function type&gt;’ and ‘const char [46]’ to binary ‘operator&lt;&lt;’"

Any ideas? 

Environment: VStudio 2017 remote Linux project over on Ubuntu 22.04 (with libpoco-dev apt-get pkgs)

**Comment by andrewauclair** [comment]
It looks like `debug` is a member function of the `LogStream` class. This means that you're using/calling it wrong. The right thing would be to use one of the following:

`lstr.debug() << "This is a test log entry using poco logstream" << std::endl;` or
`lstr.debug("This is a test log entry using poco logstream\n");`

Adding your code to the Poco Foundation LogStreamTest.cpp in Visual Studio 2022 (compiling for windows) gives me these errors:

![image](https://user-images.githubusercontent.com/2949516/191864501-3e94ee08-f782-4c2f-ade1-cc223fbce3ed.png)

**Comment by stampeed** [comment]
That was a silly miss on my part. Thank you.
