### ISSUE TITLE
Using std::thread to create a thread, using `%I`, `%T`, `%J` in the log configuration file will not print a valid thread ID in the log.

### ISSUE THREAD

**Issue by baikaishui-ks** [pocoproject/poco#3811]
Using std::thread to create a thread, using `%I`, `%T`, `%J` in the log configuration file will not print a valid thread ID in the log.

I refer to `[class PatternFormatter](https://docs.pocoproject.org/current/Poco.PatternFormatter.html)` configure, configuration matching string goes like this:
`logging.formatters.f1.pattern = %Y-%m-%d %H:%M:%S.%i %q %P-%I %O(%u): %t`
The resulting log style:
`2022-09-22 15:41:32.311 I 1042-0 StatusStatistician.hpp(177): run stat info: all stat {"http.in":0....`
```shell
2022-09-22 16:19:08.153 D 20646---0 Boot.cpp(29): hello, 123123 // %T-%J-%I
2022-09-22 16:20:24.560 D 21493- Boot.cpp(29): hello, 123123 // %T
2022-09-22 16:20:46.922 D 21781- Boot.cpp(29): hello, 123123 // %J
2022-09-22 16:21:10.047 D 22087-0 Boot.cpp(29): hello, 123123 // %I
```
I'm still using the 1.11.3 version of June. I saw an update on Github, so I'll try it out.

**Comment by bas524** [comment]
@baikaishui-ks 
Hi! I've just verify your request and can say, that %J should be work, but %I and %T - never for std::thread, because there are no universal cross-platform solutions for main thread determination or determination that function is in the non-main thread context.
Which OS do you use ?
