### ISSUE TITLE
Security Vulnerability identified in POCO version 1.12.2

### ISSUE THREAD

**Issue by mraninga** [pocoproject/poco#3814]
Hello Developer,
We are using poco latest version 1.12.2. While scanning all binaries and libraries, our cyber security team has reported security risk/vulnerability in zlib and SQLite.
It is humble request to upgrade this libraries and fix these vulnerability. If you have already planned, will you please provide tentative timeline to fix this?

Many thanks!!!

![blackduck_103_release](https://user-images.githubusercontent.com/96813139/192471674-0f84637d-0061-4042-951a-944fcd758e9c.png)

**Comment by obiltschnig** [comment]
Poco 1.12.2 already includes latest zlib 1.2.12, and I am not aware of any SQLite vulnerabilities that need urgent fixing. We will update SQLite in the next regular release.

**Comment by mraninga** [comment]
Thank you very much for your quick response.
Will you also help addressing libexpat vulnerabilities?

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/issues/3805

**Comment by obiltschnig** [comment]
#3847 #3846
