### ISSUE TITLE
Base64Encoder - Segmentation fault

### ISSUE THREAD

**Issue by hanusek** [pocoproject/poco#3820]
Hello.
I have a problem with **Poco::Base64Encoder**.
When i do write to encoder it causes segfault. (`encode << text;`)

```c++
std::string to_base64_string(const std::string text)
{
    try
    {
          std::ostringstream ostr;
          Poco::Base64Encoder encoder(ostr);
          encoder << text; /// segfault.
          encoder.close();
          return ostr.str();
     }
     catch (Poco::Exception& e)
     {
           std::cout << e.message() << std::endl;
     }
     return "";
}
```

**Comment by micheleselea** [comment]
you have to user this
`encoder .write(text.data(),text.length());`
or
```
Poco::MemoryInputStream inText((char*)text.data(), text.length());
Poco::StreamCopier::copyStream(inText, encoder);
```

**Comment by hanusek** [comment]
> you have to use this `encoder .write(text.data(),text.length());` or
> 
> ```
> Poco::MemoryInputStream inText((char*)text.data(), text.length());
> Poco::StreamCopier::copyStream(inText, encoder);
> ```

Thx for your reply.
I tried `encoder.write(text.data(),text.length());` but it's the same, effect  - seg.fault.

**Comment by Fabio3rs** [comment]
I did some tests here with your initial code and it works, maybe it is a version problem when loading the compiled poco libraries/.dll/.so?

If you are using linux can try using ldd NameOfYourProgram to see what libraries are been loading when opening the program.
In Windows I think you can use the program DependencyWalker


```cpp

#include <Poco/Base64Encoder.h>
#include <Poco/Exception.h>
#include <iostream>
#include <sstream>

// I did some changes below to test and it works the same.
std::string to_base64_string(const std::string &text)
{
    try
    {
          std::ostringstream ostr;
          Poco::Base64Encoder encoder(ostr);
          encoder << text;
          encoder.close();
          return ostr.str();
     }
     catch (const Poco::Exception& e)
     {
           std::cout << e.message() << std::endl;
     }
     return "";
}

int main() {

    std::cout << to_base64_string("test") << std::endl;


}

```

Compiled and run:
```
clang++ main.cpp -ggdb -std=c++17 -lPocoFoundation -o pocobase64
./pocobase64
dGVzdA==
```

**Comment by HR1025** [comment]
It doesn't seem like Poco's problem. This looks more like an illegal access to a memory segment.

Could you simplify your code? Only run the code you show, and remove the other not relevant code.

Maybe your stack is affected by something. You can simply add some code like printing (std::cout) at the begining of the `to_base64_string` to modify the memory location, to see there if a different phenomena.

Be care of the C style dangerous operations like memcpy, sometime it will bring you unexpected results.

**Comment by Fabio3rs** [comment]
@micheleselea 
> Anyway I remember had some problems using << operator, but probably was long time ago

If the operator << works like the default behavior of the others std streams, I think it will stop writing at the first blank character it founds. Your advice about using encoder.write makes sense to me. I think should use c_str() to make compatible with a const string `encoder.write(text.c_str(), static_cast<std::streamsize>(text.size()))`

**Comment by micheleselea** [comment]
I think c_str() is useless because you specify the size so you can use data() to direct access the structure it's faster. c_str() gives you a \0 terminated string but you don't need it

**Comment by Fabio3rs** [comment]
@micheleselea 
> I think c_str() is useless because you specify the size so you can use data() to direct access the structure it's faster. c_str() gives you a \0 terminated string but you don't need it

Depends on the implementation, for example in GCC 10 implementation on ubuntu 20.04 c_str() and data() do the same thing, the difference is c_str do not has non-const alternative.
![image](https://user-images.githubusercontent.com/9311162/195601333-d23f63db-a246-4934-be8c-8e789ee5c45a.png)
