### ISSUE TITLE
Possibility of memory leak in Windows Environment nodeIdImpl?

### ISSUE THREAD

**Issue by Fabio3rs** [pocoproject/poco#3823]
https://github.com/pocoproject/poco/blob/1181fb2485292c3735c5fec40f8628f18333490a/Foundation/src/Environment_WINCE.cpp#L170
https://github.com/pocoproject/poco/blob/1181fb2485292c3735c5fec40f8628f18333490a/Foundation/src/Environment_WIN32U.cpp#L219

if GetAdaptersInfo fails in an unexpected way, the method nodeIdImpl will return without deleting the heap buffer allocated with pAdapterInfo = reinterpret_cast<IP_ADAPTER_INFO*>(new char[len]);

Fast fix would be to add something like before the return (WIN32U) and before the exception (WINCE):
```cpp
if (pAdapterInfo != nullptr) {
delete [] reinterpret_cast<char*>(pAdapterInfo);
}
```

Or maybe change the function to use a `std::vector<char>` as buffer, or `Poco::Buffer<char>`. Example with `std::vector<char>`:

Using a RAII container will reduce the chance of a memory leak
```cpp
void EnvironmentImpl::nodeIdImpl(NodeId& id)
{
	std::memset(&id, 0, sizeof(id));

	std::vector<char> buffer;

	PIP_ADAPTER_INFO pAdapter = nullptr;
	ULONG len    = sizeof(IP_ADAPTER_INFO);

	buffer.resize(len);
	PIP_ADAPTER_INFO pAdapterInfo = reinterpret_cast<IP_ADAPTER_INFO*>(buffer.data());
	// Make an initial call to GetAdaptersInfo to get
	// the necessary size into len
	DWORD rc = GetAdaptersInfo(pAdapterInfo, &len);
	if (rc == ERROR_BUFFER_OVERFLOW) 
	{
		buffer.resize(len);
		pAdapterInfo = reinterpret_cast<IP_ADAPTER_INFO*>(buffer.data());
	}
	else if (rc != ERROR_SUCCESS)
	{
		return;
	}
	if (GetAdaptersInfo(pAdapterInfo, &len) == NO_ERROR) 
	{
		pAdapter = pAdapterInfo;
		bool found = false;
		while (pAdapter && !found) 
		{
			if (pAdapter->Type == MIB_IF_TYPE_ETHERNET && pAdapter->AddressLength == sizeof(id))
			{
				found = true;
				std::memcpy(&id, pAdapter->Address, pAdapter->AddressLength);
			}
			pAdapter = pAdapter->Next;
		}
	}
}
```

**Comment by aleks-f** [comment]
@obiltschnig is there a reason why on WinCE the function throws on error, but on WIN32U it silently returns?
