### ISSUE TITLE
VS 2022 Net project missing ARM64 config

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#3825]
@hmartinez82 I thought this was fixed but it still seems to be lingering (devel branch)

![image](https://user-images.githubusercontent.com/2429093/194397924-f2cec46e-0628-4fa3-ab31-ebacb0867c72.png)
```
C:\poco\Net\testsuite\TestSuite_vs170.vcxproj : error  : Cannot load project: project does not contain requested configuration debug_shared|ARM64. Please verify that .sln file is valid and uses only existing project configurations.
```

**Comment by hmartinez82** [comment]
Me too, I wonder if this is just something that we forgot to ProGen. I'll investigate

**Comment by hmartinez82** [comment]
@aleks-f So, this was fixed on Aug 1st, in the devel branch. https://github.com/pocoproject/poco/pull/3724/files#diff-516526c04ffad5b56c7741cbbaedfcc4402e8647edb4b4e175686e310189a2b7R4 . Were you perhaps trying to build the master branch. I don't know if those changes went into the master branch yet
