### ISSUE TITLE
Hardcoded UTF-8 for all applications based on Poco ODBC

### ISSUE THREAD

**Issue by ostropik** [pocoproject/poco#3844]
https://github.com/pocoproject/poco/issues/3396
https://github.com/pocoproject/poco/commit/08d68ea4744c264ebb6ed88ec53c5bc66d7a9f79
So starting from releases
- [poco-1.12.2-release](https://github.com/pocoproject/poco/releases/tag/poco-1.12.2-release) 
- [poco-1.12.1-release](https://github.com/pocoproject/poco/releases/tag/poco-1.12.1-release)
all applications must use UTF-8 strings for Poco::Data::Odbc.
Example of issue: before this change, we self decoded in different threads strings and put it in required for DB collation. Also we did not test singleton TextEncoding::manager() for thread-safety.

**Comment by aleks-f** [comment]
I marked it a s breaking change. It sounds like we did the work you used to do yourself, is there something you are asking us to do about it?
