### ISSUE TITLE
vs2022 win10  log unable to display filename and line number

### ISSUE THREAD

**Issue by luqinlive** [pocoproject/poco#3851]
I am confused about the poco log module. Setting the parameters under Windows does not display the file name and line number, but there is no problem under Linux, the same parameters
code 
`

       Poco::AutoPtr<Poco::PatternFormatter> pattern_formatter(new Poco::PatternFormatter("%L%Y-%m-%d %H:%M:%S  code:%u-%U :%q :%t"));  
       Poco::AutoPtr<Poco::FileChannel> file_channel(new Poco::FileChannel());
        file_channel->setProperty("rotation", "20M");
        file_channel->setProperty("archive", "timestamp");
        file_channel->setProperty("path", "test.log");

        Poco::AutoPtr<Poco::ConsoleChannel> console_channel(new Poco::ConsoleChannel());

        Poco::AutoPtr<Poco::SplitterChannel> splitter_Channel(new Poco::SplitterChannel);
        splitter_Channel->addChannel(file_channel);
        splitter_Channel->addChannel(console_channel);

        Poco::AutoPtr<Poco::FormattingChannel> formattingChannel(new Poco::FormattingChannel(pattern_formatter, splitter_Channel));

        Poco::Logger::root().setChannel(formattingChannel);
         logger_handle.setLevel(Poco::Message::PRIO_TRACE);
        poco_information(logger_handle, "hello world");
        poco_warning(logger_handle, "This is a warning");
        poco_information_f(logger_handle, "An informational message with args: %d, %d", 1, 2);

`

result
2022-10-27 17:54:35  code:0- :I :hello world
2022-10-27 17:54:35  code:0- :W :This is a warning
2022-10-27 17:54:35  code:0- :I :An informational message with args: 1, 2

thanks.

**Comment by KevDi** [comment]
Are you building with MSVC? What flags do you use for the compiler and linker?

**Comment by luqinlive** [comment]
thank you so much, it works
