### ISSUE TITLE
Question about Labeled Gauges

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#3871]
Hello,

if have a short question, in the Comments of the `set` Method in the `Poco::Prometheus::Gauge` class it is mentioned that you should not call `set` on labeled `Gauge`.
So a call like this `mygauge.label({"label"}).set(2.0)` should not be made.
Is there a reason why this should not be done?
I got no error and the labeled values are shown in the Metrics.

**Comment by obiltschnig** [comment]
You can call `mygauge.set(2.0);` on a Gauge (or any other metric) that has labels defined, but that value will not be exported. If a metric has labels defined, only the values defined for the metrics will be exported. If a metric has no labels defined, the "label-less" value (`mygauge.set(2.0)` will be exported.

**Comment by KevDi** [comment]
OK so if I get it right the comment means that I should always call `set` on a labeled gauge via `mygauge.label({"label"}).set(2.0)`? Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Günter Obiltschnig ***@***.***>Datum: Sa., 12. Nov. 2022, 23:13An: pocoproject/poco ***@***.***>Cc: Kevin Dick ***@***.***>, Author ***@***.***>Betreff: Re: [pocoproject/poco] Question about Labeled Gauges (Issue #3871)
You can call mygauge.set(2.0); on a Gauge (or any other metric) that has labels defined, but that value will not be exported. If a metric has labels defined, only the values defined for the metrics will be exported. If a metric has no labels defined, the "label-less" value (mygauge.set(2.0) will be exported.

**Comment by KevDi** [comment]
OK so if I get it right the comment means that I should always call `set` on a labeled gauge via `mygauge.label({"label"}).set(2.0)` and not directly `mygauge.set(2.0)`?

**Comment by obiltschnig** [comment]
Correct
