### ISSUE TITLE
Prometheus Metric as Static Class Member

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#3889]
I have a short question regarding the usage of the Prometheus Metricies. If i add them as a member to a class which is used to run in multiple Threads i always get a issue that the Metric is already existing. 
Are there any concerns to use the Metric as a Static Class Variable?

**Comment by obiltschnig** [comment]
Static initialization order may be an issue.

**Comment by KevDi** [comment]
@obiltschnig if for example the metric is initialized before the registry?

**Comment by obiltschnig** [comment]
Yes, that could happen in theory. 
This can actually be fixed quite easily. Looks like all the singletons still use the workaround for Visual C++ before C++11 where initialization of local statics was not thread safe. If we fix that, at least the initialization order in this case should not be an issue if the `defaultRegistry()` is used.
