### ISSUE TITLE
System Exception when use Poco in Linux Docker with Windows host environment

### ISSUE THREAD

**Issue by bophancong** [pocoproject/poco#3893]
I got an Poco::SystemException issues when try to run the Poco libs (32 bit) in Linux Docker inside the Windows host environment. 

I am using this Poco versions: 1.4.6.

![DRCF_nonXenomai_Linuxdocker](https://user-images.githubusercontent.com/52955171/206400839-47794a94-35cd-42a7-96fb-11232212a747.png)

Thanks in advance

**Comment by andrewauclair** [comment]
Try catching it and calling `message()` to see what the actual error is. Unlike `std::exception`, `Poco::Exception` doesn't give the message in the `what()` function, just the name. `what()` is the same as calling `name()`.

**Comment by bophancong** [comment]
@andrewauclair Thank you very much for your comment. I found that the error happen when I tried to start a thread with priority in Poco lib. 
![poco_thread_i1](https://user-images.githubusercontent.com/52955171/209032373-c953044a-0f42-4499-8000-1f3217fe7e8c.jpg)
The issue happen in the line 274, 275 in image. I have tried to comment this code but it does not work. Do you have any idea of this? I wonder whether it could cause by the Windows OS do not provide the permission for Poco in Linux Docker to start the thread with specific priority.
