### ISSUE TITLE
 Poco::Data::MYSQL SELECT TEXT BUG?

### ISSUE THREAD

**Issue by coolan2013** [pocoproject/poco#3897]
execute follow code，you will counter a assert
 
    *_pSession << "CREATE TABLE IF NOT EXISTS test1( \
		    id BIGINT NOT NULL, \
		    cnt TEXT NOT NULL, \
		    PRIMARY KEY (id));", now;

  std::vector<UInt64> ids1;
  std::vector<std::string> strs1;			
   for (size_t i = 0; i < 500; i++)
  {
    ids1.push_back(i);
    strs1.push_back("{\"7\":1,\"9\":133,\"p\":[{\"c\":\"梁辉细塔\",\"2\":0,\"r\":811}],\"n\":0,\"8\":41,\"o\":1670987322735601}");
  }
 
    *_pSession << "REPLACE INTO test1 VALUES(?,?)", use(ids1), use(strs1), now; 
	
  std::vector<UInt64>  ids2;
  std::vector<std::string>  strs2;
    *_pSession << "SELECT id,cnt FROM test1", into(ids2), into(strs2), now;
	
	
here is the callstack：

  	ntdll.dll!00007ffe9b0391f2()	unknown
 	ntdll.dll!00007ffe9b041622()	unknown
 	ntdll.dll!00007ffe9b04192a()	unknown
 	ntdll.dll!00007ffe9b04a8e9()	unknown
 	ntdll.dll!00007ffe9afe646d()	unknown
 	ntdll.dll!00007ffe9af7fc11()	unknown
>	test.exe!_free_base(void * block) line 105	C++
 	test.exe!free_dbg_nolock(void * const block, const int block_use) line 1003	C++
 	test.exe!_free_dbg(void * block, int block_use) line 1030	C++
 	test.exe!free(void * block) line 32	C++
 	test.exe!Poco::Data::MySQL::ResultMetadata::adjustColumnSizeToFit(unsigned __int64 pos) line 270	C++
 	test.exe!Poco::Data::MySQL::Extractor::extractLongLOB(unsigned __int64 pos) line 291	C++
 	test.exe!Poco::Data::MySQL::Extractor::extract(unsigned __int64 pos, std::string & val) line 141	C++
 	test.exe!Poco::Data::TypeHandler<std::string>::extract(unsigned __int64 pos, std::string & obj, const std::string & defVal, Poco::SharedPtr<Poco::Data::AbstractExtractor,Poco::ReferenceCounter,Poco::ReleasePolicy<Poco::Data::AbstractExtractor>> pExt) line 132	C++
 	test.exe!Poco::Data::Extraction<std::vector<std::string,std::allocator<std::string>>>::extract(unsigned __int64 pos) line 193	C++
 	test.exe!Poco::Data::MySQL::MySQLStatementImpl::next() line 95	C++
 	test.exe!Poco::Data::StatementImpl::executeWithoutLimit() line 170	C++
 	test.exe!Poco::Data::StatementImpl::execute(const bool & reset) line 88	C++
 	test.exe!Poco::Data::Statement::execute(bool reset) line 128	C++
 	test.exe!Poco::Data::Keywords::now(Poco::Data::Statement & statement) line 463	C++
 	test.exe!Poco::Data::Statement::operator,(void(*)(Poco::Data::Statement &) manip) line 207	C++
 	test.exe!SQLExecutor::f_tbTest1_select(std::vector<unsigned __int64,std::allocator<unsigned __int64>> ids, std::vector<std::string,std::allocator<std::string>> & rt) line 195	C++
 	test.exe!test12(SQLExecutor & sqlE) line 184	C++
 	test.exe!test(int argc, wchar_t * * argv) line 194	C++
 	test.exe!wmain(int argc, wchar_t * * argv) line 14	C++

if   
	ALTER TABLE test1 MODIFY cnt VARCHAR(6383);
then
	it's OK!!!

**Comment by wurei** [comment]
We have the same problem, please refer [this](https://github.com/pocoproject/poco/issues/3837#issuecomment-1280938775)
