### ISSUE TITLE
Poco Net test cases gives error if provided with IPv6 address of local host(::1) instead of IPv4 address (127.0.0.1)

### ISSUE THREAD

**Issue by anshul-ux** [pocoproject/poco#3898]
For example i tried changing the address in one of the test case in SocketTest. 

void SocketTest::testAvailable()
{
	EchoServer echoServer;
	StreamSocket ss;
	ss.connect(SocketAddress("::1", echoServer.port()));
	Timespan timeout(1000000);
	ss.sendBytes("hello", 5);
	char buffer[256];
	assertTrue (ss.poll(timeout, Socket::SELECT_READ));
	int av = ss.available();
	assertTrue (av > 0 && av <= 5);
	int n = ss.receiveBytes(buffer, sizeof(buffer));
	assertTrue (n == 5);
	assertTrue (std::string(buffer, n) == "hello");
	ss.close();
}

Here i provided ::1 instead of 127.0.0.1 and this test case failed with the following error 
 1: N7CppUnit10TestCallerI10SocketTestEE.testAvailable
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1

Is there a way to run such test cases with IPv6 address of local host  ?

I am using  version 1.10.1

**Comment by andrewauclair** [comment]
Briefly looking at the tests and socket code I think you're trying to connect to an IPv4 server with an IPv6 address. Which obviously won't work.

`EchoServer echoServer;` is going to use the default constructor of `EchoServer` which sets `_socket` to a default constructed `SocketAddress`. Looking at the default constructor of `SocketAddress`  reveals that it creates a new IPv4 address. You'll have to make sure the servers are listening on an IPv6 address by creating a `SocketAddress` with the right family (IPv6).

Something like:
```cpp
SocketAddress::Family family = SocketAddress::Family::IPv6;
EchoServer echoServer(SocketAddress(family));
StreamSocket ss;
ss.connect(SocketAddress("::1", echoServer.port()));
```

**Comment by anshul-ux** [comment]
I also looked in this test case and yes this logic is correct, a few changes and it works.
But there are many more test cases belonging to different test, One such test case is there in SyslogTest which i am trying to make it work but it fails 

void SyslogTest::testListener()
{
	Poco::AutoPtr<RemoteSyslogChannel> channel = new RemoteSyslogChannel("**[::1]:51400", "loghost", 8, false**);
	channel->setProperty(**"loghost", "[::1]:51400"**);
	channel->open();
	Poco::AutoPtr<RemoteSyslogListener> listener = new RemoteSyslogListener(51400);
	listener->open();
	auto pCL = Poco::makeAuto<CachingChannel>();
	listener->addChannel(pCL);
	assertTrue (pCL->getCurrentSize() == 0);
	Poco::Message msg("asource", "amessage", Poco::Message::PRIO_CRITICAL);
	channel->log(msg);
	Poco::Thread::sleep(1000);
	listener->close();
	channel->close();
	assertTrue (pCL->getCurrentSize() == 1);
	std::vector<Poco::Message> msgs;
	pCL->getMessages(msgs, 0, 10);
	assertTrue (msgs.size() == 1);
	assertTrue (msgs[0].getSource() == "asource");
	assertTrue (msgs[0].getText() == "amessage");
	assertTrue (msgs[0].getPriority() == Poco::Message::PRIO_CRITICAL);
} 

This test case with these changes always fails at **assertTrue (pCL->getCurrentSize() == 1)**. 
I doubt the remotesyslog channel is getting created only for IPv4 and i am not sure how to create a remotesyslog channel for IPv6 family and there is no configuration available to set the family.
