### ISSUE TITLE
Missing sources in release package - buildwin.ps1 and NetSSL_Win

### ISSUE THREAD

**Issue by vitezslav-popovsky-solarwinds** [pocoproject/poco#3913]
Hello, I am trying to build POCO from released package https://pocoproject.org/releases/poco-1.12.4/poco-1.12.4-all.zip, but there are some parts missing compared to github repository branch. Namely https://github.com/pocoproject/poco/blob/poco-1.12.4/buildwin.ps1 or whole https://github.com/pocoproject/poco/tree/poco-1.12.4/NetSSL_Win

Is this intentional that these parts are not included in release packages?

**Comment by aleks-f** [comment]
`NetSSL_Win` is not officially supported and thus not present in the released archive.
`buidwin.ps1` should be included.

**Comment by aleks-f** [comment]
#4460
