### ISSUE TITLE
Http Server File Chunk Upload - File size limitation?

### ISSUE THREAD

**Issue by raxtorDD** [pocoproject/poco#3931]
I am trying to implement a http server with poco intended for big file uploads.. My intention is to receive chunks and later send them chunk by chunk to a different backend.

This sample code is working fine with files around 5mb (stream can be read until the end). When I am trying to upload files bigger than 10mb to this poco http server it fails (stream closes after 2 chunks). Is there a file size limit I don't know about? Can this be set somewhere? 

Also, is it possible to prevent the istream buffer of poco from accepting all data at once? I have to be careful about memory resources and I only want a few kb loaded in the memory. At some issue I read that this might be possible by limiting the istream buffer. Can somebody confirm this?

Thanks already for your help.

```
auto constexpr CHUNK_SIZE{5 * 1024};

void RequestHandler::handleRequest(HTTPServerRequest &req, HTTPServerResponse &resp)
{
  std::cout << "[ RequestHandler ] Got request for URI: " << req.getURI() << std::endl;

  if (req.getChunkedTransferEncoding())
    std::cout << "[ RequestHandler ] request - TransferEncoding: chunked" << std::endl;
  else if (req.getContentLength() != HTTPMessage::UNKNOWN_CONTENT_LENGTH){
    std::cout << "[ RequestHandler ] request - ContentLength: " << req.getContentLength() << std::endl;
  }
  
  auto& stream = req.stream();

  char bodyChunk[CHUNK_SIZE];
  auto contentLength{req.getContentLength()};
  long int contentRead{0};
  while(stream) {
    stream.get(bodyChunk, CHUNK_SIZE);
    contentRead += CHUNK_SIZE;
    std::cout << "[ RequestHandler ] request - Read Chunk Size: " << contentRead << std::endl;
  }

  resp.setStatus(HTTPResponse::HTTP_OK);
  resp.setContentType("text/html");

  std::ostream& out = resp.send();

  out << "Upload successful";

  out.flush();
}
```

**Comment by micheleselea** [comment]
I will change the reply to one of:
```
resp.setChunkedTransferEncoding(true);
  std::ostream& out = resp.send();
  out << "Upload successful";
```
if you do `out << "Upload successful";` you are not telling the client content lenght so you have to use chunked or manually set content lenght
or
`out.sendBuffer("Upload successful", sizeof("Upload successful")-1);`
sendBuffer send the header as well with content length
no need to do  `out.flush();`

There is no limit in upload size, but I think you can use something like that to handle receive

```
std::istream& istr = request.stream();
Poco::FileOutputStream ofs("temp file path", std::ios::out | std::ios::trunc | std::ios::binary);
contentRead = Poco::StreamCopier::copyStream(istr, ofs, CHUNK_SIZE);
```

**Comment by raxtorDD** [comment]
Thanks for your response. So I adjusted the server response to your examples but I am getting the same results as before. A fileupload with 5mb works fine, if I try to upload a file with 10mb this fails.

**Logging with 5mb upload:**
```
[ RequestHandler ] Got request for URI: /upload?api-version=1
[ RequestHandler ] request - ContentLength: 5242880
[ RequestHandler ] request - Read Chunk Size: 5120
[ RequestHandler ] request - Read Chunk Size: 10240
[ RequestHandler ] request - Read Chunk Size: 15360
[ RequestHandler ] request - Read Chunk Size: 20480
....
[ RequestHandler ] request - Read Chunk Size: 5237760
[ RequestHandler ] request - Read Chunk Size: 5242880
[ RequestHandler ] request - Read Chunk Size: 5248000
[ RequestHandler ] request - Read Chunk Size: 5253120
```

**Logging with 10mb upload:**
```
[ RequestHandler ] Got request for URI: /upload?api-version=1
[ RequestHandler ] request - ContentLength: 10485779
[ RequestHandler ] request - Read Chunk Size: 5120
[ RequestHandler ] request - Read Chunk Size: 10240
```

As you can see, the reading of the stream just stops after 2 chunks.

Do you have any idea?

Also, is there a different solution to using a Poco::FileUploadStream? I don't want to write sth into a file. For my purpose I need to buffer a few chunks in the memory.

**Comment by micheleselea** [comment]
You can use the stream you need, for example MemoryOutputStream or directly read data in a prepared std::string
like
```
std::string sData;
sData.resize(CHUNK_SIZE);
Poco::MemoryOutputStream out(sData.data(),sData.length());
contentRead = Poco::StreamCopier::copyStream(istr, ofs, sData.length());
```
or directly
`istr.read(sData.data(),sData.length());`
you can do whatever you need. Anyway I never got problems with that upload call. I can try if I have problem with 10MB but I don't think should be a problem

**Comment by micheleselea** [comment]
did you use stream.get or stream.read?

**Comment by micheleselea** [comment]
Just tried...no problem I can reach

```
...
[ RequestHandler ] request - Read Chunk Size: 10470400
[ RequestHandler ] request - Read Chunk Size: 10475520
[ RequestHandler ] request - Read Chunk Size: 10480640
[ RequestHandler ] request - Read Chunk Size: 10485760
[ RequestHandler ] request - Read Chunk Size: 10490880
```

with this code


```
auto constexpr CHUNK_SIZE{ 5 * 1024 };
TestUploadService::TestUploadService() {
}
TestUploadService::~TestUploadService() {
}
void TestUploadService::handleRequest(Poco::Net::HTTPServerRequest& request, Poco::Net::HTTPServerResponse& response)
{
	std::cout << "[ RequestHandler ] Got request for URI: " << request.getURI() << std::endl;

	if (request.getChunkedTransferEncoding())
		std::cout << "[ RequestHandler ] request - TransferEncoding: chunked" << std::endl;
	else if (request.getContentLength() != Poco::Net::HTTPMessage::UNKNOWN_CONTENT_LENGTH) {
		std::cout << "[ RequestHandler ] request - ContentLength: " << request.getContentLength() << std::endl;
	}

	auto& stream = request.stream();

	char bodyChunk[CHUNK_SIZE];
	auto contentLength{ request.getContentLength() };
	long int contentRead{ 0 };
	while (stream) {
		stream.read(bodyChunk, CHUNK_SIZE);
		contentRead += CHUNK_SIZE;
		std::cout << "[ RequestHandler ] request - Read Chunk Size: " << contentRead << std::endl;
	}

	response.setStatus(Poco::Net::HTTPResponse::HTTP_OK);
	response.setContentType("text/html");
	response.sendBuffer("Upload successful", sizeof("Upload successful") - 1);
}
```

**Comment by raxtorDD** [comment]
@micheleselea Thanks for your help! I got it to work now. Turned out that my 10MB file was corrupt. 

For your example with following

```
std::string sData;
sData.resize(CHUNK_SIZE);
Poco::MemoryOutputStream out(sData.data(),sData.length());
contentRead = Poco::StreamCopier::copyStream(istr, ofs, sData.length());
```
it is good to know that string.data() returns const char* and for Poco MemoryOutPutStream a char* is needed (if anyone is interested in this).
