### ISSUE TITLE
Poco::File exists() issue

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3938]
Hi all, that's I think one of the strangest thing happen in my developer life.
This happened to me on windows 8.1 10 (not on my windows 11)
The point is that if you ask to Poco::File if a file like "C:\ProgramData\nul.whatever" exists...the result is always TRUE even if not!
that's unbelievable I know, so that the code

```
std::string sFileName = "C:\\ProgramData\\nul.whatever";	
try {
	printf("check file1 %s", sFileName.c_str());
	Poco::File fFile(sFileName);
	if (fFile.exists()) {
               //YOU END UP HERE!
		printf("check file2 EXISTS! %s", sFileName.c_str());

		std::string utf8Path = sFileName;
		std::wstring utf16Path;
		{
			Poco::UnicodeConverter::toUTF16(utf8Path, utf16Path);
			if (utf16Path.size() > MAX_PATH - 12) // Note: CreateDirectory has a limit of MAX_PATH - 12 (room for 8.3 file name)
			{
				if (utf16Path[0] == '\\' || utf16Path[1] == ':')
				{
					if (utf16Path.compare(0, 4, L"\\\\?\\", 4) != 0)
					{
						if (utf16Path[1] == '\\')
							utf16Path.insert(0, L"\\\\?\\UNC\\", 8);
						else
							utf16Path.insert(0, L"\\\\?\\", 4);
					}
				}
			}
		}

		{
			DWORD attr = GetFileAttributesW(utf16Path.c_str());
			printf("check file4 attr: %d", attr);
			if (attr == INVALID_FILE_ATTRIBUTES)
			{
				DWORD lasterror = GetLastError();
				printf("check file5 lasterror: %d", lasterror);
			}
		}
	}
	else {
		printf("check file3 NOT EXISTS! %s", sFileName.c_str());
	}
}
catch (Poco::Exception& exc) {
	printf("check file4 err: %s", exc.displayText().c_str());
}
```
you will end up with this output
check file1 C:\ProgramData\nul.whatever
check file2 EXISTS! C:\ProgramData\nul.whatever
check file4 attr: 32

 if you try to `fFile.getLastModified();` an exception is thrown

I think probably is some windows filesystem behavior with nul filename
attr==32 from windows sdk
FILE_ATTRIBUTE_ARCHIVE
32 (0x20)
A file or directory that is an archive file or directory. Applications typically use this attribute to mark files for backup or removal .

**Comment by EXTREMEGABEL** [comment]
NUL is a reserved filenaem under windows and shouldn't be used

https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by micheleselea** [comment]
There is not that filename, is just the string you fill into Poco::File class, but the file is not on disk, anyway the class tells you file exists

**Comment by obiltschnig** [comment]
That's because Windows tells that the file exists. Because, apparently, a file on Windows containing the string NUL at the beginning of the name always exists.

**Comment by micheleselea** [comment]
@obiltschnig ah ah what a S.O. :)

**Comment by aker99** [comment]
@micheleselea, do we need to fix this? Like, return false if a file name is null or nul.extension?
