### ISSUE TITLE
NetSSL_Win: Error during handshake: failed to read data

### ISSUE THREAD

**Issue by Trigve** [pocoproject/poco#3944]
I'm getting the `Error during handshake: failed to read data` while connecting to the SMTP server to send the mail. The code in use:
```
Poco::Net::Context::Ptr p_context(new Poco::Net::Context(Poco::Net::Context::TLS_CLIENT_USE, std::string(), Poco::Net::Context::VERIFY_NONE));
Session.login();
Session.startTLS(p_context);
```
The error occurs in `startTLS()` after some time (cca 20s). The problem is that this happen on some remote computer (to which I cannot connect to debug the issue). When testing on my computer (with same SMTP, etc.) , everything is working OK. The strange thing is, that with Poco 1.9.4 everything works ok on the remote computer.

Poco 1.11.02 compiled as x86 using vcpkg with VS 2019, Windows 10 22H2

I've tried to search the internet about some leads, but no success.

**Comment by Trigve** [comment]
The problem was with NETSSL_WIN. When building the Poco with OpenSSL, then everything works OK.

**Comment by tavi-cacina** [comment]
And can you make it use the installed certificates on the windows machine? That was the reason I went with NetSSL_Win, to avoid maintaining and deliver a ca-file for OpenSSL.

**Comment by Trigve** [comment]
I don't know.
