### ISSUE TITLE
I got this error while compiling  a code running poco framework : the errror is in delegate.h header file 

### ISSUE THREAD

**Issue by yassin-git** [pocoproject/poco#3958]
I got this error while compiling  a code running poco framework : the errror is in delegate.h header file 

/usr/local/include/Poco/Delegate.h:35:23: error: creating pointer to member function of non-class type ‘void’/usr/local/include/Poco/Delegate.h:35:23: error: creating pointer to member function of non-class type ‘void’

**Comment by bas524** [comment]
Are you sure that you compile framework in "clean" system? I mean ... Do you have already installed another version poco in system? If yes than delete previous poco version
