### ISSUE TITLE
Check _ptr != ptr is not enough in AutoPtr.assign

### ISSUE THREAD

**Issue by funny-falcon** [pocoproject/poco#3979]
https://github.com/pocoproject/poco/blob/38380701469d28c4275b5ac192c8f2afc5c9b65d/Foundation/include/Poco/AutoPtr.h#L122-L127

New object could be one referenced by old with it's internal AutoPtr.
If we `release` old pointer before `duplicate` new we could have dangled pointer problem already.

**Comment by aleks-f** [comment]
@funny-falcon how does the dangling pointer happen exactly? the check is whether the assigned-from `AutoPtr` is the same as the assigned-to one. If they are different `AutoPtr`s pointing to the same object, assignment can be skipped because they are both in the desired state already, but there is no harm done - the assigned-to `release()` will not `delete` because assigned-from still keeps the reference count > 0

**Comment by funny-falcon** [comment]
Using poco 1.11.0 from Ubuntu 23.04
```c++
#include <iostream>
#include <string>
#include <Poco/RefCountedObject.h>
#include <Poco/AutoPtr.h>

class RCO : public Poco::RefCountedObject
{
    public:
        RCO(int _i) : i(_i), name("RCO(" + std::to_string(_i) + ")")
        {
            std::cout << name << " constructed\n";
        }

        int i;
        std::string name;
        Poco::AutoPtr<RCO> linked;

        ~RCO()
        {
            std::cout << name << " destructed\n";
            name = "BOOMED " + name;
        }
};

Poco::AutoPtr<RCO>
make_two()
{
    Poco::AutoPtr<RCO> a(new RCO(1));
    a->linked = new RCO(2);
    return a;
}

int
main() {
    Poco::AutoPtr<RCO> a;

    a = make_two();
    std::cout << "will it boom?\n";
    a = a->linked;

    std::cout << "hello " << a->name << "\n";
}
```
Output:
```
~/tmp/poco_issue3979 $ g++ issue3979.cc -lPocoFoundation
~/tmp/poco_issue3979 $ ./a.out 
RCO(1) constructed
RCO(2) constructed
will it boom?
RCO(1) destructed
RCO(2) destructed
hello BOOMED RCO(2)
```

**Comment by funny-falcon** [comment]
Is it desired behaviour?

**Comment by aleks-f** [comment]
> Is it desired behavior?

I'd say, it is not a desirable use - you are assigning a member `AutoPtr` to the owner, which causes the member to be destructed during the assignment. Sadly, we don't provide a shield against shooting yourself in the foot.

You can do this instead and everything will be fine:
```
auto b = a->linked;
a = b;
```
