### ISSUE TITLE
HTTPServerConnection::onServerStopped does not halt poll

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3985]
When you call httpServer->stoppAll(true) we end up in 
HTTPServerConnection::onServerStopped -> with abortConnection true
if the http connection is in keepalive waiting for `socket().poll(_keepAliveTimeout, Socket::SELECT_READ)`
on windows you are waiting for epoll_wait that call GetQueuedCompletionStatusEx
the .close() done in onServerStopped  is not enough to exit without waiting for keepalive timeout occur

**Comment by micheleselea** [comment]
An alternative way to handle that is to do this
https://github.com/piscisaureus/wepoll/pull/20

**Comment by lovelycheep** [comment]
i  had the same problem with version 1.10.1.

Here is the crash stack:

![image](https://github.com/pocoproject/poco/assets/16484182/1c022bec-fbc3-44c2-a5bc-d31f635cf352)

I tried to simulate the stack, but the position was never right.
![image](https://github.com/pocoproject/poco/assets/16484182/675b3ec3-4505-413a-b196-d2bb8814af9e)

Does anyone know how to analyze and solve this problem

**Comment by micheleselea** [comment]
@lovelycheep I think the best solution is to do
https://github.com/piscisaureus/wepoll/pull/20
so cheanging PollSet wakeUp like this
so you can avoid creating _eventfd

```
	void wakeUp()
	{		
#ifdef WEPOLL_H_
		if (_port > 0) {
			StreamSocket ss(SocketAddress("127.0.0.1", _port));
		}
		else if (_epollfd > 0) {
			PostQueuedCompletionStatus(_epollfd, 0, 0, NULL);
		}
#else
		uint64_t val = 1;
		// This is guaranteed to write into a valid fd,
		// or 0 (meaning PollSet is being destroyed).
		// Errors are ignored.
		write(_eventfd, &val, sizeof(val));
#endif
	}
```

**Comment by aleks-f** [comment]
This is likely addressed by [this fix](https://github.com/pocoproject/poco/pull/3797)

But, generally speaking, code that is reproducing the issue is the best way to report and get it fixed - create a test case that fails send a pull.

**Comment by aleks-f** [comment]
> I think that this function `PostQueuedCompletionStatus(_epollfd, 0, 0, NULL);` can work in PollSet too instead using a tcp listening connection

it doesn't
```
testPollSetWakeUp:
Net\testsuite\binA64\TestSuited.exe (process 15108) exited with code -1073741819.
```

**Comment by micheleselea** [comment]
I managed to work the PostQueuedCompletionStatus working, so no problem, I already fix my code, if you think is not the correct way to handle it, never mind

**Comment by vm2mv** [comment]
@aleks-f, are you planning to fix this problem?
I'm forced to use POCO without POCO_HAVE_FD_EPOLL now, but I don't like this option.

**Comment by aleks-f** [comment]
@vm2mv the solution proposed here was segfaulting when I tried it. 

Generally speaking, "here's a fix from my heavily tweaked poco code" is not an efficient way to get the issues fixed. If you have a problem and want it fixed quick, send a pull request to devel branch, let's see if CI goes green with it and then we'll be in a much better place to fix it.

/cc @matejk
