### ISSUE TITLE
Fix dead lock on Timer destructor

### ISSUE THREAD

**Issue by vojinilic** [pocoproject/poco#3986]
Consider following situation. A class owns a timer. In destructor of that class we call .cancel() asynchronous on timer before it's destruction.
Now timer is executing cancel in it's own internal thread, while it's doing that destructor of timer is called from owning class. Timer destructor enqueues stop notification. If that enqueue is happening just after while loop from cancel notification, stop notification is gonna be dropped and timer will never stop.

**Comment by vojinilic** [comment]
Here is the new proposal for the fix.
https://github.com/pocoproject/poco/pull/3999

**Comment by obiltschnig** [comment]
fix needs to be merged into 1.12.5 from devel.

**Comment by vojinilic** [comment]
Added merge to 1.12.5.
please take a look and merge.
