### ISSUE TITLE
Build issues on Apple’s Xcode

### ISSUE THREAD

**Issue by jott4321** [pocoproject/poco#4002]
Need some guidance on nine build issues on Apple’s Xcode. Using Xcode 12.4, no build issues. Upgraded to Xcode 14.2, nine build issues. I believe that all of the issues are related.

Building with Poco 1.10.1 on Xcode 12.4.  No Poco build problems (clang version 1200.0.32.29).
Building with Poco 1.10.1 on Xcode 14.2. Nine Poco build issues (clang version 1400.0.29.202).

The nine issues: 
(a) BasicEvent.h (one error of the following) No template named 'AbstractEvent' found on line: 31 (defining the class ‘BasicEvent’).
(b) FIFOBuffer.h (eight errors of the following) No member named 'notify’ in 'Poco::BasicEvent' found on lines: 421, 422, 431, 523, 458, 525, 528, 530. All of the eight issues are of this type: readable.notify(this, f);, where the “notify” generates the compiler error.

Looking at the latest version of Poco (1.12.4), header files BasicEvent.h is identical to Poco version 1.10.1, and FIFOBuffer.h had two changes that wouldn’t correct the issues: 

Differences between versions 1.10.1 and 1.12.4 of file FIFOBuffer.h:
Poco version: 1.10.1 
if (error && isReadable() && _notify) 
    readable.notify(this, f); 
if (error && isWritable() && _notify) 
    writable.notify(this, f); 

Poco 1.12.4 
if (isReadable() && _notify) 
   readable.notify(this, f); 
if (isWritable() && _notify) 
   writable.notify(this, f);

I don’t know of this is an issue with the later Clang compiler or is it an issue with Poco. As of now, I really don’t want to use the latest Poco libraries unless I actually have to. I really haven’t dug into the build issues very deeply. Before I did that, I wanted to if see anyone has experienced these issues, and what work-arounds there might be. And by the looks of the issues, I’m not sure building with the latest Poco base would help (but I could be incorrect since I didn’t dig in too deeply).

-- Jonathan

**Comment by obiltschnig** [comment]
I'm using POCO on macOS (with Apple's Xcode command-line build tools) regularly (with CMake and GNU Make builds) and have not noticed any issues. Maybe there is some issue with your specific setup? More information needed. Please provide the detailed error messages and more information about your build configuration.

**Comment by jott4321** [comment]
What version of Xcode and CLang are you using?

My GitHub message from me had all of the version information and the error message information. Did you see/read the message from me?

Thanks,

Jonathan Ott
________________________________
