### ISSUE TITLE
Incompatibility with gcc 13.1

### ISSUE THREAD

**Issue by flexborne** [pocoproject/poco#4028]
After the MSYS update, I cannot compile the Poco file because the latest version of GCC has the std::format function, and due to ADL, it is searching for the format function in the std namespace. This is causing an error
You gotta change format->Poco::format in your headers like that:

> template <
> 	typename T,
> 	typename... Args>
> void format(std::string& result, const std::string& fmt, T arg1, Args... args)
> 	/// Appends the formatted string to result.
> {
> 	std::vector<Any> values;
> 	values.reserve(sizeof...(Args) + 1);
> 	values.emplace_back(arg1);
> 	values.insert(values.end(), { args... });
>         Poco::format(result, fmt, values);
> }

The error is below:

> C:/msys64/mingw64/include/Poco/Format.h:112:21: note: candidate function
> void Foundation_API format(std::string& result, const std::string& fmt, const std::vector<Any>& values);
>                     ^
> C:/msys64/mingw64/include/Poco/Format.h:120:6: note: candidate function [with T = std::vector<Poco::Any>, Args = <>]
> void format(std::string& result, const std::string& fmt, T arg1, Args... args)
>      ^
> C:/msys64/mingw64/include/Poco/Format.h:156:2: error: call to 'format' is ambiguous
>         format(result, fmt, values);
>         ^~~~~~
> C:/msys64/mingw64/include/Poco/Format.h:120:6: note: candidate function [with T = std::vector<Poco::Any>, Args = <>]
> void format(std::string& result, const std::string& fmt, T arg1, Args... args)
>      ^
> C:/msys64/mingw64/include/Poco/Format.h:148:13: note: candidate function [with T = std::basic_string<char>, Args = <std::vector<Poco::Any>>]
> std::string format(const std::string& fmt, T arg1, Args... args)
>             ^
> C:/msys64/mingw64/include/c++/13.1.0/format:3713:5: note: candidate function [with _Args = <const std::basic_string<char> &, std::vector<Poco::Any> &>]
>     format(format_string<_Args...> __fmt, _Args&&... __args)
>     ^
> C:/msys64/mingw64/include/Poco/Format.h:112:21: note: candidate function
> void Foundation_API format(std::string& result, const std::string& fmt, const std::vector<Any>& values);
>                     ^
> C:/msys64/mingw64/include/Poco/Format.h:172:2: error: call to 'format' is ambiguous
>         format(result, fmt, values);
>         ^~~~~~
> C:/msys64/mingw64/include/Poco/Format.h:134:6: note: candidate function [with T = std::vector<Poco::Any>, Args = <>]
> void format(std::string& result, const char* fmt, T arg1, Args... args)
>      ^
> C:/msys64/mingw64/include/c++/13.1.0/format:3713:5: note: candidate function [with _Args = <const char *&, std::vector<Poco::Any> &>]
>     format(format_string<_Args...> __fmt, _Args&&... __args)
>     ^
>

**Comment by matejk** [comment]
std::format is enabled with C++20 standard, however GCC 13 enables C++17 by default as it can be seen in documentation.

@flexborne, did you enable C++20 or newer C++ standard perhaps?

**Comment by matejk** [comment]
Aforementioned commits contain changes mentioned in the description and were tested with Apple clang 15.0.0. `-std=c++20` was forced when testing. Compile and unit tests passed. Considering issue as fixed.
