### ISSUE TITLE
Support alternative key derivation function is CipherKey

### ISSUE THREAD

**Issue by bachp** [pocoproject/poco#403]
Currently the CipherKey implementation in `Poco::Crypto` uses the `EVP_BytesToKey` from OpenSSL. [1]

It would also be nice if the `CipherKey` class could use alternative key derivation functions instead of the currently used `EVP_BytesToKey`. The OpenSSL library even suggests using PBKDF2 (implemented in 7175be3) as a replacement [2].

[1] https://github.com/pocoproject/poco/blob/915265f2cb71571116f9a3db4551ce273985ce78/Crypto/src/CipherKeyImpl.cpp#L180

[2] http://www.openssl.org/docs/crypto/EVP_BytesToKey.html#NOTES

**Comment by TroudhuK** [comment]
I'm not sure why this request was closed, as nothing changed about this point.
