### ISSUE TITLE
Classes with virtual functions missing virtual destructors (compilation issues)

### ISSUE THREAD

**Issue by PeterErnsthaft** [pocoproject/poco#4031]
Hi, I have problems building poco (and pocod) when applying strict compiler rules:

The errors I get are as follows:
```
poco/Net/include/Poco/Net/PartStore.h:85:7: error: 'Poco::Net::PartStoreFactory' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
poco/Net/include/Poco/Net/PartStore.h:93:7: error: 'Poco::Net::FilePartStoreFactory' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
```
compiler: clang
target architecture: aarch64 (ARM)
problematic flags: `-Werror,-Wnon-virtual-dtor`
host system: linux

**Is it possible to fix this by adding virtual destructors to those classes?**
https://github.com/pocoproject/poco/blob/1211613642269b7d53bea58b02de7fcd25ece3b9/Net/include/Poco/Net/PartStore.h#L89
**Are there any other classes that might have the same issue?**

Let me know if you need additional info to reproduce

**Comment by micheleselea** [comment]
O think probably PartStoreFactory is just an interface here, so I think virtual keyword can be avoided in the declaration

**Comment by aleks-f** [comment]
> O think probably PartStoreFactory is just an interface here, so I think virtual keyword can be avoided in the declaration

pure virtual function must have `virtual` qualifier

**Comment by micheleselea** [comment]
@aleks-f yes, your're right
