### ISSUE TITLE
Static linking with my application

### ISSUE THREAD

**Issue by ktoyou** [pocoproject/poco#4034]
Hello! I need to build an application and link Poco to it in order to run the application from under the OS on which Poco is not installed. How can I do this? Please tell me, I will be grateful. Linux OS

**Comment by micheleselea** [comment]
You can just compile libraries and than use this line to trun application
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./WhereYouPutPocoLib ./YourApp

**Comment by ktoyou** [comment]
> You can just compile libraries and than use this line to trun application LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./WhereYouPutPocoLib ./YourApp

I tried to build it again with the static Poco libraries, you have much fewer errors, but they are there

/usr/bin/ld: CMakeFiles/ots_grunt.dir/src/utils/Command.cpp.o: in function `Command::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)':
Command.cpp:(.text+0x71): undefined reference to `Poco::Process::launch(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, Poco::Pipe*, Poco::Pipe*, Poco::Pipe*)'
/usr/bin/ld: CMakeFiles/ots_grunt.dir/src/utils/parsers/CpuStatisticsParser.cpp.o: in function `Poco::Thread::sleep(long)':
CpuStatisticsParser.cpp:(.text._ZN4Poco6Thread5sleepEl[_ZN4Poco6Thread5sleepEl]+0x18): undefined reference to `Poco::ThreadImpl::sleepImpl(long)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ots_grunt.dir/build.make:457: ots_grunt] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/ots_grunt.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

[CMakeLists.txt](https://github.com/pocoproject/poco/files/11507601/CMakeLists.txt)

**Comment by peter-kozarec** [comment]
You can just simply add Poco location to your CMAKE_PREFIX_PATH and then add the required package in the CMakeLists.txt file.

Example of CMakeLists.txt: 

```
cmake_minimum_required(VERSION 3.16)

project(link-poco VERSION 1.0.0)

set(CMAKE_PREFIX_PATH /mnt/sda/WorkSpace/poco/cmake-build/Poco)
find_package(Poco REQUIRED Foundation)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE Poco::Foundation)
```

**Comment by ktoyou** [comment]
> 



> You can just simply add Poco location to your CMAKE_PREFIX_PATH and then add the required package in the CMakeLists.txt file.
> 
> Example of CMakeLists.txt:
> 
> ```
> cmake_minimum_required(VERSION 3.16)
> 
> project(link-poco VERSION 1.0.0)
> 
> set(CMAKE_PREFIX_PATH /mnt/sda/WorkSpace/poco/cmake-build/Poco)
> find_package(Poco REQUIRED Foundation)
> 
> add_executable(${PROJECT_NAME} main.cpp)
> target_link_libraries(${PROJECT_NAME} PRIVATE Poco::Foundation)
> ```

Look, I need to distribute the assembled application on Linux. If I want to run it where there is no Poco, it will not find .so files. How can I statically build an application? Add the -static flag to target_link_libraries?

**Comment by peter-kozarec** [comment]
If you build Poco as static libraries the above CMakeLists.txt will link them for you as well. However, if you wish to do it manualy you can just pass the path to the static library in target_link_libraries command.

```
add_executable(${PROJECT_NAME} main.cpp)

target_include_directories(${PROJECT_NAME} PRIVATE
    /mnt/sda/WorkSpace/poco/Util/include
    /mnt/sda/WorkSpace/poco/Prometheus/include
    /mnt/sda/WorkSpace/poco/Crypto/include
    /mnt/sda/WorkSpace/poco/Net/include
    /mnt/sda/WorkSpace/poco/XML/include
    /mnt/sda/WorkSpace/poco/JSON/include
    /mnt/sda/WorkSpace/poco/Foundation/include)

target_link_libraries(${PROJECT_NAME} PRIVATE 
    /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoUtil.a
    /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoPrometheus.a
    /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoCrypto.a
    /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoNet.a
    /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoXML.a
    /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoJSON.a
    /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoFoundation.a)
```

With that you can just build the binary

```
pko@local:/mnt/sda/WorkSpace/link-poco/build$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/sda/WorkSpace/link-poco/build
pko@local:/mnt/sda/WorkSpace/link-poco/build$ make
[ 50%] Linking CXX executable link-poco
[100%] Built target link-poco
pko@local:/mnt/sda/WorkSpace/link-poco/build$ ./link-poco 
<body>
        <0>Hello</0>
</body>
pko@local:/mnt/sda/WorkSpace/link-poco/build$ 
```

**Comment by ktoyou** [comment]
> If you build Poco as static libraries the above CMakeLists.txt will link them for you as well. However, if you wish to do it manualy you can just pass the path to the static library in target_link_libraries command.
> 
> ```
> add_executable(${PROJECT_NAME} main.cpp)
> 
> target_include_directories(${PROJECT_NAME} PRIVATE
>     /mnt/sda/WorkSpace/poco/Util/include
>     /mnt/sda/WorkSpace/poco/Prometheus/include
>     /mnt/sda/WorkSpace/poco/Crypto/include
>     /mnt/sda/WorkSpace/poco/Net/include
>     /mnt/sda/WorkSpace/poco/XML/include
>     /mnt/sda/WorkSpace/poco/JSON/include
>     /mnt/sda/WorkSpace/poco/Foundation/include)
> 
> target_link_libraries(${PROJECT_NAME} PRIVATE 
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoUtil.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoPrometheus.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoCrypto.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoNet.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoXML.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoJSON.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoFoundation.a)
> ```
> 
> With that you can just build the binary
> 
> ```
> pko@local:/mnt/sda/WorkSpace/link-poco/build$ cmake ..
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /mnt/sda/WorkSpace/link-poco/build
> pko@local:/mnt/sda/WorkSpace/link-poco/build$ make
> [ 50%] Linking CXX executable link-poco
> [100%] Built target link-poco
> pko@local:/mnt/sda/WorkSpace/link-poco/build$ ./link-poco 
> <body>
>         <0>Hello</0>
> </body>
> pko@local:/mnt/sda/WorkSpace/link-poco/build$ 
> ```

https://pastebin.com/zrAJz8n2

**Comment by ktoyou** [comment]
> If you build Poco as static libraries the above CMakeLists.txt will link them for you as well. However, if you wish to do it manualy you can just pass the path to the static library in target_link_libraries command.
> 
> ```
> add_executable(${PROJECT_NAME} main.cpp)
> 
> target_include_directories(${PROJECT_NAME} PRIVATE
>     /mnt/sda/WorkSpace/poco/Util/include
>     /mnt/sda/WorkSpace/poco/Prometheus/include
>     /mnt/sda/WorkSpace/poco/Crypto/include
>     /mnt/sda/WorkSpace/poco/Net/include
>     /mnt/sda/WorkSpace/poco/XML/include
>     /mnt/sda/WorkSpace/poco/JSON/include
>     /mnt/sda/WorkSpace/poco/Foundation/include)
> 
> target_link_libraries(${PROJECT_NAME} PRIVATE 
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoUtil.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoPrometheus.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoCrypto.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoNet.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoXML.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoJSON.a
>     /mnt/sda/WorkSpace/poco/cmake-build/lib/libPocoFoundation.a)
> ```
> 
> With that you can just build the binary
> 
> ```
> pko@local:/mnt/sda/WorkSpace/link-poco/build$ cmake ..
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /mnt/sda/WorkSpace/link-poco/build
> pko@local:/mnt/sda/WorkSpace/link-poco/build$ make
> [ 50%] Linking CXX executable link-poco
> [100%] Built target link-poco
> pko@local:/mnt/sda/WorkSpace/link-poco/build$ ./link-poco 
> <body>
>         <0>Hello</0>
> </body>
> pko@local:/mnt/sda/WorkSpace/link-poco/build$ 
> ```

thank you, it turned out to collect!
