### ISSUE TITLE
Poco::XML cannot parse valid xml

### ISSUE THREAD

**Issue by Jihadist** [pocoproject/poco#4044]
Hello, I cannot parse XML file generated by SQL Server Reporting Services with exception "XML processing instruction not at start of external **entity**". What I do wrong? Thanx
```c++
	std::stringstream sstream;
	sstream << R"(
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
	  <GetInfo xmlns="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application">
		 <nodeparentid>32</nodeparentid>
		 <nodegrandparentid>0</nodegrandparentid>
	  </GetInfo>
   </soap:Body>
</soap:Envelope>
)";

	Poco::XML::InputSource src(sstream);
	Poco::AutoPtr<Poco::XML::Document> pDoc = parser.parse(&src);
```

If I use file with the same content, it will be parsed.

Windows 10, msvc 2019, Poco 1.12.0

**Comment by obiltschnig** [comment]
Apparently your XML document starts with a newline. The XML declaration must be on the first line of the XML file.

**Comment by Jihadist** [comment]
Oh, I missed it. Thank you!
