### ISSUE TITLE
pthread_setname_np was not declared in this scope

### ISSUE THREAD

**Issue by navinagaraj** [pocoproject/poco#4063]
While building i am facing the issue i added the with " **-lpthread** " option also but build failed. I added the web page related to small C library for embedded systems is that ok ?

**web page Link:** 
```
https://patchwork.ozlabs.org/project/uclibc-ng/patch/20161110012740.82DFF10162@helium.openadk.org/

```

**platform Info:**

```
Kernel Architecture   -> arm  (Linux)           
Kernel Version        -> 4.19 
gcc                   -> 5.5.0          
uClibc                -> 0.9.33.2 
```

**Error:**

```
In file included from src/Thread.cpp:32:0:
src/Thread_POSIX.cpp: In function 'void {anonymous}::setThreadName(pthread_t, const string&)':
src/Thread_POSIX.cpp:71:51: error: 'pthread_setname_np' was not declared in this scope
  if (pthread_setname_np(thread, threadName.c_str()) == ERANGE && threadName.size() > 15)
```

**Previous issue:** 

#3832 
#4042

**Comment by aleks-f** [comment]
[These functions are nonstandard GNU extensions.](https://linux.die.net/man/3/pthread_getname_np)

**Comment by aleks-f** [comment]
this is [not available](https://stackoverflow.com/a/49456216/205386) on GLIBC<2.12 and also not available on many platforms, so it would probably be best solved by using `prctl(2)` with `PR_SET_NAME`/`PR_GET_NAME`
