### ISSUE TITLE
OpenSSL 3: Don't throw if legacy provider is not available

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#4077]
In 1.11.x and 1.12.x `OpenSSLInitializer::initialize()` will throw a `CryptoException` if the OpenSSL 3 legacy provider cannot be loaded. Since the legacy provider is not available in all environments, and generally is not required by most programs using OpenSSL anyway, failing to load it should not be an error.

Change: try to load the legacy provider, but don't fail if it cannot be loaded. Provide a function `OpenSSLInitializer::haveLegacyProvider()` so that interested programs can check whether the legacy provider is available.

**Comment by obiltschnig** [comment]
Will be fixed in 1.11.7 and 1.12.5.

**Comment by tyler92** [comment]
@obiltschnig Thank you for the fix. Do you have an approximate release date for 1.12.5?

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/milestone/46

**Comment by SAO-kirito-asuna** [comment]
Does Poco1.12.4 support loading of OpenSSL3.0 legacy providers?
