### ISSUE TITLE
unable to make_unique<Poco::Data::SessionPool>

### ISSUE THREAD

**Issue by omerbrandis** [pocoproject/poco#4092]
Hello,

I'm using poco 1.11.0.

I'm unable to compile
`std::unique_ptr<Poco::Data::SessionPool> temp = std::make_unique<Poco::Data::SessionPool>(Poco::Data::SessionPool("PostgreSQL",ConnectionString));
`
i get  error: 
‘Poco::Data::SessionPool::SessionPool(const Poco::Data::SessionPool&)’ is private within this context
     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

as far as i can tell is "private within this context" indicates an attempt to use a private member or a non static one.
while the SessionPool does have a public constructor....

please advise.
:-)

**Comment by andrewauclair** [comment]
Poco::Data::SessionPool can't be copied as is indicated there. Making the copy constructor private is the older way of doing so, new style would use = delete. You want `std::unique_ptr<Poco::Data::SessionPool> temp = std::make_unique<Poco::Data::SessionPool>("PostgreSQL",ConnectionString);`, `std::make_unique` calls the constructor for you.

**Comment by omerbrandis** [comment]
thanks
