### ISSUE TITLE
HttpClientSession does not allow specification of local port address.

### ISSUE THREAD

**Issue by dedvalson** [pocoproject/poco#411]
There is no combination of Constructors or Functions that allow the creation of an HttpClientSession specifying the local address. I tried the following:

<code>
StreamSocket s;                 // create the socket manually
SocketImpl *si = s.impl();  
si->bind (LocalAddress);    // bind it
HTTPClientSession hs (s);  // create the session using the socket
hs.setHost(RemoteServer);  // try to set the remote server - FAILS
hs.setPort(RemotePort);
</code>

The SetHost call fails because it thinks the socket is already connected, even though it isn't really. The Connected() function checks to see if the socket is initialized, not whether or not it is connected. 

I think what is needed is a member function like the following:

<code>
void setLocalHost(
    const std::string & host
);                 // specify the local network interface to use for this connection.
</code>

Probably this should exist at the HttpSession level.

**Comment by roccocorsi** [comment]
@obiltschnig Should this be marked as part of 2.0 since it is solved in #1475 and a few other followup bug fixes.
