### ISSUE TITLE
Initialisation of _socketIndex in SSLManager (OpenSSL)

### ISSUE THREAD

**Issue by sudheerhebbale** [pocoproject/poco#4134]
The class SSLManager (NetSSL_OpenSSL/include/Poco/Net/SSLManager.h) declares a variable _socketIndex, the value of which is used in SecureSocketImpl to store and retrieve application data in SSL*

This is not initialized and can lead to errors.

It should be initialized using the function SSL_get_ex_new_index in the constructor.

**Comment by micheleselea** [comment]
In current version of PocoLib the index is _contextIndex and in constructor
```
SSLManager::SSLManager():
	_contextIndex(SSL_CTX_get_ex_new_index(0, NULL, NULL, NULL, NULL))
{
}
```

so probably you are talking about an old version?

**Comment by sudheerhebbale** [comment]
I am talking about one more member _socketIndex, whose value is referred in SecureSocketImpl.cpp in order to store and retrieve user data in _pSSL (SSL*). This needs to be instantiated properly as well.

While _contextIndex is instantiated and referred in Context.cpp and SSLManager.cpp

**Comment by micheleselea** [comment]
I don't have any _socketIndex in SecureSocketImpl.cpp
I still think you are probably tacking about an old version
I look in source code and could not find that _socketIndex or any other "index" member variable

**Comment by micheleselea** [comment]
Wait I found a strange thing.
If you select from github tag 1.12.4 you see the use of _socketIndex that is not initialized used in acceptSSL
but if you download https://pocoproject.org/releases/poco-1.12.4/poco-1.12.4-all.zip
you cannot find that _socketIndex 
I'm confused...

**Comment by sudheerhebbale** [comment]
I am referring to the master branch on github (https://github.com/pocoproject/poco master branch)

The definition of class member is in SSLManager.h (should be instantiated in SSLManager.cpp in the constructor). Value is referred in SecureSocketImpl.cpp

**Comment by micheleselea** [comment]
Understand but the problem seems to be in the 1.12.4 tag to but not in the zip package that is strange because tag and zip should be the same.
The changes you refer to are on the github branches only not in the release zip (or gzip) package you can find on poco website

**Comment by sudheerhebbale** [comment]
Well that may be one more issue to be fixed
