### ISSUE TITLE
missing \r\n when setting trailer header in chunked response

### ISSUE THREAD

**Issue by SpitchAG** [pocoproject/poco#4147]
version 1.12.X
It seems that when adding trailer headers to a chunked response, message is not ended by the mandatory \r\n.
curl will complain with a 18 error.
(As a workaround add  a "\r\n" at the end of the trailer header value , i.e responseTrailer.set(header_name, header_value+"\r\n").

**Comment by micheleselea** [comment]
I often use custom headers in chunked responses but I never had that problem. I'm trying now with curl and I do not have the warning. Can you put some more code to see how you reply in server and the curl error and version?

**Comment by obiltschnig** [comment]
This affects only "trailing" headers (sent after the chunked content), not "normal" (custom) headers.

**Comment by micheleselea** [comment]
Ah ok, I never use that kind of headers, I though I can't send headers after .send() call, my bad

**Comment by banka50** [comment]
@obiltschnig
This is not a complete fix. In addition, it is also necessary to replace
```HTTPOutputStream hos(_session);``` on line 59 to
```HTTPHeaderOutputStream hos(_session);```. Otherwise HTTPOutputStream will shuts down the sending part of the underlying socket in it's destructor and you will be not able to send "\r\n".
