### ISSUE TITLE
[Bug] `SharedLibraryImpl::loadImpl` uses an incorrect format specifier

### ISSUE THREAD

**Issue by Smurf-IV** [pocoproject/poco#4164]
According to https://www.tutorialspoint.com/c_standard_library/c_function_sprintf.htm

the `length` should be "BEFORE" the `specifier`

in the above function (In the win32 version) the following is formatted

Poco::format(err, "Error **%ul** while loading [%s]: [%s]", errn, path, trimmedError);

and it should be

Poco::format(err, "Error **%lu** while loading [%s]: [%s]", errn, path, trimmedError);

**Comment by obiltschnig** [comment]
Already fixed in `devel` branch.

**Comment by Smurf-IV** [comment]
@obiltschnig You have added the 1.11.8 milestone.
I found this in 1.12.4
What is the difference in this versioning structure ?

**Comment by obiltschnig** [comment]
We currently maintain 1.11.x (next release 1.11.8) and 1.12.x (next release 1.12.4) release branches, in addition to `devel`, which will become 1.13.

**Comment by Smurf-IV** [comment]
Thanks,
Can the above be elaborated on the project page, and to also state the differences between the versions please ?
