### ISSUE TITLE
VS170 binary names mismatch on ARM

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4207]
Some (but not all) VS170 projects generate binaries with `A` inserted into the binary name, which is fine, but it has to be consistent in order to work.

TODO:

- [x] consolidate/unify pdb names (not consistent)
- [x] align `Foundation` and `CppUnit`
- [x] debug testsuites not having `d` appended to the executable name
- [x] `C++17` ~~and `C11`~~ should be made default for VS2022 and 2019:
https://github.com/pocoproject/poco/blob/78234857bf416b718455496800d1b7be3a0d0a53/ProGen/src/ProGen.cpp#L587
- [x] would be good to have the `progen.ps1` PowerShell script to build needed libs and exe using [buildwin.ps1](https://github.com/pocoproject/poco/blob/devel/buildwin.ps1) and start `Progen` with arguments for some or all VS projects generation #4248

**Comment by hmartinez82** [comment]
Regarding `here is name discrepancy between dll, pdb and lib, eg.`
I didn't want to change the Import Library, because I didn't see it being different between Win32 and x64, so for ARM64 I also didn't change it.
Also, I didn't want to have to change this part:
```
	#if defined(POCO_DLL)
		#if defined(_DEBUG)
			#define POCO_LIB_SUFFIX "d.lib"
		#else
			#define POCO_LIB_SUFFIX ".lib"
		#endif
	#elif defined(_DLL)
		#if defined(_DEBUG)
			#define POCO_LIB_SUFFIX "mdd.lib"
		#else
			#define POCO_LIB_SUFFIX "md.lib"
		#endif
	#else
		#if defined(_DEBUG)
			#define POCO_LIB_SUFFIX "mtd.lib"
		#else
			#define POCO_LIB_SUFFIX "mt.lib"
		#endif
	#endif
```

**Comment by aleks-f** [comment]
Ok, I guess we can leave those names like that for consistency, and scratch that item from the list

**Comment by aleks-f** [comment]
@hmartinez82 I did not check other VS versions, not sure if this applies there
and please coordinate with @chrisbednarski, he has some changes [here](https://github.com/pocoproject/poco/pull/4097)

**Comment by aleks-f** [comment]
@hmartinez82 please write a short [ProGen](https://github.com/pocoproject/poco/tree/devel/ProGen) [wiki](https://github.com/pocoproject/poco/wiki) entry.
@pavledragisic has a couple of new source files in this [PR](https://github.com/pocoproject/poco/pull/4225)

**Comment by aleks-f** [comment]
moved [1.13.0](https://github.com/pocoproject/poco/milestone/42) release to 11/6
