### ISSUE TITLE
Replace C string literals (const char*) with C++ std::string literals for std::string parameters.

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#4216]
This should save a lot of std::string constructor calls when passing literal string values to functions expecting std::string.

**Comment by Smurf-IV** [comment]
And / or maybe use `const std::string&` ??

**Comment by aleks-f** [comment]
@obiltschnig put this in `Foundation.h`?
```c++
#include <string>
using namespace std::literals;
```
Should be [ok](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-using-directive)

**Comment by obiltschnig** [comment]
I would never put a `using namespace` declaration in a header. I only put this in .cpp files, or if needed in the header, directly in the function where I need it.

**Comment by obiltschnig** [comment]
Maybe putting the `using namespace std::string_literals;` in the `Poco` namespace may be a better way.

**Comment by obiltschnig** [comment]
Yes

**Comment by obiltschnig** [comment]
Probably a few more places (e.g. in Data) where this could be done, but will close for now.
