### ISSUE TITLE
Poco::Data::PostgreSQL::SessionHandle::disconnect() leaks memory for failed connections

### ISSUE THREAD

**Issue by tadas-smetanin** [pocoproject/poco#4231]
Poco::Data::PostgreSQL::SessionHandle::disconnect() implementation does not free (PQfinish) PGconn*  _pConnection, if the connection has failed:

```
SessionHandle::~SessionHandle()
{
	try
	{
		disconnect();
	}
	catch (...)
	{
	}
}

void SessionHandle::disconnect()
{
	Poco::FastMutex::ScopedLock mutexLocker(_sessionMutex);

	if (isConnectedNoLock())
	{
		PQfinish(_pConnection);

		_pConnection = 0;

		_connectionString = std::string();
		_inTransaction= false;
		_isAutoCommit = true;
		_isAsynchronousCommit = false;
		_tranactionIsolationLevel = Session::TRANSACTION_READ_COMMITTED;
	}
}

bool SessionHandle::isConnectedNoLock() const
{
	// DO NOT ACQUIRE THE MUTEX IN PRIVATE METHODS

	if (_pConnection && PQstatus(_pConnection) == CONNECTION_OK)
	{
		return true;
	}
	return false;
}
```

As stated by libpq [documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQFINISH):

> Note that even if the server connection attempt fails (as indicated by [PQstatus](https://www.postgresql.org/docs/current/libpq-status.html#LIBPQ-PQSTATUS)), the application should call [PQfinish](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQFINISH) to free the memory used by the PGconn object. The PGconn pointer must not be used again after [PQfinish](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQFINISH) has been called.

**Comment by aleks-f** [comment]
@tadas-smetanin can you please send a pull request?

**Comment by frwilckens** [comment]
It think this should be fixed connect(), not in disconnect(): if the connection attempt fails, we should make sure _pConnection is freed and set to 0 before raising an exception.

**Comment by aleks-f** [comment]
@frwilckens that may well be true. The best thing to do is fix the code as you see fit, write a test case creating the situation in question and ensuring it is handled properly, and send a pull request

**Comment by frwilckens** [comment]
@tadas-smetanin I worked in parallel on this issue, see https://github.com/pocoproject/poco/pull/4239/. I had added code to connect(), but you are right that the connection has to be freed if it becomes bad afterwards.  Hence I added code from your commits.  The solution is similar to yours, though I added code to disconnect() instead of the destructor. Please let me know if you think it's still not watertight.

**Comment by tadas-smetanin** [comment]
@frwilckens from my practical tests, your solution does solve the main problem and the memory leak is no longer observed, when the connection fails during periodic database polling.
