### ISSUE TITLE
C++17 and C11

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4235]
Starting with release [1.13.0](https://github.com/pocoproject/poco/milestone/42), C++17 standard will be the lowest fully supported version.

What does that mean for POCO users?

1. it will be possible to build POCO with lower versions, but without some features that require C++17
2. given 1., all the existing user code will continue to work with new versions
3. g++ and clang default will become `-std=c++17`
4. [Visual Studio 2022 default](https://github.com/pocoproject/poco/issues/4207) will become `/std:c++17 /std:c11`; older VS versions will remain as they are

- [x] fix [std::iterator deprecated](https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/) warnings

**Comment by matejk** [comment]
> 4. [Visual Studio 2022 default](https://github.com/pocoproject/poco/issues/4207) will become `/std:c++17 /std:c11`; older VS versions will remain as they are

Visual Studio 2019 also support C++17. Will option `/std:c++17` be enabled for that version of Visual Studio also?

**Comment by aleks-f** [comment]
> > 4. [Visual Studio 2022 default](https://github.com/pocoproject/poco/issues/4207) will become `/std:c++17 /std:c11`; older VS versions will remain as they are
> 
> Visual Studio 2019 also supports C++17. Will option `/std:c++17` be enabled for that version of Visual Studio also?

we can enable it there, too. @pavledragisic is regenerating Vs2022 and we will also have [PS script](https://github.com/pocoproject/poco/pull/4255) to regenerate with one command, so it will be easy
