### ISSUE TITLE
Add ProGen PowerShell script

### ISSUE THREAD

**Issue by pavledragisic** [pocoproject/poco#4248]
Create a `PowerShell` script named `progen.ps1` that automates the execution of `ProGen` for all dependencies listed in the [components](https://github.com/pocoproject/poco/blob/devel/components) file. 
Additionally, this script should provide the flexibility to generate one or multiple user-defined dependencies by accepting command-line arguments.

[Generating VS Projects Using ProGen](https://github.com/pocoproject/poco/wiki/Generating-VS-Projects-using-ProGen)

Script should:
- [x] provide `-components` argument
  - specifies a list of components for which to regenerate the projects
  - this option is the opposite and mutually exclusive with `-omit` (finding both on the command line should be error)
  - this argument should also be added to the `buildwin.ps1`
    https://github.com/pocoproject/poco/blob/10ad89594a9122c8a449ac5694bf4f502b74fe0b/buildwin.ps1#L263
- [x] provide `-build` (default true) optional argument to internally build `static_mt` Foundation, XML, JSON, Util and Progen
- [x] add special cases handling:
  - [x] `Data/testsuite/DataTest`
    this one is one level deeper than the normal project/testuite hierarchy, it should be added as a special case in the script logic (ie. adding it to the `components` config file would probably work, but that's not the way to do it)
- [x] generate projects as specified (progen can run without `/tool` argument specified, in which case it generates all suported versions)

**Comment by aleks-f** [comment]
> > * [ ]   provide `-build` (default true) optional argument to internally build `static_mt` Foundation, XML, JSON, Util and Progen
> 
> Could you please explain this part, should the `buildwin.ps1` script be called if the `-build` argument is set to true?

yes, that is probably the best way to do it - modify `buildwin.ps1` to accept `-build` argument and the call it from progen script before generating projects

**Comment by aleks-f** [comment]
sorry, I meant add `-components` argument, not `-build` (that one already exists and means something else)
