### ISSUE TITLE
Feature request: add class Poco::WeakPtr

### ISSUE THREAD

**Issue by mkrivos** [pocoproject/poco#428]
In addition to Poco::SharedPtr add Poco::WeakPtr class (inspired by std::shared_ptr/std::weak_ptr) for circular dependent objects. 

Any idea?

**Comment by RobertAcksel** [comment]
Are there really no plans to implement it for Poco 1.x.x. 
Some of us can not use the ISO C++11 (even though we would like to) for example when we ship source code which has to be ISO C++03 complaint.

A Weak_Ptr is also not only for resolving circular dependencies. 
Is is also usefull when you have to track the state of a pointer but dont want keep the pointer alive and can also not rely on a poroper event which tells when the pointer is out of scope. 
Than a Weak_Ptr can do the trick.

**Comment by obiltschnig** [comment]
I understand your point, but given the constantly limited resources, and the fact that we're way behind in our plans to "modernize" POCO for C++11 (not even mentioning C++14) I see no value in trying to duplicate C++11 features at this point in time. If you absolutely need this feature, maybe re-implementing Poco::SharedPtr in terms of boost::shared_ptr may be an option. Kind of similar what we plan with std::shared_ptr.
