### ISSUE TITLE
Environment::nodeId Should Throw SystemException When Node ID is 0

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4328]
### Discussed in https://github.com/pocoproject/poco/discussions/4326

<div type='discussions-op-text'>

<sup>Originally posted by **andrewauclair** December  7, 2023</sup>
We've had a few issues with this recently. If the Environment_UNIX.cpp EnvironmentImpl::nodeIdImpl fails to find a node ID it simply leaves the node ID as all 0's. A similar thing appears to happen on Windows. We then assume that this is a valid ID and use it. Some parts of our system end up getting 0's and other parts get a valid node ID and fail to communicate.

I think that this would work better if a SystemException was thrown when nodeIdImpl fails to set a value.</div>

**Comment by aleks-f** [comment]
> I think that this would work better if a SystemException was thrown when nodeIdImpl fails to set a value.

That's actually what the documentation says, but it should throw if it can not produce `nodeId` for an reason.

@andrewauclair please create a PR, and @matejk and myself will review

**Comment by obiltschnig** [comment]
`EnvironmentImpl::nodeIdImpl()` should be changed to also look for WiFi adapters if no Ethernet adapter was found.
