### ISSUE TITLE
`Session::open()` has no timeout parameter

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4366]

**Comment by matejk** [comment]
SQLite session implementation uses login timeout, but ODBC session implementation does not.

@aleks-f, Is it sufficient to implement timeout for ODBC in the way that is implemented for SQLite?

**Comment by aleks-f** [comment]
this issue doesn't really make sense; open could have a login timeout parameter, but it requires changing all the backends and it doesn't really make sense because Session constructor takes login timeout as parameter, which is then reused later. the issue was really with opening ODBC connection where timeouts are obtained from the API
