### ISSUE TITLE
Can we silence NoCertificateException in NetSSL_Win Net::Context::certificate when mustFindCertificate is false?

### ISSUE THREAD

**Issue by mzeilfelder** [pocoproject/poco#4370]
Only place I see Net::Context::certificate() called is in SecureSocketImpl::loadCertificate which has a mustFindCertificate parameter. Net::Context::certificate() doesn't know about that parameter so far, so it always throws an exception in the following code which is then ignored again in loadCertificate:
``
	if (_certNameOrPath.empty())
		throw NoCertificateException("Certificate requested, but no certificate name or path provided");
``
The problem is that despite being ignored later it prints out those exceptions on the console and I'm getting quite a few of those.

If we would pass on mustFindCertificate to Net::Context::certificate() it could ignore that check and directly do an empty throw. Or maybe you have some way to silence an exception. Or return some invalid X509Certificate. Anything which silences this would be nice.

**Comment by matejk** [comment]
@mzeilfelder, would it be possible for you to provide the solution and create a pull request that we can review?

**Comment by mzeilfelder** [comment]
I'll try
