### ISSUE TITLE
UUID parser silently ignores too long strings

### ISSUE THREAD

**Issue by omerbrandis** [pocoproject/poco#4375]
Hello,

I've found a previous [issue](https://github.com/pocoproject/poco/issues/878) that may be similar, only it is marked as fixed in 2015, and i'm using a recent version (Release 1.12.3 )
and the error seems similar.

std::string Str = "495cff3a-a4b3-11ee-9e54-9cb6d0f68b51**AA**";
poco::UUID myUUID.tryParse(Str)

myUUID.toString() != Str.
the last AA are truncated/missing in myUUID.

please advise.
Omer.

**Comment by bas524** [comment]
Hi, @omerbrandis. Your string contains 38 symbols include 4*```-```, but correct uuid should contain only 36 include 4*```-```

**Comment by omerbrandis** [comment]
Hello @bas524,

this is the documentation for "tryParse" as taken from the header file:
/// Tries to interpret the given string as an UUID.
/// If the UUID is syntactically valid, assigns the
/// members and returns true. Otherwise leaves the
/// object unchanged and returns false.

my expectation is that if the input to tryParse is invalid for whatever reason, including if the string is too long and/or contains invalid characters, tryPasre will return false, as described in the documentation, but does not occur.
:-)

**Comment by bas524** [comment]
@matejk , @aleks-f 
Please look at https://github.com/pocoproject/poco/pull/4389/
I hope it can be useful

**Comment by bas524** [comment]
> IMO it is not necessary to make parsing of the UUID less strict as it is currently. Trimming of the string can be done before parsing by the caller.

Ok, I agree
