### ISSUE TITLE
iOS ARM64 : Invalid access: Can not convert empty value.

### ISSUE THREAD

**Issue by mbhaskar98** [pocoproject/poco#4393]
**Describe the bug**
This bug is similar to this - https://github.com/pocoproject/poco/issues/3331 but on iOS. Exact same config is failing. 

Exact same code snippet and same except as provided in the description of the above bug.
Only in Release mode
-fvisibility=hidden compiler flags
ENABLE_TESTABILITY set to NO

**To Reproduce**
NA

**Expected behavior**
Json parsing should succeed.

**Logs**
NA

**Screenshots**
NA

**Please add relevant environment information:**
 - iOS-16 
 - POCO Version - 1.11.7

**Comment by matejk** [comment]
@mbhaskar98, can you please test with version 1.13 and provide a simple code example that demonstrates the problem.

**Comment by mbhaskar98** [comment]
<img width="713" alt="image" src="https://github.com/pocoproject/poco/assets/46974232/d9a61784-4128-42a3-9bfa-fc3b20883097">

Poco 1.13.0 not able to get it working. 
There are multiple files which are throwing this similar error (related to std namespace not found) .

Second type of error 
<img width="711" alt="image" src="https://github.com/pocoproject/poco/assets/46974232/f800e4c3-04d0-46e0-929d-e48a6ebe5484">
 

Based on release notes made sure to keep C++ version gnu++17 and C gnu11

**Comment by mbhaskar98** [comment]
Basic example

https://github.com/mbhaskar98/poco-issue.git

In case you want to rebuild poco, 
```
open terminal
cd to <project_root>/library-testing/poco_1_13
./buildPoco.sh
```

**Comment by matejk** [comment]
I managed to reproduce the problem on macOS also by modifying CMakeLists.txt (#3331).

**Comment by mbhaskar98** [comment]
@matejk could you please provide list of classes that would require `*_API directives` changes so that we could make the same changes in our Poco code for the time being as updating to 1.13 would be a big task at this point.

**Comment by matejk** [comment]
I am working on it.

**Comment by mbhaskar98** [comment]
Found something which is atleast causing issues with 1.11.7. 

Here json value is set 

`void ParserImpl::handle()
{
	enum json_type type = json_next(_pJSON);
	switch (type)
	{
	case JSON_DONE:
		return;
	case JSON_NULL:
		_pHandler->null();
		break;
	case JSON_TRUE:
		if (_pHandler) _pHandler->value(true);
		break;
	case JSON_FALSE:
		if (_pHandler) _pHandler->value(false);
		break;
	case JSON_NUMBER:
		if (_pHandler)
		{
			std::string str(json_get_string(_pJSON, NULL));
			if (str.find(_decimalPoint) != str.npos || str.find('e') != str.npos || str.find('E') != str.npos)
			{
				_pHandler->value(NumberParser::parseFloat(str));
			}
			else
			{
				Poco::Int64 val;
				if (NumberParser::tryParse64(str, val))
					_pHandler->value(val);
				else
					_pHandler->value(NumberParser::parseUnsigned64(str));
			}
		}
		break;
	case JSON_STRING:
		if (_pHandler)
		{
			std::size_t length = 0;
			const char* val = json_get_string(_pJSON, &length);
			_pHandler->value(std::string(val, length == 0 ? 0 : length - 1)); // Decrease the length by 1 because it also contains the terminating null character
		}
		break;
	case JSON_OBJECT:
		if (_pHandler) _pHandler->startObject();
		handleObject();
		break;
	case JSON_OBJECT_END:
		if (_pHandler) _pHandler->endObject();
		return;
	case JSON_ARRAY:
		if (_pHandler) _pHandler->startArray();
		handleArray();
		break;
	case JSON_ARRAY_END:
		if (_pHandler) _pHandler->endArray();
		return;
	case JSON_ERROR:
		{
			const char* pErr = json_get_error(_pJSON);
			std::string err(pErr ? pErr : "JSON parser error.");
			throw JSONException(err);
		}
	}
}`

The flow goes inside "case JSON_STRING:" and then "_pHandler->value(". 


The flow comes here
`void ParseHandler::setValue(const Var& value)
{
	if (_stack.size())
	{
		Var parent = _stack.top();

		if (parent.type() == typeid(Array::Ptr))
		{
			Array::Ptr arr = parent.extract<Array::Ptr>();
			arr->add(value);
		}
		else if (parent.type() == typeid(Object::Ptr))
		{
			Object::Ptr obj = parent.extract<Object::Ptr>();
			obj->set(_key, value);
			_key.clear();
		}
	}
	else throw JSONException("Attempt to set value on an empty stack");
}`

Now none of the inner if condition is passing here.  


If code is changed slightly to this - 
`std::string parentName = parent.type().name();
		std::string arrayPtrName = typeid(Array::Ptr).name();
		std::string objPtrName = typeid(Object::Ptr).name();
		if (parentName == arrayPtrName)
		{
			Array::Ptr arr = parent.extract<Array::Ptr>();
			arr->add(value);
		}
		else if (parentName == objPtrName)
		{
			Object::Ptr obj = parent.extract<Object::Ptr>();
			obj->set(_key, value, "ParseHandler::setValue");
			_key.clear();
		}`
		
		
Then this condition is true "parentName == objPtrName". This is similar to this - https://github.com/pocoproject/poco/issues/3331#issuecomment-1738320715. 

As nothing is getting saved in the map hence the while extracting issue is seen. 


Digging in the std library, the type_info object comparison is something like this. 

`class _LIBCPP_EXCEPTION_ABI _LIBCPP_TYPE_INFO_VTABLE_POINTER_AUTH type_info
{
  type_info& operator=(const type_info&);
  type_info(const type_info&);

 protected:
    typedef __type_info_implementations::__impl __impl;

    __impl::__type_name_t __type_name;

    _LIBCPP_INLINE_VISIBILITY
    explicit type_info(const char* __n)
      : __type_name(__impl::__string_to_type_name(__n)) {}

public:
    _LIBCPP_AVAILABILITY_TYPEINFO_VTABLE
    virtual ~type_info();

    _LIBCPP_INLINE_VISIBILITY
    const char* name() const _NOEXCEPT
    {
      return __impl::__type_name_to_string(__type_name);
    }

    _LIBCPP_INLINE_VISIBILITY
    bool before(const type_info& __arg) const _NOEXCEPT
    {
      return __impl::__lt(__type_name, __arg.__type_name);
    }

    _LIBCPP_INLINE_VISIBILITY
    size_t hash_code() const _NOEXCEPT
    {
      return __impl::__hash(__type_name);
    }

    _LIBCPP_INLINE_VISIBILITY
    bool operator==(const type_info& __arg) const _NOEXCEPT
    {
      return __impl::__eq(__type_name, __arg.__type_name);
    }

#if _LIBCPP_STD_VER <= 17
    _LIBCPP_INLINE_VISIBILITY
    bool operator!=(const type_info& __arg) const _NOEXCEPT
    { return !operator==(__arg); }
#endif
};
#endif // defined(_LIBCPP_ABI_MICROSOFT)` 

Maybe char* is pointing to different address and with std::string comparison is between 2 plain strings instead of char*

**Comment by matejk** [comment]
@mbhaskar98 , is it possible for you to not use the compiler flags "-fvisibility=hidden"?

Making Poco to work properly with this flag set requires more work as it seemed at first.

**Comment by mbhaskar98** [comment]
1. @matejk we are developing an iOS framework that will be used by our customers. It will contains our internal code. Without this flag all the symbols are present in the final binary that is created. That is why want to use this flag. 

2. Also do you know why these comparisons are working correctly for x86_64 but failing for arm64 with visibility compiler flags? 
`
if (parent.type() == typeid(Array::Ptr))
	{
		Array::Ptr arr = parent.extract<Array::Ptr>();
		arr->add(value);
	}
	else if (parent.type() == typeid(Object::Ptr))
	{
		Object::Ptr obj = parent.extract<Object::Ptr>();
		obj->set(_key, value);
		_key.clear();
}
`

And if we change comparison to  string(*.name()) then everything works fine? 

3. And what are the nature of changes from Poco to make this flag work? Is it something related to Poco code side changes or some change in build process? Or does it look like some issue with Apple's c++ std library?

**Comment by matejk** [comment]
@mbhaskar98 , please see MR #4394 for a fix for version 1.13.

Code from that MR compiles fine for iPhone using the configure and make commands that you used (Apple clang version 15.0.0).

**Comment by mbhaskar98** [comment]
@matejk ok these changes are working now. 

Could you please explain in brief why this was working for x86_64 and not for arm64 arch ?

**Comment by matejk** [comment]
I don't know. It shouldn't work on  x86_64 either.
