### ISSUE TITLE
`Dynamic::Var` silently loses precision on int->float conversion

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4423]
**Description**
As stated - on integral to floating point conversion, loss of precision is suppressed and ignored.

**To Reproduce**
Assign an `int` value occupying more than 23 bits (on most platforms) to a `float`.

**Expected behavior**
Precision loss should be  allowed (as is in the language type system). However, it should be possible to enforce strict no-precision-loss policy for integral to floating point conversions.

**Comment by andrewauclair** [comment]
Should Poco consider migrating to `std::any` now that C++17 is supported?

**Comment by aleks-f** [comment]
> Should Poco consider migrating to `std::any` now that C++17 is supported?

`Poco::Any` and `std::any` originate from the same source - Kevlin Henney's `boost::any`. I have no cycles to replace it, and I'm not sure it is worth the effort, either.
