### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4426]
All deprecated code should be removed.

List of deprecated items:

Data:
- SQLParser::parseSQLString
- RecordSet::totalRowCount
- SQLChannel::PROP_ASYNC

Foundation:
- AbstractObserver::accepts(Notification* pNf, const char* pName)
- DirectorySeparator::operator++ (postfix operator)
- Dynamic::Var::empty
- DynamicAny
- Event::Event(bool autoReset)
- FIFOEvent
- FIFOStrategy
- HashFunction
- HashStatistic
- HashTable
- NObserver::accepts(Notification* pNf, const char* pName)
- NumericString::uIntToStr
- Observer::accepts(Notification* pNf, const char* pName)
- SimpleHashTable

Net:
- HTTPResponse::HTTP_USEPROXY
- HTTPResponse::HTTP_REQUESTENTITYTOOLARGE
- HTTPResponse::HTTP_REQUESTURITOOLONG
- HTTPResponse::HTTP_UNSUPPORTEDMEDIATYPE
- NetworkInterface::NetworkInterfaceList
- Socket::select

Applications can define `POCO_SILENCE_DEPRECATED` to disable Poco deprecation warnings if needed.

**Comment by obiltschnig** [comment]
Maybe, as a first step, change everything marked `//@ deprecated` to `[[deprecated]]` so that everyone has a chance to fix their code.

**Comment by andrewauclair** [comment]
Can the title of this issue be updated? In its current state it is confusing and implies that code was actually removed, when it doesn't look like any was. At least the functions I'm concerned with.

**Comment by matejk** [comment]
As you can see in the comments, some code will be removed eventually, it was marked as deprecated in release 1.14 to give a chance to update the code using it.
