### ISSUE TITLE
Error between Poco::ActiveRecord and Poco::Data::PostgreSQL

### ISSUE THREAD

**Issue by SystemDataModel** [pocoproject/poco#4450]
**Describe the bug**
I use Poco ActiveRecord with PostgreSQL 16.

I use ActiveRecord::lastInsertID(Poco::Data::Session& session) where Data::Session is a PostgreSQL Session.

In Data::Session, session.connector() returns "postgresql"

This method is used in ActiveRecord::lastInsertID and test with "if (session.connector() == "PostgreSQL")". This condition is not satisfied.

**To Reproduce**

m_pSession = Poco::SharedPtr<Poco::Data::Session>(new Session(PostgreSQL::Connector::KEY, dbConnString));
Context::Ptr pContext = new Context(*m_pSession);

Use this context with ActiveRecord

**Expected behavior**

Change test "if (session.connector() == "PostgreSQL")" by "if (session.connector() == "postgresql")" in ActiveRecord::lastInsertID

**Logs**
No Logs

**Screenshots**
No screenshots

**Please add relevant environment information:**
 - OS Type and Version : Oracle Linux 9.3
 - POCO Version : Last version from git repo
 - Third-party product (eg. database or library) type and version: PosrtgreSQL 16

**Additional context**
I use Postgres tables with INHERITANCE relationship  between tables.
I use "bigserial" id as primary key in tables

**Comment by obiltschnig** [comment]
The comparison should be case insensitive, as connector names are case insensitive as well (see SessionFactory). The canonical name is "postgresql".

**Comment by SystemDataModel** [comment]
Another improvement

In Postgres, the name of the sequence is autogenerated and is always tablename_columnname_seq.

So, the code below generates an exception:
		session
			<< "SELECT currval('id_seq')",
			into(id),
			now;

Everything works for me with the following fixes:
	else if (session.connector() == "postgresql")
	{
		session
			<< "SELECT lastval()",
			into(id),
			now;
	}

Sincerely yours
