### ISSUE TITLE
ProcessRunner does not detect launch errors

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4482]
**Describe the bug**
Launch thread silently ignores any errors or exceptions.

**To Reproduce**
Launch a non-existing executable.

EDIt: there seems to be no reliable portable way to detect what exactly happens with the launched process (not even when the executable does not exist). Seems best to add the executable file existence check which includes `cwd` and environment path, and not even try to launch a non-existent executable.

**Comment by matejk** [comment]
Fixed in #4483
