### ISSUE TITLE
Optional and Nullable Improvements

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4502]
- `Optional` in terms of `std::optional`
- `Nullable` should be implemented in terms of `std::unique_ptr<T>`
- `NullType` should be `nullptr_t` (or at least a `static const`)
- tests

**Comment by obiltschnig** [comment]
One point of Poco::Nullable and Poco::Optional was to avoid heap allocations, so Poco::Nullable should be implemented with std::optional as well.
