### ISSUE TITLE
SQLChannel stops logging on LoggingSubsystem shutdown

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4529]
**Describe the bug**
- [x] last log messages not logged on shutdown
- [x] code after main while loop in run is never reached (thread abruptly terminated?)
- [x] feature: add `store-and-forward` mode

**Comment by matejk** [comment]
I get this static analysis warning in SQLChannel dtor:

```
/poco/Data/src/SQLChannel.cpp:112:3: Call to virtual method 'SQLChannel::close' during destruction bypasses virtual dispatch [clang-analyzer-optin.cplusplus.VirtualCall]
```
