### ISSUE TITLE
Serializable Isolation level for SQLite Databases

### ISSUE THREAD

**Issue by ClaudeTO80** [pocoproject/poco#4536]
Hi all.

I am working on a personal project using DB connection both to _SQLite_ and _PostgreSQL_. Due to nature of some insert statements, serializable transactions are required. 

As far as I understood by reading Poco source code, _PostgreSQL_ session implementation handles all kinds of transactions, while _SQLite_ session implementation handles only _Read committed_ one.
Moreover I read SQLite project documentation and it seems (if I didn't misunderstood) that _SQLite_ handles serializable transactions if proper compile-time and run-time options are used.

I was wondering:
1.  if limitations to SQLite transactions in Poco library are due to historical or security reasons
2. should it be possible handling all types of transactions in SQLite session implementation?

Thanks in advance.
Best things.

**Comment by aleks-f** [comment]
As far as i remember, the reason for weaker transaction support in SQLite is because nobody so far had a need for those. I see no reason why it shouldn't be supported, but i can't promise when that would be done; you can do the work yourself and send pul request.

**Comment by ClaudeTO80** [comment]
@bas524 Thanks a lot for your reply and support. Close the issue.
