### ISSUE TITLE
MacOS ARM64 build warning: 'OS_CODE' macro redefined

### ISSUE THREAD

**Issue by JackyWoo** [pocoproject/poco#4585]
**Describe the bug**

Env: MacOS 14.4.1 ARM64 clang 18

Build project with cmake.

```
In file included from /Users/wujianchao5/project/jd/poco/Foundation/src/adler32.c:8:
/Users/wujianchao5/project/jd/poco/Foundation/src/zutil.h:170:11: warning: 'OS_CODE' macro redefined [-Wmacro-redefined]
  170 | #  define OS_CODE 19
      |           ^
/Users/wujianchao5/project/jd/poco/Foundation/src/zutil.h:141:11: note: previous definition is here
  141 | #  define OS_CODE  7
      |           ^
1 warning generated.
```

**Comment by andrewauclair** [comment]
`zutil.h` is part of `zlib` which is a 3rd Party library Poco uses. Looks like this code has changed slightly in the latest code, maybe it doesn't cause the issue. Line 40 changed from `#if defined(MACOS) || defined(TARGET_OS_MAC)` to `#if defined(MACOS)`.

**Comment by matejk** [comment]
Where did you install clang 18 from?

Latest XCode 15.4 installs clang 15.

**Comment by matejk** [comment]
@JackyWoo, would you try compiling the code from PR #4587?

**Comment by JackyWoo** [comment]
@matejk buid success, thanks.

**Comment by kornelski** [comment]
If anyone encounters this error in a Rust/Cargo project, it's due to an old version of [cloudflare-zlib-sys](https://lib.rs/crates/cloudflare-zlib-sys), and updating deps is enough to fix it:

```bash
cargo update
```

**Comment by PerezChilli** [comment]
> `zutil.h` is part of `zlib` which is a 3rd Party library Poco uses. Looks like this code has changed slightly in the latest code, maybe it doesn't cause the issue. Line 40 changed from `#if defined(MACOS) || defined(TARGET_OS_MAC)` to `#if defined(MACOS)`.

Thank you! Manually changed **zutil.h** in build dir and my OpenWRT build passed
