### ISSUE TITLE
Incorrect setting of ciphersuites for TLSv1.3

### ISSUE THREAD

**Issue by afshinpir** [pocoproject/poco#4610]
Hi all,

In OpenSSL version of NetSSL, you are using `SSL_CTX_set_cipher_list` method to set cipher list:
https://github.com/pocoproject/poco/blob/1edabc19d8ed70362f764b2bfc25efc297f617e8/NetSSL_OpenSSL/src/Context.cpp#L192
But the point is that this method only affects TLSv1.2 and below, and for TLSv1.3 you need to use `SSL_CTX_set_ciphersuites()` method based on OpenSSL documentation here: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_cipher_list.html

**Comment by micheleselea** [comment]
You are right @afshinpir the point is that probably we need a new cipherList_TLS1.3 params because the two configuration are completely different. The default value for 1.3 is
"TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256"

**Comment by micheleselea** [comment]
I understand from the commit that you replace SSL_CTX_set_cipher_list with SSL_CTX_set_ciphersuites
```
#if OPENSSL_VERSION_NUMBER >= 0x30000000L
		SSL_CTX_set_ciphersuites(_pSSLContext, params.cipherList.c_str());
#else
		SSL_CTX_set_cipher_list(_pSSLContext, params.cipherList.c_str());
#endif // OPENSSL_VERSION_NUMBER >= 0x30000000L
```
But if I'm not wrong, from Openssl documentation I think that 
SSL_CTX_set_cipher_list is for TLS1.2
and
SSL_CTX_set_ciphersuites this is for TLS1.3

I think we need both function, even because cipher for 1.2 and 1.3 are different, Am I wrong?

**Comment by matejk** [comment]
@micheleselea, does it work properly?

**Comment by micheleselea** [comment]
I did not try it yet, but I was looking in documentation for example
[debian](https://manpages.debian.org/bullseye/libssl-doc/SSL_CTX_set_ciphersuites.3ssl.en.html#:~:text=SSL_CTX_set_ciphersuites%20%28%29%20is%20used%20to%20configure%20the%20available,ciphersuite%20names%20are%3A%20An%20empty%20list%20is%20permissible.)
or
[ibm](https://www.ibm.com/docs/en/ztpf/2024?topic=apis-ssl-ctx-set-ciphersuites)
but even in the official OpenSSL and I read that SSL_CTX_set_ciphersuites impacts only in TLS1.3 for TLS1.2 you still have to use SSL_CTX_set_cipher_list
This is what I understand, do you think is not correct?

**Comment by afshinpir** [comment]
I think this implementation is wrong.
You need 2 different methods, one for setting cipher list and another one for setting cipher suites.
The reason is the fact that one TLS connection may connect with TLSv1.3 if other one supports it and if not, it will falls back to older version like TLSv1.2. So both lists are needed in practice.
