### ISSUE TITLE
undefined reference to `Poco::Data::Session::~Session()'

### ISSUE THREAD

**Issue by AfricanDEV-og** [pocoproject/poco#4625]
I don't know whether this is simply a problem in my side or your side. For the past few days, I have been struggling on building my project due to g++ not finding the actual reference of Poco Session. Yes, I had no problem with CMake and had no problems with installing it either (I installed it via vcpkg). I integrated vcpkg with Cmake which wasn't that difficult as well. The only problem I'm facing is how to solve this problem:

CMAKE FILE
```cmake_minimum_required(VERSION 3.5.0)
project(GDeliver VERSION 0.1.0 LANGUAGES C CXX)

find_package(Poco REQUIRED COMPONENTS Util DataSQLite Data)
add_subdirectory(util)

add_executable(${PROJECT_NAME} main.cpp)

target_link_libraries(${PROJECT_NAME} PRIVATE Poco::Util Poco::DataSQLite Poco::Data)
target_link_directories(${PROJECT_NAME} PRIVATE util)
```

Source code
```#include "Poco/Data/Session.h"
#include "util/Appstate.hpp"

#include <iostream>

using namespace Poco::Data;

int main() {
    Session session("SQLite", "GDatabase.db");

    // Appstate state = { session };

    std::cout << "Works?\n";
}
```
Output
```undefined reference to `Poco::Data::Session::Session(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long)'```

**Comment by matejk** [comment]
Which version of Poco on which platform?

**Comment by AfricanDEV-og** [comment]
@matejk I have the latest poco version in vcpkg. (1.13.3)

**Comment by matejk** [comment]
Output indicates different error than it is mentioned in the title. 

Output suggests that you used wrong parameters for the ctor.

**Comment by AfricanDEV-og** [comment]
@matejk True. There were like a lot of errors so I chose one that is easy to comprehend as the title and the one that is more elaborate as the output.

**Comment by AfricanDEV-og** [comment]
@matejk This time. I tried using Net library but the error still persisted. 

CMAKE

```
cmake_minimum_required(VERSION 3.5.0)
project(GDeliver VERSION 0.1.0 LANGUAGES C CXX)

find_package(Poco REQUIRED COMPONENTS Net)

add_executable(${PROJECT_NAME} main.cpp)

target_link_libraries(${PROJECT_NAME} PRIVATE Poco::Net)
```

SOURCE CODE
```
#include "Poco/Net/SocketAddress.h"

#include <iostream>

int main() {
    Poco::Net::SocketAddress sa("www.appinf.com", 80);
    std::cout << "Works?\n";
}

```

ERROR

```
undefined reference to `Poco::Net::IPAddress::IPAddress(void const*, int)'
undefined reference to `Poco::Net::IPAddress::IPAddress(void const*, int, unsigned int)'
undefined reference to `Poco::Net::Impl::IPv6SocketAddressImpl::toString[abi:cxx11]() const'
undefined reference to `Poco::Net::Impl::IPv4SocketAddressImpl::toString[abi:cxx11]() const'
```

**Comment by AfricanDEV-og** [comment]
I changed the compiler from g++ to MSVC and it worked.
