### ISSUE TITLE
Make `Util::Application::getApplicationPath()` and `findAppConfigFile()` protected

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4630]
**Is your feature request related to a problem? Please describe.**
Application loads config files and forgets which file(s) it has loaded.

**Describe the solution you'd like**
Make `Application::getApplicationPath()` and `Application::findAppConfigFile()` protected so that inheriting classes can utilize them to find the default config file name (when it wasn't specified on the command line) and retain it in the runtime config.

**Comment by siren186** [comment]
@aleks-f Consider about this PR https://github.com/pocoproject/poco/pull/4661
