### ISSUE TITLE
can not run Crypto sample code

### ISSUE THREAD

**Issue by edidadaoutlook** [pocoproject/poco#4639]
can not run Crypto sample code

https://github.com/pocoproject/poco/blob/main/Crypto/samples/genrsakey/src/genrsakey.cpp

error: libc++abi: terminating with uncaught exception of type Poco::Crypto::CryptoException: Crypto Exception

**Comment by aleks-f** [comment]
@matejk I can reproduce this, apparently something on destruction because files are produced ok

**Comment by matejk** [comment]
Which OS?

**Comment by aleks-f** [comment]
> @aleks-f , @edidadaoutlook On which OS is this problem reproducible?
> 
> Works properly on macOS (Apple Silicon), compiled with clang.

@matejk I was able to reproduce the problem on Linux/g++

**Comment by matejk** [comment]
* Ubuntu 24.04
* openssl 3.0.13-0ubuntu3.4
* g++ (Ubuntu 13.2.0-23ubuntu4) 13.2.0
* cmake version 3.28.3

Poco (current main (pre 1.14)) is built with CMake.

`genrsakey -f new-key` runs just fine in `Debug` and `RelWithDebInfo`.

@aleks-f, @edidadaoutlook: Can't reproduce. No exception is thrown. Do you have some more details how to reproduce the problem?
