### ISSUE TITLE
Poco::Zlib: Unimplemented ZipArchiveInfo::getVersionMadeBy and ZipArchiveInfo::getRequiredVersion

### ISSUE THREAD

**Issue by tbeu** [pocoproject/poco#4655]
ZipArchiveInfo::getVersionMadeBy and ZipArchiveInfo::getRequiredVersion are declared, but never defined.

https://github.com/pocoproject/poco/blob/63bed8c8d376d13cb3a86f78966884c649745ea6/Zip/include/Poco/Zip/ZipArchiveInfo.h#L137-L141

**Comment by matejk** [comment]
@tbeu, thank you for finding this out.

Would you be so kind and prepare a pull request that implements missing functions?
