### ISSUE TITLE
File Channel Logs in UTC Despite ‘times = local’

### ISSUE THREAD

**Issue by pavledragisic** [pocoproject/poco#4703]
**Describe the bug**
Logging file channel logs using UTC time even though it is configured to use local time by setting `logging.channels.file.times = local`. For console channel it is not possible to specify `times` parameter.

**To Reproduce**
Add this configuration and compare times in logs with actual time.
```
logging.channels.file.class = FileChannel
logging.channels.file.pattern = %Y-%m-%d %H:%M:%S.%i [%p] %s<%I>: %t
logging.channels.file.path = ${application.dir}log/${application.baseName}.log
logging.channels.file.rotation = daily
logging.channels.file.archive = number
logging.channels.file.purgeCount = 10
logging.channels.file.times = local
```

**Expected behavior**
When `logging.channels.file.times = local` is configured, timestamps in log file should be using local time. Also `times` parameter should be supported in console channel.
Currently workaround this issue is to use `PatternFormatter`.
Example configuration:
```
logging.channels.file.class = FileChannel
logging.channels.file.path = /var/log/devs/${application.baseName}.log
logging.channels.file.formatter.class = PatternFormatter
logging.channels.file.formatter.pattern = %Y-%m-%d %H:%M:%S.%i [%p] %s<%I>: %t
logging.channels.file.formatter.times = local

logging.channels.file.rotation = daily
logging.channels.file.archive = number
logging.channels.file.purgeCount = 10

logging.channels.console.class = ColorConsoleChannel
logging.channels.console.formatter.class = PatternFormatter
logging.channels.console.formatter.pattern = %Y-%m-%d %H:%M:%S.%i [%p] %s<%I>: %t
logging.channels.console.formatter.times = local
```

**Comment by Felipe-Rafael-Rosa** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by obiltschnig** [comment]
Check the documentation. The times parameter controls log rotation. 
To specify a local time for the timestamp written to the logfile, use the %L format specifier or the `times` property of the `PatternFormatter`.

```
	/// Using the "times" property it is possible to specify
	/// time mode for the day/time based rotation. The following values
	/// for the "times" property are supported:
	///
	///   * utc:        Rotation strategy is based on UTC time (default).
	///   * local:      Rotation strategy is based on local time.
```
