### ISSUE TITLE
Cannot set library prefix from command line

### ISSUE THREAD

**Issue by grandinj** [pocoproject/poco#4763]
i.e.

    cmake .. -DLIBPREFIX=foo

does not work.

Ideally POCO should be using the normal CMake stuff instead of re-inventing the wheel, but at least overriding should work.

**Comment by matejk** [comment]
@grandinj, what do you mean by "POCO should be using the normal CMake stuff instead of re-inventing the wheel"?

Was this reproduced with the latest code from `main`?

**Comment by grandinj** [comment]
Hi @matejk 

Thanks for responding. Yes, I tested with the latest code from main.

Possibly I am mistaken, or using the cmake build wrong, so feel free to close this bug if I am being an idiot :-)

As far as I understand, CMake already has:

https://cmake.org/cmake/help/v3.17/variable/CMAKE_SHARED_LIBRARY_PREFIX.html

Which is what I meant by "re-inventing the wheel".

What I was trying to do, was to remove the "lib" prefix that is inserted for library names on Linux.

**Comment by matejk** [comment]
Poco does not use `LIBPREFIX` in CMake files. They are only used when building with make.

Did you try setting `CMAKE_SHARED_LIBRARY_PREFIX` when configuring CMake?

**Comment by grandinj** [comment]
> Did you try setting `CMAKE_SHARED_LIBRARY_PREFIX` when configuring CMake?

Yes, I tried
    cmake .. -DCMAKE_SHARED_LIBRARY_PREFIX=xxx
but it always used "lib".

Hmmm, some googling finds me this:
https://discourse.cmake.org/t/how-to-use-cmake-shared-library-prefix-in-command-line/11410

So apparently this is a CMake issue, not a Poco issue.

Thanks for checking, I will close this.
