### ISSUE TITLE
ProcessRunner sync

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4766]
devs <-> poco sync ProcessRunner

**Comment by pavledragisic** [comment]
@aleks-f There are no features in devs that are not in poco.

Main difference between poco and devs is  feature to find executable which is implemented in [poco](https://github.com/pocoproject/poco/blame/2815ea45a92fe487a2bf77efcf822deee9410b99/Foundation/src/ProcessRunner.cpp#L230) in this PR:
https://github.com/pocoproject/poco/commit/3656f069e16dcf0ee7b75060fbe7d337b86272e6#diff-e3b4417cfde2e5d0e0f0c0b2c7592d2d72c9f38b44ba59c7287e4a712ea8fd64
