### ISSUE TITLE
pocoNetworkInitializer - change fixed path (Windows Platform related)

### ISSUE THREAD

**Issue by Tepic** [pocoproject/poco#4769]
Currently there is a fixed path set for pocoNetworkInitalizer for a Windows platform:
#define POCO_NET_FORCE_SYMBOL(s) __pragma(comment (linker, "/include:_"#s))

It should be resolved, so the external project can define the path custom to its needs and build-output location

**Comment by matejk** [comment]
Resolved in #4770
