### ISSUE TITLE
Application cleanup not possible after returning from waitForTerminationRequest if CTRL_CLOSE_EVENT

### ISSUE THREAD

**Issue by petersmar** [pocoproject/poco#535]
Writing a (server) application.
Cleanup code is written after call to waitForTerminationRequest(). This works fine if console application is terminated by CTRL_C_EVENT. But...

If application is terminated by clicking the "X" to close the console window, the CTRL_CLOSE_EVENT is send. After that, waitForTerminationRequest() returns but within the next operations Windows terminates the application. Application could not complete its cleanup work.
Termination is done when registered handler routine returns. See MSDN (http://msdn.microsoft.com/en-us/library/windows/desktop/ms683242%28v=vs.85%29.aspx, section "Remarks"): "Return TRUE. In this case, no other handler functions are called and the system terminates the process."

Would be fine to have a "asynchronous" version of the waitForTerminationRequest function, that does not set the _terminated event before returning, so the request handler would not return and Windows would not terminate application directly. Therefore a second function "signalApplicationTerminated" could be introduced to set the _terminated event before application exits.

**Comment by whidbey** [comment]
same issue at Poco 1.7.8 p3
