### ISSUE TITLE
Poco SQLite: SELECT query throws NotFound exception

### ISSUE THREAD

**Issue by asockanathan** [pocoproject/poco#542]
I am using Poco 1.4.6p4. A SQLite SELECT query throws a NotFound error. The SELECT looks like this:
"SELECT chr_value from parameter WHERE chr_name='dns_address'"

statement.execute throws this error. I even tried piping the SELECT to a Session and found the same problem. 
Any suggestions what could be the problem.

**Comment by aleks-f** [comment]
works for me
