### ISSUE TITLE
Feature request: install PocoConfig.cmake when installing from zip.

### ISSUE THREAD

**Issue by mkcybi** [pocoproject/poco#555]
I would be nice if while making Poco make/configure would install PocoConfig.cmake into the proper directory.  Right now I don't think it puts it anywhere cmake could use it.

**Comment by Bjoe** [comment]
For the sake of completeness in `poco-1.9.1` and `develop` branch, the cmake build is create and install `PocoConfig.cmake` into the proper directory and is easily to use with `find_package(Poco REQUIRED Foundation)`
I think this issue is fixed.
