### ISSUE TITLE
Reschedule Poco::Util::TimerTask

### ISSUE THREAD

**Issue by bachp** [pocoproject/poco#605]
I have some periodic Tasks running using `Poco::Util::Timer`.
The tasks are started using `Poco::Util::Timer::schedule(taks, delay, interval)`.

Now I would like to reschedule one of these tasks so that it runs again after a given delay and then again periodic with the given interval. So basically re-positioning the moment of periodic execution in time.

I tried to cancel the `Poco::Util::TimerTask` but once it is canceled I can not reschedule it.
Is there a way to achieve this?

**Comment by naderafshari** [comment]
Where do you call reschedule()? Can you call it from inside mytask()
