### ISSUE TITLE
Idle Reactor high CPU usage

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#607]
Before a connection is accepted reactor loops without timeout repeatedly calling onIdle(), which results in high CPU usage.

**Comment by MaPoToFuGit** [comment]
I found the same issue while using version 1.7.2-all, anyone can help me?

**Comment by MaPoToFuGit** [comment]
ah,I found the reason that I register the eventhandler of writeable, I found it when I print logs.
