### ISSUE TITLE
Nullable for types without default constructor

### ISSUE THREAD

**Issue by hadzim** [pocoproject/poco#617]
I am not using Poco::Nullable in my projects, because it has one disadvantage. It cannot be used with types without default constructor.

There is simple change to change type of private member _value to pointer (or better smart pointer) to given type.

This change does not have any effect on public interface from my point of view.

I can write pull request, but first I would like to ask if it makes sense for you and if yes, what type of pointer should be used (raw pointer, std::auto_ptr, std::unique_ptr, Poco::SharedPtr)

**Comment by lgm42** [comment]
I'm agree to the disadvantage of can't use Poco::Nullable with types with default ctor.

For example I would like to make that in class members:
~~~c++
Poco::Nullable<Poco::ProcessHandle> m_pppdProcessHandle;
~~~

And it is not possible but at the creation of my class m_pppdProcessHandle is set as NULL until I assign it a value. So it really makes sense to do that.
