### ISSUE TITLE
Remove support for compiling without POCO_WIN32_UTF8 on Windows

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#630]
Experience shows that supporting Windows builds without POCO_WIN32_UTF8 defined leads to some issues as a) this configuration is not regularly tested and b) causes duplicate work, which in some cases (e.g. Poco::Glob) would be significant and thus has not been done. For 1.6 I propose to deprecate compilation on Windows without POCO_WIN32_UTF8 defined, and emitting a warning if this is attempted. For 2.0, POCO_WIN32_UTF8 will probably be removed and the existing behavior of POCO_WIN32_UTF8 is defined will be the standard behavior.

**Comment by aleks-f** [comment]
@obiltschnig can `POCO_NO_WSTRING` also be removed for 2.0? Currently, it is used inconsistently alongside `POCO_WIN32_UTF8`

**Comment by obiltschnig** [comment]
It's still used by some embedded Linux configurations, so not sure. It's not used/supported on Windows, so it's independent of POCO_WIN32_UTF8.

**Comment by aleks-f** [comment]
ok, let's leave it as is for now. The major places where `wchar_t` is used is Windows and XML with `XML_UNICODE_WCHAR_T` defined - not sure how much is that used, but it does not account for `POCO_NO_WSTRING`

**Comment by obiltschnig** [comment]
`XML_UNICODE_WCHAR_T` is not really well supported anyway. Most of the code using XML won't work with `XML_UNICODE_WCHAR_T` defined.
