### ISSUE TITLE
Exception on application shutdown when using asynchronous logging

### ISSUE THREAD

**Issue by petersmar** [pocoproject/poco#639]
There is an application based on Poco::Util::ServerApplication and using logging.
Logging uses the AsyncChannel to do logging.
(Complete logging chain is: Logger -> AsyncChannel -> SplitterChannel -> 1. ConsoleChannel + PatternFormatter, 2. FileChannel + PatternFormatter)

The application terminates. The ServerApplication class uninitialises the subsystems, which also includes the Logging subsystem. The uninit is completed, while pending log messages are processed by the asynchronous logger thread.
It happens that the thread calls the PatternFormatter function getPriorityName and the static string array "priorities" is already cleaned:

![2014-12-15 09_48_18-telro_server debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/8695557/5433993/85e6a770-844d-11e4-9562-55343c242d71.png)

So calling priorities[prio] results in an out_of_range exception:

![2014-12-15 11_23_23-telro_server debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/8695557/5433998/9d7517c8-844d-11e4-9bb6-aeff7268aadf.png)

Uninitialisation of the logging subsystem should ensure that the asynchronous logging is completed, before subsystem is ceared and removed.

**Comment by bas524** [comment]
Hi! Is it fixed in develop? I saw that getPriorityName use local variable _priorities.
