### ISSUE TITLE
Regex: match all

### ISSUE THREAD

**Issue by DEvil0000** [pocoproject/poco#643]
i would suggest a enhancement for regex.
if you extract parts of a string with capturing groups you can only get the first or last group matches.
i would suggest a method like matchall() or support for /g option (i think this is the global option) to find all matches of a regex in a string.

example:
https://regex101.com/
php regex
regex: /abc(\d)/g
string to match: abc1xyzabc2xyzabc3
expected result:
matches=3
match1: "1"
match2: "2"
match3: "3"

**Comment by martin-osborne** [comment]
@DEvil0000 

I've started to prepare a pull request for this.  However, in the example above, the matches you list are for sub-expression 1, which seems odd to me.  I'd expect the matches to be for sub-expression zero, i.e. "abc1", "abc2", and, "abc3".  In what I'm preparing to submit the first form of `matchAll` will return `["abc1", "abc2", "abc3"]`.  The second form of `matchAll` will return `[["abc1", "1"], ["abc2", "2"], ["abc3", "3"]]`, so it should give you what you need.

```
    int matchAll(const std::string& subject, std::string::size_type offset, MatchVec& matches, int options = 0) const;
        /// Matches all the non-overlapping occurances of the subject string, starting at offset, against the pattern. 
        /// Returns the position of each matched substring in matches.
        /// If no part of the subject matches the pattern, matches is empty.
        /// Throws a RegularExpressionException in case of an error.
        /// Returns the number of matches.

    int matchAll(const std::string& subject, std::string::size_type offset, std::vector<MatchVec>& matches, int options = 0) const;
        /// Matches all the non-overlapping occurances of the subject string, starting at offset, against the pattern. 
        /// For each match it returns the captured text for each subexpression in matches[i].
        /// If no part of the subject matches the pattern, matches is empty.
        /// Throws a RegularExpressionException in case of an error.
        /// Returns the number of matches.
```

**Comment by martin-osborne** [comment]
I should clarify that you can achieve the results in the example you posted using a positive lookahead `(?=abc)\d`, and the first form of `matchAll`.  The second form is still required (I believe) to find overlapped matches using `(?=(xyz))`.

**Comment by DEvil0000** [comment]
I was using the regex `/abc(\d)/g` in my example so the matches '1','2' and '3' are perfectly expected. It is returning the captured matches for the part in brackets (capturing group). As far as i know this is perfectly expected.
If you write it like `(abc\d)` then you will match 'abc1' and so on.
This is why I would consider your first method as incorrect. The second is at least returning the captured part.

Usecase: extracting substrings from a string according to a regex.

Take a look at:
https://regex101.com/
http://www.regular-expressions.info/brackets.html

**Comment by martin-osborne** [comment]
This is just for background:

Ruby
----
Ruby's equivalent of `matchAll` is [scan](http://ruby-doc.org/core-2.2.0/String.html#method-i-scan). Examples of `scan`'s behavior:

```
"abc1xyzabc2xyzabc3".scan(/abc(\d)/) { |m| print m, ' '; }
print "\n";
```
Produces: `1 2 3`
```
"abc1xyzabc2xyzabc3".scan(/abc\d/) { |m| print m, ' '; }
print "\n";
```
Produces: `abc1 abc2 abc3`
```
"abc1xyzabc2xyzabc3".scan(/(abc)(\d)/) { |m| print m[0], ' ', m[1], ' '; }
print "\n";
```
Produces: `abc 1 abc 2 abc 3`

Python
------
Python's equivalent of `matchAll` is [findall](https://docs.python.org/2/library/re.html#re.findall).  Examples of `findall`'s behavior:
```
import re
print(re.findall("abc(\\d)", "abc1xyzabc2xyzabc3"));
```
Produces: `['1', '2', '3']`
```
import re
print(re.findall("abc\\d", "abc1xyzabc2xyzabc3"));
```
Produces: `['abc1', 'abc2', 'abc3']`
```
import re
print(re.findall("(abc)(\\d)", "abc1xyzabc2xyzabc3"));
```
Produces: `[('abc', '1'), ('abc', '2'), ('abc', '3')]`

ECMAScript
----------
ECMAScript's equivalent of `matchAll` is [match](http://www.w3schools.com/jsref/jsref_match.asp).  Examples of `match`'s behavior (using the `js` command line tool from Mozilla):
```
var result = "abc1xyzabc2xyzabc3".match(/abc(\d)/g);
print(result);
```
Produces: `abc1,abc2,abc3`
```
var result = "abc1xyzabc2xyzabc3".match(/abc\d/g);
print(result);
```
Produces: `abc1,abc2,abc3`
```
var result = "abc1xyzabc2xyzabc3".match(/(abc)(\d)/g);
print(result);
```
Produces: `abc1,abc2,abc3`

Java
----
```
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Test {
	public static void main(String args[]) {
		Matcher m = Pattern.compile("abc(\\d)").matcher("abc1xyzabc2xyzabc3");
		while (m.find()) {
			System.out.println(m.group());
		}
	}
}
```
Produces:
```
abc1
abc2
abc3
```
```
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Test1 {
	public static void main(String args[]) {
		Matcher m = Pattern.compile("abc\\d").matcher("abc1xyzabc2xyzabc3");
		while (m.find()) {
			System.out.println(m.group());
		}
	}
}
```
Produces:
```
abc1
abc2
abc3
```
```
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Test2 {
	public static void main(String args[]) {
		Matcher m = Pattern.compile("(abc)(\\d)").matcher("abc1xyzabc2xyzabc3");
		while (m.find()) {
			System.out.println(m.group());
		}
	}
}
```
Produces:
```
abc1
abc2
abc3
```

PHP
---
```
<?php

$re = "/abc(\\d)/";
$str = "abc1xyzabc2xyzabc3";
preg_match_all($re, $str, $m);
for ($i = 0; $i < count($m); $i++) {
	for ($j = 0; $j < count($m[$i]); $j++) {
		print "match[" . $i . "][" . $j . "]=" . $m[$i][$j] . "\n";
	}
}
?>
```
Produces:
```
match[0][0]=abc1
match[0][1]=abc2
match[0][2]=abc3
match[1][0]=1
match[1][1]=2
match[1][2]=3
```

**Comment by martin-osborne** [comment]
@DEvil0000 ,

Firstly, thank you for getting back to me on this issue.

I have two points about the above findings:
1. PHP's `preg_match_all` seems to behave exactly like the second form of `matchAll`. So I hope you are okay with the second form of `matchAll`.
2. Ruby and Python appear to behave differently to ECMAScript & Java.  Ruby and Python behave as you would expect; ECMAScript and Java behave as I would expect.  I don't really have a strong view as to which is "better".  On reflection I think Ruby/Python's behavior is more useful, but ECMAScript/Java's behavior is more consistent with POCO's two versions of `match`.  For now, I think I will cowardly sidestep the issue and only put the second form of `matchAll` forward for review.  The first form of `matchAll` doesn't provide anything the second form provides, it is (in some cases) a little more convenient.

I hope that is acceptable.

**Comment by martin-osborne** [comment]
P.S.  Do let me know if there are any mistakes in the above examples.  I have no previous experience in some of the languages.

**Comment by DEvil0000** [comment]
@martin-osborne 
your ECMA/Javascript code looks wrong
the following code works like the php code
see: https://regex101.com/ (code generator)
```
    var re = /abc(\d)/g;
    var str = 'abc1xyzabc2xyzabc3';
    var m;
     
    if ((m = re.exec(str)) !== null) {
      if (m.index === re.lastIndex) {
         re.lastIndex++;
      }
      // View your result using the m-variable.
      // eg m[0] etc.
    }
```
I think your java code is also not correct.
Try a additional call to:
`m.group(1)` this should return the captured content of capture group 1

**Comment by martin-osborne** [comment]
@DEvil0000 ,

Okay, I'll make the first form work like Ruby's `scan` method, add a couple more tests and submit it for review.

Thanks for the feedback.
