### ISSUE TITLE
asynchronous network library 

### ISSUE THREAD

**Issue by lion117** [pocoproject/poco#655]
it seems that poco provided few  low level network library  ,  i would like to ask whether there is any plan for the poco team  to develop  the asynchronous network library ?   
without the asynchronous network library supporting , i will have to take the multiple thread to solve my problem , which would cuase the program quite complicated  , and easy to loss control .

**Comment by bantl23** [comment]
Just out of curiosity, what happened to the following?

https://pocoproject.org/blog/?p=87

Was it removed?

**Comment by obiltschnig** [comment]
That approach was abandoned. Next step in 1.8 will be a better wrapper around epoll/poll, which at one point may become a building block for a truly async network library.
