### ISSUE TITLE
"Address family not supported" exception on OSX

### ISSUE THREAD

**Issue by 0x1mason** [pocoproject/poco#657]
I'm experiencing this issue with Yosemite 10.10 and clang 6. I believe this issue is related to #234 .

I get an "Address family not supported" exception in **HTTPClientSession::sendRequest** when using a valid URI such as `http://localhost:4723/wd/hub/session`. 

Here's the problem function:
```cpp
    std::unique_ptr<Response> doSession(const std::string& url, const std::string& verb, const std::string& data)
    {
        std::stringstream response;

        try
        {
            // prepare session
            Poco::URI uri(url);
            Poco::Net::HTTPClientSession session(uri.getHost(), uri.getPort());

            // prepare path
            std::string path(uri.getPathAndQuery());
            if (path.empty()) path = "/";

            // send request
            Poco::Net::HTTPRequest req(verb, path, Poco::Net::HTTPMessage::HTTP_1_1);
            req.set("Content-Type", "application/json;charset=UTF-8");
            req.set("Accept", "application/json");
            std::ostream& os = session.sendRequest(req);

            if (!data.empty()) {
                // write request body to stream
                std::stringstream ifs(data); // missing: error handling
                Poco::StreamCopier::copyStream(ifs, os);
            }

            // get response
            Poco::Net::HTTPResponse res;
            std::istream &is = session.receiveResponse(res);
            Poco::StreamCopier::copyStream(is, response);
        }
        catch (Poco::Exception &ex)
        {
             std::cerr << ex.displayText() << std::endl;
        }
        //
        return std::make_unique<Response>(response.str());
    }
```
I'm using POCO built for static linking, if that makes any difference.  Here's my config: ./configure --omit=Data/ODBC,Data/MySQL,NetSSL_OpenSSL,Crypto,MongoDB,Data,Data/SQLite,XML,Zip --config=Darwin64-clang-libc++ --static

Thanks!

**Comment by 0x1mason** [comment]
The problem goes away if I put the code directly in my executable, eg exe=>poco.a.  However, if do exe=>my_lib.a=>poco.a, then the problem reappears.  Other poco features work fine.

**Comment by 0x1mason** [comment]
I got this sorted--I don't think I set the --config option when I built the static binaries.

**Comment by AbhinavBansal** [comment]
Hi @0x1mason 
I am facing a similar problem, Could you please help? 
here is the config file that I used: 
./configure --omit=Data/ODBC,MonoDB,Data/MySQL,Data/SQLite --config=Darwin64-clang-libc++ --static
Environment:
Poco:1.6.0
XCode: 6.1.1
OS-X: 10.10
Simple HTTP Request is failing with same exception

**Comment by bas524** [comment]
on OS X
at SocketImpl.cpp
`SocketImpl::initSocket(int af, int type, int proto) {
...
_sockfd = ::socket(af, type, proto);
...
}`
socket can't be created with PF_UNSPEC.
if af is equal to 0, then socket return EAFNOSUPPORT.

**Comment by bas524** [comment]
On OS X 10.11 SocketAddress initialized correctly only if POCO_ENABLE_CPP11 enabled, otherwise "Address family not supported"

**Comment by gelldur** [comment]
In my case i moved C++11 flag to the end of my CMakeLists.txt. As @bas524  sad :) TY!

`SET(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-std=c++11")`
