### ISSUE TITLE
why readable/writable/except list  rebuilt every time?

### ISSUE THREAD

**Issue by stallion5632** [pocoproject/poco#659]
void SocketReactor::run()
{
	Socket::SocketList readable;
	Socket::SocketList writable;
	Socket::SocketList except;
	
	while (!_stop)
	{
		try
		{
			readable.clear();
			writable.clear();
			except.clear();
			int nSockets = 0;
			{
				FastMutex::ScopedLock lock(_mutex);
				for (EventHandlerMap::iterator it = _handlers.begin(); it != _handlers.end(); ++it)
				{
					if (it->second->accepts(_pReadableNotification))
					{
						readable.push_back(it->first);
						nSockets++;
					}
					if (it->second->accepts(_pWritableNotification))
					{
						writable.push_back(it->first);
						nSockets++;
					}
					if (it->second->accepts(_pErrorNotification))
					{
						except.push_back(it->first);
						nSockets++;
					}
				}
			}
			....
			
I do not understand why rebuilt readable/writable/except list every time in the while loop.
 Is it good for performance.?

**Comment by aleks-f** [comment]
Because you (1) build a list of signalled sockets, (2) dispatch notifications, (3) clear the list and do (1),(2),(3) again for the next set of signalled sockets. How do you propose to do it?

**Comment by stallion5632** [comment]
Can wen create(or update) readable/writable/except list in the SocketReactor::addEventHandler (or SocketReactor::removeEventHandler)?

Beacause SocketReactor::addEventHandler and SocketReactor::removeEventHandler  do not execute frequently.

move 
「
	for (EventHandlerMap::iterator it = _handlers.begin(); it != _handlers.end(); ++it)
	{
		if (it->second->accepts(_pReadableNotification))
		{
			readable.push_back(it->first);
			nSockets++;
		}
		if (it->second->accepts(_pWritableNotification))
		{
			writable.push_back(it->first);
			nSockets++;
		}
		if (it->second->accepts(_pErrorNotification))
		{
			except.push_back(it->first);
			nSockets++;
		}
	}

」

to the SocketReactor::addEventHandler;

And add some code in the SocketReactor::removeEventHandler.

I've tried this method,it's feasible.

**Comment by aleks-f** [comment]
Raison d'etre of the reactor is to loop (i.e. execute "frequently") and react to the pending I/O. If I am not misunderstanding, you propose to iterate over all the registered handlers only once in every newly created handler to populate the socket lists. How does the data I/O which occurs after the handler creation get processed? Who dispatches events on the sockets that become readable/writable after the handler creation?

**Comment by rafzi** [comment]
If you make the socket lists members of the SocketReactor, you would need to keep the lock while executing `select`. This would cause a possible hang on `addEventHandler` and `removeEventHandler`.

Alternatively, if you copy those new members every time before `select`, you just moved code around and didn't gain any performance.
