### ISSUE TITLE
Poco::Thread leak on Linux

### ISSUE THREAD

**Issue by DEvil0000** [pocoproject/poco#675]
I am using version 5.2 and have not tested if it is fixed in the new one.
the bug is "the same" as in [#79](https://github.com/pocoproject/poco/issues/79).

getting SystemException with message "cannot start thread" after 350-550 Thread starts.

Here is some code to reproduce the problem:

``` C++
#include <Poco/Thread.h>
#include <iostream>

using namespace std;
using namespace Poco;

Thread t;

class RC: public Runnable {
virtual void run() {}
};

RC r;

int main(int argc, char * argv[]){
  int count = 0;
  while (1) {
    //t.join(); //this fixes the issue so it has to be the same as in #79
    t.start(r);
    Thread::sleep(100);//the thread calling run finished the work
    cout<<"count"<<count++<<endl;
  }
}
```

i think the fix is to have something like the following in the start method:

``` C++
if (isRunningImpl())
      pthread_detach(_pData->thread);
```

edit:
i would expect to reuse the pthread if i reuse the poco::Thread but it seams this is not the case. otherwise there would not be a thread leak - right?

**Comment by aleks-f** [comment]
Just out of curiosity: how many threads do you expect you should be able to start without joining? If you need hundreds of threads to run concurrently, create them. If you don't want to join them, let them be destructed and targets remain running in the wild (don't be surprised if it takes long time for your program to exit). 

If pthread is joinable (which is default), then you must join it in order to force the release all of its resources. System will not reclaim the thread's resources automatically unless it is detached; in Poco implementation, detaching happens only at destruction.

**Comment by DEvil0000** [comment]
i expect the following:
>a poco::Thread instance equals/wrapps one os thread.
>start(Runnable) starts the runnable in the os thread if there is no runnable running in the thread
>if a os thread was started before but has ended execution start(runnable) should reuse it and not start a new os thread.
>i should not care about destroy or join logic as long as i don't need/want to join (wait for execution finish of the thread)

current implementation of poco::thread(pthread wrapper) will create a new pthread for every start() call but it will only handle destruction for the last created one when you destroy the poco::thread.
i would expect some logic to reuse the created pthread or at least destroy it correct. poco::threadPool seams to do it "correct" when using PooledThread class.

you got me?

**Comment by aleks-f** [comment]
If you know of a way to "reuse the created pthread" thread (other than thread pool pattern), let us know.

As for request to join before we create another thread, since we already check if the previous incarnation is running (and throw if it is), maybe it does have some merit. @obiltschnig ?

**Comment by DEvil0000** [comment]
for ticket #79 you fixed pretty much the same thing for destruction of a thread object. from my perspective start() should at least do the same thing:
>if (isRunningImpl())
>      pthread_detach(_pData->thread);

but maybe it would be better to use something like the PooledThread mechanism inside a poco::Thread(pthread) if pthread has no mechanism to reuse the thread. (but i think it has something to reuse it, otherwise it would not make much sense in my eyes to keep it even when execution is finished until we join it)

**Comment by obiltschnig** [comment]
The other question is whether Poco::Thread should be reusable at all. pthreads and Windows threads are not reusable, and neither is std::thread. For POCO 2.0, Poco::Thread will be a thin layer around std::thread, so whatever std::thread does should be what we do.

**Comment by DEvil0000** [comment]
this should be the std::thread equivalent to what poco is doing:

```C++
// thread example
#include <iostream>       // std::cout
#include <thread>         // std::thread
#include <unistd.h>

using namespace std;
 
void* foo(void* temp) 
{
  // do stuff...
}

std::thread t;

int main() 
{
  static int count=0;
  long unsigned int handle = t.native_handle();
  while(1){
   pthread_create(&handle, NULL, foo, NULL);
   usleep(100);
   //t.join();
   cout<<"count:"<<count++<<endl;
  }
  return 0;
}
```
>g++ test.cpp -std=c++11 -pthread

on std::thread is no start method but a constructor without argument this kind of sucks.. i have not found a other way than exployting the native_handle()...

as you will see it behaves different - but i am not yet sure in which kind...
with the poco::thread virt memory will explode pretty fast (without join - with join its fine)....
with std::thread the virt memory increases in both cases until "0,250t" but stops there and the program runs forever..
so it looks like std::thread is using some hidden threadpool..

**Comment by aleks-f** [comment]
Since you are not checking the return value of pthread_create, the same thing happens as with Poco::Thread - pthread_create() fails after a while. As for putting thread pool inside thread, it makes one wonder what would the purpose for the ThreadPool class be ... pooling of threads that are already pooled internally? In any case, you have a workaround for what you are trying to do - call join() explicitly and life is good.

**Comment by DEvil0000** [comment]
i have edited my last comment (last paragraph and code return value).
i think the usage of the native_handle() is (kind of) wrong in my code and leads to std::thread.join() not working. but however pthread_detach is working as expected.
