### ISSUE TITLE
create a appveyor.yml file to build POCO on Windows similar to travis-ci

### ISSUE THREAD

**Issue by bufferoverflow** [pocoproject/poco#676]
[Appveyor](http://www.appveyor.com/) provides a similar service as travis-ci for Windows.
Would be nice to have this for POCO.

**Comment by aleks-f** [comment]
I agree, it would be great to have this. We should use both [Powershell](https://github.com/pocoproject/poco/blob/develop/buildwin.ps1) and [CMake](https://github.com/pocoproject/poco/blob/develop/CMakeLists.txt) builds to make sure they are continuously tested. I do have small improvements (relevant for [macchina.io](https://github.com/macchina-io/macchina.io), not poco) to do in buildwin.ps1 and I'd really like to phase out the [buildwin.cmd](https://github.com/pocoproject/poco/blob/develop/buildwin.cmd) monstrosity.

**Comment by bufferoverflow** [comment]
initial work is done, I close this issue.
