### ISSUE TITLE
Stale CMake file

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#677]
@bachp : What is the purpose of [this file](https://github.com/pocoproject/poco/blob/develop/cmake/PocoConfig.cmake)? If it is not used (I doubt it is, with 1.2.4 version being the last one sought), it should be removed.

**Comment by bachp** [comment]
The file is used by other packages that use CMake to find poco. I will remove it once the generated [CMake config](http://www.cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#config-file-packages) files are complete.

**Comment by bachp** [comment]
@aleks-f: This issue can be closed

**Comment by bachp** [comment]
@aleks-f ping, please close
