### ISSUE TITLE
OS X/iOS Support for universal libraries

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#680]
Received via email:

I am in the process of trying to get Poco to build universally for Mac OS X via the Homebrew package manager. I submitted a patch to Homebrew that does this, but they suggested I reach out to you instead. At this point, I am interested in writing a patch for Poco to accomplish this universal build. Would it be acceptable for me to submit a patch to the Poco project? Is this the correct email address to send the patch to?

Here is the relevant thread:

https://github.com/Homebrew/homebrew/pull/35839#issuecomment-70220149

**Comment by obiltschnig** [comment]
The GNU Make based build system used by POCO currently does not support universal builds.
It would be possible to add this, but it would require some changes to the build system. Specifically, the way compiler flags are passed to the compiler needs to be changed. Generally it’s easy to create an universal library by passing multiple -arch flags to the compiler (e.g., -arch i386 -arch x86_64). However, this will make the compiler complain with an error when it’s invoked to determine the dependencies. It may be possible to add this to the alternative CMake-based build system, though.

**Comment by bakercp** [comment]
+1 For a way to do this.  We over in openFrameworks land would also love to see this, as currently we go through a process of manually building FAT libs via `lipo` as well.  For reference:

https://github.com/openframeworks/openFrameworks/blob/master/scripts/apothecary/formulas/poco/poco.sh#L101-L130

That said, it's not a huge priority ...

**Comment by bakercp** [comment]
I guess a better argument would be based on our insane iOS fat lib build:

https://github.com/openframeworks/openFrameworks/blob/master/scripts/apothecary/formulas/poco/poco.sh#L158-L322

:)

**Comment by danoli3** [comment]
Yes please!! I never want to ```sed``` again...

**Comment by mikedld** [comment]
CMake build should work as is, with `-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"`.

**Comment by bachp** [comment]
I think with CMake this should be possible. If not already working, patches are welcome.

**Comment by Bjoe** [comment]
For the sake of completeness in `poco-1.9.1` and `develop` branch, the cmake build can build universal libraries. 
But unfortunately, it is not installing a framework. Is this mean by this issue here?
It is maybe a good idea to create an new issue "Add Framework support for OS X/iOS in cmake build system"?
