### ISSUE TITLE
"How to Contribute" page out of date

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#681]
Update the [How to Contribute](http://pocoproject.org/community/howtocontribute.html) page.

**Comment by bufferoverflow** [comment]
a CONTRIBUTING.md file might be an option here, please look at this: https://github.com/blog/1184-contributing-guidelines

**Comment by aleks-f** [comment]
thanks @bufferoverflow , see [CONTRIBUTING.md](https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md) 

@obiltschnig please close this when you remove or update the inaccurate page.
