### ISSUE TITLE
poco logger  how to record the source code line ?

### ISSUE THREAD

**Issue by lionm117** [pocoproject/poco#685]
hey ,guys , when i try to use logger to record some info into the log file ,  i wanna keep the code line ,and source file name  .  but  the result was never what i had expected . 
was it the way i used wrong ? or  it was a bug ? 
if it was not a bug , how could i  keep down  the souce code line number automatic  ?　
what do you think about it ?  

void Logger_test()
{
	AutoPtr<FileChannel> pchannel(new FileChannel);
	pchannel->setProperty("path", "sample file.log");
	pchannel->setProperty("rotation", "2000 K");
	pchannel->setProperty("archive", "timestamp");

	AutoPtr<PatternFormatter>  ptnfmt(new PatternFormatter("%L%H:%M:%S-%u-%U : %t"));
	AutoPtr<FormattingChannel> fmtchnl(new FormattingChannel(ptnfmt, pchannel));
	Logger::root().setChannel(fmtchnl);
	Logger& logger = Logger::get("TestLogger"); // inherits root channel 
	static string filename = "E:logger_poco.cpp";
	for (int i = 0; i < 1000; ++i)
	{
		logger.information("Testing SimpleFileChannel" ,filename , 60);
		Sleep(1500);
	}
}

int _tmain(int argc, _TCHAR* argv[])
{
	Logger_test();
	cout<<"this is the end"<<endl;
	int kk;
	cin >> kk;
	return 0;
}

expected  result:  " 16:55:17-60- E:logger_poco.cpp : Testing SimpleFileChannel "

result :  " 16:55:17-0- : Testing SimpleFileChannel "

**Comment by bachp** [comment]
Could the [poco_* convenience macros](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Logger.h#L520) be what you are looking for?

**Comment by DEvil0000** [comment]
For the normal printf like logger API this is possible but for LogStream I do not see a chance to get file and line into it.
1) I would suggest a flag in the Logger constructor/configuration if it should be included by default.
2) I would suggest to extend the following LogStream API calls with LINE/FILE parameters
priority()
error()
warning()
.....
