### ISSUE TITLE
iPhone Simulator link errors

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#692]
I am having these link errors when building an Xcode 6.1.1 project for Simulator that links with Poco 1.6.0. OSX is 10.10.1 Yosemite.

```
Undefined symbols for architecture x86_64:
  "_opendir$INODE64", referenced from:
      Poco::DirectoryIteratorImpl::DirectoryIteratorImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libPocoFoundation.a(DirectoryIterator.o)
  "_readdir$INODE64", referenced from:
      Poco::DirectoryIteratorImpl::next() in libPocoFoundation.a(DirectoryIterator.o)
ld: symbol(s) not found for architecture x86_64
```

Questions:
1. Why is x86_64 architecture needed for the simulator?
2. Why can't these symbols be resolved?

Thanks in advance.

**Comment by syedhali** [comment]
Newer devices run in 64-bit (iPhone 6 and later) instead of 32. I resolved this by running:
`make POCO_TARGET_OSARCH=x86_64 -s -j4`

then combined the i686 and x86_64 into a single lib with:
```
lipo -create i686/libPocoFoundation.31.dylib x86_64/libPocoFoundation.31.dylib universal/libPocoFoundation.31.dylib

...for each framework you need
```
