### ISSUE TITLE
bug in parsing name of attachment poco c++ 1.6.0

### ISSUE THREAD

**Issue by chepokabra** [pocoproject/poco#696]
Hello!
poco c++ has code in Net/src/MailMessage.cpp file:

		std::string getFileNameFromDisp(const std::string& str)
		{
			StringTokenizer st(str, ";=", StringTokenizer::TOK_IGNORE_EMPTY | StringTokenizer::TOK_TRIM);
			StringTokenizer::Iterator it = st.begin();
			StringTokenizer::Iterator end = st.end();
			for (; it != end; ++it) { if (*it == "filename") break; }
			if (it != end)
			{
				++it;
				if (it == end) return "";
				return *it;
			}
			return "";
		}
poco gets file name from Content-Type. So, I suposeed it should get it from "name" instead of "filename" property.
Example,
Content-Type: application/pdf; name="example.pdf" <-- see "name" is used instead of "filename".
So when poco parses attachment Poco::Net::StringPartSource::filename() returns empty string.
According RFC filename Content-Disposition should keep file name of attachment. (If I am not wrong).
Example,
Content-Disposition: attachment; filename="example.pdf"
But in fact file name usually exists in both Content-Disposition and Content-Type in different value names, "filename" and "name".

**Comment by aleks-f** [comment]
Thanks. Would you mind sending a pull request with a test for this?

**Comment by chepokabra** [comment]
I am glad to help you. So, please send me a pull request with a test for this.

**Comment by aleks-f** [comment]
I think we have a misunderstanding. Please see [contribution guidelines](https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md).

**Comment by chepokabra** [comment]
I am sorry. I am not familiar with git at all. And I have created an account here just to report exactly this bug.
Everything there is a need is to change next line of the function I posted above in Net/src/MailMessage.cpp file:
for (; it != end; ++it) { if (*it == "filename") break; }
to
for (; it != end; ++it) { if (*it == "name") break; }
i.e. "filename" replaced by "name". I have tested that change and it works for me.
I think merging from one branch to another takes more time then just replace "filename" to "name".

**Comment by obiltschnig** [comment]
The bug is elsewhere:

    NameValueCollection::ConstIterator it = header.begin();
    NameValueCollection::ConstIterator end = header.end();
    PartSource* pPS = _pMsg->createPartStore(tmp, 
        header[MailMessage::HEADER_CONTENT_TYPE], 
        getFileNameFromDisp(it->second));

So, the code assumes that the Content-Disposition header is always the first header.
