### ISSUE TITLE
PropertyFileConfiguration does not preserve comments

### ISSUE THREAD

**Issue by markculley** [pocoproject/poco#700]
1.6.0-all (2014-12-22)
"PropertyFileConfiguration does not preserve comments"

PropertyFileConfiguration supports comments, in a way. The documentation says...

> a line starting with a hash '#' or exclamation mark '!' is treated as a comment and ignored

Okay, that works as advertised. However, there is no mechanism to preserve comments in property files.  After a property file is loaded, the comment are discarded.  The use case is clear I think.  Comments in Read/Write property files are important since it is likely the user may edit a value to change runtime behavior. e.g. /etc/sudoers

**Comment by aleks-f** [comment]
Yes, it would be nice to have such feature. If you need it urgently, send us a pull request with changed code and tests. Otherwise, it will be done at a point yet to be determined.

**Comment by markculley** [comment]
No immediate need, but thanks for the offer!

**Comment by sergrak** [comment]
Sorry for necro-posting, but I see this pull request never got to the release. 
It was done by mistake, or there are some problems?

**Comment by aleks-f** [comment]
It went to the old develop branch, which was meant to become 2.0, but it was abandoned due to lack of resources to pursue it. If you want it released, send a pull to `devel` branch.

**Comment by sergrak** [comment]
Understood, thanks for clarification.
Will try to contribute when possible.
