### ISSUE TITLE
Poco::Data::SQLite data types

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#703]
I think that we can discuss more about the data types in SQLite about INTEGER
according to this link:
https://www.sqlite.org/datatype3.html#affinity
INTEGER are variable data types, so I can store 1 bit or 64 bit value as well.
The problem is when you read data with for example

Statement select(cSQLiteSession);
select << sSelectStatement;
select.execute();

The execute code use the call inside somewhere the function:
MetaColumn::ColumnDataType Utility::getColumnType(sqlite3_stmt\* pStmt, std::size_t pos)
that use _types to get the data type. INTEGER is mapped as int32_t and I think this is wrong because if you stored a 64bit timestamp in the INTEGER value you retrieve a wrong value

is it clear?

**Comment by micheleselea** [comment]
if you use Tuple for storing data from select the behavior it's ok and you can get 64 bit value from INTEGER field

**Comment by aleks-f** [comment]
Fix for this is easy but it will break some runtime semantics. @obiltschnig : 1.6.1 or 1.7.0?

**Comment by micheleselea** [comment]
Why do you think the solution brake semantics?

**Comment by aleks-f** [comment]
I mean that code like [this](https://github.com/pocoproject/poco/blob/develop/Data/SQLite/testsuite/src/SQLiteTest.cpp#L1936-L1943) will fail.

**Comment by aleks-f** [comment]
@obiltschnig : here's [the diff](https://gist.github.com/aleks-f/559603822f1a2f6c762e), whenever you get to it.

**Comment by micheleselea** [comment]
Already changed yesterday like you did in the diff file and was ok. The problem is that if you create an SQLite table with and INTEGER column ah you put inside a 64bit value it's works good unless you use the Recordset directly that make a wrong conversion. With standard select+tuple you do not have the problem

**Comment by micheleselea** [comment]
The patch for INTEGER to int64 for SQLITE is not in 1.6.1 version and I think is not in the trunk. Do you plan to merge it in the trunk?

**Comment by obiltschnig** [comment]
TODO: fix in upcoming 1.9 release.
