### ISSUE TITLE
Poco Sockets: Exceptions on non-exceptional program flow

### ISSUE THREAD

**Issue by Incubbus** [pocoproject/poco#704]
For Poco Sockets which perform non-blocking I/O, if the operation does not complete immediately a `Poco::IOException` with error code `POCO_EWOULDBLOCK` is thrown.
Indicating that the operation is still in progress is **not** an exceptional case.

_Using exceptions to direct normal program flow is considered a major design flaw_ (not only because of the performance hit in loops, etc), which is done here.

Example cases:
- When calling `Poco::Net::ServerSocket::acceptConnection()` on a _non-blocking Socket_, an `IOException` with code() `POCO_EWOULDBLOCK` is thrown. This is a **non-exceptional** condition.
- This is also true for any other non-blocking I/O-Operation on non-blocking sockets, where you would expect it to return instead of throwing an exception, because returning is the expected behaviour.

Consider returning -1 or any other code like POCO_EWOULDBLOCK to indicate WOULD_BLOCK-ing behaviour.

**Comment by aleks-f** [comment]
You can do it without exception on POCO_EWOULDBLOCK:
```
Poco::Net::ServerSocket s;
Poco::Timespan span(250000);
if (s.poll(span, Socket::SELECT_READ))
{
  StreamSocket ss = s.acceptConnection();
  // ...
}
```

But perhaps we could change [SocketImpl::acceptConnection()](https://github.com/pocoproject/poco/blob/develop/Net/src/SocketImpl.cpp#L85-L86) to
```
if (lastError() == POCO_EWOULDBLOCK) return -1;
error() // will throw
return 0;
```
I'll leave the decision to @obiltschnig

**Comment by Incubbus** [comment]
Thank you for the fast answer.

In my opinion, changing the implementation would make coding feel and look cleaner and more convenient. (But that's only my opinion!)

**Comment by Incubbus** [comment]
It's been a while.
Is there already an decision made?

**Comment by aleks-f** [comment]
@obiltschnig ?

**Comment by obiltschnig** [comment]
If the socket has been set to nonblocking we could return an uninitialized `StreamSocket`. However, I don't really like that, as even creating an uninitialized `StreamSocket` requires creating a `StreamSocketImpl` object on the heap. For a blocking socket, nothing will change.
We could also use `Poco::Optional` to wrap the StreamSocket object, and optimize the `Poco::Optional` implementation not to default-construct the object if it's unspecified (like `std::optional`, which, unfortunately, is C++17. For backwards compatibility, we may do that in a separate method (`acceptConnectionNB()`).

**Comment by SmileGobo** [comment]
I have a similar situation when sending in non-blocking mode. Calling sendBytes without poll/select. I get an exception for the POCO_EWOULDBLOCK error code
Occurs on Win7. Is there a guarantee that there will be no such error when using select/poll?
