### ISSUE TITLE
Error building with ENABLE_UTIL=ON and ENABLE_XML=OFF

### ISSUE THREAD

**Issue by Gamadril** [pocoproject/poco#705]
I don't need XML, but I do need UTIL for a command-line application / daemon. But seems that UTIL depends on XML. 

Building on OSX using cmake 3.0.2 with following configuration:
 ```
cmake -DENABLE_MONGODB=OFF -DENABLE_XML=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA=OFF -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_ZIP=OFF -DENABLE_PAGECOMPILER=OFF -DENABLE_PAGECOMPILER_FILE2PAGE=OFF ..
```
make fails:
```
... /poco/Util/include/Poco/Util/XMLConfiguration.h:30:10: fatal error: 
      'Poco/DOM/Document.h' file not found
#include "Poco/DOM/Document.h"
         ^
1 error generated.
make[2]: *** [Util/CMakeFiles/Util.dir/src/Application.cpp.o] Error 1
make[1]: *** [Util/CMakeFiles/Util.dir/all] Error 2
make: *** [all] Error 2

```
Tested with 1.6.0 and git clone

**Comment by bachp** [comment]
Dependencies between components is not modeled in the build system at the moment.

It could be modeled using [CMakeDependentOption](http://www.cmake.org/cmake/help/git-master/module/CMakeDependentOption.html?highlight=dependent) or by just printing an error if Util is enabled but XML is not.

It might be worth to add at least such a check.

**Comment by aleks-f** [comment]
To compile Util without XML and JSON, [define POCO_UTIL_NO_JSONCONFIGURATION and POCO_UTIL_NO_XMLCONFIGURATION](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Config.h#L144-L153)

**Comment by Gamadril** [comment]
uncommented in Config.h
```
#define POCO_UTIL_NO_INIFILECONFIGURATION
#define POCO_UTIL_NO_XMLCONFIGURATION
```
still get an error:
```
Linking CXX shared library ../lib/libPocoUtil.dylib
ld: library not found for -lXML
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libPocoUtil.30.dylib] Error 1
make[1]: *** [Util/CMakeFiles/Util.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by bachp** [comment]
Could you try adding [add_definitions](http://www.cmake.org/cmake/help/git-master/command/add_definitions.html?highlight=add_defi#command:add_definitions)(-DPOCO_UTIL_NO_JSONCONFIGURATION -DPOCO_UTIL_NO_XMLCONFIGURATION) to [Util/CMakeLists.txt](https://github.com/pocoproject/poco/blob/develop/Util/CMakeLists.txt#L17) and remove XML and JSON from [here](https://github.com/pocoproject/poco/blob/develop/Util/CMakeLists.txt#L27).

If this works I will change the CMake file to detect if XML or JSON was enabled and set the definitions accordingly.

**Comment by Gamadril** [comment]
Got errors about macro redefinition, so reverted Config.h, modified Util/CMakeLists.txt as suggested - build runs without errors now. Thanks

**Comment by aleks-f** [comment]
I have [added](https://github.com/pocoproject/poco/commit/74c24a3789bda61ca7441c67496eb6ca5e570529) support for this in the original build system but the defines still have to be supplied to the Util make to get it to do the right thing. Will look at how to automate it further through configure script.

**Comment by aleks-f** [comment]
Also related to #134

**Comment by Gamadril** [comment]
This is how it works for me. Tested with poco-1.6.1 branch.
CMakeLists.txt:
```
if(ENABLE_XML)
  add_subdirectory(XML)
  list(APPEND Poco_COMPONENTS "XML")
else ()
  add_definitions( -DPOCO_UTIL_NO_XMLCONFIGURATION )
  endif()
if(ENABLE_JSON)
  add_subdirectory(JSON)
  list(APPEND Poco_COMPONENTS "JSON")
else ()
  add_definitions( -DPOCO_UTIL_NO_JSONCONFIGURATION )
endif()
```
Util/CMakeLists.txt:
```
#target_link_libraries( "${LIBNAME}" JSON XML Foundation)
target_link_libraries( "${LIBNAME}" Foundation)
if (ENABLE_XML)
	target_link_libraries( "${LIBNAME}" XML)
endif()
if (ENABLE_JSON)
	target_link_libraries( "${LIBNAME}" JSON)
endif()
```

**Comment by bachp** [comment]
Your suggestion looks good.
One improvement would be to move the else clause with the ``add_definitions( -DPOCO_UTIL_NO_* )`` definitions to the Util/CMakeLists.txt as it is Util specifc.

I would be glad to see a pull request for your changes. :)

**Comment by bachp** [comment]
I think this issue is solved.
Please close

**Comment by Popovich** [comment]
And what about PocoUtilConfig.cmake? https://github.com/pocoproject/poco/blob/develop/Util/cmake/PocoUtilConfig.cmake#L3
