### ISSUE TITLE
Poco::Dynamic::Var memory leak?

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#709]
I found a strange behavior of Poco::Dynamic::Var that seams to cause a memory leak.
If you do something like:

Poco::Dynamic::Var var1;
var1 = std::string("test1");
Poco::Dynamic::Var var2;
var2 = std::string("test2");
var1.swap(var2);

the code works well without leak.

But if I do this:
Poco::Dynamic::Var var1;
var1 = std::string("test1");
var1 = std::string("test2");

I got a memory leak. I've compiled without the POCO_NO_SOO define so my config.h is
//define POCO_NO_SOO

Do you have the same behavior? or I'm missing something?

**Comment by aleks-f** [comment]
@micheleselea POCO_NO_SOO is not sufficiently tested and not recommended for production yet, but keep in mind that with it defined, new will not actually allocate on the heap, so maybe a false positive from the tool? On the other side, it is possible that the manual destructor call is somehow skipped and leak is for real, from inside the string that was not destructed.

**Comment by micheleselea** [comment]
I don't know because is a long time I found that and I can remember well. Anyway I made the test of POCO_NO_SOO  for you :) I think it's at least 2 year I use in production environment without problem after fixing using swap
