### ISSUE TITLE
Make install on CYGWIN doesn't copy cygPoco*.dll

### ISSUE THREAD

**Issue by dirvens** [pocoproject/poco#710]
When executing a "make install" using Cygwin with Poco 1.6.0, the install target doesn't copy over the cygPoco* dlls. These are the actual shared libs.

**Comment by aleks-f** [comment]
@dirvens : can you please test if this [fix](https://github.com/pocoproject/poco/commit/291a0fc8fc059cccbc54ed5d653400f86190bd45) works for you?
