### ISSUE TITLE
gcc error

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#711]
These [compile errors](https://travis-ci.org/pocoproject/poco/jobs/50214187) baffle me. Why does this code fail to compile?
``` c++
void toJSON(const std::string& value, std::ostream& out, bool wrap)
{
  if (wrap) out << '"';
// ...
}
```

Here's the error:

```
src/JSONString.cpp:42:16: error: no match for `operator<<' (operand types are `s
td::ostream {aka std::basic_ostream<char>}' and `char')
  if (wrap) out << '"';
                ^
```

**Comment by PureAbstract** [comment]
I haven't had a chance to try it myself, but you might Try adding a ```#include <ostream>``` in JSONString.cpp?

**Comment by aleks-f** [comment]
indeed, that's what it was. I would've sworn I have put it there at some point but obviously I did not. Thanks for your help.

**Comment by PureAbstract** [comment]
@aleks-f No problem - happy to help :)
