### ISSUE TITLE
Travis builds

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#727]
This [Travis build](https://travis-ci.org/pocoproject/poco/jobs/52839243) is failing and I don't know why. It builds fine on Mac and Linux, clang and gcc on my local machines.

Another annoyance are these warnings in Travis builds:
```
/home/travis/build/pocoproject/poco/Foundation/include/Poco/Bugcheck.h:152:24: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
```
coming from [here](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Bugcheck.h#L151-L153).  Does anyone know what is the right incantation there? Without that diag off, there's an avalanche of unused warnings on newer gcc versions.

**Comment by obiltschnig** [comment]
The web-based Travis log viewer has a limit of 10000 lines. You'll need to download the log file (there's a button in the top right).

** Building shared executable (debug)      /home/travis/build/pocoproject/poco/NetSSL_OpenSSL/testsuite/bin/Linux/x86_64/testrunnerd
/home/travis/build/pocoproject/poco/NetSSL_OpenSSL/testsuite/obj/Linux/x86_64/debug_shared/NetSSLTestSuite.o: In function `NetSSLTestSuite::suite()':
/home/travis/build/pocoproject/poco/NetSSL_OpenSSL/testsuite/src/NetSSLTestSuite.cpp:29: undefined reference to `WebSocketTestSuite::suite()'
collect2: ld returned 1 exit status

**Comment by aleks-f** [comment]
I don't understand where is that [error](https://github.com/pocoproject/poco/blob/develop/NetSSL_OpenSSL/testsuite/Makefile#L21) coming from; I can not find any [caches](https://travis-ci.org/pocoproject/poco/caches) on travis.

**Comment by obiltschnig** [comment]
It seems to have gone away on the latest build. But we now have lots of warnings in ODBC:

** Compiling src/Binder.cpp (release, shared)
In file included from include/Poco/Data/ODBC/SessionImpl.h:26:0,
                 from include/Poco/Data/ODBC/ODBCStatementImpl.h:24,
                 from src/ODBCStatementImpl.cpp:17:
include/Poco/Data/ODBC/Binder.h: In member function ‘void Poco::Data::ODBC::Binder::bindImplContainerDate(std::size_t, const C&, Poco::Data::ODBC::Binder::Direction) [with C = std::vector<Poco::Data::Date>, std::size_t = long unsigned int, Poco::Data::ODBC::Binder::Direction = Poco::Data::AbstractBinder::Direction]’:
include/Poco/Data/ODBC/Binder.h:1426:37:   instantiated from here
include/Poco/Data/ODBC/Binder.h:757:14: warning: unused variable ‘size’ [-Wunused-variable]

**Comment by obiltschnig** [comment]
Btw, I have enabled the diag pragma only for GCC >= 4.8.

**Comment by obiltschnig** [comment]
Build is fine again.
