### ISSUE TITLE
which file to to load  "Array::Ptr "   typedef  ?  

### ISSUE THREAD

**Issue by lion117** [pocoproject/poco#728]
hey guys , i had met a issue which made me thought i was a idiot .  
as i wanna take used of poco::json to parse json files  which did not have much  document about how to used it ,  i did a demo fellow the tutorial in the authorized  document . like following code .

but in the VS 2013 compiling ,  IDE always hint could not recognize  "Array::Ptr" 
i thought this should be a typedef  definition  . but i could not locate where the hell it was . 
which file did i misss to add ? could you do me a favor ?   

  appreciated  to recommend some  tutorial about how to use json  
# include "Poco/JSON/Handler.h"
# include "Poco/JSON/Parser.h"
# include "Poco/JSON/PrintHandler.h"
# include "Poco/JSON/Array.h"
# include "Poco/JSON/Object.h"
# include "Poco/JSON/ParseHandler.h"
# include "Poco/Dynamic/Var.h"

using namespace Poco::JSON;
using namespace Poco::Dynamic;
using namespace Poco;

```
std::string json = "[ {\"test\" : 0}, { \"test1\" : [1, 2, 3], \"test2\" : 4 } ]";
Parser parser;
Var result = parser.parse(json);
```

/////////////////////////////////////////////////////////////////////////////////
// could not find the array::Ptr    typedef 

```
Array::Ptr  arr = result.extract<Array::Ptr>();
```

////////////////////////////////////////////////////////////////////////////////
    Object::Ptr object = arr->getObject(0); // object == {\"test\" : 0}
    int i = object->getValue<int>("test"); // i == 0;
    Object::Ptr subObject = *arr->getObject(1); // subObject == {\"test\" : 0}
    Array subArr::Ptr = subObject->getArray("test1"); // subArr == [1, 2, 3]
        i = result = subArr->get(0); // i == 1;

```
    // copy/convert to Poco::Dynamic::Array
    Poco::Dynamic::Array da = *arr;
    i = da[0]["test"];     // i == 0
    i = da[1]["test1"][1]; // i == 2
    i = da[1]["test2"];    // i == 4
```

**Comment by aleks-f** [comment]
There is [Poco::Array](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Array.h) that is conflicting because you are using both Poco and Poco::JSON namespaces. Fully qualify the JSON one and you'll be fine:
```
POCO::JSON::Array::Ptr
```
