### ISSUE TITLE
Compilation failures for vs2008 (vc90)

### ISSUE THREAD

**Issue by keeely** [pocoproject/poco#729]
Here's the 1.6.0 release:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++ Building [Foundation_vs90.vcproj]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Microsoft (R) Visual Studio Version 9.0.21022.8.
Copyright (C) Microsoft Corp. All rights reserved.
1>------ Build started: Project: Foundation, Configuration: debug_shared Win32 ------
1>Performing Custom Build Step
1>MC: Compiling c:\thirdparty\poco\poco-1.6.0\Foundation\src\pocomsg.mc
1>c:\thirdparty\poco\poco-1.6.0\Foundation\src\pocomsg.mc(89) : error : unable to open output file - c:\thirdparty\poco\
poco-1.6.0\Foundation\src\.\MSG00001.bin
1>Project : error PRJ0019: A tool returned an error code from "Performing Custom Build Step"
1>Build log was saved at "file://c:\thirdparty\poco\poco-1.6.0\Foundation\obj\Foundation\debug_shared\BuildLog.htm"
1>Foundation - 2 error(s), 0 warning(s)
2>------ Build started: Project: TestLibrary, Configuration: debug_shared Win32 ------
2>Linking...
2>LINK : fatal error LNK1104: cannot open file 'PocoFoundationd.lib'
2>Build log was saved at "file://c:\thirdparty\poco\poco-1.6.0\Foundation\testsuite\obj\TestLibrary\debug_shared\BuildLo
g.htm"
2>TestLibrary - 1 error(s), 0 warning(s)
3>------ Build started: Project: TestSuite, Configuration: debug_shared Win32 ------
3>Linking...
3>LINK : fatal error LNK1104: cannot open file 'PocoFoundationd.lib'
3>Build log was saved at "file://c:\thirdparty\poco\poco-1.6.0\Foundation\testsuite\obj\TestSuite\debug_shared\BuildLog.
htm"
3>TestSuite - 1 error(s), 0 warning(s)
========== Build: 0 succeeded, 3 failed, 1 up-to-date, 0 skipped ==========

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX  BUILD FAILED. EXITING. XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Here's github tip,3/3/2015: 5dea080b0b3bb2cd93555205ae3a6f531a3735ff.
Completely different error:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++ Building [Foundation_vs90.vcproj]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Microsoft (R) Visual Studio Version 9.0.21022.8.
Copyright (C) Microsoft Corp. All rights reserved.
1>------ Build started: Project: Foundation, Configuration: debug_shared Win32 ------
1>Linking...
1>   Creating library ..\lib\PocoFoundationd.lib and object ..\lib\PocoFoundationd.exp
1>Embedding manifest...
1>Build log was saved at "file://c:\thirdparty\poco\poco-develop\poco-develop\Foundation\obj\debug_shared\BuildLog.htm"
1>Foundation - 0 error(s), 0 warning(s)
2>------ Build started: Project: TestSuite, Configuration: debug_shared Win32 ------
2>Linking...
2>FoundationTestSuite.obj : error LNK2019: unresolved external symbol "public: static class CppUnit::Test * __cdecl Buff
erTestSuite::suite(void)" (?suite@BufferTestSuite@@SAPAVTest@CppUnit@@XZ) referenced in function "public: static class C
ppUnit::Test * __cdecl FoundationTestSuite::suite(void)" (?suite@FoundationTestSuite@@SAPAVTest@CppUnit@@XZ)
2>bin\TestSuited.exe : fatal error LNK1120: 1 unresolved externals
2>Build log was saved at "file://c:\thirdparty\poco\poco-develop\poco-develop\Foundation\testsuite\obj\TestSuite\debug_s
hared\BuildLog.htm"
2>TestSuite - 2 error(s), 0 warning(s)
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX  BUILD FAILED. EXITING. XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by aleks-f** [comment]
Just built with VS2008 on windows 7 and it builds fine. Look at your error logs and build system settings.

**Comment by keeely** [comment]
There is definitely something going on.  I installed a fresh development environment today, comprising these ISOs downloaded off MSDN:
en_windows_7_ultimate_with_sp1_x86_dvd_u_677460.iso
en_visual_studio_2008_professional_x86_dvd_x14-26326.iso (full install).

I get output as below.  Interestingly, this only happens for a clean build.  If I re-run the build after the error, it seems to get further.  Please post systeminfo and your exact studio version.

I tried this as admin console window, and non-admin console window and get much the same thing.

c:\> buildwin.cmd 90 build
<snip>

Linking...
   Creating library ..\..\lib\WinTestRunnerd.lib and object ..\..\lib\WinTestRun
nerd.exp
Embedding manifest...
Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
Copyright (C) Microsoft Corporation.  All rights reserved.
LINK : fatal error LNK1000: Internal error during IncrBuildImage
  Version 9.00.21022.08
  ExceptionCode            = C0000005
  ExceptionFlags           = 00000000
  ExceptionAddress         = 003FFCF7 (00380000) "C:\Program Files\Microsoft Vis
ual Studio 9.0\VC\BIN\link.exe"
  NumberParameters         = 00000002
  ExceptionInformation[ 0] = 00000000
  ExceptionInformation[ 1] = 00A3D670
CONTEXT:
  Eax    = 401380F4  Esp    = 0024F1D4
  Ebx    = 40008178  Ebp    = 0024F1FC
  Ecx    = 00A3D670  Esi    = 40137F64
  Edx    = 0024F1EC  Edi    = 0038D6C0
  Eip    = 003FFCF7  EFlags = 00010246
  SegCs  = 0000001B  SegDs  = 00000023
  SegSs  = 00000023  SegEs  = 00000023
  SegFs  = 0000003B  SegGs  = 00000000
  Dr0    = 00000000  Dr3    = 00000000
  Dr1    = 00000000  Dr6    = 00000000
  Dr2    = 00000000  Dr7    = 00000000
Build log was saved at "file://c:\poco-1.6.0\CppUnit\WinTestRunner\obj\debug_sha
red\BuildLog.htm"
WinTestRunner - 1 error(s), 0 warning(s)
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX  BUILD FAILED. EXITING. XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by aleks-f** [comment]
That's a VS 90 bug, I've seen it many tines

**Comment by keeely** [comment]
Is there a work-around?  I've never seen this bug.  I was wanting to use VS 90, as I also use it to compile Python extensions :-(.

**Comment by keeely** [comment]
I have a machine where I'm reproducing this every build.  It doesn't appear to be a random thing.
