### ISSUE TITLE
Would be useful to have a WebSocket::receiveFrame that takes a resizable buffer

### ISSUE THREAD

**Issue by tml1024** [pocoproject/poco#733]
For instance:

int receiveFrame(Poco::Buffer<char>& buffer, int& flags)

So that one wouldn't need to know in advance what the maximum frame size to receive is.

Would you be interested in an implementation of a such? How "clean" does it need to be? My first quick hack has a WebSocketImpl::receiveBytes(Poco::Buffer<char>& buffer, int) that is basically a copy-paste job of the WebSocketImpl::receiveBytes(void\* buffer, int length, int), with the obvious small changes. It resizes the buffer when the payloadLength is known. I tried to factor out the common code to read the header and to read the rest, but it got a bit ugly, having to pass so many state variables around, hmm.

**Comment by aleks-f** [comment]
I'd just cut/paste code from WebSocketImpl::receiveBytes(void*,int,int) to WebSocketImpl::receiveBytes(Poco::Buffer&) and implement former in terms of latter. I.e.,receiveBytes(void*,int,int) calls receiveBytes(Poco::Buffer&). To preserve semantics, maybe have something like receiveBytes(Poco::Buffer&, int maxSize = MAX_WS_BUF_SIZE) to limit frame length as it does now and prevent Buffer from growing uncontrollably.
Maybe we could even promote Socket::receiveBytes(Poco::Buffer&) up the hierarchy?
@obiltschnig ?

**Comment by tml1024** [comment]
OK. I already did it in a different way, factored out a receiceHeader() (that reads *only* the header) and receivePayload() function, but I will see how your approach works out. Expect a pull request in a few days, busy with another thing now.

**Comment by anton19286** [comment]
Is it possible to store length-related bytes of header in WebSocketImpl to make possible to call receiveBytes again with resized buffer after "Insufficient buffer for payload size" exception?

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/08a748dae166e9aa735ae90fc5d91a420dc132f2
