### ISSUE TITLE
Problem using InflatingOutputStream

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#744]
I receive a zip file over the network:
```c++
std::vector<Poco::UInt8> data = gv.readBlock(addr, size);
```
This works fine and I can expand and read the contents of the zip file:
```c++
Poco::FileOutputStream fos("C:\\temp\\genicam.zip");
fos.write(reinterpret_cast<const char*>(&data[0]), data.size());
fos.close();
```

This, however, fails with IOException:
```c++
std::string str(data.begin(), data.end());
std::stringstream buffer(str);
std::stringstream buffer2;
Poco::InflatingOutputStream inflater(buffer2, Poco::InflatingStreamBuf::STREAM_ZIP);
Poco::StreamCopier::copyStream(buffer, inflater);
inflater.close(); // throws IOException
std::string xml;
buffer2 >> xml;
```
Where am I going wrong?

**Comment by obiltschnig** [comment]
Poco::InflatingOutputStream does not handle Zip files. You'll need to use the Zip library for that. Poco::InflatingStreamBuf::STREAM_ZIP is used for reading compressed data contained in Zip files, not for entire Zip files.

**Comment by aleks-f** [comment]
Ah, I see. Like [this](https://github.com/pocoproject/poco/blob/develop/Zip/testsuite/src/ZipTest.cpp#L70).
