### ISSUE TITLE
compile poco with static lib  technique query 

### ISSUE THREAD

**Issue by lionm117** [pocoproject/poco#745]
#description 

poco is awesome library which provide two kind versions for calling : static lib and dynamic lib . 
when i use poco static lib  in VS2008, it only require two step config that i could embed poco code into my program and pass through compiling .   it was a  surprise and hommization

> 1. Project->properties->c/c++->general->additional include directories
> 2.  Project->properties->linker->general->additional library directories

generally speaking ,  calling static lib would require three steps config , the left one is : 
 > 3. Project->properties->linker->input->additional additional dependencies

in my own static lib , if i did not  execute the third operation , the compiler would report :  
>  error LNK2019: unresolved external symbol.....    something like that 

# summary 
to be honest   , ** two steps** that would load the **static lib** and pass through compiler  is more **convenient** and **comfortable**  for developer  , especially there are lots of static libs .  i prefer to eat my keyboard than **tping the lib names one by one** .  

# question 
> are there any **technique** or **black magic**  that i did know**which could have the static lib** i made be called by two  steps like poco lib did ?

**Comment by obiltschnig** [comment]
Not black magic, but platform/compiler specific pragma:

Add

    #pragma comment(lib, "YourLib.lib") 

to one of your library headers. However, make sure that the #pragma is only enabled if you're including the header from a client, not when actually building the library. In the POCO libraries, we generally use the following boilerplate code, which also takes care of __declspec(dllexport/dllimport) for DLLs:

    //
    // The following block is the standard way of creating macros which make exporting 
    // from a DLL simpler. All files within this DLL are compiled with the XML_EXPORTS
    // symbol defined on the command line. this symbol should not be defined on any project
    // that uses this DLL. This way any other project whose source files include this file see 
    // XML_API functions as being imported from a DLL, wheras this DLL sees symbols
    // defined with this macro as being exported.
    //
    #if defined(_WIN32) && defined(POCO_DLL)
        #if defined(XML_EXPORTS)
            #define XML_API __declspec(dllexport)
        #else
            #define XML_API __declspec(dllimport)   
        #endif
    #endif


    #if !defined(XML_API)
        #if !defined(POCO_NO_GCC_API_ATTRIBUTE) && defined (__GNUC__) && (__GNUC__ >= 4)
            #define XML_API __attribute__ ((visibility ("default")))
        #else
            #define XML_API
        #endif
    #endif


    //
    // Automatically link XML library.
    //
    #if defined(_MSC_VER)
        #if !defined(POCO_NO_AUTOMATIC_LIBS) && !defined(XML_EXPORTS)
            #pragma comment(lib, "PocoXML" POCO_LIB_SUFFIX)
        #endif
    #endif

**Comment by lionm117** [comment]
yeah ,you are right , add 
>  #pragma comment(lib, "YourLib.lib")    // declaration 
to the head of library could work .   

but at the beginning  , when i tried  to**find such declaration in poco source code** (.h  and .cpp ) , i **found noting** .   this  was why i rose the issue .

> the technique of exporting and import dll , i had locate the code block  which is really smart design .  it look like something black magic  if i don't know the mechanism . poco bring  me lots of inspiration 

 ##thanks
