### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by jano42** [pocoproject/poco#747]
I propose you a possible enhancement on command line processing.

In current Poco version, the command line options are
* starting by "/" on Windows
* starting by "-" on Unix system

It would be nice if the two starting chars could be used.
In fact that options could be processed on any operating system using a "-" or a "/".

In my software we are chaging from boost::program_options to Poco, but boost is using one or other starting flag.

**Comment by obiltschnig** [comment]
At least on Windows, you can enable Unix-style options (but not both) via Application::setUnixOptions(). I don't think anyone using a Unix platform will want to use Windows-style options, though.

**Comment by jano42** [comment]
OK. Good idea.
Regards
