### ISSUE TITLE
how to assign char string  to SharePtr<char>  as soon as possible 

### ISSUE THREAD

**Issue by lion117** [pocoproject/poco#756]
I try to apply smart pointer to robust the software when programming . 
character string operation was the most headache which was easy to cause memory leak , at the same time , i had get tired to new a memory space each time  when pass parameter  in function .  apply smart pointer would be a good solution for me . 
# document issue report

there is something wrong in [authorized tutorial](http://pocoproject.org/slides/030-MemoryManagement.pdf)  

``` c++
template <class C>  
class ArrayReleasePolicy  
{  
public:  
    static void release(C* pObj)  
        /// Delete the object.  
        /// Note that pObj can be 0.  
    {  
        delete [] pObj;  
    }  
};  
char* pStr = new char[100];  
SharedPtr<char, Poco::ReferenceCounter, ArrayReleasePolicy> p(pStr);     // **error line** 
```

missing  template type at the third parameter position 

``` c++
char* pStr = new char[100];  
SharedPtr<char, Poco::ReferenceCounter, ArrayReleasePolicy<char>> p(pStr);     // correct  line 
```
# assign char string to SharePtr

`question`

> correct way but too many code 
> 
> ``` c++
> char *pchar = new char[11];
> pchar = "hello world";
> SharedPtr<char , ReferenceCounter, ReleaseArrayPolicy<char> > ptr_smart(new char[11]);
> memcpy(ptr_smart , pchar ,11);
> ```
> 
> upper operation looks not **so smart**  and **so OOP** , although it could work ,  are there any more  simple and fast way  to assigning  a string to the smart  pointer ?  like following code lines 

``` C++
// method one :
char *pstr 1 = "hello wolld";
SharedPtr<char , ReferenceCounter, ReleaseArrayPolicy<char> > ptr_smart(new char[11]);
ptr_smart = pstr1;
// method 2
SharedPtr<char , ReferenceCounter, ReleaseArrayPolicy<char> > ptr_smart(new char[11]);
ptr_smart = "hello world"
```

**Comment by obiltschnig** [comment]
What's wrong with simply using std::string or std::vector<char>?

**Comment by aleks-f** [comment]
OK, so documentation is indeed inaccurate, here's the code that compiles (note that you don't need your own release policy):
```
#include "Poco/SharedPtr.h"

char* pStr = new char[100];
SharedPtr<char, Poco::ReferenceCounter, Poco::ReleaseArrayPolicy<char> > p(pStr);
```
But, it is an exercise in futility indeed. Simplify your life and use std::string.

**Comment by lionm117** [comment]
#why not using std::string
in the **low level network programing** (like *UDP/TCP* ),  the interface usually  passes char pointer , and string lenth  in ,  in the char string structure  , sometimes there were some **unwelcome bytes**  like '0x00' for stl::string , 
if use stl:;string  to store data , it may **casue data lost**  as there are some  "0x00" bytes mixed in the char string. 

#conclusion 
> in the **high level programing** , std;;string would be **ok  and very convenient** .no more memory leak issue .  but in low level programing ,especially refering  communication with embed-system  , which usually prefer to customized **byte** protocol ,  in case of data memory release  or rewrited,  **passing parameters and storing data** had became  headache things . 
like followed code :
```c++
 // to prevent pdata 's data from releaseing , each funcitons which refer char string 
// have to new a memory to store datas 
bool  OnRecieveData( char * pdata , int nlenth) 
{
     char * strore_data = new char[nlenth];
     memset(store_data , 0, nlenth);
     memcpy(store_data , pdata , nlenth );      
    // @ do other things 
}
```

although i had define a class  which have similar property and interface  like std;:string , at the same time  , it could compatible with  "0x00" , but the efficiency is not so good .

**Comment by PureAbstract** [comment]
`std::string` copes just fine with 0x00 bytes - always has done.
```
bool On ReceiveData( char *pdata, int nlength )
{
   std::string store_data( pdata, nlength );
   // @do other things.
}
```

**Comment by lionm117** [comment]
if  pdata    is   "0x01 **0x00** 0x01 0x02 " , std::string would abandon the right data of  0x00 as std::string treate **0x00** as the end mark. 

> as low level  network communication take hex byte to define communication protocol , there is lots of data like that to deal.  std;;string is not so fitful .  
what i could recall is that java have a lib named "ByteString" to deal  such issue , but i did find C++ library to do that

**Comment by aleks-f** [comment]
Really? And how exactly does char* treat 0x00 to make it favorable to std::string? Please find a C++ compiler, try this with your sequence of bytes and let us know the result:
```
void OnReceiveData(char *pdata, int nlength)
{
	std::string store_data(pdata, nlength);
	std::cout << store_data.size() << std::endl;
	for (auto it : store_data)
		std::cout << (unsigned) it << std::endl;
}
```

**Comment by lionm117** [comment]
sorry , my fault , I realized that i did not master stl::string very well  after check std::string constructor dict . **appreciated your patience and help and  deeply sorry for my low grade fault .**

> from sequence (5)	string (const char* s, size_t n);
Construct string object:  Copies the null-terminated character sequence (C-string) pointed by s.

**thanks to pointing out my stupid behave ,**
