### ISSUE TITLE
ServerApplication close console bug

### ISSUE THREAD

**Issue by jano42** [pocoproject/poco#758]
# The bug:

The issue is reproduced in Windows environnement

I've created a ServerApplication. 
The aim is to run either as a service or directly from a console.

If I run the application in a console, then terminate it with "Ctrl+C" all is OK.
If I run the application in a console, then terminate it by **closing the window then  neither my last lines are not called, nor uninitialize overidden uninitialize method**.

The same handler is called after Ctrl+C or closing window; but behavior is not !
# Reproduce it

**It is easy to reproduce.**

I've opened the "Util\samples\SampleServer" sample (from poco-1.6.0-all)

I just add log lines (step 1 to 3) to highligth the bug.

```
    int main(const ArgVec& args)
    {
        if (!_helpRequested)
        {
            TaskManager tm;
            tm.start(new SampleTask);
            waitForTerminationRequest();
            logger().information("STEP 1"); 
            tm.cancelAll();
            logger().information("STEP 2");
            tm.joinAll();
        }
        logger().information("STEP 3");
        return Application::EXIT_OK;
    }
```
# The result:

I've just let running the application for 10-15 seconds, to have task outputs before closing it.
Here are the log files (given with using SampleServer.properties : provided with poco)
## Ending by Ctrl+C

```
Application: [Information] starting up
Application: [Information] busy doing nothing... 0d 00:00:05.087
Application: [Information] busy doing nothing... 0d 00:00:10.108
Application: [Information] STEP 1
Application: [Information] STEP 2
Application: [Information] STEP 3
Application: [Information] shutting down
```
## Ending by closing Window

```
Application: [Information] starting up
Application: [Information] busy doing nothing... 0d 00:00:05.046
Application: [Information] busy doing nothing... 0d 00:00:10.068
```

Neither the Step1 to 3 are called, nor  the uninitialize overriding method 

```
    void uninitialize()
    {
        logger().information("shutting down");
        ServerApplication::uninitialize();
    }
```

Using poco-1.6.0 complete edition, with Windows 7 64bits (and Windows 8.1pro 64) and VisualStudio 2013

**Comment by rafzi** [comment]
Closing the console fires the CTRL_CLOSE_EVENT. I am only talking about this event here.

A console handler can be used to do final cleanup, but if it returns the OS will kill the process. In practice the process is also killed if the handler does not return for some time. This is 5 seconds on my system (Win 8.1 64-bit).

ServerApplication::ConsoleCtrlHandler is implementing this handler in Poco. It waits on the Poco::Event _terminated before returning.

ServerApplication::waitForTerminationRequest does set the event _terminated before returning, so from this point on the OS may kill the process at any time.

Maybe it would be better to set _terminated only in the destructor of ServerApplication, to give the application time to shut down properly.

Source: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683242(v=vs.85).aspx

**Comment by jano42** [comment]
I completly agree with your idea.

In case of Ctrl+C or Close console, the application should have time to terminate properly.
Has it is coded, the application never ends properly (because OS kill it quickly)

**Comment by DomXC** [comment]
Poco 1.8.0.1 the same issue, in case of Ctrl+C application has chance to close all resources properly, unfortunately using "Close" (CTRL_CLOSE_EVENT) is going to kill the application immediately. Unfortunately, I do not know, what exactly happens in Poco lib in case of CTRL_CLOSE_EVENT, hope will have time to investigate.

**Comment by nazilliefesi** [comment]
+1 for providing a way to let the application close itself gracefully. In our case this behavior prevents our server app to perform final log rotations when run from console. (using boost for logging)
