### ISSUE TITLE
Digest proxy with HTTPSClientSession

### ISSUE THREAD

**Issue by eraffi** [pocoproject/poco#761]
Is there a way to use a Digest authenticated proxy with an https connection?
I'm creating an HTTPSClientSession, which works fine with basic authentication.  It looks like the problem is that HTTPClientSession::proxyConnect is throwing an exception instead of checking the response and then setting the Digest credentials (as described in HTTPCredentials.h).
Am I doing this wrong or is Digest just not supported with https?
thanks
-Eric

**Comment by aleks-f** [comment]
See [HTTPClientSessionTest::testProxyAuth()](https://github.com/pocoproject/poco/blob/develop/Net/testsuite/src/HTTPClientSessionTest.cpp#L262). note also that there may be some [cookie-related caveats](http://stackoverflow.com/questions/29118669/client-digest-authentication-with-poco) with certain http servers.

**Comment by eraffi** [comment]
I don't think that applies here.  The case I'm concerned about is with https.  When I make a regular http connection, the HTTPClient::sendRequest method works, it returns a status 407 and then I can configure the proxy.  However, with https, the sendRequest method calls proxyConnect which throws an exception so I can't configure the request to use digest proxy.

**Comment by andriisavin** [comment]
I have the same situation, is any updates?
