### ISSUE TITLE
Unable to build static with NetSSL_OpenSSL for OS X

### ISSUE THREAD

**Issue by Cupidvogel** [pocoproject/poco#763]
I downloaded the complete Poco library from here, and tried to build it. I need it in 32 bit version (to use with Qt 5.3 32 bit), and I don't require the MySQL or ODBC parts, so I ran 

./configure --static --omit=Data/ODBC,Data/MySQL --config=Darwin32

followed by make -s, when I get this error during the test run of Open_SSL part:

** Building executable (debug) /Users/kausta/Desktop/poco-1.6.0-all/NetSSL_OpenSSL/testsuite/bin/Darwin/i386/static/testrunnerd
Undefined symbols for architecture i386:
  "Poco::JSON::ParseHandler::ParseHandler(bool)", referenced from:
      Poco::Util::JSONConfiguration::load(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Array::Array()", referenced from:
      Poco::Util::JSONConfiguration::findStart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::setValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Dynamic::Var const&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Query::Query(Poco::Dynamic::Var const&)", referenced from:
      Poco::Util::JSONConfiguration::getRaw(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) const in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::enumerate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) const in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Query::~Query()", referenced from:
      Poco::Util::JSONConfiguration::getRaw(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) const in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::enumerate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) const in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Object::set(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Dynamic::Var const&)", referenced from:
      Poco::Util::JSONConfiguration::loadEmpty(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::findStart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::setValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Dynamic::Var const&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Object::Object(bool)", referenced from:
      Poco::Util::JSONConfiguration::JSONConfiguration() in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::loadEmpty(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::findStart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Parser::parse(std::__1::basic_istream<char, std::__1::char_traits<char> >&)", referenced from:
      Poco::Util::JSONConfiguration::load(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Parser::Parser(Poco::SharedPtr<Poco::JSON::Handler, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Handler> > const&, unsigned long)", referenced from:
      Poco::Util::JSONConfiguration::load(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Parser::~Parser()", referenced from:
      Poco::Util::JSONConfiguration::load(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Array::get(unsigned int) const", referenced from:
      Poco::Util::JSONConfiguration::findStart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Array::getArray(unsigned int) const", referenced from:
      Poco::Util::JSONConfiguration::findStart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::setValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Dynamic::Var const&) in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::removeRaw(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Array::stringify(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, unsigned int, int) const", referenced from:
      Poco::Dynamic::VarHolderImpl<Poco::SharedPtr<Poco::JSON::Array, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Array> > >::convert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) const in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Query::find(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      Poco::Util::JSONConfiguration::getRaw(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) const in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::enumerate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) const in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Object::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      Poco::Util::JSONConfiguration::findStart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::setValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Dynamic::Var const&) in libPocoUtild.a(JSONConfiguration.o)
      Poco::Util::JSONConfiguration::removeRaw(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Object::getNames(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) const", referenced from:
      Poco::Util::JSONConfiguration::enumerate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) const in libPocoUtild.a(JSONConfiguration.o)
  "Poco::JSON::Object::stringify(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, unsigned int, int) const", referenced from:
      Poco::Util::JSONConfiguration::save(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, unsigned int) const in libPocoUtild.a(JSONConfiguration.o)
      Poco::Dynamic::VarHolderImpl<Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> > >::convert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) const in libPocoUtild.a(JSONConfiguration.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/Users/kausta/Desktop/poco-1.6.0-all/NetSSL_OpenSSL/testsuite/bin/Darwin/i386/static/testrunnerd] Error 1
make: *** [NetSSL_OpenSSL-tests] Error 2

How do I fix this?

**Comment by aleks-f** [comment]
The above fix takes care of the problem. Modify your makefiles accordingly; it will be in [1.6.1](https://github.com/pocoproject/poco/milestones/Release%201.6.1) release

**Comment by Cupidvogel** [comment]
Thanks. I made changes to all the 4 files as you mentioned and ran configure followed by make -s again. This time I get this error:

make[1]: *** No rule to make target `/Users/kausta/Desktop/poco-1.6.0-all/NetSSL_OpenSSL/testsuite/obj/Darwin/i386/debug_static/WebSocketTest.o', needed by `/Users/kausta/Desktop/poco-1.6.0-all/NetSSL_OpenSSL/testsuite/bin/Darwin/i386/static/testrunnerd'.  Stop.
make: *** [NetSSL_OpenSSL-tests] Error 2

**Comment by aleks-f** [comment]
You must be mixing something, that was [added recently](https://github.com/pocoproject/poco/commit/7022c44397012e6729a52853018cc99e607a23b5) and is not in the 1.6.0 release. I suggest you get 1.6.0 and rebuild. Or, checkout develop branch and rebuild (I just built 32 and 64 bit static and it builds fine). In any case, make sure you are building cleanly one or the other.

**Comment by Cupidvogel** [comment]
Umm, what do you mean by clean-build? I just changed all the four files (including the male file you just mentioned in test suite), ran the same configure command for static 32 bit and then ran make -s and got the error. What can I do otherwise?

**Comment by Cupidvogel** [comment]
Okay, so I am building 1.6.1. Where do I get 1.6.0 version?

**Comment by aleks-f** [comment]
No, you are not building 1.6.1. because it was not released yet. I did not suggest you copy the whole NetSSL Testsuite Makefile, just the changes I committed earlier. You copied the whole file and there lays your problem.

**Comment by Cupidvogel** [comment]
Okay, got it. I just downloaded 1.6.0 developers branch and started building it. Keeping fingers crossed. :)

**Comment by Cupidvogel** [comment]
Cheers! It worked!
