### ISSUE TITLE
Inconsistency in getPath & getPathAndQuery returns

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#767]
From [forum](http://pocoproject.org/forum/viewtopic.php?f=12&t=6494):

postby mfkilian » Thu Apr 02, 2015 1:07 pm

The strings returned from URI::getPath and URI::getPathAndQuery seem inconsistent:
```
#include <iostream>
using namespace std;
#include "Poco/URI.h"

int main(int argc, char *argv[]) {
Poco::URI x("/a%20b/c.mp4");

cout << "getPath() = '" << x.getPath() << "'" << endl;
cout << "getPathAndQuery() = '" << x.getPathAndQuery() << "'" << endl;
}
```
```
getPath() = '/a b/c.mp4'
getPathAndQuery() = '/a%20b/c.mp4'
```

Why is getPath() returning decoded content but getPathAndQuery returning the original (encoded) content? It seems inconsistent. It is also not apparent that there is an equivalent of getRawQuery for Path, i.e., getRawPath -- a way to get the original encoded version.

**Comment by aaron0x** [comment]
Hi @aleks-f,

The description of the URI class says:
“The class automatically performs a few normalizations on all URIs and URI parts passed to it: percent-encoded characters are decoded”
But the description of the setQuery says:
“The query string will be percent-encoded.”
Which description is right and should be kept?

**Comment by obiltschnig** [comment]
Well, both are right, kinda. Some parts of the URI are internally stored decoded (e.g., path, fragment, etc.), while the query string is stored URL-encoded internally. Therefore, setQuery() expects an unencoded query string (which is percent-encoded for internal storage), while setRawQuery() expects a properly percent-encoded query string. Consequently, getQuery() will return the decoded query string, while getRawQuery() will return the percent-encoded query string.

**Comment by obiltschnig** [comment]
And regarding the original question: any string involving the query should be kept encoded as it otherwise may lead to ambiguities. Therefore, getPath() can safely return the decoded path, while getPathEtc() and getPathAndQuery() must return encoded strings.

**Comment by obiltschnig** [comment]
Updated the documentation.

**Comment by obiltschnig** [comment]
(updated also in 1.6.2 branch)
