### ISSUE TITLE
OpenSSL build script on Windows

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#780]
A PowerShell script to build OpenSSL on windows

**Comment by aleks-f** [comment]
Added [OpenSSLBuild](https://github.com/pocoproject/poco/tree/OpenSSLBuild) branch with:

- [build script](https://github.com/pocoproject/poco/blob/OpenSSLBuild/openssl/build.ps1)
- [headers](https://github.com/pocoproject/poco/tree/OpenSSLBuild/openssl/out/include/openssl)
- pre-built (VS2008) [binaries](https://github.com/pocoproject/poco/tree/OpenSSLBuild/openssl/out)
- updated VS projects

**Comment by aleks-f** [comment]
@obiltschnig : please review and let me know if this is good to merge. I had to do some minor ProGen changes

**Comment by aleks-f** [comment]
@bachp : not sure whether and how this (openssl binaries and headers included in the poco tree) affects CMake

**Comment by bachp** [comment]
Maybe I missed some part of the conversation leading to this.
Is it really a good idea to have the binaries checked in to source control? Wouldn't it make more sense to do it similar to how libpcre or sqlit3 are handled? Or is it just to simplify building on windows?
I think for OpenSSL it is especially important to let the user select an unbundled version of OpenSSL as-well.

It has no imediate feedback on the CMake build as it still searches for an external OpenSSL. If we need to enhance CMake to support the included binaries I first need to understand a bit more about the reason before I can tell how this would fit into CMake.

**Comment by aleks-f** [comment]
Well, you are right about binaries in the repository - it's ugly, but ... there are always exceptions to rules. Namely, to have OpenSSL sources embedded would mean to also have Perl embedded and there you have the proverbial can of worms; the build system is one horrible mess of Perl and batch files (so I added a PowerShell script on top of it for desert, LOL). But seriously, the background of this effort is that I've got tired of having to install OpenSSL and modify VS projects every time I have a fresh copy of Poco to deal with (which is quite often). As for the external OpenSSL on Windows, it still works as usual - you have to install it and modify your projects to point to the right include and lib locations.

**Comment by pwm1234** [comment]
I have tried solving this problem with the cmake build of poco by adding logic to download the prebuilt openssl binaries during the cmake configure step. I have packaged the pre-built openssl binaries into tar.bz2 files (one for each 32 and 64 bit architectures), and then download them when FORCE_OPENSSL is defined but find_package openssl fails.

The snippet below is not fully usable for anyone but me, but I think it demonstrates a reasonable approach for using worthwhile 3rdparty binaries that are too hard build from source. (This is how how OpenCV is handling some of their optional dependencies.)


    if (WIN32 AND FORCE_OPENSSL)
      find_package(OpenSSL)
      if (NOT OpenSSL_FOUND)
        # get the name of the file to download
        if (CMAKE_SIZEOF_VOID_P EQUAL 8)
          # 64-bit
          set(openssl_fname OpenSSL-1.0.2a-Win64.tar.bz2)
          set(openssl_unpack_dir OpenSSL-1.0.2a-Win64)
        else()
          # 32-bit
          set(openssl_fname OpenSSL-1.0.2a-Win32.tar.bz2)
          set(openssl_unpack_dir OpenSSL-1.0.2a-Win32)
        endif()
    
        # settings for the download
        set(openssl_url https://artifact.server.com/3rdparty/OpenSSL/1.0.2a/${openssl_fname})
        set(openssl_download_dir ${CMAKE_BINARY_DIR}/download)
        set(openssl_unpack_dir "${openssl_download_dir}/${openssl_unpack_dir}")
    
        # if it has not yet been downloaded an unpacked, do so now
        if (NOT EXISTS ${openssl_unpack_dir})
          if (NOT EXISTS ${openssl_download_dir}/${openssl_fname})
    	file(DOWNLOAD ${openssl_url} ${openssl_download_dir}/${openssl_fname}
    	  SHOW_PROGRESS)
          endif()
          execute_process(COMMAND
    	${CMAKE_COMMAND} -E tar xvJ ${openssl_download_dir}/${openssl_fname}
    	WORKING_DIRECTORY ${openssl_download_dir}
    	)
        endif()
    
        # set the openssl root dir variable so cmake will find it on the
        # find_package(OpenSSL)
        set(OPENSSL_ROOT_DIR ${openssl_unpack_dir})
    
        # debug print for some of the variables used
        include(CMakePrintHelpers)
        cmake_print_variables(OPENSSL_ROOT_DIR
          openssl_fname
          openssl_url
          openssl_download_dir
          openssl_unpack_dir
          )
      endif()
    endif()

**Comment by aleks-f** [comment]
FYI: For 1.7.0,  OpenSSL headers and binaries will be supplied under $POCO_BASE/openssl directory, see [OpenSSL branch](https://github.com/pocoproject/poco/tree/OpenSSLBuild/openssl); so, any CMake modification should be along those lines. 

I am not yet done - have to move openssl headers from Crypto back to openssl directory, update ProGen files and then I will merge it to develop (probably by the end of the week). For those who want a different version, [build script](https://github.com/pocoproject/poco/blob/OpenSSLBuild/openssl/build.ps1) (which has to be invoked manually) will fetch everything needed and build OpenSSL. Those that want externally pre-built OpenSSL will have to modify VS project.

**Comment by aleks-f** [comment]
This is now in [develop branch](https://github.com/pocoproject/poco/tree/develop/openssl).
