### ISSUE TITLE
Several undefined references

### ISSUE THREAD

**Issue by Hetsh** [pocoproject/poco#781]
I'm using poco basic 1.6.0 and get 4 undefined reference errors in Poco/Net/SocketAddressImpl.h when including Poco/Net/HTTPClientSession.h:

Line:88 Undefined reference: 'Poco::Net::IPAddress::IPAddress(void const\*, unsigned int)'
Line:149 Undefined reference: 'Poco::Net::IPAddress::IPAddress(void const\*, unsigned int, unsigned int)'
Line:119 Undefined reference: 'Poco::Net::Impl::SocketAddressImpl::~SocketAddressImpl()'
Line:58 Undefined reference: 'Poco::Net::Impl::SocketAddressImpl::~SocketAddressImpl()'

g++ -v output:

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by aleks-f** [comment]
It's hard to figure out from the information you provided what exactly you are doing; in any case, you'll have to link with libPocoNet

**Comment by Hetsh** [comment]
That did it.

Thanks
