### ISSUE TITLE
GCC_DIAG_* definitions are missing for Windows (MinGW)

### ISSUE THREAD

**Issue by procedural** [pocoproject/poco#785]
https://github.com/pocoproject/poco/blob/1b70142/Foundation/include/Poco/Platform_POSIX.h#L47-L76

They're defined only for POSIX platforms, when trying to compile master branch on Windows with MinGW it throws errors because of undefined GCC_DIAG_* macros.

**Comment by aleks-f** [comment]
Fix it and send pull request pleas

**Comment by procedural** [comment]
You mean copy and paste GCC_DIAG_* macros to Platform_WIN32.h?

**Comment by aleks-f** [comment]
Of course not. I mean #ifdef them out for mingw

**Comment by aleks-f** [comment]
Alternatively, GCC_DIAG should be moved to it's own header and included from Platform_POSIX and Platform_Win32 (for MinGW). Reopening, perhaps someone will be interested to do this. I have no MinGW environment handy.

**Comment by procedural** [comment]
How would you like to name this header file?

**Comment by procedural** [comment]
PR https://github.com/pocoproject/poco/pull/787

**Comment by aleks-f** [comment]
Just out of curiosity, I tried MinGW and the build is broken - when <cmath> is included, these should be in std namespace:

```
In file included from include/Poco/FPEnvironment.h:27,
                 from include/Poco/NumericString.h:25,
                 from include/Poco/NumberFormatter.h:24,
                 from include/Poco/ArchiveStrategy.h:27,
                 from src/ArchiveStrategy.cpp:17:
include/Poco/FPEnvironment_DUMMY.h: In static member function `static bool Poco:
:FPEnvironmentImpl::isInfiniteImpl(float)':
include/Poco/FPEnvironment_DUMMY.h:78: error: `isinf' is not a member of `std'
include/Poco/FPEnvironment_DUMMY.h: In static member function `static bool Poco:
:FPEnvironmentImpl::isInfiniteImpl(double)':
include/Poco/FPEnvironment_DUMMY.h:84: error: `isinf' is not a member of `std'
include/Poco/FPEnvironment_DUMMY.h: In static member function `static bool Poco:
:FPEnvironmentImpl::isInfiniteImpl(long double)':
include/Poco/FPEnvironment_DUMMY.h:90: error: `isinf' is not a member of `std'
include/Poco/FPEnvironment_DUMMY.h: In static member function `static bool Poco:
:FPEnvironmentImpl::isNaNImpl(float)':
include/Poco/FPEnvironment_DUMMY.h:96: error: `isnan' is not a member of `std'
include/Poco/FPEnvironment_DUMMY.h: In static member function `static bool Poco:
:FPEnvironmentImpl::isNaNImpl(double)':
include/Poco/FPEnvironment_DUMMY.h:102: error: `isnan' is not a member of `std'
include/Poco/FPEnvironment_DUMMY.h: In static member function `static bool Poco:
:FPEnvironmentImpl::isNaNImpl(long double)':
include/Poco/FPEnvironment_DUMMY.h:108: error: `isnan' is not a member of `std'
make: *** [/c/poco/Foundation/obj/MinGW/i686/debug_static/ArchiveStrategy.o] Err
or 1
```

**Comment by procedural** [comment]
> In file included from include/Poco/FPEnvironment.h:27

Wait, did you defined POCO_NO_FPENVIRONMENT for MinGW build on Windows? Is it necessary?

**Comment by procedural** [comment]
I build POCO with CMake and [POCO_NO_FPENVIRONMENT is defined only for Android and iOS platforms only](https://github.com/pocoproject/poco/blob/3ee9e2a/CMakeLists.txt#L172-L180), so I don't think it's needed for this case.

**Comment by aleks-f** [comment]
I did not define anything, just configured for MinGW and run make for Foundation

**Comment by procedural** [comment]
> I did not define anything, just configured for MinGW and run make for Foundation

Well, [you did](https://github.com/pocoproject/poco/blob/9d259ac/build/config/MinGW#L70) :) Welcome to macro hell, when you don't know what you've defined and why build fails.

Either way I decided to undefine GCC_DIAG macros because I think it's stupid to suppress warnings trough code, the issue can be closed.

**Comment by obiltschnig** [comment]
Given that many issues that GCC_DIAG has caused in recent weeks, I'm inclined to remove it altogether.

**Comment by procedural** [comment]
@obiltschnig ah, thank you! Would appreciate that!

**Comment by aleks-f** [comment]
The problem was that the macro and switching it off were in two different places; plus it was ifdef'd in yet another place. That is [fixed](https://github.com/pocoproject/poco/commit/62bcc5c6edbbb67388232f03fc36c17730f5c138). I can't remember exactly when, but GCC_DIAG was introduced when gcc started emitting an avalanche of unreasonable warnings. While it is true that it's easy to disarm those warnings manually, when you have to do it over and over again, it becomes a bit tiresome.

@procedural : when I said I did not define anything, I meant I did not **explicitly** define anything, i.e. I used defaults that come with MinGW config.

**Comment by procedural** [comment]
@aleks-f yea, I know :)

> While it is true that it's easy to disarm those warnings manually

It's not. These flags should be defined in project configures if needed, CMake can detect GNU compilers for example. Leaving flags in code asks for troubles for different compilers which may fail on compile time rather than on project generation step.

**Comment by obiltschnig** [comment]
I was able to fix the warning by adding __attribute__((unused)) to the typedef for GCC. Since the GCC_DIAG_OFF macro is used nowhere else, I've removed it.

**Comment by aleks-f** [comment]
@procedural: keep in mind that CMake is not the only build system used to build Poco
@obiltschnig: I can't see it removed in the last commit, you must have missed something

**Comment by obiltschnig** [comment]
Believe me, it's gone ;-) Look one commit earlier.
