### ISSUE TITLE
Travis jobs failing

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#789]
Quite annoyingly, recently Travis jobs seem to be randomly failing. E.g. [this one](https://travis-ci.org/pocoproject/poco/jobs/59642765):

```
The command "sudo apt-get install -qq -y cmake3" exited with 100.
```

@bachp : can you explain what is going on and provide a permanent fix? I'm not sure it's always CMake, but I hate seeing a broken build icon; particularly after I push a small documentation change.

**Comment by bachp** [comment]
I will have a look at it
