### ISSUE TITLE
Fetch a resultset from MySQL Stored Procedure

### ISSUE THREAD

**Issue by DBarzo** [pocoproject/poco#794]
Hi,
I'm working with a MySQL DB (Server version 5.6.20) which contains the following Procedure:

```
DELIMITER $$
CREATE PROCEDURE GetLastIds()
BEGIN

  SELECT m_fon_id, 
                (SELECT MAX(m_fon_rcd_id) as rcd_id 
                 FROM tbl_misure as m2 WHERE m2.m_fon_id = m.m_fon_id) as max
  FROM tbl_misure m 
  GROUP BY m_fon_id;

END $$
DELIMITER ;
```

Which returns the following resultset:

| m_fon_id | max |
| --- | --- |
| 2147617449 | 1462 |
| 2147617450 | 1304 |
| 2147617451 | 1308 |

If I call it from code it returns an empty recordset:

```
Statement select(*m_pSession);

select << "call GetLastIds()";
select.execute();
RecordSet rs(select);
bool more = rs.moveFirst();  // <- Is FALSE
```

Instead if I issue the same query from code, it works:

```
Statement select(*m_pSession);

select << "SELECT m_fon_id, \
                  (SELECT MAX(m_fon_rcd_id) as rcd_id \
                  FROM tbl_misure as m2 WHERE m2.m_fon_id = m.m_fon_id) as max \
            FROM tbl_misure m \
            GROUP BY m_fon_id";

select.execute();
RecordSet rs(select);
bool more = rs.moveFirst(); // <- is TRUE
```

The MySQL should have an 'implicit' cursor which returns the select statement:
https://dev.mysql.com/doc/refman/5.6/en/faqs-stored-procs.html#qandaitem-A-4-1-14

I'm using poco 1.6.0
I'm wrong or misunderstood something?

Regards,
Daniele.

**Comment by aleks-f** [comment]
AFAIK, Poco::Data::MySQL back-end does not support stored procedures. When I tested [ODBC driver](https://github.com/pocoproject/poco/blob/develop/Data/ODBC/testsuite/src/ODBCMySQLTest.cpp#L183-L206) (long time ago), MySQL was buggy and poorly supported stored procedures. Hopefully things have improved and someone will step in to contribute stored procedure support for MySQL.

**Comment by DBarzo** [comment]
Thanks a lot Aleks, if I have some time I try to dig into the problem more deeply.
