### ISSUE TITLE
ColorConsoleChannnel not printing properly?

### ISSUE THREAD

**Issue by Mazyod** [pocoproject/poco#795]
Hi,

Thanks for this amazing library. I am just having a minor issue trying to get ColorConsolChannel to work properly.

After I initialize the logger in the main method, I print out a few statements, and they work as expected with colors and all. After that, I try to fetch the logger and print a few logs, but the colors are not added at all. Any idea what could be wrong?

Main:

```cpp
AutoPtr<ColorConsoleChannel> consoleChannel(new ColorConsoleChannel());
auto& logger = Logger::get("network");
logger.setChannel(consoleChannel);
logger.setLevel(Message::PRIO_TRACE);

logger.warning("Look, I has colors");
```
Somewhere else in the code, these logs print the messages, but without colors:

```cpp
Net::HTTPRequestHandler * HandlerFactory::createRequestHandler(const Net::HTTPServerRequest &request)
{
    auto& LOG = Logger::get("network");
    LOG.trace("Handle factory for: %s"
              , request.getURI());
    
    if (request.getURI() == "/results") {
        return new ResultsHandler();
    }
    else if (request.getURI() == "/action") {
        return new ActionHandler();
    }
    
    LOG.warning("Rogue URI detected at: %s, from: %s"
                , request.getURI()
                , request.clientAddress().toString());
    
    return nullptr;
}
```

image:
![](http://imgur.com/7sPhVqx.png)

**Comment by Mazyod** [comment]
I have similar logger code on the client and server applications, and it works perfectly on the client app. The server, however, doesn't work and I am guessing cause it is multithreaded. Is there a way around this?

**Comment by aleks-f** [comment]
Do you have any logging configuration loaded from a config file? Somehow you are not getting the reference to the same channel in the handler.

I did not have time to try reproduce the problem;a [MCVE](http://stackoverflow.com/help/mcve) will help resolving the issue faster.

**Comment by Mazyod** [comment]
Thanks @aleks-f, and sorry for the lack of a proper MCVE. I will work on that.
Meanwhile, all the related code is shown in the post. No config loaded from any file.

**Comment by Mazyod** [comment]
OK, here are my findings, and at the end is the MCVE.

1. It is not a multithreading issue:
I spawned threads, wrote to the log, it all works.

2. It is specifically affected by `Util/ServerApplication`, I think:
If I initialize the logger before the server app, the channel reference probably changes, as you mentioned.

In order to reproduce the issue, [I used this example](https://github.com/wancw/poco-examples/tree/master/200-Network/http-server). Here are the changes I made, and got the same bug:

`main.cpp`

```cpp
#include <Poco/Util/ServerApplication.h>

#include "SimpleHTTPServerApplication.h"
#include <iostream>

// NEW
#include <Poco/Logger.h>
#include <Poco/ConsoleChannel.h>

int main(int argc, char** argv)
{
	// NEW
	Poco::AutoPtr<Poco::ColorConsoleChannel> consoleChannel(new Poco::ColorConsoleChannel());
	auto& logger = Poco::Logger::get("something");
	logger.setChannel(consoleChannel);
	logger.setLevel(Poco::Message::PRIO_TRACE);

	logger.warning("Look, I has colors");

    try {        
        SimpleHTTPServerApplication app;
        return app.run(argc, argv);
    }
    catch (Poco::Exception& exc) {
        std::cerr << exc.displayText() << std::endl;
        return Poco::Util::Application::EXIT_SOFTWARE;
    }
}
```

`HandlerFactory.cpp`

```cpp
#include "HandlerFactory.h"

#include "CurrentTimeHandler.h"
#include <Poco/Logger.h> // THIS

HandlerFactory::HandlerFactory () {}

Poco::Net::HTTPRequestHandler * HandlerFactory::createRequestHandler (const Poco::Net::HTTPServerRequest &request)
{
	Poco::Logger::get("something").error("colors not present"); // THIS
	return new CurrentTimeHandler();
} 
```

Then, I decided to move the logger initialization log inside the `SimpleHTTPServerApplication::main` method, and it actually works when I did that.

**Comment by Mazyod** [comment]
For your convenience, I forked the examples, and committed two versions, one that works and one that doesn't.

+ [Broken revision](https://github.com/Mazyod/poco-examples/tree/26336af05f67cc37835d644be9a5cfc9ffc29413)
+ [Working revision](https://github.com/Mazyod/poco-examples/tree/e17ee8e677bfa5f6fa378cfc8c2a98b846bf26b7)

**Comment by aleks-f** [comment]
ServerApplication is not meant to be used the way you are using it because it will initialize everything, including the LoggingSubsystem. If you use ServerApplication, then you should leave the logging initialization to it and provide the logging system setup through [configuration](https://github.com/pocoproject/poco/blob/9d259ac02f880a486ebef30acc4e5e83d3e87b5f/Util/samples/SampleServer/SampleServer.properties). 

I was able to reproduce your problem and did not have time to look deep into the exact point where it happens, but it is obvious that your initial channel setup gets lost later during the ServerApplication LoggingSubsystem initialization.

**Comment by Mazyod** [comment]
Oops, sorry I'll be more careful about that. It makes sense now to have the server app main macro.
