### ISSUE TITLE
Poco::UInt64 should be unsigned long long on OS X not unsigned long

### ISSUE THREAD

**Issue by Fallen-Zen-zz** [pocoproject/poco#800]
Therefore some of the .bind (not only those) methods in Poco refused to work.
In my opinion Poco/Types.h should be dropped and std:: used instead. It doesn't add any extra value over std:: (or maybe I can't see it) so why use it?

Example from my machine:
`Poco::JSON::Object::Ptr jsonObject(new Poco::JSON::Object());`
`expiresIn = jsonObject->getValue<std::uint64_t>("expires_in");`

Gives me 64/poco/include/Poco/Dynamic/Var.h:171:12: No matching member function for call to 'convert' as std::uint64_t is unsigned long long.

**Comment by aleks-f** [comment]
On OSX with clang and gcc alike, Poco::UInt64 is [unsigned long](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Types.h#L73) when long is 64 bit and [unsigned long long](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Types.h#L76) when long is 32 bit.

>  It doesn't add any extra value over std:: (or maybe I can't see it) so why use it?

It adds extra value where there is (or was) no cstdint. In any case, there's too much code depending on it to simply drop it but it should be gradually transformed into a proxy for standard header

**Comment by davidandreoletti** [comment]
@Fallen-Zen: I agree with @aleks-f about not dropping the header. However, I believe by default Poco::Type should match the fixed width types offered by the target platform (C/C++ Standard) or define them otherwise.

@aleks-f  Do you think uint64_t should always match Poco::Uint64 ? IMHO, they semantically implies to represent an unsigned 64bit value yet differs in how to represent it depending on the data model. So I would be inclined to answer yet (it also solves my current compilation problem)

**Comment by zosrothko** [comment]
Poco/Typs.should NOT be dropped. Intermediate typedef like Int8 up toUIntPtr are used to define a precise semantic of the type in term of capacity and sign for the Poco code and isolate the Poco code from small variation of the compiler native data type. 

Moreover, no code in Poco sould use the cstdint types but only the one from Poco/Types.h (an int on a 32 bit architecture would be 32 bit long, while an int on a 64 bit architecture could be 64 bit long)

**Comment by davidandreoletti** [comment]
@zosrothko The problem (for me) is how to map C/C++ standard types (eg: uint64_t) to Poco/Types.h and inversely. **Do you have any recommendation to help solving this type of problem ?** This would help answer the initial question raised by @Fallen-Zen.

**Comment by zosrothko** [comment]
Have a look at Poco/Type.h to find out wich Poco's type corresponds to the C/C++ type.  For example, uint64_t is matched by UInt64. UInt64 should be used instead of uint64_t in your code

**Comment by aleks-f** [comment]
There is no simple way out of this now, but time will take care of it. Poco consolidated the insanity that is the type system before it was made sane by the standard. Eventually, as old compilers are desupported, the old things will go away as well and we will have the freedom to align with standard. For now, if you use Poco, it is recommended to use Poco types as well - they will work in the future.

**Comment by zosrothko** [comment]
@davidandreoletti May be I did not understand really your point " Do you think uint64_t should always match Poco::Uint64 ?", so I would like to add another comments. In my opinion, one should never think of C/C++ types in Poco but only in term of Poco types defined in Poco/Types.h. The general accepted semantic of uint64_t is a type as an unsigned 2s complement binary encoded with a precision of 64 bits. That's exactly what means the Poco type UInt64. Thus your question should be reversed as " Do you think Poco::Uint64 should always match uint64_t ? and the answer is no, at least with GNU and clang. 

So to come back at the initial point of @Fallen-Zen: Why Poco::UInt64 should be unsigned long long on OS X not unsigned long? ( I do not master the arcane of OS X and from the Poco/Type.h, UInt64 is a unsigned long when __LP64__ is defined while it is a unsigned long long when not) Thus what did I miss?

**Comment by mellery451** [comment]
I'm hitting this same issue and trying to understand the responses above. Given that, on osx we have:
    typedef unsigned long      UInt64;
and
    typedef unsigned long long uint64_t;

AND if we want to stick to standard c++ types in our code, when we want to call Poco methods, what is the recommended way to do that? We need to cast all uint64_t types?

**Comment by zosrothko** [comment]
@mellery451 Which version of Poco are you using?

**Comment by mellery451** [comment]
looks like it's

`#define POCO_VERSION 0x01060000`

**Comment by obiltschnig** [comment]
Eventually we should change the definition of Poco/Types.h to match <cstdint>, but that change is not trivial as it affects quite some code which will have to be reviewed. Will probably have to wait for 2.0.

**Comment by zosrothko** [comment]
@mellery451 When using Poco API, one should use the Poco types defined in Poco/types.h instead of the one in cstdint. This is warrant of portability among various combinations of OS/Compiler/hardware(Windos/Linux-Intel/gcc/clang-32/64)


#include <cstdint>
#include "Poco/JSON/Object.h"
using namespace std;
using namespace Poco;

int main(int argc, char** argv) {
        uint64_t expiresIn;
        JSON::Object::Ptr jsonObject(new JSON::Object());
        expiresIn = jsonObject->getValue<UInt64>("expires_in");
}
Using getValue<UInt64>,Tte above program compiles without error on Fedora with g++ and clang++, while it fails when using getValue<uint64_t>.

gcc --version
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
clang --version
clang version 3.7.0 (tags/RELEASE_370/final)
