### ISSUE TITLE
Feature Request: NotificationQueue::remove

### ISSUE THREAD

**Issue by Mazyod** [pocoproject/poco#803]
I am using `Poco::NotificationQueue` for queueing requests coming into the server to later be served at 10 second intervals.

Sometimes, a client request may come in that cancels the previous work request. The obvious way to go about this is to add a remove method on `NotificationQueue`. A work around that occurred to me is to create an ignore list, but that is more code to maintain on my end, so I would like to avoid that.

Any ideas on whether such a feature is welcomed to the `NotificationQueue` class? Would creating a PR with this feature be something you're interested in?

Thanks,
Maz

**Comment by aleks-f** [comment]
I guess cancelling would be fine, returning bool indicating whether cancellation was successful or not. Make sure the operation is mutex-locked and also provide tests with PR.

**Comment by Mazyod** [comment]
Of course, thanks for the reply.
