### ISSUE TITLE
cmake fails with Visual Studio 2013 Express

### ISSUE THREAD

**Issue by aaboyd** [pocoproject/poco#805]
I installed Visual Studio 2013 Express in hopes of being able to compile POCO on windows, and I noticed that cmake wasn't able to find the mc.exe ( Microsoft message compiler ).  After poking around in the PocoMacros.cmake I noticed the two keys that are grabbed in the registry to help find the mc.exe executable.  ```HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot``` doesn't actually exist.  ```HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot81``` however does exist.  I don't know if that should be added to the search, but I was able to get past the issue by creating the ```HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot``` key myself.

Relevant portion of [PocoMacros.cmake](https://github.com/pocoproject/poco/blob/develop/cmake/PocoMacros.cmake#L9) 
``` cmake
if (WIN32)
  # cmake has CMAKE_RC_COMPILER, but no message compiler
  if ("${CMAKE_GENERATOR}" MATCHES "Visual Studio")
    # this path is only present for 2008+, but we currently require PATH to
    # be set up anyway
    get_filename_component(sdk_dir "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Microsoft SDKs\\Windows;CurrentInstallFolder]" REALPATH)
    get_filename_component(kit_dir "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot]" REALPATH)
    if (X64)
      set(sdk_bindir "${sdk_dir}/bin/x64")
      set(kit_bindir "${kit_dir}/bin/x64")
    else (X64)
      set(sdk_bindir "${sdk_dir}/bin")
      set(kit_bindir "${kit_dir}/bin/x86")
    endif (X64)
  endif ()
  find_program(CMAKE_MC_COMPILER mc.exe HINTS "${sdk_bindir}" "${kit_bindir}"
    DOC "path to message compiler")
  if (NOT CMAKE_MC_COMPILER)
    message(FATAL_ERROR "message compiler not found: required to build")
  endif (NOT CMAKE_MC_COMPILER)
  message(STATUS "Found message compiler: ${CMAKE_MC_COMPILER}")
  mark_as_advanced(CMAKE_MC_COMPILER)
endif(WIN32)```

**Comment by bachp** [comment]
Hi Alex

Thanks for pointing that out. It seems the key is changing depending on the SDK installed.
As far as I know mc.exe is not part of Visual Studio but is part of the Windows SDK.

Maybe we can find a better way then just keep adding keys.

Do you know if and what version is installed? And what is the exact location of mc.exe on your sytem?

**Comment by aaboyd** [comment]
I started on a fresh install of windows, installed Visual Studio Express for Windows Desktop which in turn installs the mc.exe that is part of the Windows SDK.  I thought that would be the easiest way to get myself up and running.  I have never installed the Windows SDK by itself.

```
C:\Program Files (x86)\Windows Kits\8.1\bin\x64\mc.exe
C:\Program Files (x86)\Windows Kits\8.1\bin\x86\mc.exe
```

**Comment by bachp** [comment]
Could you try the following version and check if this solves the issue?
https://github.com/siemens/poco/tree/mc-compiler

**Comment by aaboyd** [comment]
@bachp that worked for me.

BTW, the registry key for the Windows 10 kit is ```[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10```.  Don't know if you just want to get out ahead of that issue popping up.

Whats a little odd is that on my Windows 10 VM the build works off of a develop even though the KitsRoot key doesn't exist ...

**Comment by bachp** [comment]
@aaboyd Thanks for the hint.

I t might be that the mc.exe is already in a standard location. That way CMake would find it as-well.
Can you check what mc.exe was used on your windows 10 machine? You can find the value by searching the `CMakeCache.txt` for `CMAKE_MC_COMPILER`.

**Comment by aaboyd** [comment]
I have ```CMAKE_MC_COMPILER:FILEPATH=C:/Program Files (x86)/Windows Kits/8.0/bin/x86/mc.exe```

Here are the relevant registry keys.

```HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Microsoft SDKs\\Windows;CurrentInstallFolder```
```C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\```

```HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot```
```C:\Program Files (x86)\Windows Kits\8.1\```

**Comment by Torndeco** [comment]
For sdk 8.1 its

    get_filename_component(sdk_dir "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Microsoft SDKs\\Windows;CurrentInstallDirectory]" REALPATH)
    get_filename_component(kit_dir "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot81]" REALPATH)

**Comment by kainjow** [comment]
I got this error from an uninstall of VS Express 2013 and then installing VS Community 2015. I also have KitsRoot, KitsRoot10, and KitsRoot81.

In my case, the CMAKE_MC_COMPILER macro doesn't even seem to be needed (I am integrating into my CMake project via `add_subdirectory`). Second, if it is needed, it would help to only define it if the POCO_MESSAGES macro is called.

If I disable the FATAL_ERROR when mc.exe isn't found, I am able to build. So it doesn't seem to be crucial for the core components.

**Comment by mikeloomisgg** [comment]
Just chiming in on this old issue. I'm on windows, compiling with clang 18, using cmake generator ninja attempting to use poco 1.14.0. For whatever reason, all of this additional cmake module code to try and seek out mc.exe is only enabled if your generator is either visual studio or mingw.

You need to add the windows kit, wherever you have installed the Microsoft SDK, locate the mc.exe and add that to your path. If its in your system path then poco will successfully configure.
