### ISSUE TITLE
POP3 client fails to retrieve message if content-type is absent

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#806]
From [SourceForge](https://sourceforge.net/p/poco/bugs/632/):

Method POP3ClientSession::retrieveMessage() throws exception Poco::NotFoundException if Content-Type is absent.
It happens in MultiPartHandler::handlePart()

```
...
99  PartSource* pPS = _pMsg->createPartStore(tmp, 
100     header[MailMessage::HEADER_CONTENT_TYPE], 
101     getFileNameFromDisp(it->second));
...
```

See file Net/src/MailMessage.cpp (line 100)

'header' variable (type of MessageHeader) does not have value of MailMessage::HEADER_CONTENT_TYPE. So NameValueCollection (parent class of MessageHeader) throws NotFoundException inside of operator[].

Content-Type can be absent. Default value is "text/plain".

**Comment by aleks-f** [comment]
From [RFC 2045](https://www.ietf.org/rfc/rfc2045.txt):

> 5.2.  Content-Type Defaults

>   Default RFC 822 messages without a MIME Content-Type header are taken
>   by this protocol to be plain text in the US-ASCII character set,
>   which can be explicitly specified as:
```
     Content-type: text/plain; charset=us-ascii
```
>   This default is assumed if no Content-Type header field is specified.
>   It is also recommend that this default be assumed when a
>   syntactically invalid Content-Type header field is encountered. In
>   the presence of a MIME-Version header field and the absence of any
>   Content-Type header field, a receiving User Agent can also assume
>   that plain US-ASCII text was the sender's intent.  Plain US-ASCII
>   text may still be assumed in the absence of a MIME-Version or the
>  presence of an syntactically invalid Content-Type header field, but
>   the sender's intent might have been otherwise.

**Comment by chepokabra** [comment]
https://www.ietf.org/rfc/rfc1521.txt
   7.2.  The Multipart Content-Type
   ...
   A body part is NOT to be interpreted as actually being an RFC 822
   message.  To begin with, NO header fields are actually required in
   body parts.  A body part that starts with a blank line, therefore, is
   allowed and is a body part for which all default values are to be
   assumed.  In such a case, the absence of a Content-Type header field
   implies that the corresponding body is plain US-ASCII text.

**Comment by chepokabra** [comment]
anyway "Content-type" can be absent it is a fact. So it seems POCO C++ should face it. All email clients, I have used, handle absence of Content-type correctly.

**Comment by aleks-f** [comment]
It is marked as but and will be addressed (i.e. we have heard the complaint and admitted there is a problem). 

If you are in a hurry, send a pull request with fix and tests, please.

**Comment by chepokabra** [comment]
Thank you. I am not in a hurry but if I have time to fix I will fix it.

**Comment by chepokabra** [comment]
What about a pull request without writing code of unit tests (if you talk about unit tests)? But I can test on my side.

**Comment by chepokabra** [comment]
Patch https://drive.google.com/file/d/0B275a-c8rCuROWxyM1BORTR4ckU/view?usp=sharing
