### ISSUE TITLE
Unable to build for android

### ISSUE THREAD

**Issue by aaboyd** [pocoproject/poco#812]
I don't know if this is a bug or if I am doing something completely wrong.  I followed the steps on [Android Platform Notes](http://pocoproject.org/docs/99300-AndroidPlatformNotes.html#2) but am failing to get anything to build.

```
** Compiling src/ArchiveStrategy.cpp (debug, static)
** Compiling src/Ascii.cpp (debug, static)
** Compiling src/ASCIIEncoding.cpp (debug, static)
** Compiling src/AsyncChannel.cpp (debug, static)
In file included from include/Poco/Foundation.h:115:0,
                 from include/Poco/AsyncChannel.h:23,
                 from src/AsyncChannel.cpp:17:
include/Poco/Alignment.h:37:19: fatal error: cstddef: No such file or directory
 #include <cstddef>
                   ^
compilation terminated.
In file included from include/Poco/Foundation.h:115:0,
                 from include/Poco/ASCIIEncoding.h:23,
                 from src/ASCIIEncoding.cpp:17:
include/Poco/Alignment.h:37:19: fatal error: cstddef: No such file or directory
 #include <cstddef>
                   ^
compilation terminated.
In file included from include/Poco/Foundation.h:115:0,
                 from include/Poco/Ascii.h:23,
                 from src/Ascii.cpp:17:
include/Poco/Alignment.h:37:19: fatal error: cstddef: No such file or directory
 #include <cstddef>
                   ^
compilation terminated.
In file included from include/Poco/Foundation.h:115:0,
                 from include/Poco/ArchiveStrategy.h:23,
                 from src/ArchiveStrategy.cpp:17:
include/Poco/Alignment.h:37:19: fatal error: cstddef: No such file or directory
 #include <cstddef>
                   ^
compilation terminated.
make[1]: *** [/Users/alex/Source/brain/lib/poco/Foundation/obj/Android/armeabi/debug_static/ASCIIEncoding.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/Users/alex/Source/brain/lib/poco/Foundation/obj/Android/armeabi/debug_static/AsyncChannel.o] Error 1
make[1]: *** [/Users/alex/Source/brain/lib/poco/Foundation/obj/Android/armeabi/debug_static/Ascii.o] Error 1
make[1]: *** [/Users/alex/Source/brain/lib/poco/Foundation/obj/Android/armeabi/debug_static/ArchiveStrategy.o] Error 1
make: *** [Foundation-libexec] Error 2
```

Any ideas would be greatly appreciated.

Is there a write up on how to compile for android with cmake?

**Comment by bachp** [comment]
I never tried to build Poco on Android using CMake.
So help getting this working is appreciated.

**Comment by RangelReale** [comment]
I build using the ./configure script, following exactly the instructions on the Poco Android README. Using a latest NDK toolchain (10), it compiles cleanly. Probably there are required compiler flags that are configured on the build script.

**Comment by aleks-f** [comment]
@bachp look [here](https://github.com/pocoproject/poco/blob/develop/build/config/Android) to see what's missing

**Comment by aaboyd** [comment]
@bachp @RangelReale  sorry, I worded that really poorly.  The error output I posted above is actually from running the ```./configure``` script.  I am on Mac OS X yosemite and I installed the ndk using homebrew, I can compile other things with the standalone toolchain, but Poco fails every time.  I am going to try later to download the ndk and build the toolchain exactly as the README described.  I will report any results I find.

I was curious if there was instructions on how to compile it with CMake as that is the build tool we are using for our main project and I was trying to get some consistency.  The actual error output was from the ```./configure``` and ```./make``` execution per the README instructions.

**Comment by aleks-f** [comment]
ok, rolling it back to the android expert

**Comment by bachp** [comment]
@aaboyd Ok I don't have any experience with CMake and Android.

But the general approach would be like this:

1. Get a CMake toolchain file for NDK (Somthing like: https://github.com/taka-no-me/android-cmake), this is independent of Poco.
2. Make sure all the required options are correctly set in the Poco CMake files for android, this might require some changes to Poco CMake files.

**Comment by RangelReale** [comment]
I compile poco using the configure script, and my project is all CMake
based, the generated lib works perfectly in this setup.

But I only compiled in ubuntu, don't know about mac.

What I know is that older NDKs gave a lot of errors like this.
Em 09/05/2015 14:40, "Pascal Bach" <notifications@github.com> escreveu:

**Comment by aaboyd** [comment]
I just uninstalled the ndk, deleted my built toolchains and started over.

Things are working now, sorry for the false alarm.

It might be worth creating a separate issue for allowing android builds through cmake.

**Comment by qqstoneme** [comment]
Hi:
I have the same problem when build poco for android ,
the evironment is  poco-1.6.0-all  and  android-ndk-r9b.
If someone has been resolved.,please help me.
