### ISSUE TITLE
CMake Android build

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#814]
Follow-up to Unable to build for android #812

**Comment by peterholak** [comment]
Android NDK r13 now comes with an "official" cmake toolchain file https://github.com/android-ndk/ndk/wiki/Changelog-r13#ndk

**Comment by Bjoe** [comment]
For the sake of completeness in `poco-1.9.1` and `develop` branch, there is support for Android build. There are also test builds on travis.
I think this issue is fixed.
#2555 Update CMake documentation for Android Platform is still missing.
