### ISSUE TITLE
JSON Stringifier fails with preserve insert order

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#819]
Since Dynamic::Var makes a copy of the object, the [Object::getKey(KeyPtrList::const_iterator&)](https://github.com/pocoproject/poco/blob/develop/JSON/src/Object.cpp#L104-L114) succeeds when called directly on the object but fails when JSON::Stringifier is used.

**Comment by bleach3** [comment]
thinks you.
-		if (&it->second == *iter) return it->first;
+		if (it->second == **iter) return it->first;

use  Var::operator == (const Var& other) const       ---> code so clean.


good  ...

I must learn from you

**Comment by bleach3** [comment]
sorry,There is a problem.


	Object jObj2(true);//-------->use preserveInsertionOrder=true

	jObj2.set("car", "这是中文abc@qwe.com1231");
	jObj2.set("baz", "fas");
	jObj2.set("baz1", "fas");
	jObj2.set("1baz11", "fas");
	Poco::JSON::Array array1;
	array1.add(jObj2);
	
	std::ostringstream oss122;
	array1.stringify(oss122);
	std::string fdsafsa=oss122.str();
	
	std::cout<<"array1="<<fdsafsa<<std::endl;

//[{"car":"这是中文abc@qwe.com1231","1baz11":"fas","1baz11":"fas","1baz11":"fas"}]

not match 

/[{"car":"这是中文abc@qwe.com1231","baz":"fas","baz1":"fas","1baz11":"fas"}]
