### ISSUE TITLE
Timeout Exception with non-blocking SSL connection since V1.6.0

### ISSUE THREAD

**Issue by ronnydierckx** [pocoproject/poco#822]
1. SSL server uses acceptConnection() to create a new client socket
2. use client_socket.setBlocking(false) to make socket no-blocking
3. When trying to read from socket I always get a Timeout exception. This is because
   the (shared) socket descriptor is made non-blocking, but the _blocking flag in the socket
   object in SecureSocketImpl is not adjusted. 
4. In SecureSocketImpl::handleError() SSL_ERROR_WANT_READ there is now a check on 
   _pSocket->getBlocking(), and this will always be true and thus throw an Exception

**Comment by alexacidy** [comment]
Still the issue in the latest version. Is there a simple workaround? 😐

**Comment by matejk** [comment]
> Still the issue in the latest version. Is there a simple workaround? 😐

@alexacidy, by inspecting code changes it seems that this problem was resolved in release 1.12.

Which version exactly did you use to reproduce the problem and how?

**Comment by matejk** [comment]
Additional changes in handling timeouts were done in #3725.

**Comment by matejk** [comment]
Can't be reproduced anymore.
