### ISSUE TITLE
Bug in ZIP code 1.6.0

### ISSUE THREAD

**Issue by MCoder42** [pocoproject/poco#828]
Poco library 1.6.0 compiled with Visual Studio Express 2013. 

Run \Zip\samples\zip example with this params:

```
zip /file=qqq.zip mainwindow.h
```

This sample produce broken CRC arhive file. 

Links to file and result archive:

http://www.lenmedia.ru/mainwindow.h
http://www.lenmedia.ru/qqq.zip

**Comment by obiltschnig** [comment]
This has already been fixed in develop and 1.6.1 branch.

**Comment by MCoder42** [comment]
Thank you. Develop branch work fine.
