### ISSUE TITLE
1.6.0: MongoDB aggregate $cmd fails with "wrong type for field (pipeline) 3 != 4"

### ISSUE THREAD

**Issue by matejk** [pocoproject/poco#829]
We use Poco::MongoDB from stable release 1.6.0.

I wanted to construct an aggregate command like this:

```C++
    Poco::MongoDB::Document::Ptr match(new Poco::MongoDB::Document());
    Poco::MongoDB::Document::Ptr group(new Poco::MongoDB::Document());
    Poco::MongoDB::Document::Ptr pipeline(new Poco::MongoDB::Array());

    match->addNewDocument("$match")
        .add("internal.tenant_id", containerID.toString());
    group->addNewDocument("$group")
        .add("_id", "$internal.tenant_id").addNewDocument("size")
        .add("$sum", "$static.size");

    pipeline->add("step0", match);
    pipeline->add("step1", group);

    auto request = m_db.createCommand();
    request->selector()
        .add("aggregate", "Object")
        .add("pipeline", pipeline);
```

selector().toString(2) gives this output:

```JSON
{
   "aggregate" : "Object",
   "pipeline" : [
     {"$match":{"internal.tenant_id":"b5fc860d-39d8-4e6f-a090-4e762bdf6ac5"}},
     {"$group":{"_id":"$internal.tenant_id","size":{"$sum":"$static.size"}}}
   ]
}
```

That seems to be valid according to the MongoDB 3.0.3 documentation:

http://docs.mongodb.org/manual/reference/command/aggregate/#dbcmd.aggregate

However, the command returns the following error:

```JSON
{
   "code" : 13111,
   "errmsg" : "exception: wrong type for field (pipeline) 3 != 4",
   "ok" : 0
}
```

indicating that "pipeline" is object, not array.

Does this indicate an error in serializing the command in Poco::MongoDB?

**Comment by matejk** [comment]
There is a similar issue when trying to create a bit more complex count query containing $in operator.

Code:

```C++
    auto countReq = m_db.createCountRequest("Object");

    Poco::MongoDB::Document::Ptr query(new Poco::MongoDB::Document());
    query->add("internal.container_id", containerID.toString());

    // Filter objects by the state given as parameter
    Poco::MongoDB::Document::Ptr stateArray(new Poco::MongoDB::Array());
    for (const auto s: states) {
        auto ss = Object::getStateString(s);
        stateArray->add("st-" + ss, ss);
    }
    query->addNewDocument("internal.state").add("$in", stateArray);
    Poco::MongoDB::Document::Ptr query(new Poco::MongoDB::Document());

    countReq->selector().add("query", query);

```

Stringified selector:

```JSON
{
  "count" : "Object",
  "query" : {
    "internal.container_id" : "b5fc860d-39d8-4e6f-a090-4e762bdf6ac5",
    "internal.state" : {
      "$in" : [
        "checksum-failure",
        "checksum-verified",
        "data-deleted",
        "transferred"
      ]
    }
  }
}
```

Response from the server (MongoDB 3.0.3):

```JSON
{
  "code" : 2,
  "errmsg" : "$in needs an array",
  "ok" : 0
}
```

**Comment by matejk** [comment]
The issue is still present in latest code on branch poco-1.6.1.

**Comment by fbraem** [comment]
In your last example with $in, you are using a Document for Array:

    Poco::MongoDB::Document::Ptr stateArray(new Poco::MongoDB::Array());

This sample works:

````
//SELECT players WHERE birthyear IN (1982, 1983)
void sample14(Poco::MongoDB::Connection& connection)
{
    std::cout << "*** SAMPLE 14 ***" << std::endl;

    Poco::MongoDB::Cursor cursor("sample", "players");
    Poco::MongoDB::Array::Ptr years = new Poco::MongoDB::Array();
    years->add("0", 1982);
    years->add("1", 1983);
    cursor.query().selector().addNewDocument("birthyear").add("$in", years);

    Poco::MongoDB::ResponseMessage& response = cursor.next(connection);
    while(1)
    {
        for(Poco::MongoDB::Document::Vector::const_iterator it = response.documents().begin(); it != response.documents().end(); ++it)
        {
            std::cout << (*it)->get<std::string>("lastname") << ' ' << (*it)->get<std::string>("firstname") << " (" << (*it)->get<int>("birthyear") << ')' << std::endl;
        }

        // When the cursorID is 0, there are no documents left, so break out ...
        if ( response.cursorID() == 0 )
        {
            break;
        }

        // Get the next bunch of documents
        response = cursor.next(connection);
    };
}
````

**Comment by fbraem** [comment]
Your first sample contains the same error:

     Poco::MongoDB::Document::Ptr pipeline(new Poco::MongoDB::Array());

must be 

     Poco::MongoDB::Array::Ptr pipeline(new Poco::MongoDB::Array());

**Comment by matejk** [comment]
Thanks for spotting this.

It confused me that toString() properly printed arrays but they were then not correctly serialised.

**Comment by matejk** [comment]
Query using $in and an array of simple values (strings) now works as expected.

However I still can't make the aggregation work properly. As you can see above, the pipeline array is printed, however not taking the indentation parameter into account, which is strange.

Aggregation is now executed but the result is the same as if the pipeline would be and empty array: all objects are returned in the aggregated result.

Shall MongoDB objects be added to an array as it can be seen in the sample code in the first comment?

**Comment by matejk** [comment]
I can't move forward with performing aggregation command using Poco::MongoDB.

The same aggregate command executed in MongoDB shell (db.players.runCommand) gives expected result.

New test case was added to the test suite in the cloned repo 06a99602e4be8e8038d36625fdab32101307d3fc (part of pull request #830).

Fails in the same way as in my code above.

**Comment by matejk** [comment]
Explaining the problem to someone else helps (as usually).

```C++
	pipeline->add("0", match);
	pipeline->add("1", group);
```
Changing the add lines as shown above solves the problem.

It is not really obvious that the name of an item being added to an MongoDB::Array must be stringified number.

**Comment by fbraem** [comment]
This is stated in the BSON spec for Array :

*Array - The document for an array is a normal BSON document with integer values for the keys, starting with 0 and continuing sequentially. For example, the array ['red', 'blue'] would be encoded as the document {'0': 'red', '1': 'blue'}. The keys must be in ascending numerical order.*

Maybe we can add an add function to Array that hides the stringified number ...

**Comment by matejk** [comment]
I think that would be useful.

Franky, thank you very much for your assistance.

I pushed some updates for version 1.6.1 to #830. Some of them might be generally useful.

Closing the issue. It was mostly my confusion with Poco::MongoDB.
