### ISSUE TITLE
Error compile library

### ISSUE THREAD

**Issue by MCoder42** [pocoproject/poco#831]
Apply for 1.6.0 and develop branch.
1. Download library
2. Unpack to directory C:\Poco
3. Change components file to:

```
Foundation
XML
JSON
Util
Net
Zip
```
1. From Visual Studio Express 2013 native tools command promt run build:

```
buildwin 120 build static_mt both Win32 nosamples notests wdexpress
```
1. When build get error:

```
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX  BUILD FAILED. EXITING. XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
1. In files we have:

**_C:\Poco\Foundation\testsuite\obj\TestSuite\debug_static_mt\TestSuite_vs120.log**_

```
1>LINK : fatal error LNK1104: cannot open file 'CppUnitmtd.lib'
     1>Done Building Project "c:\Poco\Foundation\testsuite\TestSuite_vs120.vcxproj" (Build target(s)) -- FAILED.

Build FAILED.
```

**C:\Poco\Foundation\testsuite\obj\TestLibrary\debug_shared\TestLibrary_vs120.log**

```
     1>LINK : fatal error LNK1104: cannot open file 'PocoFoundationd.lib'
     1>Done Building Project "c:\Poco\Foundation\testsuite\TestLibrary_vs120.vcxproj" (Build target(s)) -- FAILED.

Build FAILED.
```
1. Question: why testsuite compiled if we write in command line **notests** ?

Thank you.

**Comment by MCoder42** [comment]
Add:

If write
```
buildwin 120 build static_mt both Win32 nosamples
```
All work fine. And please can you add multithreaded compilation ?

**Comment by aleks-f** [comment]
> why testsuite compiled if we write in command line notests

Because devenv will build solution instead of the project if it finds the solution with the same name. From what I recall, not much we can do about it. Try msbuild.

> please can you add multithreaded compilation

You are welcome to send a contribution. I have no plans to spend much more time on the brain-dead batch build file, PowerShell script should work fine and we'll make it official for 1.7.0.
