### ISSUE TITLE
Failing to link shared library on Android

### ISSUE THREAD

**Issue by aaboyd** [pocoproject/poco#832]
I went through the Android build tutorial and I got things to build and run correctly when statically linking.  

I want to build shared libraries for android because you have to ship a .so file, when I try to link with poco I get the following errors.

Any ideas why this might work with static libraries and fail with shared libraries?

```
error: undefined reference to 'Poco::SystemException::SystemException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)'
error: undefined reference to 'Poco::SystemException::SystemException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)'
error: undefined reference to 'Poco::SystemException::SystemException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)'
error: undefined reference to 'Poco::SystemException::SystemException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)'
error: undefined reference to 'Poco::Net::HTTPMessage::setContentType(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
error: undefined reference to 'Poco::Net::NameValueCollection::find(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const'
error: undefined reference to 'Poco::Net::NameValueCollection::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const'
```
Any help would be much appreciated, any good ways to diagnose why those symbols are undefined?

**Comment by RangelReale** [comment]
I never built a shared library for android, but I know that android have several options for a c++ stdlib (none, glibc, stlport), these errors looks like some errors with it. Maybe you compiled with one library but linked the other?

**Comment by aaboyd** [comment]
If you never built a shared library with android, how exactly do you include it in an apk?  You need a .so not a ".a".  Is there a simple way I can take the .a that I build successfully and get it into a .so for distribution in apk?

**Comment by RangelReale** [comment]
I link the static library in each of my shared libraries, and never pass directly Poco classes between them.

**Comment by aaboyd** [comment]
@RangelReale thanks for the tip.  I will go ahead and do that as well.
