### ISSUE TITLE
Does Poco support redis client?

### ISSUE THREAD

**Issue by nanrenhaiyang** [pocoproject/poco#836]
redis is very popular,in internet company.I use Poco write server program.I think Poco provide support redis c++ ,will be more community members.

**Comment by aleks-f** [comment]
I think I understand what his issue is about: you would like to add [Redis](http://redis.io/) support to Poco. Please read [contributing guidelines](https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md) and act accordingly. Note that Redis does not build out of the box on Windows and, from what I have seen, authors seem to have no interest in that platform.

**Comment by nanrenhaiyang** [comment]
在 2015年05月27日 21:52, Aleksandar Fabijanic 写道:
>
> I think I understand what his issue is about: you would like to add 
> Redis <http://redis.io/> support to Poco. Please read contributing 
> guidelines 
> <https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md> and 
> act accordingly. Note that Redis does not build out of the box on 
> Windows and, from what I have seen, authors seem to have no interest 
> in that platform.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pocoproject/poco/issues/836#issuecomment-105919260>.
>
Thanks very much. I want to join you very much,but i am a beginner for 
c++.In order to join you as soon as possible i will try to study 
hard.This is just beginning.

**Comment by bachp** [comment]
May be you could give a short description what you would hope from Redis support in Poco?
I think this would help.

Some ideas that come to my mind are:
- A Poco style Redis client library
- A persistent enhancement for the `Poco::Cache` framework
- An additional persistence layer similar to MongoDB

**Comment by nanrenhaiyang** [comment]
在 2015年05月28日 05:02, Pascal Bach 写道:
>
> May be you could give a short description what you would hope from 
> Redis support in Poco?
> I think this would help.
>
> Some ideas that come to my mind are:
>
>   * A Poco style Redis client library
>   * A persistent enhancement for the |Poco::Cache| framework
>   * An additional persistence layer similar to MongoDB
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pocoproject/poco/issues/836#issuecomment-106073762>.
>
An additional persistence layer similar to MongoDb.
I've decided to code redis client using c++,and use in producttion platform.
acl::redis seems to be a good reference, i will read this code.
I will pull request, after stability.

**Comment by nanrenhaiyang** [comment]
https://github.com/RedisCppTeam/RedisCpp

i will finished it in a short time.i have used poco::Net in this redis client.i will use poco::Mutex and poco::Condition in redis pool(in the future). I have read acl lib and i think its readable and style is a question.  Could you give me some suggestion or help. Welcome to join us.

**Comment by fbraem** [comment]
Redis support is now available in develop branch: https://github.com/pocoproject/poco/tree/develop/Redis

**Comment by nanrenhaiyang** [comment]
We have coded a redis-client and pool.All command is suppored ,and use it in production platforms.
git@github.com:RedisCppTeam/redis-client.git
How to join Poco Team
