### ISSUE TITLE
Could poco::logger  save different messages into several files ? 

### ISSUE THREAD

**Issue by lion117** [pocoproject/poco#847]
hi , guys . 
## in the development  , i had **several components  whose error messages were required to record into independent log files** . instead of all messages recorded into one files.

i tried following steps to realize my purposes :  
for example :  i had two software components  : **ui component  and  data  component **
so   i wanna two log files  :  **ui_log**  ,  **data_log**  to keep independent log 
# my issue
### did I missed something important or  Poco::logger  only support to save messages into  one log file ?

``` C++
/// initialize logger when need 
void Logger_initiation( string t_filename , unsigned int t_max_size )
{
    string file_size = format("%uM", t_max_size);
    AutoPtr<FileChannel> file_channel(new FileChannel());
    file_channel->setProperty("rotation", file_size);
    file_channel->setProperty("archive", "timestamp");
    file_channel->setProperty("path", t_filename);
    AutoPtr<PatternFormatter> pattern_formatter(new PatternFormatter("Date :%y-%n-%d Time: %L%H:%M:%S \r\nPosition: %U\r\nCode line : %u\r\n%p: %t"));
    AutoPtr<FormattingChannel> formatter_channle(new FormattingChannel(pattern_formatter, file_channel));
    Logger::root().setChannel(filename, formatter_channle );
    ///- finish logger initiation
}
```
### recoard messages into different files  by **str_log_name**

``` C++

// record ui messages
poco_information(  (Logger::get("ui_log  ")) ,  str_msg);

// record data message 
poco_information(  (Logger::get("data_log")) ,  str_msg);
```

but the result is that  i get nothing  , no logs or messages had been recorded . 
in the   poco logger file , i fould there is a API 

``` C++
static void setChannel(const std::string& name, Channel* pChannel);
        /// Attaches the given Channel to all loggers that are
        /// descendants of the Logger with the given name.
```

but it didnot  work as i expected  . i knew i almost get there , but i didn't know what i missed . 
# my issue

**Comment by aleks-f** [comment]
See [LogRotation example](https://github.com/pocoproject/poco/blob/develop/Foundation/samples/LogRotation/src/LogRotation.cpp).
