### ISSUE TITLE
MailMessage::_encoding is not set when retrieving plain/text message

### ISSUE THREAD

**Issue by maiso** [pocoproject/poco#848]
If POP3ClientSession::retrieveMessage is used to retrieve a plain/text email message. It seems the MailMessage::_encoding is not being set.
Resulting in MailMessage::write not being able to find the right encoder, thus not printing the content to the stream.

I think there are two solutions, either to set the MailMessage::_encoding in MailMessage::readPart
Or have a default StreamCopier in MailMessage::writeEncoded

My version is: POCO 1.6.0-all (2014-12-22)

**Comment by aleks-f** [comment]
[duplicate](https://github.com/pocoproject/poco/issues/806)

**Comment by maiso** [comment]
Hello Aleks,

Sorry but this has nothing to do with that issue.

This is about econding, not the content -type.

When an email is received with plain/text with retrieveMessage with a multpartHandler.
MailMessage::read(std::istream& istr, PartHandler& handler) is called, which calls MailMessage::readPart.
Here the encoding is decided, but nowhere the MailMessage ::_econding variable is set.

So if you decide to use MailMessage::write right after receiving. The code will try to use writeEncoded(istr, ostr, _encoding); with an unset _encoding variable.
Which results in only the header being printed and not the body.
Even though the _encoding could have set, becuase it was decided in MailMessage::readPart.

So as mentioned before, there are two solutions.
Either to set the MailMessage::_encoding in MailMessage::readPart 
Or have a default StreamCopier in MailMessage::writeEncoded

**Comment by aleks-f** [comment]
Send a pull request to develop branch if you want it fixed quickly.

**Comment by maiso** [comment]
Sorry no time for pull request. We've fixed it and recompiled it ourselfs like this. In MailMessage.cpp
```
void MailMessage::readPart(std::istream& istr, const MessageHeader& header, PartHandler& handler)
{
	std::string encoding;
	if (header.has(HEADER_CONTENT_TRANSFER_ENCODING))
	{
		encoding = header.get(HEADER_CONTENT_TRANSFER_ENCODING);
		// get rid of a parameter if one is set
		std::string::size_type pos = encoding.find(';');
		if (pos != std::string::npos)
			encoding.resize(pos);
	}
	if (icompare(encoding, CTE_QUOTED_PRINTABLE) == 0)
	{
		QuotedPrintableDecoder decoder(istr);
		handlePart(decoder, header, handler);
		_encoding = ENCODING_QUOTED_PRINTABLE;
	}
	else if (icompare(encoding, CTE_BASE64) == 0)
	{
		Base64Decoder decoder(istr);
		handlePart(decoder, header, handler);
		_encoding = ENCODING_BASE64;
	}
	else
	{
		if (icompare(encoding, CTE_7BIT) == 0)
			_encoding = ENCODING_7BIT;
		else if (icompare(encoding, CTE_8BIT) == 0)
			_encoding = ENCODING_8BIT;

		handlePart(istr, header, handler);
	}
}
```
