### ISSUE TITLE
Compilation of Error.cpp in Foundation fails using Intel's C++ Compiler on OS X

### ISSUE THREAD

**Issue by LogicalKnight** [pocoproject/poco#855]
Using the latest available C++ compiler from Intel (`icpc (ICC) 15.0.3 20150408`) on OS X (10.10), building Poco fails on `Foundation/src/Error.cpp` with the following error:

    Error.cpp(71): error: no instance of constructor "std::__1::basic_string<_CharT, _Traits, 
    _Allocator>::basic_string [with _CharT=char, _Traits=std::__1::char_traits<char>, 
    _Allocator=std::__1::allocator<char>]" matches the argument list
            argument types are: (int)
  		return std::string(strerror_r(errorCode, errmsg, 256));

It seems that the problem is that the GNU version of `strerror_r` is expected since the compiler is defining `_GNU_SOURCE`, whereas the `strerror_r` function used is really the POSIX version that returns an int. I'm going to guess that it's really a problem with the Intel compiler inappropriately defining `_GNU_SOURCE` somewhere.

My current "fix" is patching Error.cpp to include a check for `__INTEL_COMPILER` and `__APPLE__` at the same time, and ignoring the `__GNU_SOURCE` define in that case. Is there a better, more robust fix?

I've tested this using the 1.6.0 release and the latest commit on develop.

**Comment by aleks-f** [comment]
Please send pull request for this and we will review/comment.
