### ISSUE TITLE
Put PostgreSQL adapter in the mainstream release

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#857]
Hi

As for Data/MySQL, I would like to have the PostgreSQL adapter into the mainstream instead of a specific branch/contrib. Is there any plan for doing so?

zosrothko

**Comment by seb777** [comment]
+1

**Comment by kmribti** [comment]
+1

**Comment by obiltschnig** [comment]
AFAIK it needs a bit more work, but we plan to release it with 1.7.

**Comment by zosrothko** [comment]
That's a good news...

Thanks for allowing this enhancement.

**Comment by aleks-f** [comment]
@intensifi is in charge of that and can provide accurate info on it.

**Comment by intensifi** [comment]
I need time to figure out what I have wrong for the cmake build environment.  Any help would be appreciated.   This is the only blocker issue I know of.

Aleks, does anything else come to mind?

I would like to optimize the BLOB code in extractor.cpp and binder.cpp.  But that is not a blocker.

**Comment by cpt1gl0** [comment]
So will the PostgreSQL adapter be released any time soon?
