### ISSUE TITLE
sqlite distribute file lost   issue feedback 

### ISSUE THREAD

**Issue by lion117** [pocoproject/poco#859]
hey , guys . there is a issue in the  distribute   :  [poco-1.6.0-release](https://github.com/pocoproject/poco/releases)
## issue

> in the [SQLite include folder](https://github.com/pocoproject/poco/tree/develop/Data/SQLite/include/Poco/Data/SQLite) ,   **sqlite3.h** file is lost : , without this file , complier would report error .

of coulse , the file could be found in the  [souce folder](https://github.com/pocoproject/poco/tree/develop/Data/SQLite/src)

---

> hope this issue could be solved in the next release version

**Comment by aleks-f** [comment]
What error is reported by compiler?

**Comment by lionm117** [comment]
when add  the head file   
**Binder.h**  which in **Data\SQLite\include** path , compiler would report error   : 
> fatal error C1083: Cannot open include file: 'sqlite3.h': No such file or directory

in the**Binder.h**   it have one code line :  **#include "sqlite3.h"**  , but no head file could found in the folder. so i add the head file from src folder ,  compile error gone
