### ISSUE TITLE
Poco 1.6.0 cannot be built as dynamic lib using cmake

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#868]
From [forum](http://pocoproject.org/forum/viewtopic.php?f=12&t=6546):

Unread postby dmitryshm » Fri Jun 19, 2015 1:41 pm

When I try to build Poco 1.6.0 using cmake as dynamic lib in my KUbuntu 14.04 I get error.

E.g. I enter these commands in poco dir

```
$: mkdir linux_build
$: cd linux_build
$: cmake ..
$: make
```

and get this error

```
make[2]: *** No such rule for target `lib/libPocoFoundation.so.1-all (2014-12-22).6-all (2014-12-22).0-all (2014-12-22)', for `lib/libPocoXML.so.30'.  Stop.
make[1]: *** [XML/CMakeFiles/XML.dir/all] Error 2
make: *** [all] Error 2
```

But when I build Poco as static lib using 

```
cmake -DPOCO_STATIC ..
```

there're no errors.

So there're errors in Poco CMakeLists.

**Comment by bachp** [comment]
I don't have access to a Ubuntu 14.04 machine at the moment.
I will have a look at it next week.

**Comment by tuckerwales** [comment]
Hi, is there any update on this? 

I have the same issue when attempting to cross-compile for ARM from a x86_64 machine. I can also confirm that this does not happen when built as a static library.

**Comment by bachp** [comment]
I'm unable to reproduce this. Could you provide some more information.
What CMake version are you using?
What's the exact poco version used?

**Comment by nanrenhaiyang** [comment]
poco1.6
fedora26
cmake 3.9.0

-

**Comment by Bjoe** [comment]
For the sake of completeness in `poco-1.9.1` and `develop` branch, the cmake build is building dynamic libs.
