### ISSUE TITLE
Conventional Changelog

### ISSUE THREAD

**Issue by bufferoverflow** [pocoproject/poco#875]
What about introducing Conventional Changelog and generate CHANGELOG.md automatically?

here's an example of a generated changelog:
https://github.com/angular/angular.js/blob/master/CHANGELOG.md

and the tool to generate is here https://www.npmjs.com/package/conventional-changelog

**Comment by aleks-f** [comment]
Yeah, we are not very good about keeping up with changelog entries as we go, so we usually have to go back through commit history and recreate them - painful process.

It looks like this would require following convention when committing and we would need to establish a point when we start following this convention? @obiltschnig ?

**Comment by obiltschnig** [comment]
I'm generally in favor of anything that saves us work, but we'll have to improve our commit messages significantly (me included ;-) We could introduce it after 1.7.0. The other issue is the changelog in the generated SDK documentation, which must also be kept up-to-date. Right now it's just a copy-paste of the main CHANGELOG with some minor formatting applied.
