### ISSUE TITLE
Poco::Data::SQLite

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#877]
When you use the recordset to access to the records the column type INTEGER are miss translated, because INTEGER is translated as INT32, but in SQLite INTEGER type is potentially 64BIT
So I think the correct way is to translate to a 64 bit integer type
https://www.sqlite.org/datatype3.html#affinity

**Comment by aleks-f** [comment]
[duplicate](https://github.com/pocoproject/poco/issues/703
