### ISSUE TITLE
UUID tryParse

### ISSUE THREAD

**Issue by lucianmli** [pocoproject/poco#878]
Hello,

In the code for tryParse there isn't a check that the characters are in the  0-9a-fA-F range. So for an uuid like b0a6fe41-a360-6e22-3381-7de3410b4z07, the result of try parse is true.

Also the size should be exactly 36 chars with hyphens or it will also return true for 
b0a6fe41-a360-6e22-3381-7de3410b4z07zzzz.

 And if the format without hypes is supported, size should be restricted to exactly 32 chars,

[RFC4122](http://tools.ietf.org/html/rfc4122) states that the chars should be hex digits.

**Comment by Antauri** [comment]
On the same note, UUIDv5 (sha-1 name based) should be supported in the version enum (already in Boost).

**Comment by intensifi** [comment]
Günter,

I sent you a code fix a couple years back for this issue from my Neural ID email account.  This was pre-Github.  Do you still have it?
