### ISSUE TITLE
parseHex accepts invalid syntax and does not throw an exception

### ISSUE THREAD

**Issue by monohydroxy** [pocoproject/poco#880]
parseHex("0x99a") will return 0x9d8 instead of throwing an exception.
parseHex("xxx") will return 0 instead of throwing an exception.

It appears that the switch statement for 'x' in strToInt() can fall through to the '1' case and modify result.

**Comment by aleks-f** [comment]
can't reproduce this, must have been fixed somehow (although the first case reported made no sense to start with - 0x99a is a valid hex)
