### ISSUE TITLE
Poco::Event_POSIX tryWait(long) not resiliant to clock change

### ISSUE THREAD

**Issue by mellery451** [pocoproject/poco#884]
The current implementation of tryWait(long) for POSIX platforms is uses CLOCK_REALTIME and gettimeofday() to specify the duration of the pthread_cond_timedwait(). If the system clock is set backwards while waiting, the timer expiration is compromised. I believe this is counter to the spirit of the interval timer interface that is implied. 

At a minimum, this deficiency should be documented. Better yet, using CLOCK_MONOTONIC to initialize the condition variable might help, but it is not available on all POSIX platforms.

**Comment by bachp** [comment]
I think this is fixed with f89bea4411c7949c19492c07f44980299cd02472 included in version 1.7.5

**Comment by obiltschnig** [comment]
Yes.
