### ISSUE TITLE
Poco::JSON::Array  preserveInsertionOrder =true  stringify is error

### ISSUE THREAD

**Issue by bleach3** [pocoproject/poco#885]
hello ,I use Poco::JSON::Array .stringify  is error where  preserveInsertionOrder =true.
final,I'm found error.(english is poor,so  wirte code)

demo.cpp:

Object jObj2(true);//-------->use preserveInsertionOrder=true

```
std::string  strValue2="[{\"backspace1\":\"bs2222\",\"1backspace1\":\"1bs2222\"},{\"te1\":\"t1\",\"t2\":\"t2\"}]";
jObj2.set("car", "这是中文abc@qwe.com1231");
jObj2.set("baz", "fas");
```

Poco::JSON::Array  array1;
array1.add(jObj2);

--->\Poco\Dynamic\Var.h

Var(const T& val)
        /// Creates the Var from the given value.
# ifdef POCO_NO_SOO

```
    : _pHolder(new VarHolderImpl<T>(val))
{
}
```
# else

```
{
    construct(val);
}
```

new VarHolderImpl<T>(val)  --->change Object._values with Object._keys relation

JSON\src\Object.cpp:

 Object._values  not match _keys

```
    void Object::set(const std::string& key, const Dynamic::Var& value)
    {
        _values[key] = value;
        if (_preserveInsOrder)
        {
            KeyPtrList::iterator it = _keys.begin();
            KeyPtrList::iterator end = _keys.end();
            for (; it != end; ++it)
            {
                if (key == **it) return;
            }
            _keys.push_back(&_values[key]);
        }
    }

    const std::string& Object::getKey(KeyPtrList::const_iterator& iter) const
    {
        ValueMap::const_iterator it = _values.begin();
        ValueMap::const_iterator end = _values.end();
        for (; it != end; ++it)
        {
            if (&it->second == *iter) return it->first;
        }


        throw NotFoundException((*iter)->convert<std::string>());//---------------->without _keys!=_values.

    }
```

+++++++++++++++++++++++++++++++++++++++++
I have change \Poco\JSON\Object.h  \Poco\JSON\Object.cpp

typedef std::dequeDynamic::Var                   KeyPtrList;

void Object::set(const std::string& key, const Dynamic::Var& value)
{
    _values[key] = value;
    if (_preserveInsOrder)
    {
        KeyPtrList::iterator it = _keys.begin();
        KeyPtrList::iterator end = _keys.end();
        for (; it != end; ++it)
        {
            if (key == *it) return;
        }

```
    std::cout<<"key="<<key<<",&_values[key]="<<&_values[key]<<",&value"<<&value<<",_values[key]="<<value.toString()<<std::endl;

    Dynamic::Var v1=key;
    _keys.push_back(v1);
}
```

}

const std::string& Object::getKey(KeyPtrList::const_iterator& iter) const
{
    ValueMap::const_iterator it = _values.begin();
    ValueMap::const_iterator end = _values.end();
    for (; it != end; ++it)
    {
        //const Dynamic::Var  keyValue=*iter;
        //const Dynamic::Var \* mapValue=&it->second;
        //void \* p=(void *)(&it->second );
        //void \* p2=(void *)(&iter);

```
    if (iter->toString().compare(it->first.c_str())==0) 
        return it->first;
}

throw NotFoundException((iter)->convert<std::string>());
```

}

_keys match _values key.

Is there a better way?

**Comment by aleks-f** [comment]
Preservation of insertion order for objects was [fixed in develop branch](https://github.com/pocoproject/poco/issues/819)
