### ISSUE TITLE
VS 2015 support

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#890]
As stated in the subject

**Comment by bakercp** [comment]
Not sure if it's helpful, but we've got Poco compiled for VS2015 over @openFrameworks.  @domamato did a lot of work on that and might have some scripts / solutions / configs laying around.

**Comment by aleks-f** [comment]
thanks, any help is welcome. We do have a [VS project generator tool](https://github.com/pocoproject/poco/tree/develop/ProGen), though. So, if you feel inclined to help, you could either add support for 2015 or give us some hints how much work it will be. If file format did not change from 2013, there should not be too much to do.

**Comment by DomAmato** [comment]
It was pretty easy, I just had it upgrade from the 2013 projects that was in the download and edited the buildWin.cmd file to automate the whole process.
