### ISSUE TITLE
Impossible to login at Forum

### ISSUE THREAD

**Issue by AlexanderShniperson** [pocoproject/poco#895]
Hi.

I cant login to forum, this is last place where i can contact with Poco team.
I registered new user, activate account by clicking link in email but can't login "user not found", restore password does not work because "user not found".
I wrote message to forum Administrator, but not get answer more then 2 weeks.

Any one life here?
Can you please investigate what is wrong?

Email is: alex.shniperson at gmail dot com

Thanks.

**Comment by obiltschnig** [comment]
Please try registering again. We've had some database issues a couple of days ago, so it could be your newly registered account was lost.

**Comment by AlexanderShniperson** [comment]
i try with usage of my email, but forum tell me that email is used, maybe you remove my account and i try again?

**Comment by obiltschnig** [comment]
You should have received another activation email. Did you get it?

**Comment by AlexanderShniperson** [comment]
yes i get it, thank you!

**Comment by AlexanderShniperson** [comment]
still something wrong, i cant recover my password

**Comment by obiltschnig** [comment]
Strange. What does it say? Anyway, I have deleted your account. Try to create a new one.

**Comment by AlexanderShniperson** [comment]
it say something "user not found", i created account again and now it is works, thank you very much.
