### ISSUE TITLE
Sample "TwitterClient" of NetSSL_OpenSSL can't be build

### ISSUE THREAD

**Issue by DonChunior** [pocoproject/poco#896]
Version 1.6.1 of POCO C++ Libraries is concerned.
My build system is Visual Studio 9.0 (2008) and I've installed Win32 OpenSSL 1.0.2d.

The build configuration "**debug_static_mt**" of the sample "**TwitterClient**" (part of NetSSL_OpenSSL) ends up in errors (90 unresolved externals; error LNK2019, LNK2001 and LNK1120).

**Comment by Yendolosch** [comment]
Seems like in every TwitterClient Visual Studio project, both 32 and 64 bit and from vs90 to vs140, is missing the linker dependencies for the correct versions of both `libeay32.lib` and `ssleay32.lib` in the static release and debug configurations.

In other words, everything from `TwitterClient_vs90.vcproj` to `TwitterClient_x64_vs140.vcxproj` needs either
* `libeay32MT.lib` and `ssleay32MT.lib`, 
* `libeay32MTd.lib` and `ssleay32MTd.lib`,
* `libeay32MD.lib` and `ssleay32MD.lib`, or
* `libeay32MDd.lib` and `ssleay32MDd.lib`

in the `AdditionalDependencies` of their `(debug|release)_static_m(d|t)` build configurations.

**Comment by AlisaYe** [comment]
we also have the same problem in poco version 1.9.0
