### ISSUE TITLE
Need help fixing CMake in PostgreSQL branch

### ISSUE THREAD

**Issue by intensifi** [pocoproject/poco#900]
@bachp Pascal,  

Aleks said you might be able to teach/tell me what I am getting wrong. 

Thanks in advance!

**Comment by bachp** [comment]
I will have a look as soon as I'm back next week.

**Comment by Bjoe** [comment]
For the sake of completeness in `poco-1.9.1` and `develop` branch, the cmake build is building PostgreSQL support in Poco.
I think this issue is fixed.
