### ISSUE TITLE
CLOB File Insert/Select Database Corruption

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#902]
From [forum](http://pocoproject.org/forum/viewtopic.php?f=12&t=6587):

postby gavin1958wood » Wed Aug 05, 2015 7:49 am

Environment is Server 2008, PostgreSQL ODBC

I can save a file CLOB into the database and the contents are correct, field is of type bytea 
When I read the CLOBits corrupted. Data corruption occurs after the 256 value.
For test I am saving a text file; aim is to save a binary file; using Base64

Any ideas why when I read the CLOB from the database its contents are corrupted after byte 255?
Is there a property I have to set for max read size or something similar?
```
// Save CLOB to database field type is bytea
// The file is correctly stored into the database, verified by PostgreSQL command line query
Poco::Data::CLOB:: blob(encoded_oss.str().c_str(), encoded_oss.str().size());
Poco::Data::Statement insert_statement(session);
insert_statement << "INSERT INTO irl_files_table (file) VALUES(?) RETURNING(pk)",
Poco::Data::Keywords::use(blob),
Poco::Data::Keywords::into(pk);
insert_statement.execute();

// Read file from Database
// Read CLOB size is correct, but the data corruption occurs after byte 255
Poco::Data::CLOB readClob;
Poco::Data::Statement select_statement(session);
select_statement << "SELECT file FROM irl_files_table WHERE pk=?",
Poco::Data::Keyworks::use(pk),
Poco::Data::Keywords::into(readClob);
select_statement.execute();
```

**Comment by kostya-lnk-ms** [comment]
When it comes to PostgresODBC, there is a number of ODBC driver settings.
I'd suggest you to try running the ODBCPostgreSQLTest::testBLOB test and take a look at its code and how the driver is set up for the test ODBCPostgreSQLTest.cpp

That also depends on how that blob column is declared in your DB schema.

**Comment by gavin1958wood** [comment]
Thanks for the info regarding ODBCPostgreSQL.cpp, that solved my problem.
Mods were updating connection string to include ByteaAsLongVarBinary and updating maxFieldSize

// Added ByteaAsLongVarBinary=1 to the connection string
Poco::Data::Session session(
"ODBC",
"Driver={PostgreSQL ANSI}; Server=127.0.0.1; DSN=PostgresSQL30; Database=wtsdb; Uid=postgres; Pwd=admin; ByteaAsLongVarBinary=1;"
);

// Sets the maximum field size property to 1Mb
const std::size_t field_size(1000000);
session.setProperty("maxFieldSize", Poco::Any(field_size));
