### ISSUE TITLE
Generating custom open SSL cipher keys

### ISSUE THREAD

**Issue by benoitbleuze** [pocoproject/poco#912]
Hi all,

I have a problem with an assumption made in the Cipher Key implementation. First a disclaimer, I am far from an open SSL expert, and that was one among many reason why our team started using poco, which is a great piece of software.

If one looks at [CipherKeyImpl.cpp](https://github.com/pocoproject/poco/blob/develop/Crypto/src/CipherKeyImpl.cpp)
one would find that the key and Iv are created by using user-provided password, salt (if not empty), and number of iteration for the generation.

This is fine, but insufficient for my use. Open SSL can accept more arguments, such as different digest algorithm. I must read encrypted data that use keys that employ a SHA1 digest. 

Here is the part of the code "tailored" for MD5:

```cpp
void CipherKeyImpl::generateKey(
	const std::string& password,
	const std::string& salt,
	int iterationCount)
{

// ...

// Now create the key and IV, using the MD5 digest algorithm.
	int keySize = EVP_BytesToKey(
		_pCipher,
		EVP_md5(),
		(salt.empty() ? 0 : saltBytes),
		reinterpret_cast<const unsigned char*>(password.data()),
		static_cast<int>(password.size()),
		iterationCount,
		keyBytes,
		ivBytes);
```

My obvious solution would be : 

* Change the interface of this function, and all the constructors needed to add a new parameter being `digest`. 
* Choose a data structure to identify digests (enum? string, the same way the cipher names are encrypted?)
* still keep a default to MD5 to not break backward compatibility

Is it a change the poco team would be interested upstream? if yes do you have any suggestion to improve, or fix issues I would not have found when thinking about this improvement?

**Comment by benoitbleuze** [comment]
I will bump my own post, by adding I have seen there is a constructor in `CipherKey` that takes a `key` and an `iv` vectors, and one could use this constructor to use any digest they want, but a very good feature of the poco library is to abstract oneself of any direct linking dependency on open-ssl. 


Also since last time, I found `EVP_get_digestbyname()` which is the best candidate to use the open ssl sanctioned list of digests, without creating a list of digests in poco itself. I would use these strings (similarly to the cipher name) to set the digest, raising the same exception as the one raised for unknown cipher names.

Is anyone in the core team interested in receiving such a patch?

**Comment by obiltschnig** [comment]
Yes, that sounds useful. Pull request welcome ;-)

**Comment by benoitbleuze** [comment]
Patch merged upstream, I guess we can close this issue then :-)
