### ISSUE TITLE
develop branch: The Crypto project seems inconsistent

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#918]
Hi

It seems that the Crypto project  of the develop branche be inconsistent. Here the log

make[1]: Entering directory `/home/francis/poco/Crypto'
** Compiling src/CipherFactory.cpp (debug, shared)
g++  -Iinclude -I/home/francis/poco/CppUnit/include -I/home/francis/poco/CppUnit/WinTestRunner/include -I/home/francis/poco/Foundation/include -I/home/francis/poco/XML/include -I/home/francis/poco/JSON/include -I/home/francis/poco/Util/include -I/home/francis/poco/Net/include -I/home/francis/poco/Crypto/include -I/home/francis/poco/NetSSL_OpenSSL/include -I/home/francis/poco/NetSSL_Win/include -I/home/francis/poco/Data/include -I/home/francis/poco/Data/SQLite/include -I/home/francis/poco/Data/ODBC/include -I/home/francis/poco/Data/MySQL/include -I/home/francis/poco/Zip/include -I/home/francis/poco/PageCompiler/include -I/home/francis/poco/PageCompiler/File2Page/include -I/home/francis/poco/PDF/include -I/home/francis/poco/CppParser/include -I/home/francis/poco/MongoDB/include -I/home/francis/poco/PocoDoc/include -I/home/francis/poco/ProGen/include -Wall -Wno-sign-compare -DPOCO_BUILD_HOST=obelix  -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -c src/CipherFactory.cpp -o /home/francis/poco/Crypto/obj/Linux/x86_64/debug_shared/CipherFactory.o
In file included from include/Poco/Crypto/CipherKeyImpl.h:24:0,
                 from include/Poco/Crypto/CipherKey.h:24,
                 from src/CipherFactory.cpp:19:
include/Poco/Crypto/OpenSSLInitializer.h:26:28: fatal error: openssl/crypto.h: No such file or directory
compilation terminated.
make[1]: *** [/home/francis/poco/Crypto/obj/Linux/x86_64/debug_shared/CipherFactory.o] Error 1
make[1]: Leaving directory `/home/francis/poco/Crypto'
make: *** [Crypto-libexec] Error 2
[

[francis@obelix poco]$ git remote show origin
* remote origin
  Fetch URL: https://github.com/pocoproject/poco.git
  Push  URL: https://github.com/pocoproject/poco.git
  HEAD branch: develop

  Local branch configured for 'git pull':
    develop merges with remote develop
  Local ref configured for 'git push':
    develop pushes to develop (up to date)

**Comment by aleks-f** [comment]
What do you mean by "inconsistent"? For posix, you must have openssl installed and headers/libraries in path to build on your system.

**Comment by zosrothko** [comment]
OK, its an mistake from my side, I have openssl installed but not the 
openssl-devel package!
Sorry for the noise

Le 21/08/2015 15:21, Aleksandar Fabijanic a écrit :
>
> What do you mean by "inconsistent"? For posix, you must have openssl 
> installed and headers/libraries in path to build on your system.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pocoproject/poco/issues/918#issuecomment-133423962>.
>


This email has been protected by YAC (Yet Another Cleaner) http://www.yac.mx
