### ISSUE TITLE
XMLStreamParser: merge QName and Name

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#923]
The Name and QName classes are largely equivalent. Get rid of QName class and extend Name as necessary to use it with XMLStreamParser

**Comment by mkrivos** [comment]
I spent some hours with replacing QName for Name and I am not very much satisfied with result. The code is not committed still and is nor beauty nor as efficient as original. The main source of problem is different behaviour with handling prefix versus qname. If you want, I can send intermediate result by email. IMHO maybe we want both classes there ...

**Comment by obiltschnig** [comment]
Did the same a couple of days ago and also basically gave up. While it was relatively easy to replace QName with Name in the external interfaces, the blocking point was the parser's namespace stack, which also uses QName. So I'd say we'll keep QName in the stream parser.
