### ISSUE TITLE
How to get _id of last inserted record.

### ISSUE THREAD

**Issue by manthanrtilva** [pocoproject/poco#930]
I need to use _id of last inserted record in my program to update that record letter on. 
I go through the documentation, sample,test suite and source code of API as well. But I am unable to locate such thing. Can you guide me how to do this?

Thanks in Advance.

**Comment by aleks-f** [comment]
There is no such thing in Poco::Data API. You will have to use your back-end native facilities. Here's a (very old) [discussion on the topic](http://sourceforge.net/p/poco/feature-requests/60/)
