### ISSUE TITLE
Prepared statement

### ISSUE THREAD

**Issue by banka50** [pocoproject/poco#932]
Why Poco::Data::Statement always recompile statement before execution?

Is it a bug or i missed something?

**Comment by obiltschnig** [comment]
Seems to contradict the notion of prepared statements? But I may be missing something. @aleks-f?

**Comment by aleks-f** [comment]
It's been like that from the beginning of time. I'm not sure if it has to be for some reason.

**Comment by Popovich** [comment]
Look [here](https://github.com/pocoproject/poco/blob/develop/Data/src/Statement.cpp#L106).
After statement execution it's state become ST_DONE, so next time when you use same statement it will be reset and state will be ST_RESET.
