### ISSUE TITLE
Change in JSON::Object::set(key,value) behavior in 1.6.1

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#933]
void Object::set(const std::string& key, const Dynamic::Var& value)
{
//Calling with preserverInsOrder == false.
New code doesn't overwrite existing value:
std::pair<ValueMap::iterator, bool=""> ret = _values.insert(ValueMap::value_type(key, value));
if (_preserveInsOrder)
Old code overwrote existing value:
_values[key] = value;
if (_preserveInsOrder)

Was this intentional? If so it should be documented, if not, add test case to make sure it gets overwritten.

(from https://sourceforge.net/p/poco/bugs/633/)

**Comment by obiltschnig** [comment]
Comment on SourceForge by Tom Gissel:
Typically bahvior changes should be reserved for major version releases. This change is likely to break downstream users of who move up to Poco 1.6.1 from Poco 1.6.0, as it did in our case. We only caught the change, and found this bug, becuse our automated unit tests started failing after the upgrade to Poco 1.6.1

**Comment by obiltschnig** [comment]
_values.insert(ValueMap::value_type(key, value)); 
is probably wrong as it won't overwrite an existing value. @fbraem?

**Comment by aleks-f** [comment]
Fixed, the second question is irrelevant

**Comment by obiltschnig** [comment]
fixed in 1.6.2 branch as well
