### ISSUE TITLE
Thread::join hangs forever if Thread::start has not been called

### ISSUE THREAD

**Issue by mattias-nilsson** [pocoproject/poco#936]
I realize that this of cause is a miss-use of the library, but the consequences are of the fault are problematic. A workaround is to only call join in case tid() is set, but I think join should do that check and either ignore it or throw an exception in case tid()==0.
This occurs with pthreads on linux, not sure about other platforms.

class Work:public Poco::Runnable{
public:
    void run(){
    }
};

int main(){
    Work work;
    Poco::Thread thread;

    //thread.start(work);
    thread.join(); // hangs if start not called

    return 0;
}

**Comment by obiltschnig** [comment]
At least with 1.6 and later releases this should not happen, as there's a test in join() and I've added a testcase to verify this. Could happen with 1.4.x, though.

**Comment by mattias-nilsson** [comment]
Yes, I we see this issue in 1.4.5. I just retested with 1.6 and it works as expected.
Thanks for the quick response!
