### ISSUE TITLE
CMake build produces libPocoFoundation.1.6.1.dylib (or .so)

### ISSUE THREAD

**Issue by mikedld** [pocoproject/poco#944]
Autoconf-based build only produces libPocoFoundation.dylib and libPocoFoundation.31.dylib (and their debug counterparts with "d" suffix) on Mac (or .so on other *NIX systems), but CMake-based build also has libPocoFoundation.1.6.1.dylib with former two being symlinked to it. This discrepancy was introduced by pull request #574 (commit b69fafb) and is about Foundation library only. The issue is that when one wants to use `$<TARGET_FILE:Poco::Foundation>` (e.g. to copy the file for distribution), path to libPocoFoundation.1.6.1.dylib is returned, but linking is being made against the libPocoFoundation.31.dylib.

**Comment by bachp** [comment]
This sounds like a Mac only Problem, and at the moment I'm not really equipped to debug this.

By saying it is about the Foundation library only, do you mean the other libraries like PocoUtil is behaving differently?

Could you provide me the content of the generated `PocoFoundationTargets.cmake` file and another generated file like `PocoUtil.cmake` that is behaving as expected?

**Comment by mikedld** [comment]
All the other libraries are fine (read: have only libPocoFoundation.dylib and libPocoFoundation.31.dylib). I don't believe it's a Mac-only issue, but I didn't try reproducing it on other *NIX systems.

Here's the info you request: https://gist.github.com/mikedld/b88a9d351ed04d2142b3 (note the different is actually in `Poco*Targets-<config>.cmake` files).

**Comment by mikedld** [comment]
As hinted in the comment to the aforementioned commit, changing `VERSION ${PROJECT_VERSION}` back to `VERSION ${SHARED_LIBRARY_VERSION}` fixes it for me.
