### ISSUE TITLE
Inconsistency in naming version of libs or shared libs among platforms

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#948]
Hi

I noticed that the version format given to libs or shared libs is quite a bit inconsisten. For exemple

on Windows:               PocoZip.dll
on Linux/Unix:             libPocoZip.so.40
on Cygwin                  cygPocoZip.40.dll
on Cygwin/CMake      cygPocoZip-40.dll

This is not a real issue but is forces developper to think differently when looking for the "real" name of a shared libs. I would suggest to to have a unqie format for version naming.

**Comment by bachp** [comment]
Hi

The question is if we want to have:
1. Our own naming convention which is the same accross all platforms.
2. Adhere the the conventions of the platform.

I would say approach two is the better way. But as I don't know the conventions on all systems sombody might be able to help out and we can collect how the libraries should be named on each platform to correspond to the convention.

**Comment by aleks-f** [comment]
I would just align the Cygwin make/cmake names, the rest is ok because links are created, e.g. `libPocoZip.so -> libPocoZip.so.40`

**Comment by bachp** [comment]
It looks like the cyg prefix is also used in the Poco SharedLibrary loader:
https://github.com/pocoproject/poco/blob/develop/Foundation/src/SharedLibrary_UNIX.cpp#L105

I also had a look into a cygwin installation and it seams that most cygwin libraries indeed follow the same convention as CMake `cyg<libname>-<soversion>.dll`.

I think the cygwin Make version should be adjusted to correspond to the cygwin convention.

**Comment by obiltschnig** [comment]
It used to be that way in the make-based build system also. Don't know when and why this was changed.

**Comment by bachp** [comment]
I created a wiki page where I try do document the naming conventions: https://github.com/pocoproject/poco/wiki/Library-Naming-Conventions

It is only partially complete, Maybe you can help completing it.

**Comment by zosrothko** [comment]
HI

I added the function SharedLibrary::prefix() for providing the shared library prefix as specified by the standard of the target platform. This is a way to improve portability of the SharedLibrary::load() function among all platforms. Cygwin states that the prefix "cyg" should be used to differentiate Cygwin dll from MinGW dll in the same directory (see https://cygwin.com/cygwin-ug-net/dll.html for discussion). This is a pure naming convention as the name of the shared library can work without the "cyg" prefix. Since Poco is targeting also to run on MinGW platform, I presume it is a good choice to follow this naming standard. Thus, as suggested by Aleks, I will align on Cygwin the libversion format with the Linux one (the '-' beeing replaced by a '.') but the '.ddl' suffix will remain at the end because it is a mandatory requirement of Windows. (That's why I was willing to use <prefix><libname>.<libversion>.<libsuffix> even for Linuces)

So the final schema will be

on Windows: PocoZip.dll
on Linux/Unix: libPocoZip.so.40
on Cygwin cygPocoZip.40.dll
on Cygwin/CMake cygPocoZip.40.dll

Everybody agreed?

BY the way, could you tell me what is the meaning of the libversion? (Is there a relationship betwwen the libversion and the Tag name of the Poco version?) When the libversion is incremented? By which number shema?

**Comment by obiltschnig** [comment]
on OS X it's libPocoZip.40.dylib

libversion is basically incremented for every POCO release. In theory it's supposed to be incremented when the binary interface of the library changes. Since this happens very easily in C++ (e.g., modifying the data members or virtual functions of a class) we do it with every release, as we don't track or make efforts for binary backwards compatibility. Furthermore, since we adopted the convention to increment it by 10 with every minor release change (so 1.6.0 is 30, 1.6.1 is 31, 1.6.2 is 32, etc. and 1.7.0 will be 40).
This is also the reason why we don't follow the usual .so naming convention with major and minor release number, as this would just add to confusion, as the major .so version number would have to change with every release and the minor version number would practically always be zero.

**Comment by zosrothko** [comment]
ok.. the libversion of Poco 1.6.2 is 31 right now...

**Comment by obiltschnig** [comment]
Will be changed before release. 1.6.2 has not been released yet.

**Comment by aleks-f** [comment]
I never paid much attention to lib version numbers because they are not intuitive, but I was thinking perhaps it would make sense to align them with releases, e.g. 1.6.2 would be 162 and 1.7.0 would be 170.

Any reason not to do that, especially since we are not doing the p* releases anymore?

**Comment by zosrothko** [comment]
IMHO, because under Linux, the convention is to have a major and minor version for shared library as explain here : http://l4u-00.jinr.ru/usoft/WWW/HOWTO/GCC-HOWTO-6.html
Executive summary: supposing that you observe the tradition that major upgrades may break compatibility, minor upgrades may not, then link with

    gcc -shared -Wl,-soname,libfoo.so.major -o libfoo.so.major.minor

Thus the libversion exists because it is supposed to be only 2 digits while the Poco tag is 3 digits..

Just my 2 cts...

**Comment by zosrothko** [comment]
Followup
It appears that the "-" connector for naming a shared library build with CMake on Cygwin is a builtin feature of CMake. Since the *dll and *dll.a objects produced by the standard make and CMake should be identical, it results that for the Zip shared library, the names will be

on Windows: PocoZip.dll
on Linux/Unix: libPocoZip.so.40 with a link from libPocoZip.so ==> libPocoZip.so.40
on Cygwin cygPocoZip-40.dll and libPocoZip-40.dll.a with a link from libPocoZip.dll.a ==>libPocoZip-40.dll.a 
on Cygwin/CMake cygPocoZip-40.dll and libPocoZip.dll.a

upcoming reworking would make CMake Cygwin objects identical  as gnu make objects.

By the way, I am wondering why Poco dlls on Windows do not include the libversion number even if this information is already in the rc file. And also why there is no installation of Windows Poco dlls in Windows/system32 as there is a install of Poco in /usr/local on Linux?
