### ISSUE TITLE
Crypto (and NetSSL) failing on Mac OSX (10.10.5) with XCode 7 (7A220)

### ISSUE THREAD

**Issue by intensifi** [pocoproject/poco#951]
Both gmake and CMake builds are failing for the crypto module.

Error received during gmake (./configure --config=Darwin64-clang)

In file included from src/CipherFactory.cpp:19:
In file included from include/Poco/Crypto/CipherKey.h:24:
In file included from include/Poco/Crypto/CipherKeyImpl.h:24:
include/Poco/Crypto/OpenSSLInitializer.h:26:10: fatal error: 'openssl/crypto.h'
      file not found
#include <openssl/crypto.h

From CMake

Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_INCLUDE_DIR) 

"which openssl" returns:

/usr/bin/openssl

"openssl --version" returns:

OpenSSL 0.9.8zg 14 July 2015

Apple deprecated openssl a while back.  The recommend change was to use their common crypto library.  I found the following man page:

man CC_crypto

The openssl header files ARE NOT in the normal usr/include/ MacOSX10.11.sdk location.  They are in the Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include directory.  However this does not appear to be in the normal search path.

Any ideas how to proceed?

**Comment by intensifi** [comment]
per a suggestion from Alex I acquired a distribution of open ssl (actually built 0.9.8zg from source) and 

1) ran Poco configure as follows:

./configure --config=Darwin64-clang --omit=Data/MySQL,Data/ODBC --include-path=/usr/local/ssl/include --library-path=/usr/local/ssl/lib

2) ran CMake specifying 

OPENSSL_INCLUDE_DIR
OPENSSL_CRYPTO_LIBRARY
OPENSSL_SSL_LIBRARY

and everything built fine.

It looks like an update to the Readme file in the OpenSSL for Mac OS X section is in due.

**Comment by matejk** [comment]
On of the options is to use LibreSSL.

I downloaded version 2.3.0 and compiled it with clang that comes with XCode 7.

Poco was built successfully with cmake then:

```
export OPENSSL_ROOT_DIR=<path to where LibreSSL is installed>
cmake ../poco-1.7.0
```
