### ISSUE TITLE
Poco::Process::launch can't start process with very long filename on Windows

### ISSUE THREAD

**Issue by eugeneseppel** [pocoproject/poco#955]
It's impossible to start process with very long filename, for example
\?\c:\tmp\1\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiplwbhsoceofpnddblwfnufopisawwjwicmjjpbykplsaklrwyefdlugvuokvbspwlqdyjxomvmbyqadszivlbxxwiumzximbwsqsqvdpxhmjsplxcjcpplppywciumqyeatwtuqwjjyeddxtmvoamxbjisplxyagoutdemvvzjdvefuwbcahuslbibamvqzwdxxptqyxmbdljlajbjjqsimqfl\BBBBBBBBBBBBBBBBBBBBBBBBBBBBgylpxtafbkcefofedvogrtndbbuisjbysjgtcetupghoyrcfjivawstqwqiyfibsqnjsgymjhoufswiksuidkvlbtmjwxqsglstajuhkphefrrfvjulpmuutvfkolaaqgmunhjktwpfghfydtwmzfsrhpupjkdokhghvmtobpfkvvhouiztkggdsptptusxntgxvseouuphnzhewhbfbycgkfbmibofnxbl\gylpxtafbkcefofedvogrtndbbuisjbysjgtcetupghoyrcfjivawstqwqiyfibsqnjsgymjhoufswiksuidkvlbtmjwxqsglstajuhkphefrrfvjulpmuutvfkolaaqgmunhjktwpfghfydtwmzfsrhpupjkdokhghvmtobpfkvvhouiztkggdsptptusxntgxvseouuphnzhewhbfbycgkfbmiYYYYYYY.exe
WinAPI call ::CreateProcessW executes such process unhindered. Of course process executable should be able to be start with such long path, for instance simple C++ HelloWorld.

**Comment by eugeneseppel** [comment]
Why closed?

**Comment by obiltschnig** [comment]
https://twitter.com/obiltschnig/status/1122484561747771392?s=20
