### ISSUE TITLE
Create CMake README file similar to Gmake file

### ISSUE THREAD

**Issue by intensifi** [pocoproject/poco#956]
Under doc 99150-GMakeBuildNotes.page exists. 

I'd like to see one for CMake as well.

**Comment by bachp** [comment]
Currently we only have https://github.com/pocoproject/poco/blob/develop/cmake/README for CMake.

What exactly would you expect from such a document?
- All the options documented?
- Step by step guide?
- ...?

**Comment by aleks-f** [comment]
@intensifi wanted to add some comments in regards to PostgreSQL build. Perhaps updating the README would be a good start.

**Comment by obiltschnig** [comment]
Yes, updating cmake/README would be a good start. Then, create something like doc/99150-GMakeBuildNotes.page (call it doc/99150-CMakeBuildNotes.page), describing the contents of the cmake directory, how to include POCO in another cmake-based project, how to write CMakeLists.txt files, and document the available options.
The steps to build POCO with cmake could also be added to doc/00200-GettingStarted.page.

**Comment by aleks-f** [comment]
It is already in GettingStarted: https://github.com/pocoproject/poco/blob/develop/doc/00200-GettingStarted.page#L306

**Comment by obiltschnig** [comment]
Cool. Obviously, I don't read the GettingStarted doc too often anymore... ;-)

**Comment by intensifi** [comment]
What I was looking for was something/everything to put CMake at an even footing with GMake.  I'd like to also see a section in each file for module/adapter specific issues & required settings.  For example with the PostgreSQL CMake "Find.cmake" file I can't (maybe my ignorance) craft a find_library section that will work successfully on MacOSX, Linux and Windows.  So I made it work properly on Linux.  MacOSX and Windows users will need to update the default configuration CMake creates.  I just wanted a place where everyone knows to look for module/adapter specific build issues/caveats.

There is the top level Readme file.  However I don't recall any CMake info there.  It only includes how to omit certain database adapters, not how to build them successfully per platform.  Additionally the doc directory contains similar info.  Finally the doc web pages that get created will need to be updated.
