### ISSUE TITLE
Deliver Poco/CppUnit as a component

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#957]
Hi

I think it would be useful to deliver Poco/CppUnit as a component of Poco. In my own application using Poco, the unit tests are build using Poco/CppUnit but it is not delivered/released.

If it is agreed to deliver/release Poco/CppUnit, I will make the changes.

**Comment by aleks-f** [comment]
Is this a new library or modification of the existing CppUnit library?

**Comment by zosrothko** [comment]
It is about the existing Poco/CppUnit which is not delivered/installed 
by the Makefile

Le 30/09/2015 14:53, Aleksandar Fabijanic a écrit :
>
> Is this a new library or modification of the existing CppUnit library?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pocoproject/poco/issues/957#issuecomment-144386915>.
>


This email has been protected by YAC (Yet Another Cleaner) http://www.yac.mx

**Comment by aleks-f** [comment]
ah, that. I'll leave that to @obiltschnig

**Comment by obiltschnig** [comment]
If we do install CppUnit with make install, this should be optional, e.g.
  make install INSTALL_CPPUNIT=1
to avoid potential conflicts with other libcppunit versions.

**Comment by zosrothko** [comment]
and what about renaming CppUnit to PocoCppUnit? The CppUnit lib is quite out of date for Windows( From the INSTALL-WIN32.txt, "the only supported WIN32 platform is Microsoft Visual C++. You must have VC++ 6.0 at least"). Moreover IMO, it does not work with VS Express editions.  

Delivering PocoCppUnit could bring a uniform portability  of a unit testing framework on all supported platforms of Poco itself, letting the end user to switch to CppUnit if he needs extra functionnalities.

**Comment by zosrothko** [comment]
Gunter, do you agree with renaming the CppUnit shared library to PocoCppUnit as others Poco's component?

**Comment by Z223I** [comment]
@obiltschnig 

My novice Makefile brain tells me that the Makefile was not updated for your suggested:
make install INSTALL_CPPUNIT=l

So, how do I install cppunit on Linux?

I have done:
make CppUnit-clean
and it seems to run just fine.
