### ISSUE TITLE
CMake: RelWithDebInfo must not add the "d" postfix

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#959]
Hi

In the DefinePlatformSpecifc.cmake, the "d" postfix is added for the target RelWithDebInfo. Since RelWithDebugInfo is using -DNDEBUG and not -D_DEBUG, this leads to a contradictory naming suffix with SharedLibrary::suffix(). Thus the "d" postfix for RelWithDebInfo should be removed.

set(CMAKE_RELWITHDEBINFO_POSTFIX "${STATIC_POSTFIX}d" CACHE STRING "Set RelWithDebInfo library postfix" FORCE)

set(CMAKE_RELWITHDEBINFO_POSTFIX "d" CACHE STRING "Set RelWithDebInfo library postfix" FORCE)

**Comment by obiltschnig** [comment]
Correct, release with debug info should not use the "d" suffix.

**Comment by bachp** [comment]
I agree this should be changed.
