### ISSUE TITLE
CMake: remove unecessary defines POCO_OS_XXX

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#960]
Hi

In DefinePlatformSpecifc.cmake are explicitly defined POCO_OS_XXX. Those are unecessary and should be removed since it makes a strong dependency between the DefinePlatformSpecifc.cmake and the Foundation code.

It is the same issue for other defines like DPOCO_HAVE_FD_EPOLL, DPOCO_HAVE_FD_POLL

**Comment by bachp** [comment]
I think you are right. The POCO_OS_* defines should be set by Platform.h and not by the build system?
@obiltschnig Is this assumption correct?

If yes they should be removed from DefinePlatformSpecifc.cmake.

**Comment by obiltschnig** [comment]
Yes, POCO_OS_* will be set by Poco/Platform.h header.
