### ISSUE TITLE
Can't get error response from HTTPServer

### ISSUE THREAD

**Issue by tomaz-beltram** [pocoproject/poco#962]
I want to avoid the reading of the PUT request body stream if some error condition is detected on the server (e.g. wrong URI). Therefore my HTTPRequestHandler::handleRequest() method immediately returns with HTTP error.

    if (request.getURI() != "/") {
        response.setStatus(HTTPServerResponse::HTTP_NOT_ACCEPTABLE);
        response.setReason("Wrong request");
        (void)response.send();
    }
    else {
        // read request.stream() and return HTTP_OK
        std::istream& is = request.stream();
        std::stringstream out;
        out << is.rdbuf();
        ...

This causes problems to the HTTPClientSession, specifically to the ostream << operator that the client uses for sending request body. 

    const std::string inputStr(200000, 'x');
    HTTPRequest request(HTTPRequest::HTTP_GET, "/err", HTTPMessage::HTTP_1_1);

    std::ostream& os = session.sendRequest(request);
    std::stringstream is(inputStr);
    os << is.rdbuf(); // causes exception or crash

On Linux the stream fail bit is set and I have to reset the session, loosing the error response sent from the server. On Windows I even get access violation and program crash.

I don't know the transport details of HTTP but is it possible to achieve such a thing as sending error response before receiving complete request?

**Comment by matejk** [comment]
Does using keep-alive or not make any difference?

**Comment by tomaz-beltram** [comment]
It looks to me that with keep-alive disabled the problem happens more frequently. The sample client and server sources that I used to reproduce this issue are here https://gist.github.com/tomaz-beltram/82aea8fabe4d4aaadaf7.

**Comment by matejk** [comment]
According to the description of HTTP 1.1 the server shall be allowed to respond with error after reading the header as described [HTTP Made Really Easy](https://www.jmarshall.com/easy/http/#http1.1s5):

> When an HTTP 1.1 server receives the first line of an HTTP 1.1 (or later) request,
> it must respond with either "100 Continue" or an error.

Another article describing this situation: a client can use "Expect: 100-continue" and the server can response with either "100 Continue" or an error: https://benramsey.com/blog/2008/04/http-status-100-continue/

The server shall not just close the connection as far as I was able to determine from these articles.

**Comment by obiltschnig** [comment]
The latest code in the develop branch has a new HTTPClientSession::peekResponse() method that can be used to check for a 100 Continue response. Furthermore, HTTPRequest has a new setExpectContinue() method. On the server side, in your HTTPRequestHandlerFactory::createRequestHandler() method, you can set the response status (request.response().setStatus()) to something other than 200 to prevent the default 100 Continue response from being sent.

**Comment by tomaz-beltram** [comment]
I have tried the peekResponse() and it works as described. Thanks for pointing this out.

However I noticed that it only works if response status is set from the HTTPRequestHandlerFactory but not when set from the HTTPRequestHandler.

**Comment by thorsten-ottosen** [comment]
In case anyone tries to debug this, then here's a solution:

Call response.setStatusAndReason() before response.send().
