### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#964]
Having HTTP/2 support in the POCO Net library would be nice, now that the protocol has been finalized.

**Comment by mkrivos** [comment]
Interesting, do you have some ideas about implementation / integration into existing http implementation?

**Comment by obiltschnig** [comment]
The APIs should be largely compatible to the existing ones, e.g., based on HTTPRequest/HTTPResponse. There'll be a HTTP2ClientSession and a HTTP2Server class probably. Haven't looked that deeply into the specification yet, so we'll have to see how far we get with the existing classes and interfaces.

**Comment by JiekeZhu** [comment]
I'm trying to build a provider for Apple Push Notification Service (APNs). But the latest APNs API use HTTP/2. So I wonder whether POCO has already has implemented this feature. 👍
