### ISSUE TITLE
Compile error using XCode 7.0.1 on Mac OSX 10.11

### ISSUE THREAD

**Issue by intensifi** [pocoproject/poco#965]
Hello,

From the command line I can build a Poco based executable just fine using Poco's builtin build system.

My source directory is outside of POCO_BASE.  So I set the POCO_BASE and PROJECT_BASE environment variables and all is well. (Actually I did have to remove config.make from POCO_BASE because it sets POCO_BUILD which overrides where to put OBJs and EXEs - I Believe this to be a bug in the Poco Build system.)

Back to the main problem.

When I create an "external build system" project in Xcode and properly set POCO_BASE and PROJECT_BASE, I cannot compile my code.  I receive the following error on an inclusion of <iostream>.

---

In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:37:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:23:10: fatal error: 'unistd.h' file not found
# include <unistd.h>

```
     ^
```
## 1 error generated.

XCode generates a ton of environment variables and passes them to the shell where make runs.  I'm thinking that might be part of the problem  

Any ideas?

I'd like to stick with the external makefiles.

**Comment by aleks-f** [comment]
I'm not an Xcode expert, but you may have an [SDK mix](https://forum.qt.io/topic/58926/solved-xcode-7-and-qt-error/3)

**Comment by intensifi** [comment]
Thanks!

I'll give it a try!

Best regards,

===
Jeff Adams
