### ISSUE TITLE
Poco::File::renameTo() behaviour differs on windows and linux

### ISSUE THREAD

**Issue by hadzim** [pocoproject/poco#969]
If move destination file exists, it is overwritten on linux, but on windows throws exception.

Moreover, the windows exception message is little bit confusing in this case:

"File exists: [SOURCE_FILE_NAME]"

instead of 

"File exists: [DESTINATION_FILE_NAME]"

**Comment by aaboyd** [comment]
This should be fairly easy to fix, I'm not exactly sure what the desired behaviour should be.  The implementations for Windows just needs to use ```MoveFileExA``` with a flag to overwrite.

The error message is a function that handles all of the error messages for file operations and it gets passed the ```_path``` to add into the message, but in this case the ```_path``` isn't what was causing the problems it was the destination.  I agree the error message is ugly.

**Comment by obiltschnig** [comment]
Since it's easy to change the Windows behavior to match that of POSIX, I'd say go with that.
