### ISSUE TITLE
Inserting date to MongoDB

### ISSUE THREAD

**Issue by manthanrtilva** [pocoproject/poco#971]
Hi When I am trying to insert current time to MongoDB it is inserted as string instead of MongoDate type. I want to use ttl functionality of MongoDB to remove older data. for that date-time must be stored in MongoDate type object. Can you guide some work around to this or how can I add support for MongoDate object in Poco's MongoDB api.

**Comment by fbraem** [comment]
The BSON spec says to store a date as "UTC datetime - The int64 is UTC milliseconds since the Unix epoch". So in POCO this is implemented using the Timestamp class.

**Comment by manthanrtilva** [comment]
Hi Fbraem, Thanks for reply. I root cause of issue. Before inserting toString method is get called, so MongoDate object is not get created.
