### ISSUE TITLE
Can't build Net for iPhone (arm64, armv7, or armv6)

### ISSUE THREAD

**Issue by syedhali** [pocoproject/poco#981]
Hey, thank you so much for the amazing Poco! I was able to build for OSX and the iPhone Simulator, but haven't been able to get any of the iPhone architectures to compile with the Net library. 

```
src/NetworkInterface.cpp:1349:10: fatal error: 'net/if_types.h' file not found
#include <net/if_types.h>
         ^
1 error generated.
```

If the if_types file is not defined does mean the iPhone is not supported?

**Comment by aaboyd** [comment]
I currently build for iOS and everything works fine for me.  I use the cmake build though.   I can't explain exactly what is going on here, but I can confirm that it works on iOS

**Comment by aleks-f** [comment]
It is not clear how or what version are you building. Missing if_types.h only mean a less precise network interface detection, see response [here](http://stackoverflow.com/questions/30087994/what-is-poco-no-net-iftypes-used-for).

**Comment by syedhali** [comment]
I'm using the 1.6.1 release. I actually just tried again using the clange-libc++ config and it worked perfectly, though I needed to install xcode command line tools first (thought I already had them installed).

## What worked for me:
1.) Make sure Xcode command line tools are installed:

```
xcode-select --install
```
2.) Config (I'm just using the Foundation and Net classes, targeting arm64, armv7, and armv7s devices with a minimum iOS version of 8.0):

```
./configure --config=iPhone-clang-libc++ --no-tests --no-samples --static --omit=Data/MySQL,Data/ODBC,Zip,JSON,Util,XML --cflags="-arch arm64 -arch armv7 -arch armv7s -miphoneos-version-min=8.0"
```
3.) Run:

```
make -s -j4
```

Thank you guys again for all your hard work! These libraries are amazing.
