### ISSUE TITLE
Can't get interface type properly from Net::NetworkInterface 

### ISSUE THREAD

**Issue by ideatuples** [pocoproject/poco#984]
Hi.. 

When I was writing some codes with Socket::NetworkInterface class, I found that there is something strange.

Socket::NetworkInterface has a method type() which detects network interface type like (ethernet, 802.11 or something else)

Unfortunately, however, it was not working. The class can't distinguish between ethernet and wireless LAN. 

In my cases, Socket::NetworkInterface recognised wireless interface as ethernet interface.

It was tested under the environment as below.

OS: Ubuntu 14.04 LTS (AMD64)
Compiler: G++ 4.8.4 with C++11
Wired NIC: Realtek RTL8101E/RTL8102E (rev 07) \* I usually shut it down
Wireless NIC: Intel Centrino Wireless-N 2230 (rev c4) 

If there is something that I don't understand properly, please let me know.

Thank you.

**Comment by aleks-f** [comment]
Unless you are seeing `NetworkInterface::NI_TYPE_OTHER`, which would mean a type not handled by POCO, you are getting whatever your platform's `getifaddrs()` says it is. See [here](https://github.com/pocoproject/poco/blob/develop/Net/src/NetworkInterface.cpp#L1601), [here](https://github.com/pocoproject/poco/blob/develop/Net/src/NetworkInterface.cpp#L1562) and [here](https://github.com/pocoproject/poco/blob/develop/Net/src/NetworkInterface.cpp#L978).

If you find something wrong with the detection logic, let us know and we'll fix it.

**Comment by ideatuples** [comment]
Thank you for your reply and I read your comments carefully, but there is something else.

You told that Network::Interface is based on 'getifaddrs()', didn't you?
However, I found out that 'getifaddrs()' doesn't help detect Network Interface Type.

As you know, 'getifaddrs()' is a function to bring network information with struct 'ifaddrs'. 
No matter how it works internally, what we have to focus on is 'ifa_flags' in struct 'ifaddrs'.

According to man page (exactly, linux.die.net), 'ifa_flags' is strongly associated with 'SIOCGIFFLAGS' operation of 'ioctl()'.

Unfortunately, I think that 'ifa_flags' has only limited information about network interface. We can find out each flag for 'ifa_flags' in '/usr/include/net/if.h' but I couldn't find any flag for wireless.

Consequently, using 'getifaddrs()' is not eligible for this, I think.

If I made a mistake or misunderstood, please let me know.

Thank you

**Comment by aleks-f** [comment]
It's what we currently have. Open source is about sharing code, finding problems and proposing solutions (optimally in the form of code). Perhaps there exists a solution to your problem but I haven't seen it in this discussion so far. I hope you don't expect us to invest our time investigating your problem - if you have a concrete proposal, one of the type "let's do it like this" (as opposed to "that's not how it's done"), we'll be glad to hear it.

**Comment by ideatuples** [comment]
It seems that you misunderstand about what my intention is. 

I don't want you to spend your time to investigate for this and also it DOESN'T mean you should fix this.

My intention for this issue is just to LET YOU KNOW WHAT IS HAPPENING ON THE CODES.

**Comment by aleks-f** [comment]
Since I wrote the code, I already knew what's happening. Thanks for your help, though.
