### ISSUE TITLE
POCO_UNBUNDLE: compile error on RegularExpression.cpp

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#986]
Hi

When building Poco without the bundling of pcre and zlib with #define POCO_UNBUNDLED  1, one gets a compiling error on RegularExpression.cpp as below. The problem is coming from a divergente definition of typedef .. pcre; in RegularExpression.h bewteen the Poco/src/pcre.h and the system /usr/include/pcre.h

extern "C"
{
    struct real_pcre8_or_16;                 /\* declaration; the definition is private  */
    typedef struct real_pcre8_or_16 pcre;
    struct pcre_extra;
}

g++  -Iinclude -I/home/fandre/pocozos/CppUnit/include -I/home/fandre/pocozos/CppUnit/WinTestRunner/include -I/home/fandre/pocozos/Foundation/include -I/home/fandre/pocozos/XML/include -I/home/fandre/pocozos/JSON/include -I/home/fandre/pocozos/Util/include -I/home/fandre/pocozos/Net/include -I/home/fandre/pocozos/Crypto/include -I/home/fandre/pocozos/NetSSL_OpenSSL/include -I/home/fandre/pocozos/NetSSL_Win/include -I/home/fandre/pocozos/Data/include -I/home/fandre/pocozos/Data/SQLite/include -I/home/fandre/pocozos/Data/ODBC/include -I/home/fandre/pocozos/Data/MySQL/include -I/home/fandre/pocozos/Zip/include -I/home/fandre/pocozos/PageCompiler/include -I/home/fandre/pocozos/PageCompiler/File2Page/include -I/home/fandre/pocozos/PDF/include -I/home/fandre/pocozos/CppParser/include -I/home/fandre/pocozos/MongoDB/include -I/home/fandre/pocozos/PocoDoc/include -I/home/fandre/pocozos/ProGen/include -Wall -Wno-sign-compare -DPOCO_BUILD_HOST=obelix  -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -c src/RegularExpression.cpp -o /home/fandre/pocozos/Foundation/obj/Linux/x86_64/debug_shared/RegularExpression.o
In file included from src/RegularExpression.cpp:21:0:
/usr/include/pcre.h:325:26: erreur: conflicting declaration ‘typedef struct real_pcre pcre’
 typedef struct real_pcre pcre;
                          ^
In file included from src/RegularExpression.cpp:17:0:
include/Poco/RegularExpression.h:38:34: note: previous declaration as ‘typedef struct real_pcre8_or_16 pcre’
  typedef struct real_pcre8_or_16 pcre;

**Comment by bachp** [comment]
It look like POCO_UNBUNDLED (the compiler variable) is never set by CMake.
Can you verify for me if you add `add_definitions(-DPOCO_UNBUNDLED)` somewhere in you CMakeLists.txt if it works?

If yes we need to add a section like this

```
if(POCO_UNBUNDLED)
    add_definitions(-DPOCO_UNBUNDLED)
endif()
```

somewhere.

**Comment by zosrothko** [comment]
I will check for CMake, but the issue is valid for the standard Makefile

**Comment by Arandhras** [comment]
Hi, I have the same issue when trying to compile Poco 1.6.1 statically with CMake.

The command lines I have used to configure the required dependencies are as follows (of course $PREFIX_PATH is set to the directory where I want to install the libraries):
* **openSSL-1.0.1p**: `./configure --prefix=$PREFIX_PATH --disable-shared --enable-pcre16 --enable-pcre32 --enable-utf8 --enable-jit --enable-unicode-properties`
* **pcre-8.37**: `./configure --prefix=$PREFIX_PATH --disable-shared --enable-pcre16 --enable-pcre32 --enable-utf8 --enable-jit --enable-unicode-properties`
* **zlib-1.2.8**: `./configure --prefix=$PREFIX_PATH --static`

And these are the commands I used to configure Poco:
```mkdir build-dir && cd build-dir
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX_PATH -DPOCO_STATIC=ON -DENABLE_MONGODB=OFF -DENABLE_PAGECOMPILER=OFF -DENABLE_PAGECOMPILER_FILE2PAGE=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_SQLITE=OFF -DENABLE_DATA=OFF -DENABLE_CRYPTO=ON -DENABLE_NETSSL=ON -DENABLE_ZIP=OFF -DENABLE_XML=OFF -DPOCO_UNBUNDLED=ON```
