### ISSUE TITLE
CMake: define constants inconsistents with those of the standard build using GNU make

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#987]
Hi

IMO, the constants defined in DefinePlatformSpecific. for the various platforms/OS/hardware should be aligned with those found in build/config/\* files. For example, for QNX, one have
CMake: add_definitions( -D_XOPEN_SOURCE=500 -DPOCO_HAVE_FD_EPOLL)
confir/QNX: SYSFLAGS = -D_QNX_SOURCE

I would suggest to have a strict identical set of defines between CMake and GNU make by copying the defines found in config/\* into DefinePlatformSpecific

**Comment by bachp** [comment]
I agree they should be identical. Changes to clean up the DefinePlatformSpecific file are welcome

**Comment by zosrothko** [comment]
Hi Pascal
In the latest branch develop, the $POCO_BASE/build_cmake.cmd is now fixed and need one parameter to run : `Debug | Release`

There are a lot a configuration errors when building with jom. Can you have a look? (I am not a specialist of CMake)
