### ISSUE TITLE
CMake on Windows: build NetSSL_Win is missing

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#988]
Below the logof CMake.exe 3.3.2 on Win7

Z:\git\pocozos\cmake-build>"C:\Program Files (x86)\CMake\bin\cmake.exe" ..
-- Building for: Visual Studio 12 2013
-- The C compiler identification is MSVC 18.0.30723.0
-- The CXX compiler identification is MSVC 18.0.30723.0
-- Check for working C compiler using: Visual Studio 12 2013
-- Check for working C compiler using: Visual Studio 12 2013 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013
-- Check for working CXX compiler using: Visual Studio 12 2013 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Poco package version: 1.7.0
-- Found message compiler: C:/Program Files (x86)/Windows Kits/8.1/bin/x86/mc.exe
-- Building dynamic libraries
-- Building without tests & samples
-- Build with using internal copy of sqlite, libz, pcre, expat, ...
-- Found OpenSSL: optimized;C:/OpenSSL-Win32/lib/VC/ssleay32MD.lib;debug;C:/OpenSSL-Win32/lib/VC/ssleay32MDd.lib;optimized;C:/OpenSSL-Win32/
lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win32/lib/VC/libeay32MDd.lib (found version "1.0.1i")
-- Couldn't find MySQL
-- MySQL Support Disabled - no MySQL library
-- Found ODBC: C:/Program Files (x86)/Windows Kits/8.1/Include/um
-- Windows native ODBC Support Enabled
-- CMake 3.3.2 successfully configured Poco using Visual Studio 12 2013 generator
-- Installation target path: C:/Program Files (x86)/Poco
-- C_FLAGS:  = /DWIN32 /D_WINDOWS /W3
-- CMAKE_C_FLAGS_DEBUG:=/D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 -D_DEBUG
-- CMAKE_C_FLAGS_RELEASE:=/MD /O2 /Ob2 /D NDEBUG
-- CMAKE_C_FLAGS_MINSIZEREL:=/MD /O1 /Ob1 /D NDEBUG
-- CMAKE_C_FLAGS_RELWITHDEBINFO:=/MD /Zi /O2 /Ob1 /D NDEBUG
--
--
-- CXX_FLAGS:= /DWIN32 /D_WINDOWS /W3 /GR /EHsc
-- CMAKE_CXX_FLAGS_DEBUG:=/D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 -D_DEBUG
-- CMAKE_CXX_FLAGS_RELEASE:=/MD /O2 /Ob2 /D NDEBUG
-- CMAKE_CXX_FLAGS_MINSIZEREL:=/MD /O1 /Ob1 /D NDEBUG
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO:=/MD /Zi /O2 /Ob1 /D NDEBUG
-- Building: XML
-- Building: JSON
-- Building: MongoDB
-- Building: Util
-- Building: Net
-- Building: NetSSL_OpenSSL
-- Building: Crypto
-- Building: Data
-- Building: Zip
-- Building: PageCompiler
-- Building: File2Page
-- Configuring done
-- Generating done
-- Build files have been written to: Z:/git/pocozos/cmake-build

**Comment by bachp** [comment]
NetSSL_Win has to be explicitly enabled via: `-DENABLE_NETSSL_WIN=ON`.

Do you suggest this should be changed?
I'm also not sure if it conflicts with NetSSL_OpenSSL in some way.

**Comment by zosrothko** [comment]
on Windows, I think NetSSL_Win should be the default while NetSSL_OpenSSL be optional

**Comment by aleks-f** [comment]
Unless something has changed, they are not compatible - the code you write using OpenSSL will not compile with WinSSL. So, OpenSSL should remain default.

**Comment by zosrothko** [comment]
Ok this holds...
