### ISSUE TITLE
Potential race condition in `Poco::File` on Windows

### ISSUE THREAD

**Issue by quantumsteve** [pocoproject/poco#990]
I recently watched a [CppCon talk](https://youtu.be/uhRWMGBjlO8?t=455) where the speaker said that to delete a directory tree on Windows, one should first rename files to a random name in `%TEMP%`, then delete.

I noticed that [Poco::File::remove(bool recursive)](http://pocoproject.org/docs/Poco.File.html) is using the same algorithm on both UNIX and Windows. 

https://github.com/pocoproject/poco/blob/develop/Foundation/src/File.cpp#L262
https://github.com/pocoproject/poco/blob/develop/Foundation/src/File_UNIX.cpp#L368
https://github.com/pocoproject/poco/blob/develop/Foundation/src/File_WIN32.cpp#L305

The Windows algorithm should be changed to avoid this potential data race.

**Comment by obiltschnig** [comment]
Ah, the collection of special cases sold as operating system called Windows.
