### ISSUE TITLE
Using Poco::Process with already running processes

### ISSUE THREAD

**Issue by intensifi** [pocoproject/poco#992]
I have the pid of a running process.

It is a process I started on a previous application run using Process::launch().  On a subsequent application run I'd like to attach to the running process and send commands to its STDIN and monitor its STDOUT.

Any ideas?

**Comment by obiltschnig** [comment]
You cannot attach to stdin/stdout of another process unless you've launched it and set up proper redirection and have the respective file descriptors. 
What you could do is create a wrapper executable that provides a network service (TCPServer/HTTPServer REST API) for talking to that process.

**Comment by intensifi** [comment]
@obiltschnig 

I was thinking about that but felt it has a lot of overhead (code wise).

I thought another solution might be to create fifos and attach STDIN, STDOUT and STDERR to said fifos.  The fifos would be named via the PID of the launched process (and located under /var/run).  That way I could "re-attach" to the process at any time and perform IO.

Thoughts on this approach (besides being 'nix only)?
