### ISSUE TITLE
Invalid zip format when opening a docx in word

### ISSUE THREAD

**Issue by MrHat4242** [pocoproject/poco#993]
Hi,

I write a program to create docx files.
As a docx file is a zip file, I use Poco::Zip::Compress to create the file.

I work with Mac OS X, and I can open open the file with no problem in the application Pages.
But when I try to open it with Word 2013, I have an error message saying that the zip version is not supported by Word, but clicking "OK" it opens. I also tried to open it with Word Online but it does not open at all.

I tried to create a docx with the command zip and it works fine, I also run a unzip -t on my docx and there is no error in it.

Do you know anything about that, if it is an issue on the zip implementation of Poco ?

Thank you for your answer,

Regards

Edit: I commited a little test program here : https://github.com/MrHat4242/TestPocoZipDocx
It takes two arguments, the docx to unzip and the docx to create, you can try to run it and open the created docx in Word.

**Comment by minstral** [comment]
G'day,

We also have a report from an end user describing the issue. They have been in touch with support at PKWare and were informed that:

"The creating software is writing an incorrect value into the field that holds the value for the minimum “version needed to extract”. The value for this field in the ZIP file you provided is out of the documented range for this field which results in the problem you are experiencing."

regards,

Mark

**Comment by obiltschnig** [comment]
@minstral can you confirm that the Zip file was created on Linux or OS X?

The reason is that if you create a Zip file on a Unix-type system, Poco::Zip will set the "system type" field (that's part of the version needed header) to 3 - UNIX. Apparently, Word does not like this - it expects system type 0 - MS-DOS and OS/2 (FAT / VFAT / FAT32 file systems).

There's currently no API to set the system type. We'll probably need to provide a way to force the system type to 0.

**Comment by obiltschnig** [comment]
It seems safe to always set the system type field to zero. This is what both command-line Zip and the Finder's "Compress" feature do. Re-reading the Zip file format specification seems to confirm this. Host system type should only be set to non-zero if the file attribute information is not compatible with FAT.

**Comment by minstral** [comment]
Thanks, Günter.

It's created on OS X (we don't run under Linux).

**Comment by minstral** [comment]
We are advised that the fix has cleared the issue for the end user.

Many thanks.
