### ISSUE TITLE
Poco Logger change Message parameters

### ISSUE THREAD

**Issue by fabregaszy** [pocoproject/poco#995]
I'm using Poco::Logger to trace logs in my application.

Now I want to trace a value of a variable in all of my logs.  The value is not sure when the logger instance is created. Since I do not want to change every line where I output the line before. I want to make it something default in the format.

I checked the documents and tutorial of Poco logging system, and found:

>
+ A message can store an arbitrary number of name-value pairs. 
+ Names and values can be arbitrary strings. 
+ Message parameters can be referenced in a formatter.
>

which looks like exactly what I'm looking for. But I cannot found detailed information about this and it seems that Poco::logger creates a Poco::Message itself.

Is there any way to achieve what I want to do? Thanks.

**Comment by aleks-f** [comment]
Answered [here](http://stackoverflow.com/questions/33277881/poco-logger-change-message-parameters/33285316#33285316).
