### ISSUE TITLE
MySQL unregisterConnector slow

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#997]
I found that mysql_library_end, called in MySQL Connector::unregisterConnector it's quite slow: it takes seconds to execute. I found similar problem on internet related to miss call to mysql_thread_end where you use the mysql structures. In Poco lib code that function is called only in ThreadCleanupHelper compiled only for the POCO_OS_FAMILY_UNIX. Do you found this "slow" behavior too? does that call have to be done only on unix platforms or even in windows?

**Comment by intensifi** [comment]
I'll take a look.

**Comment by intensifi** [comment]
@micheleselea 

Are you having this problem in debug and release builds?

http://dev.mysql.com/doc/refman/5.7/en/mysql-thread-end.html

Which version of Windows?

Which version of MySQL?

Which version of Poco?

What happens when you build and run the Poco MySQL Testsuite?

I read the following documentation/comments which makes me think mysql_thread_end() should be called in the non UNIX code:

http://dev.mysql.com/doc/refman/5.7/en/mysql-thread-init.html

However I find this odd because @aleks-f is a Windows dev and since he originally wrote the new Poco::Data code I'd think he would have discovered this problem earlier.

**Comment by micheleselea** [comment]
I have the problem in release as well in debug mode.
I'm using Windows 10 but I experiment the problem from win7 and newer
I'm using the latest version of Poco 1.6.1
I found that it happens only when I use it in a Poco::Util::ServerApplication software. If I use it in a MFC Gui the problem seems not present.
I'm trying to undestand what happens...I'll try with the TestSuite even in a ServerApplication and I'll inform you..
From what the link says seems that in windows you should not explicit call thread_end()
Going into more debug...

**Comment by micheleselea** [comment]
Ok I think I know how to reproduce the problem (with test suite no problem)
If you create a Poco::Util::ServerApplication and in main() function you call

Poco::Data::MySQL::Connector::registerConnector();
do something
Poco::Data::MySQL::Connector::unregisterConnector();

the function is executed fast
If you do something like

int main(const std::vector<std::string>& args){
start main task with a Poco::TaskManager for example (so in another thread)
wait for task end
}

and the run() of the task do this

void run(){
Poco::Data::MySQL::Connector::registerConnector();
do something
Poco::Data::MySQL::Connector::unregisterConnector();
}

the unregisterConnector became slow. I don't think is a Poco problem, perhaps is the initialization of the mysql lib inside the non principal thread.
What do you think? I don't know if it's clear enough

**Comment by intensifi** [comment]
@micheleselea 

Which MySQL version?

How about running a test for me?

In your run() code, call mysql_thread_end() before Poco::Data::MySQL::Connector::unregisterConnector();

Let me know what happens.  If it is fast, then I think we need to update the Poco::MySQL code.

I'm also interested in knowing if this happens in Win7 and Win10 or just Win10.

**Comment by micheleselea** [comment]
I'm using the latest dll client from MySQL 6.1.6
I already done the test you speak about (mysql_thread_end())but the result is the same.
I found this behavior from Windows XP if I remember well, anyway from Win7 for sure
